fedimint/fedimint

README.md

typo 'ons'

---

mint-client/src/api.rs
mint-client/src/mint/mod.rs

suggested in https://github.com/fedimint/minimint/pull/39#pullrequestreview-887367406

Remove FederationApiExt

---

.github/workflows/rust.yml
minimint/src/transaction.rs
modules/minimint-ln/src/contracts/incoming.rs
modules/minimint-mint/src/lib.rs

Docs fixes

---

mint-client/src/wallet/mod.rs
modules/minimint-wallet/src/bitcoind.rs
modules/minimint-wallet/src/db.rs
modules/minimint-wallet/src/lib.rs
modules/minimint-wallet/src/tweakable.rs

One of the truly reckless corners cut was not dealing with change properly so far, this PR fixes that. THAT'S NOT THE ONLY FOOTGUN, STILL NOT SAFE TO RUN ON MAINNET!!!!

wallet: Recognize change UTXOs

---

.github/workflows/rust.yml

ci: cache deps for faster builds

---

Cargo.lock
ln-gateway/Cargo.toml
mint-client/Cargo.toml
modules/minimint-ln/Cargo.toml

Bump lightning

---

.github/workflows/docs.yml

See sample output at https://maan2003.github.io/minimint/

CI: Publish docs to gh pages

---

.github/workflows/rust.yml

1] Masked `Swatinem/rust-cache@v1` as its not being used as of now. 
2] Removed `jq` as it already exists in nix-shell

Cleaning up yaml file 

---

ln-gateway/src/bin/ln_gateway.rs
ln-gateway/src/lib.rs
ln-gateway/src/ln.rs
minimint/src/consensus/mod.rs
minimint/src/lib.rs
minimint/src/net/api.rs
minimint/src/net/connect.rs
mint-client/src/main.rs
mint-client/src/mint/mod.rs
mint-client/src/wallet/mod.rs
modules/minimint-ln/src/lib.rs
modules/minimint-mint/src/lib.rs
modules/minimint-wallet/src/bitcoind.rs
modules/minimint-wallet/src/lib.rs

Structured logging

---

ln-gateway/src/lib.rs

fix(tracing): use display for error

---

.github/workflows/rust.yml
Cargo.lock
minimint-api/Cargo.toml

Ensure that no one breaks the crates that already compile on wasm

ci: add check for wasm

---

.github/workflows/rust.yml

Masking action-rs/toochain as we are using nix to install rust 

---

Cargo.lock
minimint-api/Cargo.toml
minimint/Cargo.toml
mint-client/Cargo.toml
modules/minimint-mint/Cargo.toml
shell.nix

This might help fix some errors in nix-builds

Updating the links to rust-secp256k1-zkp repo

---

minimint-api/src/db/mod.rs

`DbIter` is not needed. We can just use `map`!

cleanup: remove DbIter, use iterator helpers

---

.github/workflows/rust.yml
crypto/tbs/src/lib.rs
minimint-api/src/encoding/secp256k1.rs
minimint/src/consensus/mod.rs
minimint/tests/fixture/fake.rs
minimint/tests/fixture/mod.rs
minimint/tests/fixture/real.rs
modules/minimint-mint/src/lib.rs
scripts/final-checks.sh

I got the `cargo clippy +nightly` to pass, adding that command to `scripts/final-check.sh`
Also updated the GH actions to include `clippy --lib --bins --tests --examples --workspace -- -D warnings`

Fix clippy checks for some files

---

scripts/integrationtest.sh

Seemed like CI doesn't have a loaded bitcoind wallet: https://github.com/fedimint/minimint/pull/125
This should fix it

Ensure bitcoind wallet loaded in integrationtests.sh

---

.github/workflows/linkcheck.yml

Humans are bad a this, let the machine do it!

CI: Check markdown links

---

minimint/src/net/connect.rs

This error does not appear currently for unclear reasons, but is triggered by the new framed transport logic (that may just report closed connections sooner/at all).

Fix spurious error in `drop_peers_who_contribute_bad_sigs`

---

.github/workflows/rust.yml
default.nix

* remove CI redundancy
* Nix build: build right commit

Remove CI redundancy and fix bug

---

Cargo.lock
integrationtests/tests/fixtures/mod.rs
minimint/Cargo.toml
minimint/src/config.rs
minimint/src/lib.rs
minimint/src/net/api.rs
minimint/src/net/connect.rs
minimint/src/net/framed.rs
minimint/src/net/mod.rs
minimint/src/net/peers.rs
minimint/src/net/queue.rs

Make the network stack robust so that federations can survive network disruptions

---

.github/workflows/rust.yml

actions: run cachix only on fedimint/minimint

---

integrationtests/tests/tests.rs

I had previously added unnecesary epochs in these tests because I misunderstand how coins were fetched. Because coins didn't show up in balances as expected, I assumed that we needed to wait a few more epochs. But waiting for more epochs was actually just giving `background_fetch` time to run again. Perhaps we should consider having an option to disable `background_fetch` in testing because it is a little conceptually confusing.
This PR addresses [this comment](https://github.com/fedimint/minimint/pull/175#discussion_r906656696). To re-iterate, this has nothing to do with #171. Preimage decryption always took 1 epoch. I tested this commit on a branch of master before #171 was merged and tests passed.
Also, perhaps we should add a `UserTest.assert_balance(<amount>)` helper method which …

Remove unnecessary consensus rounds from ln receive tests

---

shell.nix

use bitcoind instead of bitcoin since we don't want GUI

---

minimint/src/consensus/mod.rs
minimint/src/net/api.rs

Add server side API interface 

---

README.md
scripts/build.sh

Big update of the README
- Replaced Telegram with Discord (are we sure about the replacement of Telegram entirely?)
- Simplified the build/run instructions, tested on a fresh version of Linux

update the README.md

---

minimint/src/net/api.rs
minimint/src/net/connect.rs
minimint/src/net/framed.rs
minimint/src/net/peers.rs

Refactor `PeerConnection` state machine into enum

---

Cargo.lock
Cargo.toml
client/cli/Cargo.toml
client/cli/src/bin/mint-rpc-client.rs
client/cli/src/main.rs
client/client-lib/Cargo.toml
client/client-lib/src/api.rs
client/client-lib/src/clients/gateway.rs
client/client-lib/src/clients/user.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
ln-gateway/src/lib.rs
minimint-api/Cargo.toml
minimint-api/src/module/interconnect.rs
minimint-api/src/module/mod.rs
minimint-api/src/module/testing.rs
minimint/Cargo.toml
minimint/src/config.rs
minimint/src/consensus/interconnect.rs
minimint/src/net/api.rs
modules/minimint-ln/Cargo.toml
modules/minimint-ln/src/lib.rs
modules/minimint-wallet/src/lib.rs
scripts/build.sh
scripts/pegin.sh
scripts/start-fed.sh

Use jsonrpc over Web Sockets for client -> federation commutation.
resolve #152

Web Sockets

---

Cargo.lock
client/client-lib/Cargo.toml
client/client-lib/src/api.rs
integrationtests/tests/fixtures/mod.rs
minimint-api/Cargo.toml
minimint-api/src/task.rs
scripts/start-fed.sh

web sockets: reconnect on disconnect

---

docs/lifecycle.md

Copying over [this file](https://github.com/fedimint/minimint/wiki/The-life-of-a-Transaction) from the wiki to the `docs/` folder

Add lifecycle.md

---

scripts/setup-tests.sh

Tested it works on both `lightningd` builds, fixes #251

setup-tests.sh shouldn't assume dev build of lightningd

---

client/client-lib/src/clients/gateway.rs
client/client-lib/src/mint/mod.rs

Need this change for rest clientd and the refactor fetch [PR](https://github.com/NicolaLS/minimint/commit/d7256c97f4cee1123c5207e69a22fddb9dc4f83c) needs some debugging so will take some time (concurrent fetching causes the federation api to timeout)

also return CoinFinalization data in list_active_issuances

---

scripts/build.sh
scripts/start-fed.sh

fix server pids not beeing captured

---

client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
integrationtests/tests/fixtures/mod.rs
ln-gateway/src/lib.rs

I thought it was a problem with the code but it seems like the problem was with CI so I'm opening this one again

concurrent fetch_all_coins and some refactoring

---

client/client-lib/src/api.rs

This is exposing too many failures that CI is no longer useful. Nearly every run on master is failing.
related: https://github.com/fedimint/minimint/issues/222#issuecomment-1185700280
Reverts fedimint/minimint#208

Revert "client: make requests to federation members concurrent"

---

integrationtests/tests/tests.rs
modules/minimint-mint/src/lib.rs

Fixes #198, peers will now save a mint issuance so long as it's valid even if they didn't contribute to consensus.
I wasn't able to recreate a failure other than the logging issue.

save valid issuances without our own contribution

---

Cargo.lock
integrationtests/tests/fixtures/mod.rs
minimint/Cargo.toml
minimint/src/config.rs
minimint/src/lib.rs
minimint/src/net/connect.rs
minimint/src/net/peers.rs

More work towards #15, leaving out Tor for now but implementing secure communications for public network usage.
TODO:
`PKCS_ECDSA_P256_SHA256` is what cln-grpc uses and seems closest to our existing crypto suite. If someone has stronger opinions on TLS I'd be happy to hear them.

Implement a TLS based networks stack

---

docs/architecture.md
docs/wallet_module.md

Little overview on how the wallet module works (wasn't sure on best way to link to code).

docs for wallet module

---

Cargo.lock
integrationtests/tests/fixtures/mod.rs
ln-gateway/Cargo.toml
ln-gateway/src/lib.rs
ln-gateway/src/webserver.rs
minimint/src/net/peers.rs

migrate from tide to axum

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
client/clientd/Cargo.toml
client/clientd/src/bin/clientd-cli.rs
client/clientd/src/lib.rs
client/clientd/src/main.rs
scripts/build.sh
scripts/clientd-tests.sh
scripts/final-checks.sh
scripts/lib.sh

Initial stup for clientd REST API + cli to interact with it.
the tests are only vanity. will refactor them if everything is setup.

Clientd (REST API)

---

Cargo.lock
integrationtests/Cargo.toml
minimint-api/Cargo.toml
minimint-api/src/lib.rs
minimint-api/src/rand.rs
minimint/Cargo.toml
minimint/src/config.rs
minimint/src/lib.rs
minimint/src/net/peers.rs
modules/minimint-ln/Cargo.toml
modules/minimint-ln/src/config.rs

We updated fedimint/hbbft master branch, but never changed it here.
Co-authored-by: Justin Moon <mail@justinmoon.com>

update hbbft to master branch

---

README.md
client/cli/src/main.rs
client/client-lib/src/lib.rs
integrationtests/tests/fixtures/mod.rs
scripts/lib.sh

Possible alternative solution to #319 with polling
It has the added benefit of allowing us to eliminate a bash function and use the client API directly in some of our cli tests.

await fed api is ready in tests

---

minimint-api/src/encoding/secp256k1.rs

@elsirion mentioned this during review for #269 but I forgot to update the PR

Simplify Encodable impl for PublicKey

---

.github/workflows/ci-nix.yml
flake.lock
flake.nix
misc/git-hooks/commit-template.txt
misc/git-hooks/pre-commit

Nix flake poc followup

---

.github/workflows/ci-nix.yml
client/cli/Cargo.toml
client/client-lib/Cargo.toml
client/clientd/Cargo.toml
crypto/tbs/Cargo.toml
default.nix
flake.lock
flake.nix
integrationtests/Cargo.toml
integrationtests/src/main.rs
ln-gateway/Cargo.toml
minimint-api/Cargo.toml
minimint-core/Cargo.toml
minimint-derive/Cargo.toml
minimint/Cargo.toml
modules/minimint-ln/Cargo.toml
modules/minimint-mint/Cargo.toml
modules/minimint-wallet/Cargo.toml
nix/sources.nix
scripts/build.sh
scripts/lib.sh
scripts/pegin.sh
scripts/start-fed.sh
scripts/tmux-user-shell.sh
scripts/tmuxinator.sh
shell.nix

Only after actually landing and enabling Nix Flake based workflow all the smaller and bigger issues resurfaced.
This PR is to get everything in order.
#345 is used to track problems that can addressed later.

Bunch of nix flake improvements

---

.tmuxinator.yml
scripts/tmux-user-shell.sh

Also added a change for the lightning additional options added as I saw it giving me these errors
`--dev-fast-gossip: unrecognized option`
`--dev-bitcoind-poll: unrecognized option`

Update tmuxinator since the cli message did not match the actual usage of the cli

---

client/client-lib/src/lib.rs
client/client-lib/src/wallet/mod.rs
integrationtests/tests/fixtures/mod.rs
minimint-core/src/config.rs
minimint-core/src/transaction.rs
minimint/src/config.rs
minimint/src/consensus/mod.rs
modules/minimint-ln/src/config.rs
modules/minimint-mint/src/config.rs
modules/minimint-mint/src/lib.rs
modules/minimint-wallet/src/config.rs

Addresses issue: https://github.com/fedimint/minimint/issues/313

Move FeeConsensus into modules

---

ln-gateway/src/lib.rs

This PR is a small change to improve the readability of the LnGateway module. There is a common pattern of returning Result<T, LnGatewayError> and this PR defines a new type called LnGatewayResult that encapsulates this type. I was not able to use shadowing to override the definition of Result since serde_hex_deserialize also uses Result, but it returns a different error that is not of type LnGatewayError. Because of this, I elected to make a new type called LnGatewayResult.

Refactor Result to LnGatewayResult

---

.github/workflows/ci-nix.yml
.github/workflows/rust.yml
flake.nix

Now it will use Nix, and not consume 8 extra CPUs

Migrate non-nix-based CI step to nix-ci

---

docs/macos.md

step by step guide, (coping section is necessary)

how to on developing for macOS

---

docs/macos.md

Made the guide less wordy, and added a place for @rndhouse to describe devcontainer approach

Update mac docs

---

.github/workflows/ci-nix.yml
client/client-lib/src/api.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
flake.nix
integrationtests/tests/tests.rs
minimint-api/src/db/mem_impl.rs
minimint-api/src/db/mod.rs
minimint-api/src/db/rocksdb_impl.rs
minimint-core/src/epoch.rs
minimint/src/net/connect.rs
minimint/src/net/framed.rs
modules/minimint-ln/tests/ln_contracts.rs
modules/minimint-mint/src/lib.rs

This also switches ci-nix to use nightly, as code coverage require it.

Add code coverage in ci-nix

---

.github/workflows/ci-nix.yml
.github/workflows/rust.yml
client/client-lib/src/api.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
flake.nix
integrationtests/tests/tests.rs
minimint-api/src/db/mem_impl.rs
minimint-api/src/db/mod.rs
minimint-api/src/db/rocksdb_impl.rs
minimint-core/src/epoch.rs
minimint/src/net/connect.rs
minimint/src/net/framed.rs
modules/minimint-ln/tests/ln_contracts.rs
modules/minimint-mint/src/lib.rs

Significantly improve cache reuse between builds

---

.github/workflows/ci-nix.yml
.github/workflows/rust.yml
client/client-lib/src/api.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
flake.nix
integrationtests/tests/tests.rs
minimint-api/src/db/mem_impl.rs
minimint-api/src/db/mod.rs
minimint-api/src/db/rocksdb_impl.rs
minimint-core/src/epoch.rs
minimint/src/net/connect.rs
minimint/src/net/framed.rs
modules/minimint-ln/tests/ln_contracts.rs
modules/minimint-mint/src/lib.rs

Nix flake cargo udeps

---

minimint/src/net/api.rs

respond with bad_request instead of panic

---

client/cli/src/main.rs
client/client-lib/src/api.rs
client/client-lib/src/mint/mod.rs
integrationtests/tests/fixtures/mod.rs
ln-gateway/src/bin/ln_gateway.rs
ln-gateway/src/lib.rs
ln-gateway/src/webserver.rs
minimint-api/src/config.rs
minimint/src/config.rs
minimint/src/lib.rs
minimint/src/net/api.rs
minimint/src/net/peers.rs
modules/minimint-ln/src/config.rs
modules/minimint-mint/src/config.rs
modules/minimint-mint/src/lib.rs
modules/minimint-wallet/src/config.rs

This PR adds the ability to connect to a federation and download it's config.
To do this I create a struct called `WsFederationConnect`. This just contains enough information to instantiate `WsFederationApi`.
I also try to convert some `String`s to `SocketAddr`s in pursuit of https://github.com/fedimint/fedimint/issues/376.

Connect remote clients

---

.github/workflows/ci-nix.yml

Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges

Fix pushing to docker hub (attempt 2)

---

client/client-lib/src/api.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
flake.nix
integrationtests/tests/tests.rs
minimint-api/src/db/mod.rs
minimint/src/net/connect.rs
minimint/src/net/framed.rs
modules/minimint-ln/tests/ln_contracts.rs
modules/minimint-mint/src/lib.rs

Somehow I missed switching `complete` (latest nightly with all
components) to `stable`.

Switch toolchain to stable

---

fedimint/src/net/api.rs

Previously, when the API was using tide as its server, panics were caught and returned as HTTP errors. This means that this might still be an implicit assumption in some places and should be investigated. Catching panics is only the last line of defense, but it seems prudent.
Related to #398
Thoughts @dpc @jkitman @justinmoon ?

Catch panics in API handlers

---

client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/transaction.rs
client/client-lib/src/wallet/mod.rs
docs/database.md
fedimint-core/src/outcome.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
ln-gateway/src/lib.rs
modules/fedimint-wallet/src/db.rs
modules/fedimint-wallet/src/lib.rs

Communicate withdrawal transaction id to users

---

Cargo.lock
client/clientd/Cargo.toml
client/clientd/src/bin/clientd-cli.rs
client/clientd/src/lib.rs
client/clientd/src/main.rs
scripts/clientd-tests.sh

peg-in functionality for clientd with cli command and tests.
I messed up my git history a bit but I think its fixed now (just in case you see something odd)

clientd: peg-in

---

.github/workflows/rust.yml
client/client-lib/src/lib.rs

It seems like cross-compilation using Nix is kind of clunky so this adds some improvements to github action based building, including cross-compilation to macos, and possibly more in the future.

Github Actions-based CI cross-compilation builds

---

.github/workflows/devcontainer-daily.yml

Fix https://github.com/fedimint/fedimint/issues/426

Build and publish devcontainer

---

.github/workflows/ci-nix.yml
flake.nix

Run `cargo doc` on every PR

---

flake.nix

These changes should significantly improve run times of "CI (nix) / Code coverage" CI job.

Improve performance of llvm-cov build

---

fedimint-core/src/transaction.rs

From Docs session with @dpc @jkitman @NicolaLS @justinmoon, added some documentation to transaction.rs

add docs to transaction.rs

---

flake.nix

This allows more "tight" source filtering, which can avoid rebuilding certain Nix packages when only unrelated Rust packages changed.
Right now we don't really use these granular Nix packages much, and it's unclear if we will (instead of building the whole workspace all at once), but I fixed it already anyway, so might as well land it. It might come handy for building containers with specific binaries inside them.

flake: Fix source directory filtering

---

docs/contributing.md

Re https://github.com/fedimint/fedimint/pull/474#issuecomment-1229268651

Instruct developers to use 'imperative mood' for commits

---

fedimint-api/src/config.rs
fedimint/src/config.rs
fedimint/src/lib.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-wallet/src/config.rs

verify config key shares are valid

---

integrationtests/tests/fixtures/mod.rs

Addresses #493 see [comment](https://github.com/fedimint/fedimint/issues/493#issuecomment-1237074302)

initialize gateway with different ports

---

integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

This removes the timeout from the integration tests which can trigger spuriously on slower machines.  Instead we can check if the proposal is empty (unless user calls a different function explicitly).
@NicolaLS can you help test if this resolves your issues when running `cargo test -p fedimint-tests`?

remove timeouts from integration tests

---

docs/dev-running.md

Added instructions how to stop `tmuxinator.sh`. Helpful for newcomers unfamiliar with `tmux`.

added: instructions how to stop tmuxinator.sh

---

docs/dev-env.md
docs/macos.md

The current documentation had missing steps for macOS setup. I modified the instructions to make it clearer for macOS users.

Modified macOS install instructions

---

.github/workflows/daily.yml
.github/workflows/docs.yml

https://github.com/fedimint/fedimint/runs/8255591793?check_suite_focus=true#step:6:285

Fix daily unused deps check failing without `mold`

---

integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

Small test improvement to help @okjodom

await-multiple-epochs-in-tests

---

Cargo.lock
client/cli/Cargo.toml
client/cli/src/bin/mint-rpc-client.rs
client/client-lib/Cargo.toml
client/client-lib/src/api.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
fedimint-api/Cargo.toml
fedimint-api/src/encoding/mod.rs
fedimint-core/Cargo.toml
fedimint-core/src/config.rs
fedimint/Cargo.toml
fedimint/src/config.rs
fedimint/src/net/peers.rs
integrationtests/Cargo.toml
integrationtests/tests/fixtures/mod.rs
ln-gateway/Cargo.toml
ln-gateway/src/bin/ln_gateway.rs
modules/fedimint-ln/Cargo.toml
modules/fedimint-ln/src/lib.rs

Was working directly off of master and this makes it weird to rebase so thankfully @okjodom helped me out by showing me how to rebase.
Also many thanks to @NicolaLS for his intuition during debugging.
This PR is for issues #376 previous PR is #466 - sorry for the confusion.

Swapped out String type for URL type in config structs

---

modules/fedimint-mint/src/lib.rs

Fixes this docs build issue on master https://github.com/fedimint/fedimint/runs/8291098467?check_suite_focus=true#step:6:583

Remove links to items not in scope in the mint module docs

---

client/cli/src/main.rs
client/client-lib/src/mint/mod.rs
docs/dev-running.md
scripts/cli-test.sh
scripts/latency-test.sh
scripts/pegin.sh

This PR starts off the global Refactoring of `panic!` to more robust `Result`-based error handling
Also, the CLI output is changed to JSON

Refactor Error handling and Outputs in CLI (json)

---

Cargo.lock
client/client-lib/Cargo.toml

Fixed up https://github.com/fedimint/fedimint/pull/542 and https://github.com/fedimint/fedimint/pull/538

Bump jsonrpsee crates

---

Cargo.lock
client/cli/Cargo.toml
client/client-lib/Cargo.toml
fedimint-api/Cargo.toml
integrationtests/Cargo.toml
ln-gateway/Cargo.toml
modules/fedimint-ln/Cargo.toml

Upgrade lightning crates

---

client/client-lib/src/lib.rs
integrationtests/tests/tests.rs

Cherry picking changes we made collaboratively to #495 . This PR is a doc and error reporting enhancement to gateway client `buy_preimage_offer`

update buy preimage offer to use offer amount in contract output

---

client/client-lib/src/lib.rs
integrationtests/tests/tests.rs
ln-gateway/src/lib.rs
ln-gateway/src/util.rs

My take on internal routing. Fixes #461.

Internal routing II

---

fedimint-api/src/db/sled_impl.rs

This might fix some of the problems with DB inconsistencies in Fluttermint (https://github.com/futurepaul/fluttermint/issues/59). Long term we should get rid of `sled` instead.

Force `sled` to flush to disk on writes

---

client/cli/build.rs
flake.nix

Clean up flake.nix a bit

---

client/client-lib/src/api.rs
integrationtests/tests/tests.rs

Discover a couple tests breaking ~20% of the time, should help with some of the intermittent CI failures.

fix 2 breaking integration tests

---

client/client-lib/src/api.rs

Fix WebsocketSecure connections on Android

---

Cargo.lock
client/cli/Cargo.toml
client/cli/src/bin/mint-rpc-client.rs
client/cli/src/main.rs
client/client-lib/src/utils.rs
client/clientd/Cargo.toml
client/clientd/src/bin/clientd-cli.rs
crypto/tbs/Cargo.toml
fedimint-server/Cargo.toml
fedimintd/Cargo.toml
fedimintd/src/bin/configgen.rs

Bump clap from 3.2.22 to 4.0.0 (fixed)

---

flake.lock
flake.nix

https://github.com/ipetkov/crane/releases/tag/v0.7.0

Update `crane` to `v0.7.0`

---

client/cli/src/main.rs

Fix `--help` for fedimint-cli

---

docs/dev-env.md

Fix a typo

---

client/cli/src/main.rs
docs/dev-running.md
scripts/build.sh

Positional arguments are cursed. :)

Use long argument for `fedimint-cli` 'workdir'

---

fedimint-api/src/macros.rs

* Add support for lifetimes
* `Box<...>` does not have to be `Sync` (that's kind of a whole purspose of using it over `Arc`, I guess)

Improve `dyn_newtype_define` macro

---

fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimintd/src/main.rs
integrationtests/tests/fixtures/mod.rs

This is another small step toward end-binary (fedimintd) injecting modules into general purpose fedimint-server.

refactor: Inject `FedimintConsensus` into `FedimintServer`

---

flake.nix

This is an more gradual version of #707

Use nightly rustfmt

---

client/client-lib/src/lib.rs

This will currently return `OK` if gateway refuses HTTP connection. As a result, clients attempting a payment will think that the gateway has executed their outgoing contract. When in fact the gateway might not even be online.
Creating as a "draft" because this needs a test.

await_outgoing_contract_execution doesn't ignore http errors

---

fedimint-api/src/config.rs

Requires peers to commit to a hash prior to revealing their commitments to avoid manipulation of the secret key.
Long-term will need to revisit DKG to deal with issues of liveness, but we can at least be assured if DKG runs that no one knows the secret key.
Fixes #760

Fix potential attack against DKG

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/transaction.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/module/mod.rs
fedimint-api/src/module/testing.rs
fedimint-core/src/config.rs
fedimint-core/src/transaction.rs
fedimint-server/src/config.rs
fedimint-server/src/consensus/mod.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Completion of #325, fixes  #359

Remove `FeeConsensus`

---

integrationtests/tests/fixtures/real.rs

Remove unused struct `FundChannelFixed`

---

integrationtests/tests/fixtures/real.rs

@jkitman tiny PR to merge the two impl blocks.

Merge two impl blocks into one

---

.tmuxinator.yml
scripts/tmux-user-shell.sh

Go tmux!
```
$ gateway-cli
Usage: gateway-cli [OPTIONS] <COMMAND>
Commands:
version-hash  Display CLI version hash
info          Display high-level information about the Gateway
balance       Check gateway balance TODO: add federation id to scope the federation for which we want a pegin address
address       Generate a new peg-in address, funds sent to it can later be claimed
deposit       Deposit funds into a gateway federation TODO: add federation id to scope the federation for which we want a pegin address
withdraw      Claim funds from a gateway federation TODO: add federation id to scope the federation for which we want a pegin address
help          Print this message or the help of the given subcommand(s)
```

alias gateway-cli in tmux

---

fedimintd/src/lib.rs
fedimintd/src/main.rs

Fix lint errors on latest master. These seem to have come with #808

fix fedimintd lint error

---

fedimint-api/src/module/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-testing/src/lib.rs
fedimintd/src/ui/configgen.rs
fedimintd/src/ui/mod.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

This is not going to work in modularization code.

Don't pass `rng` to `FedimintModule`

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
gateway/cli/src/main.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/webserver.rs

Pass federation id on user client request to pay invoice

Pass federation id on pay invoice

---

Cargo.lock
client/cli/Cargo.toml
client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/cln.rs
gateway/ln-gateway/src/ln.rs
integrationtests/tests/fixtures/fake.rs
integrationtests/tests/fixtures/utils.rs
modules/fedimint-ln/Cargo.toml
modules/fedimint-ln/src/contracts/outgoing.rs
modules/fedimint-ln/tests/ln_contracts.rs

use `lightning_invoice::Invoice` instead of `&str` and `String`

type invoice

---

crypto/tbs/benches/tbs.rs

Fixes https://github.com/fedimint/fedimint/actions/runs/3416711150/jobs/5687111424

Fix failing daily udeps run

---

.cargo/config.toml
docs/dev-env.md
flake.nix

this is suggested in the book "Zero to Production in Rust", and mold is currently broken

use zld for apple linker

---

gateway/cli/src/main.rs
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc.rs
gateway/ln-gateway/src/webserver.rs
integrationtests/tests/fixtures/mod.rs

Move all Gateway requests and RPC messaging types to `rpc` module

Code shuffle: Clean Gateway Library

---

gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/webserver.rs

small gateway webserver polish

pass ready gateway rpc sender to webserver

---

flake.nix

This way it will actually get tested.

Fix `gateway-cli` build and add it to the ln-gateway-clightning cont.

---

Cargo.lock
client/client-lib/Cargo.toml
client/client-lib/src/api.rs
fedimint-server/Cargo.toml
fedimint-server/src/net/api.rs
fedimintd/Cargo.toml

Closes #898
Closes #899
Closes #900
Closes #901

Upgrade `jsonrpsee` 0.15.1 -> 0.16.0

---

Cargo.lock
gateway/tests/Cargo.toml
gateway/tests/tests/fixtures.rs

Part one of #938   - Create gateway test fixtures

Create gateway test fixtures

---

fedimint-server/src/config.rs
fedimintd/src/bin/distributedgen.rs
scripts/build.sh

Make bind address independent of announced address

---

fedimint-server/src/config.rs
fedimintd/src/bin/distributedgen.rs
modules/fedimint-wallet/src/config.rs
modules/fedimint-wallet/src/lib.rs

Also fixes that the configures network wasn't used for the generated client config.

Make finality delay configurable

---

gateway/cli/src/main.rs
gateway/ln-gateway/src/config.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/tests.rs
integrationtests/tests/fixtures/mod.rs
scripts/lib.sh

Separate bind and announce address for gateway

---

fedimintd/src/bin/distributedgen.rs
scripts/build.sh
scripts/cli-test.sh

Implement en-/decryption tool for config files

---

client/cli/src/main.rs
client/client-lib/src/lib.rs

Implement contract fetching in fedimint-cli

---

client/cli/src/main.rs
fedimint-core/src/config.rs
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/fixtures.rs
gateway/tests/tests/tests.rs
integrationtests/tests/fixtures/mod.rs

Load federation config from disk when restarting gateway

---

fedimint-bitcoind/src/lib.rs

Instead of crashing when bitcoind is unavailable this will retry the requests forever, blocking the current thread and logging the error.  Tested manually.
We should eventually have a way to notify users via the server UI.
Fixes #37

Instead of erroring, retry until bitcoind returns a successful response

---

fedimint-server/src/consensus/mod.rs

Fix for #971
Will also make it easier to determine the failed txs for including in the consensus history.

Don't rely on double spends to deduplicate transactions

---

client/client-lib/src/api.rs
client/client-lib/src/query.rs

add an exponential backoff to the client

---

Cargo.lock
gateway/ln-gateway/src/rpc/mod.rs
gateway/tests/Cargo.toml
gateway/tests/tests/fixtures/client.rs
gateway/tests/tests/fixtures/fed.rs
gateway/tests/tests/tests.rs

New coverage: Test authentication on:
Pending: Test authentication on:

Test gateway authentication

---

docs/gateway.md
gateway/cli/src/main.rs

If I'm not mistaken, these TODOs are already addressed? @okjodom 
Or is there more to be done?
in 3038e8ada9 and 4125656938

Remove addressed TODOs

---

gateway/ln-gateway/src/lib.rs

Fix crash on invalid member string

---

docs/recoverable_e-cash.md

Reflect e-cash recovery tweaks in documentation

---

fedimint-api/src/core.rs
fedimint-server/src/consensus/debug.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Make consensus item logs pretty again

---

gateway/ln-gateway/src/lib.rs
gateway/tests/tests/fixtures/fed.rs
gateway/tests/tests/fixtures/ln.rs

use async mutexes in gateway

---

Cargo.lock
client/cli/Cargo.toml
crypto/tbs/Cargo.toml
fedimintd/Cargo.toml
gateway/cli/Cargo.toml

Fedimint did not compile on my machine on master anymore:
https://github.com/sunfishcode/io-lifetimes/issues/51
https://github.com/sunfishcode/io-lifetimes/pull/53

disable default clap features and add std

---

Cargo.lock
client/cli/Cargo.toml
crypto/tbs/Cargo.toml
fedimintd/Cargo.toml
gateway/cli/Cargo.toml

Accidentally deactivated by #1042

Enable clap help again

---

client/client-lib/src/mint/mod.rs

E-cash recovery code needs a per-`NoteIssuanceRequest` finalize.

Split `NoteIssuanceRequests::finalize`

---

.github/workflows/pr-conflicts.yml

Try out potential-conflicts-checker github action

---

client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/transaction.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

Refactors the mint-specific code out of `TransactionBuilder` which gets us closer to modularization and simplifies a lot of boilerplate code.  Also will make it easier to modify the change algorithm in a follow-up PR.

Refactor mint code out of TransactionBuilder

---

client/client-lib/Cargo.toml
client/client-lib/src/lib.rs
client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/backup/tests.rs
client/client-lib/src/mint/mod.rs
fedimint-api/src/tiered.rs
fedimint-api/src/tiered_multi.rs
modules/fedimint-mint/src/lib.rs

No test yet, so this probably does not work as is yet, but since
it is not used for anything yet, it is probably OK to land.

Core ecash recovery logic 

---

client/cli/src/main.rs
client/client-lib/src/lib.rs

This reverts commit 15582a85cec876059e68cfbbe8a682c09fee5cb0.
[We decided to revert this during a dev call](https://github.com/fedimint/fedimint/pull/991#issuecomment-1331002567) but never did.

Revert "Implement contract fetching in fedimint-cli"

---

fedimint-server/src/lib.rs

Small PR to make the handling of steps consistent.
Bans peers sending undecodeable messages.

Small refactor to log faults and possibly ban peers on every step

---

client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/backup/tests.rs
fedimint-api/src/encoding/mod.rs
fedimint-core/src/epoch.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs

Use it during recovery to skip them.

 Track rejected_txs in EpochHistory 

---

client/client-lib/src/api.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/query.rs
client/client-lib/src/wallet/mod.rs
fedimint-core/src/epoch.rs
fedimint-server/src/consensus/debug.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/db.rs
fedimint-server/src/lib.rs
gateway/tests/tests/fixtures/fed.rs
integrationtests/tests/fixtures/mod.rs

Rename consensus history idents.

---

fedimint-server/src/lib.rs

fix hash verification on epoch download

---

README.md

There are no longer known security issues, and Fedimint can now benefit from conservative testing on mainnet.
And much work remains on the privacy front, so added a warning about that.

Relax warning on README

---

client/client-lib/src/mint/mod.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-mint/src/lib.rs

Configurable target denominations

---

fedimint-api/src/module/mod.rs
fedimint-server/src/config.rs
fedimint-testing/src/lib.rs
fedimintd/src/bin/configgen.rs
fedimintd/src/ui/configgen.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Remove more unnecessary client config generation code.

Clean-up unnecessary trusted client config gen

---

fedimint-server/src/config.rs
fedimintd/src/bin/main.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/config.rs
modules/fedimint-wallet/src/lib.rs

Final splitting of the module configs into local, private, and consensus files.
Fix #960

Splits module configs into local, private, and consensus files

---

fedimint-server/src/config.rs
fedimintd/src/bin/configgen.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/lib.rs
fedimintd/src/ui/configgen.rs
integrationtests/tests/fixtures/mod.rs

Adds the code version to consensus config for the purposes of validation (see #950)

Add code version to consensus config

---

gateway/ln-gateway/src/rpc/mod.rs

Instead of panicking on channel failures in `GatewayRpcSender`, we return error responses, thus adding resiliency to our messaging pipeline between CLN node and the gateway.

Return response on message channels

---

gateway/ln-gateway/src/cln.rs

Intercepting and processing of HTLCs with gateway as CLN plugin results in channel force closures, and we suspect this arises in scenarios where we never give a response to the plugin after intercepting HTLCs.
This potential fix adds a timeout to HTLC intercept and processing, ensuring the plugin always gets a `continue` response, if processing of the intercepted HTLC did not complete in time.
**Risks**
- Timeout is arbitrary, and we may end up with double payment of invoices if we still forward the invoice but the gateway had actually paid it?
- We instruct CLN to continue forwarding an invoice to a `false-last-hop` if the invoice indeed belongs to a federation. This will fail as there is no LN node to process the HTLC
**Next Steps**
- Check in this code and validate behavior / fix on …

Continue intercepted htlcs if processing times out

---

gateway/ln-gateway/src/actor.rs

GatewayActor::new doesn't panic

---

fedimintd/src/distributedgen.rs
fedimintd/src/ui.rs

Based on @m1sterc001guy's comments on https://github.com/fedimint/fedimint/pull/1155

Admin UI fixes

---

docs/networking.md

Add networking.md to document default ports

---

fedimint-api/src/config.rs
fedimint-server/src/config.rs
gateway/tests/tests/fixtures/client.rs
modules/fedimint-ln/src/lib.rs

Add a new threshold key for authenticating the configuration

---

Cargo.lock
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
fedimint-api/src/config.rs
fedimint-server/src/config.rs
gateway/cli/Cargo.toml
gateway/cli/src/main.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/config.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs
gateway/tests/tests/fixtures/client.rs
gateway/tests/tests/tests.rs
integrationtests/tests/fixtures/mod.rs

Make federation id stable and unique

---

integrationtests/tests/fixtures/mod.rs

Fix logging in integration test

---

fedimint-api/src/core/server.rs
fedimint-api/src/lib.rs

This PR aims to add some documentation. 
Please check it for correct terminology

Add documentation

---

fedimint-bitcoind/src/bitcoincore_rpc.rs

Report address on bitcoind rpc errors

---

scripts/cli-test.sh
scripts/lib.sh
scripts/pegin.sh
scripts/reconnect-test.sh
scripts/setup-tests.sh
scripts/tmux-user-shell.sh

Fixes [this error](https://discord.com/channels/990354215060795454/990354215878688860/1060635781510729789)

Tmuxinator waits until cln / bitcoind rpc are available

---

.github/workflows/docs.yml

Hopefully fixes failing docs builds https://github.com/fedimint/fedimint/actions/runs/3869680045/jobs/6595965055

Install `protoc` in docs CI

---

fedimintd/src/bin/distributedgen.rs

These values disagreed with https://github.com/fedimint/fedimint/blob/master/docs/networking.md and https://github.com/fedimint/fedimint/blob/master/fedimint-server/src/config.rs#L37

Make default addresses consistent

---

scripts/start-containers.sh

Recent changes to fedimintd broke the start-containers script which brings up a federation using docker and docker-compose. This PR makes the small changes to fix the script.

Fix start-containers script

---

docs/dev-env.md
fedimintd/src/bin/main.rs
fedimintd/src/ui.rs

Re https://github.com/fedimint/fedimint/issues/1251#issuecomment-1375599594

Rename fedimintd command line args

---

client/client-lib/src/lib.rs
fedimint-api/src/core/encode.rs
fedimint-api/src/module/registry.rs
fedimint-server/src/config.rs
fedimint-server/src/consensus/interconnect.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs
fedimint-testing/src/lib.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/tests/ln_contracts.rs

Renames in module and decoder registries inspired by @mxz42

Renames in module and decoder registries inspired by @mxz42

---

fedimint-api/src/config.rs
fedimint-server/src/config.rs
gateway/tests/tests/fixtures/client.rs

Remove duplicate fed id from client config

---

scripts/lib.sh

Fix tmuxinator after instance-id change

---

fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/distributedgen.rs
fedimintd/src/encrypt.rs
fedimintd/src/lib.rs
fedimintd/src/ui.rs

No longer panic from DKG setup UI, but displays the error message, fixes #1211.
Also fixes #1183 by displaying the missing directory.
Would be cool to auto-populate more fields, esp for testing.  I'll try that in another PR.

Improve error handling for setup UI

---

client/client-lib/src/lib.rs
fedimint-api/src/config.rs
fedimint-api/src/core.rs
fedimint-api/src/module/mod.rs
fedimint-api/src/module/registry.rs
fedimint-server/src/config.rs
fedimintd/src/bin/main.rs
integrationtests/tests/fixtures/mod.rs

Address feedback from `ModuleInstanceId` change

---

client/client-lib/src/wallet/mod.rs
fedimint-api/src/bitcoin_rpc.rs
fedimint-api/src/module/mod.rs
fedimint-server/src/config.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/distributedgen.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/config.rs
modules/fedimint-wallet/src/lib.rs
scripts/tmuxinator.sh

Pass the bitcoind rpc url via env variable

---

client/cli/src/main.rs
docs/dev-running.md

add network to info command

---

fedimint-api/src/config.rs
fedimint-server/src/config.rs

Fix a `JsonWithKind` `Deserialize` to serde_json::Value quirk

---

fedimintd/src/ui.rs
fedimintd/templates/base.html
fedimintd/templates/params.html

Show `FM_BITCOIND_RPC` in a setup UI

---

scripts/lib.sh
scripts/pegin.sh
scripts/tmux-user-shell.sh

Please merge #1302 for a more important fix before testing this one.

 Clean up tmuxinator output and fix some minor bugs 

---

flake.nix

* Include fedimint-cli
* Binaries to contain a correct `version-hash`

Minor fedimintd container fixes

---

fedimint-api/src/module/mod.rs

follow up on #1314 @dpc 
I think this is what you meant?

Remove `module_kind` method in typed `ModuleGen` trait

---

Cargo.lock
Cargo.toml
fedimint-api/src/db/mod.rs
fedimint-dbtool/Cargo.toml
fedimint-dbtool/src/main.rs

This is the lower level alternative to `dbdump` to manually salvage DBs.
This is a draft so far since it's missing tests and I could not figure out how to make write operations persist so far.

`dbtool` to read, write and delete raw data from our DBs

---

client/cli/src/main.rs
fedimint-api/src/db/mem_impl.rs
gateway/cli/src/main.rs

Direct interactive outputs to appropriate stdout/stderr streams

---

client/client-lib/src/mint/mod.rs

Address this comment https://github.com/fedimint/fedimint/pull/1328#discussion_r1070404290

Use Amount::ZERO for comparison

---

Cargo.lock
fedimint-sqlite/Cargo.toml

We avoid openssl dependency everywhere else, so let's do it here too?

Change fedimint-sqlite dep from openssl to rustls

---

fedimint-server/src/consensus/mod.rs

Re-try committing DB tx when processing consensus outcomes

---

fedimint-api/src/module/mod.rs

use `RUST_LOG="fedimint_server::request,fedimint_client::request"` to log requests and corresponding responses.
It adds `+ Debug` at some places, should be fine IMO.

Add request logging

---

client/cli/src/main.rs
client/client-lib/src/api.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/query.rs
client/client-lib/src/wallet/mod.rs

Rename things related to `IFederationApi`

---

client/client-lib/src/mint/mod.rs

I think this can be removed. 
[Issue at rust-bitcoin/rust-secp256k1](https://github.com/rust-bitcoin/rust-secp256k1/issues/491). Was solved in [this PR](https://github.com/rust-bitcoin/rust-secp256k1/pull/492) merged on Oct, 25th 2022.
Our currently used version is secp256k1 0.24.2 which was released on Dez, 7th 2022.

Remove workaround for deserializing `KeyPair`

---

fedimint-api/src/core/encode.rs
fedimint-api/src/module/registry.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/net/api.rs
integrationtests/tests/fixtures/mod.rs

Unify `ModuleRegistry*` types

---

client/cli/src/main.rs
client/client-lib/src/mint/mod.rs
fedimint-api/src/tiered_multi.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-mint/src/lib.rs

Rename `TieredMulti` methods to be more descriptive

---

client/client-lib/src/mint/mod.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-mint/src/lib.rs

Change coin terminology to notes in mint module

---

.github/workflows/ci-nix.yml
flake.nix

Cross-compile fedimint-sqlite in CI

---

Cargo.lock
fedimint-api/src/bitcoin_rpc.rs
fedimint-bitcoind/Cargo.toml
fedimint-bitcoind/src/bitcoincore_rpc.rs
fedimint-bitcoind/src/lib.rs
fedimintd/src/ui.rs
fedimintd/templates/params.html
integrationtests/tests/fixtures/mod.rs
misc/fedimintd-container-entrypoint.sh
modules/fedimint-wallet/Cargo.toml
modules/fedimint-wallet/src/lib.rs

This adds (not really tested properly yet) support for electrum as backend.
Fixes some issues I've found along the way.

Add electrum support

---

gateway/ln-gateway/src/cln.rs

Instead of processing all htlcs to gateway for processing, filter only the relevant ones, and forward all other intercepted htlcs. This rightly assumes the gateway is only serving one federation, and clients in that federation use `short_channel_id=0` in the route hint
**TODO**: Expand this filtering logic to work with other short channel ids, as part of completing #664

Filter cln htlcs on intercept

---

fedimint-server/src/net/peers.rs
flake.lock
flake.nix
gateway/ln-gateway/src/lib.rs

The meaning of `cargoBuild` changed at some point in crane, and was
ignoring previous overrides to run the tests instead of just doing
`cargo build`.
Couple of minor fixes along with it.
Fix #1379

Fix CI not runing tests

---

client/cli/src/main.rs

Add federation info to cli info command

---

fedimint-api/src/macros.rs
fedimint-api/src/module/mod.rs
fedimint-core/src/epoch.rs
fedimint-core/src/outcome.rs
fedimint-core/src/transaction.rs

cleanup: replace serde_module_encoding_wrapper macro with generics

---

fedimint-server/src/net/peers.rs

This should prevent the network stack from continuing to run when fedimint is trying to shut down.

Make peer connections wait for task manager shutdown explicitly

---

Cargo.lock
docs/telemetry.md
integrationtests/Cargo.toml
integrationtests/tests/fixtures/mod.rs

Just as suggestion to try out.
It is much more user friendly than open telemetry for debugging.   
Instructions are in docs/telemetry.md

chrome tracing for integration tests

---

fedimint-api/src/module/mod.rs

tracing: Fix error logging level in server request

---

fedimint-api/src/encoding/mod.rs
fedimint-derive/src/lib.rs

fix: implement variantless enum encode/decode derive

---

fedimint-core/src/lib.rs
fedimint-core/src/util.rs
fedimintd/src/ui.rs

Hide user+password in serialized URLs in UI

---

.github/workflows/ci-nix.yml
flake.nix
scripts/always-fail-test.sh

Use always-fail tests to make sure nix flake is having the tests run

---

fedimint-api/src/config.rs
fedimint-server/src/config.rs
fedimint-server/src/multiplexed.rs
fedimintd/src/distributedgen.rs

Make sure other peers received all our dkg messages

---

fedimintd/templates/run.html

Don't flicker the setup UI after dkg is done.

---

fedimint-core/src/util.rs
misc/git-hooks/pre-commit

Seems like I'm not the only one, so we could say it's endemic now.

Complain about leftover `dbg!` in `.rs` files

---

fedimintd/src/bin/main.rs
fedimintd/src/ui.rs

A papercut when working on your own module.

Don't hardcode module gens in the ui

---

fedimintd/src/distributedgen.rs

In #1424 I first wrote this workaround, then decided it's meh, then wrote rest of the #1424 with a proper solution, and forgot to delete the workaround.

Delete unnecessary workaround

---

fedimint-api/src/db/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs

generic autocommit version for fix in pr #1351 that fixed issue #1316 
Builds on top of #1352 
still needs some work now to integrate, but the function works now _I think_.

Lifetimes for autocommit feature in db

---

.github/workflows/linkcheck.yml
docs/recoverable_e-cash.md

```
ERROR: 2 dead links found!
[:heavy_multiplication_x:] https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TR03111/BSI-TR-03111_V-2-1_pdf.pdf?__blob=publicationFile&v=1 → Status: 0
[:heavy_multiplication_x:] https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.pdf?__blob=publicationFile&v=4 → Status: 0
```

Unbreak link checker

---

.github/actions/prepare/action.yml
.github/workflows/ci-nix.yml

See https://stackoverflow.com/a/74887073/134409

Build docker images with correct commit sha

---

client/cli/src/main.rs
client/client-lib/src/api.rs
fedimint-api/src/config.rs
fedimintd/src/lib.rs
scripts/build.sh
scripts/cli-test.sh

Fixes #1456
Also adds a CLI test for downloading the client config.

Test and fix the CLI client connection string

---

client/client-lib/src/mint/backup.rs
fedimint-api/src/config.rs
fedimint-api/src/task.rs
fedimint-server/src/multiplexed.rs
fedimint-server/src/net/peers.rs
fedimintd/src/bin/main.rs
fedimintd/src/ui.rs
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/tests/tests/tests.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

Graceful shutdown fixes

---

client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/backup/tests.rs
client/client-lib/src/mint/db.rs
client/client-lib/src/mint/mod.rs
docs/architecture.md
docs/database.md
fedimint-dbdump/README.md
fedimint-dbdump/src/main.rs
gateway/ln-gateway/src/actor.rs
integrationtests/README.md
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-mint/src/db.rs

Replace additional usages of 'coin' term with note

---

gateway/ln-gateway/src/cln.rs
scripts/cli-test.sh

The first commit reproduces the problem in CI, the second one fixes it, the third one is out of abundance of caution.

Don't fail if gw LN node is direct recipient of payment

---

client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/transaction.rs
integrationtests/tests/tests.rs

Only writes change to the DB once a transaction has been submitted successfully, adds integration test coverage as well.
Note that this does not handle the case where the tx is rejected during consensus.
Fixes #1478

finalize_change shouldn't commit to the database

---

fedimintd/src/ui.rs
fedimintd/templates/params.html
integrationtests/tests/tests.rs

Change UI form field from finality delay to block confirmations

---

fedimintd/templates/run.html
integrationtests/tests/tests.rs

I had an opportunity to set up federation again, and noticed these two things.

Setup UI fixes

---

docs/debugging.md
fedimint-api/src/db/mod.rs

Now you can view all changes to database.

tracing: improved db logging

---

docs/debugging.md
fedimint-dbtool/README.md
fedimint-dbtool/src/main.rs

People keep asking me how to use it, I take this as a sign that I should document it better :laughing:

Add `dbtool` documentation

---

client/client-lib/src/lib.rs
gateway/ln-gateway/src/actor.rs

* Refund contracts the gateway doesn't accept due to being faulty in some way
* Bug fix: don't pay invoices of cancelled outgoing contracts

Refund contracts the gateway doen't accept

---

client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
docs/architecture.md
docs/dev-running.md
docs/recoverable_e-cash.md
gateway/ln-gateway/src/rpc/rpc_server.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
scripts/cli-test.sh
scripts/latency-test.sh
scripts/pegin.sh

Change 'token' term to 'note'

---

fedimint-api/src/db/mod.rs

We got a comparison the wrong way around, this commit adds a test so it doesn't break again and fixes the issue.

fix: autocommit re-tries failed DB tx

---

fedimint-derive/src/lib.rs

Should fix the clippy error in CI, although I'm not sure how to test locally.

Fixes macos clippy error

---

docs/contributing.md
docs/gateway.md

Cherry picked the documentation parts of #1454 .
These doc refresh add detail on the components that make up the new gateway

Gateway docs update

---

client/client-lib/src/lib.rs
gateway/ln-gateway/src/actor.rs

Currently, gateway logs almost nothing. This adds some spans and increases level of some logs.

ln_gateway: improve logging and add spans

---

gateway/ln-gateway/src/utils.rs

Fixes the u32 overflow mentioned in #1545

Fix u32 overflow 

---

client/client-lib/src/mint/backup.rs
integrationtests/tests/tests.rs

Replaces #1556 
It seems that in practice fetching epochs take a long time leading to a bad user-experience. Fetching epochs from federation has a large latency, so it makes sense to do in on multiple-threads.
I selected 8 as a good compromise that should not create issues, like too much load, while hopefully giving most of the benefit of parallelism.

 feat: Fetch epochs in parallel during ecash restoration (stream version)

---

gateway/ln-gateway/src/cln.rs
integrationtests/tests/fixtures/mod.rs

fix: avoid lock around CLN RPC client

---

fedimintd/src/bin/main.rs

Log code version on startup

---

client/client-lib/src/api.rs
client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/backup/tests.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/net/api.rs

Hi, I've started working on this PR to address #1340.
I hope I'm on the right track. I'm quite new to this project and Rust in general so I'll be very grateful for any feedback :)

Use epoch count instead of last epoch

---

flake.nix
justfile
misc/git-hooks/pre-commit

feat: Introduce just

---

integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

Refactoring of the tests to make things a bit more clear.
Some of the feedback from @dpc

Tests refactor

---

fedimint-api/src/core/server.rs
fedimint-api/src/module/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-testing/src/lib.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs
scripts/rust-tests.sh

* Make the module explicitily return proposals with a flag that indicate if it should trigger a new epoch, or not.
* Rename relevant test helper functions and add comments.
* Fix some bugs.

fix: Fix test epoch handling

---

fedimint-testing/src/btc/fixtures.rs
fedimint-testing/src/btc/mod.rs
integrationtests/tests/fixtures/real.rs

I should have seen this being totally wrong from the start...

fix: locking in parallel tests

---

scripts/rust-tests.sh

Saves around 20 secs (from 2:20 to 1:59).

feat: run integration tests with more paralellism

---

scripts/always-fail-test.sh
scripts/gw-reload.sh
scripts/restart-tmux.sh

fixes #1650
script permission was added in #1646

fix: add correct shebang for nix environments

---

modules/fedimint-wallet/src/lib.rs

Hi, this PR is for #1658. Thanks.

Use rust-bitcoin's `is_valid_for_network`

---

client/client-lib/src/db.rs
client/client-lib/src/ln/db.rs
client/client-lib/src/mint/db.rs
client/client-lib/src/wallet/db.rs
fedimint-api/src/db/mod.rs
fedimint-server/src/db.rs
modules/fedimint-dummy/src/db.rs
modules/fedimint-ln/src/db.rs
modules/fedimint-mint/src/db.rs
modules/fedimint-wallet/src/db.rs

implement feedback from [this conversation](https://github.com/fedimint/fedimint/pull/1608#discussion_r1103269619)
@m1sterc001guy

refactor: clarify parameters of db macro

---

fedimintd/templates/add_guardians.html
fedimintd/templates/base.html
fedimintd/templates/params.html

sorry autoformatter went to town on this
main changes:
- spacing between some form fields
- full-width header
- use system monospace font

styling for guardian setup

---

gateway/ln-gateway/src/bin/cln_extension.rs

Ports fixes introduced by #1577 to `ln-gateway`, over to `gateway-cln-extension`

feat: avoid lock around CLN RPC client in cln-extension

---

Cargo.lock
fedimint-core/Cargo.toml
fedimint-core/src/db/mod.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/consensus/mod.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy/Cargo.toml
modules/fedimint-dummy/src/db.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

This PR adds:
- Persisting the database version of each module and checking if a db migration needs to occur.
- A DB Migration of the Dummy Module integration test.

Dummy Module Database Migration

---

Cargo.lock
fedimint-core/Cargo.toml
fedimint-core/src/api.rs
fedimintd/src/ui.rs

Reduction is 242 -> 229 bytes for 10 peers.
Fixes #1659

bech32 encode connect string

---

Cargo.lock
fedimint-server/Cargo.toml
fedimint-server/src/logging.rs
fedimintd/Cargo.toml
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
gateway/tests/Cargo.toml
gateway/tests/tests/tests.rs
integrationtests/Cargo.toml
integrationtests/tests/fixtures/mod.rs

Refactors tracing into logging mod for `fedimint-server`.
Simplifies some of our dependencies and logging setup code.

Refactor tracing into logging mod

---

fedimint-dbtool/src/main.rs
fedimint-server/Cargo.toml
fedimintd/Cargo.toml
fedimintd/src/bin/main.rs
gateway/cli/src/main.rs
gateway/ln-gateway/src/bin/gatewayd.rs
integrationtests/Cargo.toml

Fixes #1493
Some binaries were too trivial for tracing or did not have the dep.

Add tracing to binaries, make telemetry non-default

---

client/client-lib/src/api.rs
client/client-lib/src/logging.rs
client/client-lib/src/mint/backup.rs

fix some flaky tests

---

gateway/ln-gateway/src/utils.rs

Add two tests for the retry function. The first test should run the closure only once as it immediately succeeds. The closure of the second test always fails, hence the closure should be run `max_attempt` times.

test: add tests for retry function

---

client/client-lib/src/mint/backup.rs

This TODO was already implemented (in `handle_consensus_item`).

fix: leftover comment

---

client/cli/src/main.rs
fedimint-core/src/api.rs
fedimint-server/src/config/io.rs
gateway/ln-gateway/src/gatewayd/gateway.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/tests.rs
scripts/cli-test.sh

Fix connect info serde impl and accepted string in cli commands

---

flake.lock
flake.nix

Update `crane` to include fix for https://github.com/ipetkov/crane/issues/242

fix: spurious rebuilds of whole repo on unrelated file changes

---

modules/fedimint-wallet/src/lib.rs

fix: Add checks in Wallet to ensure Bitcoin is configured correctly

---

fedimintd/src/ui.rs
fedimintd/templates/params.html
scripts/run-ui.sh

Hi, I've started making some changes towards #1532 based on a discussion with @justinmoon.
Values for the networking parameters are read from env variables and passed to the params page. I haven't handled them using clap as suggested in https://github.com/fedimint/fedimint/issues/1532#issuecomment-1428317094, but can try adding that if required.
After initial feedback, I can do the same for the other parameters too.
Thanks.

WIP: Get default values from env variables

---

client/cli/src/main.rs
fedimint-core/src/config.rs
fedimint-server/src/config/mod.rs
gateway/tests/tests/fixtures/client.rs

Allow federation to send additional config values to clients

---

fedimint-core/src/core.rs

Fixups for `module_dyn_newtype_impl_encode_decode`

---

client/cli/src/main.rs
fedimint-core/src/config.rs
gateway/ln-gateway/src/client.rs

Inspired by https://github.com/fedimint/fedimint/pull/1718#pullrequestreview-1314059849

feat: impl Display for FederationId

---

client/cli/src/main.rs
fedimint-core/src/api.rs
scripts/cli-test.sh

I've made an initial attempt at the decoder part of #1730.
It would be great if you could check I'm on the right track. Thanks.

feat: add connect string decoder to `fedimint-cli`

---

flake.nix

This in certain cases can lead to incorrect behavior and weird issues.
See https://github.com/ipetkov/crane/issues/249#issuecomment-1445432300 for details.

fix: mixing `craneLib` and `craneLibCross`

---

fedimintd/src/ui.rs

I think this resolves #1273.
I was able to run the UI locally and generate the connection string.

refactor: Generate connection string from consensus config

---

Cargo.lock
client/client-lib/Cargo.toml
docs/database.md
fedimint-client/Cargo.toml
fedimint-client/src/lib.rs
fedimint-client/src/sm/executor.rs
fedimint-client/src/sm/mod.rs
fedimint-client/src/sm/state.rs
fedimint-core/Cargo.toml
fedimint-core/src/core.rs
fedimint-server/Cargo.toml
fedimintd/Cargo.toml
gateway/tests/Cargo.toml
integrationtests/Cargo.toml
modules/fedimint-ln/Cargo.toml
modules/fedimint-mint/Cargo.toml

This PR implements the interfaces for module state machines and implements an executor for these. There are a few TODOs left for after this design is validated, but seems to work in a [basic test](https://github.com/fedimint/fedimint/blob/f3c54150dd0684f7c769e08ad580327081e768c1/fedimint-client/src/sm/executor.rs#L411-L614) so far.
I can live with either keeping it a PR or merging, I think there shouldn't be too much trouble rebasing since I'm not touching the main code base too much. But feedback is definitely welcome at this point.
Builds on top of #1782 to make CI happy.

Base for state machine client

---

fedimint-core/src/config.rs
modules/fedimint-dummy/src/config.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-wallet/src/config.rs
scripts/lib.sh

 feat: clients with a subset of federation module support 

---

docs/building-new-modules.md

fix: replace broken fedimint-dummy link

---

flake.lock
flake.nix

Ran `nix flake lock --update-input flake-utils`.
See https://github.com/ipetkov/crane/issues/243 for details.

fix: `nix flake show` was broken

---

fedimint-bitcoind/src/bitcoincore_rpc.rs
fedimint-bitcoind/src/lib.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs
scripts/build.sh
scripts/rust-tests.sh
scripts/setup-tests.sh

Adds tests for the esplora client (after fixing some issues with it).  @oleonardolima
Fixes #1383

add esplora tests to CI

---

Cargo.lock
fedimint-core/Cargo.toml
fedimint-core/src/db/mod.rs
fedimint-core/src/db/notifications.rs
fedimint-dbtool/src/dump.rs

separated from #231
motivation: useful in new client.

feat: add notifications in database for modifying keys

---

fedimint-dbtool/src/dump.rs

Small fixes to dbtool:
- Fix bug where consensus data wasn't being printed when all of the data is supposed to be printed
- Print out version of module. Will likely be useful to debugging in the future.

fix: read database version from modules and print consensus data

---

.tmuxinator.yml
Cargo.lock
docs/dev-running.md
flake.nix
integrationtests/Cargo.toml
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs
misc/test/bitcoin.conf
misc/test/lightningd.conf
misc/test/lnd.conf
scripts/build.sh
scripts/cli-test.sh
scripts/gw-reload.sh
scripts/latency-test.sh
scripts/lib.sh
scripts/run-ui.sh
scripts/setup-tests.sh
scripts/tmux-user-shell.sh

First chunk broken off https://github.com/fedimint/fedimint/pull/1719.
Just run LND as non-gateway node in tests and tmuxinator.
In follow-up PR I'll turn this node into a gateway as well.
Also contains commits from https://github.com/fedimint/fedimint/pull/1851 which could be merged separately.

Run LND in tests and tmuxinator

---

fedimint-core/src/core.rs
modules/fedimint-dummy-common/src/lib.rs
modules/fedimint-dummy-server/src/lib.rs

Remove old macro

---

crypto/aead/src/lib.rs

Looks like our CI is broken (always passing) so I didn't catch this issue that will cause the fed to fail to start.

Fix min value for Argon2

---

.github/workflows/daily.yml
.github/workflows/docs.yml
flake.nix
justfile

chore: nixify cargo-udeps daily check and add just udeps

---

.github/workflows/rust.yml

The Rust version not being locked via flake is annoying.

fix: build macos build using Nix

---

Cargo.lock
fedimint-testing/Cargo.toml
fedimint-testing/src/bin/fixtures.rs
scripts/lib.sh
scripts/setup-tests.sh
scripts/tmux-user-shell.sh

Spawn electrs, esplora, fedimintd, gatewayd via rust. Also, run a whole federation or dkg.
After this, whenever you're bored you can just choose some bash function in lib.sh and re-write it in rust. I think all the basic infrastructure is there.

Spawn all daemons via RUST

---

flake.nix

fixes https://github.com/fedimint/fedimint/issues/1911

Fix env check for optional semgrep package

---

docs/database.md

This PR adds a diagram and explanation of the database transaction interfaces/structs and their purposes.
Issue: https://github.com/fedimint/fedimint/issues/1831
Link to branch: https://github.com/m1sterc001guy/fedimint/blob/db_tx_doc/docs/database.md

doc: adding database transaction diagram and explanation

---

fedimint-testing/src/bin/fixtures.rs

leftover from https://github.com/fedimint/fedimint/pull/1899

fix: remove dead code

---

flake.nix

I'm using it installed locally, but I think everyone should enjoy it.

chore(nix): install `nil` Nix LSP server

---

docs/building-new-modules.md
docs/database.md
docs/macos.md
docs/telemetry.md

* fixed some small typos in the docs
* updated links to renamed api in building new modules.md

chore: fix typos in docs

---

integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs
integrationtests/tests/fixtures/utils.rs
integrationtests/tests/tests.rs

fixed some typos in the integrationtests

fix typos in integrationtests

---

fedimint-server/src/consensus/mod.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

Fix latency tests for real

---

Cargo.lock
gateway/ln-gateway/Cargo.toml
gateway/ln-gateway/src/bin/gatewayd.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/lnd.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs
integrationtests/tests/tests.rs

Lnd Support

---

integrationtests/tests/fixtures/mod.rs

In response to https://discord.com/channels/990354215060795454/990354215878688860/1085998204463611904

fix: alias huge integration test fn trait

---

Cargo.lock
client/client-lib/Cargo.toml
fedimint-rocksdb/Cargo.toml
fedimint-sqlite/Cargo.toml
fedimint-testing/Cargo.toml

Fixes https://rustsec.org/advisories/RUSTSEC-2023-0018

chore: update tempfile

---

client/cli/src/main.rs

fixes #1931
gets rid of all module_decode_stubs() calls in fedimint-cli/main.rs

chore: create decoder registry in cli

---

scripts/cli-test.sh
scripts/latency-test.sh
scripts/reconnect-test.sh
scripts/test-ci-all.sh

`set -x` produces waay too much output.

fix: in scripts use `set -euo`, not `set -euox`

---

client/cli/src/main.rs

Refactor `fedimint-cli` to get rid of the `--workdir` hacks.
The root of the problem is that we don't know if we need a `Client` (and thus `--workdir`) before we know which sub-command we are handling. So lets accept that fact, and just build the client dynamically when we need it, instead of trying to maintain a list of places where we actually don't need it, etc.

fix: can't use `fedimint-cli decode-connect-info` without `--workdir`

---

Cargo.lock
fedimint-core/src/api.rs
fedimint-server/Cargo.toml
fedimint-server/src/config/api.rs
fedimint-server/src/config/mod.rs
fedimint-server/src/net/api.rs

Initial stab at the config API.  If we are good with this then it'll be a simple matter of implementing the rest of the endpoints with tests.
Related to #1893 #1628

Initial config API

---

integrationtests/tests/tests.rs

Reproduces error in #2017 confirmed on eletrs + esplora
Fixes #2017

Test tx already in blockchain

---

flake.nix

Build with:
```
nix bundle .#fedimintd -o fedimintd.bundled
```
This binary will work on any Linux machine (allegedly).
```
> ls -alh fedimintd.bundled
lrwxrwxrwx 1 dpc dpc 47 Mar 26 20:16 fedimintd.bundled -> /nix/store/mj1km415nd9j4na5bc7pvn1z3f1adxaz-arx
> ldd fedimintd.bundled 
not a dynamic executable
> ls -alh /nix/store/mj1km415nd9j4na5bc7pvn1z3f1adxaz-arx
-r-xr-xr-x 2 root root 51M Dec 31  1969 /nix/store/mj1km415nd9j4na5bc7pvn1z3f1adxaz-arx
> ls -alh /nix/store/mj1km415nd9j4na5bc7pvn1z3f1adxaz-arx
```
To get a `deb` to install on Debian/Ubuntu:
```
nix bundle --bundler github:NixOS/bundlers#toDEB .#fedimintd
```
```
> ls -alh deb-single-fedimintd-bin-fedimintd/fedimintd-bin-fedimintd_1.0_amd64.deb
-r--r--r-- 2 root root 43M Dec 31  1969 …
```

chore: ability to bundle a fedimintd package 

---

modules/fedimint-wallet-server/Cargo.toml
modules/fedimint-wallet-server/src/lib.rs

Fix wallet round consensus

---

fedimint-bitcoind/src/bitcoincore_rpc.rs

@justinmoon Fixes failure here https://github.com/fedimint/fedimint/issues/222#issuecomment-1487825777 which could could fedimintd to panic.

Remove panics from bitcoind RPC

---

codecov.yml

edit(justin): closes https://github.com/fedimint/fedimint/issues/2048

fix: make new codecov app happy

---

fedimint-core/src/admin_client.rs
fedimint-server/src/config/api.rs
fedimint-server/src/lib.rs
fedimintd/src/fedimintd.rs

Adds starting consensus to the config api

Api config v4

---

client/cli/src/lib.rs
crypto/tbs/examples/keygen.rs
fedimint-dbtool/src/main.rs
fedimint-testing/src/bin/fixtures.rs
fedimintd/src/fedimintd.rs
gateway/cli/src/main.rs
recoverytool/src/main.rs

Fixes #1562 
Please let me know if these changes are appropriate so that I can complete them for the other command definitions!

chore: change positional arguments to kwargs

---

.github/workflows/ci-nix.yml
flake.crane.nix
flake.nix

Fix #1891
I suspect some extra things might be needed here (like an entrypoint doing stuff), but this should be a good start.

feat: build gatewayd OCI container

---

client/cli/src/lib.rs
crypto/tbs/examples/keygen.rs
fedimint-dbtool/src/main.rs
fedimint-testing/src/bin/fixtures.rs
fedimintd/src/fedimintd.rs
gateway/cli/src/main.rs
recoverytool/src/main.rs

The tests were not updated.
fixes #2102 
Reverts fedimint/fedimint#2085

Revert "chore: change positional arguments to kwargs"

---

flake.crane.nix
scripts/always-fail-test.sh
scripts/always-success-test.sh
scripts/test-ci-all.sh

Test if we correctly detect test failures by introducing an artificial failure and re-running the whole thing. I can't think of any more e2e way.

chore(ci): more robust failure detection test

---

.tmuxinator.yml

Closes https://github.com/fedimint/fedimint/issues/1937

feat: Tmuxinator runs 4 panes tailing each fedimintd log

---

justfile

I just want to exit tmuxinator you know

feat: just exit tmuxinator alias

---

gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs
gateway/ln-gateway/src/rpc/rpc_server.rs

gateway: return FederationInfo for /connect-fed

---

gateway/ln-gateway/src/lib.rs

Reverts fedimint/fedimint#2099
compile errors on master

Revert "fix: skip connecting to federation if already connected"

---

fedimint-bin-tests/src/federation.rs
fedimint-dbtool/README.md
fedimint-testing/src/bin/fixtures.rs
scripts/build.sh
scripts/cli-test.sh
scripts/lib.sh
scripts/upgrade-test.sh

Following convention set by https://github.com/fedimint/fedimint/pull/2063

chore: rename FM_CFG_DIR to FM_DATA_DIR

---

fedimint-cli/src/lib.rs

Currently in tmuxinator you can use this command to fetch the list of gateways:
```
fedimint-cli api /module/0/list_gateways null
```
But that would check for consensus on the result. With this PR now you can just make the API call to a specific guardian. For example, to ask only the guardian with peer id 1:
```
api /module/0/list_gateways null 1
```
This can be useful to debug API calls where the results aren't enforced by consensus.

feat: Add optional peer_id parameter to `fedimint-cli api` command

---

justfile

feat: just lint-fix

---

fedimint-bin-tests/src/federation.rs
fedimint-bin-tests/src/main.rs
fedimint-bin-tests/src/util.rs
scripts/reconnect-test.sh

Step towards completing #2101 (2b). This PR rewrites `reconnect-test.sh` in Rust.

feat: rewrite reconnest-test.sh in rust

---

fedimint-core/src/core/server.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-testing/src/lib.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy-server/src/lib.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

Ban peers who submit multiple or missing round items

---

gateway/ln-gateway/src/actor.rs

When actors in `gatewayd` are processing htlcs, they wait on two futures (one is a signal that the thread should shutdown, the other is the htlc sent from the lightning node).
There is a race condition currently where we try to send a "shutdown" signal over a channel that then returns an error. This can happen during shutdown, where the webserver and the connection to the lightning node shutdown at the same time. Currently, we have some `expects` that will crash `gatewayd` if it can't send over the channel. This PR changes it to remove the `expects` so that `gatewayd` doesn't crash in this case.

fix: remove gatewayd reconnect expects

---

flake.lock
flake.nix
flake.toolchain.nix

Previously we were blocked on on lack of android SDK, but justin pointed me at:
https://github.com/tadfisher/android-nixpkgs
which should do the job.

fix: enable cross-compilation to android from macos

---

gateway/cli/Cargo.toml
gateway/ln-gateway/Cargo.toml

chore: explicitily import reqwest with rustls support

---

fedimint-core/src/db/mod.rs

`IsolatedDatabaseTransaction::raw_find_by_prefix` will get a `Stream`, transform it into a `Vec`, then transform into a `Stream` again destroying all the good things about streams in the process.
(Note the `.collect::<Vec<_>>()` followed by a `stream::iter(stream)` on the old code)
Why do this? Probably because if you just remove the `collect` then the borrow checker gets very nasty.
Yes, the borrow checker. Our friend, but sometimes our foe.
This solution works around that by decomposing the method into two functions, bypassing the struct ownership.
Probably there is a better solution if you play with the lifetimes. But there are times that our life time is too short.
(But everyone is invited to give it a try)
This was found during the review of …

fix: Let IsolatedDatabaseTransaction::raw_find_by_prefix stream all the way

---

gateway/ln-gateway/src/lnd.rs

Closes https://github.com/fedimint/fedimint/issues/1953

Implement route hint fetching for LND

---

scripts/rust-tests.sh
scripts/test-ci-all.sh

chore: run the 3 rust-tests sub-tests in parallel

---

fedimint-core/src/lib.rs
fedimint-core/src/timing.rs
fedimint-logging/src/lib.rs
fedimint-server/src/config/mod.rs
fedimintd/src/fedimintd.rs
flake.crane.nix
scripts/rust-tests.sh

chore: report more timings in major tests

---

fedimint-server/src/net/api.rs
integrationtests/tests/tests.rs

fix: Re-submitting an accepted transaction should not be an error

---

fedimint-testing/src/bin/fixtures.rs

This should help figure out the root cause of the random test hang bug.

chore(tests): log pids of processess being started

---

.gitignore

Fix https://github.com/fedimint/fedimint/issues/2067

chore: gitignore `./target` if a symlink

---

.codecov.yml

https://docs.codecov.com/docs/commit-status#target
Fix https://github.com/fedimint/fedimint/issues/2105

 chore: fix code coverage status symbols 

---

fedimint-bin-tests/src/main.rs
fedimint-bin-tests/src/util.rs

feat: faster fedimint bin tests

---

Cargo.lock
fedimint-cli/src/ng.rs
fedimint-client-legacy/src/lib.rs
fedimint-client-legacy/src/mint/mod.rs
fedimint-client-legacy/src/wallet/mod.rs
fedimint-client/src/lib.rs
fedimint-client/src/module/gen.rs
fedimint-client/src/module/mod.rs
fedimint-client/src/sm/executor.rs
fedimint-client/src/sm/mod.rs
fedimint-client/src/sm/state.rs
fedimint-client/src/transaction/sm.rs
fedimint-core/src/api.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/macros.rs
fedimint-core/src/module/mod.rs
fedimint-core/src/tiered_multi.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-mint-client/Cargo.toml
modules/fedimint-mint-client/src/input.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-mint-client/src/output.rs
modules/fedimint-wallet-client/src/lib.rs

client-ng: don't make modules aware of their instance id

---

Cargo.lock
fedimint-client-legacy/src/mint/mod.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/tiered_multi.rs
modules/fedimint-mint-client/Cargo.toml
modules/fedimint-mint-client/src/lib.rs

client-ng: Don't load all e-cash notes

---

fedimint-bin-tests/src/federation.rs
fedimint-client-legacy/src/api.rs
fedimint-client-legacy/src/ln/mod.rs
fedimint-client-legacy/src/mint/mod.rs
fedimint-client-legacy/src/wallet/mod.rs
fedimint-client/src/transaction/sm.rs
fedimint-core/src/api.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs
fedimint-testing/src/lib.rs
gateway/ln-gateway/tests/fixtures/fed.rs
modules/fedimint-dummy-server/src/lib.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs
scripts/lib.sh

Fixes #1280
Note that I didn't change any of the routes for the LN gateway which is using REST instead of WS (although we probably should change that to make it consistent #2293)

chore: Sanitize paths in api_endpoint

---

fedimint-core/src/tiered.rs
fedimint-core/src/tiered_multi.rs
fedimintd/src/distributed_gen.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-mint-server/src/lib.rs

fix: Ensure federation can handle bigger on chain deposits

---

fedimint-core/src/encoding/mod.rs

fix: remove unused `SerdeEncodable`

---

fedimintd/templates/params.html

feat: add signet option to setup UI

---

Cargo.lock
fedimint-bitcoind/Cargo.toml
fedimint-client-legacy/Cargo.toml
fedimint-client-legacy/src/api/fake.rs
fedimint-core/Cargo.toml
fedimint-core/src/api.rs
integrationtests/tests/fixtures/user.rs
integrationtests/tests/tests.rs
misc/git-hooks/pre-commit

chore: get rid of openssl

---

fedimint-server/src/config/api.rs

As discussed, this change enables the leader to set the configs before/after/during receiving connections from peers.

feature: remove the state constraints in the config gen API

---

flake.crane.nix

Lots of effort, not a lot of benefit.

refactor(crane): don't filter pkg dirs manually

---

gateway/ui/.eslintrc.json
gateway/ui/package.json
gateway/ui/yarn.lock
guardian-ui/.eslintrc.json
guardian-ui/package.json
guardian-ui/yarn.lock

Adds prettier to the eslint config so they do not conflict.

fix: avoids eslint and prettier conflict in Guardian UI

---

.github/workflows/ci-nix.yml
flake.nix

Closes #2282 (Unless there's some gateway-cli config that I missed for the containerization)

feat: build gateway-cli OCI container.

---

devimint/src/main.rs

Should help debugging this issue https://github.com/fedimint/fedimint/issues/2341

fix: don't hard-code amount in balance assertion

---

guardian-ui/README.md

README with basics for running the UI.

chore: Guardian UI README init

---

fedimint-cli/src/ng.rs
fedimint-client/src/sm/util.rs
modules/fedimint-ln-client/src/api.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-client/src/pay.rs
modules/fedimint-ln-client/src/receive.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-wallet-client/src/lib.rs

Implementation of the lightning client receive state machine that awaits for the LightingGateway to fund an `IncomingContract` that can be claimed by the client.

feat: Lightning Client Receive State Machine

---

devimint/src/util.rs

chore(devimint): add context on missing daemon binary

---

fedimint-client/src/lib.rs

This will be needed for things like making and restoring from backups.

chore: ability to build `Client` without starting executor yet

---

fedimint-server/src/config/api.rs

Was getting a panic from calling `run_dkg` twice rapidly.  This will return an API error instead by holding onto locks until the status has been changed to prevent re-entry.

fix: lock config gen api states to prevent re-entry

---

Cargo.lock
fedimint-bitcoind/Cargo.toml
fedimint-bitcoind/src/lib.rs
fedimint-logging/src/lib.rs

chore: add target to bitcoind log macro using constant

---

gateway/ui/src/components/ConnectFederation.tsx

Fix: validation logic in Gateway UI

---

fedimint-client/src/lib.rs

https://github.com/fedimint/fedimint/pull/2270#discussion_r1175840055

fix(client-ng): use `insert_new_entry` to write operation log

---

fedimint-core/src/db/mem_impl.rs
fedimint-core/src/db/mod.rs
fedimint-rocksdb/src/lib.rs
fedimint-sqlite/src/lib.rs

Closes https://github.com/fedimint/fedimint/issues/2329

refactor: Make result_find_by_prefix return a result

---

misc/git-hooks/pre-commit

It starts to be a bit annoying, so makes sense to optimize a bit.

feat(lint): faster pre-commit hook

---

scripts/build.sh

fix: logs for run-ui

---

fedimint-client/src/lib.rs
fedimint-client/src/sm/mod.rs
fedimint-client/src/transaction/sm.rs

Fixes https://github.com/fedimint/fedimint/pull/2404#discussion_r1187987544

feat(client-ng): allow adding state machines from inside transitions

---

Cargo.lock
Cargo.toml
fedimint-testing/src/fixtures.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/tests/integration_tests.rs
modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-dummy-tests/tests/tests.rs
modules/fedimint-ln-tests/tests/tests.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-mint-common/src/config.rs
modules/fedimint-mint-tests/Cargo.toml
modules/fedimint-mint-tests/tests/tests.rs

- Defaults fed size to 1 for mocked tests
- First mint module test for OOB payment
- Fixes LN gateway not waiting to connect to fed, caused a test to fail, should return error and retry client side

First mint tests

---

modules/fedimint-ln-client/src/lib.rs

This is nice to have. It's already there in the `LightningMeta::Pay` variant.

feat(ln-client): Add invoice to LightningMeta::Pay

---

Cargo.lock
devimint/Cargo.toml
fedimint-bitcoind/Cargo.toml
fedimint-bitcoind/src/lib.rs
fedimint-build/Cargo.toml
fedimint-testing/Cargo.toml
fedimint-testing/src/fixtures.rs
fedimint-testing/src/gateway.rs
fedimint-testing/src/ln/mock.rs
fedimintd/Cargo.toml
gateway/ln-gateway/src/rpc/mod.rs
gateway/ln-gateway/tests/integration_tests.rs
modules/fedimint-dummy-common/src/config.rs
modules/fedimint-dummy-server/src/lib.rs
modules/fedimint-dummy-tests/tests/tests.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-tests/Cargo.toml
modules/fedimint-ln-tests/tests/tests.rs
modules/fedimint-mint-tests/tests/tests.rs
modules/fedimint-wallet-server/Cargo.toml
modules/fedimint-wallet-server/src/lib.rs
modules/fedimint-wallet-tests/Cargo.toml

Starts the ln test, but we can't easily finish it until the gateway is using the new client.

feature: start on the ln send test

---

Cargo.lock
fedimint-cli/src/lib.rs
fedimint-cli/src/ng.rs
fedimint-client/Cargo.toml
fedimint-client/src/backup.rs
fedimint-client/src/lib.rs
fedimint-client/src/module/mod.rs
fedimint-client/src/sm/executor.rs
fedimint-client/src/sm/mod.rs
fedimint-client/src/transaction/sm.rs
fedimint-core/src/api.rs
fedimint-core/src/backup.rs
fedimint-core/src/core.rs
fedimint-core/src/core/backup.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/lib.rs
fedimint-logging/src/lib.rs
fedimint-server/src/net/api.rs
modules/fedimint-mint-client/Cargo.toml
modules/fedimint-mint-client/src/backup.rs
modules/fedimint-mint-client/src/backup/recovery.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-mint-client/src/output.rs
modules/fedimint-mint-common/src/lib.rs

Integrate backup restore into ClientBuilder

---

Cargo.lock
Cargo.toml
fedimint-bip39/Cargo.toml
fedimint-bip39/src/lib.rs
fedimint-cli/src/lib.rs
fedimint-cli/src/ng.rs
fedimint-client/src/backup.rs
fedimint-client/src/db.rs
fedimint-client/src/lib.rs
fedimint-client/src/secret.rs
fedimint-testing/src/federation.rs

feat(client-ng): make client root secret encoding flexible using strategy pattern

---

devimint/src/lib.rs
devimint/src/main.rs
scripts/run-ui.sh

Allow variable number of servers in `run-ui`

---

fedimint-ui/apps/gateway-ui/package.json
fedimint-ui/apps/guardian-ui/package.json
flake.nix
misc/mprocs-ui.yaml
scripts/run-ui.sh

Builds on: https://github.com/fedimint/fedimint/pull/2513 by @wbobeirne 
and checks for nix shell before running. Also starts 4 fedimintd's and UI's for `just run-ui`

Run 4 Servers with `just run-ui`

---

fedimint-core/src/config.rs
fedimint-ui/apps/guardian-ui/src/GuardianContext.tsx
fedimint-ui/apps/guardian-ui/src/components/ConnectGuardians.tsx
fedimint-ui/apps/guardian-ui/src/components/SetConfiguration.tsx
fedimint-ui/apps/guardian-ui/src/types.tsx
modules/fedimint-mint-common/src/config.rs

- Updates api transalation in guardian setup ui after #2540

fix(ui): update guardian api types

---

fedimint-client-legacy/src/lib.rs
modules/fedimint-ln-client/src/lib.rs

We don't need it since amountless invoices aren't supported anyway and the gateway isn't aware of the payment secret.
Fixes #2370

fix(ln): remove payment secret from invoice

---

fedimint-core/src/config.rs
fedimint-server/src/config/mod.rs
fedimintd/src/distributed_gen.rs

better DKG failures if modules are missing 

---

fedimint-cli/src/lib.rs
fedimint-client-legacy/src/api/fake.rs
fedimint-client-legacy/src/lib.rs
fedimint-client-legacy/src/utils.rs
fedimint-client/src/lib.rs
fedimint-client/src/module/mod.rs
fedimint-client/src/transaction/sm.rs
fedimint-core/src/admin_client.rs
fedimint-core/src/api.rs
fedimint-server/src/consensus/server.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/tests/fixtures/client.rs
modules/fedimint-dummy-client/src/api.rs
modules/fedimint-ln-client/src/api.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-client/src/pay.rs
modules/fedimint-mint-client/src/backup.rs
modules/fedimint-mint-client/src/backup/recovery.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-wallet-client/src/api.rs

feature: split out global and module api traits

---

Cargo.lock
devimint/src/external.rs
devimint/src/main.rs
fedimint-cli/src/ng.rs
fedimint-client/src/sm/executor.rs
fedimint-client/src/sm/notifier.rs
modules/fedimint-wallet-client/Cargo.toml
modules/fedimint-wallet-client/src/deposit.rs
modules/fedimint-wallet-client/src/lib.rs
modules/fedimint-wallet-common/src/config.rs
modules/fedimint-wallet-server/src/lib.rs

* Minor API fixes
* Deposit state machine
* Deposit method in extension traits

Client-NG: Deposits

---

modules/fedimint-mint-client/src/lib.rs

* Trigger balance update on OOB spend (fixes #2561)
* Trigger balance update on successful recovery

Fixup #2537: more balance update conditions

---

flake.nix

fix: copy in mprocs

---

modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-client/src/pay.rs
modules/fedimint-ln-client/src/receive.rs
modules/fedimint-ln-common/src/api.rs
modules/fedimint-ln-common/src/contracts/incoming.rs
modules/fedimint-ln-common/src/contracts/outgoing.rs
modules/fedimint-ln-common/src/lib.rs

This will help make them usable by the new gateway client.

chore: move some stuff from fedimint-ln-client to fedimint-ln-common

---

fedimint-client-legacy/src/lib.rs
fedimint-client-legacy/src/mint/mod.rs

Just protect them with a mutex, bolted a bit ad-hoc in there.
In seems that in the gateway we already handle incoming payments on a separate task, without any protection, and in the Fedi Alpha deployement we've noticed some strage behavior where some outputs/notes seems to be missing etc.
This should also enable some concurrent usage of the `Client`, serializing only what we know is not safe.

chore: protect legacy client high-level note-related operations from concurrent use

---

fedimint-ui/README.md
fedimint-ui/apps/gateway-ui/README.md
fedimint-ui/apps/gateway-ui/package.json
fedimint-ui/apps/guardian-ui/README.md
fedimint-ui/apps/guardian-ui/package.json
flake.nix
justfile
scripts/run-ui.sh

also fix: our ui shell didn't have correct cargo

chore: merge fedimint-ui devshell into default shell

---

devimint/src/main.rs
fedimint-core/src/encoding/mod.rs
fedimint-core/src/epoch.rs
modules/fedimint-mint-client/src/lib.rs

Fixes the issue described in https://github.com/fedimint/fedimint/issues/2514#issuecomment-1555368893

fix(wallet-client): don't fail on self-reissue

---

modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-tests/tests/tests.rs

fix(ln-client): check lightning invoice currency

---

modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-dummy-client/src/states.rs

While working on the gateway receive state machines, I found two bugs with the dummy client.
1. `receive_money` adds the current balance from the `DummyOutputOutcome` onto the current balance, instead of the difference.
2. Both the input state and the output state use `Done` has their sync state, so `Done` will be emitted twice which makes it difficult to await on the output of a transaction with both an input and output from the dummy module.
This PR changes:
1. `receive_money` just takes the new balance from the `DummyOutputOutcome`
2. Adds `InputDone` and `OutputDone` so `await_primary_module_output` can just wait for `OutputDone` to be reached.

fix: dummy client uses wrong amount when receiving funds

---

gateway/ln-gateway/src/ng/mod.rs
gateway/ln-gateway/src/ng/receive.rs
gateway/ln-gateway/src/ng/tests.rs
modules/fedimint-ln-client/src/lib.rs

Gateway state machine for funding an incoming contract and decrypting the preimage.

feat: gateway incoming state machine

---

gateway/ln-gateway/src/db.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/ng/mod.rs
gateway/ln-gateway/src/ng/register.rs
gateway/ln-gateway/src/ng/tests.rs

Adds a state machine for registering the lightning gateway with the federation.

feat: register gateway state machine

---

modules/fedimint-ln-tests/tests/tests.rs

Assert that the state machine actually terminates successfully

feat: assert more states with internal tests

---

devimint/src/external.rs
devimint/src/main.rs
docs/database.md
fedimint-core/src/api.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/consensus/server.rs
fedimint-server/src/net/api.rs
integrationtests/tests/tests.rs
modules/fedimint-dummy-server/src/lib.rs
modules/fedimint-ln-common/src/incoming.rs
modules/fedimint-ln-common/src/lib.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs
nix/craneCommon.nix

I was looking and the code and found some typos...

fix: minor typos

---

Cargo.lock
crypto/aead/src/lib.rs
fedimint-testing/src/federation.rs
fedimint-testing/src/fixtures.rs
gateway/ln-gateway/src/ng/tests.rs
gateway/ln-gateway/tests/fixtures.rs
modules/fedimint-ln-tests/tests/tests.rs
modules/fedimint-wallet-client/src/deposit.rs
modules/fedimint-wallet-tests/Cargo.toml
modules/fedimint-wallet-tests/tests/tests.rs
scripts/rust-tests.sh

Start testing the new wallet tests against real bitcoind.
Will need more changes to get real LN tests working.

test: add wallet tests against real bitcoind

---

devimint/src/main.rs
fedimint-load-test-tool/src/common.rs

refactor(load-test-tool): use ng cli by default

---

Cargo.lock
fedimint-cli/Cargo.toml
fedimint-cli/src/lib.rs
gateway/cli/Cargo.toml
gateway/cli/src/main.rs
scripts/completion.sh
scripts/user-shell.sh

gateway-cln doesn't work because bash doesn't understand it wraps gateway-cli

shell completions for fedimint-cli in mprocs

---

docs/dev-running.md

There are no default notes on the old client, making the current guide very confusing. Also the gateway commands changed.

fix: update some commands on docs

---

fedimint-core/src/api.rs
fedimint-core/src/query.rs

In a common api versions discovery PR, I needed to express an error where not a single memeber was actually at fault, and I had to do it using member errors field and a fake, fixed `peer-0`.
This change addrs a field for `general` member error.

feat: a "general" federation api error

---

fedimint-load-test-tool/src/main.rs

feat(load-test-tool): add optional sleep after ln payment

---

misc/git-hooks/commit-msg

fixes https://github.com/fedimint/fedimint/issues/2336

fix: handle fixup! correctly in commit-msg hook

---

Cargo.lock
gateway/cli/Cargo.toml
modules/fedimint-ln-common/Cargo.toml

https://github.com/fedimint/fedimint/actions/runs/5440952265/jobs/9894377345

fix: daily check build failing

---

gateway/ln-gateway/src/lnd.rs

A group of us were trying to debug problems connecting gatewayd to lnd in the https://github.com/fedimint/ui repo. Could use a little more info.

feat: log error message when gateway can't connect to lnd

---

fedimint-build/src/lib.rs
fedimint-cli/src/lib.rs
fedimint-server/src/config/io.rs
flake.nix
gateway/cli/src/main.rs
gateway/ln-gateway/src/bin/cln_extension.rs
gateway/ln-gateway/src/bin/gatewayd.rs
gateway/ln-gateway/src/lib.rs
nix/craneCommon.nix

Don't silently ignore failures.

fix: improve version hash detection and handling

---

fedimint-bitcoind/src/lib.rs
fedimint-core/src/bitcoinrpc.rs
fedimint-server/src/net/peers.rs
fedimintd/src/fedimintd.rs

Improves user experience while running `fedimintd` from scratch

feat: better error reporting

---

fedimint-atomic-broadcast/tests/integration.rs

Re: https://github.com/fedimint/fedimint/issues/2741

chore: disable slow tests

---

modules/fedimint-dummy-client/src/lib.rs

So no idea what was:
https://github.com/fedimint/fedimint/actions/runs/5507104672/jobs/10036623154?pr=2742
about

fix: error being swallowed

---

Cargo.lock
gateway/ln-gateway/Cargo.toml
gateway/ln-gateway/src/lnd.rs

This version now has `invoicesrpc` feature, accessible if needed

feat: bump tonic_lnd dependency

---

fedimint-client/src/lib.rs

fixes #2701 after #2753 is merged

fix: Arc cycle in Client

---

.github/workflows/extra-docker-images.yml
docker/fedimintd/docker-compose.yaml
docker/gateway-mutinynet/docker-compose.yaml
docker/mutinynet-bitcoind-docker/Dockerfile

Plus minor changes.
More documentation to come in further PRs
(Improves https://github.com/fedimint/fedimint/issues/2665)

feat: docker for running gateway/mutinynet

---

gateway/ln-gateway/src/lnd.rs
gateway/ln-gateway/src/ng/pay.rs

Fixes: https://github.com/fedimint/fedimint/issues/2747
Also addresses: https://github.com/fedimint/fedimint/issues/2301
The crux of the stuck payments issue for LND is that `SendPaymentV2` and `SendPaymentSync` are not atomic. This means that if they're pre-empted while executing, it is possible that the payment becomes stuck and will not succeed. 
To fix this, I have moved `buy_preimage_over_lightning` into the transition function so that it can leverage the state machine framework's atomicity when moving between states. Since this function is already idempotent, I believe this is a safe refactor.
I'm now able to get 20+ concurrent payments with LND gateway (maybe more, haven't tried higher)
`fedimint-load-test-tool --users 20 load-test --generate-invoice-with cln-lightning-cli`

fix: LND Stuck Payments

---

fedimint-core/src/encoding/mod.rs

Re #2763
I'm sure that at some point in the past in the CI I've seen panics due to trying to allocate block of unsanitized length in decoding, but I was never able to figure out what caused it.
This is so far my best guess, but I wasn't able to reproduce the problem for some reason, even thought tracing the code I'm quite sure it's there. stdlib is using non trivial generic trait specializations, so I might have missed something. One way or another, at least in theory I think the current problem is not safe.

fix: panic on malicious len when decoding `Vec`

---

devimint/src/main.rs

It may take a while for the gateway to be able to connect to the ln node.
It seems that previously the test would consider that if `gateway-cli info` returns successful then it means that this reconnection have already happened. But this isn't the case.
So we try to pay the invoice at most 10 times, waiting 1 second between each retry, and only fail after that.

fix: lightning_gw_reconnect_test not flaky anymore

---

.github/workflows/extra-docker-images.yml
docker/fedimintd-mutinynet/docker-compose.yaml
docker/gateway-mutinynet/docker-compose.yaml

Related to https://github.com/fedimint/ui/pull/85

chore: more docker tags

---

docs/meta_fields/README.md
docs/meta_fields/federation_expiry_timestamp.md
docs/meta_fields/federation_name.md
docs/meta_fields/meta_override_url.md
docs/meta_fields/welcome_message.md

This PR adds instructions how to standardize meta fields and adds descriptions for some that have already been in use. [You can view a rendered version here.](https://github.com/fedimint/fedimint/blob/a868b8a0e07b4fcd4612f67f8ae5f574094185a7/docs/meta_fields/README.md)
Related to #2719

feat(docs): document meta fields

---

fedimint-server/src/config/api.rs

Followers wait for guardian server to get to `ReadyForConfigGen`, thus signalling all guardians are ready for DKG
depends on #2790

feat: wait for leader to signal ready for DKG

---

gateway/ln-gateway/src/bin/cln_extension.rs

Simple rename to fix: https://github.com/fedimint/fedimint/issues/2737

rename: prefix gateway extension CLN options

---

fedimint-server/src/config/api.rs

After a guardian has already verified configs from other peers and proceeded to `VerifiedConfigs` state added in #2807, they should still have the ability to fetch and share their own config hash. Helps fix https://github.com/fedimint/ui/issues/14.

fix: allow get_verify_config_hash after verification is done

---

modules/fedimint-wallet-server/src/lib.rs
recoverytool/src/main.rs

Fix wallet change tweak derivation and recoverytool

---

devimint/src/main.rs
gateway/ln-gateway/src/ng/tests.rs

* Add logging to flaky test encountered in #2804 for debugging next time: https://github.com/fedimint/fedimint/actions/runs/5616067369/job/15217649916?pr=2804#step:9:8282
* Fix flaky test encountered in this PR by re-trying https://github.com/fedimint/fedimint/actions/runs/5621050947/job/15231130231?pr=2809#step:9:271

Debug+fix flaky tests

---

docker/full-tls-mutinynet/docker-compose.yaml
docker/tls-download-mutinynet.sh

Full federation (fedimintd + gatewayd + lnd + bitcoind) using a TLS (Let's Encrypt) setup with hostnames.
Docs to come in future PRs

feat: docker compose for mutinyet with TLS

---

gateway/ln-gateway/src/bin/cln_extension.rs

CLN extensions now support options without default parameters. 
Fixes: https://github.com/fedimint/fedimint/issues/1244

remove: remove default-dont-use from CLN extension

---

fedimint-core/src/module/mod.rs
fedimint-server/src/config/api.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs

replicates #2820 for the consensus api

feat: add consensus gen auth endpoint for validating password

---

gateway/ln-gateway/src/ng/pay.rs
gateway/ln-gateway/src/ng/tests.rs

Fixes: https://github.com/fedimint/fedimint/issues/2627

fix: Check invoice expiry before paying

---

devimint/src/util.rs

fix: panics possible due to `SystemTime` not being monotonic

---

devimint/src/main.rs
fedimint-server/src/consensus/mod.rs
modules/fedimint-mint-client/src/backup/recovery.rs

See commit messages.
Fix #2842

fix(consensus): processing same tx submitted multiple times 

---

.github/workflows/ci-nix.yml

Rework of #2771
Mostly w.r.t moving deb&rpm bundling to a step that already built these packages anyway.

chore: build and upload deb&rpm binaries 

---

fedimint-wasm-tests/src/lib.rs

chore(tests): add WASM test for ring chacha20 being available

---

fedimint-server/src/consensus/mod.rs

We remove the autocommit here since there should never be write conflicts for consensus state. If there is a conflict we would rather crash instead of continuing with inconsistent state.

fix: remove autocommit

---

fedimint-testing/src/ln/mod.rs
gateway/ln-gateway/src/ng/tests.rs

Closes https://github.com/fedimint/fedimint/issues/2906

Reactivate test_gateway_client_pay_invalid_invoice and improve documentation

---

fedimint-server/src/net/connect.rs
fedimint-server/src/net/peers.rs

Our network stack assumes that broken connections
a) are reliable or break completely
b) broken connections are noticed by both sides eventually
So far the mock network has not conformed to these requirements, causing flaky tests.
Alternative to #2901

fix(core): fix mock network

---

fedimint-cli/src/lib.rs
fedimint-client/src/lib.rs
fedimint-client/src/sm/executor.rs
fedimint-client/src/transaction/sm.rs
fedimint-core/src/task.rs
fedimint-load-test-tool/src/common.rs
fedimint-load-test-tool/src/main.rs
fedimint-testing/src/federation.rs
fedimint-wasm-tests/src/lib.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs

Possible alternative to #2891.

fix(client): make client independent on task groups

---

devimint/src/lib.rs

Improve logging to help debug recurrences of https://github.com/fedimint/fedimint/actions/runs/5719826045/job/15498532948?pr=2796#step:9:18858

chore: devimint logs more when gateway-cli connect-fed fails

---

gateway/ln-gateway/src/ng/mod.rs

I have noticed `test_gateway_cannot_pay_expired_invoice` fail sometimes because the refund transaction is not accepted by the federation: https://github.com/fedimint/fedimint/actions/runs/5777285019/job/15657290448#step:9:6985
This PR just modifies the error message a bit to help with debugging.
@elsirion @joschisan any ideas on what might cause a refund transaction to not be accepted?

chore: improve error message when refund transaction fails to be accepted

---

fedimint-client/src/transaction/sm.rs

Don't fail transactions when the client is offline or there are other temporary failures.

fix(client-ng): retry submitting tx

---

fedimint-core/src/db/mem_impl.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/db/notifications.rs
fedimint-rocksdb/src/lib.rs

Looking at #2926 . Some initial cleanup.

 chore: unify common db ops under one trait 

---

fedimint-core/src/api.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/encoding/as_hex.rs
fedimint-core/src/epoch.rs
fedimint-dbtool/src/dump.rs
modules/fedimint-wallet-common/src/lib.rs

chore: serialize and dump some consensus types better

---

fedimint-rocksdb/src/lib.rs

fix: rocksdb still running blocking operations in async runtime

---

Cargo.lock
fedimint-core/src/module/mod.rs
modules/fedimint-mint-server/Cargo.toml
modules/fedimint-mint-server/src/lib.rs

test(mint): test double spends are not possible

---

Cargo.lock
fedimint-client/Cargo.toml
fedimint-client/build.rs
fedimint-client/src/lib.rs

Closes #2886
Please refer to the issue discussion for context and approach to verifying changes.

Log fedimint client git hash on executor start

---

scripts/dev/run-isolated-test/fm-run-isolated-test
scripts/test-ci-all.sh

chore: "fix" test-ci-all.sh on MacOS

---

.github/workflows/ci-nix.yml

Example: https://github.com/fedimint/fedimint/actions/runs/5895608638?pr=2980

feat(ci): upload logs of failed builds

---

fedimint-server/src/db.rs
fedimint-testing/src/db.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

chore: better logging of failed validated_migrations

---

Cargo.lock
Cargo.toml
crypto/tbs/src/lib.rs
devimint/src/federation.rs
devimint/src/main.rs
devimint/src/util.rs
devimint/src/vars.rs
fedimint-cli/src/client.rs
fedimint-client-legacy/src/lib.rs
fedimint-client/src/lib.rs
fedimint-client/src/sm/executor.rs
fedimint-core/src/api.rs
fedimint-core/src/config.rs
fedimint-load-test-tool/src/main.rs
fedimint-server/src/config/distributedgen.rs
fedimint-server/src/db.rs
fedimint-testing/src/db.rs
fedimint-wasm-tests/src/lib.rs
flake.lock
flake.nix
flake.toolchain.nix
gateway/ln-gateway/src/bin/cln_extension.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

I was looking into some slowness in the CI, and it would be improved with sparse index support which was recently made stable
https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol
(+ made default in 1.70).
There's a separate PR for miniscript update, which seems to be required here as well: https://github.com/fedimint/fedimint/pull/2950

chore: Rust  toolchain update

---

devimint/src/lib.rs
devimint/src/util.rs

I've seen it failing, and I think it just happened to get a bit slow.

fix: more retries in devimint's connect-fed 

---

devimint/src/util.rs

(This is related to https://github.com/fedimint/fedimint/pull/2853 and https://github.com/fedimint/fedimint/pull/2873)
Today we suppose processes are killed almost immediately after a SIGKILL. But this isn't always the case, it's very possible for devimint to exit and then we start a new one and the new daemons will fail because the older ones are not quite dead and using the same listen address.
(if this happen inside the context of tests, the tests may keep retrying for many minutes before some timeout or retry limit happens)
So now devimint will always await for the processes to exit.

fix(devimint): always await after SIGKILL

---

fedimint-bitcoind/src/bitcoincore.rs

fix(bitcoinrpc): off-by-one in block count

---

devimint/src/main.rs
integrationtests/README.md
scripts/build.sh
scripts/dev/mprocs/run.sh
scripts/dev/tmuxinator/run.sh
scripts/lib.sh
scripts/tests/rust-tests.sh
scripts/tests/wasm-tests.sh

fix: remove FM_PID_FILE 

---

docs/gateway.md
fedimint-testing/src/federation.rs
fedimint-testing/src/fixtures.rs
fedimint-testing/src/ln/mock.rs
fedimint-testing/src/ln/real.rs
fedimintd/src/fedimintd.rs
gateway/ln-gateway/build.rs
gateway/ln-gateway/proto/gateway_lnrpc.proto
gateway/ln-gateway/src/bin/cln_extension.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/lnd.rs
gateway/ln-gateway/src/lnrpc_client.rs
gateway/ln-gateway/src/ng/complete.rs
gateway/ln-gateway/src/ng/mod.rs
gateway/ln-gateway/src/ng/pay.rs
gateway/ln-gateway/src/types.rs
integrationtests/tests/fixtures/mod.rs

- Renames `gatewaylnrpc` to `gateway_lnrpc`
- Changes uses of `decoders` to `available_decoders`

fix: Change decoders to available_decoders

---

Cargo.lock

chore: update rustls-webpki

---

fedimint-client/src/lib.rs

feat(client): expose secret derived from seed for external use

---

fedimint-core/src/api.rs
fedimint-core/src/fmt_utils.rs
fedimint-core/src/query.rs
fedimint-server/src/consensus/server.rs

chore: improve output on start of `just mprocs`

---

justfile
misc/git-hooks/pre-commit

 chore: optimize pre-commit check

---

devimint/src/external.rs

Fixes: https://github.com/fedimint/fedimint/issues/2827

fix: allow LND to pay < 1 sat invoices

---

.github/workflows/ci-nix.yml

feat: publish docker with a tagged release

---

Cargo.lock
devimint/src/external.rs
fedimint-testing/src/btc/real.rs
fedimint-testing/src/fixtures.rs
modules/fedimint-wallet-client/src/deposit.rs
modules/fedimint-wallet-server/src/lib.rs
modules/fedimint-wallet-tests/Cargo.toml
modules/fedimint-wallet-tests/tests/tests.rs

Fully migrate an old integration test that was removed (https://github.com/fedimint/fedimint/pull/2969#pullrequestreview-1581944324)
Update:
Found that some code was mixing block height and block count without the proper precautions. Fixed that

feat(wallet-tests): add peg_ins_that_are_unconfirmed_are_rejected

---

flake.nix
nix/craneCommon.nix

Backporting https://github.com/fedimint/fedimint/pull/3047

backport: *do* strip symbols on MacOS

---

.github/workflows/ci-nix.yml
.github/workflows/extra-docker-images.yml

Backport: CI on release branch

---

.cargo/audit.toml

Backport: chore: add audit configuration file

---

gateway/ln-gateway/src/ng/tests.rs
modules/fedimint-ln-client/src/lib.rs

Fixes: https://github.com/fedimint/fedimint/issues/3031

fix: always add one hop route hint

---

misc/git-hooks/commit-msg
misc/git-hooks/pre-commit

There's no reason not to just wrap it in a nix develop shell for their convenience.

fix: git hooks not working in VSCode not started in Nix shell

---

docker/fedimintd-mutinynet/docker-compose.yaml
docker/full-tls-mutinynet/docker-compose.yaml
docker/gateway-mutinynet/docker-compose.yaml
scripts/dev/change-docker-tags.sh

Let docker-compose files use a tagged release.

feat: tag docker with release tag

---

scripts/tests/backend-test.sh

Problem causing these is described in https://github.com/ipetkov/crane/issues/370 , but I actually just need to to show up so I remember about it.

chore: surface needless rebuilds

---

fedimint-cli/src/client.rs
fedimint-client/src/oplog.rs
gateway/ln-gateway/src/ng/tests.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-common/src/lib.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-wallet-client/src/lib.rs

Fixes #3028
Fixes #3029 
Fixes #3030

Client operation log ergonomic improvements

---

fedimint-server/src/net/api.rs

This will help @wbobeirne finish the guardian MVP implementation. See [discussion on discord](https://discord.com/channels/990354215060795454/990354215878688860/1146567059610808330).

feat: module_json RPC command

---

fedimint-core/src/config.rs
fedimint-server/src/config/api.rs

fix(api): stacktrace in an api error

---

modules/fedimint-wallet-server/src/lib.rs

Fix #3069
```
> fedimint-cli dev api module_2_block_count
2023-09-01T18:58:46.559652Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-09-01T18:58:46.559655Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-09-01T18:58:46.560027Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
{
"value": 284
}
> fedimint-cli dev api module_2_block_count_local
2023-09-01T19:00:01.080251Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-09-01T19:00:01.080371Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-09-01T19:00:01.080948Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner …
```

feat(module/wallet): add `block_count_local` api

---

gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs

[Backport releases/v0.1] feature(gateway): add ClientConfig to FederationInfo for /info api endpoint

---

devimint/src/federation.rs
devimint/src/util.rs
fedimint-server/src/config/api.rs
fedimintd/src/fedimintd.rs

```
> env FM_EXTRA_DKG_META=foo=bar just mprocs
```
gives:

feat: pass extra dkg meta to fedimintd

---

.github/workflows/ci-nix.yml
flake.nix

Use `nix build -L .#container.fedimint-devtools` to build locally.

feat(nix): build and publish `fedimint-devtools` container

---

.github/workflows/ci-nix.yml
.github/workflows/daily.yml
.github/workflows/docs.yml

Fixes https://github.com/fedimint/fedimint/issues/3129
Followup to https://github.com/fedimint/fedimint/pull/3114#pullrequestreview-1612985083

chore: prevent gh workflows with secrets on forks

---

misc/git-hooks/commit-msg

It's not important if it doesn't contain an emoji.

 chore: better error on invalid commit message 

---

Cargo.lock
Cargo.toml
fedimint-testing/Cargo.toml
fedimint-testing/src/fixtures.rs
integrationtests/Cargo.toml
integrationtests/tests/fixtures/mod.rs
justfile
nix/craneCommon.nix
utils/portalloc/Cargo.toml
utils/portalloc/src/data.rs
utils/portalloc/src/data/dto.rs
utils/portalloc/src/lib.rs
utils/portalloc/src/util.rs

All the cool projects are already using `cargo nextest` for these [sweet, sweet features](https://nexte.st/index.html#features), including much better performance, and we're still doing `cargo test` like we're stuck in the past.
This change unlocks the future and grants us new bragging rights.

feat: cargo nextest support

---

.config/nextest.toml
flake.nix
nix/craneBuild.nix
nix/craneCommon.nix

 chore: use cargo-nextest in some places in the CI (more to follow) 

---

modules/fedimint-mint-client/src/output.rs

First step towards fixing #3173.

fix(mint-client): retry failed output outcome fetching

---

.github/workflows/backport.yml

This will allow the bot to run CI automatically without human intervention.
I created the @fedimint-backports account for this, lmk if I should change anything about it.

chore: use backport bot account

---

.github/workflows/ci-nix.yml
.github/workflows/daily.yml
.github/workflows/docs.yml

- Closes https://github.com/fedimint/fedimint/issues/3137
- Backports https://github.com/fedimint/fedimint/pull/3130
(cherry picked from commit b892896452fdaadb5c12c2094b66d6189fafd6ed)

Backport 3130 to release/v0.1

---

gateway/ln-gateway/src/bin/cln_extension.rs

Fixes: https://github.com/fedimint/fedimint/issues/3171
This will probably require CLN users to update their CLN version

refactor: use new ListPeersChannel RPC for CLN extension

---

modules/fedimint-wallet-common/src/config.rs
modules/fedimint-wallet-server/src/lib.rs

fix: wallet module spaming epochs

---

gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs
gateway/ln-gateway/src/rpc/rpc_server.rs
gateway/ln-gateway/tests/integration_tests.rs

Fixes: https://github.com/fedimint/fedimint/issues/3158

feat: expose gateway state

---

Cargo.toml
nix/craneBuild.nix
scripts/tests/backend-test.sh
scripts/tests/test-ci-all.sh

Re: https://github.com/ipetkov/crane/issues/370
Re: https://github.com/rust-lang/cargo/issues/12457

fix: needless rebuilds

---

flake.nix

Re:  https://github.com/nextest-rs/nextest/issues/962

fix: cargo nextest triggering macos SIP

---

.github/workflows/ci-nix.yml
flake.lock

Just to remaind us to update nixpkgs from time to time?

chore: check flake inputs as a non-mandatory CI step

---

fedimint-cli/src/lib.rs

chore: better `--help` comments for `fedimint-cli dev api`

---

Cargo.lock
Cargo.toml
fedimint-core/Cargo.toml
fedimint-server/Cargo.toml
fedimintd/Cargo.toml
gateway/ln-gateway/Cargo.toml
modules/fedimint-dummy-client/Cargo.toml
modules/fedimint-dummy-common/Cargo.toml
modules/fedimint-dummy-server/Cargo.toml
modules/fedimint-dummy-tests/Cargo.toml
modules/fedimint-ln-client/Cargo.toml
modules/fedimint-ln-common/Cargo.toml
modules/fedimint-ln-server/Cargo.toml
modules/fedimint-mint-client/Cargo.toml
modules/fedimint-mint-common/Cargo.toml
modules/fedimint-mint-server/Cargo.toml

https://github.com/fedimint/hbbft/pull/10
https://github.com/fedimint/threshold_crypto/pull/8

chore: use fedimint forks of threshold_crypto & hbbft

---

gateway/ln-gateway/tests/integration_tests.rs

Fixes: https://github.com/fedimint/fedimint/issues/3187

test: retry connect_fed since web server might not be up

---

fedimint-cli/src/lib.rs

chore: fix&improve `fedimint-cli config api` examples

---

devimint/src/main.rs
fedimint-cli/src/lib.rs
fedimint-core/src/api.rs
fedimint-server/src/config/mod.rs
fedimint-server/src/net/api.rs

 chore: better errors on federation id or peer id invite code mismatch 

---

Cargo.lock
modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-dummy-tests/Cargo.toml
modules/fedimint-dummy-tests/tests/tests.rs

Replaces the old test:
https://github.com/fedimint/fedimint/blob/1132d742c2357fd70a0c3691636f80637edc0adb/integrationtests/tests/tests.rs#L167C10-L167C46

chore: implement unbalanced_transactions_get_rejected

---

crypto/derive-secret/src/lib.rs
fedimint-core/src/query.rs
modules/fedimint-ln-common/src/api.rs
modules/fedimint-mint-client/src/lib.rs

Finish https://github.com/fedimint/fedimint/pull/2981
Drop tricky parts, move some stuff.  Let's just get in what we can so it doesn't go to waste.

chore: Derivable secret and query strategy docs

---

fedimint-testing/src/gateway.rs
gateway/ln-gateway/tests/integration_tests.rs

Better fix for: https://github.com/fedimint/fedimint/issues/3187 that applies to all gateway tests.

fix: wait for webserver when creating a new gateway

---

Cargo.lock
fedimint-testing/Cargo.toml
fedimint-testing/src/ln/real.rs

Backport of #3235 to `releases/v0.1`.

[Backport releases/v0.1] chore: align dependencies on FM fork of tonic_lnd

---

Cargo.lock
fedimint-cli/src/client.rs
fedimint-wasm-tests/src/lib.rs
gateway/ln-gateway/tests/integration_tests.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-tests/Cargo.toml
modules/fedimint-ln-tests/tests/tests.rs

More up to date version of: https://github.com/fedimint/fedimint/pull/2487

feat: allow injecting user-specified meta into operations

---

modules/fedimint-dummy-tests/tests/tests.rs

Helps debug https://github.com/fedimint/fedimint/issues/3258. I can't reproduce it locally.

chore: added more debugging for test flakiness

---

Cargo.lock
Cargo.toml
devimint/Cargo.toml
fedimint-testing/Cargo.toml
gateway/ln-gateway/Cargo.toml

use our published fork of https://github.com/Kixunil/tonic_lnd

chore: use fedimint-tonic-lnd from crates.io

---

devimint/src/federation.rs
fedimint-core/src/task.rs
fedimint-server/src/config/api.rs

Backport of #3218 to `releases/v0.1`.

[Backport releases/v0.1] fix: run_dkg in background task instead of blocking

---

fedimint-client/src/module/init.rs
gateway/ln-gateway/src/state_machine/mod.rs
modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-wallet-client/src/lib.rs

refactor: Future proof arguments to ClientModuleInit::init

---

modules/fedimint-mint-client/src/lib.rs
modules/fedimint-mint-tests/tests/tests.rs

These could lead to weird error messages since all zero-value OOB spends have the same identity. All but the first would fail.
Fixes #3182

fix(mint-client): reject zero-value out-of-band spends

---

devimint/src/util.rs

Re https://github.com/fedimint/fedimint/issues/3307

fix(deviming): bad errors

---

Cargo.lock
devimint/Cargo.toml
devimint/src/bin/faucet.rs
devimint/src/cfg/bitcoin.conf
devimint/src/cfg/electrs.toml
devimint/src/cfg/lightningd.conf
devimint/src/cfg/lnd.conf
devimint/src/external.rs
devimint/src/federation.rs
devimint/src/lib.rs
devimint/src/main.rs
devimint/src/vars.rs
fedimint-wasm-tests/src/lib.rs
fedimintd/src/lib.rs
misc/mprocs.yaml
modules/fedimint-wallet-common/src/config.rs
scripts/dev/run-isolated-test/fm-run-isolated-test
scripts/dev/run-test/fm-run-test
scripts/tests/test-ci-all.sh
scripts/tests/wasm-test.sh

current status: everything works!

Devimint use random ports

---

scripts/tests/wasm-test.sh

fix: increase timeout for wasm tests

---

devimint/src/federation.rs
devimint/src/util.rs
fedimint-server/src/config/api.rs
fedimintd/src/fedimintd.rs

Backport of #3126 to `releases/v0.1`.

[Backport releases/v0.1] feat: pass extra dkg meta to fedimintd

---

fedimint-server/src/atomic_broadcast/data_provider.rs

Should fix https://github.com/fedimint/fedimint/issues/3345

fix: calculate the maximum length of the encoding correctly

---

gateway/ln-gateway/src/lib.rs

fix: gateway registers with federations right after startup

---

modules/fedimint-wallet-server/src/lib.rs

fix: only propose new fee rate when our vote changes

---

devimint/src/main.rs

fix: wasm tests race with faucet startup

---

.github/workflows/backport.yml

- Add debug logs to investigate outputs from backport action
- Disable creating issues while investigating

chore: add debug logs for issue bot

---

modules/fedimint-wallet-server/src/lib.rs

Needs to be rebased once the backport of #3367 lands in releases/v0.1.

Backport epoch spamming fix

---

.github/templates/failed-backport-issue.md
.github/workflows/backport.yml

- Fixes GH actions boolean syntax
- Verified on [fork](https://github.com/bradleystachurski/fedimint/actions/runs/6509554139?pr=11) syntax works correctly and doesn't open an issue
- Fixes issue titles
- Verified on [fork](https://github.com/bradleystachurski/fedimint/issues/10) title works and links to PR number

fix: update conditional and title in open-issue action

---

fedimint-client/src/lib.rs
fedimint-client/src/module/mod.rs
fedimint-core/src/core.rs
fedimint-core/src/macros.rs
fedimint-core/src/module/mod.rs
gateway/ln-gateway/src/state_machine/mod.rs
modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-wallet-client/src/lib.rs

#3386 + removing redundant code

Client config json with module-specific configs

---

devimint/src/federation.rs
fedimint-core/src/lib.rs
fedimint-core/src/tiered.rs
fedimintd/src/fedimintd.rs
fedimintd/src/lib.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-mint-common/src/config.rs
modules/fedimint-mint-server/src/lib.rs

Server mint consensus config stores denomination base instead of all denominations

---

devimint/src/main.rs
modules/fedimint-wallet-client/src/deposit.rs
modules/fedimint-wallet-client/src/lib.rs
modules/fedimint-wallet-tests/tests/tests.rs

feat(client): expose BitcoinTransactionData in onchain deposit

---

modules/fedimint-mint-client/src/lib.rs

Backport of #3422 to `releases/v0.1`.

[Backport releases/v0.1] feat(mint-client): oob_notes_operation_id

---

devimint/src/main.rs
modules/fedimint-wallet-client/src/deposit.rs
modules/fedimint-wallet-client/src/lib.rs
modules/fedimint-wallet-tests/tests/tests.rs

backport: feat(client): expose BitcoinTransactionData in onchain deposit

---

gateway/ln-gateway/src/state_machine/pay.rs

Error handling in the gateway's pay state machine is a bit cumbersome, adding another error type requires handling code in too many places. Additionally, each `OutgoingPaymentError` holds the contract, but this can be shared across all of the error types which simplifies the error handling.
Should simplify some of the logic in: https://github.com/fedimint/fedimint/pull/3425

refactor: cleanup OutgoingPaymentError in gateway

---

.github/workflows/extra-docker-images.yml

Let's hope it works :crossed_fingers:

fix: change docker context so we can include entrypoint

---

modules/fedimint-ln-client/src/incoming.rs

Re #3472 , quick fix for once place where this became apparent.

fix: don't consume all JsonRPC subscriptions in `await_funding_success`

---

fedimint-client/src/module/mod.rs
modules/fedimint-mint-client/src/lib.rs

feat: ClientModule::leave 

---

Cargo.lock
Cargo.toml
devimint/src/vars.rs
gateway/ln-gateway/Cargo.toml

Adds support for IP address connection to LND nodes

chore: bump version of tonic lnd

---

fedimint-load-test-tool/src/main.rs

If both an invite code and an archive dir is given, the tool will fail the second time with
```
Error: Alternative config source provided but config was found in DB
```
So if the persisted wallet exists, we don't need to provide the invite code to the client builder.
Plus provide context on some file opening.

fix: let load-test-tool properly load the wallet from archive dir

---

modules/fedimint-mint-client/src/lib.rs

allows custom selection of notes in OOB spend
TODO: fix wasm

feat: trait for NotesSelection in OOB spend

---

fedimint-client/src/sm/executor.rs
fedimint-core/src/db/mod.rs

Backport of #3502 to `releases/v0.1`.

[Backport releases/v0.1] fix: Reduce client log levels

---

docs/meta_fields/README.md
docs/meta_fields/vetted_gateways.md

While we should allow any gateway to connect to a federation, we need additional mechanisms by which federation members can vet such gateways. This PR proposes meta field structure for vetted gateways

feat: propose vetted gateways meta field

---

fedimint-cli/src/lib.rs
fedimint-client/src/lib.rs
fedimint-load-test-tool/src/common.rs
fedimint-testing/src/federation.rs
fedimint-wasm-tests/src/lib.rs
gateway/ln-gateway/src/client.rs

feat: make federation info available before joining

---

fedimint-server/src/consensus/server.rs
fedimint-server/src/lib.rs
fedimint-testing/src/federation.rs

Closes https://github.com/fedimint/fedimint/issues/3333

feat: enable single guardians

---

modules/fedimint-mint-client/src/lib.rs

backport: feat: trait for NotesSelection in OOB spend

---

Cargo.lock
Cargo.toml
devimint/Cargo.toml
fedimint-testing/Cargo.toml
gateway/ln-gateway/Cargo.toml

chore: move to fedimint-maintained fork of cln-rpc

---

devimint/src/federation.rs
fedimint-core/src/lib.rs
fedimint-load-test-tool/src/common.rs
fedimint-load-test-tool/src/main.rs

- Tries to get the necessary ecash from the command line but won't fail if there are funds on the archive dir and no ecash is provided
- Automatically gets the invite-code from the command line if possible/necessary

chore(load-test-tool): usability improvements

---

fedimint-core/src/api.rs
modules/fedimint-dummy-client/src/states.rs
modules/fedimint-dummy-tests/tests/tests.rs
modules/fedimint-ln-client/Cargo.toml
modules/fedimint-ln-client/src/pay.rs
modules/fedimint-ln-client/src/receive.rs
modules/fedimint-ln-common/src/api.rs
modules/fedimint-wallet-client/src/withdraw.rs

Fixes #3173
Please double-check!

Review and fix retry behavior of all state machines

---

fedimint-core/src/db/mod.rs

This fixes annoying warnings about uncommited writes when `DatabaseTransactionRef` (which is effectively just a reference to the real Tx) is dropped.

fix: DatabaseTransactionRef should share commit tracker with parent

---

gateway/ln-gateway/src/state_machine/mod.rs
modules/fedimint-ln-client/src/lib.rs

chore: add comments explaining standard vs gateway ln client module

---

docs/wallet_module_v2.md

One of the takeaways from discussing potential wallet improvements on [2023-11-10](https://discord.com/channels/990354215060795454/999362050625130656/1172585091206230096) was to create a shared document we can capture ideas for improvements. This PR copy/pastes this [gist](https://gist.github.com/bradleystachurski/3fd1acf32bfc6a74304f21527e1ed05d) so we have a shared starting point.
In the future it may be worth creating a new repo for Fedimint Improvement Proposals (FIPs) similar to the BIPs [repo](https://github.com/bitcoin/bips), however introducing the additional process seems unnecessary.
Please don't hesitate to suggest other approaches for creating a shared doc for capturing improvement ideas to the wallet module.

docs: add wallet module v2

---

.github/workflows/ci-nix.yml

chore: build binaries on release branch

---

.config/nextest.toml
fedimint-bitcoind/src/lib.rs
fedimint-testing/src/fixtures.rs
modules/fedimint-wallet-tests/tests/tests.rs
scripts/tests/backend-test.sh

Upstream issue to figure out why this has been failing silently, as I still don't understand: https://github.com/nextest-rs/nextest/issues/1108

fix: a typo that lead to all backend tests being skipped

---

.github/workflows/ci-nix.yml

Backport of #3597, fixes #3599

backport: chore: build binaries on release branch

---

devimint/src/external.rs

Addresses feedback from https://github.com/fedimint/fedimint/pull/3590#issuecomment-1810609506.
- Useful for debugging connection issues
- Only devimint logs have been added, so no mainnet urls / auth will be logged

chore: add devimint logging

---

gateway/ln-gateway/src/lib.rs

Closes https://github.com/fedimint/fedimint/issues/3494

fix(gateway): shows the inner error instead of a "0"

---

fedimint-client/src/sm/notifier.rs

fix: workaround for `Notifier` errors

---

fedimint-core/src/timing.rs
fedimint-server/src/consensus/server.rs

Should help with debugging #3623

chore: add timing logs to module audits

---

Cargo.lock
fedimint-cli/src/client.rs
fedimint-core/src/lib.rs
fedimint-dbtool/Cargo.toml
fedimint-load-test-tool/Cargo.toml
gateway/cli/src/main.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs
recoverytool/Cargo.toml

builds on #3573 BitcoinAmountOrAll, moves struct into fedimint_core and adds 'all' option to fedimint-cli clap args

feat: add BitcoinAmountOrAll to fedimint-cli 

---

gateway/ln-gateway/src/state_machine/mod.rs
gateway/ln-gateway/src/state_machine/pay.rs
gateway/ln-gateway/tests/integration_tests.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-common/src/contracts/incoming.rs
modules/fedimint-ln-common/src/contracts/outgoing.rs
modules/fedimint-ln-common/src/db.rs
modules/fedimint-ln-common/src/lib.rs
modules/fedimint-ln-server/src/lib.rs

 feat: make lightning associated types extensible 

---

Cargo.lock
fedimint-core/src/encoding/mod.rs
fedimint-core/src/epoch.rs
fedimint-derive/Cargo.toml
fedimint-derive/src/lib.rs
modules/fedimint-wallet-common/src/lib.rs

This was a leftover from ancient, pre-modularized times.
Fixes #3633

chore: remove `UnzipConsensus`

---

gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/state_machine/mod.rs
gateway/ln-gateway/src/state_machine/pay.rs
gateway/ln-gateway/tests/integration_tests.rs

refactor: get rid of GatewayClientExt

---

fedimint-client/src/backup.rs
fedimint-client/src/module/mod.rs
gateway/ln-gateway/src/state_machine/mod.rs
modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-mint-client/src/backup.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-wallet-client/src/lib.rs

 refactor: ClientModule::backup to use ClientContext 

---

modules/fedimint-mint-client/src/lib.rs
modules/fedimint-wallet-client/src/lib.rs

chore: serialize operation meta in snake case

---

fedimint-client/src/backup.rs
fedimint-client/src/module/mod.rs
modules/fedimint-mint-client/src/backup.rs
modules/fedimint-mint-client/src/lib.rs

 refactor: ClientModule::recover to use ClientContext 

---

recoverytool/src/main.rs

Closes #3482 
When we switched to AlephBFT, the transaction consensus items were nested in a different type so we commented out the recovery tool logic to parse the transactions from signed blocks. This PR parses transactions from `SignedBlock`s and allows the recovery tool to recover using `TweakSource::Epochs`.
I don't believe any tests exist for the recovery tool ([comment](https://github.com/fedimint/fedimint/issues/3482#issuecomment-1819763368)), so perhaps a useful followup PR can introduce tests.

feat: port recovery tool to AlephBFT

---

fedimint-logging/src/lib.rs
fedimint-server/src/atomic_broadcast/backup.rs
fedimint-server/src/consensus/server.rs

Fixes #3598 (hopefully for real this time)

Improve logging

---

fedimint-client/src/backup.rs
fedimint-client/src/lib.rs

made restore_from_backup public
made it accept backup as argument as instead of downloading itself.

feat: provide more control in restore_from_backup to clients

---

fedimint-client/src/module/recovery.rs
modules/fedimint-mint-client/src/backup.rs
modules/fedimint-mint-client/src/backup/recovery.rs
modules/fedimint-mint-client/src/lib.rs

feat(core): make backups extensible

---

devimint/src/main.rs

Closes https://github.com/fedimint/fedimint/issues/3686

feat: improved latency tests

---

gateway/ln-gateway/tests/integration_tests.rs

asserting gateway balance after swap seems sensitive to consensus +  gateway state
machine performance. this change adds a 5s sleep, hopefully giving the gateway a chance to claim
outgoing contract and update balances before we assert new balances
fixes #3679 
drafting this as a fix but we'd need correlation with latency test data from #3696

test: re-enable gateway swap balance assertion

---

Cargo.lock
fedimint-cli/src/client.rs
fedimint-load-test-tool/src/common.rs
fedimint-load-test-tool/src/main.rs
fedimint-wasm-tests/src/lib.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/tests/integration_tests.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-tests/tests/tests.rs
modules/fedimint-wallet-client/Cargo.toml
modules/fedimint-wallet-client/src/lib.rs
modules/fedimint-wallet-tests/tests/tests.rs

Add extra meta to wallet and ln operations

---

fedimint-load-test-tool/src/main.rs

This helps generating the metric mentioned on https://github.com/fedimint/fedimint/issues/3705

feat(load-test-tool): add receiving method to metric

---

fedimint-core/src/epoch.rs
fedimint-server/src/consensus/debug.rs
fedimint-server/src/consensus/server.rs
recoverytool/src/main.rs

feat(core): make `ConsensusItem` extensible

---

modules/fedimint-wallet-server/src/lib.rs
recoverytool/src/main.rs

fix: recoverytool

---

Cargo.lock
crypto/derive-secret/Cargo.toml
crypto/hkdf/Cargo.toml
crypto/tbs/Cargo.toml
devimint/Cargo.toml
fedimint-core/Cargo.toml
fedimint-dbtool/Cargo.toml
fedimint-load-test-tool/Cargo.toml
fedimint-server/Cargo.toml
fedimint-testing/Cargo.toml
fedimint-wasm-tests/Cargo.toml
fedimintd/Cargo.toml
gateway/cli/Cargo.toml
gateway/ln-gateway/Cargo.toml
misc/git-hooks/pre-commit
modules/fedimint-ln-tests/Cargo.toml
modules/fedimint-mint-client/Cargo.toml
modules/fedimint-mint-common/Cargo.toml
modules/fedimint-mint-server/Cargo.toml
modules/fedimint-mint-tests/Cargo.toml
modules/fedimint-wallet-tests/Cargo.toml
nix/check-forbidden-deps.sh
nix/flakebox.nix
recoverytool/Cargo.toml

Backport of #3721 to `releases/v0.2`.

[Backport releases/v0.2] chore: ensure prefix `fedimint` on all published crates

---

crypto/derive-secret/Cargo.toml
fedimint-bip39/Cargo.toml
fedimint-bitcoind/Cargo.toml
fedimint-cli/Cargo.toml
fedimint-client/Cargo.toml
fedimint-core/Cargo.toml
fedimint-dbtool/Cargo.toml
fedimint-load-test-tool/Cargo.toml
fedimint-metrics/Cargo.toml
fedimint-rocksdb/Cargo.toml
fedimint-server/Cargo.toml
fedimint-testing/Cargo.toml
fedimintd/Cargo.toml
gateway/cli/Cargo.toml
gateway/ln-gateway/Cargo.toml
modules/fedimint-dummy-client/Cargo.toml
modules/fedimint-dummy-common/Cargo.toml
modules/fedimint-dummy-server/Cargo.toml
modules/fedimint-dummy-tests/Cargo.toml
modules/fedimint-ln-client/Cargo.toml
modules/fedimint-ln-common/Cargo.toml
modules/fedimint-ln-server/Cargo.toml
modules/fedimint-mint-client/Cargo.toml
modules/fedimint-mint-common/Cargo.toml
modules/fedimint-mint-server/Cargo.toml
modules/fedimint-wallet-client/Cargo.toml
modules/fedimint-wallet-common/Cargo.toml
modules/fedimint-wallet-server/Cargo.toml
recoverytool/Cargo.toml
utils/portalloc/Cargo.toml

Fixes I had to apply to be ablet to release Fedimint on crates.io

---

Cargo.lock
fedimint-build/Cargo.toml
fedimint-build/src/lib.rs

feat: read git hash from .cargo_vcs_info.json if compiling release

---

gateway/ln-gateway/src/bin/cln_extension.rs
gateway/ln-gateway/src/lib.rs

On `cln-extension`, while one HTLC was being processed, the `self.sender` lock would be held, blocking further requests to get initiated and making the whole process synchronous.
Also minor code cleanups/improvements.
Closes https://github.com/fedimint/fedimint/issues/3705

fix(cln-extension): avoid holding the sender lock during HTLC processing

---

gateway/ln-gateway/src/bin/cln_extension.rs
gateway/ln-gateway/src/lib.rs

Backport of #3742 to `releases/v0.2`.

[Backport releases/v0.2] fix(cln-extension): avoid holding the sender lock during HTLC processing

---

fedimint-core/src/api.rs

Backport of #3761 to `releases/v0.2`.

[Backport releases/v0.2] fix(api): serialize enums in snake case

---

fedimint-server/src/consensus/server.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

Backport of #3758 to `releases/v0.2`.

[Backport releases/v0.2] simplification: always propose block height and feerate votes

---

devimint/src/federation.rs
devimint/src/main.rs
recoverytool/README.md
recoverytool/src/main.rs
scripts/tests/recoverytool-tests.sh
scripts/tests/test-ci-all.sh

Added tests for `utxos`and `epochs` method. Reviewed the README

feat: added recoverytool tests

---

fedimint-cli/src/lib.rs

Backport of #3749 to `releases/v0.2`.

[Backport releases/v0.2] feat: can pass --auth flag to `fedimint-cli dev api`

---

fedimint-cli/src/client.rs
fedimint-core/src/lib.rs
gateway/ln-gateway/src/lib.rs

Backport of #3755 to `releases/v0.2`.

[Backport releases/v0.2] fix 'withdraw all' feature

---

gateway/ln-gateway/src/lib.rs

chore: log successful ln-gateway withdrawal

---

devimint/src/federation.rs
docs/tutorial.md
fedimint-cli/src/lib.rs

fix(fedimint-cli): create data dir if doesn't exist

---

fedimint-cli/src/lib.rs
fedimint-logging/src/lib.rs

Part of https://github.com/fedimint/fedimint/issues/3822

fix: make client less verbose

---

gateway/ln-gateway/src/lib.rs

Closes https://github.com/fedimint/fedimint/issues/3806

fix(gateway): disconnect before changing the network

---

gateway/ln-gateway/src/lib.rs

Backport of #3833 to `releases/v0.2`.

[Backport releases/v0.2] fix(gateway): disconnect before changing the network

---

modules/fedimint-ln-client/src/pay.rs

Backport of #3845 to `releases/v0.2`.

[Backport releases/v0.2] chore: refactor invoice expiration check in client

---

fedimint-cli/src/client.rs

fix(cli): increase deposit timeout and make it configurable

---

fedimint-cli/src/client.rs

Backport of #3864 to `releases/v0.2`.

[Backport releases/v0.2] fix(cli): increase deposit timeout and make it configurable

---

gateway/ln-gateway/src/lib.rs

Backport of #3873 to `releases/v0.2`.

[Backport releases/v0.2] chore: change warning to a info

---

devimint/src/main.rs

test: verify recoverytool includes change outputs

---

gateway/ln-gateway/src/lib.rs
modules/fedimint-ln-client/src/receive.rs

Backport of #3885 to `releases/v0.2`.

[Backport releases/v0.2] chore: change some errors to warns/infos

---

Cargo.lock
gateway/ln-gateway/Cargo.toml
gateway/ln-gateway/src/lnd.rs
modules/fedimint-ln-common/Cargo.toml
modules/fedimint-ln-common/src/lib.rs

Backport fix: supply LN invoice features to LN gateway node

---

Cargo.lock
fedimint-testing/Cargo.toml

fix: downstream consumer broken (0.1)

---

fedimint-cli/src/client.rs
fedimint-core/src/lib.rs
modules/fedimint-mint-common/src/config.rs

(cherry picked from commit 3dd3eb8fbe42e32cb101f9a64313be241b266408)
Backport https://github.com/fedimint/fedimint/pull/3889

[Backport releases/v0.2] refactor: amount improvements

---

modules/fedimint-mint-client/src/client_db.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-mint-client/src/oob.rs
modules/fedimint-mint-tests/tests/tests.rs

fix: make OOB spend cancellation reliable

---

.github/workflows/backport.yml

fix: prevent multiple backport workflows per branch

---

Cargo.lock
devimint/Cargo.toml
devimint/build.rs
devimint/src/main.rs

(cherry picked from commit 8c12e84c82c61cb7dad376234f5a7968e6eb52ac)

feat(devimint): `devimint version-hash`

---

fedimint-core/src/endpoint_constants.rs
fedimint-core/src/time.rs
fedimint-load-test-tool/src/main.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-client/src/pay.rs
modules/fedimint-ln-client/src/receive.rs
modules/fedimint-ln-common/src/api.rs
modules/fedimint-ln-common/src/contracts/mod.rs
modules/fedimint-ln-server/src/lib.rs
utils/portalloc/src/lib.rs

Backport of #3929 to `releases/v0.2`.

[Backport releases/v0.2] fix: more robust lightning receive

---

modules/fedimint-mint-client/src/backup/recovery.rs

> Cause: recovery only invalidates notes as spent that it recovered itself, not ones that were in the backup file retrieved from the federation.
Fix #3941

fix(mint-client): invalidate all spent notes on recovery

---

crypto/aead/Cargo.toml
crypto/derive-secret/Cargo.toml
fedimint-bip39/Cargo.toml
fedimint-bitcoind/Cargo.toml
fedimint-cli/Cargo.toml
fedimint-client/Cargo.toml
fedimint-dbtool/Cargo.toml
fedimint-metrics/Cargo.toml
fedimint-rocksdb/Cargo.toml
fedimint-server/Cargo.toml
fedimint-testing/Cargo.toml
fedimintd/Cargo.toml
gateway/cli/Cargo.toml
modules/fedimint-dummy-client/Cargo.toml
modules/fedimint-dummy-common/Cargo.toml
modules/fedimint-dummy-server/Cargo.toml
modules/fedimint-ln-client/Cargo.toml
modules/fedimint-ln-common/Cargo.toml
modules/fedimint-ln-server/Cargo.toml
modules/fedimint-mint-client/Cargo.toml
modules/fedimint-mint-common/Cargo.toml
modules/fedimint-mint-server/Cargo.toml
modules/fedimint-wallet-client/Cargo.toml
modules/fedimint-wallet-common/Cargo.toml
modules/fedimint-wallet-server/Cargo.toml
recoverytool/Cargo.toml
utils/portalloc/Cargo.toml

Backport of #3952 to `releases/v0.2`.

[Backport releases/v0.2] chore: give build instructions to docs.rs

---

modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-client/src/receive.rs
modules/fedimint-ln-common/src/api.rs

Backport of #3963 to `releases/v0.2`.

[Backport releases/v0.2] fix(lightning): proper handle timeouts while receiving a payment

---

Cargo.lock

fixes RUSTSEC-2024-0003
https://rustsec.org/advisories/RUSTSEC-2024-0003

fix: RUSTSEC-2024-0003

---

Cargo.lock

fixes https://rustsec.org/advisories/RUSTSEC-2024-0006

fix RUSTSEC-2024-0006

---

.github/workflows/ci-nix.yml
flake.nix

chore: expose fedimint-dbtool

---

modules/fedimint-ln-client/src/lib.rs

backport: feat(ln-client): make LN gateway known upfront

---

Cargo.lock
Cargo.toml

Backport https://github.com/fedimint/fedimint/pull/4031

Backport #4031

---

fedimint-core/src/db/mem_impl.rs

related https://github.com/fedimint/fedimint/issues/3988

fix: handle write write conflicts in mem db

---

fedimint-server/src/consensus/server.rs

Backport of #4188 to `releases/v0.2`.

[Backport releases/v0.2] fix: calculate the batches per sessions correctly to achieve fault tolerance

---

fedimint-core/src/task.rs
fedimint-core/src/util/mod.rs
fedimint-testing/src/gateway.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/rpc_server.rs
gateway/ln-gateway/src/state_machine/pay.rs

backports #4175 
FYI 5bf8f219c102d37711cd9496308458b107504496 didn't backport trivial

Better logs for gateway [0.2]

---

devimint/src/main.rs
nix/flakebox.nix
scripts/tests/latency-test.sh
scripts/tests/test-ci-all.sh

[0.2] devimint latency tests with degraded federations

---

modules/fedimint-ln-client/src/lib.rs

chore(ln-client): improve logging when choosing gateway

---

.github/workflows/ci-nix.yml

fix: fail to upload debs/rpms bundle on master

---

fedimintd/src/fedimintd.rs

Document fedimintd/src/fedimintd.rs

---

fedimint-core/src/module/mod.rs

Currently it's a (potentially) very long and unhelpful `[0, 52, 192, ...`

fix: raw bytes Debug formatting

---

fedimint-wasm-tests/src/lib.rs
scripts/tests/wasm-test.sh

I don't why did only one receive and pay before.

feat: wasm test concurrency

---

fedimint-wasm-tests/src/lib.rs

hopefully this will catch more wasm bugs on master

feat: wasm ecash tests

---

gateway/ln-gateway/tests/integration_tests.rs

Fix #4301
Possibly fixed by fixed that landed after it was disabled.

chore: try to re-enable test_can_change_routing_fees

---

fedimint-core/src/db/mem_impl.rs

chore(memdb): use rwlock

---

modules/fedimint-ln-client/src/lib.rs

fix: remove use of system time in ln client

---

fedimint-client/src/module/init/recovery.rs
fedimint-core/src/api.rs
fedimint-core/src/module/version.rs

Use https://github.com/fedimint/fedimint/pull/4150 to avoid waiting for the final session to finish.
Fix #4043

 fix: recovery waiting for the last session to close (mostly in tests) 

---

fedimint-wasm-tests/src/lib.rs

i will keep adding more wasm tests until I find a failing one

chore: more wasm tests

---

.github/workflows/ci-nix.yml
nix/flakebox.nix

chore(nix): export gateway-cln-extension binary

---

.github/workflows/ci-backwards-compatibility.yml
.github/workflows/ci-nix.yml

On top of #4401 to avoid merge conflict.

 chore(ci): update install-nix-action nixpkgs channel 

---

.editorconfig

chore: add basic .editorconfig file

---

fedimint-client/src/lib.rs

Hopefully fixes #4397 (mostly a documentation issue imo). @benthecarman would this have helped?

chore(client): document joining a federation

---

.github/workflows/ci-backwards-compatibility.yml
scripts/_common.sh
scripts/dev/run-test/fm-run-test
scripts/tests/test-ci-all.sh

Parallel backward compat. tests improvements

---

gateway/ln-gateway/src/lib.rs

If a federation is unreachable, the delay for retrying is reduced to 10 seconds instead of a multiple of GW_ANNOUNCEMENT_TTL.
Closes: https://github.com/fedimint/fedimint/issues/4280

chore: decrease sleep time when registration fails

---

devimint/src/tests.rs

@bradleystachurski left some good comments in #4415 on which I didn't want to block, addressing them here.

chore: address comments from #4415

---

Cargo.lock

https://rustsec.org/advisories/RUSTSEC-2024-0019

chore: bump mio

---

justfile.fedimint.just
scripts/bench-compilation.sh

See https://github.com/fedimint/fedimint/wiki/Benchmark-compilation-times

feat(dev): `just bench-compilation`

---

.github/workflows/ci-nix.yml

Context: https://github.com/fedimint/fedimint/pull/4476#issuecomment-1982263388
Issue to track reverting: https://github.com/fedimint/fedimint/issues/4488

chore: increase cross compile timeout in CI

---

Cargo.lock
fedimint-rocksdb/Cargo.toml
flake.nix
nix/overlays/rocksdb.nix

chore(deps): bump rocksdb from 0.21.0 to 0.22.0

---

scripts/tests/test-ci-all.sh

Need to be more conservative here.

chore(test-ci-all): lower number of parallel jobs on dev machines

---

fedimint-cli/src/client.rs
fedimint-cli/src/lib.rs
fedimint-client/src/lib.rs
fedimint-load-test-tool/src/common.rs
fedimint-load-test-tool/src/main.rs
fedimint-testing/src/federation.rs
fedimint-testing/src/gateway.rs
fedimint-wasm-tests/src/lib.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/state_machine/pay.rs
gateway/ln-gateway/tests/integration_tests.rs
modules/fedimint-ln-common/src/lib.rs
modules/fedimint-wallet-tests/tests/tests.rs

gives more control to user code
on top of #4535

 feat: make user code put ClientHandle in Arc 

---

devimint/src/cli.rs
scripts/_common.sh
scripts/dev/devimint-env.sh
scripts/dev/devimint-env/starship.toml

As I am beginning to use it, I discover problems and tweak things.

chore(devimint-env): fixes & improvements

---

fedimint-cli/src/db_locked.rs

With recent dependency updates, this is now possible. I know because I contributed it, just so I can eventually get it to work like this. :D

chore(fedimint-cli): print locking message  only if lock busy

---

devimint/src/tests.rs
devimint/src/util.rs
fedimint-cli/src/lib.rs

Closes https://github.com/fedimint/fedimint/issues/4558

chore(fedimint-cli): write json error to stdout

---

fedimint-client/src/transaction/sm.rs

chore: disable deprecation warnings

---

devimint/src/util.rs

Brad was right, I was wrong.
I'm not worried about the performance, but the flood of logging messages is inconvenient.

chore(devimint): polling maybe a bit too aggressive

---

fedimint-testing/src/gateway.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/tests/integration_tests.rs

Fixes: https://github.com/fedimint/fedimint/issues/4290
No longer flaky!

fix: test_gateway_configuration

---

fedimint-client/src/lib.rs

Backport of #4633 to `releases/v0.3`.

[Backport releases/v0.3] chore: expose the client task group

---

modules/fedimint-mint-tests/tests/tests.rs

https://github.com/fedimint/fedimint/actions/runs/8348631889/job/22851011073
I suspect without sleep, 200 retries here might finish really fast.

chore: debug flaky sends_ecash_out_of_band_cancel test

---

modules/fedimint-mint-tests/tests/tests.rs

Backport of #4625 to `releases/v0.3`.

[Backport releases/v0.3] chore: debug flaky sends_ecash_out_of_band_cancel test

---

gateway/ln-gateway/tests/integration_tests.rs
modules/fedimint-ln-client/src/lib.rs

Backport of #4652 to `releases/v0.3`.

[Backport releases/v0.3] feat: add gateway id in lightning operation meta

---

fedimint-client/src/lib.rs
fedimint-core/src/task.rs
gateway/ln-gateway/src/lib.rs

helps to make correct behavior easy to use

chore: helper TaskGroup::spawn_cancellable

---

docs/rustdoc-index.md
scripts/dev/build-docs.sh

On top of https://github.com/fedimint/fedimint/pull/4624
Please point out nits, but approve anyway, as I need to see it published to improve further.

 chore: write landing page for docs.fedimint.org 

---

fedimint-client/src/lib.rs
fedimint-core/src/task.rs
gateway/ln-gateway/src/lib.rs

Backport of #4638 to `releases/v0.3`.

[Backport releases/v0.3] chore: helper TaskGroup::spawn_cancellable

---

scripts/dev/run-test/fm-run-test

chore(ci): clean test dirs on success

---

modules/fedimint-ln-client/src/lib.rs

Backport of #4681 to `releases/v0.3`.

[Backport releases/v0.3] feat: Make claim_funded_incoming_contract public

---

devimint/src/util.rs
gateway/ln-gateway/src/lib.rs

Followup to https://github.com/fedimint/fedimint/pull/4678#discussion_r1536632435

chore(gatewayd): add clap --version

---

fedimint-cli/src/lib.rs
fedimint-client/src/lib.rs
fedimint-core/src/db/mem_impl.rs
fedimint-core/src/db/mod.rs
fedimint-load-test-tool/src/common.rs
fedimint-rocksdb/src/lib.rs
fedimint-testing/src/federation.rs
fedimint-wasm-tests/src/lib.rs
gateway/ln-gateway/src/client.rs

And other improvements around it.

refactor: better key&value decoding in db code

---

fedimint-client/src/db.rs
modules/fedimint-ln-client/src/db.rs
modules/fedimint-ln-client/src/receive.rs

Backport of #4707 to `releases/v0.3`.

[Backport releases/v0.3] Add missing state machine migration

---

Cargo.toml
nix/flakebox.nix

fix: autodetect nix pkgs versions from root Cargo.toml

---

Cargo.lock
modules/fedimint-ln-tests/Cargo.toml

chore: remove bitcoin dependency from fedimint-ln-tests

---

fedimint-cli/src/lib.rs

Port of https://github.com/fedimint/fedimint/pull/3796
Plus missing methods and minor improvements
Closes https://github.com/fedimint/fedimint/issues/3795
In future we may create another command that does the full setup using these subcommands and use them to setup devimint, perhaps replacing the current method: https://github.com/fedimint/fedimint/blob/0b8cdd855cc46e58a74fa04678849bddd8da3832/devimint/src/federation.rs#L501
Calling example:
```bash
fedimint-cli admin dkg --ws ws://127.0.0.1:24329/ ws-status
```

feat: allow setting up federation via `fedimint-cli`

---

fedimint-cli/src/lib.rs

Backport of #4628 to `releases/v0.3`.

[Backport releases/v0.3] feat: allow setting up federation via `fedimint-cli`

---

flake.lock
flake.nix

Features include:
* crane will download crates from new mirrors
* newer toolchain

chore(nix): update crane & fenix

---

devimint/src/federation.rs

Closes https://github.com/fedimint/fedimint/issues/4730
Backports back-compat flakey test fix https://github.com/fedimint/fedimint/pull/4647

Backport fix: bump wait_server_status timeout

---

fedimint-dbtool/src/main.rs
gateway/ln-gateway/src/bin/cln_extension.rs
recoverytool/src/main.rs

Backport of #4723 to `releases/v0.3`.

[Backport releases/v0.3] chore: add clap version command to all binaries

---

flake.nix
justfile.fedimint.just

chore: add versioning just command

---

fedimint-cli/src/lib.rs

Backport of #4742 to `releases/v0.3`.

[Backport releases/v0.3] chore(fedimint-cli): increase wait-block-count to 60s

---

Cargo.lock
fedimint-core/Cargo.toml
fedimint-core/src/config.rs
fedimint-core/src/util/mod.rs
gateway/ln-gateway/tests/integration_tests.rs

I really like 0.2, 0.2, 0.4, 0.6, 1.0, 1.6, 2.6, 4.6, 5, 5...
We should export some statergy in fedimint-core but naming is hard.

feat: backoff in retry helper

---

fedimint-client/src/lib.rs
fedimint-client/src/module/init.rs

split from https://github.com/fedimint/fedimint/pull/4756 to quickly merge and backport

chore: make client task group available to modules

---

fedimint-client/src/lib.rs
fedimint-client/src/module/init.rs

Backport of #4764 to `releases/v0.3`.

[Backport releases/v0.3] chore: make client task group available to modules

---

fedimint-core/src/config.rs

Backport of #4761 to `releases/v0.3`.

[Backport releases/v0.3] chore: expose try_download_client_config

---

Cargo.lock
fedimint-core/src/bitcoin_migration.rs
gateway/ln-gateway/Cargo.toml
gateway/ln-gateway/src/db.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs
gateway/ln-gateway/src/rpc/rpc_client.rs
gateway/ln-gateway/src/state_machine/mod.rs
gateway/ln-gateway/src/state_machine/pay.rs
gateway/ln-gateway/tests/integration_tests.rs
recoverytool/src/main.rs

chore: upgrade ln-gateway to bitcoin v0.30
