- fedimint-client/src/lib.rs
- fedimint-testing/src/federation.rs
- modules/fedimint-dummy-tests/tests/tests.rs
For a client it is ok to not understand all modules supported by a server, it can still interact with the ones it knows.
> fix(client-ng): ignore modules of unknown kind

- fedimint-core/src/config.rs
- fedimint-core/src/module/mod.rs
- fedimint-server/src/config/api.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/lib.rs
- fedimint-server/src/net/connect.rs
- fedimint-ui/apps/guardian-ui/src/components/SetConfiguration.tsx
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
- Uses the default params if params are not supplied
- Validates the params can be parsed upon calling `set_config_gen_params`
- Sanitizes guardian names that are numeric
Fixes #2545
> feature: validate params and use defaults

- fedimint-ui/apps/guardian-ui/src/components/SetConfiguration.tsx
Uses the NumberInput for some form fields. Adds error text from when things are out of validity.
Delete the number or type in non-numeric strings to get an error printed.
> feat(ui): use number input for block confirmations and guardian number

- Cargo.lock
- fedimint-bitcoind/Cargo.toml
- fedimint-bitcoind/src/bitcoincore_rpc.rs
- modules/fedimint-wallet-client/Cargo.toml
- modules/fedimint-wallet-client/src/deposit.rs
`rust-esplora-client` v0.5.0 release: https://github.com/bitcoindevkit/rust-esplora-client/releases/tag/v0.5.0
fixes #2325
> build(deps): bump `rust-esplora-client` to 0.5.0

- devimint/src/main.rs
- fedimint-cli/src/ng.rs
> fix(client-ng): base64-encode e-cash notes like the old client

- misc/fedimintd-container-entrypoint.sh
Since we set the password in the UI, this is no longer needed.
I alos believe this will avoid hitting a bug in (config api)[https://github.com/fedimint/fedimint/blob/5b89c5a71340414e424aaf02235a8edb1af8c832/fedimint-server/src/config/api.rs#LL247C1-L261C6] where writing configs fail if a password is already set.
Resulting in this error during setup:
This error was found when testing in [this repo](https://github.com/EthnTuttle/fedimint-ui), where I have been working on push button Docker running of a Fedimint. It enables commit hash pegging via the Docker image tag we specify in the setup.
I believe this PR will unlock final testing in that repo so we can populate https://github.com/fedimint/ui and start removing all the dirty javascript from this beautiful Rust project. Then myself and …
> fix: remove password requirement for docker image

- justfile
now `just run-ui` should work in a fresh clone
> chore: yarn build in just run-ui

- fedimint-ui/README.md
- fedimint-ui/package.json
- fedimint-ui/packages/ui/package.json
- fedimint-ui/turbo.json
* Adds `yarn dev` to `fedimint-ui/` to run all `dev` commands
* Due to there being port conflicts amongst apps, I also added `yarn dev:[app-name]` commands to only run one app at a time, along with any packages it depends on. You can specify different ports in each command to run multiple.
* E.g. `yarn dev:guardian-ui` in one terminal, `PORT=4000 yarn dev:gateway-ui` in another terminal
* Alternatively, we could hard-code in different ports for each app, and make them all runnable via one command?
* Fixes `yarn dev` command in `packages/ui`, a typo was causing it to fail
1. cd into `fedimint-ui` and run `yarn dev`, confirm it all runs but apps die due to port conflicts
2. run `yarn dev:guardian-ui`, confirm it runs properly on port 3000 and also runs dev for `ui`
3. run `PORT=4000 yarn …
> feat(ui): turbo dev

- fedimint-server/src/consensus/server.rs
- integrationtests/tests/fixtures/mod.rs
In Fedi Alpha deployement, probably caused by #2605 , we've noticed Federations accumulating hundreds of empty epochs to be created, due to how currently they are being accumulated (`+=`) on every request.
Change the code to cap the pending epochs to a max value (10).
While at it, do some renaming.
> fix: don't accumulate empty epochs on rejoin requests

- modules/fedimint-ln-client/src/lib.rs
Without something like this, you can't really run fedimint without multiple gateways. At any given time, all clients will select the same "active gateway".
Also, fixes bug where select_active_gateway would always return an expired gateway if one was returned by server and no active gateway. Luckily, the server also checks that gateways haven't expired.
> Randomly select active gateway

- fedimint-testing/src/gateway.rs
- gateway/ln-gateway/src/bin/gatewayd.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/lib.rs
- integrationtests/tests/fixtures/mod.rs
This PR changes gatewayd's persistence. Instead of persisting `GatewayClientConfig` for each client, it now stores this metadata in a "gatewayd" database. There is still a database per federation client, but now there is an additional database for gatewayd to store metadata.
Right now, gatewayd stores just enough to reconstruct `GatewayClientConfig`, but the downside is that when it re-creates the actors it needs to contact each federation to get the configuration. Once we migrate off of the old client, we can optimize this and store configuration for the new client. This is just a backwards compatible workaround, but allows for easy changing once the NG client is in place.
> feat: Gatewayd database

- devimint/src/federation.rs
- devimint/src/main.rs
- scripts/user-shell.sh
This is to resolve #2507.
I've created a new method `pegin_ng` based on the changes from #2416. This is called as part of `devimint dev-fed` to fund the new client and also as part of the CLI tests where I took the original code from.
I've updated some CLI tests to reflect the non-zero initial balance of the new client.
I've also reverted the changes from #2509.
> feat: fund client ng from devimint dev-fed

- fedimint-core/src/config.rs
- fedimint-testing/src/gateway.rs
- fedimint-testing/src/ln/mock.rs
- fedimint-testing/src/ln/real.rs
- gateway/cli/src/main.rs
- gateway/ln-gateway/proto/gatewaylnrpc.proto
- gateway/ln-gateway/src/actor.rs
- gateway/ln-gateway/src/bin/cln_extension.rs
- gateway/ln-gateway/src/bin/gatewayd.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lnd.rs
- gateway/ln-gateway/src/lnrpc_client.rs
- gateway/ln-gateway/src/ng/mod.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- integrationtests/tests/fixtures/mod.rs
We are moving away from `GatewayActor` and instead `Gatewayd` will keep a map of federation clients. To prepare for this change, this PR refactors a bunch of logic away from `GatewayActor` but does not instantiate the new client yet.
Changes:
- Remove Lightning re-connection logic (can be added back in once we have the new client) https://github.com/fedimint/fedimint/issues/2625
- `ILnRpcClient` has changed from `Arc<RwLock<dyn ILnRpcClient>>` to `Arc<dyn ILnRpcClient>`. The new client accepts the later.
- `route_htlcs` has moved from `GatewayActor` to `Gatewayd`. This means we will only have one gRPC channel between the lightning node and `Gatewayd` instead of per-actor.
- Subscribing to HTLCs has been removed. All HTLCs are sent from the lightning implementations to `gatewayd`. …
> refactor: one route_htlcs instead of per-actor

- docs/dev-running.md
This command in the dev-running doc page appears to be out of date. It now requires the `--amount` and `--description` flags before each command line argument.
> correct ln-invoice command

- fedimint-client/src/sm/executor.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
During ecash recovery the logs are currently flooded with very long messages.
> chore: less logs during module recovery

- flake.nix
- nix/craneCommon.nix
Using `${src}` where `src = ./.;` causes whole dependency build to depend on every file in the project directory.
> chore(nix): fix needless rebuilds

- Cargo.lock
- Cargo.toml
- fedimint-atomic-broadcast/Cargo.toml
- fedimint-atomic-broadcast/src/broadcast.rs
- fedimint-atomic-broadcast/src/conversion.rs
- fedimint-atomic-broadcast/src/data_provider.rs
- fedimint-atomic-broadcast/src/db.rs
- fedimint-atomic-broadcast/src/finalization_handler.rs
- fedimint-atomic-broadcast/src/keychain.rs
- fedimint-atomic-broadcast/src/lib.rs
- fedimint-atomic-broadcast/src/network.rs
- fedimint-atomic-broadcast/src/session.rs
- fedimint-atomic-broadcast/src/spawner.rs
- fedimint-atomic-broadcast/tests/integration.rs
Just like the bitcoin network a federation has to agree on a total order of transactions before they can be processed in order to decide which transaction is valid in case of conflicts between transactions. An algorithm which achieves this ordering in a byzantine fault tolerant (BFT) setting, meaning when up to f out of 3f + 1 total nodes are malicious, is called an atomic broadcast. Since its inception, Fedimint used the so called Honey Badger BFT (HBBFT) as its atomic broadcast. However, the algorithm and its implementation have a some critical problems:
* HBBFT trades of transaction latency for throughput by design. Furthermore the transaction latency is very sensitive towards bad network conditions, faulty guardians and number of guardians and all those four factors  compound. …
> Initial Implementation of the atomic broadcast abstraction based on Aleph BFT

- fedimint-client/src/lib.rs
- fedimint-core/src/config.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-tests/tests/tests.rs
Implements a [proposal allowing clients to create invoices when there are no gateways connected](https://github.com/fedimint/fedimint/issues/2618).
In this scenario, invoices have a node pubkey and short channel id markers which make them payable within the current federation only, but not from an external payer
closes #2618
> Internal Payment With Markers

- fedimint-client-legacy/src/lib.rs
- fedimint-client-legacy/src/ln/mod.rs
- gateway/ln-gateway/src/ng/mod.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
Fixes: https://github.com/fedimint/fedimint/issues/2639
`Gatewayd` currently does have a unique identifier, its just confusingly named `mint_pub_key`. This is actually the `redeem_key` that the gateway uses to redeem contracts from a federation, it has nothing to do with the mint or mint module.
This PR just renames it to `gateway_pub_key` to make its purpose a bit more clear.
> rename: rename mint_pub_key to gateway_pub_key

- devimint/src/lib.rs
- devimint/src/main.rs
- fedimint-testing/src/ln/real.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lnd.rs
- gateway/ln-gateway/src/lnrpc_client.rs
Fixes: https://github.com/fedimint/fedimint/issues/2625
Allows `gatewayd` to reconnect to the lightning node if the connection drops.
Each `ILnRpcClient` implementation now only holds the connection information and not the actual connect. A connection is created when an RPC is requested. Each implementation will try 10 times to reconnect and fail if it can't connect (so that RPCs don't block indefinitely). 
Since the connections are no longer cached by the `ILnRpcClient` implementation, this might have a small perf overhead.
> feat: lightning reconnect

- misc/git-hooks/pre-commit
this broke precommit in magit(https://magit.vc) when there were any unstaged changes
> fix: git --literal-pathspecs commit

- fedimint-client/src/backup.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/gen.rs
- fedimint-client/src/module/mod.rs
- fedimint-core/src/module/registry.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
The fact that primary modules implement a separate trait generate a lot of friction, for rather small gains.
In particular the fact that primary module is not present in the client's `modules` makes functionality that need to something on "all module instances" error prone, and require extra ceremony.
> refactor: make a primary module a runtime concept, not type system one

- devimint/src/federation.rs
- devimint/src/lib.rs
- fedimint-cli/src/lib.rs
- fedimint-cli/src/ng.rs
- fedimint-client-legacy/src/lib.rs
- fedimint-client-legacy/src/utils.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-wasm-tests/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-tests/tests/tests.rs
- scripts/user-shell.sh
`switch_gateway` currently uses `node_pub_key` as the key for determining which gateway the user desires. This is broken because it is possible multiple gateways could use the same lightning node.
We have `gateway_pub_key` which the gateway uses the redeem contracts from the federations its connected to. This PR changes `switch_gateway` to use that key for switching gateways.
> refactor: use gateway public key instead of node public key

- fedimint-core/src/api.rs
- fedimint-testing/src/btc/mock.rs
- fedimint-testing/src/btc/mod.rs
- fedimint-testing/src/btc/real.rs
- integrationtests/tests/fixtures/mod.rs
- integrationtests/tests/tests.rs
- modules/fedimint-wallet-client/src/api.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Migrates peg-in and peg-out tests to new test framework.
> refactor: migrate peg in and out test

- .github/workflows/ci-nix.yml
- flake.nix
- gateway/cli/src/main.rs
- nix/craneBuild.nix
It will only verify it for binaries built with Nix (like in CI, but unlike `cargo build ...` locally).
It will run only on `master` branch (along the place where when we build & publish release versions of our binaries). I tested it via an extra commit.
>  feat(ci): verify versions hashes were set 

- fedimint-client/src/sm/executor.rs
- fedimint-client/src/sm/state.rs
Closes https://github.com/fedimint/fedimint/issues/2696
This reduces the execution time of a transaction with 250 outputs from 1 hour to just 30 seconds.
The idea is to not throw away the trigger/transitions futures we have created after some state transition happens. We just add the next transitions to the list and keep polling them until completion.
> fix: change state machines execution from quadratic to linear time

- fedimint-server/src/lib.rs
- nix/craneBuild.nix
Investigating intermittent CI failures:
```
fedimint-lcov> thread 'test_gateway_cannot_claim_invalid_preimage' panicked at 'Could not start API server: Bind address: 127.0.0.1:38222
fedimint-lcov> Caused by:
fedimint-lcov>     0: Networking or low-level protocol error: Address already in use (os error 98)
fedimint-lcov>     1: Address already in use (os error 98)', /build/source/fedimint-server/src/lib.rs:197:14
fedimint-lcov> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fedimint-lcov> failures:
fedimint-lcov>     test_gateway_cannot_claim_invalid_preimage
```
I wish these changes were already there.
> chore: minor debugability tweaks

- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/gen.rs
- fedimint-client/src/module/mod.rs
- fedimint-core/src/core/server.rs
- fedimint-core/src/module/mod.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/consensus/server.rs
- gateway/ln-gateway/src/ng/mod.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-dummy-tests/tests/tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
This will allow passing the api version to use to the `init` function, so the client module implementation can use it to communicate using right APIs.
> refactor: move common version discovery to module gen (from module)

- scripts/build.sh
I think this was added while refactoring shell scripts to prepare way for devimint. That's all ancient history now!
> fix: remove leftover FM_POLL_INTERVAL variable in build.sh

- docs/networking.md
- flake.nix
We forgot to remove these when the old admin UI was removed.
> fix: remove 8176 port used by old admin UI

- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- gateway/ln-gateway/tests/integration_tests.rs
Fixes https://github.com/fedimint/fedimint/issues/2508
TODO
> feat(gateway-cli): Show balance per federation in info

- fedimint-testing/src/fixtures.rs
Ports above 32k are generally used by kernel for ephemeral ports
https://en.wikipedia.org/wiki/Ephemeral_port
which means they can get allocated for almost anything at any time.
That would explain random failures.
> fix: BASE_PORT should not be in ephmeral ports range

- Cargo.lock
- devimint/Cargo.toml
- devimint/src/external.rs
Realized Devimint also has a direct dependency on `tonic_lnd` that we should've bumped in #2755
> chore: bump tonic-lnd dep in devimint

- devimint/src/main.rs
This is useful when you're in an external repo waiting for devimint to start up
You can test it with this script:
```
export FM_TEST_DIR="${2-$TMP}/fm-$(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 4 || true)"
export FM_FED_SIZE=4
export FM_PID_FILE="$FM_TEST_DIR/.pid"
export FM_LOGS_DIR="$FM_TEST_DIR/logs"
cargo build ${CARGO_PROFILE:+--profile ${CARGO_PROFILE}}
export PATH=$PATH:target/debug/
devimint run-ui 2>/dev/null &
STATUS="$(devimint wait)"
echo "Status: $STATUS"
```
Should output: `Status: READY`
> chore: write ready file in run-ui command

- devimint/src/lib.rs
- fedimint-load-test-tool/src/main.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- modules/fedimint-ln-tests/tests/tests.rs
Fixes: https://github.com/fedimint/fedimint/issues/2651
Eliminates redundant information in the `gateway-cli info` command.
Before:
After:
> refactor: eliminate redundant info in gateway-cli info

- .github/workflows/ci-nix.yml
I think this was added a long time ago when we were first developing the setup UI or something. Only master should post to docker.
> fix: remove old github ref from docker branch whitelist

- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lnd.rs
PR contains small fixes for the lightning reconnect logic:
1) We no longer re-try when the gateway fails to be created. This is because the gateway creation should always succeed, if it doesn't, it likely indicates that something is wrong with the db, which will not be fixed by retrying. The retry logic has been replaced with an `expect`.
2) For LND, we try to call `get_info` before attempting to intercept HTLCs. This is because there is a small period of time where the client can connect to LND, but RPCs aren't successful. During this time, we don't want to spawn the new thread to intercept HTLCs. So instead we first wait for `get_info` to succeed, which will increase the probability of `route_htlcs` succeeding.
> fix: LND get info before intercepting HTLCs

- flake.nix
Closes https://github.com/fedimint/fedimint/issues/2798
> fix: use wl-clipboard and xclip only on linux

- fedimint-core/src/api.rs
- fedimint-server/src/config/api.rs
Add another state to config API state machine. This doesn't have any real functional change in terms of the API, but allows peers to signal they've finished verifying peer config hashes. Helps fix https://github.com/fedimint/ui/issues/14.
> feat: add VerifiedConfigs step to config API state machine

- fedimint-core/src/module/mod.rs
- modules/fedimint-mint-common/src/common.rs
I've noticed somewhere during debugging some very inefficient
encodings of `Vec<u8>` in jsonrpc calls. I'm not sure exactly,
but I think these might have been it.
Re #2762
> chore: improve json encoding of some fields

- docker/download-mutinynet.sh
When running this script, if both fedimintd and gatewayd are selected, the message about connecting to the fedimintd dashboard gets lost in the terminal. This ensures all messages for connecting are echoed at the end
> refactor: move user messages to end of script

- fedimint-core/src/bitcoinrpc.rs
- fedimintd/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-common/src/config.rs
- modules/fedimint-wallet-server/src/lib.rs
This should allow using custom signets/regtests networks and setting alternative defaults for mainnet.
If we want to expose the parameter in the UI I can open an issue there.
> Make bitcoin blockchain API used by the client configurable

- fedimint-core/src/config.rs
- fedimint-server/src/config/api.rs
Use `{e:?}` when formatting an error so we can have the backtrace
> fix: show backtrace when there is a config error

- fedimint-cli/src/lib.rs
- fedimint-core/src/admin_client.rs
- fedimint-server/src/config/api.rs
> chore: remove unused peer id argument from admin client constructor

- Cargo.lock
- fedimint-client/Cargo.toml
- justfile
Locally I get the following error, @douglaz said he gets the same on linux:
```
error[E0432]: unresolved import `super::sysrand_chunk`
--> /Users/justin/.cargo/git/checkouts/ring-236810bb234b0c6b/52a1294/src/rand.rs:307:16
|
307 |     use super::sysrand_chunk::chunk;
|                ^^^^^^^^^^^^^ could not find `sysrand_chunk` in `super`
```
> chore: update 'check-wasm' command to check fedimint-client

- fedimint-bitcoind/src/bitcoincore.rs
- fedimint-core/src/bitcoinrpc.rs
This is a rework of #2612
When `FM_BITCOIND_COOKIE_FILE` env is set, use it as path to
the cookie file.
AFAIK, auth is not required for JsonRPC, so we I don't think we
can do any automatic cookie file detection/fallback if auth
information is missing.
> Use cookie file for auth when username does not exist

- fedimint-server/src/net/peers.rs
The root of all evil is state. Especially mutable and shared. Seems to me like peer communication is using a connection where both sides think they are in control. So with higher latencies it is possible to get into a sort of a reconnect ping-pong, when one sides reconnects, starts re-sending all messages, and during that time the other side reconnects, and starts sending messages themselves... just to get new connection from the other side...
Typically the way I'd write is to have two connections (for each side) and the sending side being responsible for (re-)connecting. A bit wasteful, but makes the code easier.
Here, to avoid refactoring too much, I just make the peer with a lower `PeerId` responsible for reconnections.
Fix #2800
> fix(peer): reconnection ping-pongs

- flake.nix
cargo and some other scripts here and there require it, so technically dev env should provide it as well. Otherwise when running `nix develop --ignore-environment` things fail.
> chore(flake): provide `git`

- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-testing/src/federation.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
Previously tokio would complain that it's awaiting futures while the runtime is shut down.
> fix(fedimint-cli): clean shutdown

- fedimint-cli/src/client.rs
- fedimint-testing/src/ln/mock.rs
- fedimint-testing/src/ln/real.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lnd.rs
- gateway/ln-gateway/src/lnrpc_client.rs
- gateway/ln-gateway/src/ng/complete.rs
- gateway/ln-gateway/src/ng/mod.rs
- gateway/ln-gateway/src/ng/pay.rs
- gateway/ln-gateway/src/ng/tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-common/src/incoming.rs
- modules/fedimint-ln-common/src/lib.rs
Error messages in the gateway are not structured correctly right now, we frequently swallow the underlying error and just output a vague string that something went wrong. This makes debugging hard.
This PR improves the error handling logic to attach errors in different states in the gateway. Fixes: https://github.com/fedimint/fedimint/issues/2827
CLI output after PR:
Gateway output after PR:
Gateway output contains the underlying error message now (e.g `FailureReasonNoRoute`). Client is returned a user friendly message that gives a bit of a description on what went wrong.
> chore: improve gatewayd error messages

- Cargo.lock
- Cargo.toml
- fedimint-client-legacy/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-wasm-tests/Cargo.toml
The actual fix:
https://github.com/dpc/ring/commit/5493e7e76d0d8fb1d3cbb0be9c4944700741b802
The reason the poly stuff was missing was:
https://github.com/dpc/ring/blob/5493e7e76d0d8fb1d3cbb0be9c4944700741b802/build.rs#L326
which took me embarrassingly long to figure out.
I just re-introduced `wasm32_c`, to keep the changes minimal.
Fix #2843
I confirmed that the "import from env" is gone. Though the repro in it now fails with:
```
Error: non-200 response code: 500
{"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":""}}
error: test failed, to rerun pass `--lib`
```
but that seems something entirely different.
> fix: our ring fork not compiling c code for wasm

- nix/craneBuild.nix
The goal there is to validate the client builds for a given architecture.
> chore: build both client-legacy and client in `.#client-pkgs`

- docker/gateway-mutinynet/docker-compose.yaml
thunderhub before v0.13.20 does not have signet support and therefore fails. This upgrades to v0.13.20.
> Update to thunderhub v0.13.20 with signet support

- .tmuxinator.yml
- Cargo.lock
- devimint/Cargo.toml
- devimint/src/bin/faucet.rs
- devimint/src/federation.rs
- devimint/src/lib.rs
- devimint/src/main.rs
- devimint/src/util.rs
- devimint/src/vars.rs
- fedimint-core/src/admin_client.rs
- fedimint-core/src/api.rs
- fedimint-dbtool/README.md
- fedimint-server/src/config/api.rs
- fedimint-testing/src/federation.rs
- misc/mprocs.yaml
- scripts/mprocs.sh
- scripts/tmuxinator.sh
devimint is supposed to test binaries, but currently DKG is using fedimint as a library, making it harder to run tests with custom fedimintd binaries.
This change drops this "library" usage and makes DKG runs as api calls to the underlining fedimintd process.
One difficulty of implementing this is that we don't know before DKG what will be the peer ids. But we need to start everything with the conventional names and configurations.
So it's tricky to set up different passwords for different peers (we don't know exactly which fedimintd will be which peer). To make things simple, we are now using the same password for all the fedimintds.
> refactor(devimint): run DKG using the apis

- scripts/build.sh
Before this PR, if you wanted to inspect say `config.json` while running `just mprocs` you would need to enter user shell, and run something like `echo $FM_TEST_DIR` to find the path containing configs and logs.
Now you can just run `ls target/devimint/`:
```
$ ls target/devimint/
bitcoin/  cfg/  cln/  electrs/  env  esplora/  gw-cln/  gw-lnd/  lnd/  logs/
```
Should we add a new gitignored path for this? Or just re-use `target/` like I do here?
> fix: Symlink FM_TEST_DIR so they're easier to find

- devimint/src/federation.rs
Small fix from https://github.com/fedimint/fedimint/pull/2848. So far we've always set `federation_name` in the meta fields. Let's continue to do this.
> chore: devimint sets federation_name meta field

- devimint/src/bin/faucet.rs
- devimint/src/federation.rs
- devimint/src/lib.rs
- devimint/src/main.rs
- docs/dev-running.md
- fedimint-cli/src/lib.rs
- fedimint-core/src/api.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-server/src/config/io.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/net/api.rs
- fedimint-testing/src/federation.rs
- fedimint-testing/src/gateway.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/cli/src/main.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/tests/authentication_tests.rs
- gateway/ln-gateway/tests/integration_tests.rs
- integrationtests/tests/fixtures/mod.rs
- integrationtests/tests/tests.rs
rename clarifies what the code is and what it's used for
> chore: rename WsClientConenctionInfo and related params, methods, comments, etc

- devimint/src/external.rs
- devimint/src/federation.rs
- devimint/src/lib.rs
- devimint/src/main.rs
- devimint/src/util.rs
Based on https://github.com/fedimint/fedimint/pull/2853
This PR introduces SIGKILL on drop and will leave SIGTERM for when graceful/controlled termination is required.
It will also finish earlier when exiting tmux/mprocs, sending a SIGKILL to subprocesses (through drop of `DevFed`/daemons).
> fix(devimint): better handling of kill/terminate on subprocesses

- fedimint-client/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
Since the check if the operation exists happens outside a database transaction we can not rely on it to still be true when we later try to write to the database.
> fix(client): race condition in `reissue_external_notes`

- gateway/ln-gateway/src/ng/tests.rs
This test relies on mock LND node that treats invoices with `INVALID` description as invalid.
How is it even working right now is unclear.
> fix: skip test_gateway_client_pay_invalid_invoice without mocks

- Cargo.lock
- fedimint-core/Cargo.toml
- fedimint-core/src/task.rs
- fedimint-metrics/src/lib.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
Using a future to signal shutdown condition is much more composable, and doesn't involve "callbacks" that can hold to resources accidentally.
As a first step to remove `on_shutdown` - just make it private, so it's only used internally inside `TaskGroup`. We might replace it with something like `tokio_util::CancellationToken` etc. later.
This revealed a problem where `shutdown_join_all` does not wait for tasks spawned in the subgroup, so we fix that as well.
> chore: make `TaskGroup::on_shutdown` private

- fedimint-core/src/core/server.rs
- fedimint-core/src/module/mod.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/net/api.rs
- integrationtests/tests/fixtures/mod.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
The reduction in computational load from splitting the functions is negligible.
> cleanup: consolidate validation and application of transaction inputs and outputs

- modules/fedimint-mint-client/src/lib.rs
When integrating with the client, it is helpful for this to be public
> chore: Make MintMetaVariants public

- modules/fedimint-ln-client/src/lib.rs
When integrating with the client, it's nice to have access to db structs.
> chore: make fedimint-ln-client::db public

- fedimint-server/src/consensus/server.rs
This has been annoying me for a while, probably introduced by a refactor a few months ago.
> fix(server): logs don't claim an epoch was missing if it wasn't

- devimint/src/main.rs
- fedimint-core/src/task.rs
- fedimint-metrics/src/lib.rs
- fedimint-server/src/lib.rs
- fedimint-server/src/net/peers.rs
- fedimintd/src/fedimintd.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
It makes it easy to leak memory.
Instead, use `tokio::sync::watch` to update tasks that might be waiting for shutdown signal.
> chore: don't use `Task::on_shutdown` for `Task::make_shutdown_rx`

- devimint/src/federation.rs
- devimint/src/lib.rs
- devimint/src/main.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/db.rs
- fedimint-client/src/lib.rs
- fedimint-core/src/db/mod.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-wasm-tests/src/lib.rs
Adds ability for client builder to download config from Federation when building clients. The builder saves any successfully downloaded configs in client database. It skips re-downloads when building a client with a previously-used db, and prefers loading the config from the db.
Next:
> Client NG Join Federation

- Cargo.lock
- devimint/src/main.rs
- fedimint-cli/Cargo.toml
- fedimint-cli/src/client.rs
Allows inspecting the operation log using the CLI client. Builds on #2594.
> feat(cli-ng): list operations

- flake.nix
- nix/craneBuild.nix
`*-pkgs` are mostly about building bunch of crates together in one go, so they only really need to be split if certain packages can't build in certain places (for us: wasm).
Fix #2774
> chore: move fedimint-dbtool into `fedimint-pkgs`

- integrationtests/tests/tests.rs
`wallet_peg_outs_are_rejected_if_fees_are_too_low` is already covered by `peg_out_fail_refund` added by https://github.com/fedimint/fedimint/pull/2921
> cleanup: remove duplicated test

- integrationtests/tests/tests.rs
On the new client there is a explicit state for unconfirmed transactions and this is already being tested: https://github.com/fedimint/fedimint/blob/3ed7fe0f4504617d250136e4150900df0a799ff1/modules/fedimint-wallet-tests/tests/tests.rs#L49
So we don't need this test anymore
> cleanup: remove outdated test

- gateway/ln-gateway/src/lib.rs
I think I've seen one cli_test_lightning_reconnect failing, locally due to lnd taking its sweet time after restart, while gateway giving up on getting the hint.
The other time, I've seen it failing on parsing some weird (temporary) response.
BTW. We should rewrite this part so gateway continuously checks for hints or something. There should be no such thing as panicking for external reasons.
> fix: random ln gateway failures on start

- fedimint-cli/src/client.rs
- modules/fedimint-mint-client/src/lib.rs
> feat(mint-client): client can validate e-cash without spending

- .cargo/config.toml
- Cargo.toml
- nix/craneBuild.nix
- scripts/build.sh
- scripts/tests/rust-tests.sh
- scripts/tests/test-ci-all.sh
> fix: avoid rebuilds

- .github/workflows/ci-nix.yml
Makes it easier to handle multiple of them locally.
> chore: add run number to failed test logs artifact name

- fedimint-client/src/lib.rs
- fedimint-client/src/oplog.rs
- gateway/ln-gateway/src/ng/mod.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
If update streams have non-static lifetimes they cannot be moved between tasks/captured easily, making them less useful, in particular they cannot be given to front end code that typically doesn't have a lifetime guaranteed to be shorter than that of the client.
To achieve static lifetimes I had to clone the `Client(Arc<ClientInner>)` and move the reference into the stream. This means as long as any of these streams is still around the client will not terminate. Is this a problem @justinmoon? It does mean that, if we want to drop the client and its database (e.g. when wanting to leave and re-join a federation, all UI elements/other objects/tasks referencing these streams need to be dropped.
Fixes #2928
> Make client subscription streams static

- .cargo/config.toml
before:
```
-rwxr-xr-x 2 dpc dpc 46M Aug 18 08:38 ./target/release/fedimintd
```
after:
```
-rwxr-xr-x 2 dpc dpc 44M Aug 18 08:46 ./target/release/fedimintd
```
> fix: compress debug symbols directive not working

- scripts/build.sh
- scripts/dev/run-isolated-test/fm-run-isolated-test
> chore: make it easier to identify test's tmp dir in log dump

- Cargo.lock
- devimint/src/federation.rs
- devimint/src/main.rs
- fedimint-cli/Cargo.toml
- fedimint-cli/src/client.rs
Also adds `preserve_order` feature for `serde_json` to ensure keys appear in the same order in the output as they are defined in the code.
Resolves #2973
> Restore old CLI `info` command output schema with federation details

- flake.toolchain.nix
before:
```
> ls -alh target/aarch64-linux-android/release/fedimint-cli
-rwxr-xr-x 2 dpc dpc 14M Aug 18 15:46 target/aarch64-linux-android/release/fedimint-cli
```
after:
```
> ls -alh target/aarch64-linux-android/release/fedimint-cli
-rwxr-xr-x 2 dpc dpc 9.7M Aug 18 15:37 target/aarch64-linux-android/release/fedimint-cli
```
> chore: compress symbols on cross-compilation builds

- Cargo.toml
- flake.nix
- nix/craneCommon.nix
Before:
```
-r-xr-xr-x 2 root root  37M Dec 31  1969 fedimint-cli
-r-xr-xr-x 2 root root  43M Dec 31  1969 fedimintd
-r-xr-xr-x 2 root root  31M Dec 31  1969 fedimint-dbtool
```
after
```
-r-xr-xr-x 2 root root  57M Dec 31  1969 fedimint-cli
-r-xr-xr-x 2 root root  67M Dec 31  1969 fedimintd
-r-xr-xr-x 3 root root  53M Dec 31  1969 fedimint-dbtool
```
There's a cost, but we should get line numbers in panics/errors working.
> chore: don't strip release binaries

- devimint/src/federation.rs
- fedimint-client-legacy/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-testing/src/btc/mock.rs
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Also don't return zero when there is no block count consensus.
Build on https://github.com/fedimint/fedimint/pull/2976 and implements the fix for https://github.com/fedimint/fedimint/issues/2974 in a way that fixes the tests but don't introduce regressions on initial blockchain scanning.
> fix: make wallet tests wait consensus

- fedimint-cli/src/lib.rs
- fedimint-core/src/admin_client.rs
- fedimint-core/src/module/audit.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/net/api.rs
- integrationtests/tests/fixtures/mod.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
Closes #2948
- Adds an `AuditSummary` that calculates net assets for each module and the federation in aggregate
- Adds an RPC and admin cli command that gets the most recent audit summary
- To accomplish the goal in the [issue](https://github.com/fedimint/fedimint/issues/2948) for the guardian UI to display the total sats held by the federation, the client can parse the net assets in the wallet module
```bash
bash-5.1$ fedimint-cli --our-id 0 --password pass admin audit
{
"net_assets": 0,
"module_summaries": {
"mint": {
"net_assets": -50000000
},
"wallet": {
"net_assets": 50000000
},
"ln": {
"net_assets": 0
}
}
}
```
> Add RPC to expose audit summary

- .github/workflows/ci-nix.yml
We are [seeing a lot of tests time out](https://github.com/fedimint/fedimint/actions/runs/5953944182/job/16149367352?pr=3008) while fetching from our nix caches, there might be temporary network congestion, but that shouldn't make our tests fail.
> chore(ci): increase linux build timeout

- scripts/lib.sh
It's inconvenient when a script exits but still leaves stuff running (even if these processes have just received a signal and will hopefully die soon). This can cause failures if some other script starts right away and uses the same resources.
> feat(shell): wait for background processes to exit

- modules/fedimint-wallet-tests/tests/tests.rs
This was added recently by https://github.com/fedimint/fedimint/pull/2967
It fails like 5-10% of time. Will disable until a proper fix.
> fix: temporarily disable flaky peg_outs_support_rbf

- fedimint-cli/src/client.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/init.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- gateway/ln-gateway/src/ng/mod.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
We create a new struct called `OOBNotes` that encapsulates the federation ID + notes. Modules aren't aware of the federation ID so we also have to inject that.
Should close #2783
> Prefix federation ID to e-cash notes when spending/reissuing/validating

- Cargo.lock
- fedimint-testing/Cargo.toml
The only thing pinning `ldk-node` to a specific version is our `Cargo.lock`. But if anyone uses `fedimint-testing` as a library, our `Cargo.lock` has no effect and they'll just pull `ldk-node` from master, which will be prone to breaking.
> chore: pin ldk-node to git hash

- _typos.toml
- devimint/src/lib.rs
- fedimint-client-legacy/src/mint/backup.rs
- fedimint-core/src/db/mod.rs
- flake.nix
- justfile
- misc/git-hooks/pre-commit
In combination with #3037 it makes commit check even faster, especially on cold cache.
Before (`master` branch):
```
Executed in    4.86 secs    fish           external
usr time   25.39 secs    0.00 micros   25.39 secs
sys time   10.23 secs  466.00 micros   10.23 secs
```
After (#3037 + #3038):
```
Executed in    1.33 secs    fish           external
usr time    8.23 secs   20.29 millis    8.21 secs
sys time    1.54 secs    4.15 millis    1.54 secs
```
> chore: use faster `typos` versions

- docs/dev-running.md
Adding https://github.com/fedimint/fedimint/pull/2960#issuecomment-1693692234 to the docs for future reference.
For anyone wondering about the `[!Note]` syntax: https://github.com/orgs/community/discussions/16925#discussioncomment-6506860
> Document preventing out-of-memory when compiling

- flake.nix
- nix/craneCommon.nix
It was reported that it trips something somewhere on Macs which leads to segfault.
> chore: *do* strip symbols on MacOS

- .cargo/audit.toml
- flake.nix
This PR is adding cargo-audit inside the nix env but this PR does not solve the issue of the CI because looks like 
there is no upgrade available
```
[vincent@vincent-arch fedimint]$ cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 562 security advisories (from /home/vincent/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (511 crate dependencies)
Crate:     webpki
Version:   0.21.4
Title:     webpki: CPU denial of service in certificate path building
Date:      2023-08-22
ID:        RUSTSEC-2023-0052
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0052
Severity:  7.5 (high)
Solution:  No fixed upgrade is available!
Dependency tree:
```
But looks like the library is unmaintained …
> chore: fix cargo audit

- .github/workflows/ci-nix.yml
Backport of #3058 
(cherry picked from commit df26e32380c8272af2c941a63f5db1918daac595)
> Backport: fix(github-actions): login to publish tagged dockers images

- .github/workflows/backport.yml
This workflow is intended to automate the backport process in cases where cherry-picking succeeds without merge conflicts. For more details see [the action's README](https://github.com/korthout/backport-action#how-it-works).
I created a tag `backport releases/v0.1`. If this is added before merging it should work according to the docs. I also changed the reference workflow slightly so that it should also work if the tag is added after merging.
> chore: add backport bot

- devimint/src/external.rs
- devimint/src/main.rs
It's handy to have things like esplora and the lightning nodes in our development testing, so this starts them with `run-ui` just like `dev-fed` does.
Also added a bit of extra logging to when LND fails to connect, since that dragged me down for ~30m trying to figure that out since it fails silently.
> Start externals with `devimint run-ui`

- Cargo.lock
- devimint/Cargo.toml
- devimint/src/external.rs
- devimint/src/main.rs
- fedimint-testing/Cargo.toml
- fedimint-testing/src/fixtures.rs
- fedimint-testing/src/gateway.rs
- fedimint-testing/src/ln/mock.rs
- fedimint-testing/src/ln/mod.rs
- fedimint-testing/src/ln/real.rs
- gateway/ln-gateway/src/bin/gatewayd.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lnrpc_client.rs
- gateway/ln-gateway/src/ng/tests.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
Working towards: https://github.com/fedimint/fedimint/issues/2786
Currently, the gateway's webserver is tied to the connection status of the lightning node. This is because there are some operations that the webserver needs a lightning connection to do (like fetching route hints). However, this makes it difficult to allow for "configuration" APIs that might be needed before the lightning connection is even established.
This PR decouples the webserver from the lightning connection. The webserver is now long-lived, but has a `GatewayState` struct that allows it to be in different states. Some APIs will not be accessible when the Gateway is in certain states (i.e `GatewayState::Disconnected`). In the future, we can add states like `Configuring` to allow for a configuration phase before …
> refactor: Decouple Web Server from Lightning Connection

- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
Closes #3089.
Adds `{ config: ClientConfig; }` to the `federations: FederationInfo[]` array we get from `/info`. Unfortunately this includes the hex encoded module configs, so it might be nice to add a `modules_config_json` in the future ala #3072, but for now it's not necessary for anything we've got in the designs for the gateway UI.
Could be nice to backport this to 0.1.0 so that gateway config can incorporate this into the gateway admin for release too, but the merge is a little messy due to some refactoring that's been done here.
> feature(gateway): add ClientConfig to FederationInfo for /info api endpoint

- gateway/ln-gateway/src/lib.rs
Fixes: https://github.com/fedimint/fedimint/issues/2857
Instead of failing the whole gateway init, now we catch the error and emit a warning. Gateway operator can check which federations are currently connected by doing `gateway-cli info`
> fix: boot when a client fails to initialize

- Cargo.lock
- gateway/ln-gateway/Cargo.toml
Fix for #1978
Switch from fedimint's own fork to official release incorporating needed API addition https://github.com/ElementsProject/lightning/commit/57d21206dbeb05f085e288b9324c7bb8d76b7180.
TODO after merging: Retire fedimint's own fork?
**Pointers for what to test are welcome!**
I've gone through the manual lightning invoice back-and-forth flows described in `docs/dev-running.md` successfully. But when running `cargo test ` I get several different errors both with and without my changes:
```
ERROR connection{remote_addr=127.0.0.1:53786 conn_id=0}: jsonrpsee_server::transport::ws: WS transport error: i/o error: Broken pipe (os error 32); terminate connection: 0
```
```
ERROR pay_invoice: ln_gateway::rpc::rpc_server: error=Invalid Metadata: No federation with id …
```
> feat: Switch to vanilla cln-plugin instead of custom fork

- fedimint-core/src/api.rs
- fedimint-server/src/consensus/server.rs
- fedimint-server/src/db.rs
- fedimint-server/src/net/api.rs
Serialize db writes to these fields using a worker thread. Theoretical missed writes are not an issue, so seems like an elegant solution.
Fix #3016
> fix: db commit failures on `/config` endpoint

- fedimint-core/src/core/server.rs
- fedimint-core/src/module/audit.rs
- fedimint-core/src/module/mod.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/net/api.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
Fixes #3076, fixes #3071 
- update module summaries from module name -> module summary to module instance id -> module summary
- includes the module `kind` in the summary so consumers can identify the module without additional network round trips
- this update is necessary since multiple instances of a single module kind can exist (i.e. module kind is not guaranteed to be a singleton)
- add a default placeholder for modules without `AuditItem`s
---
Starting devimint without peg-ins
```bash
bash-5.1$ fedimint-cli --our-id 0 --password pass admin audit
{
"net_assets": 0,
"module_summaries": {
"0": {
"net_assets": 0,
"kind": "ln"
},
"1": {
"net_assets": 0,
"kind": "mint"
},
"2": {
"net_assets": 0,
"kind": "wallet"
}
}
}
```
> Refactor Audit RPC (module instance IDs and defaults)

- .github/workflows/extra-docker-images.yml
Fixes https://github.com/fedimint/fedimint/issues/3113
- the `extra-docker-images` workflow attempts to access secrets to login to docker hub which will fail on forks
- see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository
> Prevent `extra-docker-images` GH workflow on forks

- fedimint-server/src/config/mod.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
This will prevent accidentally mixing up the first release with federations previously deployed off random master commits.
Related to #3053
> chore: set consensus version to 1

- fedimint-server/src/config/mod.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
This will prevent accidentally using master with deployed federations.
Related to #3052
> chore: set consensus version on master to `u32::MAX`

- Cargo.toml
For storage and compute savings.
> chore: disable incremental builds in ci build profile

- modules/fedimint-wallet-client/src/lib.rs
> fix(wallet-client): timeout can only occur *after* `Created` state

- fedimint-core/src/db/mod.rs
- fedimint-server/src/net/api.rs
- integrationtests/tests/fixtures/legacy.rs
Instead of trying to cancel dbtx at the end (which can be skipped
by an early return like `?`), mark uncommited writes as expected
upfront.
>  fix: DBTransaction::cancel doesn't handle errors well

- integrationtests/tests/tests.rs
The test is already implemented on the new framework:
https://github.com/fedimint/fedimint/blob/5b943048333b9c6b86af1f4658f4887689e4dee6/modules/fedimint-mint-tests/tests/tests.rs#L19
> chore: remove test from old framework

- .github/templates/failed-backport-issue.md
- .github/workflows/backport.yml
Addresses what was [discussed](https://github.com/fedimint/fedimint/issues/3137#issuecomment-1714229910) on the dev call to open an issue automatically when the backport bot fails.
I'm not sure how to test this prior to merging. Perhaps a sane strategy is to carefully review then quickly revert if we notice unwanted behavior?
Useful for reviewing
- `create-an-issue` GH [action](https://github.com/marketplace/actions/create-an-issue)
- backport action [outputs](https://github.com/korthout/backport-action#outputs) (specifically `was_successful`)
- Consuming outputs from previous jobs [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs)
- outputs are unicode strings
- Referencing PR number
- GH …
> chore: open issue when backport bot fails

- .semgrep.all.yaml
- devimint/Cargo.toml
- fedimint-atomic-broadcast/src/broadcast.rs
- fedimint-atomic-broadcast/src/session.rs
- fedimint-atomic-broadcast/src/spawner.rs
- fedimint-atomic-broadcast/tests/integration.rs
- fedimint-cli/Cargo.toml
- fedimint-client-legacy/Cargo.toml
- fedimint-client/src/sm/executor.rs
- fedimint-core/Cargo.toml
- fedimint-core/src/db/mod.rs
- fedimint-core/src/task.rs
- fedimint-load-test-tool/Cargo.toml
- fedimint-load-test-tool/src/main.rs
- fedimint-logging/src/lib.rs
- fedimint-server/Cargo.toml
- fedimint-server/src/config/distributedgen.rs
- fedimint-server/src/multiplexed.rs
- fedimint-server/src/net/connect.rs
- fedimint-testing/Cargo.toml
- gateway/ln-gateway/src/bin/cln_extension.rs
- integrationtests/Cargo.toml
This helps debugging by giving tasks some meaningful name, which will show by tokio on trace debugging level.
It doesn't fully acomplish my original goal that was setting a name for threads, but it's a improvement nonetheless.
> feat: set task names

- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lnd.rs
Fixes https://github.com/fedimint/fedimint/issues/3107
If `GatewayState` is not set to `Running` prior to calling `register_clients_timer`, no task will be scheduled to re-register the gateway with the federation prior to gateway TTL expiration.
> fix: set gateway state to running prior to register clients timer

- .cargo/config.toml
- .config/nextest.toml
- nix/craneBuild.nix
`cargo nextest` is soooo much better.
The biggest improvements:
* It will capture outputs of all tests separately and only output ones that failed.
* It can kill a slow test after a timeout (and then display its output).
These alone should make debugging so much easier. Not to mention the whole thing runs faster.
>  chore: run workspace codecov tests with cargo nextest 

- devimint/src/federation.rs
- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- fedimint-client-legacy/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/mod.rs
- fedimint-core/src/api.rs
- fedimint-core/src/config.rs
- fedimint-core/src/lib.rs
- fedimint-core/src/module/mod.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-server/src/config/mod.rs
- fedimint-testing/src/federation.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/ng/mod.rs
- integrationtests/tests/fixtures/legacy.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
Large parts of the client config are binary-encoded, even when transported via JSON RPC, so it is easier to deterministically apply cryptographic operations to them without re-encoding (hashing, signing). Unfortunately this leads to difficulties when debugging or integrating with software that doesn't have access to Fedimint's encoding framework.
This PR exposes a JSON version of the client config both in the CLI as well as via the API:
* CLI: `fedimint-cli config`: fixes #3074 
* ~API: `fedimint-cli dev api config_json`: fixes #3067~ Already done in #3072. Removed commits:
* 23935ccb5531d7e14e15db500fd625daf9437471: expose config via API
* 9f29fddce08a3083751822a059f27fcad2f9d6ce: test that API and CLI command return the same config
> Expose JSON encoded client config

- fedimint-core/src/tiered_multi.rs
- modules/fedimint-mint-server/src/lib.rs
This allows us to sign a collection of blind nonces without consuming them
> refactor: TieredMulti::map() doesn't self-consume

- .github/workflows/ci-nix.yml
The MacOS build is already struggling. Disabling these two steps should save around 15 minutes of build time for it, and they are both unlikely to fail, and even if they somehow did - it shouldn't matter.
> chore(ci): skip some steps on MacOS

- .cargo/config.toml
- flake.nix
Especially in dev shell some speedup during linking is really nice.
> chore: link with mold

- devimint/src/federation.rs
- fedimint-core/src/task.rs
- fedimint-server/src/config/api.rs
Closes #2815 
These changes update the `run_dkg` API to set the server status to `ReadyForConfigGen`, then return after spawning a background task to handle the rest of coordinating DKG.
Previously, calls to `run_dkg` would block until DKG completed amongst all peers. This is troublesome for clients since there was no way to gracefully recover if a client experienced connectivity issues or elapsed a timeout.
These changes are not guaranteed to be backwards compatible for all clients, however testing against the UI repo (https://github.com/fedimint/ui/tree/c0cf511902f9e33cd66bb6438e4a56c95a395991), I verified these changes fix the issue without required changes.
_Introduces a 100s sleep in `distributed_gen`, simulating poor network behavior which causes clients to timeout_
_Same 100s sleep …
> fix: run_dkg in background task instead of blocking

- .github/workflows/ci-nix.yml
MacOS being broken is annoying, and barely anyone pays attention to notifications about it on Discord.
Seems like running MacOS check on the merge queue would not hurt, as no one has to wait for it to completely, and it auto-aggregates multiple commits, so shouldn't lag too much.
On top of #3238 to fix the broken MacOS
> chore: run macos workflow in the merge queue

- flake.lock
- flake.nix
Our build deps being the worst case scenario, and MacOS always a snowflake, we've hit some unforeseen problems after we've landed.
Has been quickly reverted and now I fixed it, so we unrevert it.
> Revert "Revert "chore: use a new incremental zstd crane mode""

- devimint/src/main.rs
- gateway/ln-gateway/src/rpc/mod.rs
- scripts/tests/gateway-reboot-test.sh
- scripts/tests/test-ci-all.sh
Reboots a running gateway instance and asserts its state progression up to `Running` state.
Feels like this should be part of gateway package, though it should still use devimint framework. hmm
> feat: test gateway reboot

- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-dummy-common/src/lib.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-dummy-tests/tests/tests.rs
A similar test was implemented on the old framework:
https://github.com/fedimint/fedimint/blob/1132d742c2357fd70a0c3691636f80637edc0adb/integrationtests/tests/tests.rs#L157
> chore: implement federation_should_abort_if_balance_sheet_is_negative

- Cargo.lock
- fedimint-logging/Cargo.toml
- fedimint-wasm-tests/Cargo.toml
- flake.nix
Fix #2222
Required updating wasm-bindgen and related packages as well.
Bumps [opentelemetry-jaeger](https://github.com/open-telemetry/opentelemetry-rust) from 0.17.0 to 0.18.0.
- [Release notes](https://github.com/open-telemetry/opentelemetry-rust/releases)
- [Commits](https://github.com/open-telemetry/opentelemetry-rust/compare/v0.17.0...v0.18.0)
---
updated-dependencies:
- dependency-name: opentelemetry-jaeger dependency-type: direct:production update-type: version-update:semver-minor ...
> chore(deps): bump opentelemetry-jaeger from 0.17.0 to 0.18.0

- nix/craneCommon.nix
> fix: `just test-ci-all` broken on Linux

- flake.toolchain.nix
Due to double symlinking `wrapToolchain` seems incompatible with current method of combining toolchain targets.
It's probably fixable, but we don't use it RN anyway.
> fix: broken building in .#cross and .#crossWasm

- fedimint-core/src/module/mod.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
Like #3254 but for server modules.
Re #3025
I'm not sure if this is not over-engineering, but it seems likely that since client side needs it, server side will need it too. We were already thinking about passing `identity: PeerId` etc. through it.
>  refactor: Future proof arguments to ServerModuleInit::init

- fedimint-logging/src/lib.rs
Importing stuff for conditional code will generate spurious warnings in some situations.
> chore: fix some warnings

- fedimint-core/src/task.rs
- fedimint-testing/src/gateway.rs
- gateway/ln-gateway/src/bin/gatewayd.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lnd.rs
- gateway/ln-gateway/tests/integration_tests.rs
Fix a infinite loop on `test_gateway_filters_route_hints_by_inbound`  where a `GatewayTest` will run, then another `GatewayTest` will start but all tasks and HTLC interceptors from the previous one are still running.
This is specially problematic for LND because you can't have two or more HTLC interceptors (both will fail).
So the solution is to properly shutdown the `GatewayTest` on `Drop`. This required to review all "blocking" calls to also select `handle.make_shutdown_rx()`.
I also added new debugging logs that helped find and solve the issue.
This improves https://github.com/fedimint/fedimint/issues/3259
>  fix: properly shutdown the gateway

- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
Previously we've been indefinitely storing all Lightning Gateway registrations and filtering any expired registrations when calling `list_gateways()`. Now, we delete expired registrations on every write of a new registration. We're deleting on write instead of on read for two reasons:
1. To optimize for read speed (since reads will likely be much higher qps).
2. To avoid potential write conflicts during a read-only API call. If `delete_expired_gateways()` is called twice at the same time (where each call opens a separate dbtx), the call that commits second will fail since they're both attempting to delete the same keys. A read-only API call that sometimes returns a DB write error would be confusing.
> feat: Lightning Gateway Registration DB Garbage Collection

- fedimint-client/src/lib.rs
- fedimint-core/src/api.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/lib.rs
Refactor gateway client builder to persist only the connection info, channel id, fees and timelock in gateway db.
The gateway client builder delegates registration with the federation to the common `ClientBuilder`, to which it provides a connection info the first time a client is registered
depends on #2734
> Refactor: Gateway Client Builder

- modules/fedimint-wallet-client/src/lib.rs
Backport of #3117 to `releases/v0.1`.
> [Backport releases/v0.1] fix(wallet-client): timeout can only occur *after* `Created` state

- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/mod.rs
This ln gateway owned DB record is inserted to and deleted from, but its values are never read. The gateway instead uses stored `FederationConfig`s to reference its registrations with federations: https://github.com/fedimint/fedimint/blob/d63752b79f15455ef3096d19e1fbf38991d250bf/gateway/ln-gateway/src/db.rs#L30-L48
Which makes the record we're deleting here redundant.
> refactor: remove ln gateway `LightningGateway ` db record

- Cargo.lock
- modules/fedimint-dummy-tests/Cargo.toml
- modules/fedimint-dummy-tests/tests/tests.rs
Closes https://github.com/fedimint/fedimint/issues/3258
Previously the test would suppose the transaction isn't accepted, but it seems that's not the case. Now we only suppose the consensus will never produce an outcome.
> fix: no more flakiness on federation_should_abort_if_balance_sheet_is_negative

- modules/fedimint-wallet-client/src/lib.rs
Partially addresses: https://github.com/fedimint/fedimint/issues/2955
This allows the bitcoin rpc method to be overridden using environment variables. 
Set `FM_BITCOIN_RPC_KIND` to `esplora`, or `electrum` (`bitcoind` is not supported yet, see below)
Set `FM_BITCOIN_RPC_URL` to the URL of the esplora or electrum server.
`bitcoind` is not supported yet because we need to update our `bitcoin`, `bitcoin_hashes`, `secp*` crates. We are currently blocked on some downstream dependencies not supporting `bitcoin 0.30.0` yet. https://github.com/fedimint/fedimint/pull/2667
> chore(wallet-client): use btc rpc client from env var

- scripts/tests/test-ci-all.sh
Now that @Maan2003 fixed #3247 , MacOS should not require this workaround.
> chore: make macos test-ci-all blazingly fast again

- devimint/src/cfg/lnd.conf
This is useful if some service running inside Docker is trying to access the LND RPC port. You can just point it at your LAN IP and it will work, where localhost won't. But devimint can continue to use localhost. 
We encountered this while integrating [torq](https://github.com/lncapital/torq).
> feat: devimint LND RPC server listens on all interfaces

- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-common/src/api.rs
`fetch_contract` is currently confusingly named, since it actually blocks and waits for a contract to exist. It is useful to have both `wait_contract` and `fetch_contract` since we also will want to validate when a contract does not exist.
> refactor: rename fetch_contract -> wait_contract

- gateway/ln-gateway/src/state_machine/complete.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-ln-client/src/incoming.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-common/src/lib.rs
`ln-common` is for sharing code across client/server boundary. `Incoming` state machine is never used on the server side, it is just shared between the client and the gateway. The gateway already depends on the client, so it is fine to just move the state machine into `ln-client`
> refactor: move incoming state machine into lightning client crate

- devimint/src/main.rs
default 20 retries is too slow for CI
> fix: flaky devimint

- fedimint-testing/src/ln/real.rs
- gateway/ln-gateway/tests/integration_tests.rs
Fixes LDK assumption of static ports after https://github.com/fedimint/fedimint/pull/3247
Fixes a bug where we were interpreting msats as sats in the LDK test.
> test: ldk port and msats fix

- flake.nix
- nix/craneCommon.nix
This eliminates any possibility of accidentally using the original version.
> chore: move `clightning-dev` into pkgs overlay

- justfile
@joschisan had some issues using the `just` command for prepare_db_migration_snapshots, so this PR intends to tweak it to make it a tad easier.
First change is to modify the environment variable to always be `force` so that the backup files are generated.
Second change is to re-purpose the `extra_args` to be the package to run, since most of the time when running this command, the user only wants to re-generate the backup for one crate.
Also added some examples.
> chore: change prepare_db_migration_snapshots justfile command

- fedimint-core/src/config.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
`fedimint-cli spend 1msat` before and after:
```
"notes": "kf/I9C5lwlSndrUo7dt5NEVy2Ecb8bx4G5bmbQdtG7ujGhTEaHZNniHnu/pgZ6X0AQEBiqT2DVKCg51ljiQk1NGjDRD2r+cKnq1JQwE2NZcQdLGLU5NLNe5AwmdLIanj2tVRC0mxXBpXNI6dh1lS6KNgPj5X0ZBclEEUMelLFbbh9wQqOhavjMzKF4QUzTQWC+IuxBT8zgmMrVl4mg1lmlyC+w=="
"notes": "kDZuAwEBAdBrqIwRc3GWVTdKgWoWpGSsNb3lYLBHKsy4stBUI5UmljLvjux7kce+MwhYKl4FBNUrpaR83qRDJ98Ii4gZpl5WNTFLSHVaBZOYyoKfMHp4s3QO85GzCV2beKdQ+3weIQ0TRNiSmGnxoNsY0eDZ5bY="
```
Re #3342
> feat: `FederationIdPrefix` in `OOBNotes` to save on the encoding size

- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/backup/recovery/tests.rs
- modules/fedimint-mint-client/src/input.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/oob.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-mint-common/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
Re #3342
`fedimint-cli spend 1msat` before and after:
```
"notes": "kf/I9C5lwlSndrUo7dt5NEVy2Ecb8bx4G5bmbQdtG7ujGhTEaHZNniHnu/pgZ6X0AQEBiqT2DVKCg51ljiQk1NGjDRD2r+cKnq1JQwE2NZcQdLGLU5NLNe5AwmdLIanj2tVRC0mxXBpXNI6dh1lS6KNgPj5X0ZBclEEUMelLFbbh9wQqOhavjMzKF4QUzTQWC+IuxBT8zgmMrVl4mg1lmlyC+w=="
"notes": "hXJ4oRcR5NkaBxZLpbf0CpojFH/vuPCxHDz0PuhVUY+lqk8P6Wle8hHGvbELY/L4AQEBj3Rgkjis+a5zc0GLFmZjPwAQgC60MX8pYhiPXaB14ZCXiGIGJxvhTvPpeB8vpQKKHFBtPCg4sxokJ0nRunbo2Gk9gnsakzaKFB/0Ky7xGA4="
```
> chore: `nonce` is redundant in `snote`

- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
Fixes #3332 
I have added the `#[serde(rename_all(serialize = "snake_case"))]` attribute to all the structs and enums  in the `fedimint-cli` package, even if they have all their attributes in snake_case (to ensure that if in future if some attributes are added to them, they do not break this stylistic guideline).
> feat: Add snake-casing for all the serde serialized structs [Fixes #3332]

- fedimint-core/src/module/mod.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
Backport of #3255
See #3356 for context.
It's a breaking change for the Rust code API for external modules, but should be invisible for external users.
Original commit message:
Like #3254 but for server modules.
Re #3025
I'm not sure if this is not over-engineering, but it seems likely that since client side needs it, server side will need it too. We were already thinking about passing `identity: PeerId` etc. through it.
> refactor!: Future proof arguments to ServerModuleInit::init

- fedimint-client/src/module/init.rs
- gateway/ln-gateway/src/ng/mod.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
Backport of #3254
See #3356 for context.
It's a breaking change for the Rust code API for external modules, but should be invisible for external users.
Original commit message:
Re #3025
> refactor: Future proof arguments to ClientModuleInit::init

- .github/workflows/backport.yml
Followup to https://github.com/fedimint/fedimint/pull/3185.
- The GH action that creates an issue if opening a backport PR fails doesn't have the correct permissions (missing `issues: write`)
- Updated permissions are referenced from the README of the [action](https://github.com/JasonEtco/create-an-issue#usage)
- Example of a failed [run](https://github.com/fedimint/fedimint/actions/runs/6484651314/job/17608968397?pr=3348)
```
Error: An error occurred while creating the issue. This might be caused by a malformed issue title, or a typo in the labels or assignees. Check .github/templates/failed-backport-issue.md!
Resource not accessible by integration
```
> Fix: Add permissions for open-issue bot

- .github/workflows/backport.yml
An [issue](https://github.com/fedimint/fedimint/issues/3366) was opened when there wasn't a failed backport. I believe this was triggered since the check for `was_successful` was at the `actions/checkout` step instead of the `open-issue` job level.
> fix: check conditional at open-issue job level

- fedimint-core/src/module/mod.rs
- fedimint-server/src/consensus/server.rs
- modules/fedimint-wallet-common/src/config.rs
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
> chore: remove `our_peer_id` from wallet config

- fedimint-core/src/module/mod.rs
- fedimint-server/src/consensus/server.rs
> feat: make guardian identity available in `ServerModuleInit::init`

- fedimint-core/src/module/mod.rs
- fedimint-server/src/consensus/server.rs
Backport of #3367 to `releases/v0.1`.
> [Backport releases/v0.1] feat: make guardian identity available in `ServerModuleInit::init`

- devimint/src/federation.rs
- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- fedimint-client-legacy/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-core/src/api.rs
- fedimint-core/src/config.rs
- fedimint-core/src/core.rs
- fedimint-core/src/lib.rs
- fedimint-core/src/macros.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-server/src/config/mod.rs
- fedimint-testing/src/federation.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/ng/mod.rs
- integrationtests/tests/fixtures/legacy.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
Manual backport of #3386 and parts of #3079 (separate client config into global/module top-level keys, add `config` CLI command + function to serialize full client config as JSON)
> Backport json client module config

- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- modules/fedimint-ln-client/src/incoming.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-client/src/receive.rs
Hopefully fixes @3332
As pointed out by @elsirion, the merged PR #3360 did not completely solve the scope of the issue. I have added the rename to snake_case attribute to all the relevant enums and structs in the `fedimint-In-client` module. 
As I am pretty new to `fedimint`, I would greatly appreciate it if you could help me with these queries along with reviewing this PR:
- Are there any commands I can run to verify the changed nature of the JSON output as shown in the original issue description?
- Is there any documentation of which libraries/modules perform what? This would help me understand the codebase better. 
Thanks!
> Add snake_case attribute to fedimint-In-client for JSON serilaization [Fixes @3332]

- Cargo.lock
- devimint/Cargo.toml
- devimint/src/external.rs
- devimint/src/main.rs
- fedimint-testing/Cargo.toml
- fedimint-testing/src/fixtures.rs
- fedimint-testing/src/gateway.rs
- fedimint-testing/src/ln/mock.rs
- fedimint-testing/src/ln/mod.rs
- fedimint-testing/src/ln/real.rs
- gateway/ln-gateway/src/bin/gatewayd.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lnd.rs
- gateway/ln-gateway/src/lnrpc_client.rs
- gateway/ln-gateway/src/ng/tests.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- modules/fedimint-ln-client/src/lib.rs
This PR backports 7 commits from master:
- [feat: Decouple web server from Lightning connection ](https://github.com/fedimint/fedimint/commit/b8dcfa1d3b39e2aac1e3a6e2fedb51eab1ae26b3)
- [fix: wait for gateway to be in running state ](https://github.com/fedimint/fedimint/commit/faa45ca26659efd45845c95faeb8310b5856a1d8)
- [fix: always add one hop route hint](https://github.com/fedimint/fedimint/commit/b6806febfe76583e8871c245e7b0ba0d84d48422)
- [fix: add stack traces and retry on lightning info failure](https://github.com/fedimint/fedimint/commit/4cbfe9ec24c81aa066aaf76f0f3ecc85cf42be94)
- [fix: boot when a client fails to initialize](https://github.com/fedimint/fedimint/commit/b1e4f76490f58d02081113e81a4bfa602f379208)
- [fix: update gateway state machine with connected …
> [Backport] Gateway Backport Fixes to 0.1.x

- fedimint-core/src/lib.rs
- modules/fedimint-mint-common/src/config.rs
Added in #3401, but deemed unnecessary. See https://github.com/fedimint/fedimint/pull/3401#discussion_r1360960757.
> chore: remove `Amount::from_coins()`

- fedimint-cli/src/client.rs
- fedimint-client/src/lib.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/db.rs
- modules/fedimint-ln-client/src/incoming.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-tests/tests/tests.rs
Builds on: https://github.com/fedimint/fedimint/pull/3318 https://github.com/fedimint/fedimint/pull/3319
Fixes: https://github.com/fedimint/fedimint/issues/3248
Intuition: adds an `index` into the `OperationId` hash so that multiple attempts to pay the same invoice are allowed. When creating the contract, the client checks to see if the contract (incoming or outgoing) already exists, and returns an error if it already does. If it does not, the `index` is incremented and committed to the database (this serves as a de-facto lock which prevents multiple threads from payment the same invoice at the same time).
When the payment is successful, the `PayType` and `ContractId` are stored in the database, which allows subsequent payment attempts to just lookup the succuessful payment in the …
> feat: Support re-attempt LN invoice payment

- modules/fedimint-mint-client/src/lib.rs
useful to cancel oob spend only using ecash notes without knowing the operation_id.
> feat(mint-client): oob_notes_operation_id

- fedimint-core/src/api.rs
> fix(client): retry RPC requests on `JsonRpcError::RestartNeeded`

- fedimint-core/src/api.rs
Backport of #3421 to `releases/v0.1`.
> [Backport releases/v0.1] fix(client): retry RPC requests on `JsonRpcError::RestartNeeded`

- devimint/src/main.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- modules/fedimint-ln-client/src/lib.rs
A common footgun is to try and pay an invoice when the "active" lightning gateway is unavailable. This results in funds being locked until the timeout, which is not a good experience. 
An easy mitigation to this is just to ping the gateway before paying the invoice, to verify that it is available. That way, funds should only be stuck if the gateway goes down between the availability check and the funding transaction. 
Partially addresses: https://github.com/fedimint/fedimint/issues/3405
Next is adding retries to paying the invoice after the funding transaction is successful.
> feat: add availability check before paying lightning invoice

- .github/workflows/backport.yml
Adding a backport label [failed](https://github.com/fedimint/fedimint/pull/3156#issuecomment-1764786458) to create a PR, but didn't create an associated issue.
I reproduced a failing backport on my fork and was able to [verify](https://github.com/bradleystachurski/fedimint/pull/23) an issue was created once these changes were included. The root cause is the [outputs](https://github.com/korthout/backport-action/blob/e53c7b292aa9985d372c178a89d416ef2176c091/README.md#outputs) from the backport action are available at the step level, but are not automatically included in the outputs for the job.
Once this PR is merged, I'll verify the fix by removing/re-adding the `backport releases/v0.1` label to https://github.com/fedimint/fedimint/pull/3156. This will trigger the backport workflow and …
> fix: save output from the backport create-pr step to job outputs

- Cargo.lock
- Cargo.toml
- fedimint-testing/Cargo.toml
- fedimint-testing/src/fixtures.rs
- integrationtests/Cargo.toml
- integrationtests/tests/fixtures/mod.rs
- justfile
- nix/craneCommon.nix
- utils/portalloc/Cargo.toml
- utils/portalloc/src/data.rs
- utils/portalloc/src/data/dto.rs
- utils/portalloc/src/lib.rs
- utils/portalloc/src/util.rs
Backport of #3156 to `releases/v0.1`.
> [Backport releases/v0.1] feat: cargo nextest support

- fedimint-client/src/lib.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/integration_tests.rs
When a gateway is connected to any two federations, it can facilitate a direct e-cash swap between these federations, without routing over lightning.
`GatewayPayInvoice` state machine checks if a proposed payment can be settled via direct swap. Specifically an LN payment that can be swapped will _have the gateway node pubkey_ and _a short channel id assigned by this gateway_ to one of it's connected federations in the route hint last hop. If these markers are present, the gateway instructs the client for the receiving federation to buy the preimage, and in turn, settles the payment in the originating federation client
> feat: gateway swap between federations

- flake.nix
Our own git hash is not very interesting when you're building a forked binary.
> feat: make replaceGitHash more usable downstream

- fedimint-core/src/api.rs
- fedimint-core/src/query.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-mint-common/src/db.rs
- modules/fedimint-mint-common/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
Instead of collecting, verifying and aggregating the ecash blind signature shares via the guardians over the broadcast we move this functionality in the client. This significantly simplifies the mint server module aus it simply returns its own signature share for every accepted mint output and is done. Most importantly though it reduces the compute and disk consumption of the mint module - and therefore the federation as whole - to a fraction. Furthermore, the compute and disk consumption is now constant instead of linear in the number of guardians.
> Client-side ecash aggregation

- .github/workflows/extra-docker-images.yml
- docker/full-tls-mutinynet/docker-compose.yaml
- docker/full-tls-mutinynet/prosody/Dockerfile
- docker/full-tls-mutinynet/prosody/entrypoint.sh
- docker/tls-download-mutinynet.sh
As fedimint uses ecash, which works very well through chat, it may be useful for test federations to have a standardized chat server like xmpp.
Uses prosody, which is very stable and lightweight. Tested on one machine with 2GB of RAM and there is no increase in memory or cpu requirements compared to current version.
> feat: add a xmpp server to full tls docker-compose

- flake.nix
- nix/flakebox.nix
Before:
```
> nix run .#fedimintd version-hash                                                                                                                                                                                       
01234569abcdef7afa1d2683a099c7af48a523c1   
```
which is the placeholder value.
> fix: missing git commits in `version-hash` commands

- fedimint-cli/src/lib.rs
- fedimint-client/src/db.rs
- fedimint-client/src/lib.rs
Removes `invite-code` command from `fedimint-cli dev` and re-adds it as a non-dev command. The invite code is sourced from client database where it was stored the first time a client is created
fixes #3178
> fix: fedimint-cli invite-code

- Cargo.lock
- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/backup.rs
- fedimint-client/src/db.rs
- fedimint-client/src/lib.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-testing/src/federation.rs
- fedimint-wasm-tests/Cargo.toml
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/client.rs
Closes #3451 
There are certain limitations with how root secret management works in `fedimint-client` today:
- A root secret cannot be provided externally. This makes `fedimint-client` difficult to compose in another application that wishes to manage the secret.
- Root secret management occurs implicitly within the `build()` call, with very little transparency to the caller. Here is the sequence of events:
- Caller simply specifies the `RootSecretStrategy` ZST flavor to use as a generic argument on the `build()` call. This is typically one of the two pre-defined types: `Plain<>` or `Bip39<>`, or some custom external flavor.
-  Using this strategy, root secret is generated by either (1) loading the secret material from the `fedimint-client` DB or (2) producing a random secret material as …
> Refactor ClientBuilder to take in DerivableSecret

- fedimint-client/src/transaction/sm.rs
- fedimint-core/src/api.rs
Originally by @douglaz as #3470 to 0.1, but we want to bring it to master first.
> fix: increase limit of max number of concurrent requests

- devimint/src/federation.rs
- devimint/src/main.rs
- scripts/dev/user-shell.sh
mprocs and tmux user shells get a ready to use `$FM_INVITE_CODE`
fix #3316
> dev: expose FM_INVITE_CODE in user shells

- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/backup.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/mod.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-testing/src/federation.rs
- fedimint-testing/src/gateway.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
An initial step for #3447
Rationale:
I'd like a `ClientWeak` to be a thing. Easy.
But then I'd also want a way for APIs to use `ClientWeak`, upgrade
it to `Client` (strong Arc), yet not allow the user of such APIs
to store them (to prevent introducing harmful ownership cycles).
For this to not require duplicating forwarding methods manually,
the inner `ClientInner` should just do as much as possible.
So in thie change I'm moving all methods to `ClientInner`,
making it more usable.
Also, now `Client` will just `Deref` to `ClientInner` to make the
whole thing mostly invisible from the user perspective. And
I think that's totally OK and even preferable. After all `Client`
is just a newtype-ed smart-pointer to `ClientInner`.
We can control the visibility of methods of `ClientInner` with …
> refactor: ClientWeak and move logic to ClientInner

- fedimint-client/src/sm/executor.rs
- fedimint-core/src/db/mod.rs
Signed-off-by: Nitesh Balusu <84944042+niteshbalusu11@users.noreply.github.com>
debug!("find by prefix");
debug!("No state transitions available, waiting before re-trying");
These two logs are creating a lot of noise on the client side, lowering them to trace.
> fix: Reduce client log levels

- docker/fedimintd-mutinynet/docker-compose.yaml
- docker/full-tls-mutinynet/docker-compose.yaml
- docker/gateway-mutinynet/docker-compose.yaml
Updates all the docker configs to use `0.1` instead of `0.1.x` so that when people run these, they're always running the latest version of the 0.1 UI. The one downside here is that if you've pulled an old image (0.1.3) and we push a new one (0.1.4) I _think_ by default Docker will just use what it has around, you'd need to run `docker-compose pull` to grab the upgraded image.
I'll let @douglaz decide which he'd prefer, otherwise I can just update all of them to use 0.1.4.
Also, fixed some that were still trying to use non-existent `v` prefixed tags.
> chore(docker): use 0.1 docker tags for ui images to always use latest 0.1.x release

- fedimint-testing/src/gateway.rs
- gateway/cli/src/main.rs
- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/tests/integration_tests.rs
Adds Network configuration to gatewayd.
Speccd' and implemented behavior:
- gatewayd starts off without a network configuration
- on `set_configuration`, gatewayd assumes network configuration if provides, or defaults to regtest
- `set_configuration` can be used to change the network config when gatewayd is in running state, provided a federation has not been connected. This prevents changing the configured network to a different setting from the connected federations
Gatewayd the only allows (re)connecting a federations whose lightning module is on the same network
Tasks:
> feat: gateway checks network on connect federation

- docker/tls-download-mutinynet.sh
This restart is unnecessary and in fact may create some errors during setup, so better remove it.
> Remove unecessary restart on docker

- Cargo.lock
- fedimint-cli/Cargo.toml
- fedimint-core/Cargo.toml
- fedimint-core/src/encoding/mod.rs
- fedimint-load-test-tool/Cargo.toml
- fedimint-testing/Cargo.toml
- fedimint-testing/src/gateway.rs
- fedimint-testing/src/ln/mock.rs
- fedimint-testing/src/ln/mod.rs
- gateway/ln-gateway/Cargo.toml
- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-ln-client/Cargo.toml
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-common/Cargo.toml
- modules/fedimint-ln-common/src/config.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-ln-server/Cargo.toml
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-ln-tests/Cargo.toml
Updates LDK to latest version
Recently `lightning_invoice` re-exported some of the stuff that you guys were using from `lightning` so that dep can be removed from some crates
> chore: Update ldk to v0.0.118

- .github/workflows/docs.yml
We don't maintain `debug` profile anymore anyway.
Fix #3540
> fix: use `ci` build profile for publishing docs

- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-tests/tests/tests.rs
This PR adds a "preimage authentication" as part of the payload that is sent to the gateway. The gateway will save the first secret that it sees. If a subsequent request does not send this same preimage authentication, the gateway will throw an error. This prevents clients that did not pay the invoice from retrieving the preimage.
Fixes: https://github.com/fedimint/fedimint/issues/2746
> feat: Add Preimage Authentication to Gateway

- Cargo.lock
- Cargo.toml
- crypto/aead/Cargo.toml
- crypto/derive-secret/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-wasm-tests/Cargo.toml
- fedimintd/Cargo.toml
Closes https://github.com/fedimint/fedimint/issues/2583
`wasm32_c` feature went away, I removed it, and everything compiled. @Maan2003 is this OK?
> chore: update to ring 0.17.5

- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
Fixes #3266 
- Gracefully handle btc_rpc errors instead of panicking
- Log the associated error and return a sane fallback
> fix: remove panics from wallet consensus_proposal

- fedimint-server/src/config/api.rs
- fedimint-server/src/lib.rs
- fedimint-server/src/net/api.rs
- Refactor to clarify reuse of `get_verification_hashes` utility between config and consensus apis
- Fix to allow repeat calls to `verified_configs` endpoint in config api
closes #3543
> fix: allow repeat calls to verify configs

- fedimint-core/src/api.rs
- modules/fedimint-dummy-client/src/states.rs
- modules/fedimint-ln-client/Cargo.toml
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-client/src/receive.rs
- modules/fedimint-ln-common/src/api.rs
- modules/fedimint-wallet-client/src/withdraw.rs
Backport of #3516 minus 86c38a5f2cfbcf875e442bbf9646ebc72991a289 since the concerned test doesn't exist on 0.1.
Fixes #3559
> Backport: Review and fix retry behavior of all state machines

- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/init.rs
- fedimint-client/src/module/mod.rs
- fedimint-core/src/db/mod.rs
- fedimint-load-test-tool/src/common.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-dummy-tests/tests/tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Now that `ClientModule` has access to its context (`Client`), it can use it instead of exposing `*Ext` trait.
I picked dummy module as a first one to refactor, because I thought it will be the easiest. Didn't realize it's used all over the tests...
Due to lifetimes issues in async context my original idea of exposing only weak pointer didn't work, but I also realized that we probably don't want to expose the whole `Client` anyway, and we should be more selective about what we allow, so decided to just delegate `Client` methods I need on the `ClientContext` for now.
While working on it I noticed lots of possible improvements, and don't want to waste time splitting things into smaller commits, etc. so just did what I need immediate to make things simpler. Will follow through with some more …
> refactor: get rid of DummyClientExt

- .github/workflows/ci-nix.yml
- Cargo.toml
- deny.toml
- devimint/Cargo.toml
- fedimint-bip39/Cargo.toml
- fedimint-dbtool/Cargo.toml
- fedimint-metrics/Cargo.toml
- fedimint-wasm-tests/Cargo.toml
- flake.lock
- flake.nix
- gateway/cli/Cargo.toml
- nix/flakebox.nix
Currently really only used to enforce approved licenses.
> chore: enable cargo-deny check in the CI 

- fedimint-server/src/config/mod.rs
- fedimint-server/src/lib.rs
- fedimint-server/src/net/mod.rs
- fedimint-server/src/net/peers_reliable.rs
- fedimint-server/src/net/queue.rs
When we switched to Aleph BFT we removed the reliability from the network layer which guarantees that all messages are eventually delivered in order. However, the config generation seems to require this reliability and has probably not failed in the tests (yet) since the connections our p2p network stack is build on are themselves already reliable enough. To prevent the config gen to fail in bad network conditions we bring the old reliable network layer back and now have to separate network layers since we keep the unreliable network layer for running consensus once we have finished the config gen. In the future we may do the config gen over the atomic broadcast which would allow us to remove the reliable network layer again.
> fix: bring back reliable network layer for config generation

- fedimint-core/src/util/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
Also add one-way `From`-trait implementation.
Per discussions in #1298.
> refactor: Rename `SafeUrl::reap_guts()` -> `SafeUrl::to_unsafe()`

- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
Same idea as #3595, see that for an explanation of the design.
Fixes #3568 (implicit versioning, but even better: extensibility without breaking old clients)
> feat(mint): make `OOBNotes` forwards-compatible

- fedimint-cli/src/lib.rs
- fedimint-core/src/api.rs
- fedimint-server/src/config/mod.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/tests/integration_tests.rs
Builds on #3591, fixes #3567
The core idea is to, instead of having a strict encoding for invite codes, having a list of TLV-encoded data fields and ignoring ones that we cannot understand. This allows to extend invite codes without breaking old clients.
https://github.com/fedimint/fedimint/blob/9cb188e537e9951778cd0c0eb4c9e9b475931eed/fedimint-core/src/api.rs#L599-L600
https://github.com/fedimint/fedimint/blob/9cb188e537e9951778cd0c0eb4c9e9b475931eed/fedimint-core/src/api.rs#L680-L693
The data can be extracted via functions instead of directly reading the fields, e.g.:
https://github.com/fedimint/fedimint/blob/9cb188e537e9951778cd0c0eb4c9e9b475931eed/fedimint-core/src/api.rs#L639-L648
> chore: make invite codes extensible

- fedimint-server/src/config/api.rs
Fixes #3499 
I am pretty sure I covered all occurrences of changes to `ConfigGenApi::state`, but I am not sure If `LOG_NET_PEER_DKG` is the appropriate log channel and I would appreciated suggestions for improving the messages.
> chore: info log whenever `ConfigGenApi::state` is changed

- .rustfmt.toml
The default edition used by rustfmt is 2015, leading to the formatter not working on files containing syntax of later versions. See [rustfmt](https://github.com/rust-lang/rustfmt)
> chore: specify rustfmt edition

- Cargo.lock
- fedimint-cli/Cargo.toml
- fedimint-cli/src/db_locked.rs
- fedimint-cli/src/lib.rs
This makes semi-concurrent use possible, as `fedimint-cli` will just wait for a different process to finish.
Can be tested in `just mprocs` by running a couple of `for i in $(seq 100); do fedimint-cli info ;done &` at the same time.
> feat(fedimint-cli): lock the database with advisory fs locks

- devimint/src/main.rs
- devimint/src/vars.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
This load test is focused on the lightning payments and is intended to be run for long periods of time:
```rust
/// Run a load test where many users in parallel will receive then send a
/// payment through lightning.
/// It's 'circular' because the funds always come back to the same user then
/// we can keep making the payments in a loop
```
It comes in three flavors (strategies) that may help stressing different parts of the gateway:
```rust
enum LnCircularStrategy {
/// The user will pay its own invoice
SelfPayment,
/// One gateway will pay/receive to/from the other, then they will swap
/// places
TwoGateways,
/// Two clients will pay to each other using the same gateway
PartnerPingPong,
}
```
This load test was fundamental to reproduce the issues on …
> feat(load-test-tool): LN circular load-test

- devimint/src/main.rs
- scripts/dev/mprocs/run.sh
This should simplify running scripts against federation.
Setup and cleanup happens automatically, no need to run things in the background, call `env` etc.
Longer scripts can be executed by making them a separate file or using exported bash functions, simulated below:
```bash
#!/usr/bin/env bash
function fake_devimimint_exec() {
>&2 echo "Starting deviming with: ${*}"
export FM_DIR=some
"$@"
}
echo "Starting our test suite"
export EXTERNAL_VARIABLE=yo
function some_test_block() {
echo "TEST is running with FM_DIR=$FM_DIR EXTERNAL_VARIABLE=$EXTERNAL_VARIABLE"
}
export -f some_test_block
export EXTERNAL_VARIABLE=ye
fake_devimimint_exec bash -c some_test_block```
```> bash test-long.sh
Starting our test suite
Starting deviming with: bash -c some_test_block
TEST is running with FM_DIR=some …
```
> feat(devimint): dev-fed --exec <cmd> 

- fedimint-cli/src/client.rs
- fedimint-client/src/module/mod.rs
- modules/fedimint-mint-client/src/lib.rs
It can take it from the `ClientContext`
> refactor: `ClientModule::handle_cli_command` doesn't need Client

- fedimint-core/src/module/mod.rs
- fedimint-server/src/consensus/mod.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
We previously had to return multiple keys per input since we had multiple ecash notes within the same input. However, we switched to single ecash note per input to reduce complexity - furthermore it seems like partially spendable inputs are generally not a good idea which is why we want to enforce it by only allowing a single pub key per input now.
> cleanup: remove ability to return multiple pks per input

- devimint/src/external.rs
- devimint/src/main.rs
- fedimint-cli/src/client.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/mod.rs
- fedimint-client/src/sm/executor.rs
- fedimint-core/src/task.rs
- fedimint-load-test-tool/src/common.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-mint-client/src/lib.rs
- Moves the ln payment from the state transition to the trigger, avoiding all the state machines to get stuck while paying HOLD invoices
Closes https://github.com/fedimint/fedimint/issues/3478
- Adds a devimint test where we pay HOLD invoices and test the above scenario
- Adds `--finish-in-background` flag to `fedimint-cli ln-pay` to let us pay HOLD invoices without blocking the terminal
- Adds a `fedimint-cli await-ln-pay` to let us get the result of a ln payment in case it was interrupted or called using the above flag
- Fixes an error on the gateway when we try to resume a ln payment
Closes https://github.com/fedimint/fedimint/issues/3639
- Minor code cleanups
> Let us properly pay HOLD invoices

- fedimint-core/src/lib.rs
- fedimint-testing/src/btc/mock.rs
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Fixes #3534 
- A user reported observing 4x the fees for an on-chain withdrawal compared to what should have been paid using `bitcoin-cli estimatesmartfee`
- We've been calculating the tx fee as `sats_per_vbyte * tx weight` instead of `sats_per_vbyte * tx_vbytes`
- `tx_weight ~== 4 * tx_vbytes`, hence we're overpaying fees 4x
> fix: calculate tx fees using vbytes

- fedimint-core/src/timing.rs
- fedimint-server/src/consensus/mod.rs
> backport: chore: add timing logs to module audits

- modules/fedimint-ln-client/src/lib.rs
this should be public like other client state machine modules.
this was broken by https://github.com/fedimint/fedimint/pull/3287
> fix: make fedimint-ln-client::receive public

- fedimint-core/src/endpoint_constants.rs
- fedimint-server/src/net/api.rs
The api got dropped as part of https://github.com/fedimint/fedimint/pull/3544 but we need it for use in the federation admin UIs
quick validate with `just mprocs` and `fedimint-cli dev api invite_code --peer-id 1`
> fix: reintroduce invite_code rpc

- gateway/cli/src/main.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
Adds RPC command to leave federation.
Leave-fed removes federation key from gateway-db and session-db, if you reconnect to the federation while still having ecash the ecash is still there.
Tested with Eric leaving federation, restarting gateway, and rejoining.
> Gateway leave federation

- fedimint-client/src/module/mod.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
>  refactor: stop ClientModule from accessing own module_id (mostly)

- fedimint-server/src/net/peers.rs
- fedimint-server/src/net/peers_reliable.rs
They're not significant enough to be useful during general use, and are expected to be happening frequently. Can be enabled when debugging connectivity issues.
> chore: peer connections should be debug level

- devimint/src/vars.rs
I want just `bitcoin-cli getblockcount` to work.
> chore(mprocs): improve `bitcoin-cli` alias

- Cargo.lock
- Cargo.toml
- fedimint-client/src/transaction/builder.rs
- fedimint-core/src/transaction.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/db.rs
The signature compression via musig relied on unstable code. We therefore switch to naive multisignatures for 0.2 and will make the signature an extendible enum to maybe enable a compressed variant in the future. Furthermore this allows us to use PublicKeys instead of XOnlyPublicKeys.
> chore: remove musig2 signature compression for transaction signatures

- gateway/ln-gateway/tests/integration_tests.rs
In [test_gateway_executes_swaps_between_connected_federations](https://github.com/fedimint/fedimint/blob/fdf7edd27162b139b98bdca137fbb38ab2d27818/gateway/ln-gateway/tests/integration_tests.rs#L1109C47-L1109C47), claiming the outgoing contract seems takes too long(?) and asserting gateway balances after a swap intermittently fails.
this change disables the assertion, while we investigate why the balances sometimes fail to update as expected
> patch: partially disable intermittently failing gateway test

- devimint/src/cfg/bitcoin.conf
- devimint/src/external.rs
Due to this timeout some tests were failing on my local machine. There is no reason for it to be so low.
> chore(devimint): increase bitcoin rpc timeout on tests

- fedimint-client/src/backup.rs
- fedimint-client/src/backup/tests.rs
- fedimint-client/src/module/mod.rs
- fedimint-client/src/module/recovery.rs
- fedimint-core/src/core.rs
- fedimint-core/src/macros.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-mint-client/src/backup.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
- modules/fedimint-wallet-client/src/lib.rs
Fixes #3654
* Makes it easier to add versioning to module backups by making them enums
* Probably enables removing `supports_backup` since there's now the `NoBackup` placeholder type (does this sound correct @dpc?)
> Introduce module associated type for backups

- modules/fedimint-ln-client/src/lib.rs
when client is fetching gateway list and attempting to apply vetted gateway meta, we should debug log cases where there is no meta override url, or if there's no configured meta override for the federation
> fix: debug logging for fetch gateways without meta overrides

- fedimint-client/src/lib.rs
- fedimint-client/src/sm/executor.rs
Fixes #3687. Tl;dr: `get_active_operations` returned the recovery operation id for which no operation log entry exists.
@dpc since you want to replace the state machines for recovery anyway and @Maan2003 has a workaround for now, do we want this fix? It likely makes the function much slower, but also prevents this from happening again in the future if SMs get used for other tasks.
> fix(client): only list operation ids with associated operations as active

- fedimint-core/src/module/version.rs
- fedimint-core/src/query.rs
- fedimint-server/src/config/mod.rs
- modules/fedimint-dummy-common/src/lib.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-dummy-tests/tests/tests.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-mint-common/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-common/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
This PR only introduces minor consensus versions and makes the client ignore it. Later we'll have to find a way to determine the most recent compatible minor consensus version the client supports, but that has time till we actually release a new minor consensus version.
Fixes #3571
> Introduce minor consensus version

- modules/fedimint-wallet-client/src/lib.rs
Deriving keys from a root key without implementing recovery from backup is dangerous. Keys might be re-used since the last used key index isn't recovered. To avoid such problems we reactivate key derivation till recovery is implemented for the wallet module.
This will take #2977+implementing module recovery for the wallet off the critical path for 0.2.0.
> fix(wallet-client): deactivate secret derivation

- fedimint-server/src/config/mod.rs
- fedimint-server/src/consensus/server.rs
Payment latency on current master (4a6a580f4eeccc7f95baa8c693c2f5ae52900a24):
```
18 gateway_pay_invoice_success: avg 5.68456783s, median 5.652043845s, max 11.529719549s, min 4.11351511s
18 gateway_create_invoice: avg 1.168869878s, median 2.123909154s, max 3.395704957s, min 19.291994ms
9 gateway_payment_received_started: avg 4.464089591s, median 4.046802124s, max 9.151851322s, min 3.32866744s
2 reissue_notes: avg 2.494038092s, median 2.630916954s, max 2.630916954s, min 2.35715923s
```
Payment latency with 95deafc7b529836785059617ace5ffc49a9ea64c:
```
2 reissue_notes: avg 1.481310515s, median 1.600800859s, max 1.600800859s, min 1.361820172s
17 gateway_payment_received_started: avg 1.958627338s, median 1.884378943s, max 2.91291775s, min 1.761244498s
34 gateway_create_invoice: avg …
```
> fix: make consensus fast again

- fedimint-client/src/lib.rs
Closes #3508
Also removes `Client::external_secret` because we can now supply a derivable secret `root->child_client_0` to the client while we use `root->other_use_case` for our external needs. When the client still managed the secret this function was the only way to use the same secret as the client.
> fix: rederive root_secret using federation ID

- gateway/ln-gateway/src/ng/pay.rs
Fixes #3712 without the tests. @douglaz said the pure fix would be relatively easy to verify, so I did not want to resolve another huge merge conflict.
> Backport: fix: refactor gateway to avoid payments freezing state machines

- Cargo.lock
- fedimint-testing/Cargo.toml
This will removes the last git dependency, allowing us to publish Fedimint to crates.io, which is a requirement for getting into nixpkgs.
To verify I ran
```bash
grep "source =" Cargo.lock | grep -v "registry+"
```
which did not output anything.
Fixes #3168
> chore: move to self-published version of ldk-node

- Cargo.lock
- fedimint-testing/Cargo.toml
Backport of #3719 to `releases/v0.2`.
> [Backport releases/v0.2] chore: move to self-published version of ldk-node

- Cargo.lock
- crypto/derive-secret/Cargo.toml
- crypto/hkdf/Cargo.toml
- crypto/tbs/Cargo.toml
- devimint/Cargo.toml
- fedimint-core/Cargo.toml
- fedimint-dbtool/Cargo.toml
- fedimint-load-test-tool/Cargo.toml
- fedimint-server/Cargo.toml
- fedimint-testing/Cargo.toml
- fedimint-wasm-tests/Cargo.toml
- fedimintd/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- misc/git-hooks/pre-commit
- modules/fedimint-ln-tests/Cargo.toml
- modules/fedimint-mint-client/Cargo.toml
- modules/fedimint-mint-common/Cargo.toml
- modules/fedimint-mint-server/Cargo.toml
- modules/fedimint-mint-tests/Cargo.toml
- modules/fedimint-wallet-tests/Cargo.toml
- nix/check-forbidden-deps.sh
- nix/flakebox.nix
- recoverytool/Cargo.toml
We don't want to pollute the crates.io namespace and also don't need all the crates published.
> chore: ensure prefix `fedimint` on all published crates

- devimint/src/main.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- Segregate `gateway_payment_received_success` and `gateway_pay_invoice_success` to detect asymmetries between receiving and sending payments
- Change `gateway_payment_received_started_{method}` to `gateway_{gateway_name}_payment_received_started` to make sure all the metrics use the same convention of referring to the gateway that is receiving/sending the payment
- Sort metrics output based on metric name
> feat: improved load-test-metrics

- Cargo.lock
- fedimint-bitcoind/Cargo.toml
- fedimint-bitcoind/src/bitcoincore.rs
- fedimint-bitcoind/src/electrum.rs
- fedimint-bitcoind/src/esplora.rs
Closes #3676 
These changes suppress error logs returned when submitting a transaction already in a block, since this is a success case (see issue thread for more details).
We are unable to address the issue with esplora (https://github.com/fedimint/fedimint/issues/3732) and aren't able to handle errors with electrs as gracefully as I'd like (https://github.com/fedimint/fedimint/issues/3731). The associated followup issues will allow us to handle these errors gracefully across all clients but requires upstream PR merges/releases and for us to update our clients.
Relevant discussion from previous PR https://github.com/fedimint/fedimint/pull/2016#discussion_r1146826022
> chore: suppress tx already submitted error logs

- modules/fedimint-mint-client/src/lib.rs
Reported by @justinmoon https://github.com/elsirion/webimint-rs/commit/598bacb21faff5bb7d5f21bf148736803b42a915#r133544363
> fix: `MintOperationMetaVariant` uses singular name

- modules/fedimint-mint-client/src/lib.rs
Backport of #3734 to `releases/v0.2`.
> [Backport releases/v0.2] fix: `MintOperationMetaVariant` uses singular name

- Cargo.lock
- recoverytool/Cargo.toml
- recoverytool/src/main.rs
Followup to https://github.com/fedimint/fedimint/pull/3709 (removing x only public keys makes tweaks 33 bytes - see [BIP-137](https://github.com/bitcoin/bips/blob/master/bip-0137.mediawiki#background-on-ecdsa-signatures))
I would normally wait to include this fix with https://github.com/fedimint/fedimint/issues/3664, however it would be nice to get this in the next release candidate for 0.2.0 sooner than later.
> fix: use 33 byte tweaks in recovery tool parser

- fedimint-server/src/net/api.rs
Fixes #3750 
Please refer to this comment for reasoning behind this approach. https://github.com/fedimint/fedimint/issues/3750#issuecomment-1829242602
Reproduced the WARN log reported in the associated issue and verified these changes no longer log a warning when running `fedimint-cli --our-id 0 --password pass admin audit` in mprocs.
Before
```
nix@lenovo-m75q:/tmp/nix-shell.yafZfU/devimint-175/logs$ rg 'DatabaseTransaction has writes and has not called commit' fedimintd-0.log
78:2023-11-28T05:23:39.844034Z  WARN db: DatabaseTransaction has writes and has not called commit. location=   0: <fedimint_core::db::CommitTracker as core::ops::drop::Drop>::drop
```
After
```
nix@lenovo-m75q:/tmp/nix-shell.yafZfU/devimint-68797/logs$ rg 'DatabaseTransaction has writes and has not called commit' …
```
> chore: ignore uncommitted dbtx writes for endpoint audits

- Cargo.lock
- recoverytool/Cargo.toml
- recoverytool/src/main.rs
Backport of #3746 to `releases/v0.2`.
> [Backport releases/v0.2] fix: use 33 byte tweaks in recovery tool parser

- fedimint-server/src/net/api.rs
Backport of #3756 to `releases/v0.2`.
> [Backport releases/v0.2] chore: ignore uncommitted dbtx writes for endpoint audits

- Cargo.lock
- fedimint-build/Cargo.toml
- fedimint-build/src/lib.rs
Backport of #3735, fixes #3745
> Backport: feat: read git hash from .cargo_vcs_info.json if compiling release

- fedimint-server/src/consensus/server.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
Should fix https://github.com/fedimint/fedimint/issues/3744 as block height votes and feerate votes are proposed every session now. The broadcast ordering capacity this consumes is negligible; the filtering in the proposal was a remnant of hbbft.
> simplification: always propose block height and feerate votes

- gateway/ln-gateway/tests/integration_tests.rs
Backport of #3762 to `releases/v0.2`.
> [Backport releases/v0.2] fix: give gateway test more time to send/receive money

- fedimint-cli/src/lib.rs
I couldn't figure out how to make authenticated RPC requests using `fedimint-cli dev api` and formatting the `params` argument correctly. Tried many variations on `'[{"auth":"pass","params":null}]'` and gave up!
Now you can invoke like:
```
fedimint-cli dev api --peer-id 0 --auth pass audit
```
> feat: can pass --auth flag to `fedimint-cli dev api`

- fedimint-core/src/db/mod.rs
- fedimint-server/src/consensus/server.rs
Backport of #3775 to `releases/v0.2`.
> [Backport releases/v0.2] fix: avoid warnings on recovery from mid session crash

- docker/full-tls-mutinynet/docker-compose.yaml
fixes #3799
in XMPP, the multi-user chat (MUC) component does not strictly require DNS config on the address, only xmpp.example.com is needed since it is a virtual host
more details: https://prosody.im/doc/chatrooms#dns
> fix: dont require muc.xmpp as a traefik router

- fedimint-cli/src/client.rs
- fedimint-core/src/lib.rs
- gateway/ln-gateway/src/lib.rs
- Closes https://github.com/fedimint/fedimint/issues/3754
- Closes https://github.com/fedimint/fedimint/issues/3752, which was caused by multiplying by 1000 instead of dividing when doing msats -> sats conversions
- Trying but currently failing to fix `BitcoinAmountOrAll::All` de/serialization. Currently it can't deserialize `all`. Demands `All`. Can't figure out how to serialize this lowercase 😭.
> fix 'withdraw all' feature

- gateway/ln-gateway/src/lib.rs
Backport of #3811 to `releases/v0.2`.
> [Backport releases/v0.2] fix: allow `mainnet` as a valid network

- modules/fedimint-ln-client/src/lib.rs
LDK supports converting from network to currency and vice versa, can remove this function
> chore: remove unneeded network_to_currency

- gateway/ln-gateway/src/state_machine/pay.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-common/src/lib.rs
Fixes #3837. Would be awesome if you could test this today @TonyGiorgio so we can get it into 0.2.0.
> fix: don't depend on std features from lightning-invoice

- modules/fedimint-ln-client/src/pay.rs
Fixes one of the things found testing this: https://github.com/fedimint/fedimint/pull/3839#issuecomment-1841085709
`is_expired()` will call LDK's internal function that looks like this (https://github.com/lightningdevkit/rust-lightning/blob/37150b4d697f723f278b6cf3f63892df272b9aa5/lightning-invoice/src/lib.rs#L1376-L1389)
```
/// Returns whether the invoice has expired.
#[cfg(feature = "std")]
pub fn is_expired(&self) -> bool {
Self::is_expired_from_epoch(&self.timestamp(), self.expiry_time())
}
/// Returns whether the expiry time from the given epoch has passed.
#[cfg(feature = "std")]
pub(crate) fn is_expired_from_epoch(epoch: &SystemTime, expiry_time: Duration) -> bool {
match epoch.elapsed() {
Ok(elapsed) => elapsed > expiry_time,
Err(_) => false,
}
}
```
Which will call …
> chore: refactor invoice expiration check in client

- devimint/src/main.rs
- modules/fedimint-wallet-common/src/config.rs
- nix/flakebox.nix
- scripts/tests/devimint-cli-test-single.sh
- scripts/tests/test-ci-all.sh
Using p2wpkh is more efficient than a 1-of-1 multisig
> feat(wallet): special-case descriptor for single-guardian instances

- .github/workflows/ci-nix.yml
Seems like bundling outputs with multiple
binaries does not work, and the bundle assumes
the name of the binary is the same as the name
of the output.
> chore: bundle per-binary debs and rpms

- docker/tls-download-mutinynet.sh
Testing out rc5, it looks like snake_case has been introduced. 
https://github.com/fedimint/fedimint/blob/ba94be6398da889acc1e89bd5ae8375b0ca999db/fedimint-core/src/api.rs#L979-L996
Note, not sure how you're handling `master` and `0.2` releases when it comes to these docker notes. I think @Kodylow is on point for that so I'll defer how to handle this PR to him.
> Update tls-download-mutinynet.sh to reflect snake case awaiting_password

- Cargo.lock
- fedimint-cli/Cargo.toml
- fedimint-cli/src/client.rs
Added support to paying lnurls. Very common nowadays.
> feat(fedimint-cli): added support to pay a lnurl

- gateway/ln-gateway/src/lib.rs
- modules/fedimint-ln-client/src/receive.rs
If the error is retryable or expected to happen then we shouldn't log it as an error. Better use warn/info.
> chore: change some errors to warns/infos

- Cargo.lock
- fedimint-wasm-tests/Cargo.toml
- flake.nix
- nix/flakebox.nix
https://crates.io/crates/wasm-bindgen/versions
This causes audits to fail:
https://github.com/fedimint/fedimint/actions/runs/7137792394/job/19438296750
> fix: wasm-bindgen 0.2.88 was yanked

- devimint/src/federation.rs
- devimint/src/lib.rs
- devimint/src/main.rs
- modules/fedimint-wallet-server/src/lib.rs
Fixes #3884
- Add helper to mine enough blocks to finalize mempool transactions
- Remove `generate_epochs` since epochs are no longer part of consensus
> fix(devimint): off-by-one error for mempool transactions

- devimint/src/external.rs
- devimint/src/federation.rs
Followup for https://github.com/fedimint/fedimint/pull/3893#discussion_r1421246877
> refactor(devimint): add get_block_count to bitcoind

- Cargo.lock
- gateway/ln-gateway/Cargo.toml
- gateway/ln-gateway/src/lnd.rs
- modules/fedimint-ln-common/Cargo.toml
- modules/fedimint-ln-common/src/lib.rs
Without this, private payments to non-public nodes are failing. Fixes #3895
Let's go through the field list of [`SendPaymentV2`](https://lightning.engineering/api-docs/api/lnd/router/send-payment-v2/index.html) to avoid missing any other required fields (I originally went by the docs *"If no payment request is specified, the following fields are required: dest, amt and payment_hash."* but that obviously didn't go that well).
* `dest`: we supply :white_check_mark:
* `amt`: redundant with the next one :+1: 
* `amt_msat`: we supply :white_check_mark: 
* `payment_hash`: we supply :white_check_mark:
* `final_cltv_delta`: we supply :white_check_mark:
* `payment_addr`: we supply, turns out to be the payment secret :white_check_mark:
* `payment_request`: not needed, we supply all necessary …
> fix: supply LN invoice features to LN gateway node

- fedimint-cli/src/client.rs
- fedimint-core/src/lib.rs
- modules/fedimint-mint-common/src/config.rs
The initial motivation for this PR was making `gateway-cli withdraw --amount` (which was using `bitcoin::Amount` through `BitcoinAmountOrAll`) accept a similar syntax to other commands that accept an `amount` (most use `fedimint_core::Amount` or `parse_fedimint_amount`).
Now we upgrade `fedimint_core::Amount` and let its `from_str` accept what `parse_fedimint_amount` was able and what `bitcoin::Amount::from_str` was able to do.
We also make `fedimint_core::Amount` serializable through  `#[serde(with = "amount::serde::as_sat")` which  is analogous to `#[serde(with = "bitcoin::util::amount::serde::as_sat")]`.
The final result is that every command line is backwards compatible but also accepts the new syntax.
> refactor: amount improvements

- fedimint-core/src/config.rs
Backport of #3908 to `releases/v0.2`.
> [Backport releases/v0.2] feat: GlobalClientConfig::federation_name()

- fedimint-client/src/lib.rs
This will hopefully help unblocking #3781 , and prevent anyone from introducing more places that would depend on it.
> chore: deprecate DatabaseSource::Reuse

- fedimint-cli/src/client.rs
- modules/fedimint-mint-client/src/lib.rs
> Make CLI spend e-cash more configurable

- fedimint-client/src/sm/executor.rs
> feat: add span for showing operation_id in state machine transition

- devimint/src/main.rs
> chore: use larger amounts in tests

- modules/fedimint-ln-client/src/lib.rs
Anyone that has used lightning in the real world has probably suffered with the usual 1 hour default expiration time on invoices. Let's help a bit the users by giving them a better default.
> feat: better invoice expiration

- fedimint-cli/src/client.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-tests/tests/tests.rs
Otherwise, fees that will be paid cannot be shown to users upfront.
> feat(ln-client): make LN gateway known upfront

- Cargo.lock
- fedimint-core/Cargo.toml
- fedimint-core/src/api.rs
- fedimint-load-test-tool/Cargo.toml
In the [jsonrpsee 0.21.0 release](https://github.com/paritytech/jsonrpsee/releases/tag/v0.21.0), the refactor I did for handling generic data streams was merged, which is required to add Tor support using Arti on #2610.
Updates the `jsonrpsee-*` version to `0.21.0`, also use the specific `jsonrpsee_core::client::Error` now, it has been splitter into client/server specific variants now, check: https://github.com/paritytech/jsonrpsee/issues/1088
> build(deps): bump `fedimint-core` and `fedimint-load-test-tool` jsonrpsee to `0.21.0`

- devimint/src/federation.rs
- devimint/src/main.rs
- devimint/src/vars.rs
- fedimint-cli/src/client.rs
- fedimint-cli/src/db_locked.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/backup.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/mod.rs
- fedimint-core/src/config.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-testing/src/federation.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/client.rs
- modules/fedimint-mint-client/src/lib.rs
Fix #3748
* split the 3 cases of initalization (to be built on later)
* require only needed args, instead of using Option gymnastics
> chore: refactor `Client` initialization

- fedimint-core/src/endpoint_constants.rs
- fedimint-core/src/time.rs
- fedimint-load-test-tool/src/main.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-client/src/receive.rs
- modules/fedimint-ln-common/src/api.rs
- modules/fedimint-ln-common/src/contracts/mod.rs
- modules/fedimint-ln-server/src/lib.rs
- utils/portalloc/src/lib.rs
Closes https://github.com/fedimint/fedimint/issues/3881
Timeout now will happen at the right time: when we're sure the preimage decryption is pending and the expiry time relative to the invoice timestamp has passed.
There are no risks anymore of the timeout not happening because the state machines have been interrupted or it incorrectly happening while the client is dealing with network issues.
> fix: more robust lightning receive

- modules/fedimint-mint-client/src/backup/recovery.rs
> Backport: fix(mint-client): invalidate all spent notes on recovery

- devimint/src/vars.rs
- fedimint-rocksdb/src/lib.rs
- nix/esplora-electrs.nix
Fix https://github.com/fedimint/fedimint/issues/3665
This shrinks each devimint tmp directory from 1.3GB to 83MB. This was caused be excessive default rocksdb pre-allocation, especially in esplora-electrs, which is not useful for tiny testing setups.
> Make devimint tmp dir much smaller

- crypto/aead/Cargo.toml
- crypto/derive-secret/Cargo.toml
- fedimint-bip39/Cargo.toml
- fedimint-bitcoind/Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-dbtool/Cargo.toml
- fedimint-metrics/Cargo.toml
- fedimint-rocksdb/Cargo.toml
- fedimint-server/Cargo.toml
- fedimint-testing/Cargo.toml
- fedimintd/Cargo.toml
- gateway/cli/Cargo.toml
- modules/fedimint-dummy-client/Cargo.toml
- modules/fedimint-dummy-common/Cargo.toml
- modules/fedimint-dummy-server/Cargo.toml
- modules/fedimint-ln-client/Cargo.toml
- modules/fedimint-ln-common/Cargo.toml
- modules/fedimint-ln-server/Cargo.toml
- modules/fedimint-mint-client/Cargo.toml
- modules/fedimint-mint-common/Cargo.toml
- modules/fedimint-mint-server/Cargo.toml
- modules/fedimint-wallet-client/Cargo.toml
- modules/fedimint-wallet-common/Cargo.toml
- modules/fedimint-wallet-server/Cargo.toml
- recoverytool/Cargo.toml
- utils/portalloc/Cargo.toml
Fixes #3946 and hopefully makes docs.rs work. See how e.g. `fedimintd` fails to build and thus doesn't have docs shown: https://docs.rs/crate/fedimintd/0.2.0/builds/1062229
I added the meta field to all crates that might remotely depend on something in Fedimint that uses the task builder. I probably over-did it a bit, but it shouldn't hurt and once #3951 is fixed we can roll it back anyway.
> chore: give build instructions to docs.rs

- modules/fedimint-ln-client/src/receive.rs
Backport of #3955 to `releases/v0.2`.
> [Backport releases/v0.2] fix(client): missing expiry time

- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/receive.rs
- modules/fedimint-ln-common/src/api.rs
https://github.com/fedimint/fedimint/pull/3929 was a mess:
1) It required https://github.com/fedimint/fedimint/pull/3955
2) It still doesn't fully solve the timeout handling as it calls `context.wait_key_exists(ContractKey(contract_id))` which will block until a payment has been received.
In this situation the client will never timeout because a timeout will be considered an error and it will keep retrying.
3)  It still considers that a `DecryptedPreimage::Pending` is a good moment to timeout. But in fact if we got `DecryptedPreimage::Pending` the payment may still succeed, so we can't timeout here.
This PR tries to fix these issues. It also introduces tests for the expiration time check.
Note: this PR should be fully compatible with previous releases. We are just properly using an …
> fix(lightning): proper handle timeouts while receiving a payment

- devimint/src/federation.rs
- devimint/src/main.rs
Adds latency test coverage to transactions between two fedimint clients in a federation.
From initial tests, turns out these internal transactions are currently much slower than LN sends / receives!
A follow up here is to investigate and improve internal payments perf
```rs
================= RESULTS ==================
REISSUE: min: 1.7s, avg: 1.8s, median: 1.8s, p90: 1.9s, max: 2.0s, sum: 54.1s
LN SEND: min: 2.9s, avg: 3.1s, median: 3.1s, p90: 3.2s, max: 4.4s, sum: 62.8s
LN RECV: min: 1.9s, avg: 2.2s, median: 2.2s, p90: 3.0s, max: 3.1s, sum: 44.1s
FM PAY: min: 4.2s, avg: 4.7s, median: 4.4s, p90: 5.0s, max: 9.4s, sum: 93.5s
```
closes #3695
> test: latency of internal payments within fed

- Cargo.lock
```
fedimint-ci-audit> Crate:     zerocopy
fedimint-ci-audit> Version:   0.7.29
fedimint-ci-audit> Title:     Some Ref methods are unsound with some type parameters
fedimint-ci-audit> Date:      2023-12-14
fedimint-ci-audit> ID:        RUSTSEC-2023-0074
fedimint-ci-audit> URL:       https://rustsec.org/advisories/RUSTSEC-2023-0074
fedimint-ci-audit> Solution:  Upgrade to >=0.2.9, <0.3.0 OR >=0.3.2, <0.4.0 OR >=0.4.1, <0.5.0 OR >=0.5.2, <0.6.0 OR >=0.6.6, <0.7.0 OR >=0.7.31
```
> chore: update zerocopy to fix vulnerability

- fedimint-client/src/lib.rs
- fedimint-core/src/config.rs
- fedimint-core/src/transaction.rs
- fedimint-server/src/atomic_broadcast/data_provider.rs
Fixes #3868. While the increase of `BYTE_LIMIT` prevents oversized transactions from being generated through standard usage patterns, there is still a risk of third party modules or hand crafted transactions exceeding the limit. This makes the client throw an error in these cases.
> fix: client detects too big transactions and rejects them

- fedimint-testing/src/gateway.rs
- gateway/cli/src/main.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
Fixes #3815. I am not sure it's completely done and would appreciate feedback.
> chore: separate fedimint config info from gateway info endpoint

- devimint/src/main.rs
restore has become really slow, we need to track these.
> feat: latency test for restore

- fedimint-bitcoind/src/bitcoincore.rs
- fedimint-bitcoind/src/electrum.rs
- fedimint-bitcoind/src/esplora.rs
- fedimint-bitcoind/src/lib.rs
- fedimint-testing/src/btc/mock.rs
- modules/fedimint-wallet-client/src/deposit.rs
In some circumstances, possibly triggered by a bug or unrelated failure it seems possible
for us to keep calling blockstream.info (or other electrs/esplora backend) from the autocommit loop.
I identified two orthogonal improvements:
* watch needs to be called only once, so calling it again on retries is a waste of time
* watch & get are two separate operations so should be treated as such
Each of them separately is effectively fixing the problem we witnessed, but both make sense, so I guess makes sense to land both.
> fix: prevent spamming blockchain.info with requests

- flake.lock
Should fix CI for https://github.com/fedimint/fedimint/pull/3997 and https://github.com/fedimint/fedimint/pull/3994
> chore: `nix flake update`

- fedimint-cli/src/client.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-tests/tests/tests.rs
Currently it doesn't seem it is possible (at least non-obvious) for how to get the preimage for your own invoices. This is useful for verifying if people paid your invoices and for things like zaps.
Would be nice if this was backported to 0.2.1 as this isn't a breaking change
> feat: Return preimage when creating ln invoice

- fedimint-core/src/db/mod.rs
Reviewing some of the DB code, found some typos :)
> chore: fix some typos in the database structs

- devimint/src/federation.rs
- devimint/src/lib.rs
- devimint/src/main.rs
Removes in-built client from devimint `Federation`, and replaces it with means to create one or more clients connected to the devimint fed instance. This allows us to write devimint tests that need more than one client.
> motivation: need for #3695 and #3696
> refactor: remove in-built client in devimint fed

- fedimint-core/src/db/mod.rs
this makes transactions less likely to conflict in next try
originally part of #3989
> fix: add exponential backoff to autocommit with random delay

- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/tests/integration_tests.rs
Fixes: https://github.com/fedimint/fedimint/issues/4013
This change updates the `FederationConfig` for each federation in the gateway and also re-registers the lightning gateway when the routing fees are updated. 
This PR also gets us most of the way to per-federation routing fees: https://github.com/fedimint/fedimint/issues/3961
> fix: re-register gateway when routing fees are updated

- Cargo.toml
- crypto/aead/Cargo.toml
- fedimint-dbtool/Cargo.toml
- fedimint-load-test-tool/Cargo.toml
- fedimint-metrics/Cargo.toml
- recoverytool/Cargo.toml
Added Readme.md links in those Crate.toml where there exists a README.md file in that individual crate 
#3924
> chore: add Readme.md links in each Cargo.toml

- Cargo.lock
- fedimint-core/src/admin_client.rs
- fedimint-core/src/api.rs
- fedimint-core/src/endpoint_constants.rs
- fedimint-server/Cargo.toml
- fedimint-server/src/config/api.rs
- fedimint-server/src/config/io.rs
After setting config gen params and before starting consensus, any peer can initiate a restart of the federation setup using `restart_federation_setup` rpc.
> **server-side behavior**
- This API sets the peer server in `SetupRestarted` status.
- The Leader server waits for all peers to progress to `SetupRestarted`.
- Leader then automatically makes progress to `AwaitingPassword`.
- Followers watch leader status and when they see `AwaitingPassword`, they also make progress to the same state
All peers can then begin the setup process
> **suggested user experience**
While the server is in any of these states `SharingConfigGenParams` | `ReadyForConfigGen` | `ConfigGenFailed` |  `VerifyingConfigs` | `VerifiedConfigs`, the setup UI should watch peer information in consensus status. Should any …
> feat: restart federation setup

- README.md
The previous URL incorrectly pointed to 'lightning-gateway', whereas it should direct users to 'fedimint-gateway'. This change ensures users are guided to the correct page for setting up the Lightning Gateway in the context of Fedimint on Mutinynet.
> fix: incorrect URL for Launch Lightning Gateway in Mutinynet setup guide

- .github/workflows/ci-nix.yml
Fix:
"upload artifacts" we already have is not for uploading release artifacts.
> chore(ci): upload release artifacts on tag builds

- Cargo.lock
- Cargo.toml
> chore: upgrade tonic_lnd to 0.2.0

- modules/fedimint-mint-client/src/backup/recovery.rs
This is effectively undoing some parts of
21da63533cf34722cff1e5afb9e8e06cd02a5eeb
hopefully to improve the real life recovery performance, which people are reporting as very slow.
The WIP recovery refactoring should render this irrelevant, but might be a good bandaid for 0.2.
Backport of #4019 which won't get merged because #4042 implements the same thing post recovery refactoring.
> chore: speed up recovery by batching and streaming (v0.2 non-backport)

- modules/fedimint-ln-common/src/lib.rs
If you are using a different version of rust-lightning and rust-bitcoin then you need to import the version that fedimint is using as well. This makes it so you can get if from the ln common module
> feat: reexport lightning_invoice and bitcoin

- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-testing/src/federation.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/complete.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/integration_tests.rs
See https://github.com/fedimint/fedimint/pull/3781#issuecomment-1885878214 for context.
- Removes `DatabaseSource`
- Adds check when connecting a federation if the federation has already been connected
- Wraps every usage of `lnrpc` behind a wrapper function that first checks if the lightning node is connected to the gateway.
> refactor: Only load federation clients when gateway boots

- fedimint-core/src/api.rs
Milder version of #4064 (and #4051) that solves the problem directly and can hopefully be merged and backported fast (while a more general solution is fleshed out).
> fix: mark JsonRpcClientError:Call as retryable regardless of code

- fedimint-testing/src/gateway.rs
- fedimint-testing/src/ln/mock.rs
- fedimint-testing/src/ln/mod.rs
- fedimint-testing/src/ln/real.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/cln.rs
- gateway/ln-gateway/src/lightning/lnd.rs
- gateway/ln-gateway/src/lightning/mod.rs
- gateway/ln-gateway/src/state_machine/pay.rs
This PR refactors the Gateway's lightning implementations into a `lighting` directory.
Started as a hack to get the gateway to work with the alby api, but halfway through realized this would be a good refactor for adding additional implementations and apis as lightning options for the gateway in the future.
> refactor: Lightning Dir for Gateway

- fedimint-core/src/config.rs
- fedimint-core/src/encoding/mod.rs
- fedimint-server/src/config/distributedgen.rs
For the Nostr federated client module that @EthnTuttle and I are building, I need to be able to exchange some messages during DKG to setup the Frost key. There might be a better way to implement FROST directly into Fedimint, but I think it also might be helpful to allow modules to exchange arbitrary messages during DKG. This PR adds `DkgPeerMsg::Module(Vec<u8>)` that allows modules to exchange any type of message during DKG.
Note: `exchange_public_keys` could probably be replaced with `exchange_with_peers<PublicKey>` but I'm not sure if that's backwards compatible, so I left the existing function.
> chore: add module dkg message

- fedimint-client/src/transaction/sm.rs
- fedimint-core/src/api.rs
- modules/fedimint-dummy-client/src/states.rs
- modules/fedimint-ln-client/src/incoming.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-client/src/receive.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-wallet-client/src/withdraw.rs
After thinking about #4051 and discussion inside it, it seems to me that `is_retryable` is just a terrible pattern, so in this change:
* get rid of `is_retryable`
* make all federation errors retryable
* add function to report only errors that is somewhat important
* go over callsites and do something (hopefully) better
> refactor: client error handling

- Cargo.lock
- devimint/src/main.rs
- fedimint-cli/src/lib.rs
- fedimint-client/Cargo.toml
- fedimint-client/src/backup.rs
- fedimint-client/src/db.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/init.rs
- fedimint-client/src/module/mod.rs
- fedimint-client/src/module/recovery.rs
- fedimint-client/src/sm/executor.rs
- fedimint-core/src/core.rs
- fedimint-core/src/db/mod.rs
- fedimint-core/src/module/registry.rs
- fedimint-core/src/task.rs
- fedimint-server/src/config/api.rs
- fedimint-server/src/multiplexed.rs
- fedimint-testing/src/gateway.rs
- fedimintd/src/fedimintd.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/client_db.rs
- modules/fedimint-mint-client/src/lib.rs
- nix/flakebox.nix
Re #2977
This is a initial step towards client module recovery system described/agreed on in #2977.
Module recoveries work as just standalone function (future): `ClientModuleInit::recover` called instead of usual `ClientModuleInit::init`. This makes module job easier (in a sense at least), as it is not constantly being interrupted (will help with efficient streaming through blocks). It's up to the implementation to periodically save state and send progress updates, but a follow up changes will introduce helper functions to set the module implementation on the right track. It also avoids saving tons of in-progress data in the state machine execuation log. Conceptually module recovery is not a client state machine.
Module recovery state is persisted and tracked and modules become available …
> chore: client module recovery refactor

- Cargo.lock
- fedimint-server/Cargo.toml
- fedimint-server/src/atomic_broadcast/backup.rs
- fedimint-server/src/consensus/server.rs
> fix: use fedimint-aleph-bft

- modules/fedimint-ln-server/src/lib.rs
Replaces: https://github.com/fedimint/fedimint/pull/3389 @tvolk131 for visibility
Working towards https://github.com/fedimint/fedimint/issues/4027 I'd like to de-register the gateway when it receives SIGINT or it leaves the federation, but we can't do that until we store gateways by `gateway_id`, otherwise we risk deleting multiple gateways if they share the same `node_pub_key` (should only happen if using a custodial API)
I believe this is a rare care where a change to a database structure does not require a migration. The structure of the key stays the same (it is still a `PublicKey`), the value is just different. Additionally, on the next registration of the gateway, a new record in the db will be created, and the old one will just be cleaned up once it expires. Because of this, I do …
> chore: store Lightning Gateway Registrations by gateway id

- devimint/src/bin/faucet.rs
- devimint/src/lib.rs
- fedimint-testing/src/gateway.rs
- gateway/cli/src/main.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-ln-common/src/lib.rs
Declares v1 for gateway apis with the following schema: `gateway-http-host/version/endpoint`
After this change, clients should prefer to call `gateway-http-host/v1/endpoint`. The non-versioned api with the format `gateway-http-host/endpoint` is still supported but will likely will deprecate this, or arbitrarily change the apis as necessary
This PR proposes that the gateway should register a versioned api url as part of `LightningGateway` payload. The client can
- use the api as is, assuming compatibility. **This is the current client behaviour.**
- check the version before constructing compatible payloads
- ignore a gateway that doesn't have compatible api version
closes #3904
> feat: versioned gateway api

- Cargo.lock
- devimint/Cargo.toml
- devimint/src/main.rs
- devimint/src/util.rs
- fedimintd/src/fedimintd.rs
Fixes #4017 
I verified locally against the full matrix of backwards-compatibility tests that `devimint_cli_test_single` succeeds (see: https://github.com/fedimint/fedimint/pull/4010).
```
Backwards-compatibility tests summary:
fed_version  client_version  gateway_version  exit_code
v0.2.1       v0.2.1          current          0
v0.2.1       current         v0.2.1           0
v0.2.1       current         current          0
current      v0.2.1          v0.2.1           0
current      v0.2.1          current          0
current      current         v0.2.1           0
```
> fix: make single guardian devimint cli test backwards-compatible

- Cargo.lock
- fedimint-cli/src/lib.rs
- fedimint-client/src/backup.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/transaction/sm.rs
- fedimint-core/Cargo.toml
- fedimint-core/src/admin_client.rs
- fedimint-core/src/api.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-server/src/consensus/server.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-dummy-client/src/states.rs
- modules/fedimint-dummy-tests/tests/tests.rs
- modules/fedimint-ln-client/src/incoming.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-mint-client/src/backup.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-wallet-client/src/withdraw.rs
On top of #4035 and #4042.
This is a version #4046 without global statics.
Wasm couldn't handle `lazy_static`, and globals are icky. The price is wrangling with an already overly complicated set of traits in this area.
>  feat: await_block LRU cache (non-global) 

- fedimint-cli/src/lib.rs
If `params` fails to get parsed into JSON -> then convert it into valid `JSON String` wrapped in `Value::String`
fix #3194
> chore(fedimint-cli): convert invalid JSON data to JSON string

- .github/workflows/ci-backwards-compatibility.yml
The discord `alerts` channel is too noisy with these alerts, especially while we know there are outstanding fixes.
> chore: disable discord alerts for backwards-compatibility

- fedimint-server/src/db.rs
- modules/fedimint-dummy-tests/tests/tests.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-mint-tests/tests/tests.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Running `cargo test` causes an error with the db migration tests since the tracing subscriber is already setup. Simple fix is just to ignore the error.
> fix: ignore TracingSetup error in migration tests

- nix/flakebox.nix
This wasn't doing anything, which OK, but might be confusing.
> chore: delete incorrect argument

- fedimint-testing/src/gateway.rs
- gateway/cli/src/main.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
Fixes #3977 
- Builds off of https://github.com/fedimint/fedimint/pull/4037
- Fixes backwards-incompatibility introduced in https://github.com/fedimint/fedimint/pull/3847 and  https://github.com/fedimint/fedimint/pull/3880
> fix: make gateway api backwards-compatible

- fedimint-core/src/encoding/mod.rs
- fedimint-core/src/tiered_multi.rs
Re #4111
Re https://github.com/rust-bitcoin/rust-bitcoin/issues/2390
Due to Rust limitations, we can't have impls for both `Vec<T>` and `Vec<u8>`. Handling byte case in a generic way is potentially *very* inefficient, and we do use it in some places, thought it's hard to find all of them (and then prevent even more from being introduced).
The most appealing approach seems to be specializing that case using `TypeId` check and `unsafe`.
Cons:
* `TypeId` requires `'static` bound
* unsafe (but small and easy to reason about)
Pros:
* zero cost (at runtime)
* works automatically everywhere
* no loss in ergonomics
**Edit**:
In idle `just mprocs` I can't tell if there's any performance difference.
> chore: specialize `Encodable`/`Decodable` for bytes

- devimint/src/federation.rs
- devimint/src/main.rs
- devimint/src/util.rs
- scripts/tests/test-ci-all.sh
Fixes [#4106](https://github.com/fedimint/fedimint/issues/4016)
For visibility, resurfacing this comment from the associated issue:
> Should we adapt the test script instead here? At least in my mind we didn't commit to CLI stability (maybe we should? @justinmoon)
https://github.com/fedimint/fedimint/issues/4016#issuecomment-1893662992
This approach resolves by adapting the test script and doesn't change the CLI.
> fix: make devimint backup & restore test backwards-compatible

- fedimint-core/src/task.rs
- fedimint-core/src/util/mod.rs
- fedimint-testing/src/gateway.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- gateway/ln-gateway/src/state_machine/pay.rs
fixes https://github.com/fedimint/fedimint/issues/4165
based on #4174
> Better gatewayd logs

- modules/fedimint-ln-client/src/lib.rs
fixes #4110 
~~just put a lock around it for now~~
return error on concurrent calls
> fix: make set_active_gateway concurrency safe

- .github/workflows/ci-backwards-compatibility.yml
Now that all backwards-compatibility issues have been resolved, we can re-enable the discord alerts.
See: https://github.com/fedimint/fedimint/pull/4139#issuecomment-1915905704
> chore: re-enable discord alerts for backwards-compatibility

- fedimint-server/src/db.rs
- fedimint-testing/src/db.rs
- justfile.fedimint.just
- modules/fedimint-dummy-tests/tests/tests.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-mint-tests/tests/tests.rs
- modules/fedimint-wallet-tests/tests/tests.rs
It causes different features/deps being selected, which causes rebuilds of almost whole project, which can be painful.
Instead of `cargo test -p pkg` it's better to use
`cargo nextest run -E 'package(pkg)'`.
> fix(justfile): don't use `cargo -p`

- fedimint-server/src/config/api.rs
> chore: during dkg generate peer-ids by peer name ordering

- modules/fedimint-ln-common/src/lib.rs
Backport of #4065 to `releases/v0.2`.
> [Backport releases/v0.2] feat: reexport lightning_invoice and bitcoin

- fedimint-dbtool/src/dump.rs
- fedimint-server/src/consensus/server.rs
- fedimint-server/src/db.rs
I `git revert`ed the corresponding cache session outcome count commit on 0.2 to avoid merge-conflicts from cherry-picking the revert commit, then cherry-picked @joschisan's actual changes. 
Backport #4159
> Backport: remove redundant session counter from db

- fedimint-cli/src/lib.rs
- fedimint-core/src/api.rs
- fedimint-core/src/query.rs
Requiring full participation in this one place is unexpected behaviour in a bft system. All query strategies should be bft.
> fix: remove non-fault tolerant query strategy

- .typos.toml
- misc/git-hooks/pre-commit
`pre-commit` is generated by flakebox, so must not contain custom changes.
For ignoring `db/` in `typos`, `.typos.toml` can be used.
For ignoring newlines, trailing whitespace during during db snapshots... ... I guess just use a one time `git commit --no-verify`.
> fix: pre-commit modified manually

- gateway/ln-gateway/tests/integration_tests.rs
The web server is restarting so we may need to wait a bit longer. Multiple code coverage CI failures due to this.
```
Error: error sending request for url (http://127.0.0.1:20037/info): error trying to connect: tcp connect error: Connection refused (os error 111)
```
https://github.com/fedimint/fedimint/actions/runs/7704054812/job/20995614440?pr=4169#step:6:1719
> fix: bump retry count for test_gateway_configuration

- devimint/src/federation.rs
- devimint/src/tests.rs
`reconnect_test` is flakey, which can likely be resolved by polling.
https://github.com/fedimint/fedimint/actions/runs/7747755393/job/21128923550#step:5:1433
```
2024-02-01T21:34:35.3311143Z 00:00:30 Error: command: /nix/store/fdbrlr3n4n94gs5a1lgnzskhgmv8pimq-fedimint-cli/bin/fedimint-cli --data-dir=/tmp/nix-shell.qkvd7G/devimint-73588/cl
ients/default dev api module_2_block_count
2024-02-01T21:34:35.3312020Z 00:00:30
2024-02-01T21:34:35.3312197Z 00:00:30 Caused by:
2024-02-01T21:34:35.3312415Z 00:00:30     exit status: 1
2024-02-01T21:34:35.3312648Z 00:00:30     stdout:
2024-02-01T21:34:35.3312845Z 00:00:30
2024-02-01T21:34:35.3313047Z 00:00:30     stderr:
2024-02-01T21:34:35.3313661Z 00:00:30     2024-02-01T21:34:34.877575Z  INFO fedimint_cli::db_locked: Acquiring database lock …
```
> fix: poll in reconnect test

- fedimint-core/src/encoding/mod.rs
- fedimint-derive/src/lib.rs
This was debugging a decoding bug in LN NG.
> chore: print more useful error message on enum decode errors

- Cargo.lock
- devimint/src/main.rs
- fedimint-cli/src/lib.rs
- fedimint-core/src/util/mod.rs
- fedimint-dbtool/Cargo.toml
- fedimint-dbtool/build.rs
- fedimint-dbtool/src/main.rs
- fedimintd/src/fedimintd.rs
- gateway/ln-gateway/src/bin/cln_extension.rs
- gateway/ln-gateway/src/bin/gatewayd.rs
- gateway/ln-gateway/src/lib.rs
We added `fedimint-dbtool` as an output in https://github.com/fedimint/fedimint/pull/4075. This causes the release packages step in CI to fail since `fedimint-dbtool` doesn't have a version-hash command.
```
error: unrecognized subcommand 'version-hash'
Usage: fedimint-dbtool --database <DATABASE> <COMMAND>
```
https://github.com/fedimint/fedimint/actions/runs/7771368281/job/21192586123#step:6:47
Relevant CI step: https://github.com/fedimint/fedimint/blob/6d20243/.github/workflows/ci-nix.yml#L389
Verified locally with
```
nix@lenovo-m75q:~/fedimint$ ./target/debug/fedimint-dbtool version-hash
5a941b7339f332b3000000008d37e4f8e611f4
```
> fix: add fedimint-dbtool version-hash

- fedimint-client/src/lib.rs
- fedimint-client/src/module/init.rs
- fedimint-client/src/module/mod.rs
- fedimint-client/src/sm/executor.rs
- fedimint-client/src/sm/mod.rs
- fedimint-client/src/sm/notifier.rs
- fedimint-client/src/sm/state.rs
- fedimint-client/src/transaction/builder.rs
- fedimint-client/src/transaction/sm.rs
- gateway/ln-gateway/src/state_machine/complete.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-dummy-client/src/states.rs
- modules/fedimint-ln-client/src/incoming.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-client/src/receive.rs
- modules/fedimint-mint-client/src/input.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/oob.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-wallet-client/src/deposit.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-client/src/withdraw.rs
I'm a simple developer. I see a "GC" I find the way to get rid of it.
https://www.reddit.com/r/rustjerk/comments/n8b09i/ron_swanson_on_garbage_collection/
> chore: remove Garbage Collection ;)

- fedimint-cli/src/client.rs
- fedimint-client/src/module/mod.rs
- fedimint-load-test-tool/src/common.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
> feat(mint-client): include federation join info in `OOBNotes`

- .github/workflows/ci-nix.yml
M1 MacOS dev shell broke on this branch recently ...
> [0.2] update macos github runners to m1-based `macos-14`

- flake.lock
This reverts commit 209a595639248aa4db4a4ef5887731c448c366bf.
Working around https://github.com/fedimint/fedimint/issues/4217
`nix develop` fails on Mac on `releases/v0.2`. I've replicated failure with 2 other people. Usually either bitcoind or rocksdb fail to compile. @dpc why didn't CI catch this?
> Revert "chore: `nix flake update`"

- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-wallet-client/src/withdraw.rs
*Tells which error is causing failure.
*Gives information of the Contract by giving its `TransactionId` and `ContractId`
fix #4196
> chore: make debug statement more informative

- fedimint-server/src/config/api.rs
Backport of #4178 to `releases/v0.2`.
> [Backport releases/v0.2] chore: during dkg generate peer-ids by peer name ordering

- docker/0.2.1/full-tls-mutinynet/docker-compose.yaml
- docker/0.2.1/gateway-mutinynet/docker-compose.yaml
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-common/src/config.rs
- updates `v0.2.*` docker compose files to package gateway with **0 base msat, 10000 PPM** default fees
- updates tests to include assertions for variable part of globally configured gateway fees
partially addresses #4093 by updating fee defaults in docker packaged gatewayd
> test gateway fees and revise docker defaults

- gateway/ln-gateway/src/state_machine/mod.rs
Fixes: https://github.com/fedimint/fedimint/issues/4279
These constants are leftover and are no longer used.
> chore: remove unused constants

- utils/portalloc/src/lib.rs
See code comment.
To compensate for more ports possibly being taken, increase the retry rate.
> chore(portalloc): increase port allocation time

- modules/fedimint-mint-client/src/lib.rs
Add back `MintClientStateMachines::Restore` in a form that can decode and ready `operation_id`, but otherwise does nothing and is a terminal state.
Fix #4271
> fix: broken db backward compat (MintRestoreStateMachine)

- fedimint-client/src/lib.rs
- modules/fedimint-dummy-client/src/states.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-client/src/receive.rs
- modules/fedimint-mint-client/src/input.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-wallet-client/src/withdraw.rs
This is another step in the direction of making client state machines unaware of their operation id.
> cleanup: remove operation id argument from await_tx_accepted

- fedimint-core/src/api.rs
- fedimint-core/src/query.rs
We remove the timeout since this is the only place were we use such a timeout and therefore its unexpected behaviour, especially in a generally async system. If we want to timeout the download of the client config we should do so explicitly by wrapping either try_download_client_config or FederationInfo::from_invite_code with a timeout instead of somewhere in the middle.
> fix: remove random timeout from download of client config

- .github/workflows/ci-nix.yml
- fedimint-client/src/lib.rs
- fedimint-client/src/sm/executor.rs
- fedimint-core/src/db/mod.rs
- fedimint-server/src/atomic_broadcast/spawner.rs
- fedimint-server/src/config/api.rs
- fedimint-server/src/net/connect.rs
- fedimint-testing/src/gateway.rs
- flake.nix
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-mint-tests/tests/tests.rs
- nix/flakebox.nix
- scripts/tests/test-ci-all.sh
- utils/portalloc/src/lib.rs
This has been on my mind for a long while: Run the tests in the merge queue multiple times to make detecting flakiness easier.
Currently there's some issue surfaced with #4250 , so *temporarily* disable random peer failures.
> chore: anti-flakiness spring offensive

- fedimint-server/src/atomic_broadcast/spawner.rs
https://github.com/fedimint/fedimint/actions/runs/7860754434/job/21454090481?pr=4292
```
fedimint-test-all-ci> 00:08:10 2024-02-11T17:47:35.994448Z ERROR AlephBFT-backup-saver: receiver of alert data to save closed early
fedimint-test-all-ci> 00:08:10 thread 'tokio-runtime-worker' panicked at /build/source/fedimint-server/src/atomic_broadcast/spawner.rs:30:29:
fedimint-test-all-ci> 00:08:10 We own the rx.: ()
fedimint-test-all-ci> 00:08:10 stack backtrace:
fedimint-test-all-ci> 00:08:10    0: rust_begin_unwind
fedimint-test-all-ci> 00:08:10              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
fedimint-test-all-ci> 00:08:10    1: core::panicking::panic_fmt
fedimint-test-all-ci> 00:08:10              at …
```
> fix: possible panic on server shutdown

- .github/workflows/ci-nix.yml
Seems like it consistently times out in the CI:
https://github.com/fedimint/fedimint/actions/runs/7881787581/job/21505971243
It will probably pass if given enough time, and caching will take care of it afterwards.
> chore: give macos-14 runner some time to cross-compile everything

- .github/workflows/ci-nix.yml
This is fixed already on `master`, and produces an empty deb&rpm release artifacts.
> fix(ci): client-pkgs doesn't contain any binaries (v0.2)

- .github/workflows/ci-nix.yml
For these we do want to produce the final binary every time, and their runtime is not as important.
Re #4258
> fix: switch back to `nix build` for release builds on master

- gateway/ln-gateway/tests/integration_tests.rs
Fixes: https://github.com/fedimint/fedimint/issues/4307
Adds explicit checks for the returned status code in the failure case and will panic if the RPC succeeds to fails unexpectedly.
> chore: verify_gateway_rpc_success and verify_gateway_rpc_failure

- scripts/tests/test-ci-all.sh
Unit tests can't use binaries from previous versions, so there's no need to run in backwards-compatibility tests.
> chore: skip rust_unit_tests in backwards-compatibility tests

- .github/workflows/ci-nix.yml
We need them available locally to publish them.
Fix:
https://github.com/fedimint/fedimint/actions/runs/7893582391/job/21542492590
> fix: build containers with normal `nix build`

- .github/workflows/ci-nix.yml
https://github.com/fedimint/fedimint/actions/runs/7904970599/job/21597079557
>  fix(ci): don't use nix-fast-build for x-compiling on macos

- fedimint-core/src/db/mem_impl.rs
After a lot of debuging I discovered that some flakes are due to all the slowness of `MemDatabase`.
On an even ligthly filled test database, coping all the data start taking considerable amount of time (single digit milliseconds), which combined with number of database transactions being opened and commited, can lead to quite long delays in processing in random places (as ordering of locking is somewhat arbitrary).
It's possible that something is also running db transactions in a tight loop somwhere.
For time being using an `RwLock` helps considerably, as all db transactions at least need to start, and we do two copied of the database content there, so being able to do it in parallel, significantly improves the throughput.
Having said that, current implementation is not practical for any …
> fix(memdb): waaay too slow, at least use rwlock

- fedimint-client/src/sm/notifier.rs
Error on send here is normal and expected.
> chore: Notifier::notify improve logging

- modules/fedimint-mint-tests/tests/tests.rs
IMO we should be doing it in every test, so I'm going to show it around.
When you are debugging a tricky problem by analyzing thousands of logs lines of a failing test, having some reference points telling you where the highest level points of test execution happened is very, very useful.
Prefixing them with `###`, it makes jumping around and finding them easier.
> chore: add highest-level logs to sends_ecash_out_of_band

- fedimint-core/src/config.rs
- modules/fedimint-ln-client/src/lib.rs
Fedimint clients would only recognise [vetted gateways meta] field if configured via meta override url. This change allows clients to also read the same meta field on the base meta config. vetted gateways meta value from `meta_override_url` is preferred over value supplied from the base meta.
> fix: recognise vetted gateways configured in base meta

- fedimint-server/src/consensus/debug.rs
- fedimint-server/src/consensus/server.rs
Display txid, which is very useful for debuging.
Be lazy-evaluated which should give better perf when logging is not enabled and avoid extra allocation anyway.
> chore: better consensus item formatting

- devimint/src/util.rs
Seems like LND was taking sweet time initializing, and it's better to wait 10 seconds more than flake out because of it.
https://github.com/fedimint/fedimint/actions/runs/7923824298/job/21634324405
> chore: poll longer in devimint

- fedimint-client/src/sm/executor.rs
- fedimint-client/src/sm/state.rs
- fedimint-client/src/transaction/sm.rs
- fedimint-core/src/core.rs
- fedimint-core/src/db/mem_impl.rs
- fedimint-logging/src/lib.rs
- gateway/ln-gateway/src/lightning/mod.rs
- gateway/ln-gateway/src/state_machine/complete.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- modules/fedimint-dummy-client/src/states.rs
- modules/fedimint-ln-client/src/incoming.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-client/src/receive.rs
- modules/fedimint-ln-common/src/contracts/incoming.rs
- modules/fedimint-ln-common/src/contracts/outgoing.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-mint-client/src/input.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/oob.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-wallet-client/src/deposit.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-client/src/withdraw.rs
On top of #4227 
Make client side state machines go brrrr:
* no busy looping/polling anything (good for phone bateries)
* no canceling anything
* parallel state transitions
No state machine was harmed during the rewrite.
> refactor: improve client executor loop

- devimint/src/external.rs
- devimint/src/util.rs
https://github.com/fedimint/fedimint/actions/runs/7933984731/job/21663951534
suggests that lnd needs even more time.
> fix: wait longer for lnd startup in reconnection test

- flake.nix
This should improve compilation times when switching between branches etc.
You can view the sccache with `sccache --show-stats`:
```
> sccache --show-stats
Compile requests                   2093
Compile requests executed          1501
Cache hits                         1150
Cache hits (Rust)                  1150
Cache misses                        339
Cache misses (Rust)                 339
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                 11
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                 592
Non-compilation calls                 0
Unsupported compiler calls            0 …
```
> feat(flake): use `sccache` in the dev shell

- modules/fedimint-ln-client/src/lib.rs
Calling `.elapsed` will call `SystemTime::now()` under the hood. The semgrep did not catch this sadly.
Looks like `elapsed` is used other places but just for tests and server side stuff
This is present in 0.2.2 so should be backported as well
> fix: remove use of system time in ln client

- devimint/src/federation.rs
Closes: https://github.com/fedimint/fedimint/issues/4225
The code compiles, but I didn't write any tests for it because I'm not sure where to put them. All of the tests in `tests.rs` seem like big integration tests and testing the small `Federation::invite_code_for` method along side the other big integration tests doesn't seem good.
> feat: save invite code for each guardian

- Cargo.lock
- fedimint-core/Cargo.toml
- fedimint-core/src/bitcoin_migration.rs
- fedimint-core/src/lib.rs
- modules/fedimint-wallet-client/Cargo.toml
- modules/fedimint-wallet-client/src/deposit.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-common/Cargo.toml
- modules/fedimint-wallet-common/src/keys.rs
- modules/fedimint-wallet-common/src/lib.rs
- modules/fedimint-wallet-common/src/txoproof.rs
- modules/fedimint-wallet-server/Cargo.toml
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/Cargo.toml
- modules/fedimint-wallet-tests/tests/tests.rs
- recoverytool/Cargo.toml
- recoverytool/src/main.rs
Migrate from [miniscript v9.0.2](https://crates.io/crates/miniscript/9.0.2) to [miniscript v10.0.0](https://crates.io/crates/miniscript/10.0.0) everywhere except one callsite where bitcoin v0.29's `PartiallySignedTransaction` uses miniscript v9's `PsbtExt` trait and provided implementation.
Miniscript v9 relies on bitcoin v0.29, whereas miniscript v10 relies on bitcoin v0.30, which is why we're adding `fedimint-core/src/bitcoin_migration.rs` which contains functions that can convert necessary types between these two versions of the bitcoin crate.
> chore: migrate to miniscript v10

- fedimint-core/src/api.rs
For the module I am working on, I have the need to submit an authenticated API request to a single peer. In this context, the client is authenticated with a single guardian, but should not have authenticated access to other guardians. For my module, this instructs the guardian to submit a consensus item.
Right now I don't think this is possible to do since `request_with_strategy` by default contacts all guardians.
> chore: add single peer request strategy

- devimint/src/tests.rs
The failing assertion compare max latency vs p90. But after improvements to client sm executor all the averages, mins, median and p90 went down.
I don't see why some rare max timing would neccessarily need to be within any range compared to p90. Especially given how many tests we're running in parallel on a VM, etc.
> fix: flaky latency test

- Cargo.lock
- fedimint-core/Cargo.toml
- fedimint-core/src/db/mem_impl.rs
currently memdb clones all the database items on each begin_transaction, this is really slow for even slightly large database.
this uses immutable data structures for memdb, so clone in begin_transaction is O(1)
> feat: immutable data structure for memdb

- .github/templates/failed-backport-issue.md
- .github/workflows/backport.yml
Closes https://github.com/fedimint/fedimint/issues/4362
This workflow has been tricky to test on forks. Since these are low risk changes, I'd like to merge and verify against future failed backports. I'll quickly revert if there are issues after merging.
> chore: include PR titles in failed backport issues

- .config/semgrep.yaml
- fedimint-core/src/task.rs
- fedimint-testing/src/btc/mock.rs
- fedimint-testing/src/btc/real.rs
- fedimint-testing/src/gateway.rs
The function fedimint_core::task::sleep_in_test should be used over fedimint_core::task::sleep in tests so the duration of the sleep and a comment describing the reason for sleeping can be logged.
Closes: https://github.com/fedimint/fedimint/issues/1792
> chore: use sleep_in_test over sleep in tests

- gateway/ln-gateway/src/state_machine/mod.rs
Since we removed the client extension traits we no longer need to use the inner pattern here.
> refactor: remove register_with_federation_inner

- gateway/cli/src/main.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- gateway/ln-gateway/tests/integration_tests.rs
- adds coverage for short channel id assignments when federations are connected to gateway
- shows  each scid assignment info for each connected federation
- shows all scid assignments in gateway info. This includes scids assigned to federations that have since been removed
- sets const `INITIAL_SCID = 0` because we always increment the scid value before assignment.
> test: gateway short channel id assignments

- scripts/tests/backwards-compatibility-test.sh
We only really need to test that current version works with every other component in every past version.
While it's possible there are bugs that only happen in certain combinations of old versions on multiple components, it's extremely unlikely, and worth the time it takes to test it.
So:
```
v0.2.1       v0.2.1          current          0
v0.2.1       current         v0.2.1           0
v0.2.1       current         current          0
current      v0.2.1          v0.2.1           0
current      v0.2.1          current          0
current      current         v0.2.1           0
```
becomes:
```
v0.2.1       current         current          0
current      v0.2.1          current          0
current      current         v0.2.1           0
```
and with even more versions the complexity changes …
>  chore(backward-compat-test): test each version of every component once 

- devimint/src/util.rs
I find logs of commands used by devimint as useful (if not more) than the logs of devimint itself.
> chore(devimint): print out stderr of commands we're running

- devimint/src/tests.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/init.rs
- fedimint-client/src/module/init/recovery.rs
- fedimint-core/src/module/version.rs
- fedimint-core/src/query.rs
I've noticed recovery tests are still super slow and investigating why that is, found bunch of bugs. This was the first time we are actually using api version discovery for anything, so it's unsurpring that I've found bunch of (my own) bugs. :D
> fix: slow client recovery in tests

- modules/fedimint-mint-client/src/lib.rs
> fix(mint-client): reissuing eternal notes doesn't block

- fedimint-core/src/api.rs
The option is now available to generate an InviteCode with max_evil + 1 number of guardian urls in case some guardians go offline.
Closes: https://github.com/fedimint/fedimint/issues/4306
> feat: generate essential num guardians InviteCode

- gateway/ln-gateway/tests/integration_tests.rs
- scripts/tests/backend-test.sh
> fix: run real fedimint-ln-gateway tests

- .github/workflows/ci-backwards-compatibility.yml
- .github/workflows/ci-nix.yml
Stuff like this: https://github.com/fedimint/fedimint/actions/runs/8011581330/job/21885131838 , hangs on downloading something and must not be doing any progress.
It's better for `nix` to timeout and retry connection.
> chore: prevent hanging connnections failing builds

- .github/workflows/ci-backwards-compatibility.yml
- devimint/src/cli.rs
- devimint/src/devfed.rs
- devimint/src/federation.rs
- devimint/src/tests.rs
- devimint/src/util.rs
- devimint/src/vars.rs
- fedimint-core/src/api.rs
- fedimint-testing/src/federation.rs
- fedimint-testing/src/fixtures.rs
- scripts/tests/backend-test.sh
- scripts/tests/test-ci-all.sh
Closes https://github.com/fedimint/fedimint/issues/4171
Inspired by https://github.com/fedimint/fedimint/pull/4173 and https://github.com/fedimint/fedimint/pull/4198
Introduces the ability to run rust and devimint tests with a parameterized number of peers offline, defaulting to a 3/4 setup.
Running all tests with a degraded federation increases the time for CI to finish by a material amount, so we should consider if running all tests degraded is worth the additional overhead.
- Build on Linux tests step: before ~10 minutes ([CI](https://github.com/fedimint/fedimint/actions/runs/7895859707/job/21548890873?pr=4323#step:9:1)), degraded ~19 minutes ([CI](https://github.com/fedimint/fedimint/actions/runs/7909623387/job/21590963278?pr=4247#step:9:1))
- Back-compat: before ~45 minutes …
> Degraded federations for devimint and rust tests

- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-core/src/api.rs
- fedimint-core/src/config.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/client.rs
Many methods were never used, the invite_code field was never read. Every time this struct was created from an invite code the caller just wanted to obtain the client config.
> Remove FederationInfo

- .config/semgrep.yaml
- modules/fedimint-ln-client/src/lib.rs
Followup to prevent further bugs similar to https://github.com/fedimint/fedimint/pull/4356
This rule catches usages of method calls to `.elapsed()`. I did an audit of all public functions for `std::time::SystemTime` and this is the only one that calls `std::time::SystemTime::now`.
Semgrep supports typed metavariables ([docs](https://semgrep.dev/docs/writing-rules/pattern-syntax/#using-typed-metavariables)), which would be much better than catching any usage of `.elapsed()`, however after testing locally it doesn't catch the usage in the associated PR. Rust support is beta and I believe it's limited in its ability to parse types from struct fields. We're currently using semgrep v1.37.0, so I installed the latest version and that doesn't work either.
Semgrep PR introducing typed …
> Add semgrep rule for `.elapsed()`

- .config/semgrep.yaml
- devimint/src/tests.rs
- fedimint-testing/src/btc/real.rs
- fedimint-testing/src/ln/real.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-mint-tests/tests/tests.rs
- modules/fedimint-wallet-tests/tests/tests.rs
If .semgrepignore is not present, semgrep uses a default .semgrepignore file. The defaults excluded some tests which is not the desired outcome.
Add a blank .semgrepignore file to indicate that nothing additional to .gitignore should be ignored by semgrep.
Also, add a second pattern to ban-direct-sleep-in-tests rule to find the sleep function when the fully qualified function name is present.
> chore: add blank .semgrepignore & fix findings

- fedimint-wasm-tests/src/lib.rs
Closes #4393
I suspect this happened because an http error was returned and it tried to parse the error string as an `InviteCode`
> fix: Handle http errors in wasm test

- .envrc
Gets rid of this warning I introduced when running direnv on local from the replit support PR, sorry @dpc :
```
> cd fedimint
nix-direnv: error current version v2.3.0 is older than the desired version v3.0.4
:bulb: Run 'just' for a list of available 'just ...' helper recipes
```
> fix: check if in repl before running replit direnv check

- Cargo.lock
- devimint/Cargo.toml
- devimint/src/federation.rs
- devimint/src/vars.rs
allow you to run latency tests twice on same test dir for example
> feat: allow multiple devimint clients with the same name

- fedimint-testing/src/federation.rs
- modules/fedimint-dummy-tests/tests/tests.rs
- modules/fedimint-mint-tests/tests/tests.rs
Fixes #3988. Note that using `MemDatabase` still leads to deadlocks, but that's not production-ready anyway, so we can track it independently.
> chore(mint-client): test parallel spends and reissuances

- fedimint-core/src/config.rs
For a long time we allowed plain strings in meta fields, i.e. without some ugly additional JSON quotation, but removed that bug/feature. Turns out that's a backwards incompatible change.
Related to #3648, #3699, #4432 and #4434.
> fix: make `String`s in meta backwards compatible

- scripts/_common.sh
It's not obvious which versions map to which binaries when looking through the devimint logs.
```
```
This will make it obvious at a glance what version each binary maps to.
```
```
> chore: include binary name in test version string

- docker/0.2.1/full-tls-mutinynet/docker-compose.yaml
The data_path where xmpp archives messages in our prosody config writer is writing to /var/lib/prosody instead of the prosody_datadir volume that gets accessed by the xmpp service
> fix: persist xmpp message archives

- Cargo.lock
- devimint/Cargo.toml
- devimint/src/tests.rs
- fedimint-cli/src/lib.rs
- fedimint-core/src/admin_client.rs
- fedimint-core/src/api.rs
- fedimint-core/src/endpoint_constants.rs
- fedimint-server/Cargo.toml
- fedimint-server/src/config/io.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/net/api.rs
- nix/flakebox.nix
- scripts/tests/guardian-backup.sh
- scripts/tests/test-ci-all.sh
Fixes #4039 on the `fedimintd` side, also needs a UI feature. 
@EthnTuttle, @Kodylow how hard would that be to integrate on the frontend side? [It seems possible to download a file "from memory", although in the typical web tech hacky way :see_no_evil: ](https://stackoverflow.com/questions/3665115/how-to-create-a-file-in-memory-for-user-to-download-but-not-through-server)
For manual testing you can run
```bash
fedimint-cli --our-id 0 --password pass admin guardian-config-backup | jq -r .tar_archive_bytes | xxd -r -p  > backup.tar
```
it decodes the returned hex and writes it to `backup.tar`. Comparing the files they look reasonably similar (some differences due to non-pretty encoding):
```
$ ls -la target/devimint/fedimintd-0/
total 200
drwxr-xr-x  3 user users   4096 Feb 25 21:19 . …
```
> Allow downloading guardian config

- fedimint-client/src/db.rs
Re #4444
I mentioned it before, but it was never followed through.
Sometimes applications using client will want to store some data, in client database. Potentially because it's already there and Fedimint provides all the infrastructure to use it, but also due to atomic transaction requirements.
We should wrap it up in a nicer interface in the future, but for now, just officially allocate it and document it in the code.
Not going to lie - while the exact range is somewhat arbitrary, and probably a smaller one would be enough, Fedi app has already started using this range, so it will make our life easier if we reserve it, and we will internally migrate to use only designated prefix when Fedimint has proper support for it, and we have some time to implement a migration.
While I think a …
> chore: allocate client db prefix range for external use

- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
allows client to decide whether they want to support recover without backup snapshot or not
> chore: allow download backup manually for recovery

- fedimint-client/src/backup.rs
- fedimint-client/src/backup/tests.rs
- fedimint-client/src/db.rs
- fedimint-core/src/core/backup.rs
- fedimint-core/src/encoding/mod.rs
- fedimint-server/src/net/api.rs
* Add server side limit per backup: 128KiB.
* Add client side limit per module-backup: 32KiB.
* Check the server limit on the client as well.
* Store and use old versions of each module backup if the current version is too large.
>  chore: cap maximum backup size at 128KiB, 32KiB per module

- .github/workflows/ci-backwards-compatibility.yml
- .github/workflows/ci-nix.yml
We'll occasionally see network issues with cachix in CI (again today - [run](https://github.com/fedimint/fedimint/actions/runs/8156982333/job/22295596321), [discord](https://discord.com/channels/990354215060795454/1075857804692295720/1214568693036744744)).
We've previously tried `connect-timeout` (see: https://github.com/fedimint/fedimint/pull/4401), but are still seeing issues. In my local env I've seen similar errors, which have been resolved by adding `stalled-download-timeout = 15` (default: 300s).
https://nixos.org/manual/nix/stable/command-ref/conf-file#conf-stalled-download-timeout
> chore: add stalled-download-timeout nix config in CI

- fedimint-client/src/lib.rs
earlier it returned true if client_recovery_progress_receiver returned empty btreemap
> fix: Client::has_pending_recoveries

- .dockerignore
- .gitignore
- flake.nix
- scripts/_common.sh
- scripts/dev/bootstrap.sh
- scripts/dev/mprocs/run.sh
- scripts/dev/tmuxinator/run.sh
People quite often report problems with constant rebuilds when using VSCode and other IDEs started outside of the dev shell.
These dev shells are using different rust-analyzer and Rust toolchain versions that mututally invalidate each other with dev shell setup.
While there are ways to configure such IDEs to co-exist with dev shell, they require customizing every text editor for every user.
We can't easily control IDEs of everyone, but we have a perfect control of the dev shell. It seems quite easy to just get out of the way, not use the default `./target` and problem mostly solved:
Dev shell users won't really notice the change, mostly.
Shell scripts need to use `CARGO_BUILD_TARGET_DIR`.
IDE users will have a separate ./target and ./target-nix, but it seems much better then suffering …
> chore: move dev shell target to `./target-nix`

- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/lib.rs
In debugging https://github.com/fedimint/fedimint/issues/4350 I realized that the gateway is not independently verifying that the client attached routing fees to the contract. We check if the contract is underfunded, but only against the invoice amount, not invoice amount + gateway fee. 
This PR adds gateway enforcement of fees and adds a test that verifies clients cannot cheat and not pay fees.
> fix: Gateway Enforce Routing Fees

- fedimint-client/src/lib.rs
Using the unknown module in mprocs will cause warning logs which can be unsettling for users. This change updates to a `debug!` log, which suppresses these warning.
See: [discord](https://discord.com/channels/990354215060795454/990354215878688860/1213174844275826728)
```
bash-5.2$ fedimint-cli info
2024-03-01T20:31:51.184211Z  WARN fedimint_client: Detected configuration for unsupported module id: 3, kind: unknown
2024-03-01T20:31:51.186137Z  WARN fedimint_client: Module kind unknown of instance 3 not found in module gens, skipping
{
...
```
> chore: update log level for mprocs

- fedimint-client/src/envs.rs
- fedimint-client/src/lib.rs
- fedimint-core/src/api.rs
- scripts/_common.sh
When working locally I've noticed test failing due to too short api discovery timeout.
Parametrize timeout of api version discovery using env variable. Set it to low value only when testing offline nodes.
> chore: timeouts on version discovery

- fedimint-build/src/lib.rs
Mathz are hard.
Hey, at least it's not off by 1.
> fix: wrong git version hash calculated if source dirty

- flake.nix
- nix/flakebox.nix
We started getting slow test and timeouts in the CI:
https://github.com/fedimint/fedimint/actions/runs/8198894922/job/22423145415
caused by #4476.
Turns out there are other tests just degraded federation tests that run with degraded federations.
Generally in dev shell, tests and CI, we can just default to 10 seconds timeout, should be enough even under heavy load.
> fix: decrease api discovery timeouts in dev shell and tests

- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/init/recovery.rs
- fedimint-client/src/module/mod.rs
- fedimint-client/src/sm/executor.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-testing/src/federation.rs
- fedimint-testing/src/gateway.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
On top of #4482 
Use two levels of `Arc` instead. While at it, rename and document things
better.
>  refactor(client): remove manual client arc counting 

- fedimint-client/src/module/init/recovery.rs
Fundamentally we can't rely on database count to detect when client executors (state machines and recoveries) finished, because external user might hold some references too.
Also, we must not be dropping `inner : Arc<Client>` before we ensure executors stopped, because something running in them might still require that `Arc<Client>` is alive and weak references to them can be upgraded.
Instead use the old and (somewhat) trusted TaskGroup to do the job.
> chore: client shutdown on handle drop incorrect

- .github/workflows/ci-nix.yml
- flake.lock
- flake.nix
- nix/flakebox.nix
- scripts/tests/test-ci-all.sh
- scripts/tests/wasm-test.sh
This required:
* reachitecting flakebox target vs toolchain handling
* fixing wasm-test.sh to stop invalidating ./target
* bunch of nix glue to stich native vs wasm32-unknown ./targets together
* continuously ignoring the question is it even worth the time
Unfortunately after tackling all the scripts & Nix issues, it turned out that wasm-tests (headless firefox?) just doesn't work when being run in GNU `parallel` or `xargs -P`, and debugging it seems like lots of work.
So we'll still run wasm-test separately, but at least it will now re-use build artifacts with the main build, so it should still be faster. And in the future we can try again.
> include wasm-test.sh in test-ci-all (almost)

- fedimint-cli/src/client.rs
- fedimint-client/src/lib.rs
- fedimint-core/src/api.rs
- fedimint-core/src/query.rs
- modules/fedimint-ln-common/src/api.rs
Use a task_group.
On top of ... too many PRs, because merge conflicts and CI being stuck ATM. Can rebase when the dust clears.
>  fix: api discovery task not being cancellable 

- fedimint-cli/src/client.rs
- fedimint-client/src/lib.rs
- fedimint-core/src/api.rs
- fedimint-core/src/query.rs
- modules/fedimint-ln-common/src/api.rs
This blocking of client on a first start is slowing everything down and creating a lot of problems. A simple solution would be to go fast and optimistic on the first start.
Subsequent runs will happen in the background, so then we can do slow, but more precise negotiation.
> chore(client): on first start, get api version from half of clients

- devimint/src/federation.rs
- devimint/src/tests.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/mod.rs
- fedimint-core/src/config.rs
- fedimint-testing/src/federation.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-ln-client/src/lib.rs
The name federation_id() makes it sound like it is just retrieving the id, however it is actually calculating a hash and can take a mild amount of cpu power. Renaming this to calculate_federation_id() implies that there is some work being done and the user should instantiate it as a variable to not duplicate that work.
Found a place where this was happening in the codebase already. We did this in several places in Mutiny too.
> feat: Rename federation_id() to calculate_federation_id()

- fedimint-core/src/tiered.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
Resolves outstanding TODO in `test_detect_double_spends`.
> test: get denomination from mint server config

- flake.nix
On top of #4524 to avoid merge conflict and integrate with `.shrc.local` (you could force TMPDIR there)
>  chore: workaround too long TMPDIR harder 

- fedimint-cli/src/lib.rs
- fedimint-client/src/db.rs
- fedimint-client/src/lib.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-testing/src/federation.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/client.rs
We can generate invite codes from the client config, the separate invite code in the db is a remnant from a time when we had to request an invite code from the guardian.
> cleanup: remove invite code from client db

- Cargo.lock
- fedimint-server/Cargo.toml
- fedimint-server/src/lib.rs
- fedimintd/Cargo.toml
> chore: update jsonrpsee to 0.22.1

- gateway/ln-gateway/tests/integration_tests.rs
I've run the test a bunch of times locally and it doesn't fail for me and the linked [GitHub issue](https://github.com/fedimint/fedimint/issues/4293) is closed. So I think it makes sense to re-enable.
> chore: remove ignore for test_gateway_client_pay_unpayable_invoice

- justfile.fedimint.just
- scripts/dev/devimint-env.sh
Copy&paste in `mprocs` is always annoying. I started improving tmux working in nested tmux, but then it occured to me, that I actually don't want devimint starting either.
All I really want is a shell inside devimint environment. I can `tail` logs myself if I need to (I usually don't). And that's what `just devimint-env` is.
Please give it a try locally before approving. High chance there are some details that can fail on different shells/systems, even if I tried to keep it *really* simple.
> chore(dev-env): `just devimint-env`

- devimint/src/tests.rs
- scripts/tests/cannot-replay-tx.sh
- scripts/tests/test-ci-all.sh
Working towards https://github.com/fedimint/fedimint/issues/3234
Ports `cannot_replay_transactions` from the legacy integration tests.
https://github.com/fedimint/fedimint/blob/1132d742c2357fd70a0c3691636f80637edc0adb/integrationtests/tests/tests.rs#L348
> Port replay protection test

- flake.nix
I don't know how fuzzing worked for others, but I had to add `clang` to the dev env, otherwise `honggfuzz` would fail to compile with
```
make: clang: No such file or directory
```
Follow-up to  #4494
> fix: make clang available in fuzz shell

- fedimint-core/src/encoding/btc.rs
- fedimint-core/src/encoding/mod.rs
- fedimint-core/src/macros.rs
- fedimint-core/src/tiered_multi.rs
- fedimint-derive/src/lib.rs
- fuzz/src/lib.rs
This is based on the same API/traits from rust-bitcoin:
https://docs.rs/bitcoin/latest/bitcoin/consensus/encode/trait.Decodable.html#method.consensus_decode_from_finite_reader
Fix #4395
On top of #287 .
A problem was incidentally discovered when fuzzing the whole thing and the fix already has a merge conflict, so is tagging along.
> chore: add DoS protection against infinite reader on decoding 

- .github/workflows/extra-docker-images.yml
- docker/0.2.1/mutinynet-bitcoind-docker/Dockerfile
Followup to https://github.com/fedimint/fedimint/pull/4490
Closes https://github.com/fedimint/fedimint/issues/4243
The symlink works but we were missing the Dockerfile. Also updates the context path for prosody.
```
ERROR: failed to solve: failed to read dockerfile: open docker/latest/mutinynet-bitcoind-docker/Dockerfile: no such file or directory
```
https://github.com/fedimint/fedimint/actions/runs/8299123739/job/22714103048
> Followup - Fix CI on master

- modules/fedimint-mint-tests/tests/tests.rs
We're observing a higher failure rate causing CI bottlenecks. Disabling for now.
https://github.com/fedimint/fedimint/issues/4508#issuecomment-2000407244
> chore: disable flaky ecash_oob_highly_parallel

- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-ln-server/src/metrics.rs
Use `direction` label to combine contract funding metrics.
Drop the counters, histograms already track `<metric>_count`
anyway.
Shorten the names.
Add human-readable descriptions.
>  refactor(metrics): combined and polish existing ln module metrics 

- nix/flakebox.nix
- scripts/tests/test-ci-all.sh
`[ -t 1 ]` is true when running in terminal + a flag to disable it from Nix script.
> fix(ci): test-ci-all running `parallel` with `--eta`

- scripts/dev/devimint-env.sh
Trust me, you're going to have a great time if you use `just devimint-env` to test stuff, and sometimes you'll be running previous version because it ignored compilation error.
This change denies anyone that fun. Sorry.
> fix(devimint-env): `set -euo pipefail` missing

- fedimint-core/src/endpoint_constants.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/net/api.rs
Closed https://github.com/fedimint/fedimint/pull/4559 in favor of this to clean force pushes / git history, just adds federation_id endpoint to not affect global client config backwards compat but still be able to get it from the guardian ui.
> feat: federation_id guardian endpoint

- devimint/src/tests.rs
Reissuing is so fast now, that it's hard to bench any potential improvements. Issue more notes, to make it work harder.
In my tests, when using `ci` build profile:
Before:
LATENCY REISSUE: min: 0.6s, avg: 0.7s, median: 0.6s, p90: 0.7s, max: 0.7s, sum: 19.5s
Now:
LATENCY REISSUE: min: 1.3s, avg: 1.4s, median: 1.4s, p90: 1.5s, max: 1.5s, sum: 42.4s
> chore(latency-tests): reissue more notes

- devimint/src/cli.rs
- devimint/src/devfed.rs
- devimint/src/external.rs
- devimint/src/federation.rs
- devimint/src/util.rs
- fedimint-client/src/sm/executor.rs
Mostly deviming, downgrading level and unifying certain things.
> chore: improve logging

- fedimint-core/src/api.rs
We can match on this error and show good error messages on the client.
> feat: allow access to FederationError

- devimint/src/tests.rs
- devimint/src/util.rs
@elsirion had some good non-blocking feedback to improve the API for interacting with `fedimint-cli` errors in devimint.
https://github.com/fedimint/fedimint/pull/4563#discussion_r1527440037
> chore(devimint): add assert_error function

- fedimint-client/src/lib.rs
- fedimint-client/src/sm/executor.rs
- fedimint-core/src/task.rs
- fedimint-metrics/src/lib.rs
- fedimint-server/src/config/api.rs
- fedimint-server/src/consensus/server.rs
- fedimint-server/src/multiplexed.rs
- fedimint-server/src/net/peers.rs
- fedimint-server/src/net/peers_reliable.rs
- fedimint-testing/src/federation.rs
- fedimint-testing/src/gateway.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/lnd.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- modules/fedimint-wallet-server/src/lib.rs
fixes https://github.com/fedimint/fedimint/issues/4493
command used for replace:
rust-analyzer ssr '$tg.spawn($n, $f).await ==>> $tg.spawn($n, $f)'
> chore: remove async from TaskGroup::spawn

- docs/dev-env.md
Ran into this footgun trying to get a dev environment set up. Since it's in the bootstrap script it makes sense to include it here as well. Closes #2149.
> docs: add section on cachix to dev-env docs

- .config/nextest.toml
We recently introduced exporting `CARGO_PROFILE="dev"` when sourcing `scripts/_common.sh` (see: https://github.com/fedimint/fedimint/blob/f001570/scripts/_common.sh#L14). We need to define a `dev` profile for nextest or `just test-ci-all` fails locally with
```bash
nix@lenovo-m75q-ubuntu:~/fedimint$ just test-ci-all
./scripts/tests/test-ci-all.sh
Pre-building workspace...
Finished dev [unoptimized + debuginfo] target(s) in 0.26s
Pre-building tests...
error: profile `dev not found (known profiles: ci, default, default-miri)`
error: Recipe `test-ci-all` failed on line 19 with exit code 96
```
> fix: define nextest `dev` profile

- devimint/src/cli.rs
- devimint/src/external.rs
- devimint/src/federation.rs
- fedimint-cli/src/client.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/sm/executor.rs
- fedimint-core/src/db/mod.rs
- fedimint-core/src/task.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-logging/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
In a default (`info`) logging level `fedimint-cli` should only print most important and infrequent messages, and not be soo chatty.
> chore(client): too chatty

- devimint/src/tests.rs
- fedimint-cli/src/lib.rs
- fedimint-core/src/config.rs
- modules/fedimint-mint-client/src/lib.rs
replaces https://github.com/fedimint/fedimint/pull/4449
Adds dev codes for fedimint-cli to encode/decode to/from json for notes and invite_code
Would it be out of scope to add cashu encoding here? It'd just rename the keys and put the amount in each of the notes then spit out the json
> feat: dev commands to decode and encode notes and invite_code to and from json

- fedimint-cli/src/client.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-tests/tests/tests.rs
This is needed along with #3820 for the lightning address server. Without being able to set the description hash some clients will reject the invoice as invalid and will make all resulting zaps invalid as well.
> feat: Support description hashes for invoices

- Cargo.lock
- modules/fedimint-mint-tests/Cargo.toml
- modules/fedimint-mint-tests/tests/tests.rs
Working towards https://github.com/fedimint/fedimint/issues/3234
Ports `ecash_backup_can_recover_metadata` from the legacy integration tests.
https://github.com/fedimint/fedimint/blob/1132d742c2357fd70a0c3691636f80637edc0adb/integrationtests/tests/tests.rs#L288
> test: port ecash_backup_can_recover_metadata

- fedimint-client/src/db.rs
- fedimint-core/src/db/mod.rs
- fedimint-testing/src/db.rs
I've noticed the `fedimint-cli` keeps printing over and over:
```
2024-03-16T21:45:20.473825Z  INFO db: Migrating DatabaseVersionKeyV0 of ln to DatabaseVersionKey. Version: 1
2024-03-16T21:45:20.473877Z  INFO db: Migrating DatabaseVersionKeyV0 of mint to DatabaseVersionKey. Version: 0
2024-03-16T21:45:20.473899Z  INFO db: Migrating DatabaseVersionKeyV0 of wallet to DatabaseVersionKey. Version:
0
2024-03-16T21:45:20.473917Z  INFO db: Migrating DatabaseVersionKeyV0 of meta to DatabaseVersionKey. Version: 0
2
```
and it seems it actually never completes it, because there is nothing else to migrate and transaction is terminated early, without completing this one migration. In other words - it does some modifications, than never calls the `commit`.
> fix(db): version field migration never completing

- .typos.toml
- devimint/src/cli.rs
- devimint/src/external.rs
- devimint/src/federation.rs
- devimint/src/main.rs
- devimint/src/tests.rs
- fedimint-client/src/lib.rs
- fedimint-core/src/task.rs
- fedimint-core/src/task/jit.rs
Is jitin' cheatin'?
At the beginning of setting up dev federation we start and initialize `bitcoind`, make it create a wallet and mine 101 blocks so it can start sending test on chain funds. This takes a couple of seconds, and we wait for it to complete.
I'm thinking - there's bunch of things we could be initializing while this is happening, we don't have to block *everything* on it. There's just no good way to easily and reliably express this ordering dependency.
That's how the idea of "just in time"-values was born. a `Jit` value is really ... an "eager future". `Jit<T>` will start a tokio task that starts executing immediately, but nothing has to block on it initially. Only calling `jit_val.get().await` will block the caller until the value is ready - which can be much, much later down …
> chore(devimint): speed up start by jiting

- fedimint-client/src/backup.rs
- fedimint-client/src/db.rs
- fedimint-core/src/db/mod.rs
> The client side migrations today assume that the global database is the db namespace where the states are stored. For any use case that needs multi-level nesting of isolated databases (e.g multiple clients within the gateway), this check doesn't make sense anymore and can be removed.
quote from https://github.com/fedimint/fedimint/issues/4616
fixes  https://github.com/fedimint/fedimint/issues/4616
> fix: remove Database::ensure_global calls

- fedimint-client/src/backup.rs
- fedimint-client/src/db.rs
- fedimint-core/src/db/mod.rs
Backport of #4620 to `releases/v0.3`.
> [Backport releases/v0.3] fix: remove Database::ensure_global calls

- fedimint-client/src/lib.rs
allows to spawn tasks that tied to client's lifetime.
> chore: expose the client task group

- devimint/src/federation.rs
Dkg isn't completing within the 15 second timeout, causing flakiness in back-compat tests. @elsirion flagged that this might be caused by the increased parallelism in https://github.com/fedimint/fedimint/issues/4636.
Let's see if giving a longer timeout resolves the flakiness.
> fix: bump devimint dkg timeout

- .github/workflows/docs.yml
- docs/rustdoc-index.md
- justfile.fedimint.just
- nix/flakebox.nix
- scripts/_common.sh
- scripts/dev/build-docs.sh
Re #4622
What we'll publish on docs.fedimint.org:
```
nix build .#nightly.ci.workspaceDocExport
xdg-open ./result/share/doc/index.html
```
Handy local version:
```
just docs
```
> feat(docs): improve documentation generation

- .github/workflows/hourly-run.yml
I think we got flakes under control, but we must remain vigilant.
This workflow will give us 24 run a day, to make sure any new flakes us quickly spotted.
> chore(ci): every hour run tests and report failure to #alerts

- devimint/src/federation.rs
Back-compat has passed 3 times with this bump.
Context for flake: https://github.com/fedimint/fedimint/pull/4641#issuecomment-2010890438
> fix: bump wait_server_status timeout

- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/lib.rs
I want to adjust priority of gateway when a payment fails or succeeds.
Imagine you have two vetted gateways, you can switch to second one when the
payment fails for first gateway.
> feat: add gateway id in lightning operation meta

- .github/workflows/backport.yml
The backport bot successfully created a backport PR that was merged. We then added a new label (`flaky test` [event](https://github.com/fedimint/fedimint/pull/4641#event-12193358389)) that triggered another backport workflow run which failed. This PR checks the label contains "backport" if adding a label triggers the workflow.
References:
- [`github.event.action`](https://stackoverflow.com/questions/61886993/in-github-actions-how-to-get-the-type-of-a-trigger-event-as-a-variable)
- [`github.event.label.name`](https://stackoverflow.com/questions/62325286/run-github-actions-when-pull-requests-have-a-specific-label)
- [`contains`](https://docs.github.com/en/actions/learn-github-actions/expressions)
> fix(backport-ci): check label contains backport

- fedimint-server/Cargo.toml
Had to do this to finish the crates.io release, so the `v0.3.0-rc.0` tag is a bit of a lie :sweat_smile: first half of the creates was released from that commit, second one from this.
> chore: add version to metrics workspace dep

- .github/workflows/hourly-run.yml
We're spamming the alerts channel with false negatives. Lets disable the cron while I debug the failures. I suspect the issue has to do with a lower resource GH runner box taking longer to start services.
> chore(ci): disable hourly workflow

- .github/workflows/hourly-run.yml
- scripts/dev/run-test/fm-run-test
Fix for what caused #4657 
Tested in a different draft PRs (#4668).  We can land, then I should be able manually trigger some runs, see if they look OK, and then we can revert #4657
> fix: hourly run

- scripts/dev/build-docs.sh
The binaries in it have short names and are just getting in a way.
> fix(docs): exclude fedimint-fuzz from rustdoc

- devimint/src/cli.rs
- fedimint-logging/src/lib.rs
remove jsonrpc error level logs during startup
> chore: cleanup devimint logs

- modules/fedimint-ln-client/src/lib.rs
Missed this in #3820 but it'd be nice to have this publicly available so we don't need to scan everytime we try to claim. We can instead give the user the `contract_id`s they need to claim
> feat: Make claim_funded_incoming_contract public

- devimint/src/util.rs
I've added the same code in #4514 but @kernelkind is blocked on this so I pulled this functionality into a separate PR
> feat: add commands to check gatewayd and gateway-cli versions

- scripts/tests/test-ci-all.sh
> chore(text-ci-all): show gnu parallel arguments

- devimint/src/util.rs
Backport of #4678 to `releases/v0.3`.
> [Backport releases/v0.3] feat: add commands to check gatewayd and gateway-cli versions

- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/tests/integration_tests.rs
Previously we had a naively implementation for Gateway authentication. We were using `ValidateRequestHeaderLayer::bearer`, which required a password to be specified during the setup of the webserver. Therefore, in order to support changing the password via the `set_configuration` API, we needed to restart the webserver. This is not ideal because it leads to longer wait times, failed requests, and made our tests flaky https://github.com/fedimint/fedimint/actions/runs/8350129601/job/22855854147
These PR removes `ValidateRequestHeaderLayer::bearer` and introduces middleware functions that intercept the requests to the gateway before they are processed and validate them again the current password that is stored within the gateway. This way, when the password is updated, it is not required to …
> feat: Gateway Authentication using middleware

- devimint/src/util.rs
- gateway/ln-gateway/src/lib.rs
Backport of #4701 to `releases/v0.3`.
> [Backport releases/v0.3] chore(gatewayd): add clap --version

- fedimint-core/src/backup.rs
- fedimint-core/src/encoding/mod.rs
- fedimint-core/src/lib.rs
- fedimint-core/src/module/mod.rs
Please don't be too nit-picky. It's better than nothing.
> chore: add `fedimint-core` high-level docstrings

- fedimint-client/src/db.rs
- modules/fedimint-ln-client/src/db.rs
- modules/fedimint-ln-client/src/receive.rs
I was considering to also rebuild the other, existing migration in the way I built the new one, eliminating the need for the `LightningReceiveStates::SubmittedOfferV0` variant, but that seems like too big of a change to backport and will follow in a separate PR to master only.
Fixes #4700
> Add missing state machine migration

- gateway/ln-gateway/src/lib.rs
I had to enable debug logging just to see this message.
> chore: use info tracing level for htlc stream open failure

- .github/workflows/hourly-run.yml
https://github.com/fedimint/fedimint/actions/runs/8392962219
https://github.com/fedimint/fedimint/actions/runs/8392961815
https://github.com/fedimint/fedimint/actions/runs/8392961211
Seems to be working fine when running manually, let's give it another go.
> chore(ci): re-enable hourly runs

- devimint/src/cli.rs
- devimint/src/devfed.rs
- devimint/src/external.rs
- devimint/src/federation.rs
- devimint/src/gatewayd.rs
- devimint/src/tests.rs
- devimint/src/util.rs
- fedimint-core/src/task/jit.rs
Decided to try `Jit<T>` all the way.
Discovered limitations (`JitCore::get` not being `Send`), and a bug (incorrect handling of `Clone` on `JitCore`).
Implemented `JitFed` which is `DevFed` where every major step is `Jit<T>`, potentially waiting for previous `Jit<T>`s.
Improved some minor other things I've found along the way.
I test everything with `env RUST_LOG=devimint=debug CARGO_PROFILE=ci j devimint-env` (multiple runs). Not exactly scientific, but will have to do for now.
Before:
```
2024-03-22T05:54:08.245424Z DEBUG devimint: Starting exec command elapsed_ms=14992
2024-03-22T05:54:30.448997Z DEBUG devimint: Starting exec command elapsed_ms=13799
2024-03-22T05:54:50.507175Z DEBUG devimint: Starting exec command elapsed_ms=14319
2024-03-22T05:55:10.860077Z DEBUG devimint: Starting …
```
> Faster devimint startup using `Jit<T>`

- fedimint-cli/src/client.rs
- fedimint-client/src/lib.rs
This PR tries to close https://github.com/fedimint/fedimint/issues/3119.
> feat(cli): add list-modules command

- .github/workflows/ci-nix.yml
Seems like sometimes it might take a bit longer:
https://github.com/fedimint/fedimint/actions/runs/8424709083/job/23069227391
> chore(ci): increase containers workflow timeout

- fedimint-dbtool/src/main.rs
- gateway/ln-gateway/src/bin/cln_extension.rs
- recoverytool/src/main.rs
Followup: https://github.com/fedimint/fedimint/pull/4701#discussion_r1536676266
Find all binaries (`vec` isn't a clap cli binary)
```bash
nix@lenovo-m75q-ubuntu:~/fedimint$ rg -A 2 --type-add 'toml:*.toml' --type toml -F '[[bin]]' | rg name
fedimint-cli/Cargo.toml-name = "fedimint-cli"
fedimint-load-test-tool/Cargo.toml-name = "fedimint-load-test-tool"
fedimintd/Cargo.toml-name = "fedimintd"
devimint/Cargo.toml-name = "devimint"
recoverytool/Cargo.toml-name = "recoverytool"
fuzz/Cargo.toml-name = "vec"
gateway/cli/Cargo.toml-name = "gateway-cli"
fedimint-dbtool/Cargo.toml-name = "fedimint-dbtool"
gateway/ln-gateway/Cargo.toml-name = "gatewayd"
gateway/ln-gateway/Cargo.toml-name = "gateway-cln-extension"
```
> chore: add clap version command to all binaries

- devimint/src/external.rs
Hopefully improves https://github.com/fedimint/fedimint/issues/4636
Polling for lnd tls cert and macaroon is flakey in back-compat. Let's bump from 30s to 60s.
```
00:00:31 Error: Polling wait for lnd files failed after 76 retries (timeout: 30s)
00:00:31 
00:00:31 Caused by:
00:00:31     lnd tls cert or lnd macaroon not found
```
https://github.com/fedimint/fedimint/actions/runs/8412860972/job/23034240849#step:6:1741
> chore(devimint): bump lnd polling to 60s

- scripts/tests/test-ci-all.sh
Especially in the backward-compat, the list is long and hard to decipher.
Now:
We could make the output more clear, but I'm just looking for a quick and easy improvement RN.
> chore(ci): print out only failed tests from the joblog

- devimint/src/external.rs
Backport of #4729 to `releases/v0.3`.
> [Backport releases/v0.3] chore(devimint): bump lnd polling to 60s

- .github/actions/prepare/action.yml
Discord [thread](https://discord.com/channels/990354215060795454/1221951795576705127/1221960366053920818)
If we tigger a manual run on `master`, we'll fail tagging with docker since the environment doesn't have a commit sha. This change sets the commit sha to the last commit on the reference branch for manual workflows.
```
Error parsing reference: "fedimint/fedimintd:" is not a valid repository/tag: invalid reference format
```
https://github.com/fedimint/fedimint/actions/runs/8427922160/job/23079408272#step:13:19
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
> fix(ci): use GITHUB_SHA for workflow_dispatch (manual) events

- flake.nix
Seems broken:
https://github.com/fedimint/fedimint/actions/runs/8442492153/job/23124016592
> chore: don't buil `cargo-workspace` on macos

- scripts/tests/test-ci-all.sh
I originally reversed them, thinking "let's start all longest tests first, so the suite can complete fastest", but I think I inadvertently made it so that most heavy tests are running together at the same time creating heavy load, instead of spreading the load appart more.
Let's revert it.
> chore(ci): reverse back-compat matrix loops

- .github/workflows/ci-nix.yml
This is a workaround for matrix jobs "Required" being broken in Github Actions.
After it lands, we should make it "Required".
> chore(ci): introduce explicit status check

- fedimint-cli/src/lib.rs
Working towards https://github.com/fedimint/fedimint/issues/4636
Back-compat was flakey waiting for a block count. Let's bump to 60s.
```
00:00:09 Error: command: fedimint-cli --data-dir=/tmp/nix-shell.iv8sgM/latency_test_ln_send-m4EE/devimint-123920-936/clients/default-0 dev wait-block-count 122
```
https://github.com/fedimint/fedimint/actions/runs/8438702476/job/23111511369#step:6:1664
This may still be an issue when back-compat runs an old client version since this change is in `fedimint-cli`, but this will hopefully prevent flakiness in clients going forward.
> chore(fedimint-cli): increase wait-block-count to 60s

- .typos.toml
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-mint-server/src/metrics.rs
It's often easier to chart things in Prometheus when similiar things
are grouped and use labels.
Keep the previous metrics for backward compat, it doesn't cost much
to keep them around.
>  chore(metrics): labeled grouped promethus metrics for wallet module 

- .typos.toml
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-server/src/metrics.rs
It's often easier to chart things in Prometheus when similiar things
are grouped and use labels.
Keep the previous metrics for backward compat, it doesn't cost much
to keep them around.
>  chore(metrics): labeled grouped prometehus metrics for wallet module 

- devimint/src/cli.rs
- devimint/src/external.rs
- devimint/src/federation.rs
- devimint/src/gatewayd.rs
- devimint/src/tests.rs
- devimint/src/util.rs
Working towards https://github.com/fedimint/fedimint/issues/4636
30s caused a flake polling the gateway balance. Let's bump to 60s.
```
00:00:39 Error: Polling gateway pegin failed after 75 retries (timeout: 30s)
00:00:39 
00:00:39 Caused by:
00:00:39     assertion failed, left: 9999999999 right: 10000000000
```
https://github.com/fedimint/fedimint/actions/runs/8445095915/job/23131758594#step:6:1737
I'm tempted to change the default for poll from 30s to 60s, but I think I'll wait for one more 30s threshold to cause a flake. If the reviewer(s) feels strongly, I can instead change the default in this PR.
Edit:
Changed the default
> chore(devimint): increase default poll timeout from 30s to 60s

- fedimint-core/src/timing.rs
- fedimint-server/src/config/api.rs
Typos wasn't catching these inside nix develop, when I run `typos` in normal shell it catches these.
> fix: typos

- devimint/src/external.rs
Core lightning's [`ConnectRequest`](https://docs.corelightning.org/reference/lightning-connect) appears to block until the peer has been connected to, so this poll shouldn't be necessary.
> chore: remove list peers poll when opening channels in devimint

- flake.nix
`nil` seems to be the prefered option anyway.
> chore: don't install rnix-lsp in our dev shell

- fedimint-client/src/db.rs
- fedimint-core/src/db/mod.rs
This PR makes some small improvements to the logging during the database migrations and also re-introduces a short-circuit mechanism to prevent running the database migrations on newly created databases.
Some of the messages were confusing to deduce what happened based on the output. Also the comments have been changed to clarify certain aspects.
The main improvement is to return `target_db_migration` if we detect that the database is a newly created database. Right now newly created database's always set their database version to 0, which causes them to run all migrations needlessly. Using `target_db_version` is a short-circuit mechanism to make the migrations faster and make the logs more intuitive.
> chore: db migrations logging and shortcircuit improvements

- .github/workflows/backport.yml
The backport bot had a few issues that are resolved by adding single quotes to the PR title when constructing the truncated PR title.
- Failed to open an issue
```
/home/runner/work/_temp/5a908921-0273-46b8-ada3-8b0b85137a8c.sh: command substitution: line 4: syntax error near unexpected token `('
```
https://github.com/fedimint/fedimint/actions/runs/8485661954/job/23250831899
- Attempted to execute command inside backticks
```
/home/runner/work/_temp/8b4842a9-3ce5-4a8f-a706-d08a03b64065.sh: line 3: just: command not found
```
https://github.com/fedimint/fedimint/actions/runs/8395853632/job/22996034143
@dpc thanks for highlighting that the issue bot created a funky short PR title in https://github.com/fedimint/fedimint/issues/4684.
Also increased the short PR title length …
> fix(ci): add single quotes to PR titles

- Cargo.lock
> chore: bump h2

- .github/workflows/backport.yml
Oops :smile: 
```
The expression is not closed. An unescaped ${{ sequence was found, but the closing }} sequence was not found
```
https://github.com/fedimint/fedimint/actions/runs/8546028622/workflow
> fix(ci): add missing bracket

- devimint/src/envs.rs
- devimint/src/util.rs
It's just too much noise, especially when polling on something that will fail for a second or two.
> chore(devimint): don't print stderr of child commands by default

- Cargo.lock
- devimint/Cargo.toml
- devimint/src/federation.rs
- devimint/src/lib.rs
- devimint/src/tests.rs
- devimint/src/version_constants.rs
@m1sterc001guy had some good feedback in https://github.com/fedimint/fedimint/pull/4804#discussion_r1548781274
>Just a thought: do we want to put all of our version constants in a central place (maybe a new file?). Might help with reasoning about which versions have changes between them.
Let's give it a shot.
> refactor(devimint): define version constants

- fedimint-server/src/consensus/server.rs
AlephBFT each round will basically take the first N responses from peers, and ignore other ones.
What can happen in a devimint run is that each `fedimintd` runs the exactly same loop but offseted by some tiny, tiny time, because we start peers in a `for _ in 0..N`.
So a last peer can get ignored consistently for a long while.
Adding any jitter breaks the lockstep immediately, but AFAIK in distributed systems it's a good practice to just use +/- 50% to immediately break any corelations, so we went with `0.5..=1.5`.
> fix: break lockstep between peers in a round by adding jitter

- Cargo.lock
- Cargo.toml
- docs/Cargo.toml
- docs/lib.rs
- docs/rustdoc-index.md
- nix/flakebox.nix
A crate to link our `./docs/` into cargo doc output.
Re #4847
> chore: introduce `fedimint-docs`

- .config/semgrep.yaml
Prevents reintroducing `VersionReq`, which doesn't work with how we compare versions in devimint (see: https://github.com/fedimint/fedimint/pull/4804).
> chore(devimint): add semgrep rule for VersionReq

- devimint/src/tests.rs
- devimint/src/version_constants.rs
- fedimint-cli/src/client.rs
Fixes: https://github.com/fedimint/fedimint/issues/4797
Changes the default of the CLI to use a random gateway if no gateway is specified via `gateway-id` instead of defaulting to an internal invoice.
> fix: use random gateway on cli when gateway not specified

- Cargo.lock
- Cargo.toml
- devimint/Cargo.toml
- docs/Cargo.toml
- fedimint-load-test-tool/Cargo.toml
- fedimint-wasm-tests/Cargo.toml
- fuzz/Cargo.toml
- justfile.fedimint.just
- modules/fedimint-dummy-tests/Cargo.toml
- modules/fedimint-ln-tests/Cargo.toml
- modules/fedimint-mint-tests/Cargo.toml
- modules/fedimint-wallet-tests/Cargo.toml
We had a few packages that weren't updated in https://github.com/fedimint/fedimint/pull/4805. Adding the `--all` flag updates the remaining packages.
```
just release-bump-version "custom 0.4.0-alpha"
```
> chore: bump remaining packages to 0.4.0-alpha

- modules/fedimint-meta-server/src/lib.rs
on clearing the outstanding minority submissions.
See https://github.com/fedimint/fedimint/pull/4772#issuecomment-2033170196
See https://github.com/fedimint/fedimint/pull/4803/files#r1552459723
Seems like never deleting desired values is the simplest correct solution, even if it can potentially waste some storage.
> fix(meta): (mostly harmless) race condition (attempt 2)

- Cargo.toml
Closes https://github.com/fedimint/fedimint/issues/4892
This seems safe to remove after a quick glance at the cargo [docs](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-metadata-table) and CI is green.
> chore: remove version from workspace.metadata

- fedimint-server/src/atomic_broadcast/data_provider.rs
Backport of #4898 to `releases/v0.3`.
> [Backport releases/v0.3] chore(consensus): log items failing max size validation

- fedimint-server/src/atomic_broadcast/data_provider.rs
Backport of #4898 to `releases/v0.2`.
> [Backport releases/v0.2] chore(consensus): log items failing max size validation

- devimint/src/federation.rs
- devimint/src/gatewayd.rs
- devimint/src/tests.rs
- justfile.fedimint.just
- scripts/tests/upgrade-test.sh
Inspired by https://github.com/fedimint/fedimint/pull/4675 and closes https://github.com/fedimint/fedimint/issues/4486.
Use with `just test-upgrades` (defaults to linear upgrade paths for v0.2.1 -> v0.2.2 -> current).
`fedimintd` upgrades fail against `master` but work on `releases/v0.3`, so use the backport PR (https://github.com/fedimint/fedimint/pull/4763) if you verify locally.
Tests upgrades for `fedimintd`, `fedimint-cli`, and `gatewayd`:
- Runs latency tests
- Upgrades path for single binary
- Reruns latency tests
- Continues for all versions passed to script
> feat(devimint): add upgrade tests for all binaries

- fedimint-client/src/module/init.rs
I don't digged why, but without these extra annotations sometimes LSP thinks it's a recursive function and displays fake compilation errors.
> fix: LSP getting spooked

- Cargo.lock
- fedimint-bitcoind/Cargo.toml
- fedimint-bitcoind/src/electrum.rs
- fedimint-core/src/bitcoin_migration.rs
- modules/fedimint-wallet-client/src/deposit.rs
- modules/fedimint-wallet-common/src/txoproof.rs
- modules/fedimint-wallet-server/src/lib.rs
v0.14.1 depends on bitcoin v0.29, whereas v0.18.0 depends on bitcoin v0.30 which requires extra changes
> chore(deps): bump electrum-client from 0.14.1 to 0.18.0

- devimint/src/cli.rs
- devimint/src/devfed.rs
- devimint/src/federation.rs
- scripts/dev/devimint-env.sh
With `Jit` employed, printing when thing start is not as interesting, as they all tend to start at the same time.
> chore(devimint): polish `just devimint-env` output

- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-empty-server/src/lib.rs
- modules/fedimint-meta-server/src/lib.rs
- modules/fedimint-unknown-server/src/lib.rs
In modules that are expected to commonly be used as a template for 3rd party modules.
I attempted to do it using return type changes, but indeeded without https://doc.rust-lang.org/core/ops/trait.Try.html stabilized, it leads to DX degradation and I have no better ideas.
> chore: add a WARNING for `process_consensus_items`

- devimint/src/federation.rs
- devimint/src/util.rs
This PR ports the devimint DKG to use the command line, as it's supposed to do.
Our devimint DKG was implemented using the fedimint client because originally the fedimint-cli didn't support the commands necessary for the setup of a federation. After https://github.com/fedimint/fedimint/pull/4628 now this is possible.
Unfortunately we need to keep compatibility with fedimint-cli v0.2.1 tests so devimint will check if we have this old version installed and then run the setup in the former way. In future we may drop this support.
This also closes https://github.com/fedimint/fedimint/issues/4717
> chore: use fedimint-cli on devimint dkg

- fedimint-core/src/util/broadcaststream.rs
Re #4841
AFAIK this line is not neccessary, and `fedimint-core` always enables `sync` on `tokio`, which this conditional seems to be related to.
> fix: docs.rs compilation error

- fedimint-core/src/module/version.rs
- fedimintd/src/fedimintd.rs
The server-side work for #4584.
Creates an optional subcommand `dev` for fedimintd, similar to fedimint-cli. 
~~Adds a single subcommand to `dev`: `list-versions`.This dumps all API and database versions and exits early.~~ 
Adds two subcommands to `dev`: `list-api-versions` and `list-db-versions`. These dump API and database versions respectively and exit early.
e.g.
```
FM_BITCOIN_RPC_KIND="bitcoind" FM_BITCOIN_RPC_URL="http://localhost:5002" fedimintd dev list-versions
```
<details>
<summary>And here's a sample of the output</summary>
```
{
"core_api_versions": [
{
"major": 0,
"minor": 2
}
],
"modules": [
{
"kind": "ln",
"api_versions": [
{
"major": 0,
"minor": 1
}
],
"database_version": 0
},
{
"kind": "meta",
"api_versions": [
{
"major": 0,
"minor": 0
}
],
"database_version": 0
},
{ …
```
> `fedimintd dev list-versions` subcommand

- devimint/src/federation.rs
- fedimint-api-client/src/api.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-server/src/config/api.rs
An-"admin-enabled" `GlobalApi` should behave for non-admin calls just like non-"admin-enabled" one. For this to happen self-peer-id needs to be tracked separately instead of just narrowing `all_peers` to one (self) peer_id.
In the future this should enable storing self-peer-id in the Client's db, and using such client for both admin and non-admin stuff all the same.
Re #4519
> refactor: GlobalApi should make non-admin calls to all peers

- justfile.fedimint.just
- scripts/tests/upgrade-test.sh
Followup to https://github.com/fedimint/fedimint/pull/4762#issuecomment-2047483947
> Do we even need to backport this? It seems to me as if we could just run any upgrade tests off master, specifying the versions we want to test.
Previously upgrade tests would fail to discover a common api version against master. Instead, we can skip testing against the binaries in the target dir and use only the versions passed to `just test-upgrades`.
> chore: conditionally handle current binaries in upgrade tests

- gateway/cli/src/main.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/tests/integration_tests.rs
This commit adds validation for the routing-fees parameter in the gateway-cli set-configuration command, ensuring it follows the correct format before sending the request to the gateway API.
Previously, setting an invalid routing-fees value could lead to a 500 Internal Server Error on the Gateway side. With this validation, such errors are prevented, and users are informed of the correct format for routing-fees.
Before:
```
bash-5.2$ $FM_GWCLI_LND set-configuration --routing-fees 10
Error: Bad status returned 500 Internal Server Error
bash-5.2$ $FM_GWCLI_LND set-configuration --routing-fees
error: a value is required for '--routing-fees <ROUTING_FEES>' but none was supplied
bash-5.2$ $FM_GWCLI_LND set-configuration --routing-fees 10,100
bash-5.2$ echo $?
0
```
After:
```
bash-5.2$ …
```
> chore: validate routing fees format in the gateway cli

- fedimint-testing/src/ln/mock.rs
- gateway/ln-gateway/proto/gateway_lnrpc.proto
- gateway/ln-gateway/src/bin/cln_extension.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/lnd.rs
This will be used by #4514 to wait for the gateway's lightning node to be synced by polling [`ILnRpcClient::info()`](https://github.com/fedimint/fedimint/blob/f1a9c4927f8a351e4878a86e95861cabf35b59bb/gateway/ln-gateway/src/lightning/mod.rs#L57)
> feat: `GetNodeInfoResponse` contains block height info

- fedimint-api-client/src/api.rs
- gateway/ln-gateway/src/lib.rs
- modules/fedimint-ln-client/src/api.rs
- modules/fedimint-ln-client/src/receive.rs
When we log these errors I'd like to see why we made the failing API call. Alternatively we could also attach it as context to the anyhow error now that I think about it. But maybe having the data in a more structured form is also nice.
> chore: add more context `api::FederationError`

- fedimint-core/src/module/version.rs
- fedimint-server/src/config/mod.rs
- justfile.fedimint.just
- modules/fedimint-dummy-common/src/lib.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-empty-common/src/lib.rs
- modules/fedimint-empty-server/src/lib.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-lnv2-common/src/lib.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-meta-common/src/lib.rs
- modules/fedimint-meta-server/src/lib.rs
- modules/fedimint-mint-common/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-unknown-common/src/lib.rs
- modules/fedimint-unknown-server/src/lib.rs
- modules/fedimint-wallet-common/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
Closes https://github.com/fedimint/fedimint/issues/4960
Upgrade tests fail when upgrading to binaries on `master` since we're using `u32::MAX` for the core consensus version. This PR updates to use the latest core consensus version (2) from `releases/v0.3`.
> chore: remove `u32::MAX` from core consensus versions

- fedimint-api-client/src/api.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/init/recovery.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
I've got a report of slow recovery, so I investigated using `fedimint-cli` to recover in one of test (but otherwise real-like) Fedrations I have available.
I found a serious problem, improved some minor stuff and decided to increase parallism level for significant speedup.
Implementing fetching every session outcome from a single peer would be a significant improvement that could further reduce recovery time.
> chore: fix, improve, speedup recovery

- devimint/src/external.rs
Working towards https://github.com/fedimint/fedimint/issues/4636
Polling `lnd_startup` for only 15s is causing flakiness in CI ([Build on linux](https://github.com/fedimint/fedimint/actions/runs/8682016495/job/23876043177?pr=4776) and [back-compat](https://github.com/fedimint/fedimint/actions/runs/8712142545/job/23897782551?pr=4983)). Let's try the default (60s) timeout.
> chore(devimint): bump poll lnd_startup from 15s to default 60s

- Cargo.lock
- crypto/tpe/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-lnv2-client/Cargo.toml
- modules/fedimint-lnv2-common/Cargo.toml
- modules/fedimint-lnv2-server/Cargo.toml
- modules/fedimint-meta-tests/Cargo.toml
The previous PR to bump remaining versions (https://github.com/fedimint/fedimint/pull/4877) was merged one day before `fedimint-meta-tests` was merged (https://github.com/fedimint/fedimint/pull/4772).
Verify locally with
```
just release-bump-version "custom 0.4.0-alpha"
```
> chore: bump fedimint-meta-tests to 0.4.0-alpha

- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/gateway_module_v2/send_sm.rs
- gateway/ln-gateway/src/lib.rs
- modules/fedimint-lnv2-client/src/lib.rs
The reasoning here is that the gateway is supposed to choose a fee for sending an outgoing payment that is sufficient for high lightning reliability; retrying with higher fees in case of cancellation is unnecessary. 
Furthermore, the fee behaviour is now identical to receiving an incoming payment.
> fix: use default total send fee provided by the gateway

- devimint/src/util.rs
- fedimint-server/src/lib.rs
- fedimint-testing/src/federation.rs
- fedimintd/src/fedimintd.rs
See commits.
Start devimint with:
```
env RUST_LOG=fm=debug just devimint-env
```
`exit` in it, and observe the shutdown time. `tail -f target-nix/devimint/logs/fedimintd-0.log` if you want to see what's happening in `fedimintd`. Another way is to `killall fedimintd` from the outside with `tail -f`.
> chore: make fedimintd and devimint shutdown stuff fast

- gateway/ln-gateway/src/gateway_module_v2/send_sm.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
This fixes two lnv2 tests that had to be deactivated in CI before.
> fix: use private payments rpc when available

- .github/dependabot.yml
Looking at
https://github.com/dependabot/dependabot-core/blob/main/.github/dependabot.yml
I think this part is off.
Would be nice to have a validator for this stuff...
> fix(ci): dependabot still not grouping patch updates

- fedimint-core/src/envs.rs
- fedimint-server/src/consensus/server.rs
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Eg. peg_outs_must_wait_for_available_utxos goes from 33s to 7s.
> chore(ci): speed up tests significantly

- fedimint-testing/src/db.rs
I was investigating something else and happened to need to rewrite it anyway.
> fix: inefficient way to look for file

- .github/dependabot.yml
> chore: disable dependabot updates off lightning

- .cargo/config.toml
- .config/semgrep.yaml
- fedimint-core/src/runtime.rs
- flake.nix
Removes tokio_unstable `Builder`, turns the thread name into a tracing span, still enforces using fedimint_core's spawn and spawn_local.
> fix: remove tokio_unstable

- fedimint-testing/src/federation.rs
- modules/fedimint-dummy-tests/tests/tests.rs
As far as I can tell, it is not currently possible to make an admin client using `FederationTest` in `fedimint-testing`. For modules that are "admin-only" this is necessary for writing tests (I hit it while writing the ROASTR module).
> chore: create admin federation client in fedimint-testing

- .github/templates/failed-backport-issue.md
Filtering issues with a `backport` label helps us quickly see all outstanding failed backports.
> chore(ci): add label to backport issues

- .github/workflows/ci-nix.yml
These are less important, and with current self-hosted runner, we have less parallelism ATM (we might add another one later).
> chore(ci): run cross-compilation steps only core build passed

- scripts/ci/run-in-fs-dir-cache.sh
> fix(ci): self hosted runners don't need fs-dir-cache lock

- scripts/tests/test-ci-all.sh
The load average limit there already protect from too much load on this particular workflow.
>  chore: test-ci-all can run more, otherwise it takes forever 

- .github/workflows/ci-backwards-compatibility.yml
Workers will cache it around, and downloading from github is kind of slow anyway.
> chore: no need to cache `.cargo` anymore

- scripts/tests/test-ci-all.sh
- scripts/tests/upgrade-test.sh
> Do not start new jobs on a given computer unless the number of running processes on the computer is less than max-load. max-load uses the same syntax as --jobs, so 100% for one per CPU is a valid setting. Only difference is 0 which is interpreted as 0.01.
https://www.gnu.org/software/parallel/parallel.html#synopsis
> chore(ci): fix `--load` on `parallel` it doesn't mean percents

- .github/workflows/ci-nix.yml
- .github/workflows/hourly-run.yml
> chore(ci): `--keep-failed` won't work on self-hosted setup

- devimint/src/envs.rs
- devimint/src/tests.rs
We don't care about their latency anymore anyway.
> chore: disable very slow restore latency tests for all versions

- fedimint-client/src/db.rs
- fedimint-client/src/lib.rs
- fedimint-testing/src/db.rs
- modules/fedimint-dummy-client/src/db.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-ln-client/src/db.rs
- modules/fedimint-ln-client/src/lib.rs
Fixes: https://github.com/fedimint/fedimint/issues/4823
Allows us to write "partial" migrations, that migrate states to another state, then migrate it again to the final state that can be parsed as a `DynState`.
> chore: remove DynState in client db migrations

- nix/flakebox.nix
- scripts/tests/test-ci-all.sh
On Linux `chrt` and `iotop` can be used to set the scheduling priority for a process.
We can use it to tactically make all heavy compilation processes have "idle" priority which means they will only execute if nothing else is trying to. AFAIK, this is a global setting and should be respected between cgroups etc.
Since we can now schedule more jobs on a single CI box, such change makes it less likely for time sensitive tasks (tests) to miss some deadline, while still utilizing resources when possible.
> chore: lower scheduling prio of most heavy compilation items

- README.md
Adds just mprocs tutorial links in the README under local dev.
> docs: add mprocs tutorial link

- gateway/ln-gateway/tests/integration_tests.rs
This is the only thing I see consistently flaking in the CI RN.
Re #5001
> chore: disable flaky test_gateway_configuration test

- devimint/src/devfed.rs
- devimint/src/external.rs
- devimint/src/gatewayd.rs
- devimint/src/lib.rs
- devimint/src/tests.rs
- devimint/src/version_constants.rs
- docs/gateway.md
- fedimint-testing/src/ln/mock.rs
- fedimint-testing/src/ln/real.rs
- gateway/cli/src/main.rs
- gateway/ln-gateway/proto/gateway_lnrpc.proto
- gateway/ln-gateway/src/bin/cln_extension.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/cln.rs
- gateway/ln-gateway/src/lightning/lnd.rs
- gateway/ln-gateway/src/lightning/mod.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
Requires #4959
We can use this API to consolidate testing behavior which will help pave the way towards supporting an LDK-based gateway with a lightning node that lives in the gateway process
> feat: add liquidity management API to ILnRpcClient

- scripts/tests/test-ci-all-backcompat.sh
When devimint initialization fails in back compat it's hard to say why.
For now we can land this. Since the logs are not printed out if the test succeeded, a lot of logs here should be OK.
> chore: debug ci flake

- .github/workflows/daily.yml
But so happens that this action was added node20 support few days ago:
https://github.com/rustsec/audit-check/commit/fe0359b3e165e4d83e11ffab7715e56c43cc2d76
> fix(ci): our runner can't use node16

- fedimint-testing/src/federation.rs
- fedimint-testing/src/fixtures.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-dummy-tests/tests/tests.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
- modules/fedimint-mint-tests/tests/tests.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Adds `FederationTestBuilder` which allows us to customize how we build federations in our tests.
> test: FederationTestBuilder for building federations in rust tests

- scripts/_common.sh
- scripts/tests/test-ci-all.sh
`nix build` can potentially hang for a long time, even if the binary was previous built, e.g. because Nix daemon is busy with other stuff and its database is locked.
This could previous potentially cause the test to spend a large part of it's time trying to build binaries.
Instead, prebuild all binaries once before `parallel` is started, and store the resulting path into matching env variable. During tests just take the path out of variable.
> fix(test-ci-all): compile nix binaries of versions outside of test

- Cargo.lock
- fedimint-bitcoind/Cargo.toml
- fedimint-bitcoind/src/esplora.rs
- fedimint-core/src/bitcoin_migration.rs
> chore(deps): bump esplora-client from 0.5.0 to 0.6.0

- devimint/src/devfed.rs
- devimint/src/external.rs
- devimint/src/gatewayd.rs
- devimint/src/tests.rs
- fedimint-api-client/src/api.rs
- fedimint-core/src/task/jit.rs
- gateway/ln-gateway/src/lib.rs
- scripts/tests/test-ci-all.sh
There's a complicated web of initialization dependencies in areas of LN that leads to flakes.
Most importantly `devimint` expects `gateway-cli info` to tell if gatewayd started. This doesn't currently work well, because it will hang for 60s or until gateway gets a channel opened. But then in a "new way" of opening channel doing so can't happen until gateway is ready to respond to API calls.
And then 60s of timeout is as much as other steps in `devimint` are actually polling some stuff. Some then sometimes it works, sometimes it doesn't.
Then `fedimint-cli connect-fed` also has the same behavior of waiting for a route hint from the channel. I don't change that, because it would probably spook many places in the tests that expect the hint to be there.
But generally currently it's all messed …
> chore(devimint): fix most of flakiness in setting up LN gateways

- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/tests/integration_tests.rs
Follow up to https://github.com/fedimint/fedimint/pull/5149
`fetch_lightning_route_hints` currently loops and waits for the route hints to exist. This is not necessary, the client is already adding a route hint for the gateway's lightning node.
> chore: never wait for fetch_lightning_route_hints

- .github/workflows/ci-nix.yml
This was introduced to limit amount of concurrency, and would be fine if not for the fact that in the merge queue we do need to run cross-compilation on MacOS which is slow, and our MQ is running serially. Because of that we want to start cross-compilation jobs sooner than later, so by the time other tests are done cross-compilation on MacOS is done as well.
> chore(ci): start cross-compile jobs earlier

- devimint/src/federation.rs
Fixes https://github.com/fedimint/fedimint/issues/5156
Fixes https://github.com/fedimint/fedimint/issues/4999
We removed `update-gateway-cache` from `fedimint-cli` in https://github.com/fedimint/fedimint/pull/4919. `v0.3.0` includes `update-gateway-cache` (see: https://github.com/fedimint/fedimint/blob/v0.3.0/fedimint-cli/src/client.rs#L126) and doesn't update the cache using `list-gateways`, so we need to handle this case explicitly in back-compat and upgrade tests.
Reviewers can verify locally using
```
just test-compatibility v0.3.0
```
and
```
just test-upgrades "v0.3.0 current"
```
> fix: use update-gateway-cache for v0.3.0

- scripts/_common.sh
- scripts/tests/backend-test.sh
- scripts/tests/test-ci-all.sh
It has a bit long runtime, and each module can just run in parallel to bring it down.
> chore: split backend test for bitcoind

- gateway/ln-gateway/proto/gateway_lnrpc.proto
- gateway/ln-gateway/src/bin/cln_extension.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/lnd.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-lnv2-client/src/lib.rs
- Adds the ability to set a description or description hash for `create_invoice` which is used in LNv2
- Implements `create_invoice` for CLN
This PR is unfortunately difficult to test. That is because `create_invoice` is only used for LNv2 currently add there aren't currently tests that exercise paying into a Fedimint from an external Lightning node. Adding support for generating the invoice for LNv1 is a longer discussion, since we would need to figure out what backwards compatibility support we want (IMO we might want to do this in the future depending on when LNv2 ships). Adding testing support for paying fedimints from an external wallet using LNv2 requires adding CLI commands, which is out of scope for this PR.
Since this only affect LNv2 currently, I hope we can merge and iterate if …
> feat: LNv2 Description Hashes and CLN Create Invoice

- fedimint-client/src/lib.rs
- fedimint-client/src/module/mod.rs
- fedimint-client/src/transaction/builder.rs
- fedimint-core/src/lib.rs
- fedimint-load-test-tool/src/common.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
This refactor gives modules more freedom when finalising a transaction as inputs and outputs don't have to be created separately anymore. This change is in preparation for ecash-ng.
> refactor: create_final_inputs_and_outputs

- modules/fedimint-mint-tests/tests/tests.rs
I've seen a weird fail that might, or might have not been a timeout here. Seems we standardize on 60s in other places, so lets increase it here as well.
> fix(ci): increase the poll time in sends_ecash_out_of_band_cancel

- fedimint-cli/src/lib.rs
- fedimint-dbtool/src/main.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-testing/src/gateway.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-client/src/receive.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
Working towards: https://github.com/fedimint/fedimint/issues/5168
Gets rid of the ugly hack we used of removing the gateway's clients during the tests.
> chore: Mock RPCs between Client -> Gateway

- devimint/src/federation.rs
- devimint/src/tests.rs
> fix(recoverytest): wait for next session before scanning session outcomes for pegins

- nix/modules/fedimintd.nix
* Ability to source the bitcoin rpc secret from a file (useful if you're using nix-bitcoin, or agenix, etc.)
* Ability to set user & group for the daemon.
* Cleanup.
Corresponding configuration.nix change (when using `nix-bitcoin`):
```
+  users.extraUsers.fedimintd-somefed.extraGroups = [ "bitcoinrpc-public" ];
services.fedimintd."somefed" = {
enable = true;
package = pkgs.fedimintd;
+    extraEnvironment = {
+      "RUST_LOG" = "info";
+      "RUST_BACKTRACE" = "1";
+    };
api = {
address = "wss://${fmApiFqdn}/ws/";
bind = "127.0.0.1";
@@ -133,7 +126,8 @@ in
bitcoin = {
network = "bitcoin";
rpc = {
-        address = "http://bitcoin:${btcPass}@127.0.0.1:8332";
+        address = "http://bitcoin@127.0.0.1:8332";
+        secretFile = …
```
> chore(nix-module): improvements

- devimint/src/tests.rs
Should help debug https://github.com/fedimint/fedimint/pull/5184
~After multiple attempts I couldn't reproduce the flake in the self-hosted runner, so let's add these logs for the next time it happens elsewhere in CI.~
Scratch that, right as I was throwing in the towel we have a flake!
---
Update: Investigating the flake showed that the epochs method returned only 3 descriptors with one descriptor different than the UTXOs method. On successful runs, the epochs method returns 4 descriptors. This is likely due to the looping approach that's removed in https://github.com/fedimint/fedimint/pull/5184 (see:  https://github.com/fedimint/fedimint/pull/5184#discussion_r1586305505), which suggests the different descriptor is a spent output instead of the change output.
Still a mystery how this …
> chore(devimint): log descriptors in recoverytool tests

- fedimint-core/src/endpoint_constants.rs
- fedimint-server/src/consensus/server.rs
- fedimint-server/src/net/api.rs
The intended shutdown procedure for this is that all guardians select a session to shutdown, let’s say via a group chat, that is sufficiently long in the future for all of them to set the index to shutdown at, so let’s say something like 15minutes. Then, when the guardians have shut down, every guardian needs to check that it has shut down at the at the intended index and confirm with each other via chat; this may not be the case of a guardian is lagging behind sufficiently. If not, retry. Only if successful for every guardian we can initialise the upgrade.
> feat: enable shutdown after certain session index for a coordinated consensus upgrade

- fedimint-core/src/config.rs
Necessary when upgrading to bitcoin v0.31 since `Error::InvalidLength` is replaced with [`hex_conservative::error::InvalidLengthError`](https://docs.rs/hex-conservative/0.2.0/hex_conservative/error/struct.InvalidLengthError.html) which is marked as `#[non_exhaustive]` and therefore cannot be constructed directly outside of that crate.
This change shouldn't affect behavior, since the implementation we're switching to ([here](https://docs.rs/bitcoin_hashes/0.12.0/src/bitcoin_hashes/hex.rs.html#163-202)) essentially does what we were previously doing here.
> chore: simplify FederationId and FederationIdPrefix string decoding

- fedimint-server/src/config/api.rs
- fedimint-server/src/lib.rs
- fedimint-server/src/net/api.rs
The verification hashes are used in the API to confirm the result of the DKG. Though all hashes are just derived from the config, and we could simply just compare the consensus config hash, the verification hashes are purposefully different for each peer such that their manual verification by the guardians via the UI is more robust.
After the dkg is done the verification hashes are not required anymore, the server checks config equality on startup via the SERVER_CONFIG_CONSENSUS_HASH_ENDPOINT.
> cleanup: simplify verification hashes

- Cargo.lock
- Cargo.toml
- modules/fedimint-lnv2-common/Cargo.toml
- modules/fedimint-lnv2-common/src/config.rs
This is safe because encrypted preimage can only be decrypted in their respective module as the bls signatures internal to the ciphertext which authenticate the encryption commit to different messages hashes.
> feat: enable migration of ln config to lnv2 config
