fedimint/fedimint

minimint-api/src/db/mod.rs

This additional trait bound should allow usage of `find_by_prefix` with muti-threaded async executors.

minimint-api: make `PrefixIter` `Send`

---

modules/minimint-wallet/src/lib.rs

A trivial fix to get in a first commit.
Taking a closer look at the error handling around `bitcoind` soon. Discussion in #37.

Fix error variant name spelling

---

minimint-api/src/db/mem_impl.rs
minimint-api/src/db/mod.rs
minimint-api/src/db/sled_impl.rs
minimint-api/src/module/testing.rs
minimint/src/consensus/mod.rs
minimint/src/lib.rs
mint-client/src/lib.rs
mint-client/src/ln/mod.rs
mint-client/src/mint/mod.rs
mint-client/src/wallet/mod.rs
modules/minimint-ln/src/lib.rs
modules/minimint-ln/tests/ln_contracts.rs
modules/minimint-mint/src/lib.rs
modules/minimint-wallet/src/lib.rs

Extension trait is not needed. We can just use inherent impl for `dyn Database`.
important changes are in `minimint-api/src/db/mod.rs`, rest are just side effects.

Remove Database trait and rename RawDatabase to Database

---

mint-client/src/main.rs

We can just use [doc comments to generate `about`](https://docs.rs/structopt/latest/structopt/#help-messages).

Cleanup: use doc comments instead of structopt(about)

---

minimint-api/src/encoding/btc.rs

Fixes a TODO left when I took a shortcut by encoding the address string.

minimint-api: implement proper `bitcoin::Address` encoding

---

mint-client/src/clients/user.rs
mint-client/src/main.rs

Don't just sleep, actively look for contract acceptance reducing latency.

Wait for outgoing LN contract readiness

---

minimint-api/src/module/mod.rs
minimint-api/src/module/testing.rs
minimint/src/consensus/mod.rs
modules/minimint-ln/src/lib.rs
modules/minimint-mint/src/lib.rs
modules/minimint-wallet/src/lib.rs

As mentioned in https://github.com/fedimint/minimint/pull/49#issuecomment-1079118926 a lot of problems arise from parallel processing of transactions. This PR will reduce parallelism in transaction processing and confine it to well-controlled areas of the code where no side effects need to be controlled for. Fixes #28

De-parallelize transaction processing

---

Cargo.lock
minimint/Cargo.toml

Before this commit I ran into [this issue](https://github.com/rust-rse/reed-solomon-erasure/issues/86) on M1 Mac. 
After this commit, the project compiles and the pass on M1 Mac. Needed to fork [hbbft](https://github.com/poanetwork/hbbft) in order to upgrade [reed-solomon-erasure](https://github.com/rust-rse/reed-solomon-erasure) to 5.0.1 in order to include [this commit](https://github.com/rust-rse/reed-solomon-erasure/pull/89).
I have not idea if I correctly upgraded the [reed-solomon-erasure](https://github.com/rust-rse/reed-solomon-erasure) dependency in hbbfd. [Here's the commit](https://github.com/justinmoon/hbbft/commit/8cf186bcb9b30137fc7d0e1c5d52cfe9202ca206) where I did it. I just hacked it to get it compiling. No tests fail, but the `reordering_attack` test doesn't finish. And …

Fork hbbft to get minimint compiling on M1 Mac

---

default.nix
shell.nix

Apparently #68 added OpenSSL as a dependency but we changed our new nix-based CI doesn't include it and apparently wasn't run again for #68 after #45 was merged.

Fix CI after adding openssl dependency

---

scripts/startfed.sh

Normally hitting "enter" in the logs helps to:
1. Scroll back to bottom of the log after scrolling back in history
2. Put some spaces in output to help separate things visually
So I often find myself hitting "enter" out of habit in the `startfed.sh` logs and accidentally killing it!
This "works on my machine" ...

Stop startfed.sh with ctrl-c instead of enter

---

mint-client/src/main.rs
scripts/integrationtest.sh

Currently the `peg-out` command is broken. It uses `bitcoin::Amount::from_str` to parse the amount argument which assumes a string of the form "\<amount\> \<denomination\>". Obviously, this doesn't work for a CLI where spaces imply separate arguments. Instead, use sats.

Fix peg-out client CLI command

---

README.md
ln-gateway/src/bin/gw_configgen.rs
scripts/integrationtest.sh

Currently we just generate a fake Lightning node pubkey which makes receiving Lightning payments impossible.
As discussed on Telegram, this change allows us to both run the federation without requiring lightning (pass your own fake pubkey) or use the pubkey of a real node.

Pass node pubkey as parameter to gw_configgen

---

minimint-api/src/db/batch.rs

`'c` is not needed because the compiler shortens the `'b` to the smallest possible lifetime.

cleanup: remove needless lifetimes

---

.github/workflows/rust.yml
.gitignore
Cargo.lock
README.md
ln-gateway/src/bin/ln_gateway.rs
ln-gateway/src/lib.rs
minimint-api/src/db/batch.rs
minimint/Cargo.toml
minimint/src/consensus/mod.rs
minimint/src/lib.rs
minimint/src/net/connect.rs
minimint/tests/TESTING.md
minimint/tests/fixture/fake.rs
minimint/tests/fixture/mod.rs
minimint/tests/fixture/real.rs
minimint/tests/integrationtest.rs
mint-client/src/clients/user.rs
mint-client/src/lib.rs
modules/minimint-mint/src/lib.rs
modules/minimint-wallet/src/lib.rs
modules/minimint-wallet/src/txoproof.rs
scripts/final-checks.sh
scripts/integrationtest.sh

I have added the ability to integration test in Rust, and written 5 passing integration tests and 4 failing (ignored) that identify known or possibly new issues.
The tests can run with fake or real versions of Bitcoin/LN, when running in parallel all tests run in <10sec.
I minimized any changes to production code, but had to refactor some infinite loops.  No changes to existing functionality should occur.
The new test fixtures allow developers to manipulate/inspect consensus, Bitcoin, LN, and test via the gateway/user client APIs.
Side-note: I'm not a fan of what `cargo fmt` does to legibility so I've separated the PR into two separate commits.  Also added a convenient script to run all checks before opening a PR.
More documentation can be found here: …

Rust integration tests

---

docs/architecture.md
minimint/src/consensus/interconnect.rs
minimint/src/consensus/mod.rs
minimint/src/lib.rs
minimint/src/net/api.rs
minimint/tests/fixture/mod.rs

This PR renames `FediMint` to `Minimint` (less confusing) and updates the `architecture.md` doc to better reflect the codebase to help new developers.

Update architecture doc

---

modules/minimint-wallet/src/lib.rs

We are looking up the `RoundConsensusKey` twice in the same function. The first lookup returned the function if `None` and the second lookup just checked `.is_some()`. So the second call wasn't necessary.

Remove repeated database lookup

---

integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
minimint/src/transaction.rs
mint-client/src/clients/gateway.rs
mint-client/src/clients/mod.rs
mint-client/src/clients/transaction.rs
mint-client/src/clients/user.rs
mint-client/src/mint/mod.rs
modules/minimint-mint/src/tiered/coins.rs
modules/minimint-wallet/src/lib.rs

A PR for improving coin selection with change outputs based on @justinmoon's work:
- Refactored duplicate code for signing transactions into the `TransactionBuilder`
- The user clients will now make change for peg-out and LN invoice transactions (tested in integration tests) #1.
- `Coins::select_coins` will minimize the total `amount` of change (but not total number of coins which is far more difficult to compute) #11
- Fees are subtracted from the final change based on `Transaction::fee_amount` so that the client and federation are using the same fee calculation code
- The `save_coin_finalization_data` function is removed and replaced with a callback in `create_coin_output` to ensure coins are saved to the database
- New `receive_coins` and `pay_coins` functions in the `UserClient` allow …

Coin selection

---

.github/workflows/rust.yml

#90 is blocking development, deactivating nix tests for now

Deactivate failing Nix CI

---

Cargo.lock
integrationtests/Cargo.toml
integrationtests/README.md
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
minimint-api/src/module/mod.rs
minimint-api/src/module/testing.rs
minimint-derive/src/lib.rs
minimint/src/consensus/mod.rs
minimint/src/db.rs
minimint/src/lib.rs
minimint/src/net/connect.rs
modules/minimint-ln/src/lib.rs
modules/minimint-mint/src/lib.rs
modules/minimint-wallet/src/lib.rs

- Introduces a new `DropPeerKey` in the database that allows a module to drop a misbehaving peer from HBBFT consensus
- During `end_consensus` peers that do not contribute shares (if we have) or contribute bad shares will be dropped
- Implementation covers the mint module only, need follow-up work to handle similar situations in ln and wallet
- Also the client and federation doesn't recover well if a federation node goes down eventually we will need to make that more robust

Drop non-contributing peers in mint module fedimint/minimint#72

---

integrationtests/tests/tests.rs
ln-gateway/src/bin/ln_gateway.rs
ln-gateway/src/lib.rs
minimint/src/outcome.rs
mint-client/src/api.rs
mint-client/src/clients/gateway.rs
mint-client/src/clients/user.rs
mint-client/src/main.rs
modules/minimint-ln/src/contracts/mod.rs
modules/minimint-ln/tests/ln_contracts.rs

While working on the lightning receive functionality I ended up with 4 different ways to poll whether a given transaction outpoint was accepted by the federation. This seemed complex and confusing.
This PR attempts to move this polling logic to the `impl` of `FederationApi`. It adds concrete variants to `OutputOutcome` which impl `TryIntoOutcome` to assist checking that the outcome observed is what we expected -- e.g. a lightning preimage was decrypted. In the future implementors of `FederationApi` should be able to override this polling implementation with websockets etc.
In order to always poll by `OutPoint` (instead of `OrderId` or `ContractId` etc) I had to make a couple functions return `OutPoint` in addition to what they previously returned.
I also made `UserClient::ln_client()` …

Implement outpoint polling in FederationApi

---

Cargo.lock
minimint-api/Cargo.toml
minimint-api/src/db/sled_impl.rs

from https://github.com/rust-lang-deprecated/tempdir
> Deprecation Note
> The tempdir crate is being merged into tempfile and is available in 3.x.

Replace tempdir with tempfile

---

Cargo.lock
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
ln-gateway/Cargo.toml
ln-gateway/src/lib.rs
minimint/src/consensus/conflictfilter.rs
minimint/src/consensus/mod.rs
minimint/src/outcome.rs
mint-client/src/api.rs
mint-client/src/clients/gateway.rs
mint-client/src/clients/user.rs
mint-client/src/ln/incoming.rs
mint-client/src/ln/mod.rs
mint-client/src/ln/outgoing.rs
mint-client/src/mint/mod.rs
mint-client/src/wallet/mod.rs
modules/minimint-ln/src/config.rs
modules/minimint-ln/src/contracts/incoming.rs
modules/minimint-ln/src/lib.rs
modules/minimint-ln/tests/ln_contracts.rs

This PR exposes the "incoming" contracts from the lightning module.
It doesn't add any new user-facing functionality yet. I have previously sketched out how the gateway daemon and user client CLI would need to change (https://github.com/fedimint/minimint/pull/101) but want to get the core library code merged first and then complete that PR.

Expose lightning receive functionality to clients

---

Cargo.lock
client/cli/Cargo.toml
client/cli/src/main.rs
client/client-lib/Cargo.toml
client/client-lib/src/lib.rs
client/client-lib/src/utils.rs

the fn moved are also useful for future modules (clientd for example) and should not only be in the mint-client bin

organize utlility functions in 'utils' (client-lib)

---

ln-gateway/src/lib.rs

This thing makes too much noise! (image from integration tests)

Reduce log level in background_fetch to "debug"

---

.github/workflows/rust.yml
README.md
docs/nix_instructions.md
flake.lock
flake.nix

cargo2nix has issues finding lib,sys crates so switching to crane (offers better caching support) untill the issue is fixed upstream. After this pr minimint can be installed using `nix run github:fedimint/minimint` and for a specific branch we can use `nix run github:fedimint/minimint/branch_name`

Flakifying minimint

---

client/client-lib/src/api.rs
client/client-lib/src/clients/gateway.rs
client/client-lib/src/clients/user.rs
client/client-lib/src/mint/mod.rs
minimint-core/src/lib.rs
minimint-core/src/outcome.rs

#146 had a little bug where [this line](https://github.com/fedimint/minimint/blob/386706597716319081609bcccbe22232c9d3111a/client/client-lib/src/clients/gateway.rs#L316) would just fail with a `MismatchingVariant` error when the outpoint contained `DecryptedPreimage::Pending`. The integration tests didn't catch this because they just skipped the "pending" state, but I noticed it testing the actual core-lightning plugin in `integrationtest.sh`.
Renamed all `is_retryable_fetch_coins` to `is_retryable` because we're not just re-fetching coins anymore ...

"retryable" error type for preimages that aren't decrypted yet

---

integrationtests/tests/fixtures/mod.rs
minimint/src/consensus/debug.rs
minimint/src/consensus/mod.rs

Some minor changes to improve the logging while testing
- If consensus times out during testing, panic with a useful error message
- Print the consensus debug logs while mints are running

improve test debugging logs

---

client/client-lib/src/api.rs
client/client-lib/src/clients/gateway.rs
client/client-lib/src/clients/user.rs
integrationtests/tests/fixtures/mod.rs
minimint-core/src/config.rs
minimint/src/config.rs

This fixes the CI tests getting stalled due to the user sending a tx to only 1 slow peer that might not be able to contribute that tx to consensus.  The solution is the client needs to be changed to send txs to at least max_evil + 1 peers.
I was able to reproduce the issue by `thread::sleeping` in the HBBFT send message loop.  Interestingly the peer that starts a HBBFT proposal will not necessarily be the peer included in the final proposal.
Long-term we should improve the client code to send to all peers concurrently so if one of the peers is unreachable we don't block forever.  Additionally we should version our APIs with the epoch # so we can verify peers are returning the same results if on the same epoch.

fix client not sending requests to enough peers

---

Cargo.lock
client/client-lib/src/clients/user.rs
integrationtests/Cargo.toml
integrationtests/tests/tests.rs
modules/minimint-ln/src/lib.rs

Drops peers who don't contribute valid decryption shares.
Allows us to finally close #72 now that all modules are dropping non-contributing peers.

Drop non-contributing peers in LN module

---

integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
minimint-api/src/module/audit.rs
minimint-api/src/module/mod.rs
minimint/src/config.rs
minimint/src/consensus/debug.rs
minimint/src/consensus/mod.rs
modules/minimint-ln/src/db.rs
modules/minimint-ln/src/lib.rs
modules/minimint-mint/src/db.rs
modules/minimint-mint/src/lib.rs
modules/minimint-wallet/src/config.rs
modules/minimint-wallet/src/lib.rs

Adds an audit of the balance sheet of the federation, closes #128.
- If the balance sheet is negative (more liabilities than assets) the federation will panic
- To ensure this never happens we need to address #196
- Eventually the audits will need to be aggregated or use a DB query as the number of minted coins grows
- Prints a very useful balance sheet message during testing (or when panic occurs):
```
- Balance Sheet -
-3000.000|OutputOutcomeKey(OutPoint { txid: 0000000000000000000000000000000000000000000000000000000000000000, out_idx: 0 })
-2000.000|OutputOutcomeKey(OutPoint { txid: 525e269e815c7167ff9d5b4b239da32a24d12a76eab517d72aa150f22c466a87, out_idx: 0 })
+1000.000|NonceKey(CoinNonce(XOnlyPublicKey(4cc953dac7ea38ba126b2eaf75513540c2af2a79ace8bc91de7786a5b3aded497e1c72118036ff7ea80 …
```

build audits into modules

---

integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

I noticed that these two lines (1) fetch coins and (2) assertion about coins kept being repeated. 
I think these helpers improve the readability of our tests a little bit?

Add coin assertion helpers to UserTest

---

scripts/latencytest.sh

Produces a confusing result currently https://discord.com/channels/990354215060795454/992503915578933268/992550624161964182
@jkitman is 4 a good number?

Default federation size of 4 for latencytest.sh

---

.github/workflows/rust.yml
scripts/integrationtest.sh
shell.nix

Core-lightning is doing some slow polling in production builds (e.g. channel openings, chain tip, …). Dev builds are said to speed things up or at least allow us to set `--dev-*` options to reduce polling latency. This should speed up integration tests.

Use dev version of core-lightning for faster polling

---

scripts/integrationtest.sh

Sometimes the integration tests would fail when trying to pay over lightning network because our our core-lightning channel was still in the `CHANNELD_AWAITING_LOCKIN` state and not in the `CHANNELD_NORMAL` state. Here we wait until `CHANNELD_NORMAL` has been observed before proceeding.

integrationtest.sh waits for operational lightning channel

---

.github/workflows/rust.yml

I just noticed we are also building every PR commit twice. That's kinda silly and seems to block runners.

Only build PR commits once

---

shell.nix

When debugging a problem in #210 with @justinmoon we noticed we were using different versions of nixpkgs. Even though it turned out not to be the cause of the problem we might want to make sure that everyone is using the same environment.
Depends on #210, do not merge before.

Pin nixpkgs

---

Cargo.lock
minimint-api/Cargo.toml
minimint-api/src/encoding/mod.rs

1. helps to put invoices into db
2. will be needed to fix [this](https://github.com/fedimint/minimint/blob/7cac6529e7e3c44b38399059080c977d334d9a7c/modules/minimint-ln/src/contracts/outgoing.rs#L23) when this [PR](https://github.com/lightningdevkit/rust-lightning/pull/1575) is available

en/de-codeable for lightning_invoice::Invoice

---

client/client-lib/src/clients/gateway.rs
client/client-lib/src/ln/db.rs
client/client-lib/src/ln/mod.rs
docs/database.md

Had to make ln client's db module public to do this. We should make it private again once the user and gateway clients are unified.
Removing db keys from the `gateway.rs` is a step towards https://github.com/fedimint/minimint/issues/236

Move all client DB keys into 0x2 namespace

---

.github/workflows/rust.yml
scripts/latency-test.sh
scripts/pegin.sh

To ensure that no change dramatically increases the latency of an action and to check for failures from hitting the API repeatedly I'd like to add `latency-test.sh` to the GH actions.
Also this change will support fed sizes up to 20 and logs timing better:
```
AVG REISSUE TIME: 2.801 seconds
AVG LN SEND TIME: 5.139 seconds
AVG LN RECEIVE TIME: 6.151 seconds
```
Surprisingly not too much slower than
```
AVG REISSUE TIME: 1.068 seconds
AVG LN SEND TIME: 2.949 seconds
AVG LN RECEIVE TIME: 2.949 seconds
```

adds latency-test.sh to GH actions

---

ln-gateway/Cargo.toml

This fixes #263
To test this, add a logging statement like `tracing::info!("hello")` in the `main` function of `ln_gateway.rs`.
Run the gateway inside lightningd e.g. with `setup-test.sh`. You'll see your log output is there.
Now run `cargo test peg_in_and_peg_out_with_fees` and you'll see that output isn't repeated. On master it is e.g. https://discord.com/channels/990354215060795454/992503915578933268/996530029582360667.
Also, this makes sense from the [docs](https://docs.rs/tracing/latest/tracing/#crate-feature-flags). The `log-always` feature always logs -- so if we have a tracing subscriber that's also logging we'll get duplicates. But `log` just logs if there **isn't** a tracing subscriber. So that's not a problem because we should always have a tracing subscriber except in …

Remove log-always feature from gateway trace dep

---

shell.nix

I noticed that running `which cargo-clippy` within nix-shell pointed to my system install, not the nix store.
Added another commit to filter out `~/.cargo` from path. This fixes an [issue](https://discord.com/channels/990354215060795454/992503915578933268/997436439845408869) I had where global `rustup` toolchain was leaking into nix environment and causing clippy errors.

Add clippy and rustfmt to nix-shell

---

client/cli/src/main.rs
client/client-lib/src/utils.rs
minimint-api/src/lib.rs
scripts/cli-test.sh
scripts/latency-test.sh
scripts/pegin.sh

Addresses #237 
Maybe you think the additional `parse_minimint_amount` is overkill since we'd just change the `FromStr` impl for `Amount` but I think this is not reasonable because the default for minimint::Amount is msat so a `"1"` should always be `1msat` when parsed as a `minimint::Amount `
Also the `from_str_in` approach maybe seems weird to but since `minimint::Amount` and `bitcoin::Amount `are closley related I wouldn't call it a hack

consistent bitcoin denominations

---

minimint/src/consensus/debug.rs

tiny spelling nit, noticed during @base58btc's summer base58 n' coding demo

nit: fix debug error spelling

---

client/cli/src/main.rs
client/client-lib/src/api.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/db.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/db.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/transaction.rs
client/client-lib/src/wallet/mod.rs
docs/database.md
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
ln-gateway/src/lib.rs
minimint-core/src/outcome.rs
minimint-core/src/transaction.rs
minimint/src/config.rs
minimint/src/consensus/conflictfilter.rs
minimint/src/consensus/mod.rs
minimint/src/db.rs
modules/minimint-wallet/src/db.rs
modules/minimint-wallet/src/lib.rs
scripts/cli-test.sh

Stops the fed from crashing due to peg-outs (fixes step 1 in #233)
- Peg-outs now only can happen once per epoch and only one peg-out is allowed per UTXO.
- Broadcasts are immediate after a peg-out is signed.
- Fees are exact and determined by the estimated min. sat/byte required by `FeeConsensus` (target confirmation time = 10 blocks) and the calculated transaction weight (no more profits/losses).
- Rather than always returning 404 if a tx failed the fed will store and return the `TransactionStatus::Rejected`, allowing clients react to tx errors.
- Stores pending coins and will reissue them in `reissue_pending_coins` if a tx is rejected (fixes #35)

add user determined fees to peg-outs

---

integrationtests/tests/tests.rs
minimint-core/src/transaction.rs

Now that we are ensuring that peg-out fees are exact we can require that all transactions are balanced.
Note in practice this means the mint should have a 1msat denomination.

do not allow unbalanced txs where fed can profit accidentally

---

minimint/src/bin/server.rs
minimint/src/config.rs
minimint/src/lib.rs
scripts/start-fed.sh

Addresses #220 
Removed `db_path` from the `ServerConfig` struct where it was always set to `cfg/mint-id.db` previously

make (server) db_path configurable

---

scripts/build.sh
scripts/cli-test.sh
scripts/latency-test.sh
scripts/lib.sh
scripts/rust-tests.sh
scripts/setup-tests.sh

Other scripts might wan't to use that cleanup logic too so it makes sense to put it into `lib.sh`
the `trap` remains in `build.sh` though because we want scripts to be able to `source lib.sh` and execute to finish without cleaning up everything (`pegin.sh` for example)

move the cleanup function to lib

---

Cargo.lock
ln-gateway/Cargo.toml
minimint/Cargo.toml
modules/minimint-wallet/Cargo.toml

Should we somehow check for unused dependencies in CI ?
e.g `cargo +nightly udeps`

async-std not needed anymore

---

Cargo.lock

Get fedimint/hbbft#6 into minimint

Update hbbft to use threshold_crypto#master instead of a pinned version

---

crypto/tbs/src/lib.rs
integrationtests/tests/tests.rs
minimint/src/lib.rs

Fixes #311 - to allow single-member federations, particularly for people who want to evaluate Fedimint themselves before putting in the effort of organizing a federation.
There is a Rust integration test, but also running `cli.test.sh` with fed size of 1 works which should test all modules.
@wiredhikari This might also help you run the nix module because you could run without any other peers.  Although for production users will need the option to pass in TLS configs for the other peers.

allows for single member federations

---

shell.nix

Thanks @justinmoon for the debugging session.
This fixes the build of bitcoind `23.0` by using the standard bitcoind package after the fix in nixos/nixpkgs#179795 was merged.

Fix bitcoind 23.0 install on aarch64

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs

All invocations of LnClient::create_outgoing_output simply await the response. This PR modifies the method declaration to be synchronous instead of asynchronous so that callers don't need to await the result.

Change LnClient::create_outgoing_output to be sync instead of async

---

integrationtests/README.md

Currently this just runs tests in the main `minimint` crate. I think this is leftover from when the integration tests lived inside `minimint` crate. Now they have their own crate.

Update README command to run integration tests

---

.tmuxinator.yml
scripts/tmuxinator.sh

I'm just getting started trying out Fedimint but I got stuck because tmuxinator didn't play nice with my tmux session I already had running using the `fish` default shell. This PR creates a `fedimint-dev` socket so a separate session using `bash` as the default shell is still possible in my case.

Create new socket in tmuxinator to avoid using any existing session

---

Cargo.lock
Cargo.toml
client/cli/Cargo.toml
client/cli/src/main.rs
default.nix
flake.lock
flake.nix
ln-gateway/Cargo.toml
ln-gateway/src/bin/ln_gateway.rs
minimint-api/Cargo.toml
minimint-api/src/db/mem_impl.rs
minimint-api/src/db/mod.rs
minimint-api/src/db/rocksdb_impl.rs
minimint-api/src/db/sled_impl.rs
minimint/Cargo.toml
minimint/src/lib.rs
shell.nix

TODO:
- Fix the lifetimes for the raw prefix search
- Change the API and Database trait to support self referencing transactions 
- Use native rocksdb column families instead of prefixing (e.g. collecting signature shares for a given token and deleting the column later)
- Perhaps create inherited traits for basic database -> transactional database -> transactional + column family database
- Crate generic trait for expected "transaction" behaviors and functionality
- Get rid of sled_impl and replace all references
- Remove Batch.rs  
- Improve UT and add coverage for all expected trait functionality
Note: transactions are soon to be merged into rust-rocksdb we are simply waiting on a couple changes for the next rocksdb you can track the issue here …

Added rocksdb with transactions using Yiyuanliu branch of rust-rocksdb.

---

ln-gateway/Cargo.toml
ln-gateway/src/webserver.rs

Inside a web browser, CORS is need for client to connect ln-gateway because
they are not hosted on the same orgin.

ln-gateway: allow CORS

---

.dockerignore

Ignore cargo target build directory when adding files to docker image.

Add .dockerignore file.

---

Cargo.lock
modules/minimint-wallet/src/bitcoincore_rpc.rs

Also includes a `Cargo.lock` update resulting from #335 afaik that wasn't included there. I wonder how we can catch such things in CI.

Add signet support

---

flake.lock
flake.nix

This is a quick PoC in relation to #317
After `nix develop`, I am able to do `cargo build` just fine. `rust-analyzer` works fine too. Though I don't have a Mac to try if any of the extra SSL paths, etc. are still needed. If so, you can add them as they were, and please add a comment that they are Darwni-fixups or something.

Nix Flake PoC

---

docs/wallet_module.md
integrationtests/tests/tests.rs
modules/minimint-wallet/src/config.rs
modules/minimint-wallet/src/lib.rs
scripts/lib.sh
scripts/pegin.sh

These changes add the reporting of `finality_delay` to the output from `scripts/pegin.sh`. Additionally, the spelling was corrected from `finalty_delay`. This addresses issue [#216](https://github.com/fedimint/minimint/issues/216).

Added finalty_delay to pegin.sh & fixed spelling

---

.github/workflows/rust.yml

addresses #306 
check for unused dependencies with the cargo tool `udeps`
This was copied from [here](https://github.com/bevyengine/bevy/pull/5172), but I think this is exactly what we need.
**I'm not sure if we want to do the caching like this though**, please give your opinion

Check for unused deps

---

modules/minimint-wallet/src/config.rs

This change adds the property `finality_delay` to the struct `modules::minimint-wallet::src::config::WalletClientConfig`. This addresses issue [#216](https://github.com/fedimint/minimint/issues/216) and pull request [#344](https://github.com/fedimint/minimint/pull/344).

Added finality_delay to WalletClientConfig

---

integrationtests/Cargo.toml

Without this, `udeps` (added to CI in #336) will report all the dependencies of `minimint-tests` as unused because they are only used in testing, causing CI to fail. CI is currently failing on master for this reason, but I don't understand why #336 passed in review ...

minimint-tests uses dev-dependencies

---

.github/workflows/ci-nix.yml

I wasn't aware of buildjet when I initially created it.

Run nix-ci on buildjet

---

flake.nix
integrationtests/Cargo.toml
integrationtests/src/main.rs

It was only neccessary because I didn't know better how to do it,
and now I've got some help:
https://github.com/ipetkov/crane/discussions/59#discussioncomment-3370974

Remove dummy `[lib]` from `integrationtests`

---

.github/workflows/ci-nix.yml

Thanks to being able to reuse per-dependency derivations, instead of having to throw away the whole cache like github-action-based cache did, even if some minor things changed, the build time seems still much better.

Use `cachix` for `nix-ci.yml`

---

README.md
minimint/src/net/connect.rs
minimint/src/net/peers.rs

This will be the second step (after renaming the repo) towards the
rebranding. Later the code changes (#293) will follow.

Update README to say Fedimint instead of MiniMint

---

Cargo.lock
client/client-lib/src/api.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
docs/database.md
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
minimint-core/Cargo.toml
minimint-core/src/epoch.rs
minimint-core/src/lib.rs
minimint-derive/src/lib.rs
minimint/Cargo.toml
minimint/src/config.rs
minimint/src/consensus/debug.rs
minimint/src/consensus/mod.rs
minimint/src/db.rs
minimint/src/lib.rs
minimint/src/net/api.rs
modules/minimint-mint/src/lib.rs
modules/minimint-wallet/src/lib.rs
scripts/final-checks.sh

First task in #320.
- Save epoch history to the database
- Use threshold sigs as consensus items to sign merkle tree hashes of the epochs
- Drop peers that do not contribute valid sigs
- Expose a history API to allow clients to download epoch history
Seems to add ~.1s to various actions in `latency-test.sh`

create api for signed epoch history

---

.github/workflows/rust.yml

Coverage in CI addresses #288 
For the uploading to codecov to work an admin needs to create a token and set as a secret (`CODECOV_TOKEN`) in the env.
We need to use `nightly` because it wants to compile `minimint-derrive` which has a feature [attribute](https://doc.rust-lang.org/error-index.html#E0554)

CI code coverage

---

.github/workflows/ci-nix.yml

When we are using buildjet runners we want tighter timeouts since they
cost us money and we don't want an accidental infinite loop to run for
the default 6h.

Add timeout to nix-ci.yml

---

README.md

While working through the cli tutorial, I noticed `mint_cli` is had been renamed to `mint-client-cli` after #329

docs: update mint client cli commands

---

client/clientd/src/bin/clientd-cli.rs
client/clientd/src/lib.rs
client/clientd/src/main.rs
scripts/clientd-tests.sh

analogous to the `mint-client-cli`
will be needed for testing the following endpoints (e.g `peg_in`)
because `clientd` and `mint-client-cli` can never run simultaneously

clientd wait_block_height

---

.github/workflows/ci-nix.yml
.github/workflows/daily.yml
flake.nix

Bunch of commits (each with separate short commit message).
* move back to stable by
* droping `--all-features` from code coverage
* moving `cargo-udeps` to separate workflow that will run daily
Keeping the "Update cargo-udeps to latest crates.io version" just for reference if I need it later.

Switch back to stable, tweak some stuff to make it possible

---

docs/macos.md

I updated the mac multipass docs with some details I figured out while setting it up
- Increased recommended disk size since VM runs out of space quickly
- Added details about setting up remote ssh with VSCode

update mac multipass docs

---

Cargo.lock

Changes the version of `threshold_crypto` that's used so that public keys are serialized as hex.
This addresses [109](https://github.com/fedimint/fedimint/issues/109) and [pull](https://github.com/fedimint/threshold_crypto/pull/2#issuecomment-1216103247).

Use threshold_crypto hex pubkey serialization

---

flake.nix

I've accidentally removed it when refactoring flake.nix.

Add `rust-analyzer` back to the dev shell

---

.github/workflows/daily.yml

For some reason daily check [failed with](https://github.com/dpc/fedimint/actions/runs/2873032165):
> This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.
I'm not sure why it happened, but since this workflow is not blocking anyone, it's OK if it's slower but free, and maybe it will fix the issue as well.

Run daily check on a free github action machine

---

.github/workflows/ci-nix.yml
flake.nix

Also run them on one thread only.
Fix #397

Run integration tests only in ccov job

---

scripts/lib.sh
scripts/pegin.sh

- added a few helper functions which can be used in the future.
- fixed a small bug in the sat to btc calculation (amounts > 100.000.000 sat would not work because there is a 0 in front of it)
- provide a quick way to peg-in manually (or do whatever with the `TXOUTPROOF` and `TRANSACTION`)

do peg-in in smaller steps and add some helper fns

---

.github/workflows/ci-nix.yml

It is redundant with "push to master" one.

Delete (not unnecessary) build of merged PR

---

integrationtests/README.md

The codeblock `cargo test -p minimint <test-name>` should be `cargo test -p minimint-tests <test-name>`.

Fix integration test README codeblock.

---

.devcontainer/Dockerfile

This should save couple of megs.
More discussion in: #426

devcontainer: Only flake.* files are needed to run `nix develop`

---

Cargo.lock
client/client-lib/Cargo.toml
client/client-lib/src/lib.rs

The `InvoiceBuilder::current_timestamp` uses `SystemTime::now()` internally, which is unimplemented on wasm and thus panics.
We can use [`getTime`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime) on `new Date()` on wasm.
This is not done in std library because `wasm32-unknown-unknown` can't garauntee presence of a JS runtime.

wasm: fix invoice generation

---

flake.nix

I'm hitting this error when running tmuxinator.sh
error: undefined variable 'fedimint'
at /nix/store/4bjsf2f7zmjmjlhb7bcl2sz9x38y7007-source/flake.nix:422:17:
421|
422|                 fedimint.package
|                 ^
423|                 fedimint-tests.package
(use '--show-trace' to show detailed location information)
I think there's a small typo in flake.nix that causes this to fail (fedimint.package needs to be fedimintd.package)

Fix typo in Flake.nix

---

client/client-lib/src/lib.rs
client/client-lib/src/wallet/mod.rs

We don't need to check two times for an amount that is too small.

don't check two times for peg-in-too-small

---

fedimint/src/bin/configgen.rs
scripts/build.sh

Positional arguments are not descriptive and harder to use.

Improve configgen command line handling a bit

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/utils.rs
client/client-lib/src/wallet/mod.rs

* Remove struct `BorrowedClientContext`
* Rename `OwnedClientContext` to `ClientContext`
We don't need `BorrowedClientContext` as we can just borrow the entirety of `OwnedClientContext` (renamed to `ClientContext`) if we held the config externally.

Remove unnecessary struct `BorrowedClientContext`

---

flake.nix

Upstream cargo issue: https://github.com/rust-lang/cargo/issues/11020

Warn users if their local binaries can get in a way

---

.gitignore

When using `nix-direnv` as [recommended by @dpc](https://discord.com/channels/990354215060795454/992109822055030845/1011755463072817223) I get a `.direnv` file that isn't gitignored

gitignore .direnv

---

Cargo.lock
Cargo.toml
client/cli/Cargo.toml
client/client-lib/Cargo.toml
client/clientd/Cargo.toml
crypto/tbs/Cargo.toml
fedimint-api/Cargo.toml
fedimint-core/Cargo.toml
fedimint-derive/Cargo.toml
fedimint/Cargo.toml
integrationtests/Cargo.toml
ln-gateway/Cargo.toml
modules/fedimint-ln/Cargo.toml
modules/fedimint-mint/Cargo.toml
modules/fedimint-wallet/Cargo.toml

Updated per recommendations in #450 
2018->2021 edition jump across all cargo.tomls is a separate commit, can remove if this is a problem.
Changed authors to "The Fedimint Developers"
Added descriptions.
Added License="MIT" and path to LICENSE.md file
Changed all lib/bin versioning to 0.1.0

Add license and additional manifest fields to cargo.tomls

---

client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/utils.rs

Introducing mint-client-cli commands for interacting with the gateways.
This PR proposes:
These commands allow interactions and management of gateways from CLI as proposed in Issue #366 
1. `list-gateways` shows all registered gateways, with their activation status.
```
$ mint-client-cli list-gateways
Found 1 registered gateways :
[
{
"mint_pub_key": "b1f4d07fe3d5a754d47dd58b9db2710ab292d125a9cba3a854c1524c92201135",
"node_pub_key": "03c218a54e57553fa0a466900b5b7de4c51db421138084a52e45fbdfd21103e560",
"api": "http://127.0.0.1:8080",
"active": false
}
]
```
2. `switch-gateway <node_pub_key>` shows all registered gateways, with their activation status. *It might be useful to allow selection with either pubkey, so `mint_pub_key` would work as well*
```
$ mint-client-cli switch-gateway …
```

Add mint-client-cli 'list-gateways' and 'switch-gateway' command

---

Cargo.toml
client/cli/Cargo.toml
client/client-lib/Cargo.toml
client/clientd/Cargo.toml
crypto/tbs/Cargo.toml
fedimint-api/Cargo.toml
fedimint-core/Cargo.toml
fedimint-derive/Cargo.toml
fedimint/Cargo.toml
integrationtests/Cargo.toml
ln-gateway/Cargo.toml
modules/fedimint-ln/Cargo.toml
modules/fedimint-mint/Cargo.toml
modules/fedimint-wallet/Cargo.toml

Removes the "unused key" warnings by putting the top level metadata into [workspace.metadata].
Removes the "only need license or license-file" warnings: removed the license-file path for all sub-crates (kept license="MIT"), kept license-file path for top level crate linking to the actual LICENSE.md

fixed cargo.toml warnings

---

.devcontainer/Dockerfile

This got broken in #431. I have not spotted the issue, because
I didn't wait for the whole thing to build.

Fix missing `.bashrc` in devcontainer build

---

flake.nix

It seems it's possible to not have to rebuild the `workspaceDoc` step
from scratch, by executing `cargo doc` during the step that builds
only dependencies.

Cache `cargo doc` of dependencies

---

.github/workflows/rust.yml

It's just way too slow. A full rebuild (when dependencies-only build is not
in cachix for whatever reason) can easily timeout on 30 minutes limit.

Disable macos build in PRs

---

Cargo.lock
Cargo.toml
docs/lifecycle.md

(rebased to master, squashed commits)
Addresses #429 
Switches bitcoin-hashes, on fedimint fork, minimint -> fedimint branch.
Updates Cargo.lock with fedimint bitcoin-hashes branch.
Updates lifecycle.md links minimint -> fedimint.

update mini->fedi and links in lifecycle.md

---

flake.nix

This does not change much, but is kind of more "accurate".

Make `cargo test` depend only on deps build

---

client/cli/src/main.rs
client/client-lib/src/lib.rs
docs/dev-running.md
scripts/cli-test.sh

Addresses https://github.com/fedimint/fedimint/issues/362
- Created function `validate_tokens` that verifies signatures by calling `Coin::verify` (does not check if nonce spent)
- Update cli with `Validate` command
- Updated readme with expected usage
Example usage:
```
$ mint-client-cli validate AQAAAAAAAABAQg8AAA...
All tokens have valid signatures
```

Add validate command to cli

---

.github/workflows/ci-nix.yml
Cargo.lock
fedimint-core/src/epoch.rs
fedimint/Cargo.toml
fedimint/src/consensus/mod.rs
fedimint/src/db.rs
fedimint/src/lib.rs
fedimint/src/net/framed.rs
fedimint/src/net/peers.rs
flake.nix
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
scripts/README.md
scripts/final-checks.sh
scripts/reconnect-test.sh
scripts/start-fed.sh

Allows peers to resync up to consensus
- Upon start-up (possibly from crash) we send `RejoinRequest` to all peers
- Peers send the HBBFT `next_epoch` back to us and last signed epoch history
- We validate the epoch history sigs and that epoch history is within `f + 3` of the `next_epoch`
- Take `max(next_epoch)` from `2f + 1` peers an run HBBFT to produce an outcome
- Download all the epochs we've missed and process them as we can validate them

Allow peers to resync up to consensus

---

client/client-lib/src/api.rs
client/client-lib/src/lib.rs
client/client-lib/src/transaction.rs
fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/sled_impl.rs

Fixes #367
Note the `jsonrpsee_core` warnings could be suppressed through the logging level if necessary or maybe by running clientd instead of starting and shutting down the cli.

make logging less noisy

---

flake.nix

Quick fix for failing nix-build on master.

fix nix failing due to missing diir

---

crypto/tbs/Cargo.toml
crypto/tbs/benches/tbs.rs

Since we are developing against `stable`, trying to compile
the whole workspace fails on benches. By putting them
behind a feature flag, everything will work, and if anyone
needs to run benches they just need to add `--features unstable`
to `cargo bench`

Put tbs's benches behind `unstable` cargo feature

---

scripts/final-checks.sh

* POSIX-compat hashbang (so that it works in NixOS)
* Remove redundant fmt check (pre-commit check already checks it)
* Remove `+nightly` - we're locking on `stable`, it should work and
it works on my system.

Some `scripts/final-checks.sh` fixes

---

fedimint/src/config.rs
fedimint/src/lib.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
scripts/reconnect-test.sh

Next step for #320, handles the case where consensus needs to be started due to crashes that affect a large number of peers.
- Upon restart we request the `next_epoch` from all peers (including our own)
- If a threshold `2f+1` respond with the same epoch, go with that (this is the case when we are all restarting)
- If not, then consensus is on-going so peers may be on different epochs, wait for them all to respond with a timeout of 1min, then take the `max(next_epoch)` so long as it falls within bounds of the last signed history (within `f+3` epochs) to prevent malicious peers from delaying us too long
- If that doesn't work then manual intervention is required to determine what to do with the epoch that was only partially saved by consensus

recover from consensus restart

---

.cargo/config.toml
flake.nix

Tested by rebuilding `fedimintd` from scratch after modifing it's main file.
Before:
```
________________________________________________________
Executed in   26.79 secs    fish           external
usr time  138.53 secs    3.28 millis  138.53 secs
sys time    2.22 secs    1.08 millis    2.22 secs
```
After:
```
________________________________________________________
Executed in   23.74 secs    fish           external
usr time  136.10 secs    2.19 millis  136.10 secs
sys time    1.65 secs    1.75 millis    1.65 secs
```
This includes both compiling `fedimintd` package, and then linking it. Considering that we've building multiple binaries in our CI, it's probably worthwhile.
For `nix develop` users this will be transparent. Users not using it will have to install `mold`, or comment …

Link our binaries with `mold` to make it faster

---

docs/dev-running.md
docs/macos.md
scripts/tmuxinator.sh

Expect the developer to start `nix develop` first instead.
`nix-shell` is just super slow.

Don't use `nix-shell` to start `tmuxinator.sh`

---

client/clientd/src/bin/clientd-cli.rs
client/clientd/src/lib.rs
client/clientd/src/main.rs
scripts/clientd-tests.sh

I also addressed improvement requests and open TODOs from #384 in commits:
- `write json directly to stdout`
- `use macro for success response`
- `add server failure error`
Even though I wanted to keep the PR small I needed the extra stuff to implement the spend endpoint without having to add TODOs/workarounds which I'd need to come back later to.
In case you go through each individual commit, know that I addressed all `//TODO: ..`, in later commits. 
With  exemption of `//TODO: Log event` in the `fetch` function and the `//TODO: Encode coins` in the cli

clientd: spend endpoint and some imporovements

---

flake.nix
scripts/tmuxinator.sh

This PR will patch the recently made changes to `tmuxinator.sh` for use with non-POSIX-compliant shells.
Tmuxinator will use the `SHELL` variable by default which breaks `source` compatibility inside tmux

Fix development shell for non POSIX-Compliant default shells

---

.cargo/config.toml
flake.nix

This reverts commit d1ff166f5d254c95a20d3ad19185c4e78770063c.
Fixes #526

Revert "Link our binaries with `mold` to make it faster"

---

misc/git-hooks/pre-commit

Use automatic `git stash` to ignore any unstaged changes.

Lint only staged changes in git commit check

---

.cargo/config.toml
flake.nix

Looking at compile times on some under-powered laptops, I think this change is worthwhile including, and we can just skip MacOS right now.

Re-enable mold, but not on MacOS

---

.github/workflows/ci-nix.yml
flake.lock
flake.nix

* [New version of `crane` was released](https://github.com/ipetkov/crane/releases/tag/v0.6.0) so use it, and while at it:
* Pin `crane` from now on
* **Run `cargo-audit`** on every PR
* Clean up a bit
Notably we will want to run `nix flake lock --update-input advisory-db` from time to time, to download latest advisories from RustSec db.

Update crane & improve `flake.nix`

---

flake.nix

Since tmuxinator and other scripts are using `sed`,
we probably want these reproducibly set in the shell.

Add `coreutils` to the flake

---

flake.nix

[It's marked as "broken" on ARM and MacOS](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/development/tools/mold/default.nix#L46)
Encountered this setting up a NixOS dev VM on my M1 following [this neat guide](https://github.com/mitchellh/nixos-config).

Disable Mold on ARM

---

scripts/cli-test.sh

I understand that we are planning to migrate away from the shell scripts but when they eventually get converted it would be good to make sure that this also gets converted to whatever equivalent gets changed.

Check that lngw got paid ecash by the mint user

---

.replit
fedimint-api/src/db/rocksdb_impl.rs
flake.nix
replit.nix

It is possible to work on Fedimint in Replit.
Limitations:
* paid version required ($7/mo) to get 1GB of storage
* only `cargo-check` + `rust-analyzer` (hopefully)
I've put details in the comments of `.replit` file.
Status:
* `cargo c` works, so it's possible to see if everything compiles
* rust-analyzer's features like auto-completion, jump to definition, inline error highlighting seem to work as well
It takes good 20 minutes for everything to compile up when initially launched, but it should be usable enough for screen sharing and collaborative work.

Add basic replit support

---

Cargo.lock
client/client-lib/Cargo.toml

Currently TLS connections to the LN GW appear to work using `mint-client-cli` but not the fluttermint android app. I'm not sure why `mint-client-cli` works, we need to explicitly add TLS support imo and this PR does it (maybe some other dep activates it accidentally?).

Enable reqwest TLS feature in client lib

---

client/client-lib/src/api.rs

Before this change the client fails to connect to WS API endpoints that use standard ports (80 for ws, 443 for wss) due to `Url` trying to be clever.

client-lib: fix failure on API endpoints with standard ports

---

client/cli/src/main.rs
flake.lock

```
nix flake lock --update-input fenix
```
This is so that our clippy and lints match
the ones we are getting from `actions-rs/cargo`
(latest stable Rust).

Upgrade rust compiler to newest version

---

client/clientd/src/bin/clientd-cli.rs
client/clientd/src/lib.rs
client/clientd/src/main.rs

This PR deletes the re-export that slipped in somehow pointed out by @elsirion in the last PR.
Also did some renames and a better type for the `TieredCount` regarding #492 and #503

minor clientd rectification

---

flake.nix

On a fresh clone, 'nix develop' showed this error message:
ln: failed to create symbolic link './.git/hooks/': No such file or directory ln: failed to create symbolic link './.git/hooks/': No such file or directory
After this change, the error message goes away, since the script will now create the directory if it does not exist.
I am a complete noob to this repository and to nix, so forgive me if I missed something. I searched the repo for `hooks` and it led me to this code. After changing this code and running `nix develop` again, the hooks directory exists and there are scripts in the directory.

Create the .git/hooks dir if non-existent in nix cmd

---

Cargo.lock
client/cli/src/bin/mint-rpc-client.rs
client/cli/src/main.rs
client/client-lib/Cargo.toml
client/client-lib/src/api.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/query.rs
client/client-lib/src/wallet/mod.rs
crypto/tbs/src/lib.rs
fedimint-core/src/config.rs
fedimint-core/src/epoch.rs
fedimint/src/lib.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-wallet/src/config.rs

API consistency checks to make clients robust against misbehaving peers and move towards removing polling
- Process responses concurrently to defend against non-responding peers
- Move retries behind the API layer to reduce requests, simplify client code, support subscriptions eventually
- Create strategies for consistent API results to defend against peers returning conflicting results
Implemented strategies (all strategies return an error if f+1 peers return errors):
- `TrustAllPeers` Returns a result from the first responding peer
- `ValidHistory` Returns first epoch with a valid sig, otherwise wait till f+1 agree
- `UnionResponses` Returns the deduplicated union of f+1 responses
- `Retry404` Returns when f+1 responses are equal, retrying on 404 errors
- `CurrentConsensus` Returns when …

add api consistency strategies

---

client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/transaction.rs
client/clientd/src/main.rs
fedimint/src/consensus/mod.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
scripts/cli-test.sh

The `receive_coins` function is the way we should transfer ecash in production because it's the safer/faster option.
However, for demonstrating ecash as a bearer note, this changes the `spend_ecash` function so that it will reissue exact change for spending.
Fixes #592

CLI spend command makes exact change

---

client/cli/build.rs
client/cli/src/bin/mint-rpc-client.rs
client/cli/src/main.rs

I decided to also do some refactoring to make the CLI logic cleaner and also give the option to work without workdir.
This is a step towards #555 the other binaries that need to be changed are:
1. clientd
2. clientd-cli
3. configgen
4. fedimintd
5. ln-gateway
I think it is best if I do each of them in a individual PR.

version-hash command for mint-client-cli and mint-rpc-client

---

.github/workflows/ci-nix.yml
.github/workflows/linkcheck.yml
.github/workflows/rust.yml

These are builds that tend to be finishing faster anyway, so they are not bottlenecks. The cpus saved in buildjet can get used for other builds that need it more.

Take off some CI jobs from buildjet

---

Cargo.lock
Cargo.toml
client/cli/Cargo.toml
client/cli/src/main.rs
client/clientd/Cargo.toml
client/clientd/src/main.rs
fedimint-api/Cargo.toml
fedimint-api/src/db/mod.rs
fedimint-rocksdb/Cargo.toml
fedimint-rocksdb/src/lib.rs
fedimint-sled/Cargo.toml
fedimint-sled/src/lib.rs
fedimint/Cargo.toml
fedimint/src/lib.rs
flake.nix
integrationtests/Cargo.toml
integrationtests/tests/fixtures/mod.rs
ln-gateway/Cargo.toml
ln-gateway/src/bin/ln_gateway.rs

This way we don't have to use feature flags on `fedimint-api` anymore and make sure third party DB implementations would actually work.

Move database impls into their own crates

---

.github/workflows/rust.yml

It seems Github Actions require the job that I'm removing to pass ... Welcome to the Github Action California... :shrug:

Remove (now redundant - done by ci-nix) wasm32 build

---

client/cli/build.rs
flake.nix

This is a continuation of #583 . More explanation in the comments.
```
> git rev-parse HEAD
cfa380f56a174de5c01e0364b357211af40f70ee
> nix run .#mint-client-cli -- version-hash
{
"version_hash": {
"hash": "cfa380f56a174de5c01e0364b357211af40f70ee"
}
}
```

Substitute git hash placeholder in binaries when building in Nix

---

.github/workflows/ci-nix.yml

We are hitting the 30' timeout with GH Action runners, waiting longer isn't a good solution imo.

Switch container build back to BuildJet

---

flake.nix

Noticed some errors when running with `nix shell .#<package> -c <bin-name>`
For example `nix shell .#fedimint -c configgen` works but 
`nix shell .#ln-gateway -c webserver`, `nix shell .#mint-client-cli -c mint-rpc-client`, `nix shell .#clientd -c clientd-cli` do not work:
`called without required argument 'bin'`
- another fix `ln_gateway` -> `ln-gateway` is the correct name
- and add `fedimint-rocksdb` where needed (or else the comands would fail with `error: couldn't read fedimint-rocksdb/src/lib.rs: No such file or directory (os error 2)`)

fix nix-flake packages

---

integrationtests/tests/tests.rs
ln-gateway/src/lib.rs

When handling internal payments, the gateways should claim a refund if it fails the preimage obtained from buying offer
Closes #532

Claim a refund if gateway fails to decrypt preimage from offer

---

client/client-lib/src/api.rs
client/client-lib/src/lib.rs
fedimint-core/src/config.rs
fedimint/src/bin/configgen.rs
fedimint/src/config.rs
integrationtests/tests/fixtures/mod.rs

In order to support multiple federations on [Fluttermint](https://github.com/futurepaul/fluttermint) / [Webimint](https://github.com/justinmoon/webimint/), we need some kind of name to refer to the federations by. 
While we're at it, I added names to the federation "nodes". If the federation experiences downtime, this would allow the user to know who to talk to in order to fix it. Question: would "servers" or "guardians" be better name than "node"? "peer" isn't right client POV because client doesn't participate in consensus.

Add federation & guardian names to server & client configs

---

scripts/cli-test.sh
scripts/lib.sh

Attempt to fix intermittant CI failure in `cli-test.sh` where we're mining blocks too quickly ([according to Rusty Russell](https://github.com/fedimint/fedimint/issues/222#issuecomment-1257313464)).

cli-test.sh waits for CLN block processing to complete before attempting lightning payments

---

fedimint-api/src/db/mem_impl.rs

It is expected to be `Arc`ed externally (via `Database` dyn newtype).

Remove `Arc` from `MemDatabase`

---

flake.lock

```
> rustc --version
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

Bump compiler to 1.64.0

---

.github/workflows/ci-nix.yml
.gitignore
docs/nix_instructions.md
integrationtests/README.md
scripts/final-checks.sh

Creating a new PR to remove nix-shell from documentation as it has been replaced by nix develop.
This PR also adds .vscode to the .gitignore file to allow for local vs code configurations.

Remove nix-shell from documentation

---

integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/utils.rs
ln-gateway/src/bin/ln_gateway.rs
ln-gateway/src/lib.rs
ln-gateway/src/ln.rs

This PR introduces a wrapper around the `ln_client` the gatway uses to gain control over it in tests. This was @okjodom idea and is called the [Decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern). We can use this in the same manner for other trait objects in the same manner but this one is  only for the gateway.

wrap the gateways ln_client to gain controll over it

---

Cargo.lock
client/client-lib/src/wallet/mod.rs
fedimint-api/src/config.rs
fedimint-server/Cargo.toml
fedimint-server/src/lib.rs
fedimintd/src/main.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs
modules/fedimint-wallet/src/bitcoincore_rpc.rs
modules/fedimint-wallet/src/config.rs
modules/fedimint-wallet/src/lib.rs

The goal for `fedimint-server` is being a very generic "consensus running common code". That means it generally should not be creating concrete instances of stuff.
More comments in the commit messages.

Refactor some stuff out of `fedimint-server`

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/ln/outgoing.rs
fedimint-core/src/outcome.rs
integrationtests/tests/fixtures/fake.rs
integrationtests/tests/fixtures/utils.rs
integrationtests/tests/tests.rs
ln-gateway/src/bin/ln_gateway.rs
ln-gateway/src/lib.rs
ln-gateway/src/ln.rs
modules/fedimint-ln/src/contracts/incoming.rs
modules/fedimint-ln/src/contracts/mod.rs
modules/fedimint-ln/src/contracts/outgoing.rs
modules/fedimint-ln/src/db.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-ln/tests/ln_contracts.rs

We previously have Preimages defined as a `random 32-byte` slice for Outgoing contracts, and as confirmed `XOnlyPubKey` for Incoming contracts.
To have uniform guarantees of validity between Incoming and Outgoing contracts this PR proposes we always define and expect Preimages to be 32 byte data slices, with ready conversion into pub keys when required
closes #605

Unify Preimage definition for incoming and outgoing contracts

---

ln-gateway/src/bin/ln_gateway.rs

Replaces previous `bytes > pubkey > string` conversion when serializing preimage and sending to cln plugin

serialize preimage as hex on send to cln plugin

---

.github/workflows/ci-nix.yml
.tmuxinator.yml
Cargo.lock
client/cli/Cargo.toml
docs/dev-running.md
flake.nix
scripts/build.sh
scripts/tmux-user-shell.sh

`mint-client-cli` isn't a good name. Kinda hard to remember, and hard to type.
`fedimint-cli` is easier to remember, but still not super easy to type.

Rename mint-client-cli to fedimint-cli

---

Cargo.lock
integrationtests/tests/fixtures/fake.rs
modules/fedimint-mint/Cargo.toml
modules/fedimint-wallet/src/bitcoincore_rpc.rs
modules/fedimint-wallet/src/bitcoind.rs
modules/fedimint-wallet/src/lib.rs

https://github.com/fedimint/fedimint/pull/655 introduced an issue where if a transaction was already submitted by another peer then we can block and retry which could delay the federation (and CI).
Fixes #670

do not retry if transactions exist in blockchain

---

client/cli/src/main.rs
scripts/cli-test.sh
scripts/latency-test.sh
scripts/pegin.sh

This turns output from:
```
{
"version_hash": {
"hash": "2e302d6ff96c8b34492deade0c3c1d96c26cccb7"
}
}
```
to:
```
{
"hash": "2e302d6ff96c8b34492deade0c3c1d96c26cccb7"
}
```
I don't see a point of the additional nesting level and explitting tag, as the user knows which format to expect, as it was requested explicitily.
My second prefered option would be internally-tagged: https://serde.rs/enum-representations.html#internally-tagged

fedimint-cli: Use `untagged` for cli output

---

fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-api/src/macros.rs
fedimint-api/src/module/mod.rs
fedimint-api/src/module/testing.rs
fedimint-rocksdb/src/lib.rs
fedimint-server/src/consensus/mod.rs
fedimint-sled/src/lib.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

This PR is a work in progress. It adds a new trait for a Database Transaction and implements the database transaction for RocksDB. I have integrated the API into the federation module. The tests are still broken and I am currently testing the changes.
The main difference between this PR and the current code is that in this PR a single Database Transaction and passed around to subsequent functions via a reference. The old code use a "Transaction batch" concept and each function either had a copy of the parent transaction, or a "subtransaction" (which is just a copy of the parent).
Open Questions.
1) Do we want the transaction API to differentiate between new insertions and insertions that potentially could overwrite a key? (current code does support this).
2) Passing a reference to a …

Database Transactions

---

fedimint-server/src/consensus/interconnect.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs

It might have been a historical leftover, but it seems better to just standardize on one and stick with it.

Remove the generic `R: RngCore + CryptoRng` from `FedimintConsensus`

---

flake.nix
misc/git-hooks/pre-commit

Apparently, despite both reporting the same `--version` there are some minor differences in how they want to format the code. Maybe a bug, maybe something I don't know about. But it seems easier to just use `cargo fmt` for linting in CI.

Use `cargo fmt` instead of `rustfmt` for linting

---

Cargo.toml
scripts/build.sh
scripts/final-checks.sh
scripts/gw-reload.sh
scripts/rust-tests.sh

This should make setting up the dev environment much faster.
If we need more performance for crypto operations, we should use:
https://doc.rust-lang.org/cargo/reference/profiles.html#overrides
to optimize only the most important crypto crates.

Use debug builds for dev work

---

docs/dev-env.md
flake.nix
scripts/bootstrap.sh

The intention here is that we should give out the:
```
git clone -o upstream https://github.com/fedimint/fedimint && cd fedimint && ./scripts/bootstrap.sh
```
and ask participants to complete it before joining if possible. In combination with #767 this should cut on time wasted on getting everyone ready.

Add a `./scripts/bootstrap.sh` for setting up dev env

---

Cargo.lock
ln-gateway/Cargo.toml
ln-gateway/src/lib.rs
ln-gateway/src/rpc.rs
ln-gateway/src/webserver.rs

[Reconsidering Gateway Architecture](https://github.com/fedimint/fedimint/pull/709): Gateway Messaging
Defines `GatewayMessageChannel` for sending and responding to `GatewayRequest` messages between gateway components.
The message channel is bi-directional, consisting of a long lived sender for sending messages to a receiver (messaging hub) within the gateway. Responses are sent back via one-shot messages to the originator of the messaging sequence.
Application: We apply the message sender to `webserver` component of the gateway

Gateway message channels

---

flake.nix

This will detect the issue described in:
https://github.com/fedimint/fedimint/blob/b65722a7e857b6f204988724ea79eb8b1b32891a/docs/dev-env.md#preclude-nix-shell--tmux-problems
and warn the user.
Probably the best we can do. Messing with their files would be a bit too invasive.

Warn users about tmux default login shell issues

---

client/client-lib/src/api.rs

Certificates weren't working in Docker so we decided to just use "web pki" in all cases

Use WebPKI certificate store everywhere

---

client/client-lib/src/lib.rs

`<smth>` in Rustdoc Markdown should be an URL.

Fix a formatting error that offends nightly cargo doc

---

flake.nix

When using `git-worktree` the `.git` directory is shared between worktrees and not just in `./git` of the current worktree. This commit handles this new case as well.

Fix git hook installation for `git worktree` users

---

.github/workflows/ci-nix.yml
flake.nix

This could possibly lead to faster CI times, at the expense of higher cachix utilization.
After we've switched to using `cargo build` (debug mode build) in the test script, we haven't noticed that it caused the CI times to increase significantly, because the tests running `cargo build`  can't reuse the artifacts that CI build in release mode:
Switching our CI to build in debug mode fixes it and restores better build times:
Debug mode is faster than it release before even ignoring this particular issue (being fixed).

Use debug builds in the CI

---

fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-api/src/module/mod.rs
fedimint-api/src/module/testing.rs
fedimint-rocksdb/src/lib.rs
fedimint-server/src/consensus/mod.rs
fedimint-sled/src/lib.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

This PR changes the rest of the consensus code to use the new DatabaseTransaction trait. It also introduces a necessary rollback() and set_tx_savepoint() API that allows a database transaction to save a state and rollback to that state in case of failure. Added implementations for all the databases (mem, rocksdb, sled).
Specifically, this PR changes apply_input, apply_output, process_transaction, and end_consensus_epoch to use DatabaseTransactions.

Federation Database Transactions

---

client/client-lib/src/ln/db.rs
client/client-lib/src/mint/db.rs
client/client-lib/src/wallet/db.rs
fedimint-api/src/db/mod.rs
fedimint-server/src/db.rs
modules/fedimint-ln/src/db.rs
modules/fedimint-mint/src/db.rs
modules/fedimint-wallet/src/db.rs

This commit reformulates database key prefixes such that they are grouped into enums.
Currently, key prefixes are listed as separate const values. This formulation makes it difficult to manage key prefixes (import, iterate, test, etc), particularly when it comes to dbdump. This commit simplifies key prefix management using enums and a key prefix trait. It also makes it possible to test and ensure key prefixes are locally unique.

331: Group database key prefixes as enums.

---

ln-gateway/src/bin/ln_gateway.rs
ln-gateway/src/cln.rs
ln-gateway/src/ln.rs

[Reconsidering Gateway Architecture](https://github.com/fedimint/fedimint/pull/709): Compact Gateway CLN Module
This refactor moves implementation of Gateway CLN plugin into a common module in `cln.rs` as a location which scopes all CLN implementation details. The gateway binary instantiates a gateway, with CLN plugin applied as the default LN implementation.
next steps:
- prototype an equivalent lnd implementation to learn more on how the ln implementation should plug in to `LnGateway`
- cherry pick `LnGateway` api changes proposed in #709

Gateway CLN Module

---

.cargo/config.toml
flake.nix

By switching to a nix-provided rocksdb we can reduce compilation times, especially on first dev env setup since it can be fetched from cachix.

Use nix-provided, dynmically linked rocksdb

---

client/client-lib/src/utils.rs
fedimint-api/src/core.rs
fedimint-api/src/core/client.rs
fedimint-api/src/core/encode.rs
fedimint-api/src/core/server.rs
fedimint-api/src/db/mod.rs
fedimint-api/src/encoding/btc.rs
fedimint-api/src/encoding/mod.rs
fedimint-api/src/encoding/secp256k1.rs
fedimint-api/src/encoding/tbs.rs
fedimint-api/src/lib.rs
fedimint-api/src/tiered_multi.rs
fedimint-client/src/lib.rs
fedimint-core/src/epoch.rs
fedimint-derive/src/lib.rs
flake.nix
modules/fedimint-ln/src/contracts/incoming.rs
modules/fedimint-ln/src/contracts/mod.rs
modules/fedimint-wallet/src/txoproof.rs
modules/mint-client/src/lib.rs
modules/mint-common/src/lib.rs
modules/mint-server/src/lib.rs

After a while of working with the current version of Decodable
I've hit a wall, with not being able to express:
```
trait Smth : for <M : Decoder> Decodable<M>
```
without some heavy HKT machiner.
This led to a realization that the current form is conceptually
wrong. I don't need a trait that is parametrized by `M`.
I need one trait, that when impleemnted guarantee that any `M`
(with a bound) can be used.

Change `Decodable<M>` to `Decodable`

---

modules/fedimint-wallet/src/config.rs

Fixes the non-deterministic failure noticed here https://github.com/fedimint/fedimint/actions/runs/3301531854/jobs/5447105401
Caused by duplicate messages being sent which seems to happen in rare cases.

Fix DKG wallet bug from duplicate messages

---

Cargo.lock
fedimintd/Cargo.toml
fedimintd/src/bin/distributedgen.rs
fedimintd/src/lib.rs
fedimintd/src/main.rs
modules/fedimint-wallet/src/config.rs
scripts/build.sh
scripts/lib.sh
scripts/start-fed.sh

Since the guardian servers will be publicly known we should reduce the attack surface by not storing private keys in plaintext which would be easy targets for attackers with access to the filesystem or a backup of the config file.  This PR encrypts the server configs containing private keys at-rest using a password supplied by the user.
- Password can be supplied at a prompt during config generation and server start-up to avoid being in command history
- Uses PBKDF2_HMAC_SHA256 to hash the password to reduce the effectiveness of brute-force attacks
- Uses CHACHA20_POLY1305 to authenticate and encrypt the configs (so they cannot be tampered with)
Note we will need to modify the nonce generation if we intend to generate multiple versions of the configs with the same password (once we have a …

Encrypt configs at rest

---

.tmuxinator.yml
gateway/ln-gateway/src/lib.rs
scripts/tmux-user-shell.sh

Starting the gateway CLN plugin runs the gateway. On run, the gateway attempts to register with a federation. If the federation is not ready, the gateway registration call fails, which in turn would fail the CLN plugin start.
The recent change to encrypt configs at rest (#808) marginally slows down the federation start, which then leads into the situation described above. As a temporary fix, this PR tweaks our sleep timers in the shell scripts we use to orchestrate federation and gateway start by:
- delaying CLN1 (with plugin) and CLN2 by 5s each to ensure the federation is started
- delaying channel opens by 10s to ensure the CLN instances are up and running
Follow Ups:

Timing tweaks in shell scripts

---

fedimint-server/src/consensus/mod.rs

Fixes a bug that caused `peg_outs_are_only_allowed_once_per_epoch` to stall.
The user submits 2 conflicting txs, one of which will be filtered out, then the user reissues the coins from the failed tx.  We were not removing the conflicting tx from the database which could cause a conflict with the reissue transaction.
The reason the test stalls rather than fails is because the the epoch isn't empty (contains failed tx), but there are no new tx notifications or proposals to trigger a new consensus epoch.
Not sure why this failure is popping up now, bug has existed for some time.

fixes a bug where filtered txs stay proposed

---

Cargo.lock
client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/wallet/mod.rs
client/clientd/src/main.rs
fedimint-api/src/task.rs
fedimintd/src/main.rs
integrationtests/Cargo.toml
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-wallet/src/lib.rs

This is a bit of chaos, but to sum up:
* we must not use unbounded retries in the client code operations
* I'd like to introduce some more structured task control

Debug CI failures, introduce task groups, error handling improvements

---

Cargo.lock
fedimint-api/src/module/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-testing/src/lib.rs
modules/fedimint-ln/Cargo.toml
modules/fedimint-ln/src/lib.rs
modules/fedimint-ln/tests/ln_contracts.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Currently `FedimintModule` trait uses errors that are imported from the specific modules. This is not possible in a post-modularization code.
As a initial step toward modularization, make all the errors returned by the server side module abstract (anyhow::Error).
In the future we might want to specify some concrete Error variants with `Other` being just an escape hatch.

Make module errors abstract

---

fedimint-server/src/net/peers.rs
fedimintd/src/ui/configgen.rs
fedimintd/src/ui/mod.rs

I keep seeing these panics:
```
cargo-package> thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /build/source/fedimint-server/src/net/peers.rs:439:37
cargo-package> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
cargo-package> thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /build/source/fedimint-server/src/net/peers.rs:297:37
cargo-package> thread 'thread 'tokio-runtime-worker' panicked at 'tokio-runtime-workerPeer connection was dropped', /build/source/fedimint-server/src/net/peers.rs:439:37
```
when running integration tests, and they are spooking me.
It seems the IO thread should just finish instead of panicking and the cause of the panic is the parent thread is gone, and nothing to do with the connection …

Do not panic in peer connection IO handling thread.

---

.tmuxinator.yml
Cargo.lock
gateway/cli/Cargo.toml
gateway/cli/src/main.rs
gateway/ln-gateway/Cargo.toml
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/config.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/webserver.rs
integrationtests/tests/fixtures/mod.rs
scripts/build.sh
scripts/lib.sh

First pass implement gateway server auth by requiring a bearer token in requests. Turns out [tower_http](https://crates.io/crates/tower-http) has really nice auth middlewares that are plug and play with axum server.
TODO:
closes #807

Gateway Server Authentiation

---

fedimint-api/Cargo.toml
fedimint-api/src/config.rs
fedimint-api/src/net/peers.rs
fedimint-api/src/task.rs
fedimint-server/src/config.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs
fedimint-server/src/net/peers.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-wallet/src/config.rs
scripts/lib.sh
scripts/reconnect-test.sh
scripts/setup-tests.sh
scripts/start-fed.sh

Follow-through with `TaskGroup`-based improvements.
The fundamental premise here is that shutting down a program is a primary consideration
and code:
* threads should handle shutdown condition gracefully without exploding (panics, weird errors),
* panic in one thread should cause other threads to finish gracefully,
* no panic should go unnoticed,
* tests should spin-down all threads and make sure none of them failed.
In long term this should help debugging and building more sophisticated and larger e2e tests.
I'm not a fan of these `Option<Result<T, SomeError>>` for "cancelleble results", but I guess we could live with them for now, and [upgrade to some better Rust cancellable result handling approach](https://users.rust-lang.org/t/state-of-art-cancellabe-option-result-or-result-option-han …

Improve shutdown and panic handling - TaskGroup everything

---

crypto/hkdf/src/lib.rs
fedimint-api/src/cancellable.rs
fedimint-api/src/config.rs
fedimint-api/src/lib.rs
fedimint-api/src/net/peers.rs
fedimint-server/src/config.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/peers.rs
fedimintd/src/bin/distributedgen.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-wallet/src/config.rs

This makes it easier to understand and harder to accidentally forget to handle.

Turn `Option<T>` into `type Cancellable<T> = Result<T, Cancelled>;`

---

crypto/hkdf/src/lib.rs
fedimintd/src/bin/configgen.rs
fedimintd/src/bin/distributedgen.rs
scripts/cli-test.sh
scripts/lib.sh
scripts/pegin.sh

Where we previously passed in  a placeholder value, this PR uses configured federation name as id in gateway-cli calls in shell scripts.
The caveat is, we change the configured federation name slightly to make it a cli friendly value without spaces or string marker `'`

Use actual federation id to gateway-cli in shell scripts

---

gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/lib.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

**Merge after #868**
Implement a simplified gataeway actor pattern to support running execution of gateway functions for multiple federations. A gateway actor is a 1:1 representation of a Federation in the context of the gateway. The actor:
- encapsulates a federation client
- exposes a logical api on the federation client, with the following functions possible:
- `sync_wallet` - Fetch coins this gateway owns in the federation and settle the wallet state. Future: we should find a way of automating this sync operation
- `buy_preimage_offer` - Buy a lightning preimage listed for sale inside the federation served by this actor
- `await_preimage_decryption` - Wait for preimage decryption by the federation served by this actor
- `pay_invoice` - Pay an invoice on behalf of a user in the …

Gateway actors for serving multiple federations

---

fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-rocksdb/src/lib.rs
fedimint-sled/src/lib.rs

This PR adds unit tests that verify the database isolation level of the database implementation. The following unit tests are added:
test_dbtx_insert_elements
test_dbtx_remove_nonexisting
test_dbtx_remove_existing
test_dbtx_read_own_writes
test_dbtx_prevent_dirty_reads
test_dbtx_find_by_prefix
test_dbtx_commit
test_dbtx_prevent_nonrepeatable_reads
test_dbtx_rollback_to_savepoint
test_dbtx_phantom_entry
test_dbtx_write_conflict
The idea is to isolate each anamoly that can happen at isolation levels that are lower than serializable or snapshot isolation. Adding new db implementations should be much easier because running these tests again the implementation should reveal if it's isolation level is sufficient or not.
Currently, rocksdb is the only implementation that satisifies all the tests …

Add Database Isolation Unit Tests

---

gateway/cli/src/main.rs
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/config.rs
gateway/ln-gateway/src/lib.rs
integrationtests/tests/fixtures/mod.rs

**Merge after #794**
Use actors to receive invoice to a specific federation.
This PR temporarily introduces the concept of a _default_federation_ in `GatewayConfig` because we have pending work to identify federation context within the `HtlcAccepted` message routing hint, as proposed by Issue #664 
Eventually, we will be able to receive invoices on behalf of users in any of the Federations served by the gateway. However, the limitation above means we can only receive invoices on behalf of users within the federation referenced by _default_federation_ in config.

Receive invoice to a specific federation

---

Cargo.lock
client/cli/Cargo.toml
client/client-lib/Cargo.toml
fedimint-api/Cargo.toml
gateway/ln-gateway/Cargo.toml
integrationtests/Cargo.toml
modules/fedimint-ln/Cargo.toml

Closes https://github.com/fedimint/fedimint/pull/858 and https://github.com/fedimint/fedimint/pull/857. Couldn't upgrade one without the other.

Update lightning and lightning-invoice crates

---

gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/webserver.rs

Show realistic gateway info. Example:
```
$ gateway-cli info
{
"federations": [
"Hals_trusty_mint",
"Coinbase_better"
],
"version_hash": "67b8510c22180a99937201fc14706e2ec3a384a3"
}
```
closes #818

Gateway info

---

fedimint-api/src/db/mod.rs

Previous IDatabaseTransaction documentation had a formatting bug that caused the table to not render correctly when running "cargo doc". This PR fixes it so that the table renders correctly.

Fix IDatabaseTransaction Documentation Formatting

---

gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/utils.rs

Starting the gateway CLN plugin runs the gateway. On run, the gateway attempts to register with a federation. If the federation is not ready, the gateway registration call fails, which in turn would fail the CLN plugin start.
The recent change to encrypt configs at rest (https://github.com/fedimint/fedimint/pull/808) marginally slows down the federation start, which then leads into the situation described above.
This PR attempts to use retries for the gateway registration action, instead of relying on timing to sequence the boot process.

Attempt gateway registration with retry

---

gateway/ln-gateway/src/cln.rs
gateway/ln-gateway/src/config.rs
gateway/ln-gateway/src/lib.rs

**ReceiveInvoice** is a misnomer, which does not describe the event where a gateway is accepting htlcs on behalf of the user. 
The best descriptive name we could come up with is **ReceivePayment**, so this pr renames the payload

Rename ReceiveInvoicePayload to ReceivePaymentPayload

---

gateway/cli/src/main.rs

Remove configured default out dir on gataway-cli generate-config. Makes the CLI predictable to user

Require out-dir when generating gateway config

---

gateway/cli/src/main.rs
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/webserver.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

**Merge after #869**
Support remote federation registration through gateway webserver. This PR adds:
- `/register` endpoint for gateway admin to register a new federation to serve. Perhaps this is done from some admin ui dashboard
- CLI capability for registering federations to the Gateway: `gateway-cli register-fed <connect-info>`

Register Federations  on Gateway

---

client/client-lib/src/lib.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs

When building gateway clients using RocksDB, we create a file seeded with the federation id provided when registering the federation. Since the ID is an unknown value, we would expose a [path traversal attack](https://owasp.org/www-community/attacks/Path_Traversal) surface by just using the plain federation id value, which is currently an unsanitized string.
This PR proposes hashing of the federation id value before use in the gateway
#754 has proposals for defining how Federation IDs are derived. We should add this as a consideration in defining Federation IDs

Hash Federation ID in gateway

---

Cargo.lock
client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
client/clientd/Cargo.toml
client/clientd/src/main.rs
fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-rocksdb/Cargo.toml
fedimint-rocksdb/src/lib.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/net/api.rs
fedimint-sled/Cargo.toml
fedimint-sled/src/lib.rs
fedimint-testing/Cargo.toml
fedimint-testing/src/lib.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/lib.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/Cargo.toml
modules/fedimint-mint/src/lib.rs

As mentioned [here](https://github.com/fedimint/fedimint/issues/848), we would like the database transaction trait to be asynchronous. This allows for the async executor to do something else while a thread is blocked on I/O. Ideally we want the entire trait to be asynchronous, as the rest of the operations could potentially block on I/O as well. 
Changing the entire trait is a large change so this PR is scoped to just commit_tx.
I tried to not use block_on (and use await instead) wherever possible, but the remaining areas where block_on is used caused problems when attempting to make them async/await (most of the issues were with matching an API_endpoint handler or the commit_tx was in a closure that wasn't easily able to be made async). Feedback welcome if there's ideas on how to reduce …

Change IDatabaseTransaction and commit_tx to be async

---

Cargo.lock
fedimint-api/src/config.rs
fedimint-api/src/core.rs
fedimint-api/src/lib.rs
fedimint-api/src/module/mod.rs
fedimint-api/src/multiplexed.rs
fedimint-api/src/net/peers.rs
fedimint-api/src/net/peers/fake.rs
fedimint-api/src/task.rs
fedimint-server/Cargo.toml
fedimint-server/src/config.rs
fedimint-server/src/lib.rs
fedimint-server/src/multiplexed.rs
fedimint-server/src/net/peers.rs
fedimintd/src/bin/distributedgen.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Abstract away multiplexed connection behind a "dyn newtype".
Move implementation into `fedeimint-server`v This allows avoiding
wasm conditional compilation hacks, and cleans up the whole thing a bit.
Add multiplexing tests, as the implementation is non-trivial.

Multiplexing peer connection improvements

---

fedimintd/src/encrypt.rs
scripts/build.sh

This makes the test federation setup *much* faster.

When running tests, don't bother with strong `pbkdf2`

---

Cargo.lock
Cargo.toml
flake.nix
gateway/tests/Cargo.toml
gateway/tests/tests/tests.rs

Create a testing crate at `gateway/tests` to host integration tests for the Gateway

Create gateway test framework crate

---

.tmuxinator.yml
gateway/cli/src/main.rs
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/cln.rs
gateway/ln-gateway/src/config.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/ln.rs
integrationtests/tests/fixtures/fake.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/utils.rs
scripts/lib.sh

Simple CLN gateway init

---

client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
client/clientd/src/main.rs
scripts/clientd-tests.sh

The clientd integration test curerntly uses a separate thread for fetching the coins that are signed by the federation. This causes race conditions because the client needs to know when the coins have been signed before fetching. To solve this, I have added a new function on the client that will await a signature response from the Mint. [Decided not to add a CLI command ](https://github.com/fedimint/fedimint/issues/910)as it is not needed currently and we ideally want to move away from polling. 
The clientd integration test will now just wait for the signature response from the mint, then call fetch aferwards, which means that the fetch will succeed and will avoid the race conditions we were running into before.

Cleanup Clientd Integration Test

---

docs/architecture.md
docs/dev-running.md
docs/gateway.md

Start documenting the Gateway by adding high level description of:

Sketch out high level gateway docs

---

docs/dev-running.md

Discussion about this in Discord: https://discordapp.com/channels/990354215060795454/990354215878688860/1042886970117992468
Summary:
I was following along in dev-running.md and the `ln1 gw-balance` command did not work. I did not see any relevant mention of "gateway" or "gw" when running `ln1 help`.
@dpc helped to point out there is the `gateway-cli` command, which led to this change.

Fix docs pointing to gw-balance, use gateway-cli instead

---

client/client-lib/src/api.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/core.rs
fedimint-api/src/core/server.rs
fedimint-api/src/db/mod.rs
fedimint-api/src/macros.rs
fedimint-api/src/module/mod.rs
fedimint-bitcoind/src/bitcoincore_rpc.rs
fedimint-bitcoind/src/lib.rs
fedimint-testing/src/bitcoind.rs
fedimint-testing/src/lib.rs
gateway/ln-gateway/src/client.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

This PR adds `Debug` to all dyn newtypes and `PartialEq` as well as `Hash` to the ones associated with modules (`Input`, `Output`, `OutputOutcome`, `ConsensusItem`).

Add traits to type-erased newtypes

---

Cargo.lock
fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-rocksdb/src/lib.rs
fedimint-sled/src/lib.rs
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs
gateway/ln-gateway/src/rpc/rpc_server.rs
gateway/tests/Cargo.toml
gateway/tests/tests/fixtures.rs
integrationtests/tests/fixtures/mod.rs

Apply TaskGroup control  to Gateway run function to allow for controlled shutdown of the gateway webserver and the main loop. A TaskGroup are injected into the `LnGateway` instance to allow shutdown by whoever created the gateway instance.
Part 3 of #938 
closes #919

Manage gateway run function using task groups

---

fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/encrypt.rs

Fixes #926 
Less chance for reusing nonces, even if there is a tiny chance of collision.

Use random nonce for config encryption

---

fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs

Fixes an intermittent issue (~10%) that stalls integration tests on `rejoin_consensus_single_peer`.
Appears that sometimes peers don't respond to the `RejoinConsensus` request, this will retry that request until responses are receive from all peers.

Fix rejoin consensus by resending requests

---

client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/transaction.rs
fedimint-api/src/core/server.rs
fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-api/src/module/mod.rs
fedimint-rocksdb/src/lib.rs
fedimint-server/src/consensus/mod.rs
fedimint-sled/src/lib.rs
fedimint-testing/src/lib.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

As a continuation of making the IDatabaseTransaction async, this PR makes remove_entry and rollback_to_savepoint async. This allows the executor to switch to a different thread in case some I/O is happening during remove_entry or rollback_to_savepoint.
I am only changing remove_entry and rollback_to_savepoint currently to keep the PR smaller and easier to review. The rest of the functions will be made async next.

Make remove_entry async in IDatabaseTransaction trait

---

modules/fedimint-wallet/src/lib.rs

When the federation is started nobody should know the descriptor yet, so nobody should have any peg-ins from the time before it was started. This means we don't really need to sync old block hashes.

Don't sync old block hashes when starting a new federation

---

fedimint-server/src/config.rs
fedimintd/src/bin/distributedgen.rs
modules/fedimint-wallet/src/config.rs
modules/fedimint-wallet/src/lib.rs

Since the config is encrypted now we need a way to change all the interesting configs.
fixes #977, related to #960

Allow setting the network to run on in `distributedgen`

---

gateway/ln-gateway/src/lib.rs

Handle errors from gateway attempt to load configs. Better error handling allows gateway startup to survive errors on attempt to load config

safe attempt to load previous gateway federation configs

---

fedimint-server/src/config.rs
fedimint-server/src/net/api.rs
fedimintd/src/ui/configgen.rs

Fixes #983 by increasing number of connections from 100 to 1000 and allowing them to be configurable.  Decreases the ping time to 10 sec to close dead connections.

increase number of client connections allowed

---

Cargo.lock
client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/transaction.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/core/server.rs
fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-api/src/module/mod.rs
fedimint-api/src/tiered_multi.rs
fedimint-rocksdb/src/lib.rs
fedimint-server/src/consensus/mod.rs
fedimint-sled/src/lib.rs
fedimint-testing/Cargo.toml
fedimint-testing/src/lib.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

This PR makes insert_entry and insert_new_entry asynchronous. This is part of the effort to move the database transaction trait to be entirely asychronous. https://github.com/fedimint/fedimint/issues/848

Make insert_entry and insert_new_entry asynchronous

---

gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/fixtures.rs
integrationtests/tests/fixtures/mod.rs

Define a standard client builder with
1) Composed  DB factories for behaviour adaptation.
- The client builder pattern supports standard client generation with shared logic to save / load gateway client configurations. This allows for easy swap out the db factory, determining what db the client builder provisions for clients. Example use case: [Quickly swap out rocks db for sled](https://github.com/okjodom/fedimint/pull/71/commits) to test deployments.
2) Generate client config from the builder
- Composing the config logic within client builder would allows us to mock gateway - federation network layer simply by swapping out the client builder. The client builder we use in production by default generates client configs and builds clients that hold a websocket connection between gateway …

Improve gateway client builder

---

client/cli/src/main.rs
client/client-lib/src/utils.rs

Switch to using consensus encoding/decoding for the CLI commands.
Fixes #994

Serialize e-cash tokens using our own encoding traits instead of bincode

---

fedimint-server/src/config.rs
fedimint-server/src/net/peers.rs

Figured I might as well do this tiny change, new logs look like:
```
022-11-29T18:56:14.350802Z  INFO fedimint_server::config: Peer 0 running distributed key generation...
2022-11-29T18:56:14.350802Z  INFO fedimint_server::config: Peer 1 running distributed key generation...
2022-11-29T18:56:14.355727Z  INFO fedimint_server::config: Peer 3 running distributed key generation...
2022-11-29T18:56:14.355728Z  INFO fedimint_server::config: Peer 2 running distributed key generation...
2022-11-29T18:56:18.336322Z  INFO fedimint_server::config: Distributed key generation has completed successfully!
2022-11-29T18:56:18.336469Z  INFO fedimint_server::config: Distributed key generation has completed successfully!
2022-11-29T18:56:18.336597Z  INFO fedimint_server::config: Distributed key generation …
```

small improvement to DKG logging

---

fedimint-api/src/module/mod.rs
fedimint-server/src/config.rs
fedimintd/src/bin/distributedgen.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Removes client config from DKG and fixes the peer names.
Fixes  #1016.

Don't generate client config in configgen

---

client/client-lib/src/api.rs
client/client-lib/src/query.rs
fedimint-server/src/lib.rs
scripts/lib.sh
scripts/reconnect-test.sh

There was a lot of flakiness in the reconnect tests that this should address, while also making them faster.  Also sets a max delay on client requests to 1sec.
Fixes #860 or at least improves it...if anyone encounters again please ping me.

fix issue that causes MissingPreviousEpoch error in CI

---

gateway/tests/tests/tests.rs

This fix attempts to use retries on the gateway rpc call. Should add minimal to zero overhead on the test suite since the tests succeed / fail on first attempt if the rpc made a successful gateway server connection.

Fix spurious gateway auth test failure?

---

client/client-lib/src/lib.rs
client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/backup/tests.rs
client/client-lib/src/mint/db.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/transaction.rs
fedimint-api/src/encoding/mod.rs
fedimint-api/src/tiered.rs
fedimint-api/src/tiered_multi.rs
fedimint-dbdump/src/main.rs
integrationtests/tests/tests.rs

This is to help e-cash recovery code to avoid problems with potential
attacks where an evil guardian could mint a different note
(with smaller) value using the same `BlindNonce`.
Previous the recovery code could derive nonces, but wouldn't know
what amount to expect for each of them, so would either have to
use the first occurence of a given nonce (possibly malicious) blindly,
or explicitily track possiblities of there being multiple ones,
and use the one with the higest value after some delay.
By deriving `BlindNonce`s independently for each amount, when generating
them we know exactly what amount to expect.
TODO:
First couple of commits are already in #1033 and can be landed independently.

Derive detereministic BlindNonces independently for each amount tier 

---

fedimint-server/src/config.rs
fedimintd/src/bin/configgen.rs
fedimintd/src/bin/distributedgen.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-mint/src/config.rs

Switching to denominations as powers of 2 to simplify code and reduce chance of errors.  More reasoning explained here https://github.com/fedimint/fedimint/issues/116#issuecomment-1332598851
Fixes #332, fixes #674

switch ecash denominations to powers of 2

---

client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/core.rs
fedimint-api/src/core/server.rs
fedimint-api/src/module/audit.rs
fedimint-api/src/module/interconnect.rs
fedimint-api/src/module/mod.rs
fedimint-server/src/consensus/interconnect.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/net/api.rs
fedimint-testing/src/lib.rs
fedimintd/src/bin/main.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-ln/tests/ln_contracts.rs
modules/fedimint-mint/src/db.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

related to #937 
By removing the database reference from the modules we avoid accidental misuse by reading from the database directly while writing to a transaction.

Remove `no_consensus_db` from modules

---

client/client-lib/src/lib.rs

This is useful for clients like Fluttermint to implement extra functionality without needing to modify Fedimint.

Client exposes reference to it's database

---

Cargo.lock
client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
fedimint-api/Cargo.toml
fedimint-api/src/config.rs
fedimint-server/src/config.rs
fedimintd/src/ui/configgen.rs
gateway/tests/tests/fixtures/client.rs

When downloading epochs, the client needs a `epoch_pk` to verify the epochs.

Add epoch_pk to ClientConfig

---

client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/db.rs
client/client-lib/src/mint/mod.rs
fedimint-dbdump/src/main.rs

This avoids skipping the note of the index 0, and aligns the "missing value" with `0`.

Rename LastEcashNoteIndex to NextEcashNoteIndex

---

client/client-lib/src/lib.rs
client/client-lib/src/mint/backup/tests.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/secrets.rs

In recovery code in certain functions I need a secret derived for the mint, and not the root secret. It's easy to mess up. Tracking the derivation level is an easy way to assert it in various places and avoid a mistake.

Track DerivableSecret's derivation level

---

client/client-lib/src/mint/mod.rs

Rename NotEnoughCoins to InsufficientBalance and include the requested amount and total balance in the error message.

Make NotEnoughCoins error more desriptive

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/backup/tests.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/config.rs
fedimint-api/src/lib.rs
fedimint-api/src/tiered_multi.rs
fedimint-server/src/config.rs
fedimint-testing/src/btc/fixtures.rs
fedimintd/src/ui/configgen.rs
gateway/ln-gateway/src/cln.rs
gateway/ln-gateway/src/rpc/rpc_server.rs
integrationtests/tests/fixtures/fake.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs
integrationtests/tests/tests.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-ln/tests/ln_contracts.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Get rid of very long `Amount::from_millis_sat`.
Make the `from_msats` and `from_sats` plural. Just like e.g. [Duration::from_secs](https://doc.rust-lang.org/std/time/struct.Duration.html#method.from_secs) .
Move `msats` and `sats` to `fedimint-api`. Seem commonly needed in all test code, to justify it.
Did NOT go around the code and change existing `Amount::from_x` usage. Maybe some other time.
Pushback and bikeshedding welcome and appreciated.

Streamline `Amount` usage

---

client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
fedimint-api/Cargo.toml
fedimint-api/src/tiered_multi.rs
integrationtests/tests/tests.rs
scripts/latency-test.sh

Modifies the algorithm for picking ecash denominations so that we try to target having 1 sets of every denomination.  This makes it easier to send ecash offline and also improves the anonymity sets.  There is an increase in tx time given the number of notes to sign:
> Greedy algorithm
> AVG REISSUE TIME: 1.749 seconds
> AVG LN SEND TIME: 1.853 seconds
> AVG LN RECEIVE TIME: 2.456 seconds
> 
> Denom sets = 1
> AVG REISSUE TIME: 1.693 seconds
> AVG LN SEND TIME: 3.822 seconds
> AVG LN RECEIVE TIME: 3.333 seconds
> 
> Denom sets = 2
> AVG REISSUE TIME: 1.960 seconds
> AVG LN SEND TIME: 4.343 seconds
> AVG LN RECEIVE TIME: 3.742 seconds
> 
> Denom sets = 3
> AVG REISSUE TIME: 2.243 seconds
> AVG LN SEND TIME: 5.475 seconds
> AVG LN RECEIVE TIME: 3.965 seconds
Fixes #962

modify change algorithm to favor denomination sets

---

client/client-lib/src/mint/mod.rs

I need it for e-cash recovery. I initially thought that I'll have to store it as an extra field, but Eric told me that it can be calculated, which is even better.

 Add a method to recover BlindNonce from NoteIssuanceRequest 

---

fedimint-api/src/lib.rs
fedimint-server/src/lib.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
scripts/reconnect-test.sh
scripts/start-fed.sh

Simplifies and fixes bugs in the reconnect logic.  The new logic works as follows:
1. When starting consensus, skip to the last saved epoch history and trigger a new epoch
2. If a threshold of peers is working on a future epoch, skip to that epoch + 10, triggering 10 empty epochs
3. If consensus produces a valid outcome and it's ahead of our last processed epoch, then download epochs until we catch up (validating the hashes/signatures)
I think this is a much more elegant solution and should be more robust than the crazy reconnect logic I had previously written.
Fixes ##1039

Simplify the reconnecting logic

---

flake.lock
flake.nix

This should improve Nix build speed when compressing artifacts, especially on machines with a lot of CPU cores. Nothing major, but these seconds add up.
In addition, this upgrades us from v0.7 to v0.10, which had some minor improvements ([including perf improvements](https://github.com/ipetkov/crane/issues/161)) along the way.

Update `crane` to include multi-threaded `zstd` compression

---

client/client-lib/src/lib.rs
client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/backup/tests.rs
client/client-lib/src/mint/db.rs
client/client-lib/src/mint/mod.rs
modules/fedimint-mint/src/lib.rs

Follow-up to #1015 
Add some basic infra to allow reasonable code to test recovery logic, and a first test to validate the approach.
Also, store unsigned notes in the backup and add code to handle them during recovery.

Add testing infra. and first unit-test for e-cash recovery 

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/core.rs
fedimint-api/src/core/client.rs
fedimint-api/src/core/server.rs
fedimint-api/src/lib.rs
fedimint-api/src/module/mod.rs
fedimint-core/src/lib.rs
modules/fedimint-ln/src/common.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-ln/tests/ln_contracts.rs
modules/fedimint-mint/src/common.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/common.rs
modules/fedimint-wallet/src/lib.rs

* Don't pollute heap with many small allocations of decoders, make them `&'static dyn` instead (easy since they are ZSTs)
* Remove decode impl from `IServerModule` and `IClientModule`
* Add `decoder` fn to `IClientModule` the get the module's decoder

Decoder cleanup

---

docs/gateway.md
gateway/cli/src/main.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs
gateway/ln-gateway/src/rpc/rpc_client.rs
gateway/ln-gateway/src/rpc/rpc_server.rs
gateway/tests/tests/tests.rs
integrationtests/tests/fixtures/mod.rs
scripts/lib.sh
scripts/tmux-user-shell.sh

Differentiate the gateway api used to connect a federation, from the federation api used to register a connected gateway client
- `connect_federation()` is a public gateway API : It can be used by authorised person gateway admin to propose a federation to the gateway
- `register_with_federation()` is a gateway client API that calls back into the federation when connect federation api is used

Rename: Differentiate connect federation  from gateway `register_with_federation`

---

client/client-lib/src/lib.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs

Gateway save federation config would `File::open` an existing config in readonly mode, then fail to ovewrite the content.
This fix introduces an explicit panic on attempts to re-register the same federation with a changed config.
Long term, we should look into [Safe persistence and migration of gateway federation config](https://github.com/fedimint/fedimint/issues/1057)

Fix: Gateway fails to save federation config if one already exists #1056

---

fedimintd/src/ui/configgen.rs

Missed this when I removed client config gen from DKG.  Should fix #1016

don't generate client config in trusted setup

---

Cargo.lock
Cargo.toml
client/cli/src/main.rs
client/client-lib/src/api.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/secrets.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/db/mod.rs
fedimint-api/src/tiered_multi.rs
fedimint-dbdump/src/main.rs
gateway/tests/tests/fixtures/fed.rs
modules/fedimint-mint/Cargo.toml
modules/fedimint-mint/src/config.rs
modules/fedimint-mint/src/db.rs
modules/fedimint-mint/src/lib.rs

This commit adds:
* `backup`
* `restore`
* `wipe-notes` (hidden)
I tested it in various sequences and it seems to work now.
[Things to follow-up with are being tracked](https://github.com/fedimint/fedimint/issues/502#issue-1363756545).
To give a feel how it works:
```
dpc@mutex:~/lab/fedimint.git/mod$ fedimint-cli info
{
"total_amount": 80000000,
"total_num_notes": 56,
"details": {
"1": 2,
"2": 1,
"4": 1,
"8": 1,
"16": 1,
"32": 1,
"64": 1,
"128": 1,
"256": 5,
"512": 1,
"1024": 5,
"2048": 5,
"4096": 1,
"8192": 5,
"16384": 1,
"32768": 1,
"65536": 5,
"131072": 1,
"262144": 1,
"524288": 1,
"1048576": 5,
"2097152": 5,
"4194304": 1,
"8388608": 1,
"16777216": 3
}
}
dpc@mutex:~/lab/fedimint.git/mod$ fedimint-cli wipe-notes
null
dpc@mutex:~/lab/fedimint.git/mod$ fedimint-cli info
{
"total_amount": …
```

Implement `fedimint-cli backup` and `restore`

---

client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/config.rs
fedimint-api/src/module/mod.rs
fedimint-server/src/config.rs
fedimint-testing/src/lib.rs
fedimintd/src/ui/configgen.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-ln/tests/ln_contracts.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

The config generation is not fully modularized yet. As a first step this PR builds a typed API to access configgen params from module configgen.

Build typed configgen parameters API

---

fedimint-api/src/config.rs
fedimint-server/src/config.rs
fedimintd/src/ui/configgen.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/config.rs
modules/fedimint-wallet/src/lib.rs

In preparation for #960 I will first add the local, private, and consensus types to all the configs and json logic.
Next step will be to break the configs up into structs representating those fields and write them to different files.  I'd like to do this in a separate PR since it will involve a large refactor.

Refactor the configs to be prepared for splitting them

---

.github/workflows/ci-nix.yml
flake.nix

I think this got broken when I've upgraded crane in #1081 as the behavior of `doCheck` have changed between releases.

Fix nix-ci not running `cargo test`

---

replit.nix

without this, it was failing with
invalid linker name in argument '-fuse-ld=lld'
Hi, I saw your tweet https://twitter.com/_JustinMoon_/status/1602728750617169920 . I tried out importing this into Replit and I found this problem. Looks like there are still more problems though because it gets a lot further and then I see:
```
Checking mint-client v0.1.0 (/home/runner/fedimint/client/client-lib)
error[E0632]: cannot provide explicit generic arguments when `impl Trait` is used in argument position
--> client/client-lib/src/api.rs:285:24
|
285 |             .request::<_, SerdeEpochHistory>("/fetch_epoch_history", epoch, qs)
|                        ^  ^^^^^^^^^^^^^^^^^ explicit generic argument not allowed
|                        |
|                        explicit generic argument not …
```

replit: add lld package

---

fedimint-server/src/config.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs
fedimintd/src/bin/configgen.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/encrypt.rs
fedimintd/src/lib.rs
fedimintd/src/ui/configgen.rs
fedimintd/src/ui/mod.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
scripts/cli-test.sh

Splits the `ServerConfig` into local, private, and consensus files, with only the private file encrypted.
Leaving the modules for another PR.

Splits configs into local, private, and consensus files

---

Cargo.lock
Cargo.toml
client/client-lib/Cargo.toml
client/client-lib/src/mint/backup.rs
crypto/aead/Cargo.toml
crypto/aead/src/lib.rs
fedimintd/Cargo.toml
fedimintd/src/encrypt.rs
flake.nix

I'm going to need to use it another place soon, so it makes sense to unify now.
Since it's being used from unrelated places, I don't see any other way than a separate crate.

Move aead wrappers around ring to separate crate

---

README.md

This way we don't need to think about multiple links. Just keep that one redirect working.

Use chat.fedimint.org for the discord link in README

---

fedimint-api/src/tiered_multi.rs

https://github.com/fedimint/fedimint/actions/runs/3742643786/jobs/6353843599

Fix clippy warning that somehow only appears in the mac builds

---

crypto/aead/src/lib.rs

I have forgot to remove the tag at the end and somehow this is revealed only when using tmuxinator. Possibly because most of the stuff we use it for uses encoding that tolerate trailing bytes.

Fix `decrypt` in the new `crypto/aead` crate

---

fedimint-server/src/config.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs
fedimint-server/src/net/connect.rs
fedimint-server/src/net/peers.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/ui/configgen.rs
scripts/build.sh

Moving URLs into consensus config, so that we can generate the client configs from the consensus configs.
The only disadvantage is that we cannot do rolling updates of the URL values, instead we need to update all at once, but that's an ability we'll need anyway since we will inevitably have to handle consensus-breaking code updates on a regular basis and once we have a P2P DNS we won't have to worry about domains at all

Move URLs into consensus config

---

scripts/build.sh

We have a user reporting problems that look
like hitting the unix named socket limit:
```
thread 'main' panicked at 'connect to ln_socket: path must be shorter than libc::sockaddr_un.sun_path'
```
It's unclear why exactly would they hit the limit - there
still seems to be some room left, but one way or another,
it seems like a good idea to keep the $TMP as short as possible,
even if just for more compact debug outputs.

tmuxinator: Keep $TMP shorter when in nix shell

---

client/client-lib/src/mint/db.rs
client/client-lib/src/mint/mod.rs
docs/database.md
fedimint-api/src/tiered_multi.rs
fedimint-dbdump/src/main.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-mint/src/lib.rs

Enforce max notes per denomination per output.  We should probably enforce max outputs per tx as well.
Lets clients configure the notes per denomination via a DB entry instead of the config file (which should be immutable).
Related to #1141

enforce max notes per denominations

---

fedimint-api/src/config.rs
fedimint-server/src/config.rs
fedimint-server/src/net/api.rs
fedimintd/src/lib.rs
fedimintd/src/ui/configgen.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/config.rs
modules/fedimint-wallet/src/lib.rs

Derives the client config from consensus config, so that we can be assured that the client config returned is the same for all guardians.

Derive the client config from consensus config

---

scripts/tmuxinator.sh

`set -u` causes expansion of unset variable to fail completely, instead of printing a message.
Using `...` causes `nix develop` to be actually run, which is confusing.

tmuxinator: Fix nix shell env detection

---

Cargo.lock
fedimint-api/Cargo.toml
fedimint-api/src/encoding/mod.rs

There are instances where we want to be able to use types that implement `serde` serialization in `Encodable` contexts.
In such cases, let's just use some binary encoding to do the job.

Implement `Encodable` newtype-wrapper for `Serializable` types

---

Cargo.lock
fedimint-api/src/module/mod.rs
fedimint-server/src/config.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs
fedimintd/Cargo.toml
fedimintd/src/bin/configgen.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/lib.rs
fedimintd/src/ui/configgen.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Get rid of some hardcodings listing federation modules deep inside generic code, and move toward edges (final binaries), so it's easier to customize/inject new modules.
There's probably a lot more work to do around it, but it's a step towards the goal, I think.

Use `FederationModuleConfigGen` to manipulate module configs

---

fedimintd/src/encrypt.rs

It currently interferes when trying set a variable on the command line:
```
$ CERTS=$(distributedgen create-cert --password password  ...)
$ echo $CERTS
WARNING: Passing in a password from the command line may be less secure! ws://hostname@5000@bravo@3082012c3081d3a003020102020900bd1e155b36b28c21300a06082a8648ce3d0403023010310e300c06035504030c05627261766f3020170d3735303130313030303030305a180f34303936303130313030303030305a3010310e300c06035504030c05627261766f3059301306072a8648ce3d020106082a8648ce3d0301070342000463bb130366f89390e559fe201726f29fc31dfdddf562d4e76183504adf711d322be1b03d61dfe54c13eaa7131fcc098dc7487da1cd7407e06ec5918501cfc465a314301230100603551d11040930078205627261766f300a06082a8648ce3d0403020348003045022100abd5a4ffefc7d707c224fda39596292430d8847cdbefc7f20dc71e7a4b2e936202204d272 …
```

Print warning to stderr

---

client/client-lib/src/lib.rs

Stole this code from @elsirion. Without this commit my gateway cannot pay invoices generated by Muun. With it, it can.
Made it a draft because I don't totally understand why it works. Could you explain @elsirion? Is there a better approach here?

Increase outgoing lightning contract timeout

---

scripts/lib.sh
scripts/tmux-user-shell.sh
scripts/tmuxinator.sh

When running the repo locally using ./scripts/tmuxinator.sh script, I noticed that it it did not work and got stuck in the lightning channel setup. Diagnosing the issue needed me to remove the /dev/null output redirection in the scripts, so I could see what is going on under the hood.
Besides diagnosis, I believe it might also be useful for new people, unfamiliar with the underlying lightning interactions, to be able to see more verbose output of what the scripts are doing for learning purposes.
This PR adds a flag that conditionally shows or suppresses this output from dependent processes.

Add verbose output flag

---

Cargo.lock
flake.nix
gateway/ln-gateway/Cargo.toml
gateway/ln-gateway/build.rs
gateway/ln-gateway/proto/gatewaylnrpc.proto

#1103 proposes an architecture that decouples the gateway logic from the node used to process lightning payments. From that proposal, we need to define an RPC interface between the gateway and the node. This PR is an early definition for such an RPC interface using [gRPC](https://grpc.io/) protocol buffers ([proto3](https://grpc.io/))

Define gateway to node rpc in proto3 spec

---

flake.nix
scripts/start-containers.sh

This PR is an extension of https://github.com/fedimint/fedimint/pull/702/files that adds a docker compose file to start a federation. This PR adds a simple bash script to generate the docker compose files that do DKG and run the federation.
Right now, for developer environment there is not much advantage to creating a federation this way vs tmux. The main advantage is not needing to download the build tools (nix) in an environment where bandwidth might be an issue (such as tabconf). Pulling the containers might not be much faster though. Images can optionally be built using nix.
I mainly did this as an exercise to practice the steps necessary for setting up a federation, and since docker creates its own virtual network, its a bit more "real" since it doesn't rely on localhost.
Currently …

Bash script to start federation with containers

---

fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-rocksdb/src/lib.rs
fedimint-sled/src/lib.rs
fedimint-sqlite/src/lib.rs

Small PR that introduces tests for remove_by_prefix and a native implementation for SQLite.
It looks like the existing default implementation for Rocksdb is the most efficient it currently supports. See comment here: https://github.com/fedimint/fedimint/issues/1111

remove_by_prefix for SQLite

---

fedimint-server/src/config.rs
fedimint-server/src/net/api.rs
fedimint-server/src/net/connect.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/ui/configgen.rs
integrationtests/README.md
integrationtests/tests/fixtures/mod.rs
scripts/build.sh
scripts/start-containers.sh

Now the URLs / bind addresses for the server and API endpoints will be independently configurable, using default ports `4000` and `4001`.  DKG will use the server endpoints.
Fix #1188

Removes the port offsets from DKG

---

integrationtests/tests/fixtures/mod.rs
scripts/build.sh

Avoids conflicts with `fedimintd` itself, which someone might want to run locally while running tmuxinator/tests, and with other random apps (currently we are hitting `syncthing` ports).

Add `10000` to test setup base port to avoid conflicts

---

fedimintd/Cargo.toml
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/encrypt.rs
scripts/build.sh
scripts/cli-test.sh
scripts/start-containers.sh
scripts/start-fed.sh

Supports passing in passwords with environment variables which is safer than command-line.  Can still prompt users if the environment var is not set.
Fix #1176

Convert the password to an env var

---

scripts/build.sh

Altough the nix shell tmp dir is unique, if you crash tmuxinator, it will leave previous files around which might get in a way.

tmuxinator: Append random string to nix tmp dir

---

.tmuxinator.yml
docs/gateway.md
gateway/cli/src/main.rs
scripts/lib.sh

Port 8080 is somewhat common. Helps with  #1199. 8175 is one above the defaults ports used by `distributedgen`. I didn't test this manually at all.

Change gateway webserver default port to 8175

---

fedimint-api/src/core.rs
fedimint-api/src/core/client.rs
fedimint-api/src/core/server.rs

`'static` is already required by `Any`.
If there was a deeper thought behind stating this explicitly, please tell

Remove unnecessary static bound

---

fedimintd/templates/params.html

String serialization of `bitcoin::Network::Bitcoin` is `bitcoin`, not `mainnet`. When setting up our test federation yesterday @m1sterc001guy and I had to edit the HTML manually to `bitcoin` but then it worked.

Fix incorrect string serialization of bitcoin::Network::Bitcoin

---

fedimint-api/src/core.rs
fedimint-api/src/core/server.rs

`Decoder` is an associated type in `ServerModulePlugin` and refers to `PluginDecode`.
This only moves the bounds. There is not functionality added or removed.

Move PluginDecode trait bounds to definition

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/fixtures/client.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/src/lib.rs

For every Federation connected, the gateway deterministically generates and assigns a channel identifier. Clients within these federations use the channel id as `short_channel_id` in every generated invoice, thus allowing the Gateway to easily identify which federation it should settle a payment on behalf of.
For full context, see these discussions:
- https://discord.com/channels/915026692102316113/915026887066132481/1058487466786574389
- https://discord.com/channels/990354215060795454/996329365329686559/1058247253594218618

Introduce gateway channel IDs for federations

---

fedimint-api/src/config.rs
fedimint-server/src/config.rs
fedimint-server/src/lib.rs

After some back and forth, we realized that p2p urls/certs can be locally configured, while client-server endpoints will remain in consensus for now.  Renaming our existing `Node` and `Peer` structs with more informative names.

Move p2p urls/certs to local config

---

scripts/cli-test.sh
scripts/lib.sh
scripts/pegin.sh

@NicolaLS discovered `cli-test.sh` was silently failing due to passing in the fed name as id (which now needs to be a hex pubkey).

Fix failing cli-test.sh

---

gateway/ln-gateway/proto/gatewaylnrpc.proto

Inspired by [this discussion](https://github.com/fedimint/fedimint/pull/1224#discussion_r1064215899). Allows lnrpc clients used by `gatewayd` to batch pay invoice operations and stream them to `pay_invoice`

request payment of multiple invoices in a stream

---

fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
flake.nix
misc/fedimintd-container-entrypoint.sh

Test with:
```sh
nix build .#container.fedimintd
docker load < result
docker run -e FM_PASSWORD=password -e FM_DATA_DIR=/data -v $PWD/data:/data -p 8173:8173 -p 8174:8174 -p 8175:8175 -it fedimintd:container-tag-from-previous-command
xdg-open http://localhost:8175/
```
Once it lands it should be just:
```sh
docker run -e FM_PASSWORD=password -e FM_DATA_DIR=/data -v $PWD/data:/data -p 8173:8173 -p 8174:8174 -p 8175:8175 -it fedimint/fedimintd:master
```
Seems to work, but there's bunch of things I'd like to do before this works well.
Created #1251 for some follow-ups.

Initial one-"docker run"-command docker image

---

gateway/ln-gateway/proto/gatewaylnrpc.proto
gateway/ln-gateway/src/lib.rs

Improve upon [GatewayLightning](https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/proto/gatewaylnrpc.proto#L17:L19) `subscribe_intercept_htlcs` by defining a corresponding `complete-htlc` [client streaming rpc](https://grpc.io/docs/what-is-grpc/core-concepts/#client-streaming-rpc) for responding to intercepted and processed htlcs
- For every new federation connected, the gateway sends a `subscribe_intercept_htlcs` RPC to **request for HTLC interception**. This opens a stream over which intercepted HTLCs are sent to the client:
```
// example
let subscription = SubscribeInterceptHtlcsRequest { short_channel_id: u64 };
let stream = client.subscribe_intercept_htlcs(Request::new(subscription)).await?;
```
- For every HTLC intercepted and processed by the gateway:
- Use …

RPC for settling or canceling intercepted HTLCs after gateway processing

---

fedimint-server/src/config.rs
integrationtests/tests/fixtures/mod.rs
scripts/build.sh

Closes #1263
I just don't think injecting a default port is useful or needed. Eric and I just setup a federation via UI and were surprised that a port was injected into the URL we put into the UI.

Don't inject a default port into API URLs

---

README.md

I just noticed that the discord link under the bullet points does not work. (the badge works). 
I changed it to the same URL as in the badge: chat.fedimint.org

Update developer discord link

---

client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-dbdump/src/main.rs
fedimint-rocksdb/src/lib.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimint-sled/src/lib.rs
fedimint-sqlite/src/lib.rs
fedimint-testing/src/lib.rs
fedimintd/src/bin/main.rs
gateway/ln-gateway/src/client.rs
gateway/tests/tests/fixtures/client.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/tests/ln_contracts.rs
modules/fedimint-wallet/src/lib.rs

Store ModuleDecoderRegistry inside Database, so it doesn't need to be supplied begin_transaction.
Split off from #1197

database: store module decoders inside database

---

fedimintd/src/ui.rs
fedimintd/templates/params.html

Have had a problem where setup UI can spawn 2 instances of DKG if the "/post_federation_params" form needs to be submitted multiple times (e.g. you realize that someone pasted in the wrong set of connection strings). Second one will fail to bind to the port, because DKG server from first one is still running there.
Not sure if this is the best approach, but it does fix this particular problem.
In a perfect world we'd start DKG server without yet telling it what connection strings to use. Then we could send it connection strings -- multiple times if necessary. So there wouldn't be any risk of binding to the port twice.

Avoid setup UI port collisions

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/backup/tests.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/core.rs
fedimint-api/src/core/client.rs
fedimint-api/src/core/encode.rs
fedimint-api/src/core/server.rs
fedimint-api/src/module/mod.rs
fedimint-api/src/module/registry.rs
fedimint-core/src/epoch.rs
fedimint-core/src/outcome.rs
fedimint-core/src/transaction.rs
fedimint-server/src/consensus/mod.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-dummy/src/common.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/common.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/common.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/common.rs
modules/fedimint-wallet/src/lib.rs

part of #1232
The `ModuleConsensusItem` still contains `Module` as there is the `ConsensusItem` enum as well. But I think one could work around that and just rename that enum either in the definition or when importing it (if `ModuleConsensusItem` should be renamed to `ConsensusItem`.

Rename symbols around modules

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
fedimint-api/src/module/mod.rs
fedimint-core/src/outcome.rs
fedimint-core/src/transaction.rs
fedimint-dbdump/src/main.rs
fedimint-server/src/config.rs
fedimint-testing/src/lib.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/distributedgen.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-ln/tests/ln_contracts.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

part of #1232
First commit renames `ModuleInit` to `ModuleGen` and moves the `try` to the front of the function `try_to_client_config`.
Second commit removes `Module` from `Lightning*` symbols. 
Happy to change or revert anything.

Renames in lightning module and ModuleInit

---

gateway/ln-gateway/src/lib.rs

It's definitely not an incoming invoice that this fn processes. I'd like to call it `handle_intercepted_htlc`, but I see how that might not get the high level functionality across as well (and would require more renames of structs).

Rename intercepted HTLC handler function

---

fedimint-api/src/db/mod.rs
fedimint-api/src/fmt_utils.rs
fedimint-api/src/lib.rs

Without some kind of abbreviation reading through log outputs is going to be painful, and usually first bytes are the most significant ones.

Fix logging a lot of raw byte debug strings in certain places

---

fedimint-api/src/core.rs
fedimint-api/src/module/mod.rs
fedimint-dbdump/src/main.rs
fedimint-server/src/config.rs
fedimint-testing/src/lib.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/distributedgen.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

part of #1303
- creates an `IModuleGen` for `ModuleGen` and the blanket impl
- `ModuleGen` is now the typed trait with associated types

Create interface for module generation trait

---

client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-dbdump/src/main.rs
fedimint-server/src/config.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/distributedgen.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-ln/tests/ln_contracts.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

folluw up for #1314  @dpc , also ACK @elsirion ?
Renaming the `MintConfigGeneration` to `MintGen` for consistency with `ModuleGen`.
Same for `MintConfigGenerationParams` -> `MintGenParams`.
same applies to the other modules.

Rename module generation structs for `ModuleGen` consistency

---

fedimint-api/src/config.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

- `ModuleConfigGenParams` to `ModuleGenParams`
follow up for #1320

Rename for consistency with `ModuleGen`

---

Cargo.lock
crypto/derive-secret/Cargo.toml
crypto/derive-secret/src/lib.rs
crypto/tbs/Cargo.toml
crypto/tbs/examples/keygen.rs
crypto/tbs/src/serde_impl/mod.rs
crypto/tbs/src/serde_impl/scalar.rs

part of #1307 
I couldn't put this part into one line. Not exactly sure why.
```rust
// current state
let deser: String = Deserialize::deserialize(d)?;
Vec::<u8>::from_hex(&deser).map_err(serde::de::Error::custom)?
// does compile but tests fail:
Vec::<u8>::from_hex(Deserialize::deserialize(d)?).map_err(serde::de::Error::custom)?
```
example test failure message: 
```
---- set_lightning_invoice_expiry stdout ----
thread 'set_lightning_invoice_expiry' panicked at 'configuration mismatch: invalid type: string "a7d06980c1c68997f040d35e2abc52d1a30eb1dd760c607ca53d7089fffcc55ff737b7e7c641b1c5c226d20023290a0d0c6cc12c95da3c5f9c19480ae2f079cf483d71f55c0fbb386659df645482840468927fed439226d51ab7a8fd2d882445", expected a borrowed string', fedimint-server/src/config.rs:180:14
```

Remove `hex` dependency from crypto crates

---

client/client-lib/src/mint/mod.rs
integrationtests/tests/tests.rs

Closes #1319
When creating lightning offers, we request zero change, which adds a zero amount output.

Don't create zero amount change ouputs

---

scripts/build.sh

It might resolve to eitherr 127.0.0.1 or ::1 , which can create an issue on some systems.
(Reported by FreeAltoid on Discord)

Do not use `localhost`

---

fedimint-server/src/config.rs
integrationtests/tests/fixtures/mod.rs
scripts/setup-tests.sh

Running integration tests with real fixtures currently has two problems:
1. Environment variables are not passed to the wallet module, causing the RPCs to bitcoind to fail.
2. The task group running DKG is not shut down causing a port conflict when running the federation.
This PR fixes both by setting the regtest bitcoin connection address, passing the environment variables to the wallet module, and shutting down DKG so the federation can re-use the port.

Fix integration tests with real fixures

---

fedimint-server/src/net/api.rs

this is no longer needed because use `SerdeTransaction` now.
earlier some types from hbbft could not be deserialized directly.

cleanup: remove serialize to string and deserialize hack

---

fedimint-api/src/fmt_utils.rs

LocalKey::with executes the closure everytime :shrug: 
thread_local is lazy by default. So we can do non const initialization.

fix: rust_log_full_enabled check env var only once

---

Cargo.lock
client/cli/src/main.rs
client/client-lib/src/api.rs
client/client-lib/src/api/fake.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/query.rs
client/client-lib/src/utils.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/macros.rs
fedimint-server/src/lib.rs
fedimint-testing/src/lib.rs
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/Cargo.toml
gateway/tests/tests/fixtures/client.rs
gateway/tests/tests/fixtures/fed.rs
gateway/tests/tests/fixtures/mod.rs
gateway/tests/tests/tests.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

List of follow-ups (before lands):
List of follow-ups (after lands):
Close  #1169

Change how the `IFederationApi` works

---

Cargo.lock
client/client-lib/Cargo.toml
client/client-lib/src/mint/mod.rs
client/client-lib/src/utils.rs
fedimint-api/src/config.rs
fedimint-api/src/db/mem_impl.rs
fedimint-api/src/fmt_utils.rs

part of #1307
more work to remove the `hex` dependency crate. I can't remove the hex dependency in cargo.toml in `fedimint-api` yet as it is needed because the mint module uses it.
used [here](https://github.com/fedimint/fedimint/blob/8d4ef26a814e53ba7012b1b50fb3afec4382c920/modules/fedimint-mint/src/common.rs#L17) and [here](https://github.com/fedimint/fedimint/blob/8d4ef26a814e53ba7012b1b50fb3afec4382c920/modules/fedimint-mint/src/db.rs#L158)
example: 
```rust
#[derive(Debug, Serialize, Deserialize, Encodable, Decodable)]
pub struct BackupRequest {
pub id: secp256k1::XOnlyPublicKey,
#[serde(with = "hex::serde")]
pub payload: Vec<u8>,
pub timestamp: std::time::SystemTime,
}
```
thoughts on replacing this? writing a deserialize and serialize function for `Vec<u8>` that de/serializes to …

Replace uses of `hex` dependency

---

Cargo.lock
fedimintd/Cargo.toml
fedimintd/src/ui.rs
gateway/cli/Cargo.toml
gateway/ln-gateway/Cargo.toml

Also bumps dependencies that need to stay in lock step.
If we don't want yet another git dependency we are blocked on https://github.com/djc/askama/pull/758 making it into a release, which [might happen soon though](https://github.com/djc/askama/issues/757#issuecomment-1378025890).
Closes #1009

Bump axum from 0.5.17 to 0.6.2

---

fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/rng.rs

RNG generators were introduced to allow usage of RNGs in rayon parallel iterators when processing transactions. Since then tx processing has been de-parallelized, making RNG gens obsolete.
Fixes #79 (thx @dpc for the archeological work recovering this issue)

fix: remove dead RNG generator code

---

Cargo.lock
client/client-lib/src/api.rs
fedimint-api/Cargo.toml
fedimint-api/src/config.rs
fedimint-api/src/encoding/btc.rs
fedimint-api/src/encoding/mod.rs
fedimint-api/src/encoding/tbs.rs
fedimint-api/src/module/mod.rs
fedimint-server/Cargo.toml
fedimint-server/src/config.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs
fedimint-testing/src/lib.rs
fedimintd/src/lib.rs
gateway/ln-gateway/src/client.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy/src/config.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/config.rs
modules/fedimint-wallet/src/keys.rs
modules/fedimint-wallet/src/lib.rs

Makes consensus and client configs implement `Encodable` so they can be deterministically hashed and validated.
Adds the consensus hash and an API endpoint for retrieving it with the client config (next step will be to save and return the signed hash of the client config).
Fixes #950, will be used to solve #1262

Add and verify consensus config hash

---

Cargo.lock
client/client-lib/src/api.rs
fedimint-api/Cargo.toml
fedimint-api/src/config.rs
fedimint-api/src/encoding/btc.rs
fedimint-api/src/encoding/mod.rs
fedimint-api/src/encoding/tbs.rs
fedimint-api/src/module/mod.rs
fedimint-server/Cargo.toml
fedimint-server/src/config.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs
fedimint-testing/src/lib.rs
fedimintd/src/lib.rs
gateway/ln-gateway/src/client.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy/src/config.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/config.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/config.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/config.rs
modules/fedimint-wallet/src/keys.rs
modules/fedimint-wallet/src/lib.rs

This reverts commit 7299e5e6ff22991975164654e321e1477fd18754.
We had cli tests disabled in CI, and it seems to affect both tmuxinator and cli tests.
Let's revert while we're trying to get it under control.

Revert "Add and verify consensus config hash (#1281)"

---

gateway/cli/src/main.rs
gateway/ln-gateway/src/config.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/tests.rs
integrationtests/tests/fixtures/mod.rs
scripts/lib.sh

Since we don't fully support multiple federations, we need to *guess* the intended destination actor for every incoming payment received via intercepted htlc. This pr removes any reference of `default_federation` in gateway configs, and instead, picks a listed actor in the gateway, then attempts to settle payment into the federation represented by this actor.
#1337 proposes a long term fix for this issue, by actively streaming intercepted htlcs into a subscribing actor, therefore avoiding the need to select actors for every intercepted htlc
See #664 for details on supporting multiple federations

Receive HTLC to default fed

---

integrationtests/tests/fixtures/mod.rs
scripts/latency-test.sh
scripts/lib.sh

This is my best guess at why `lightning_gateway_claims_refund_for_internal_invoice` fails sometimes. https://github.com/fedimint/fedimint/issues/222#issuecomment-1385766750

Make fixture initializer wait for gateway being registered

---

client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/backup/tests.rs
client/client-lib/src/mint/mod.rs
fedimint-dbdump/src/main.rs
integrationtests/tests/tests.rs
modules/fedimint-mint/src/common.rs
modules/fedimint-mint/src/db.rs
modules/fedimint-mint/src/lib.rs

part of #1342
The first commit does renames agreed upon in #1342 .
The second commit renames `OutputConfirmationSignatures` to `MintOutputSignatureShare`. according to the comment above the struct, it will contain (at some point) only the `tbs::BlindedSignatureShare` and the `tbs::BlindedMessage` will be remembered by the mint. If you don't agree I remove the second commit.
```rust
// FIXME: optimize out blinded msg by making the mint remember it
/// Blind signature share from one Federation peer for a single [`MintOutput`]
#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct MintOutputSignatureShare(
pub TieredMulti<(tbs::BlindedMessage, tbs::BlindedSignatureShare)>,
);
```
thoughts @dpc @elsirion 
--- 
I rebased this branch on #1389, …

Renames in mint module

---

fedimint-api/src/config.rs
fedimint-api/src/encoding/mod.rs
fedimint-core/src/epoch.rs
fedimint-derive/src/lib.rs
fedimint-server/src/config.rs
fedimint-server/src/lib.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/common.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Clean-up that adds an `encodable_ignore` and `consensus_hash` to `Encodable`.
This simplifies some of our code and allows `ServerConsensusConfig` to automatically pick up new fields in `Encodable`

Adds encoded ignore and hashes to remove some duplication

---

Cargo.lock
fedimint-api/Cargo.toml
fedimint-api/src/hex/mod.rs
fedimint-api/src/hex/serde.rs
fedimint-api/src/lib.rs
fedimint-dbdump/Cargo.toml
fedimint-dbdump/src/main.rs
modules/fedimint-mint/Cargo.toml
modules/fedimint-mint/src/common.rs
modules/fedimint-mint/src/db.rs

part of #1307 
the serialize and deserialize functions are specific to `Vec<u8>` but I think that works so far. 
thoughts? is it ok like this or should be more generic? 
@dpc @elsirion

Add our own hex::serde implementation

---

.tmuxinator.yml
gateway/ln-gateway/src/bin/cln_extension.rs

Misconfigured the listen address on new `gateway-cln-extension` introduced by #1295. The node already has an `addr` config, so we need a new name for the bind address config we define on the extension
```
lightningd --dev-fast-gossip --dev-bitcoind-poll=1 --network regtest --bitcoin-rpcuser=bitcoin --bitcoin-rpcpassword=bitcoin --lightning-dir=$FM_LN2_DIR --addr=127.0.0.1:9001 --plugin=$FM_BIN_DIR/gateway-cln-extension
2023-01-19T16:43:13.617Z INFO    lightningd: Creating configuration directory /tmp/nix-shell.WruqEt/fm-SxxT/ln2/regtest
error starting plugin '<path>/fedimint/target/debug/gateway-cln-extension': option name '--addr' is already taken
thread 'main' panicked at 'Failed to create cln rpc service: Error(Failed to start cln plugin)', …
```

fix: config listen address on gateway-cln-extention

---

fedimint-dbdump/src/main.rs
fedimint-server/src/config.rs
fedimint-server/src/consensus/mod.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/distributedgen.rs
fedimintd/src/lib.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs

@dpc 
Rename `ModuleInitRegistry` to `ModuleGenRegistry` for consistency with the other `ModuleGen*` types.

Rename `ModuleInitRegistry` to `ModuleGenRegistry` for consistency

---

client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/core/server.rs
fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-api/src/module/mod.rs
fedimint-dbdump/src/main.rs
fedimint-rocksdb/src/lib.rs
fedimint-server/src/consensus/interconnect.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/db.rs
fedimint-server/src/net/api.rs
fedimint-sqlite/src/lib.rs
fedimint-testing/src/lib.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-ln/tests/ln_contracts.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

This PR introduces a wrapper struct to wrap the DatabaseTransaction into an IsolatedDatabaseTransaction. IsolatedDatabaseTransaction will now always prepend a 2 byte "module_prefix", which is the ModuleInstanceId, when inserting and reading from the database. The purpose of this is to logically partition the database so modules can use keys that have conflicting prefixes. This also allows us to use the same key for different modules (ex: ModuleDatabaseVersion).
When passing a DatabaseTransaction to a module, it is first wrapped using with_module_prefix, which wraps the existing DatabaseTransaction inside an IsolatedDatabaseTransaction. This means they cannot overwrite keys from other modules. The fedimint server is now responsible for committing the wrapped DatabaseTransactions, because …

Inject module_instance_id as prefix into database operations

---

fedimintd/src/bin/main.rs
fedimintd/src/ui.rs
fedimintd/templates/run.html

Follow up to #1421
I tested the success case and getting back to `/` after restart, but I'm unable to trigger error handling I've added. Seems like nothing from what is being entered to the UI is actually compared, trying to make the settings wrong results in dkg not being able to connect or panics, and never actually a failure, so :shrug: for now.
At least you'll get
when dkg is running, which switches automatically to connection string when dkg completes, which is better then previous behavior where call would hang until dkg is complete.

Don't hang the UI during dkg

---

docs/networking.md
flake.nix
misc/fedimintd-container-entrypoint.sh

In the docker file entrypoint I default to 8175, which now conflicts with ln-gateway, making it a bit odd to set them both up on a system (which sometimes might be needed).

Allocate 8176 as a default port number for Fedimint Admin UI

---

.github/workflows/ci-nix.yml
flake.nix
misc/ln-gateway-container-entrypoint.sh

I intend to use it eventually with `podman` to deploy ln-gateway as simple bash wrapper:
```bash
#!/usr/bin/env bash
exec podman run $MOUNT_OPTS_ETC -q -i docker.io/fedimint/ln-gateway "$@"
```
This behaves very much like we were running `ln_gateway` process itself: stdio, stdout, stderr, etc. Though I'm hitting https://github.com/containers/podman/issues/14707 which makes ctrl+c not work.
Re: #1436

Add ln-gateway container build

---

Cargo.lock
client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/utils.rs
client/client-lib/src/wallet/mod.rs
fedimint-api/src/config.rs
fedimint-api/src/module/mod.rs
fedimint-dbdump/src/main.rs
fedimint-server/src/config.rs
fedimint-server/src/consensus/mod.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/lib.rs
fedimintd/src/ui.rs
gateway/ln-gateway/src/bin/ln_gateway.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/fixtures/client.rs
gateway/tests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-dummy/Cargo.toml
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Adds `ModuleGenRegistry` to the client side so that we can manipulate client config modules such as producing hashes for verification.
Having the federation sign the client config hash will be done as a separate PR.
Related to #1205

First step at adding a client module hash verification

---

.tmuxinator.yml
scripts/build.sh
scripts/tmux-user-shell.sh

I'm aware that this alias "shadows" the real `bitcoin-cli`. But I'd argue it's fine to do that in the tmuxinator? 
alias points to: 
```
bitcoin-cli -regtest -rpcuser=bitcoin -rpcpassword=bitcoin
```
If you think that's a problem, then I'd go for the name `btc-cli`. That gets rid of the annyoing to type underscore (:smile:)  and doesn't shadow the real `bitcoin-cli`

Change `btc_client` to `bitcoin-cli` for consistency

---

gateway/cli/src/main.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs
gateway/ln-gateway/src/rpc/rpc_client.rs
gateway/ln-gateway/src/rpc/rpc_server.rs

It didn't take me long before I corrupted first mainnet ln-gateway I've set up by doing a `gateway-cli deposit` one block too early. Since our client code does db modifications first, and asks federation to make a tx second, the gateway is now stuck looping and waiting for an outcome of a transaction that didn't ever happen. :S
After I realized what happened I first made a loudest facepalm in the world. Then I started thinking if I could easily recover from this corruption, and it occurred to me that a e-cash restore that is already implemented in the client would probably fix it. So here it is - just enough code to be able to make gateway do `restore` (and `backup`, as I'm already doing it).
Considering the state of the `client` consensus state handling, we probably really, really need …

Add backup&restore to ln-gateway (and gateway-cli)

---

gateway/ln-gateway/src/cln.rs
gateway/ln-gateway/src/lib.rs

6723518fa2b018686ddb5570f9e97fd23fedb38a changed the type definition of `Htlc` and `Onion` to be compliant with the current spec, but only for the new CLN plugin. The old one remained out of spec, which this commit fixes.
As a second step we should either upstream these types (together with tests, so that the CLN team notices when they break their API) or put them in a common crate so we don't have to maintain this redundancy.

Unify CLN plugin types between old and new plugin

---

client/cli/src/main.rs
client/client-lib/src/api.rs
client/client-lib/src/mint/mod.rs

Since we should retry 404s automatically based on our strategy, we can eliminate the infinite loop here.
In the future once polling is replaced by notifications this becomes further irrelevant.
Fixes #1479

Makes fetch notes parallel and eliminates unnecessary retry

---

.tmuxinator.yml
gateway/ln-gateway/proto/gatewaylnrpc.proto
gateway/ln-gateway/src/bin/cln_extension.rs

Simplify gateway < > lightning extension rpc spec by defining unary calls for `pay_invoice` and `complete_htlc`.
We don't need streams right now, and should have started off with this simpler rpc spec

Trim gateway rpc streams

---

gateway/ln-gateway/src/bin/cln_extension.rs
gateway/ln-gateway/src/bin/ln_gateway.rs

Applies fix introduced by #1496 to allow gateway node to receive payment not meant for federations
Bonus commit to make a note on how to enable debug logging

CLN extension allows node to receive payment

---

scripts/reconnect-test.sh

Fixes flakiness in our reconnect due to not giving a peer enough time to rejoin before shutting down the others.

Fixes the reconnect test failures

---

crypto/derive-secret/src/lib.rs

This can be used for deterministic bearer tokens.

feat: Allow getting raw bytes from the `DerivableSecret`

---

client/client-lib/src/lib.rs
integrationtests/tests/tests.rs

Saves to DB before tx is submitted, undoing #1495.
Assumes that we will eventually have a better fix, but this is safer for now since whenever we submit a peg-in we need to make sure our notes are persisted first.

Saves to DB before tx is submitted, undoing #1495

---

client/client-lib/src/wallet/mod.rs
fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-rocksdb/src/lib.rs
fedimint-server/src/consensus/mod.rs
fedimint-sqlite/src/lib.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-wallet/src/lib.rs

As a follow up to https://github.com/fedimint/fedimint/pull/1331, this PR allows for entire Databases to be isolated instead of just individual DatabaseTransactions. We want the ability to isolate Databases and DatabaseTransactions because there are some db transactions that need to atomically span multiple modules, but we also sometimes give each module a handle to the database, such as during module_initialization (this db handle is only used in the wallet module currently). 
Isolated databases have the same API as normal databases accept that begin_transaction now returns a DatabaseTransaction that is isolated, so all operations will have a prefix prepended to each key to keep the data separate.

Isolate each Database when initializing the module

---

.github/workflows/daily.yml
.github/workflows/docs.yml
.github/workflows/rust.yml

As described in https://github.com/rust-bitcoin/rust-bitcoin/pull/1509 and https://github.com/actions-rs/toolchain/issues/216 the actions-rs is unmaintained.
A different [Github Action](https://github.com/dtolnay/rust-toolchain ) maintained by dtolnay rust developer can be used instead.
This PR updates to use the `stable` and `nightly` toolchain instead of the action-rs one, and also need to run a `cargo build` and `cargo clippy` command as the dtolnay's rust-toolchain action does not have a cargo build/clippy one.
Fixes #1172

ci: update to use dtolnay instead of actions-rs

---

modules/fedimint-wallet/src/lib.rs

Once we have recognized one of our transactions on-chain and have saved change to the DB we can stop trying to submit the transaction to our bitcoin node and forget about it.
Fixes #1534

Remove confirmed BTC transactions from db

---

gateway/ln-gateway/src/gatewayd/actor.rs
gateway/ln-gateway/src/gatewayd/gateway.rs
gateway/ln-gateway/src/gatewayd/mod.rs

Cherry pick back-compatibility changes that will allow us to introduce the proposed `gatewayd` (#1337 ) while still supporting the current `ln_gateway`.
- Note: `LnGateway` is renamed to `Gateway` in this new file
- so we can change the constructor signature of `LnGateway`
- so we can change how the gateway gets HTLC intercepts. `Gateway` in `src/gateway.rs` does not implement `handle_receive_payment`. Instead, actors directly subscribe to htlc intercepts on an entirely new pattern. More on this below
- So we can change constructor signature of `GatewayActor`. Have the new actor take a reference to lnrpc, which is 
- So we can enable direct subscription to intercepted HTLCs using the owned lnrpc
- API signature of the `GatewayActor` changes because it owns a reference to lnrpc, rather …

Gatewayd Compat Setup

---

docs/database.md
fedimint-api/src/core/server.rs
fedimint-api/src/module/mod.rs

Updating the documentation in two spots:
- docs/database.md to include a description and examples of the prefixes that are prepended for each module.
- Remove references to `batch` in the module definition documentation.
Addresses https://github.com/fedimint/fedimint/issues/1538

Update docs to include description of module prefixes

---

client/client-lib/src/mint/mod.rs
fedimint-rocksdb/src/lib.rs

This PR wraps all Rocksdb I/O operations in fedimint_api::task::block_in_place so that the executor thread is not blocked on I/O. Rocksdb does not do I/O during writes (it always writes to memory or it fails), but insert/remove operations return the previous value, so they have a chance of doing I/O while reading for the previous value.
Issue: https://github.com/fedimint/fedimint/issues/1528

Use block_in_place for synchronous Rocksdb operations

---

client/client-lib/src/api.rs
fedimint-api/src/fmt_utils.rs

As we are (ab)using jsonrpc for delivery of potentially large payloads (like backups), it would be best to sanitize values we log that can potentially be very large, to prevent flooding logs.
This change expands the existing functionality we used for logging (potentially large) database values in hex, only for json. Some extra type-system gymnastics were needed to support values nested in other values (in this case `PeerResponse`). These newtype wrappers are a bit inconvenient and tend to proliferate, but they get the job done and they are probably the most idiomatic approach.

Prevent huge client requests/responses flooding logs

---

flake.lock

```
nix flake lock --update-input nixpkgs
```
I'm hitting some bugs in tooling I'd like to introduce, that has been fixed recently.

chore: Update nixpkgs

---

flake.lock
flake.nix
misc/git-hooks/commit-msg

Currently only via git commit check hook, but will add a proper CI test after we try it out, and decide that we want to keep it.
* https://www.conventionalcommits.org
* https://github.com/convco/convco/
Needed to pull in `nixpkgs-unstable` to get a version of the linter that supports stdin. It doesn't seem to increase the amount of things being downloaded much, so should be OK, and we can remove it in the future.

feat: enforce conventional commit format using `convco`

---

.semgrep.yaml
fedimint-server/src/config.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/logging.rs
fedimint-server/src/multiplexed.rs
fedimint-server/src/net/api.rs
fedimint-server/src/net/framed.rs
fedimint-server/src/net/peers.rs
flake.nix
misc/git-hooks/pre-commit

This is to start the ball rolling on #1469 .
New constants are defined, committing us to certain logging categories, which we will treat as a semi-public API. This way users can set their logging levels, and they will not change out of the blue, just because we shuffled some code around.
Then, as a showcase,  I change the `error!` and `warn!` use to utilize this. This does add a bit of noise, but I think it's reasonable. We could introduce things like `error_net_peer!(...)`, `warn_consensus!(...)` wrappers etc. if we decide that we don't like the noise.
Lastly, we introduce `semgrep` rules and add them to git pre-commit hook, to enforce correct usage.
I limited the scope of changes to one package and two logging levels, to keep the change small and get some feedback first, before …

Logging improvements starter pack

---

Cargo.toml

This causes noticeable slowdown.

fix: `threshold_crypto` was not optimized in debug builds

---

.tmuxinator.yml
scripts/restart-tmux.sh

A first draft to address #1553. Adds a tmuxinator alias `restart` that runs the new script "restart-tmux", which sends the commands referenced in this [message](https://discord.com/channels/990354215060795454/1060246795004944466/1064727278568878160) and runs gw-reload.sh. Not sure if this is the best approach so I definitely welcome suggested alternatives.

feat: add restart command for tmuxinator

---

Cargo.lock
client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
fedimint-testing/Cargo.toml
fedimint-testing/src/btc/fixtures.rs
fedimint-testing/src/btc/mod.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/tests.rs
integrationtests/Cargo.toml
integrationtests/tests/fixtures/fake.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs
integrationtests/tests/tests.rs
scripts/rust-tests.sh

This change is trying to take care of a biggest pain point of our current state of testing suite - the long time it takes us to execute the integration tests with real LN and `bitcoind`.
Before:
After:
After quite a bit of investigation I realized that it should be possible to retain the shared infrastructure (which is great for keeping the performance high and resource usage low) yet run tests in parallel with relatively minor changes.
The biggest assumption that is being broken is strict control over block height. As multiple tests are sharing `bitcoind`, the block height can increase at any time, which will lead to random epochs being introduced.
The common pattern this breaks is:
```
join_all([
operation,
await_consensus_epoch(exact_amount_of_epochs_required)
])
```
where `operation` …

feat: Run `rust-tests.sh` in parallel

---

integrationtests/tests/tests.rs

Gaphole is waay too little considering how many notes might get used at the same time.

fix: flaky ecash restoration test

---

Cargo.lock
client/cli/src/main.rs
client/client-lib/Cargo.toml
client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/gatewayd/actor.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

We saw an issue where `spend_ecash` was called from multiple threads which was unsafe.  But this adds better error message and test coverage.

Adds a test and better error for spend_ecash

---

fedimint-server/src/lib.rs

Realized that sometimes the reconnect can stall because the `run_empty_epochs` may be overridden with a smaller number.  This change makes that additive.

Fixes some of the flakiness of reconnecting

---

fedimint-api/src/tiered.rs
fedimint-api/src/tiered_multi.rs
fedimint-server/src/config.rs

Transferring ecash offline takes a long time ~15-30 sec because of the all the data that needs to be transferred.
Part of the problem is our note selection algorithm isn't greedy, resulting in many notes to be transferred.
This reduces the avg number of selected notes from ~70 to ~10, tested using 100 different amounts from 1k to 100k sats.
BTW if we didn't use millisats (only sat denominations) that drops from 10 to 6.
Minor improvements in our latency tests as well:
AVG REISSUE TIME: 1.037 seconds
AVG LN SEND TIME: 3.452 seconds
AVG LN RECEIVE TIME: 3.685 seconds
Previously:
AVG REISSUE TIME: 1.420 seconds
AVG LN SEND TIME: 3.552 seconds
AVG LN RECEIVE TIME: 3.942 seconds

Greedy note select

---

fedimint-dbtool/src/dump.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/db.rs
fedimint-server/src/lib.rs

Avoids putting pending txs into the DB.
We have to use a `Mutex` around the cache, or alternatively we could put the cache into `FedimintServer` which seems worse.

Caches the submitted txs instead of using DB

---

client/client-lib/src/lib.rs
client/client-lib/src/logging.rs
fedimint-api/src/tiered_multi.rs
integrationtests/tests/tests.rs

I actually didn't know why it's failing and had to do some debugging
and decided to leave these in.

fix: flaky `peg_outs_are_only_allowed_once_per_epoch`

---

flake.nix
misc/git-hooks/commit-msg

The approach I used before (starting editor to edit commit message) does not play well with how git commit hooks work (IMO, poorly designed).
Instead of opening an editor, print an error message and introduce a helper to try again without figuring out how to recover the old message.

fix: conventional commit checking when using `git commit -m`

---

Cargo.toml

~~Don't merge.~~
edit: Let's merge it. Build time seems to not increase. 
Just testing the difference between `opt-level=2` and `opt-level=3`.
local build times of very rudimentary tests run with 
```sh
cargo clean
time cargo build
```
```
opt-level 3
run 1
________________________________________________________
Executed in   82.28 secs    fish           external
usr time  830.57 secs    2.69 millis  830.57 secs
sys time   72.70 secs    0.00 millis   72.70 secs
run 2
________________________________________________________
Executed in   82.31 secs    fish           external
usr time  825.85 secs    2.43 millis  825.85 secs
sys time   72.66 secs    0.00 millis   72.66 secs
run 3
________________________________________________________
Executed in   86.30 secs    fish           external …
```

build: change opt-level to 3 in cargo dev profile

---

.cargo/config.toml
Cargo.lock
fedimintd/Cargo.toml
fedimintd/src/bin/main.rs
flake.nix

The whole feature is said to be "unstable", but it might turned out very useful, and it's enabled only optionally, so should be OK.
Run `fedimintd` with an extra `--tokio-console-bind=127.0.0.1:1111` to enable. Connect with `tokio-console http://127.0.0.1:1111` (don't forget about `http://` part or it will not work, but not give you a plain error either).
Preview:
Re: #865

feat: `tokio-console` support

---

misc/git-hooks/pre-commit

GNU Parallel displays this annoying prompt to give them money.
Make it go away for everyone automatically.

fix: silence gnu parallel

---

fedimint-server/src/consensus/mod.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

Prevents the replay of transactions with an error at the API and P2P levels with integration tests.  Small refactor of some test code as a separate commit.
Should close #1402
Last bit of work to close #1353
Also should close #1347

Replay prevention2

---

justfile

We don't put them in pre-commit hook because they potentially take a long while to rebuild everything, but when executed manually, I think it's totally fine. The user can always ctrl+c and we do lints from the fastest to slowest.

feat: `just lint` to check `clippy` and `docs`

---

client/client-lib/src/db.rs
client/client-lib/src/ln/db.rs
client/client-lib/src/mint/db.rs
client/client-lib/src/wallet/db.rs
fedimint-api/src/db/mod.rs
fedimint-server/src/db.rs
modules/fedimint-dummy/src/db.rs
modules/fedimint-ln/src/db.rs
modules/fedimint-mint/src/db.rs
modules/fedimint-wallet/src/db.rs

Database code currently contains a lot of boilerplate code for reading/writing keys, key prefixes, and their associated values. Once every DB struct is versioned, the amount of boilerplate code will become a lot.
This PR attempts to make a code a bit more readable and just add a macro for generating the common key/value and key prefix/value implementations needed for reading/writing to the database.

feat: Add macro for implementing DatabaseKeyPrefixConst

---

fedimint-api/src/config.rs
fedimint-api/src/core/server.rs
fedimint-api/src/module/mod.rs
gateway/ln-gateway/src/cln.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Currently rebased on top of #1575 to avoid merge conflict. See only the last commit.
Implement the basic types and module-related primitves to support
versioning.
These are currently not used for anything, and here only for
moving forward with the discussion from https://github.com/fedimint/fedimint/issues/1548.

 Consensus and Api versioning - APIs

---

client/client-lib/src/utils.rs

This PR relates to https://github.com/fedimint/fedimint/issues/1177.
As discussed with @justinmoon in discord (https://discord.com/channels/990354215060795454/1069535765874343976), I've changed the parser so that amounts entered default to millisats while still allowing for other denominations to be specified with a suffix, e.g. `100sat`.

Default to millisats in CLI when parsing amount

---

fedimint-api/src/tiered.rs

Practically, that's likely not that relevant as larger values are given. 
Though, intuitively I'd expect that the given amount should be part of the tiers if an exact value is given. 
@jkitman thoughts?

fix: include the given maximum amount in tier generation

---

gateway/ln-gateway/src/lib.rs

fix: Print lightning gateway version at startup

---

client/client-lib/src/lib.rs
client/client-lib/src/transaction.rs
fedimint-api/src/db/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

Note: Let's land #1592 first, as these two are going to create a merge conflict.
While `join` provides concurrency, it does not provide parallelism. Operations that are CPU heavy, will block other futures from running, and multiple cores will be under-utilized.
This change uses `spawn` to create multiple tasks for certain heavy and common operations, which should help utilize multiple-cores better.

feat: In test run consensus operations in parallel

---

fedimint-api/src/db/mod.rs

very small nit; thought I submit it anyway.
just came across when reading about `IsolatedDatabaseTransaction`s. Currently, `new` is only called with the `module_instance_id` as param. If that will be the main value for the `new` function, I think it's worth to rename that parameter. If it will be called with other prefixes in the future (not only module instance id), then just close this PR @m1sterc001guy

refactor: rename variable in isolated database transaction

---

.github/workflows/ci-nix.yml
flake.nix

At some point the code coverage was aftected by the same issue that affected tests in #1379 .
Fix #1622

fix: code coverage

---

client/cli/src/main.rs
client/client-lib/src/lib.rs
fedimint-core/src/api.rs
fedimint-core/src/query.rs
fedimint-server/src/lib.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/gatewayd/gateway.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/fixtures/client.rs
gateway/tests/tests/tests.rs
integrationtests/tests/tests.rs

Creates a generic `VerifySigned` query strategy that can be used to validate the client configs are signed.
Next step towards verifiable client config downloads from any number of URLs using the `WsFederationConnect` JSON.

Verifies the client config in the API

---

.github/workflows/ci-nix.yml
flake.nix

By compiling multiple packages together we can re-use their
dependency builds.
Unfortunately this can't be done just "one for all" as some
targets can compile only a subset of packages (wasm), etc.
so we need to be mindful about grouping them.

feat: share dependency builds between different packages

---

integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs

Please https://github.com/fedimint/fedimint/pull/1599 first.
Instead of having bunch of ad-hoc `xyz_no_lock`, make them a separate lowest-level (locking-oblivious) `struct`, and let the higher level `struct`s wrap it.

refactor: `RealBitcoinTest` locking

---

client/cli/src/main.rs
fedimint-api/src/lib.rs
fedimint-core/src/api.rs
fedimintd/src/lib.rs
fedimintd/src/ui.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/gatewayd/gateway.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/fixtures/client.rs
gateway/tests/tests/tests.rs

Refactors the client connection string to use `one_honest` number of peers.  Now that we verify against the `federation_id` we can use a smaller number of urls or even non-federation urls to download from, and the urls don't need to be trusted.
JSON still seems like the best format since it's easy to construct and read, I tried other formats and they don't compress the information much.  Bytes for 10 guardians goes down from `649` to `242` with this change.
Example config:
```
{
"urls": [
"ws://127.0.0.1:18174/",
"ws://127.0.0.1:18184/",
],
"id": "ab011cbb464a4b71d90bc1f08a9034e43365a3620a72b76fd06e07d90221c5510d8a7489e78d4375114aae30ff3250b4"
}
```
Fixes #614
Will also close #1205 as most of the stable fed id work is done, will open new issue for updating P2P federation connections.

Client connect string

---

fedimint-api/src/db/mem_impl.rs
fedimint-api/src/db/mod.rs
fedimint-rocksdb/src/lib.rs
fedimint-sqlite/src/lib.rs

IDatabaseTransaction is already `: Send + 'a`

Remove useless `+ Send + 'a` from `IDatabaseTransaction`

---

Cargo.lock
crypto/aead/Cargo.toml
crypto/aead/src/lib.rs
fedimint-dbtool/src/dump.rs
fedimint-dbtool/src/main.rs
fedimint-server/src/config/io.rs
fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/ui.rs

Small refactor to remove the prompt password which we never use and probably shouldn't have deep in the lib code.
Also simplifies some of the shared config io code into `read_server_config` and `write_server_config`

Refactor the config io to simplify

---

Cargo.lock
Cargo.toml
fedimint-core/src/core.rs
modules/fedimint-wallet/src/keys.rs
modules/fedimint-wallet/src/lib.rs
modules/fedimint-wallet/src/tweakable.rs
modules/fedimint-wallet/src/txoproof.rs
recoverytool/Cargo.toml
recoverytool/README.md
recoverytool/src/main.rs

Tool to recover on-chain funds from abandoned federations, after a lot of reckless mainnet testing I finally wanted my Bitcoin back :laughing: 
The output consists of an array of UTXOs with their out point, the wallet descriptor including n-1 public keys and 1 private key (belonging to the guardian running the script) and the amount:
```
$ recoverytool --db server-1/database/ --cfg server-1 --password pass1 | jq
[
{
"outpoint": "c76d51c9c6dc6b8e462c37b3fa376e7c2055f04f16a8fffc2ab66c5bf0deff55:1",
"descriptor": "wsh(sortedmulti(3,0280bf3115766b7e1cb23f2f57caf4de5a9171d3985934f2895cc568b384b52319,cSRM825vXJwf8iXcngedon8nQsPC9VMB18wSiG1Fgw6Y1Kzi16ta,021123625d9b21822e1178fc0d2b3f737d0397584cfac821df3250e49c3127cab5,03865705be62a71a3776cca1169908099ad6d138a0c0ed4aeeaf2c8e64616f4085))#h2zg3uhw" …
```

Wallet recovery tool

---

fedimint-core/src/db/mod.rs
fedimint-core/src/module/audit.rs

Some offline discussion with @dpc and @mxz42 has shown that there is some confusion on the purpose of some database traits. Currently there are many traits named similar things, so their purpose isn't immediately clear. This PR renames the database traits with the intention of making it more clear on their purpose.
- `DatabaseKeyPrefixConst` -> `DatabaseRecord` and `DatabaseLookup`. `DatabaseRecord` is for individual db records and `DatabaseLookup` is for multi-record lookups.
- `SerializableDatabaseValue` was collapsed into `DatabaseValue`
- `DatabaseRecord` and `DatabaseLookup` derive from `DatabaseKeyPrefix` since both of those need the ability to prepend a prefix. This is the same functionality as before but the syntax is a bit cleaner.

fix: rename database traits

---

fedimint-server/src/consensus/interconnect.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/net/api.rs

Is there a reason we have that wrapper? 
- most of the time we use `db.begin_transaction()` already, only in some cases that wrapper was used
- and I like `begin_transaction()` more as the name is more expressive than `database_transaction`

refactor: remove unnecessary method to start db transaction

---

.tmuxinator.yml
fedimint-testing/src/ln/fixtures.rs
gateway/ln-gateway/proto/gatewaylnrpc.proto
gateway/ln-gateway/src/bin/cln_extension.rs
gateway/ln-gateway/src/gatewayd/gateway.rs
gateway/ln-gateway/src/gatewayd/lnrpc_client.rs
gateway/ln-gateway/src/gatewayd/mod.rs
gateway/ln-gateway/src/gatewayd/types.rs
modules/fedimint-ln/src/lib.rs
scripts/build.sh

Define gRPC spec for sourcing route hints from a [GatewayLightning](https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/proto/gatewaylnrpc.proto#L7) service. We then implement this logic for [gateway-cln-rpc](https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/src/bin/cln_extension.rs#L193) and mock it in shared [FakeLightning](https://github.com/fedimint/fedimint/blob/master/fedimint-testing/src/ln/fixtures.rs#L113) test fixture.
Along the way, we define a pattern for mapping grpc Rust autogen structs into Fedimint locally defined structs
closes #1554

Gatewayd route hints

---

flake.nix
justfile

Unfortunately trying to set it automatically doesn't seem to work
for `direnv` users.

feat: Warn users about too small ulimit

---

fedimint-core/src/db/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/db.rs
integrationtests/tests/fixtures/mod.rs

Through some refactors this code was accidentally dropped from https://github.com/fedimint/fedimint/pull/1567
We need to apply database migrations to the consensus keys/values as well to ensure that these stay up to date with the code, in addition to the modules.

fix: apply database migrations for the consensus keys and values

---

justfile
scripts/test-cov.sh

I was wondering how tests are distributed between all packages. 
I think @justinmoon  you talked about that somewhere, too, though I can't find it anymore.
Might be useful to include this script here? 
Output looks like:
```sh
$ just test-count
./scripts/test-cov.sh
packages                      : tests
------------------------------:---------------
aead                          : 0
fedimint-derive-secret        : 0
fedimint-core                 : 47
fedimint-derive               : 0
tbs                           : 4
hkdf                          : 9
ln-gateway                    : 0
fedimint-rocksdb              : 15
fedimint-server               : 10
fedimint-build                : 0
mint-client                   : 13
fedimint-ln                   : 3
fedimint-testing              : 0 …
```

Add script to show tests per package

---

scripts/build.sh
scripts/gw-reload.sh

Make `cargo build` used in tests respect 'CARGO_PROFILE'.
`crane` that we use in CI, uses 'CARGO_PROFILE' env variable to select between debug and release mode. We have a special transformation that prefixes all nix outputs names with `.debug` while overriding `CARGO_PROFILE` to `dev` to get a debug build versions.
Since we run the tests in the CI, and these tests are attempting `cargo build` if they don't respect this variable it leads to debug build being built for no good reason. This can be observed
by running `nix build -L .#cli-test.reconnect` (instead of
`nix build -L .#cli-test.debug.reconnect` that we actually use in CI). The workspace will built in release mode, but the test build will rebuild everything in debug mode.

fix: needless rebuilds when running tests in release mode

---

Cargo.lock
fedimint-bitcoind/Cargo.toml
fedimint-bitcoind/src/bitcoincore_rpc.rs
fedimint-bitcoind/src/lib.rs
fedimint-core/src/bitcoin_rpc.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-wallet/src/lib.rs

The bitcoin backend currently supported are both bitcoind and electrum (without integration tests at the moment), as mentioned in #1187 having multiple, easy to use, bitcoin rpc backend support is useful for dogfooding federations and easy setup/deploy.
That said, this PR aims to implement and support [Esplora](https://github.com/Blockstream/esplora) support, although as it's for Electrum it currently does not have any integration test (I'm working on that 😁).
This adds a new implementation for the [`IBitcoindRpc`](https://github.com/fedimint/fedimint/blob/13a0e24e902f63fae682c4e4af6e02069621086a/fedimint-bitcoind/src/lib.rs#L27-L58) trait for Esplora client. However, it could be implemented by using `reqwest` and calling each endpoint available on the Esplora API, this PR uses the …

feat: add esplora block source support

---

fedimint-core/src/encoding/mod.rs

Sometimes it's necessary to use type using it in a context that needs to be `Serialize`&`Deserialize`.

fix: `SerdeEncodable` should impl `Serialize` and `Deserialize`

---

flake.nix

`crane` discards it anyway, and built-in filtering is probably good enough for us.

fix: don't filter deps builds

---

.github/workflows/linkcheck.yml

One of the websites we link to had a temporary problem, and I don't want this to block our PRs.

fix: don't fail when external websites are down

---

fedimint-core/src/db/mem_impl.rs
fedimint-core/src/db/mod.rs
fedimint-dbtool/src/dump.rs
fedimint-dbtool/src/main.rs
fedimint-rocksdb/src/lib.rs
fedimint-server/src/consensus/mod.rs
fedimint-sqlite/src/lib.rs

This PR attempts to fix https://github.com/fedimint/fedimint/issues/1635
Right now additional allocations need to be taken because `commit_tx` takes `self` by move and not by `&mut` like the other functions in the trait. This PR introduces a new trait that contains an `Option` of the database transaction and consumes it during commit, and panics if the transaction is `None`. Additional wrapper was also introduced to accomodate the new trait.
This will directly conflict with https://github.com/fedimint/fedimint/pull/1197

IDatabaseTransaction taking self by move during commit

---

scripts/tmuxinator.sh

I had an environment variable with `FM_` in the middle of the value, which caused an "invalid variable" error. Instead, we look for `FM_` only at the beginning of an environment variable.
See log https://gist.github.com/justinmoon/2480ba4fa8ce486e60d610f6e3a04fe0 for full error

fix: Improve tmuxinator environment variable filtering

---

.github/workflows/ci-nix.yml
flake.nix

This fixes `nix build .#client-pkgs`
I had renamed the cross compilation target from made up "shot-names" to just full triple the compiler actually uses. It was just getting in away and confusing.

fix: unify cross and native package builds

---

.github/workflows/ci-nix.yml

This is for using our cachix as a deployment nix cache (if someone were to do that).
It also proves that our flake.nix package definitions are working.
I'm not sure if it's worth doing in every PR, so gating to run only on `master`.

feat: build release mode packages

---

.tmuxinator.yml
gateway/ln-gateway/src/bin/cln_extension.rs
gateway/ln-gateway/src/gatewayd/actor.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs
integrationtests/tests/fixtures/utils.rs
integrationtests/tests/tests.rs
scripts/build.sh
scripts/cli-test.sh
scripts/latency-test.sh
scripts/lib.sh
scripts/rust-tests.sh
scripts/setup-tests.sh

In place of the existing `ln_gateway`, we integrated `gatewayd` + `gateway_cln_extension` to the existing CLI and rust tests. This implies the new gateway architecture has parity of test coverage as we had on the old gateway, and we can proceed to remove the old gateway at will.
Next comes #1718

Use new gateway code in cli + rust tests

---

fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/distributed_gen.rs
fedimintd/src/fedimintd.rs

As a user of `fedimintd`-lib I just want to depend on `fedimintd` and add my own modules.

feat: free users of `fedimintd`-lib from manually adding std modules

---

fedimintd/src/bin/distributedgen.rs
fedimintd/src/bin/main.rs
fedimintd/src/distributed_gen.rs
fedimintd/src/fedimintd.rs
flake.nix

On top of #1739 #1720 
I'm trying to make building a `fedimintd` with custom modules as simple as possible.
The corresponding downstream `flake.nix`:
```nix
{
inputs = {
nixpkgs.url = "github:NixOS/nixpkgs/nixos-22.11";
nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
flake-utils.url = "github:numtide/flake-utils";
flake-compat = {
url = "github:edolstra/flake-compat";
flake = false;
};
fedimint = {
url = "github:fedimint/fedimint?rev=...";
};
crane.url = "github:ipetkov/crane?ref=v0.11.3";
crane.inputs.nixpkgs.follows = "nixpkgs";
};
outputs = { self, nixpkgs, nixpkgs-unstable, flake-utils, flake-compat, fedimint, crane }:
flake-utils.lib.eachDefaultSystem (system:
let
pkgs = import nixpkgs {
inherit system;
};
fmLib = fedimint.lib.${system};
fenix = fedimint.inputs.fenix; …
```

feat: expose fedimintd building & dev shell as a nix library

---

modules/fedimint-wallet/src/lib.rs

Simple fix for the dust limit error.
Fixes #1693 at least for this case, not sure whether we can generalize, especially given different bitcoin rpc backends.

Fixes peg-out being under dust limit

---

client/client-lib/src/db.rs
client/client-lib/src/ln/db.rs
client/client-lib/src/mint/db.rs
client/client-lib/src/wallet/db.rs
fedimint-core/src/db/mod.rs
fedimint-server/src/db.rs
modules/fedimint-dummy/src/db.rs
modules/fedimint-ln/src/db.rs
modules/fedimint-mint/src/db.rs
modules/fedimint-wallet/src/db.rs

Why? Because the types these macro `impl`s traits for can come from different crates making it impossible to use it.
Currently this does not happen, but I'm experimenting with 3rd party module building and spliting module into server/client/common sub-parts and this becomes a blocker.
Also, it seems it's easier to use and understand when each macro is smaller (functionaly).

refactor: split `impl_db_record` into two macros

---

fedimintd/templates/params.html

chore: use `fedimint://` for P2P URL placeholder

---

gateway/ln-gateway/src/bin/cln_extension.rs
scripts/lib.sh

-Works when lightningd requests plugin stop, and when the task group is generally shutting down
> Re: _cdecker, "the shutdown signal is not reliable (if the main daemon crashes or aborts the plugin's don't get the signal), as such we must be robust against sudden disappearances"_
we should observe the reliability of `cln-plugin` shutdown subscription, so we can be resilient to lightningd crashes.

fix: shutdown gateway-cln-extension on lightningd exit

---

fedimint-core/src/module/mod.rs
fedimint-server/src/config/distributedgen.rs
fedimint-server/src/config/mod.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

We're passing a lot of arguments there, most of which should not be accessible to the module itself. The module should have no access to its instance id, or raw dkg connection.
I think we'll need to define more operations, and possibly refactor it all even more, but this should be a good starting step in the right direction.

refactor: ServerModule::distributed_gen interface

---

Cargo.lock
client/client-lib/Cargo.toml
fedimint-core/Cargo.toml
fedimint-server/Cargo.toml
fedimintd/Cargo.toml
gateway/tests/Cargo.toml
integrationtests/Cargo.toml
modules/fedimint-ln/Cargo.toml
modules/fedimint-mint/Cargo.toml

After fedimint/threshold_crypto#6 and fedimint/hbbft#7 got merged we can now migrate to our own fork of these. This should also fix some breakage on master.

fix: depend on fedimint forks of `hbbft` and `threshold_crypto`

---

integrationtests/README.md
integrationtests/tests/fixtures/mod.rs
scripts/final-checks.sh
scripts/rust-tests.sh

The double-negative in `FM_TEST_DISABLE_MOCKS` variable always confuses me.
Not sure if `FM_TEST_WITH_REAL_FIXTURES` is the best name, but it confuses me less.
What do you think?

fix: Rename FM_TEST_DISABLE_MOCKS to FM_TEST_WITH_REAL_FIXTURES

---

gateway/ln-gateway/src/actor.rs

* Rename `buy_preimage_internal` to `buy_preimage_from_federation`
* Rename `buy_preimage_external` to `buy_preimage_over_lightning`
We need to rename these because they're confusing names. Can you think of any better ones?

Rename buy_preimage_internal and buy_preimage_external

---

scripts/lib.sh

Instead, save process ID and kill it later like everything else

fix: don't kill pkill gatewayd in lib.sh

---

fedimint-bitcoind/src/bitcoincore_rpc.rs
flake.nix
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs
scripts/build.sh
scripts/rust-tests.sh
scripts/setup-tests.sh

Runs wallet tests using `electrs` fixing a bug where the fee rate could be below the min relay fee.
Note that we should do the same for `esplora` eventually, although it's not in Nix packages.
Also we should handle errors more intelligently in general I think rather than just retrying all the time.

Adds tests for electrum

---

fedimint-core/src/time.rs

the serde repr for SystemTime was different on wasm because it wrapped a `Duration`.

fix: make SystemTime serde repr same on wasm and native

---

scripts/cli-test.sh

In the process of trying to get `gateway-cli-extension` to reliably stop after running `cli-test.sh`, I noticed that we had an unnecessary sleep in `cli-test.sh`. We can just poll `getreceivedbyaddress` which is the next line in the script.

fix: Remove unnecessary sleep and await_fedimint_block_sync calls

---

client/client-lib/src/lib.rs
modules/fedimint-ln/src/contracts/mod.rs
modules/fedimint-ln/src/lib.rs

This is a source of test flakiness.
Fix #1795

fix: ln client doesn't retry on preimage pending decryption

---

fedimint-bitcoind/src/bitcoincore_rpc.rs

Created in reference to #1387
Simply logs whether an RPC call was successful or not.

Add debug logging to bitcoincore rpc

---

justfile

Useful when you want to quickly check if wasm still compiles (because it often doesn't).

feat: just check-wasm

---

client/cli/src/main.rs
scripts/cli-test.sh

This is for the encoding part of #1730.
I've used named arguments in accordance with #1562.
I understood from yesterday's dev call that it might be better to pass in a JSON directly instead of individual `--id` and `--urls` arguments, so I could do that instead if required.

feat: add CLI command `encode-connect-info`

---

Cargo.lock
client/cli/Cargo.toml
client/cli/src/main.rs
client/client-lib/src/lib.rs
client/client-lib/src/utils.rs
fedimint-core/src/api.rs
fedimint-core/src/config.rs
fedimint-core/src/module/mod.rs
fedimint-dbtool/src/dump.rs
fedimint-server/src/config/io.rs
fedimint-server/src/config/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-testing/src/lib.rs
fedimintd/src/distributed_gen.rs
fedimintd/src/fedimintd.rs
fedimintd/src/ui.rs
gateway/ln-gateway/src/bin/gatewayd.rs
gateway/ln-gateway/src/client.rs
gateway/ln-gateway/src/lib.rs
gateway/tests/tests/fixtures/client.rs
gateway/tests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy/src/lib.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint/src/lib.rs
modules/fedimint-wallet/src/lib.rs

We can't have client code use server-side module generators forever. This change introduces everything necessary to support "client side module gens" with ability to downgrade `ServerModuleGen` to `ClientModuleGen`.

feat: introduce ClientModuleGenRegistry

---

Cargo.lock
gateway/ln-gateway/Cargo.toml
gateway/ln-gateway/src/bin/cln_extension.rs
scripts/lib.sh

Replaces https://github.com/fedimint/fedimint/pull/1772 and https://github.com/fedimint/fedimint/pull/1770.
Closes https://github.com/fedimint/fedimint/issues/1766.
Switched to our [own fork of core-lightning](https://github.com/fedimint/lightning/tree/fedimint) to get [this change](https://github.com/ElementsProject/lightning/pull/6041).

Shutdown gateway-cln-plugin when lightningd stops running

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/incoming.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/ln/outgoing.rs
modules/fedimint-ln/src/contracts/incoming.rs
modules/fedimint-ln/src/contracts/mod.rs
modules/fedimint-ln/src/contracts/outgoing.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-ln/tests/ln_contracts.rs

- rename all `IdentifyableContract` trait references to`IdentifiableContract`
~**NOTE:** needs to land on top of #1812~ not anymore

fix: identifiable contract trait typo

---

fedimint-client/src/sm/executor.rs
fedimint-client/src/sm/state.rs
fedimint-core/src/core/server.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/module/audit.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-testing/src/lib.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy-common/src/lib.rs
modules/fedimint-dummy-server/src/lib.rs
modules/fedimint-ln/src/lib.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet/src/lib.rs

Today we wrap `IsolatedDatabaseTransaction` inside `DatabaseTransaction` and only expose `DatabaseTransaction` to the modules. This has some downsides, such as the fact that `commit_tx` is exposed as a possible function for the modules to call. This should not be allowed though, since modules should not be allowed to commit to the database because the fedimint server is responsible for managing the lifetime of a database transaction. Today if this happens, `commit_tx` will panic.
This PR is a refactor to expose `ModuleDatabaseTransaction` to the modules and add the public facing database transaction API to `ModuleDatabaseTransaction`, but removed the functions that modules should not be allowed to call. This allows us to keep the wrapper functionality that we have introduced in previous …

refactor: expose ModuleDatabaseTransaction for modules

---

client/client-lib/src/lib.rs
integrationtests/tests/tests.rs

This invoice is signed (all BOLT11 invoices are) but it isn't confirmed in the federation, yet

fix: rename generate_unsigned_invoice -> generate_unconfirmed_invoice

---

fedimint-client/src/sm/executor.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/module/audit.rs

Redundancy in `DatabaseLookup` leftover from refactors.
Fixes: https://github.com/fedimint/fedimint/issues/1827

refactor: remove redundancy in impl_db_lookup

---

Cargo.lock
client/client-lib/Cargo.toml
client/client-lib/src/lib.rs
client/client-lib/src/wallet/mod.rs
fedimint-testing/Cargo.toml
fedimint-testing/src/btc/fixtures.rs
fedimint-testing/src/btc/mod.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs
integrationtests/tests/tests.rs
modules/fedimint-wallet-common/src/db.rs
modules/fedimint-wallet-common/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

- Allows clients to submit RBF transactions to bump the fees of a stuck transaction
- Note there is a risk the fed could bank a small profit if in a rare case the non-RBF tx confirms first
**Follow-up fee fix**
- Need to add checks to avoid fees set below `minRelayFee` that could cause `submit_transaction` to fail
- Switch to sat/vb for clarity
- Confirm that the actual tx weight matches the `PegOutFees` paid for (could not if it pulls in an additional UTXO)
Fixes #1480
Fixes #233

Add RBF support

---

gateway/ln-gateway/src/actor.rs

Spotted by @Maan2003 https://github.com/fedimint/fedimint/pull/1197/commits/cf44e05ca711eaa886c5fc008b42672313f66cac
Just wanted to get this in now since the polling PR is still in progress

fix: continue when we fail to buy preimage (don't return)

---

scripts/build.sh

On some systems tmp dir is still too long, and shorter tmp dir template would help.

fix: shorter FM_TMP_DIR

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/backup.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-client/src/sm/executor.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/module/audit.rs
fedimint-core/src/module/mod.rs
fedimint-dbtool/src/dump.rs
fedimint-dbtool/src/main.rs
fedimint-rocksdb/src/lib.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimint-sqlite/src/lib.rs
fedimint-testing/src/lib.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy-common/src/db.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs
recoverytool/src/main.rs

Currently in our database code we propagate all errors via `Result`s all the way up to the application code. This was done partly because there was a discussion on where database errors should be handled https://github.com/fedimint/fedimint/discussions/1370
In practice, we were just calling `expect` on database errors, which makes the code much more verbose and difficult to read. This PRs refactors the error handling so that the public database transaction functions do not return `Result`, except for `commit_tx`. Right now database error handling is done after attempting to commit to the database. Database implementations that fail prematurely (e.g sqlite) can swallow their failures and fail during `commit_tx` as well, so that the failure semantics are similar across database …

refactor: remove  return values in public database transaction functions

---

client/client-lib/src/wallet/mod.rs
integrationtests/tests/tests.rs
modules/fedimint-wallet-common/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

As a follow-up to RBF, add checks for if peg-outs `fee < min_relay_fee` or the `fee_tx_weight != actual_tx_weight`.
Refactors all the validation into a separate function in `StatelessWallet` for easier unit testing.

Add checks, refactor, test the wallet validation

---

Cargo.lock
fedimint-testing/Cargo.toml
fedimint-testing/src/lib.rs
modules/fedimint-ln-server/src/lib.rs

Right now, we do not currently have a mechanism for catching if someone updated a database key or value, but forgot to update the corresponding database migration. This PR aims to add test coveage to catch this scenario, starting with the lightning module.
There are two components to testing database migrations:
1. Creating a backup. This can be done by setting `export FM_TEST_DB_BACKUP_DIR` to a directory then running `cargo test prepare_migration_snapshots`. This will create database backups in the directory specified by the environment variable. This directory can then be saved/zipped for step 2 that can be run at a later date.
2. Run the database migration tests against a backup. The database migration tests are only run if the FM_TEST_DB_BACKUP_DIR has been set (otherwise they just …

test: lightning module database migration test

---

client/client-lib/src/lib.rs

I'm trying to extend the `Client<T>` out of tree, to make it usable for 3rd party client builders, and these fields are important to be able to access.

chore: expose ro fields of Client

---

Cargo.lock
client/client-lib/Cargo.toml
crypto/aead/Cargo.toml
fedimint-dbtool/Cargo.toml
fedimint-server/Cargo.toml
fedimintd/Cargo.toml
recoverytool/Cargo.toml

We'll need to eventually publish it on crates.io, and so we need it prefixed with `fedimint-`.

chore: rename `aeae` to `fedimint-aead`

---

modules/fedimint-dummy-common/src/lib.rs
modules/fedimint-dummy-server/src/lib.rs

Cleans up duplicated code in the dummy-modules:
* Remove ServerModuleGen and ServerModule from dummy-common
* Remove DummyVerificationCache from dummy-server and use the DummyVerificationCache from the dummy-common module instead

chore: remove duplicate code from dummy-module

---

docs/dev-running.md

Gateway federation client already funded, so skip it

docs: Remove peg-in from dev-running.md

---

.gitignore

I think the integration tests used to store stuff there. But that's all in a tmp directory now.

fix: Remove outdated entries from .gitignore

---

crypto/derive-secret/src/lib.rs

In custom modules using `fedimint-derive-secret` it is sometimes neccessary to export this key.

feat: DerivableSecret::to_chacha20_poly1305_key_raw

---

scripts/lib.sh

`$FM_LNCLI getinfo` was leftover debugging code from #1852. 
The FIXME was because some variables internal to this function were `export`ed and didn't need to be. Removed the exports but forgot to remove the FIXME.

Remove leftover debugging statement and outdated FIXME from shell function 

---

misc/test/electrs.toml
scripts/build.sh
scripts/setup-tests.sh

... for tests and tmuxinator.
Esplora doesn't support config files.
Added config files for LND and Core Lighnting in #1852
I think the config files make the shell scripts a bit more readable ...

Add config files for bitcoind and electrs

---

client/client-lib/src/mint/backup.rs
fedimint-core/src/epoch.rs
fedimint-dbtool/src/dump.rs
fedimint-server/src/consensus/debug.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/db.rs
fedimint-server/src/lib.rs
fedimintd/src/fedimintd.rs

This is the preliminary code for supporting shutdown at an epoch #948
What remains is the client code + tests to enable guardians to actually trigger the shutdown.  Since that requires developing an authenticated API it'll be done in a follow-up PR. See #1841

Support shutting-down at an epoch

---

flake.nix

Workaround: pick only the `ts` from `moreutils`.

fix: `parallel` binary from `moreutils` and `parallel` package conflict

---

scripts/tmuxinator.sh

`kill_fedimint_processes` should already clean up everything

fix: don't manually pkill processes after tmuxinator exits

---

.tmuxinator.yml
scripts/build.sh
scripts/lib.sh
scripts/setup-tests.sh
scripts/tmux-user-shell.sh
scripts/tmuxinator.sh

I was noticing some inconsistencies between how daemons are spawned and disposed (https://github.com/fedimint/fedimint/pull/1865) in tests vs tmuxinator and thought I'd make it more consistent, readable, and easier to reason about.
* If a daemon depends on another, I try to wait for it in the start function.
* `start_bitcoind` creates RPC wallet and mines 101 blocks.
* `start_gatewayd` connects to federation.
* Also, updated `gw_connect_fed` to retry if it fails. That should help address [this failure](https://discord.com/channels/990354215060795454/990354215878688860/1083640931556806737).

Bash functions to start all our daemons

---

Cargo.lock
crypto/aead/Cargo.toml
crypto/aead/src/lib.rs
fedimint-server/src/config/io.rs
fedimint-server/src/config/mod.rs
fedimintd/src/distributed_gen.rs

Switches our password stretching algorithm from PBKDF2 to Argon2, which is much stronger against brute-force attacks because it's memory-hard and so more difficult to parallelize.
We can use this algorithm for both our password-based encryption and auth #1841
Pretty good explanation here 
https://medium.com/analytics-vidhya/password-hashing-pbkdf2-scrypt-bcrypt-and-argon2-e25aaf41598e

Switch to Argon2 for passwords

---

scripts/test-ci-all.sh

set -o pipefail gets reset when parallel invokes a bash function.

chore: fix test-ci-all ignoring failures

---

docs/dev-env.md

More attempts to simplify how we start services in tests & tmuxinator. The reason I'm doing this is that it was kind of difficult to reason about all the dependencies in these scripts while trying to modify them to [run LND](https://github.com/fedimint/fedimint/pull/1852).
I removed the `scripts/start-fed.sh`. I think @jkitman used to call that one directly sometimes so maybe we should keep it? Main reason I chose to delete it is because it now assumes `FM_FED_SIZE` is set so couldn't be called directly before this PR.

run_dkg and start_federation bash functions

---

client/client-lib/src/lib.rs
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-core/src/api.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/db.rs
fedimint-server/src/net/api.rs

Remain tasks:
---
Currently, we use polling to check for updates(say "fetch_transaction").
What we need is to subscribe for change in web server task, and push notification for these changes in the main task.
But we can't immediately notify the web server task because the transaction is not yet committed. And the database won't contain the value. 
So mainly I see two solution:
- have "post commit hooks", function that get called after transaction is committed. But then we don't access to the state of the module.
- build notifications into the database using database keys, which is much more clean.
Another Attempt #273

Remove polling

---

fedimint-server/src/consensus/mod.rs
scripts/test-ci-all.sh

They normally complete in < 5 minutes, so 10 should be enough.

chore: put 10 minutes timeout on ci tests

---

fedimint-core/src/core.rs

Was probably an oversight from when I was finishing server modularization.

fix: remove unused `Transaction` struct

---

fedimint-testing/src/bin/fixtures.rs

Issue occurs when running the tests multiple times locally (the bitcoin wallet is already created)

Fix wallet already exists issue

---

flake.crane.nix

See: https://nix.dev/anti-patterns/language#reproducibility-referencing-top-level-directory-with

fix: crane build cache invalidated by top-level dir name

---

.github/workflows/ci-nix.yml
flake.crane.nix
flake.nix
scripts/test-ci-all.sh

Instead of running in parallel bunch of `nix build -L ...`, where
each `nix build` invocation will have to load the previously built
`./target` (gigabytes) individually, run one `nix build` that runs
`parallel` of each test.
The major difficulty here is sandboxing each tests (network namespace).
Running in `nix build` was giving us sandboxing for free. Now
I have to resort to weird `unshare ... unshare` invocation that seems
to work, but is not best. It also won't work on Mac, but we mostly
care about CI here anyway.

chore(ci): run tests in parallel more efficiently

---

client/client-lib/src/mint/backup.rs
crypto/aead/Cargo.toml
fedimint-server/src/config/io.rs
fedimint-server/src/config/mod.rs
fedimintd/src/distributed_gen.rs

We previously rename the *crate*, but forgot about renaming the library inside it.

chore: rename `aead` *lib* to `fedimint_aead`

---

Cargo.lock
client/cli/Cargo.toml
client/cli/src/main.rs
client/client-lib/src/utils.rs
fedimint-core/src/api.rs
fedimint-core/src/module/mod.rs
fedimint-dbtool/src/dump.rs
fedimint-server/src/consensus/debug.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs
fedimintd/src/fedimintd.rs
flake.crane.nix
flake.nix
integrationtests/tests/fixtures/mod.rs
scripts/cli-test.sh
scripts/latency-test.sh
scripts/reconnect-test.sh
scripts/rust-tests.sh
scripts/test-ci-all.sh
scripts/upgrade-test.sh

PR for adding consensus upgrades to the API, fixing #948.
- Adds the consensus upgrade signaling code via an authorized API.
- Introduces `ApiEvent` so we can send non-transaction events from the API to consensus thread
- Adds a new integration test for signaling the upgrade
- Eventually the upgrade signaling/start-up should move into an admin UI.
Will follow-up with a refactor suggested by @Maan2003 to introduce `ApiEndpointContext`

Consensus upgrade

---

flake.crane.nix

See https://github.com/fedimint/fedimint/pull/1934/files/e7cc5e99979601b7f5fb826137c1e985e1f5e976#diff-41e9269e557f97c7fa1206494a0d185e6dbfb639b08a7e07cd4868274af58118

chore: use `fedimint` instead of `src` for nix flake source dir

---

fedimint-core/src/module/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/api.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

Refactors `ApiEndpointContext` out so we can pass state to all API endpoints.

Refactor ApiEndpointContext out for use in api_endpoint!

---

client/cli/src/main.rs

fix for #1919
Is there a better way to get the default module decoders?

feat: add decode-tx command to cli

---

Cargo.lock
client/cli/src/main.rs
fedimint-core/Cargo.toml
fedimint-core/src/api.rs
fedimint-core/src/config.rs
fedimint-core/src/encoding/mod.rs
fedimint-core/src/encoding/tls.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/config/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/connect.rs
gateway/ln-gateway/tests/fixtures/client.rs
integrationtests/tests/fixtures/mod.rs
scripts/cli-test.sh

Refactors our use of `ApiEndpoint` to be more consistent and also moves the TLS certs into `ServerConfigConsensus` so that we can verify them during our new config setup process documented in #1628

Refactor api endpoints

---

fedimint-core/src/core/server.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/consensus/interconnect.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/net/api.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

I needed to make `attach_endpoints` generic in order to serve an API for config generation, prior to being able to create `FedimintConsensus`.
I had to put the DB tx and module id into `ApiEndpointContext` and return it from a generic `HasApiContext` which I can implement for config generation.
Cleans up some duplicate code and the long list of parameters passed into the handlers.

Make API attach_endpoints generic

---

fedimint-testing/src/bin/fixtures.rs
gateway/ln-gateway/src/bin/gatewayd.rs

Refactor that simplifies the command line arguments, makes it harder to invoke `gatewayd` incorrectly.
Fixes: https://github.com/fedimint/fedimint/issues/1955

refactor: use subcommand to group gatewayd parameters together

---

fedimint-server/src/net/connect.rs
fedimint-server/src/net/peers.rs
integrationtests/tests/fixtures/mod.rs

Addresses https://github.com/fedimint/fedimint/issues/163
Creates a `StreamReliability` configuration for `MockConnector` making connections randomly fail on read/write and be delayed (have latency).
Introduces these failures on `test_connect()` test.

feat: test unreliable (mock) network

---

fedimint-client/src/sm/executor.rs
fedimint-core/src/db/mod.rs

Renames `max_retries` to `max_attempts` in the db `autocommit` function.
- This *does* change the behaviour of the function slightly. Previously, if `Some(5)` was passed as `max_retries` the closure would run once, and then up to five times (equal to 6 times in total). Passing `Some(5)` now runs the closure up to five times in total, hence `max_attempts`.
- Move the part to increment the attempt counter to the top part of the loop. This is good practice as that will always ensure that every run of the loop will increment the counter. For instance, a future change may introduce an early `continue` that could have introduced a bug if the counter would not have been incremented manually.
This also makes it consistent with the [`retry` …

 Rename function `max_retries` to `max_attempts` parameter for consistency

---

fedimint-core/src/config.rs
gateway/ln-gateway/Cargo.toml
gateway/ln-gateway/tests/authentication_tests.rs
gateway/ln-gateway/tests/fixtures/mod.rs
gateway/ln-gateway/tests/integration_tests.rs
integrationtests/tests/tests.rs

Proposes an integration test suite for [gatewayd](https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/src/bin/gatewayd.rs).
To start with, tests are only run with mocks of dependencies like `ILnRpcClient` and `IFederationApi`.
In it's full extent, this proposal would involve sharing the following from **fedimint-testing** crate:
Gateway would then own it's own integration tests where it uses real or fake fixtures in validating it's functionality in serving one or more federations
towards #742

Gatewayd integration test suite proposal

---

client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-core/src/config.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/config/mod.rs
fedimintd/src/distributed_gen.rs
fedimintd/src/fedimintd.rs
fedimintd/src/lib.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy-common/src/lib.rs
modules/fedimint-ln-server/tests/ln_contracts.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

Introduce `Fedimintd::with_extra_module_gens_params` that allows
passing config gen params to use for any additional modules
registered with `Fedimintd::with_module`.
This is very provisional, only to unblock 3rd party module
out-of-tree testing for time being.

refactor: clean up ConfigGenParams, add ConfigGenParamsRegistry

---

gateway/ln-gateway/src/bin/gatewayd.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/tests/fixtures/mod.rs
integrationtests/tests/fixtures/mod.rs

- Don't panic
- Don't retry fetching route hints if empty vec is returned. I don't think this solves anything, and it confuses control flow because the constructor can just block forever if you have a node with no channels. IMO that's just weird behavior, but maybe I'm missing something.

Improve gateway instantiation

---

gateway/cli/src/main.rs

See #1867 
Replaces all 'expect' panic messages with the ? operator in the main function of the gateway-cli

chore: Remove expect calls from main function in gateway-cli

---

client/cli/src/main.rs

This PR is to resolve #1863.
The default value of `""` is the same as that used by `lncli`. Please let me know if a different value should be used (or any other comments). Thanks.

feat(cli): add default value for invoice description

---

client/client-lib/src/lib.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/outcome.rs
client/client-lib/src/wallet/mod.rs
fedimint-core/src/api.rs
fedimint-core/src/lib.rs

Fetching output outcomes still assumed that there are only the three hard coded modules. This PR allows fetching output outcomes from arbitrary outcomes.
I could probably do more, especially around error cleanup (is that `CoreError` error really needed?) but this was the part that was directly blocking. Maybe @mxz42 can take a look at if we can get rid of `CoreError`.

Make outcome fetching API module-compatible

---

client/cli/src/main.rs

This change was originally made in #1996, but I think was accidentally removed in #2004.

fix(cli): re-add default value for invoice description

---

fedimint-bitcoind/src/bitcoincore_rpc.rs
fedimint-bitcoind/src/lib.rs
fedimint-testing/src/btc/bitcoind.rs
fedimint-testing/src/btc/fixtures.rs
modules/fedimint-wallet-server/src/lib.rs

See comment in the code.
This fixes hangs when backends keep returning error due to transactions being submitted already being included in the blockchain: https://github.com/fedimint/fedimint/actions/runs/4503632304/jobs/7927075007?pr=2004

fix: ignore unreliable result of `submit_transaction`

---

.gitignore

There are a couple dirs now generated when running tests that we can ignore.
Talking with @m1sterc001guy `db/` will exist after https://github.com/fedimint/fedimint/pull/1935

add generated dirs to gitignore

---

fedimint-server/src/config/mod.rs
fedimint-server/src/lib.rs
fedimint-server/src/net/connect.rs
fedimint-server/src/net/peers.rs
fedimintd/src/distributed_gen.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs

Also makes the reconnection delay a parameter with low default values on tests to avoid exponential growth in test duration when simulated network failures happen.
Closes https://github.com/fedimint/fedimint/issues/163 by completing the work started on https://github.com/fedimint/fedimint/pull/1982

feat: run integration tests under unreliable network conditions

---

README.md

I think we should make these calls more visible / discoverable. But it's a little weird putting a Google Calendar link in the README? Any better ideas?

chore: link to developer call calendar in README

---

client/cli/src/lib.rs
fedimint-core/src/admin_client.rs
fedimint-core/src/api.rs
fedimint-core/src/lib.rs
fedimint-server/src/config/api.rs
fedimint-server/src/config/io.rs
fedimint-server/src/config/mod.rs

Second iteration on the config gen API.
Adds the ability of peers to send their server connections to a leader and then the leader to return the list of peers that have connected.
Related to https://github.com/fedimint/fedimint/issues/1893 https://github.com/fedimint/fedimint/issues/1628

Second iteration on the config gen API

---

fedimintd/src/ui.rs

Currently there are not many logs when running `fedimintd` with `--listen-ui` which makes it difficult to know if it is running correctly. This PR slightly modifies the log message to make it easy to tell that the binary is listening on a `SocketAddr`.

chore: add log message when setup UI is running

---

misc/git-hooks/pre-commit

Previous checks produces warnings.

chore: skip eof check on all files under `./db`

---

fedimint-core/src/admin_client.rs
fedimint-core/src/config.rs
fedimint-core/src/core.rs
fedimint-server/src/config/api.rs
fedimint-server/src/config/mod.rs
fedimint-server/src/net/api.rs
fedimintd/src/distributed_gen.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs

Next iteration of the API, this one enables the leader to configure the final config gen params and send them to followers.
After this we should be able to run DKG.

Api config v3

---

scripts/test-ci-all.sh

Print a big `## FAILED: {testname}` after each failed test output.
How it will look:
```
> just test-ci-all
./scripts/test-ci-all.sh
⚠️  ulimit too small. Running 'ulimit -Sn 10000' to avoid problems running tests
Finished dev [unoptimized + debuginfo] target(s) in 0.46s
00:00:00 This test always fails and it is expected
...
```

chore: make it easier to locate a failed CI tests

---

Cargo.lock
client/cli/Cargo.toml
client/cli/src/lib.rs

On top of #2030
Instead of terminating early, make it convenient to convert errors to the desired `CliError` type.

refactor: get rid of early termination in fedimint cli

---

.github/workflows/ci-nix.yml
Cargo.toml
flake.nix
scripts/build.sh

Before (`nix build #.debug.workspaceBuild`, uncompressed => compressed):
```
fedimint-workspace-build> /*stdin*\            : 17.83%   (  9.16 GiB =>   1.63 GiB, /nix/store/mfy5k84rxqfh3x7ss3wwnyxf8z1zv752-fedimint-workspace-build-0.0.1/target.tar.zst)
```
After:
```
fedimint-workspace-build> /*stdin*\            : 17.46%   (  6.57 GiB =>   1.15 GiB, /nix/store/j7gh6rsi65g2ld3z3wkqdn8ymfyjl7j4-fedimint-workspace-build-0.0.1/target.tar.zst)
```
According to https://users.rust-lang.org/t/keeping-debug-info-but-smaller/55009/3 `debug=1` is the same level that release build uses, which should be adequate for CI.
BTW. If you're curious, `debug=0` produces:
```
fedimint-workspace-build> /*stdin*\            : 18.85%   (  4.04 GiB =>    779 MiB, …
```

chore: debug build with release-profile level of debug symbols

---

gateway/ln-gateway/src/bin/cln_extension.rs

Before this PR, when you call `lightning-cli plugin stop gateway-cln-extension` you'd hit a 30 second timeout before the extension exited, and `pkill -9 lightningd` would usually leave the extension running.
After this PR, both exist smoothly and instantly.

Make gateway-cln-extension exit smoothly

---

client/cli/src/lib.rs
docs/dev-running.md
fedimint-testing/src/bin/fixtures.rs
fedimintd/src/fedimintd.rs
scripts/build.sh
scripts/start-containers.sh

* Make it possible to pass by env variable
* Make it always explicit, not positional
* Use the same name (keep an alias for easier transation)

chore: clean&unify `--data-dir` argument to fedimintd and fedimint-cli

---

fedimint-testing/src/ln/fixtures.rs
fedimint-testing/src/ln/mod.rs
gateway/cli/src/main.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/bin/gatewayd.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/lnd.rs
gateway/ln-gateway/src/lnrpc_client.rs
gateway/ln-gateway/src/rpc/mod.rs
gateway/ln-gateway/src/rpc/rpc_client.rs
gateway/ln-gateway/src/rpc/rpc_server.rs
gateway/ln-gateway/tests/fixtures/mod.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/real.rs
integrationtests/tests/fixtures/utils.rs
integrationtests/tests/tests.rs

PR adds the ability for `gatewayd` to reconnect to CLN or LND if they go down. This API could also be used to switch which lightning implementation is used without needing to restart `gatewayd`.
Manual testing using tmuxinator is working. Integration test for sending an outgoing payment after a disconnection has been added.

feat: allow gatewayd to reconnect to CLN or LND

---

gateway/ln-gateway/src/rpc/rpc_client.rs
gateway/ln-gateway/src/rpc/rpc_server.rs

#2019 added `/reconnect` API to the gateway. However, `/connect` and `/reconnect` are very confusing and poorly named APIs which don't say much about the underlying functionality. This PR proposes a rename of the following form:
- `/connect` > `/connect-fed`
- `/reconnect` > `/connect-ln`

Gateway connect* API renames

---

fedimint-testing/src/ln/fixtures.rs
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/bin/gatewayd.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/lnd.rs
gateway/ln-gateway/src/lnrpc_client.rs
gateway/ln-gateway/tests/fixtures/mod.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/utils.rs
integrationtests/tests/tests.rs

PR to simplify `gatewayd`'s lightning reconnection logic. `connect` and `disconnect` no longer exist and the `connect` logic is moved into the constructor of CLN or LND client. Fixes: https://github.com/fedimint/fedimint/issues/2069
I attempted to use `ArcSwap` but ran into difficulties since `ArcSwap` is not cloneable and each actor currently needs access to the lightning connection.

refactor: simplify lightning connection logic

---

codecov.yml

https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations-via-yaml

fix: disable codecov in-code annotations

---

.github/workflows/ci-nix.yml

Will switch to `master` branch only after validating.

chore(ci): send discord notification on failed runs

---

flake.nix

Produces a .deb package when I run: `nix bundle --bundler github:NixOS/bundlers#toDEB .#gatewayd`

chore: add gateway packages to flake.nix

---

codecov.yml

While trying to figure out why the annoying "annotations" keep showing up in our diffs (https://discord.com/channels/990354215060795454/1075857804692295720/1092933724003377203) I found a [PR to another project](https://github.com/SFML/SFML/pull/2261/files) which disabled annotations. It does this:
```
github_checks:
annotations: false
```
We had an extra 2 spaces before `annotations` so removed those. I also noticed they had `coverage` at the top-level whereas we had it nested under `codecov`. So I updated ours to be the same. This is also what [example from the docs does](https://docs.codecov.com/docs/codecovyml-reference#coverage). 
If this doesn't get rid of the annotations, I don't know what will ...
One other difference is that this other project has `.github/.codecov.yml` and we …

fix: Move "coverage" key to top-level in codecov.yml

---

fedimint-bin-tests/src/main.rs
fedimint-testing/src/bin/fixtures.rs
scripts/build.sh

This is done to partially address #2101 issue 5, and will help migrate the remaining portions of Fedimint's testing infra to Rust away from Bash scripts.

feat: Spawn electrs and esplora in fedimint-bin-tests

---

.github/workflows/ci-nix.yml

Seems like `if: failure()` is true only if any previous step in the same job failed. :shrug:

chore: fix failure conditions for discord notification

---

.github/workflows/ci-nix.yml

It needs to be reminded that it's a failure. [Relevant info on failure management ;)](https://www.youtube.com/watch?v=cQpq56FmIN4).

fix: discord notifications report failures as success

---

.tmuxinator.yml
scripts/aliases.sh

When opening a new tmux pane in tmuxinator, you can easily source the aliases file with `. .aliases.sh` or `source .aliases.sh`
The core issue is that the commands in `pre_window` of tmuxinator are only executed when tmux is started, but not when I manually open a new pane or window.
```yaml
pre_window:
- source .tmpenv
- source scripts/lib.sh
- source .aliases.sh
```
I thought that's annoying since I open and close panes in the tmuxinator, too, and these new manually opened panes don't have any aliases set. This way you can just source them. 
I'm not sure if we can automate the sourcing as well? perhaps somehow via nix @dpc? 
thoughts in general?
I also just copy & pasted the aliases. The restart script was (and still is) commented out for a reason?

chore: put aliases in its own file to be easily sourced

---

gateway/ln-gateway/src/lib.rs

fix: skip connecting to federation if already connected

---

gateway/ln-gateway/Cargo.toml
gateway/ln-gateway/build.rs
gateway/ln-gateway/src/bin/cln_extension.rs
gateway/ln-gateway/src/bin/gatewayd.rs

- it follows the same approach as gatewayd, checks for an arg `version-hash` and prints the `CODE_VERSION` value.
- also sort some deps.
fixes #2081

chore: add version-hash parsing and printing for gateway-cln-extension

---

Cargo.lock
client/client-lib/src/ln/mod.rs
client/client-lib/src/mint/mod.rs
client/client-lib/src/wallet/mod.rs
fedimint-core/src/api.rs
fedimint-core/src/config.rs
fedimint-core/src/lib.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/config/api.rs
fedimint-server/src/config/mod.rs
fedimint-testing/src/lib.rs
fedimintd/src/distributed_gen.rs
fedimintd/src/ui.rs
integrationtests/Cargo.toml
integrationtests/tests/fixtures/mod.rs
modules/fedimint-dummy-server/src/lib.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-ln-server/tests/ln_contracts.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

Simplifies and standardizes our config gen parameters.
Redundant `ServerConfigParams` is replaced by the new `ConfigGenParams` struct.
Renames some duplicate names:
- `ConfigGenParams` -> `ConfigGenModuleParams`
- `ApiEndpoint` -> `PeerUrl`
Moves `gen_local` to the test crate so it isn't used accidentally.

Configgen refactor

---

fedimint-core/src/core/server.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/module/audit.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-testing/src/lib.rs
modules/fedimint-dummy-server/src/lib.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

it was already `ModuleDatabaseTransaction<..., T = ModuleInstanceId>`, but not used in the rest of code base.

chore: use default type paramater in ModuleDatabaseTransaction

---

gateway/ln-gateway/src/lnd.rs

LND in tmuxinator will currently crash with the following commands:
`fedimint-cli switch-gateway <pub key of lnd>`
`fedimint-cli ln-invoice 1000 description`
`lightning-cli pay <bolt 11 invoice>`
It is crashing because it is failing to buy the preimage (because the LND gateway has no ecash) then it tries to settle the HTLC with a `None` for `incoming_circuit_key`. Looking at the [LND source code](https://github.com/lightningnetwork/lnd/blob/f9f08079d0a0ffefabb99e210708a4733825ebef/lnrpc/routerrpc/forward_interceptor.go#L103), this is not allowed.
This is a simple PR to pass the `incoming_circuit_key` so that LND doesn't crash.

fix: LND crashes if incoming_circuit_key in None

---

scripts/pegin.sh
scripts/tmux-user-shell.sh

Tmuxinator doesn't current peg-in any ecash for LND, so it can't receive payments when tmuxinator starts. This change just pegs-in some ecash for LND so that it can receive payments over the Lightning Network.

fix: peg-in LND gateway

---

CODEOWNERS

Add a basic CODEOWNERS file.
See
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
for more details.
Right now we don't have to enforce reviews from CODEOWNERS, but it will still be useful by assigning reviewers automatically to PRs.

feat: basic CODEOWNERS

---

.codecov.yml
.github/workflows/ci-nix.yml

While at it, rename it to be hidden. (Docs say it's OK)
Turns out one can validate it with:
```
curl -X POST --data-binary @.codecov.yml https://codecov.io/validate
```

fix: codecov.yml invalid

---

CODEOWNERS

So as things are these groups are only to make sure relevant people get a notification and review request assigned automatically, to help everyone see what is relevant for them. **Importantly**, we still require 2 reviews of __anyone__ with reviewer (write) role. Being in a given team is more of a chore  while being reviewer at all is a privilege (power to approve).
Please don't be shy to ask to be added and removed from any group, fill PRs to modify the CODEOWNERS , and if anything is not ideal etc we can tweak and iterate.

feat: improved CODEOWNERS flow

---

fedimint-bin-tests/src/federation.rs
fedimint-server/src/config/api.rs
fedimint-server/src/config/io.rs
fedimint-server/src/config/mod.rs
fedimint-server/src/net/connect.rs
fedimint-testing/src/bin/fixtures.rs
scripts/start-containers.sh

Fixes  #2074
@SumantxD took a shot at fixing it, using your string replacement code

fix: handle peer names with special chars

---

gateway/cli/src/main.rs
gateway/ln-gateway/src/bin/gatewayd.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs

`Reconnect` is ambiguous because it could mean reconnect to a federation or reconnect to the lightning node. This PR makes it more explicit by renaming structs to include "Lightning" if they're dealing with lightning

refactor: rename Reconnect to ReconnectLightning

---

fedimint-cli/src/lib.rs
fedimint-client-legacy/src/mint/backup.rs
fedimint-client-legacy/src/mint/backup/tests.rs
gateway/ln-gateway/src/actor.rs
integrationtests/tests/tests.rs

We've discovered that it's useful to add extra data to backups, and absent any more general purpose backup module it's the easiest to just add a field that clients can use to put whatever they desire.

feat: ability to add metadata to mint backup

---

.github/workflows/ci-nix.yml
flake.lock

Turns out we can update `advisory-db` before every run and it doesn't cause a whole project rebuild, so we can always run with an up to date state.
However - it is failing and probably will often start failing out of the blue with no immediate fix, so I'm making it a non-required job.
It will show like that:
which does not prevent merging a PR, and should not report alerts on Discord `#alert` channel. But it will show every PR status as a red-x (just like codecov often does).

chore: update advisory-db on every run

---

Cargo.lock
fedimint-testing/Cargo.toml
fedimint-testing/src/ln/fixtures.rs
gateway/ln-gateway/proto/gatewaylnrpc.proto
gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/bin/cln_extension.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/lnd.rs
gateway/ln-gateway/src/lnrpc_client.rs
integrationtests/Cargo.toml
integrationtests/tests/fixtures/utils.rs

Currently in the gateway, there are two RPCs needed for completing an HTLC: `subscribe_htlcs` and `complete_htlc`. Subscribe returns a stream which the actors use to determine if they need to take an action with the federation. If the gateway is able to get the preimage, it then calls `complete_htlc` to complete the payment. 
However, it is not necessary to have two separate RPCs and this makes the code a bit more complicated. This refactor changes it so there is only one RPC called `route_htlcs`. This RPC takes a stream as input and returns a stream. This way, the actors can send messages using the input stream rather than needing to call a separate RPC.
This allows us to clean up the code a bit. In the LND implementation, we are able to remove the `outcomes` map.
Fixes: …

refactor: remove subscribe htlcs and complete_htlc

---

fedimint-core/src/util.rs

Making this a separate PR mostly to let make people aware of our versions of `BoxFuture` and `BoxStream`.

feat: introduce our own WASM-compatible version of `BoxStream`

---

scripts/test-ci-all.sh

MacOS Github runner is running out of memory in our CI. I'm looking for a simple way to prevent that.
https://www.gnu.org/software/parallel/parallel.html#options
`--jobs +0` will run at most as many tests as cpus available, which makes sense as the tests are already decently parallelized.
For buildjet, it will be still more then amount of high level tests we have. For `macos-12` it will be 3.
Also, increase the amount of free memory required before starting a new test job. Just in case.

chore: limit amount of parallel tests in test-ci-all.sh

---

.github/workflows/ci-nix.yml

We were not doing it before, and it seems it was broken.

chore: don't run tests on MacOS CI build

---

flake.crane.nix

According to:
https://github.com/taiki-e/cargo-llvm-cov#known-limitations
it's only defaulting to 1 thread, because of rustc issue:
https://github.com/rust-lang/rust/issues/91092
but it seems the issue is that relatively infrequently some tests
will fail to be reported... which if fine with me if it makes
the CI faster. And they are talking about thousands of tests,
while we probably have <100.
From:
to:
while it still says:
so LGTM

chore: make Code Coverage build run tests in parallel 

---

scripts/lib.sh
scripts/upgrade-test.sh

See https://github.com/fedimint/fedimint/issues/2236
My guess is that the reason the test is failing is that 
https://github.com/fedimint/fedimint/blob/fc7b43c650c4685936d0b19faca070e898372f8b/scripts/upgrade-test.sh#L9
sometimes is able to record pids from `FM_PID_FILE` before
it was updated.

fix: bandaid for flaky cli_test_upgrade hanging sometimes

---

Cargo.lock
fedimint-cli/src/lib.rs
fedimint-client-legacy/src/lib.rs
fedimint-client-legacy/src/mint/mod.rs
fedimint-core/src/db/mem_impl.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/db/notifications.rs
fedimint-core/src/tiered.rs
fedimint-core/src/tiered_multi.rs
fedimint-rocksdb/src/lib.rs
fedimint-sqlite/Cargo.toml
fedimint-sqlite/src/lib.rs
gateway/ln-gateway/src/actor.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-mint-client/src/lib.rs

Stream data from DB in descending denomination order then only uses the required notes. Also calculates and uses a summary of the notes when some metrics like `total amount` are required.
Although this started as solution to https://github.com/fedimint/fedimint/issues/82 and may improve the speed of `select_notes`, the focus is mostly on reducing memory usage.

feat: Avoid loading all notes in memory

---

gateway/ln-gateway/src/bin/gatewayd.rs
gateway/ln-gateway/src/lib.rs
gateway/ln-gateway/src/rpc/mod.rs
gateway/ln-gateway/src/rpc/rpc_server.rs
gateway/ln-gateway/tests/fixtures/mod.rs

For `gatewayd`'s web server event loop, we currently have two loops with a `sleep` in between. This is not necessary, it is simplier to just block on the channel that is waiting for messages. This PR adds a new message that is sent during shutdown.
Fixes: https://github.com/fedimint/fedimint/issues/1603

fix: remove sleep in gatewayd web server event loop

---

gateway/ln-gateway/src/actor.rs
gateway/ln-gateway/src/bin/cln_extension.rs
gateway/ln-gateway/src/lib.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

This PR refactors the `actors` data structure. We had two locks in this data structure, one locking the `HashMap` and the other locking the individual actor. Write access is rarely needed on the actors though, so using a `Mutex` is heavy since read operations will block. Instead, this PR uses a `RwLock` so that read operations are not blocked. We also only access the actors through the `HashMap` though, so its fine to just lock the map.

refactor: use RwLock for actors map

---

flake.nix

This spares people some downloading and building when setting up.

chore: use rust-analyzer shipped with NixOS 

---

flake.nix
flake.toolchain.nix

For nightly-only tools, like `cargo-fuzz`.
Use with `nix develop .#nightly`.
Requested by @Maaxxs

feat: `nightly` Rust dev shell

---

fedimint-client-legacy/src/lib.rs
fedimint-client-legacy/src/mint/mod.rs
integrationtests/tests/fixtures/legacy.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/fixtures/user.rs
integrationtests/tests/tests.rs

In order to test the next gen client, we need to extract interfaces that both the legacy and new client can implement in the interim.  These interfaces can eventually become part of the `client-app` API that is directly used by mobile wallet apps.
The final client would implement `IWalletClient + IMintClient + ILightningClient`.
`ITestClient` contains functions specifically for testing.  `IGatewayClient` contains functions only used by the gateway client.

refactor: out new client interfaces for testing

---

integrationtests/tests/fixtures/mod.rs

Fixes #2107
This was annoying me when debugging as well.  Confirmed the culprit, don't take much of a performance hit for adding normal reconnect delays.
```
time ./scripts/rust-tests.sh > out-delayed.txt 2>&1 
real	5m26.697s
user	24m35.680s
sys	2m34.754s
grep -c "Replacing existing connection" out-delayed.txt
2
...
time ./scripts/rust-tests.sh > out-normal.txt 2>&1 
real	5m6.703s
user	26m43.863s
sys	2m46.803s
grep -c "Replacing existing connection" out-normal.txt
72491
```

fix: remove flood of Replacing existing connection in test output

---

.github/workflows/ci-nix.yml

15 minutes is not enough from time to time. Example: https://github.com/fedimint/fedimint/actions/runs/4752263039/jobs/8442402557?pr=2251

chore: increase linux cross compile timeout

---

fedimint-bin-tests/src/main.rs
fedimint-server/src/consensus/server.rs

We originally only let a peer rejoin once, however due to the network buffers it's possible they successfully create an outcome but drop HBBFT messages from future epochs, getting them permanently stuck.
This PR allows them to rejoin even after they produce an outcome so long as they determine from a threshold of peers that they are behind.
We can probably close some old issues such as #1080 and #1136.  However, we still need to do #229 since it can stall the entire federation if a peer is offline for too long.
Once we switch to AlpehBFT we can drop a lot of this hacky logic since we will no longer have to deal with the concept of epochs or verifying signed epochs using signatures from produced outcomes.

fix: rejoin after any number of epochs pass

---

.gitignore
Cargo.lock
fedimint-client/Cargo.toml

It is said to stop writting to source code, so we should not need a `.gitignore` workaround anymore.

chore: update aquamarine library

---

scripts/rust-tests.sh
scripts/test-ci-all.sh

This avoids rebuilding them 3 or 4 times in parallel, in each test run.

chore: pre-compile rust-tests in CI

---

.github/workflows/ci-nix.yml

We only had a handful of macos runners available, and they take a while to build their stuff. Also - due to how filtering here needs to be done, even builds that we skip need to get an available macos runner, just so it can... ignore the step.
All this combined, stals PR's CI, due to not enough macos runners.

chore: don't run *all* cross-compilation targets on macos

---

fedimintd/src/ui.rs
fedimintd/templates/params.html
scripts/run-ui.sh

This aims to resolve #1532 by pre-populating the remaining fields in the setup UI using environment variables.
@dpc As discussed, I've followed the same approach as used in #1683. Please let me know if more robust checks of the environment variables are required.
I haven't pre-populated the guardian name as I believe that would require changing the code in https://github.com/fedimint/fedimint/blob/master/fedimint-testing/src/bin/fixtures.rs#L345, which might be out of scope here, but please let me know otherwise.

chore: pre-populate setup ui using env vars

---

fedimint-server/src/config/api.rs
fedimint-server/src/consensus/server.rs
fedimint-server/src/net/peers.rs
fedimintd/src/distributed_gen.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs

Alternative to https://github.com/fedimint/fedimint/pull/2267 using exponential backoff and hard min/max values. Will generate the following delays:
TEST_DEFAULT:
```
1: 2.191s
2: 2.198s
3: 2.172s
4: 2.058s
5: 2.141s
6: 4.411s
7: 10.294s
8: 10.781s
(...)
```
Note the high min/floor values to avoid logging flood on tests.
But for production this is a minor issue, so set a lower floor:
PROD_DEFAULT:
```
1: 10ms
2: 16ms
3: 65ms
4: 262ms
5: 1.089s
6: 4.096s
7: 10.852s
8: 10.116s
(...)
```
Closes https://github.com/fedimint/fedimint/issues/2263

refactor: limited reconnection delays using exp backoff

---

fedimint-core/src/admin_client.rs
fedimint-core/src/module/mod.rs
fedimint-server/src/config/api.rs
fedimint-server/src/net/api.rs

Makes it so we don't have to pass in auth twice in endpoints that need to read it.

refactor: expose auth in api context

---

.semgrep.all.yaml
crypto/aead/src/lib.rs
fedimint-cli/src/lib.rs
fedimint-core/src/util/mod.rs
fedimint-server/src/config/api.rs
fedimint-server/src/config/io.rs
fedimintd/src/distributed_gen.rs
fedimintd/src/fedimintd.rs
gateway/ln-gateway/src/client.rs

I've experienced a federation peer loosing private keys due
to accidentally submitting a setup form on an already running
federation.
Generally we should never overwrite files, unless this is really
the behavior we want, so ban `fs::write` and `File::create` via semgrep.
`#neveragain`

fix: overwriting existing files will lead to data loss

---

fedimint-bin-tests/Cargo.toml
flake.crane.nix
flake.nix

I don't see a big advantage of building it in CI, as it is already used for all tests anyway, but external users might want to consume it as a standalone binary.
Verified with:
```
nix build -L .#fedimint-bin-tests
```

chore: expose `fedimint-bin-tests` as a flake output

---

fedimint-bin-tests/src/main.rs
fedimint-cli/src/lib.rs
fedimint-core/src/admin_client.rs
fedimint-core/src/encoding/mod.rs
fedimint-server/src/consensus/mod.rs
fedimint-server/src/consensus/server.rs
fedimint-server/src/net/api.rs
integrationtests/tests/fixtures/mod.rs
integrationtests/tests/tests.rs

Fixes #2309
Note we upload the entire serialized epoch (which can be downloaded from the API), because it's both easier to get from the API and doesn't require additional P2P calls (we don't really know who to query).

feature: Allow forcing processing an epoch

---

fedimint-cli/src/ng.rs
fedimint-client/src/lib.rs
fedimint-core/src/db/mod.rs

* Allow building a client with a `Box<dyn IDatabase>` as its database. This allows runtime choice of the DB backend.
* Add a `Client::builder` method, I previously forgot

Client NG: allow building using dyn database and add `builder` method

---

scripts/lib.sh
scripts/pegin.sh

A recent change to the encoding of the wallet config caused the `config` section of `client.json` to be encoded as json. This broke the `pegin.sh` script since it relied on retrieving the `finality_delay` from the config.
These scripts are going away soon away with the shift to the rust based dev shells. This PR just hard codes the `finality_delay` in the bash scripts for now so that tmuxinator and fed-shell are not broken.

fix: hardcode finality delay in tmux/dev shell

---

devimint/src/main.rs
justfile
scripts/mprocs.sh
scripts/tmuxinator.sh

I sometimes forget the name of the mprocs dev tool (`fed-shell`). Renaming it to `mprocs` because that's easier to remember :)
Also, renamed `devimint tmuxinator` to `devimint dev-fed` since this is also used by `mprocs` and it calls a `dev_fed` function internally which is a nice name.
After the refactors I re-ran both `just mprocs` and `just tmuxinator` and both seemed to still work!

chore: improve naming of mprocs & tmuxinator

---

fedimint-testing/Cargo.toml

fix: fedimint-testing can't compile on its own

---

gateway/ui/src/index.tsx
gateway/ui/src/theme.tsx

This PR introduces theming to Gateway UI, as mentioned in #2129 
Before:
After:

Gateway UI Theming

---

fedimint-core/src/db/mod.rs

The notifications for ModuleDatabaseTransaction don't work at all. It doesn't call add_notification_key in insert,remove like DatabaseTransaction. 
Updated the test to catch the bug.

fix: notifications for ModuleDatabaseTransaction

---

fedimint-server/src/consensus/server.rs
fedimint-server/src/lib.rs
fedimint-testing/src/federation.rs
integrationtests/tests/fixtures/mod.rs

A couple small refactors to the consensus API to eliminate some boilerplate in tests and ensure the check of consensus hash will be tested.

Refactor: consensus api

---

fedimint-core/src/config.rs
fedimint-server/src/config/api.rs
fedimint-server/src/config/mod.rs
fedimint-testing/src/federation.rs
fedimintd/src/distributed_gen.rs
fedimintd/src/fedimintd.rs
fedimintd/src/lib.rs
fedimintd/src/ui.rs
integrationtests/tests/fixtures/mod.rs
modules/fedimint-ln-server/src/lib.rs

refactor: converts `ServerModuleGenParamsRegistry` from `ModuleGenRegistry` be `ModuleRegistry`
Eliminates `legacy_init_order_iter` from the server side (almost fully modularized!)
Removes a bunch of ugly code that existed just to pass the module id around.

refactor: converts ServerModuleGenParamsRegistry to ModuleRegistry

---

fedimint-core/src/config.rs
fedimint-core/src/module/mod.rs
modules/fedimint-dummy-common/src/config.rs
modules/fedimint-dummy-server/src/lib.rs
modules/fedimint-ln-common/src/config.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-common/src/config.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-common/src/config.rs
modules/fedimint-wallet-server/src/lib.rs

This refactor inlines some of the config functions to eliminate unnecessary indirection and move implementations to where it makes sense (on the server side).  This will also help us eventually replace the config module boilerplate with macros.

Refactor: Inline config functions

---

fedimint-client-legacy/src/api.rs
fedimint-client-legacy/src/api/fake.rs
fedimint-client/src/transaction/sm.rs
fedimint-core/src/api.rs
modules/fedimint-dummy-client/src/api.rs
modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-dummy-common/src/lib.rs
modules/fedimint-dummy-tests/tests/tests.rs
modules/fedimint-ln-client/src/api.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-wallet-client/src/api.rs

This removes the legacy ids from the new client APIs, one step closer to being fully modular.

refactor: remove legacy ids from the apis

---

fedimint-core/src/admin_client.rs
fedimint-server/src/config/api.rs
fedimint-server/src/config/io.rs
fedimint-testing/src/federation.rs
integrationtests/tests/fixtures/mod.rs

- Makes `get_consensus_config_gen_params` return all peers with `ServerStatus`
- Adds new statuses `SharingConfigGenParams`, `ReadyForConfigGen`, `ConfigGenFailed`, `VerifyingConfigs`
- Doesn’t fail when auth is unnecessarily passed in
- Returns all verification codes, leaves checking verification up to the UI
Also simplifies how we handle state.

feature: config gen modifications based on UI feedback

---

modules/fedimint-ln-client/src/pay.rs
modules/fedimint-ln-client/src/receive.rs

Follow on after https://github.com/fedimint/fedimint/pull/2400
https://github.com/fedimint/fedimint/pull/2390 broke new client and we didn't notice it because it's not well-tested yet.
You have to manually test this in mprocs / tmuxinator. Before this commit, `fedimint-cli ng ln-invoice` will never succeed. After this commit, it succeeds right after the invoice is paid.

fix: missing ln module id in ln client

---

Cargo.lock
fedimint-core/src/module/mod.rs
modules/fedimint-dummy-client/Cargo.toml
modules/fedimint-dummy-client/src/api.rs
modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-dummy-common/src/config.rs
modules/fedimint-dummy-common/src/lib.rs
modules/fedimint-dummy-server/src/db.rs
modules/fedimint-dummy-server/src/lib.rs
modules/fedimint-dummy-tests/tests/tests.rs

Improved some of the issues with the dummy module:
- Printing money is now a tx so it can output to any client primary module (e.g. for testing ecash) and will be faster
- The signature shares now sign a returned message to demonstrate consensus signing better

feature: improve the dummy module for testing

---

Cargo.lock
fedimintd/Cargo.toml

The askama_axum/derive is used by the `Template`, that said at version 0.2.1 it still uses askama 0.11.x, it seems that was the problem that prevented it to build due to conflicts.
- build(deps): bump askama from 0.11.1 to 0.12.0  (cherry-picked and rebased from https://github.com/fedimint/fedimint/pull/1915/commits/dea8a57da0f8352c0d069c8f1e1e032d8f63b132)
- build(deps): bump askama_axum from 0.2.1 to 0.3.0
**NOTE:** I have not tested it yet by running the setup UI locally
fixes #1915

build(deps): bump askama from 0.11.1 to 0.12.0 and askama_axum from 0.2.1 to 0.3.0

---

fedimint-core/src/core.rs
fedimint-core/src/module/mod.rs
fedimintd/src/lib.rs
modules/fedimint-dummy-common/src/config.rs
modules/fedimint-dummy-common/src/lib.rs
modules/fedimint-dummy-server/src/lib.rs
modules/fedimint-dummy-tests/tests/tests.rs
modules/fedimint-ln-common/src/config.rs
modules/fedimint-ln-common/src/lib.rs
modules/fedimint-ln-server/src/lib.rs
modules/fedimint-mint-common/src/config.rs
modules/fedimint-mint-common/src/lib.rs
modules/fedimint-mint-server/src/lib.rs
modules/fedimint-wallet-common/src/config.rs
modules/fedimint-wallet-common/src/lib.rs
modules/fedimint-wallet-server/src/lib.rs

To make life easier for module writers, this modifies a macro and adds a new macro so less boilerplate code is required to implement a module.

Remove boilerplate from our module common libs

---

fedimint-client/src/lib.rs
fedimint-client/src/sm/executor.rs

Allows clients to subscribe to all operations where progress is expected.

feat(client-ng): fetch active operations

---

devimint/src/federation.rs
devimint/src/lib.rs
devimint/src/main.rs
integrationtests/tests/tests.rs
scripts/lightning-reconnect-test.sh
scripts/test-ci-all.sh

This PR removes the flakey lightning gateway reconnect test and re-writes it using `devimint`.

fix: remove flaky lightning reconnect test

---

devimint/src/federation.rs
devimint/src/main.rs
scripts/run-ui.sh

This new option doesn't set the password because UI will need to set this, or `FM_LISTEN_UI` because this will block the config API from running.
Leaving as "draft" because fedimintd's password is currently required. So not setting `FM_PASSWORD` currently causes `fedimintd` to fail.

feat: devimint's run-ui command has an option to drive the new UI

---

devimint/src/main.rs
modules/fedimint-mint-client/src/oob.rs

Fixes: https://github.com/fedimint/fedimint/issues/2417
Issue is that `try_cancel_oob_spend` was only creating `MintInputStateMachine` and not `MintClientStateMachines::Input(MintInputStateMachine)`

fix: Client NG spend persists invalid state machine

---

fedimint-core/src/admin_client.rs
fedimint-core/src/api.rs
fedimint-server/src/config/api.rs
fedimint-server/src/net/api.rs

https://github.com/fedimint/fedimint/pull/2375 original goal was to add all the information to a single `status` endpoint, but at the time no good solution was found on how to merge both data. While creating the CLI command this simple and obvious solution appeared:
```rust
pub struct StatusResponse {
pub server: ServerStatus,
pub consensus: Option<ConsensusStatus>,
}
```
For instance in json:
```json
{
"consensus": {
"last_contribution": 14,
"peers_flagged": 0,
"peers_offline": 0,
"peers_online": 3,
"status_by_peer": {
"1": {
"connection_status": "Connected",
"flagged": false,
"last_contribution": 14,
"last_contribution_timestamp_seconds": 1683215023
},
"2": {
"connection_status": "Connected",
"flagged": false,
"last_contribution": 14,
"last_contribution_timestamp_seconds": 1683215023
}, …
```

refactor: Merge `status` and `consensus_status` endpoints

---

fedimint-core/src/admin_client.rs
fedimint-core/src/api.rs
fedimint-server/src/config/api.rs
fedimint-server/src/config/mod.rs
fedimint-server/src/consensus/server.rs
fedimint-server/src/net/api.rs

Based on UI feedback:
- Add current_id to “get_consensus_config_params”
- Make “get_verify_config_hash” available after start_consensus
- New “connection_code” endpoint, passed into “config” endpoint
- Write password to disk once configs are verified

Improvements to the config APIs

---

.tmuxinator.yml
Cargo.lock
devimint/Cargo.toml
devimint/src/federation.rs
devimint/src/lib.rs
devimint/src/main.rs
devimint/src/util.rs
devimint/src/vars.rs
fedimint-logging/src/lib.rs
scripts/build.sh
scripts/mprocs.sh
scripts/rust-tests.sh
scripts/tmuxinator.sh
scripts/user-shell.sh

important change is reducing build.sh and now beautiful typed env variables.
for a dev env prespective:
you can now enter the devimint environment.
say you want to run integration tests with real fixtures. You can do:
`devimint -d /tmp/foo external-daemons`
and in a different shell:
`eval "$(devimint -d /tmp/foo env)"`
and then `cargo test`

devimint cleanup

---

guardian-ui/src/components/SetConfiguration.tsx

Frontend had them ordered incorrectly which caused a panic when consensus was run:
```
2023-05-07T21:09:48.533139Z ERROR fedimint_core::db: error=Other decoding error: Error decoding blind message
thread 'main' panicked at 'Unrecoverable error when decoding the database value: Other(Error decoding blind message)', /Users/justin/work/fedimint-2/fedimint-core/src/db/mod.rs:1116:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
We need to get smarter about typing the module instance IDs on the frontend.

fix(guardian-ui): Correctly order module instance IDs

---

fedimint-client/src/sm/executor.rs
fedimint-client/src/transaction/sm.rs

`tokio::time::sleep` doesn't work in WASM

feat: tokio::time::sleep -> fedimint_core::task::sleep in Client NG

---

guardian-ui/README.md

README had incorrect instructions about how to run the servers. Behavior of `scripts/run-ui.sh` changed after https://github.com/fedimint/fedimint/pull/2377. By default it runs in a way that serves the old setup UI, but if you pass a `new` parameter to it, the config API will run which the new guardian UI needs.

Fix Guardian UI README

---

fedimint-client/src/lib.rs

Public `fedimint-client` functions return things like `ChronologicalOperationLogKey` and `OperationLogEntry` so it would be nice if these were public as well.

fix: make client db mod public

---

devimint/src/util.rs

Many of the executables called using the `cmd!(…)` macro are our own, if one panics having a backtrace is useful for debugging, thus setting the environment variable `RUST_BACKTRACE=1` for all calls seems reasonable (it shouldn't hurt other executables we call).

fix(devimint): activate rust backtraces by default

---

docs/database.md

Adds documentation on how to fix the DB migration tests when making a non-backwards compatible change (backwards compatible changes will need to write module specific migration code).

docs: Add Database Migration documentation

---

guardian-ui/src/GuardianApi.ts
guardian-ui/src/GuardianContext.tsx
guardian-ui/src/components/FederationDashboard.tsx
guardian-ui/src/components/RunDKG.tsx
guardian-ui/src/components/Setup.tsx
guardian-ui/src/components/SetupComplete.tsx
guardian-ui/src/types.tsx

* Implements a `SetupComplete` component for after you've run consensus
* Implements a placeholder `FederationDashboard` component that renders when your federation is running
* When you visit the page after setup, you will always be directed to this page
* We will need more APIs to actually make this page useful, but hopefully it will provide the federation join code and some basic status information going forward, maybe even administrative actions? #2451
* Fixes and improves `GuardianApi.startConsensus()`
* Properly tears down and restarts socket, previously it would keep trying to use the busted socket
* Retries up to 10 times with 1 second intervals to allow for slower restarts
* Returns the full `StatusResponse` from `GuardianApi.status()`
* Updated all places in code we used this …

Guardian UI - Setup completion flow

---

devimint/src/federation.rs
devimint/src/main.rs
docs/dev-running.md
fedimint-server/src/consensus/server.rs
fedimint-testing/src/gateway.rs
gateway/cli/src/main.rs
gateway/ln-gateway/src/rpc/rpc_client.rs
gateway/ln-gateway/src/rpc/rpc_server.rs
gateway/ln-gateway/tests/authentication_tests.rs
gateway/ln-gateway/tests/fixtures/mod.rs
gateway/ln-gateway/tests/integration_tests.rs

Some refactors to improve gateway testing:
- Can run gateway against feds with 1 peer (faster)
- Rename `RpcClient` to `GatewayRpcClient`
- Have `GatewayRpcClient` store the password and return types for easier testing

refactor: clean up gateway rpc client

---

fedimint-cli/src/ng.rs
fedimint-client/src/lib.rs
modules/fedimint-mint-client/src/lib.rs

Proof-of-concept for adding more meta data to operations, needs to be done for other ext traits too.

fix(mint-client): allow injecting user-specified meta into operations

---

Cargo.lock
fedimint-cli/Cargo.toml
fedimint-cli/src/ng.rs
fedimint-client/Cargo.toml
fedimint-client/src/lib.rs
fedimint-client/src/transaction/sm.rs
modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-dummy-client/src/states.rs
modules/fedimint-dummy-common/src/lib.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-client/src/pay.rs
modules/fedimint-ln-client/src/receive.rs
modules/fedimint-ln-common/src/lib.rs
modules/fedimint-mint-client/src/input.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-mint-common/src/lib.rs
modules/fedimint-wallet-client/src/lib.rs
modules/fedimint-wallet-common/src/lib.rs

- Returns the tx submit error so clients can see why a tx failed
- Refactors out common instance resources to eliminate boilerplate and help remove more legacy ids

Client refactor

---

fedimint-core/src/epoch.rs
fedimint-server/src/consensus/mod.rs
modules/fedimint-dummy-server/src/lib.rs

We combine threshold crypto signatures in a few places, this just refactors them into a single place.
Long-term we might move towards FROST instead or a better maintained library.

refactor: common combine sig code

---

scripts/pegin.sh

Recent changes to gateway-cli broke the pegin.sh script for gateways. Gateways in tmuxinator won't have ecash notes which makes testing a bit harder.

fix: Fix Gateway PegIn

---

devimint/src/federation.rs
devimint/src/main.rs
fedimint-cli/src/ng.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-client/src/pay.rs
modules/fedimint-mint-client/src/lib.rs

The current LN outgoing payment state machine has a few bugs:
- It calls the gateway's `pay_invoice` in the trigger function. Trigger functions need to be idempotent. Paying an invoice by calling the gateway is not idempotent. This can cause `pay_invoice` to be called multiple times if a different state is executed before `pay_invoice` completes. 
- `LnPay` does not wait for the change from the `MintOutput`. When executing from the CLI, this will cause the change to not be reflected after the outgoing payment, which causes the test to fail.
This PR changes:
- Moves calling the gateway's `pay_invoice` from the trigger function to the transition function.
- Outgoing payment state machine will not transition to funded until after the `LightningOutpoutOutcome` is accepted, so that the …

fix: LN Outgoing Payments not idempotent

---

fedimint-cli/src/ng.rs
fedimint-client/src/sm/executor.rs
fedimint-client/src/sm/mod.rs
fedimint-client/src/transaction/sm.rs
modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-dummy-client/src/states.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-mint-client/src/lib.rs

Originally from #2416 but making this a separate PR since multiple others could use it and I don't want to block.

fix: define canonical encoding for `OperationId`

---

Cargo.lock
devimint/Cargo.toml
devimint/src/main.rs
fedimint-cli/src/lib.rs
fedimint-cli/src/ng.rs
modules/fedimint-ln-client/src/lib.rs

`LnInvoice` in Client NG is currently blocking. It will wait for the invoice to be paid before returning. This is difficult for CLI testing, since it requires a separate thread to pay the invoice. The old client fixed this by having two CLI commands `LnInvoice` and `WaitInvoice`. `LnInvoice` would only generate the payment request and `WaitInvoice` would actually block on the `IncomingContract` to receive the ecash notes.
This PR makes a similar change to the client NG. It adds a new flag `wait_for_payment` that allows `LnInvoice` to either be blocking or non-blocking. `WaitInvoice` will now generate the state machine to wait for the `IncomingContract` to be paid.
This PR also adds lightning client NG tests for sending and receiving from the CLN and LND gateway.

feat: WaitInvoice and LN Client NG CLI tests

---

scripts/user-shell.sh

It's annoying that old client has funds in tmuxinator, but new client doesn't.

feat: user-shell.sh funds ClientNG

---

justfile
misc/mprocs-ui.yaml

`just run-ui` brings up mprocs with a 2 instance federation via `run-ui.sh` and 2 instances of the Guardian UI

feat: mprocs setup for guardian-ui dev

---

flake.nix

Otherwise `yarn install` fails, I suppose everyone working on the UI had `nodejs` installed outside nix.

fix: add `nodejs` to ui dev shell

---

gateway/ln-gateway/src/actor.rs
modules/fedimint-ln-common/src/lib.rs
modules/fedimint-ln-tests/tests/tests.rs

Current code fails because it re-registers with a `valid_until` value that doesn't get updated at all.
@okjodom this would be a great thing to cover in your new gateway tests. Should probably make `GW_ANNOUNCEMENT_TTL` a variable passed in to `gatewayd`. 
This currently doesn't have any test coverage so you have to validate the fix manually (made [issue to add coverage](https://github.com/fedimint/fedimint/issues/2516)). To validate the bug, set `GW_ANNOUNCEMENT_TTL` to 1 second on master and run tmuxinator. Run `gateway-cli list-gateways` and there won't be any. Do the same on this branch and there should be 2.

feat: fix gateway registration

---

Cargo.lock
fedimint-cli/src/ng.rs
fedimint-client/Cargo.toml
fedimint-client/src/backup.rs
fedimint-client/src/lib.rs
fedimint-client/src/module/mod.rs
fedimint-client/src/sm/executor.rs
fedimint-client/src/sm/mod.rs
fedimint-client/src/transaction/sm.rs
fedimint-core/src/api.rs
fedimint-core/src/backup.rs
fedimint-core/src/core.rs
fedimint-core/src/core/backup.rs
fedimint-core/src/db/mod.rs
fedimint-core/src/lib.rs
fedimint-logging/src/lib.rs
fedimint-server/src/net/api.rs
modules/fedimint-mint-client/Cargo.toml
modules/fedimint-mint-client/src/backup.rs
modules/fedimint-mint-client/src/backup/recovery.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-mint-client/src/output.rs
modules/fedimint-mint-common/src/lib.rs

Port of the ecash recovery code to new client, now generalized for all client modules (but implemented only for mint module).
Includes `backup`, `restore`, `wipe` command for `fedimint-cli ng`.
The old-client ecash code is still in place. New client code does not have any tests yet, but since the core logic is largely unmodified it should work OK.
I am able to succesfully backup, wipe and restore with a minor issue of `fedimint-cli` not waiting for all the state machines to finish. But I think we should address it in another PR.

feat: module (mint in particular) backup for new client

---

devimint/src/main.rs

Fixes #2341. I think the logic is the wrong way around and we test the peg-out not succeeding, which normally works because it's too slow. But if it happens faster than the check code is hit (due to scheduling) then this test fails because the peg-out succeeded.

Fix flaky peg-out test

---

Cargo.lock
fedimint-cli/src/ng.rs
fedimint-client/src/lib.rs
fedimint-client/src/module/mod.rs
fedimint-client/src/transaction/sm.rs
modules/fedimint-dummy-client/Cargo.toml
modules/fedimint-dummy-client/src/lib.rs
modules/fedimint-dummy-client/src/states.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-client/src/pay.rs
modules/fedimint-ln-client/src/receive.rs
modules/fedimint-ln-tests/tests/tests.rs
modules/fedimint-mint-client/src/input.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-mint-client/src/oob.rs
modules/fedimint-mint-client/src/output.rs
modules/fedimint-mint-tests/tests/tests.rs
modules/fedimint-wallet-client/src/api.rs

This PR adds a generic way of awaiting a primary modules output to be finalized. Often times, after the output outcome happens on the server side, the client needs to wait on some additional operations on the client side (like claiming ecash notes as change from a Lightning transaction).
Right now we don't have a good way to wait on change. This PR adds a function `await_primary_module_output_finalized` that awaits on an outpoint to be finalized. This PR also changes `finalize_and_submit_transaction` to return an `Option<OutPoint>` which will contain the `OutPoint` of the change (if there is change).
Fixes: https://github.com/fedimint/fedimint/issues/2495

feat: await primary module change

---

Cargo.lock
fedimint-cli/src/ng.rs
fedimint-client/Cargo.toml
fedimint-client/src/lib.rs
fedimint-client/src/sm/mod.rs
fedimint-core/src/db/mod.rs
modules/fedimint-ln-client/src/lib.rs
modules/fedimint-ln-tests/tests/tests.rs
modules/fedimint-mint-client/src/lib.rs
modules/fedimint-mint-tests/tests/tests.rs

Subscribing to operation updates is expensive, if we just want to know what the outcome of a finished operation was we can now read it from the operation log entry.

Cache client operation outcomes

---

devimint/src/main.rs
fedimint-server/src/lib.rs
fedimintd/src/fedimintd.rs

If it's the new UI, then we want ws:// instead of http://
The logging would be confusing for anyone unfamiliar with this nuance.

fix(devimint): use correct protocol in logging
