fedimint/fedimint

- fedimint-testing/src/ln/mod.rs
- gateway/ln-gateway/src/lightning/lnd.rs
- gateway/ln-gateway/tests/integration_tests.rs
Fixes: https://github.com/fedimint/fedimint/issues/4734
Fixes: https://github.com/fedimint/fedimint/issues/4716
We need to keep the `pay` implementation around until https://github.com/fedimint/fedimint/issues/278 is fully fixed.
> chore: remove legacy pay from LND

- README.md
Fixes [4777](https://github.com/fedimint/fedimint/issues/4777)
> Changed Nix installer to DeterminateSystems to avoid enabling flakes

- fedimint-core/src/task.rs
- fedimint-core/src/task/waiter.rs
see other dependent PRs for usage 
used by #4784 and #4768
> feat: add Waiter helper in fedimint-core

- devimint/src/cli.rs
- devimint/src/devfed.rs
- devimint/src/federation.rs
- devimint/src/tests.rs
Internal client that didn't join the Federation is not very useful.
Re #4798
> chore(devimint): make the internal client a Jit value, after it joined

- fedimint-core/src/module/mod.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-empty-client/src/lib.rs
- modules/fedimint-empty-server/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-meta-client/src/lib.rs
- modules/fedimint-meta-server/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-unknown-server/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
lets try with simple trait first
the impl looks simple, the definition is slightly complicated.
> chore: remove async trait

- devimint/src/cli.rs
- fedimint-core/src/task.rs
> fix(devimint): shutdown on success sequence looks weird

- devimint/src/cli.rs
- devimint/src/external.rs
- devimint/src/federation.rs
- devimint/src/gatewayd.rs
- devimint/src/tests.rs
- devimint/src/util.rs
Backports https://github.com/fedimint/fedimint/pull/4749
> [Backport releases/v0.3] chore(devimint): increase default poll timeout from 30s to 60s

- fedimint-cli/src/lib.rs
> fix: retry in wait-block-count

- .config/semgrep.yaml
- fedimint-client/src/lib.rs
- fedimint-logging/src/lib.rs
- modules/fedimint-meta-server/src/lib.rs
On top of #4815 (inspired by some changes there).
>  chore: clarify client vs server/core side logging 

- gateway/ln-gateway/src/lib.rs
>  chore: format start_gateway 

- Cargo.lock
> chore: bump h2 [backport]

- gateway/cli/src/main.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-common/src/config.rs
Addresses this issue https://github.com/fedimint/fedimint/issues/3961
This PR encompass the following changes:
- ~~updates the `connect-fed` sub command in `gateway-cli`, by adding a routing fee parameter~~
- update the `set-configuration` sub command in `gateway-cli`, by adding routing fees by federation id
- refactor the update configuration command to write the configuration data of gateway and federations in the same transaction (this is a little bit out of scope, if does not make sense I can revert it)
> gateway can charge fees per federation

- modules/fedimint-ln-client/src/lib.rs
allows impls to ignore non vetted gateways for example
> feat: gateway filter for update_gateway_cache_continuously

- fedimint-core/src/encoding/mod.rs
Getting the last key in the map is `O(log N)`, so in theory previous version scaled better faster. In practice, for typical map sizes it could be faster, thought in practice I don't think it matters (our keys are typically), and it just avoids `Clone` bound there and I think less state is simpler.
> chore: avoid cloning keys while deserializing maps

- fedimint-core/src/task/jit.rs
Only the first caller to `Jit::get_try` can get the original error, but we can actually return a string-copy of it to other callers, which in most cases should be good enough.
The whole complication here allows retaining the original error (including source chain, backtrace, etc.) which might be useful when using in more concrete use-cases than just starting services in Devimint.
> chore(jit-values): return string-copy of the original error

- fedimint-server/src/consensus/server.rs
Make it relatively large, just to detect and unstuck modules that really got stuck.
> chore: add a timeout to polling for consensus items

- fedimint-core/src/util/mod.rs
> fix: use u64 for attempts in fedimint retry

- fedimint-load-test-tool/src/main.rs
May help on https://github.com/fedimint/fedimint/issues/4917
> chore: add more debugging to messages to load-test-tool

- crypto/tbs/Cargo.toml
- fedimint-client/src/backup.rs
- fedimint-core/src/config.rs
- fedimint-core/src/encoding/mod.rs
- fedimint-core/src/lib.rs
- fedimint-derive/src/lib.rs
> chore: add better error reporting to derived `Decodable` trait impls

- Cargo.lock
- fedimint-core/src/bitcoin_migration.rs
- fedimint-testing/Cargo.toml
- fedimint-testing/src/gateway.rs
- fedimint-testing/src/ln/mock.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
- modules/fedimint-mint-tests/Cargo.toml
- modules/fedimint-mint-tests/tests/tests.rs
> chore(deps): bump secp256k1 from 0.24.3 to 0.27.0 for fedimint-mint-tests

- Cargo.lock
- fedimint-testing/Cargo.toml
- fedimint-testing/src/gateway.rs
- fedimint-testing/src/ln/mock.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
> chore(deps): bump secp256k1 from 0.24.3 to 0.27.0 for fedimint-testing

- fedimint-api-client/src/api.rs
Follow up to nits in https://github.com/fedimint/fedimint/pull/4929
> chore(client-api): minor follow-up fixes after review 

- .gitignore
- devimint/src/cli.rs
- devimint/src/devfed.rs
- devimint/src/external.rs
- devimint/src/federation.rs
- devimint/src/lib.rs
- devimint/src/util.rs
- devimint/src/vars.rs
- fedimint-bitcoind/src/bitcoincore.rs
- fedimint-bitcoind/src/lib.rs
- fedimint-core/src/envs.rs
- fedimint-server/src/consensus/server.rs
- fedimint-testing/src/fixtures.rs
- fedimintd/src/fedimintd.rs
- modules/fedimint-wallet-client/src/lib.rs
I need a way to verify certain behaviors manually between versions, etc. Similiar to upgrade tests etc.
It occurred to me that it should be possible to just start devimint skipping all the DKGs and other setups, and it should be relatively easy. So I implemeted it.
One blocker that I've hit was inability to tell fedimintd to use certain URL to connect to bitcoind, instead of whatever was added to the config. I made new env variables that can be used to force bitcoind kind&url. The way existing env vars are working is confusing (they are only used as a default for DKG, so I renamed them while at it (with backward-compat.  of course).
Another blocker was that on killing devimint, we send `kill -9` right away, which makes `bitcoind` not get any chance to flush database to disk, and thus lose …
>  feat(devimint): start from a previous state (skip setup) 

- devimint/src/federation.rs
- devimint/src/federation/config.rs
- devimint/src/tests.rs
- fedimintd/src/fedimintd.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-common/src/config.rs
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
> feat: charge deposit fees by default to counter dust attacks

- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/gateway_module_v2/send_sm.rs
- gateway/ln-gateway/src/lib.rs
- modules/fedimint-lnv2-client/src/lib.rs
This pr makes the design choice that errors returned by send_payment and create_invoice remain strings instead of typed error since they are not intended to be shown to the user but only serve debugging purposes. 
The errors are either due to programming errors or only occurs in theoretically possible but unlikely timing scenarios like
* The user checks an invoice for expiration and its not yet expired but when the gateway checks it a second later it is.
* The user fetches the fees from the gateway and the consensus block count from the federation to create an outgoing contract but then one of he two is unreachable for the client for at least 144 blocks such that the contract is cancelled once the gateway and/or federation come back online and the remaining timelock delta is not …
> fix: enable cancellation for checks with inherent timing assumptions

- fedimint-client/src/module/init/recovery.rs
- fedimint-core/src/api.rs
>  fix(recovery): can't recover without all server-side modules  (backport v0.3)

- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-lnv2-client/src/send_sm.rs
As far as I can test, closes https://github.com/fedimint/fedimint/issues/4195
> chore: more context on invoice payment errors

- devimint/src/external.rs
Fixes https://github.com/fedimint/fedimint/issues/4988
Context for the race condition and fix is in the associated issue.
> fix(devimint): set global channel policy before opening channel

- .github/dependabot.yml
> chore(ci): make dependabot bother us less often

- fedimint-server/src/net/peers.rs
> chore(ci): speed up test_connect

- fedimint-api-client/src/api.rs
- fedimint-api-client/src/lib.rs
> chore(fedimint-api-client): cleanup weird APIs

- modules/fedimint-mint-client/Cargo.toml
- modules/fedimint-mint-client/src/input.rs
- modules/fedimint-mint-client/src/oob.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-wallet-client/src/deposit.rs
> fix(docs): rendering of some mermaid charts

- fedimint-server/src/consensus/server.rs
Useful for debugging, especially tests.
> chore: add a span over consensus main loop with the peer id

- fedimint-build/src/lib.rs
> chore(doc): document `fedimint-build`

- Cargo.lock
- modules/fedimint-wallet-client/Cargo.toml
- modules/fedimint-wallet-common/Cargo.toml
- modules/fedimint-wallet-common/src/txoproof.rs
- modules/fedimint-wallet-server/Cargo.toml
> chore: remove validator dependency

- .github/dependabot.yml
> fix: dependabot.yml (a bit, at least)

- .github/workflows/ci-nix.yml
Prompted by the difficulty in merging #4968
> chore: bump build timeout

- flake.nix
- nix/modules/README.md
- nix/modules/fedimintd.nix
> feat(nix): expose fedimintd NixOS module (v0.3 backport)

- Cargo.lock
- fedimint-api-client/Cargo.toml
- fedimint-client/src/backup.rs
- fedimint-server/src/consensus/server.rs
> chore(deps): bump bitcoin from 0.29.2 to 0.30.2 for fedimint-api-client

- .github/workflows/validate-dependabot.yaml
> chore(ci): validate dependabot.yml

- fedimint-api-client/src/api.rs
I noticed `request_admin_no_auth` still broadcasted it's requests using `request_current_consensus`, instead of `request_single_peer_federation`, which is how `request_admin` works.
> chore: dont broadcast request_admin_no_auth

- fedimint-testing/src/gateway.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-client/src/pay.rs
Breaking out of #5019 commits that do not introduce weird failures, while the rest will need some more debugging.
> chore: speed-up gateway integration tests

- docs/dev-env.md
One of the main problems with Nix installation is that the official version requires you to change some settings in order to use `nix develop`. On the other hand, if you make a mistake during installation, uninstalling Nix can be challenging (as also mentioned as a con here: [https://nixos.org/download/](https://nixos.org/download/)). I faced this myself, so I'm recommending some of the uninstallation methods that worked for me.
So, I have added an `Uninstallation` section in the `dev-setup.md` so that if someone installs Nix incorrectly or wants to uninstall it, they can do so using:
1. Official method
2. Brute-force method
Additionally, I have updated the recommended method to use the `Determinate Nix Installer` so that setting up the development environment goes smoothly for anyone …
> docs: updating dev-env.md regarding nix installation

- devimint/src/tests.rs
- scripts/tests/test-ci-all.sh
>  fix(ci): not running enough tests in parallel 

- .github/workflows/ci-backwards-compatibility.yml
- .github/workflows/ci-nix.yml
- .github/workflows/daily.yml
- .github/workflows/docs.yml
- .github/workflows/hourly-run.yml
- scripts/ci/run-in-fs-dir-cache.sh
> chore: switch to self-hosted runners

- scripts/ci/run-in-fs-dir-cache.sh
> fix(ci): self hosted runner dir running out of space

- .github/workflows/docs.yml
> fix(ci): self hosted runner failing to push docs via git

- .github/workflows/ci-backwards-compatibility.yml
- scripts/tests/test-ci-all.sh
> chore(ci): disable lightning_reconnect_test

- devimint/src/tests.rs
> fix: skip very slow test on old Fedimint

- .github/workflows/ci-backwards-compatibility.yml
- .github/workflows/ci-nix.yml
It's hard to land them one by one.
> chore(ci): bunch of fixes

- devimint/src/cfg/lnd.conf
- devimint/src/devfed.rs
>  chore(devimint): fix LN channel on starting from previous state 

- devimint/src/tests.rs
- scripts/tests/test-ci-all.sh
Please land #5112 before this one, it might (maybe, hopefully, possibly...) improve lnd startup times too.
>  chore: re-enable lightning reconnect test 

- fedimint-testing/src/btc/mock.rs
> refactor: FakeBitcoinTest looks like it's asking for a deadlock

- devimint/src/external.rs
- devimint/src/tests.rs
> fix(devimint): remove some short polling places

- Cargo.lock
- fedimint-load-test-tool/Cargo.toml
- fedimint-load-test-tool/src/main.rs
> chore(deps): bump bitcoin from 0.29.2 to 0.30.2 for fedimint-load-test-tool

- .github/workflows/daily.yml
Replace with https://github.com/rustsec/audit-check
> fix(ci): actions-rs/audit-check is unmaintained

- .github/workflows/daily.yml
> fix(ci): just run audit-check on ubuntu-latest

- Cargo.lock
- fedimint-wasm-tests/Cargo.toml
- fedimint-wasm-tests/src/lib.rs
> chore(deps): bump gloo-net from 0.2.6 to 0.5.0

- Cargo.lock
- fedimint-core/Cargo.toml
- fedimint-core/src/invite_code.rs
> chore(deps): bump bech32 from 0.9.1 to 0.11.0

- devimint/src/external.rs
> fix(devimint): reset chan policy on retry

- devimint/src/tests.rs
> chore(backward-compat-test): skip recoveryttool test for old fedimintd

- Cargo.lock
- fedimint-client/Cargo.toml
- fedimint-client/src/lib.rs
- fedimint-core/src/config.rs
- fedimint-core/src/core/backup.rs
- fedimint-server/Cargo.toml
- fedimint-server/src/atomic_broadcast/keychain.rs
- fedimint-server/src/config/distributedgen.rs
- fedimint-server/src/net/api.rs
- modules/fedimint-mint-client/Cargo.toml
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-mint-common/Cargo.toml
- modules/fedimint-mint-common/src/common.rs
- modules/fedimint-mint-server/Cargo.toml
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-mint-tests/Cargo.toml
- recoverytool/Cargo.toml
- recoverytool/src/main.rs
> chore(deps): bump secp256k1 from 0.24.3 to 0.27.0 across multiple packages

- devimint/src/cfg/lnd.conf
- devimint/src/external.rs
There's some LND bug that makes it flacky, and turns out we are only doing it to make 1msat payement work, which we don't even use in our test suite anyway.
> chore: don't set up channel policy

- scripts/tests/test-ci-all-backcompat.sh
> chore(backward-compat): disable `h2` logs that spam the output

- Cargo.lock
- fedimint-bitcoind/Cargo.toml
- fedimint-bitcoind/src/bitcoincore.rs
- fedimint-bitcoind/src/electrum.rs
- fedimint-bitcoind/src/esplora.rs
- fedimint-bitcoind/src/lib.rs
- fedimint-testing/Cargo.toml
- fedimint-testing/src/btc/mock.rs
- modules/fedimint-wallet-client/src/deposit.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
> chore(deps): bump bitcoin from 0.29.2 to 0.30.2 for fedimint-bitcoind

- modules/fedimint-wallet-client/src/lib.rs
> fix(ci): workaround a flaky test

- fedimint-server/src/config/mod.rs
> chore: in testing run with ~10s session time

- devimint/src/external.rs
- devimint/src/gatewayd.rs
- docs/gateway.md
- fedimint-testing/src/ln/mock.rs
- fedimint-testing/src/ln/real.rs
- gateway/cli/src/main.rs
- gateway/ln-gateway/proto/gateway_lnrpc.proto
- gateway/ln-gateway/src/bin/cln_extension.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/cln.rs
- gateway/ln-gateway/src/lightning/lnd.rs
- gateway/ln-gateway/src/lightning/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
Requires #4514
Add `lightning list-active-channels` command to gateway CLI
> Gateway liquidity api can list active channels

- Cargo.lock
- Cargo.toml
- crypto/derive-secret/Cargo.toml
- crypto/tbs/Cargo.toml
- crypto/tpe/Cargo.toml
- fedimint-core/Cargo.toml
- fedimint-server/Cargo.toml
- modules/fedimint-lnv2-common/Cargo.toml
- modules/fedimint-lnv2-server/Cargo.toml
- modules/fedimint-mint-tests/Cargo.toml
> chore(deps): update bls12_381 and related deps

- scripts/tests/backend-test.sh
- scripts/tests/test-ci-all.sh
> fix(test-ci-all): typo leading to duplicate test

- scripts/tests/test-ci-all.sh
> chore(ci): run more tests at the same time

- devimint/src/cli.rs
They are fake anyway, why so stingy?
> chore: peg-in more funds in devimint setup

- Cargo.lock
- Cargo.toml
- fedimint-core/Cargo.toml
- modules/fedimint-mint-client/Cargo.toml
- modules/fedimint-mint-client/src/backup.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/client_db.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-mint-tests/tests/tests.rs
> refactor(mint-client): `SpendableNoteUndecoded` faster note handling

- fedimint-server/src/net/peers.rs
- fedimint-server/src/net/peers_reliable.rs
> fix(server): panic when there are no peers

- modules/fedimint-wallet-server/src/lib.rs
The consensus logic is not actually changed by this pr, as None and Some(0) returned by consensus_block_count do not trigger a sync, so we might as well just replace any None with a 0 to begin with.
> cleanup wallet sync logic

- fedimint-client/src/sm/notifier.rs
- modules/fedimint-wallet-client/src/lib.rs
>  fix(client): deduplicate events in ModuleNotifier::subscribe 

- devimint/src/federation.rs
- devimint/src/tests.rs
> chore(test): more logging to debug #5163

- fedimint-core/src/util/update_merge.rs
This PR adds unit test fin fedimint/fedimint-core/src/util/update_merge.rs and closes #5122
> tests: added unit test in fedimint-core/src/util/update_merge.rs

- nix/modules/fedimintd.nix
Backport of #5188 to `releases/v0.3`.
> [Backport releases/v0.3] chore(nix-module): improvements

- fedimint-client/src/sm/executor.rs
- fedimint-core/src/transaction.rs
- modules/fedimint-mint-client/src/input.rs
> fixes and debugging improvements

- .cargo/config.toml
- .config/semgrep.yaml
- fedimint-core/src/runtime.rs
- flake.nix
Backport of #5051 to `releases/v0.3`.
> [Backport releases/v0.3] fix: remove tokio_unstable

- fedimint-rocksdb/src/lib.rs
While investigating #5195 I came across the idea that RocksDB may be losing data in case of unclean shutdowns. While I don't think there's a high probability for that causing #5195, it still seems worth fixing. @m1sterc001guy lmk if I misunderstood something.
See WAL docs: https://github.com/facebook/rocksdb/wiki/WAL-Performance
<p align="center">
&nbsp; &nbsp; &nbsp; &nbsp; 
</p>
> fix: make RocksDB maximally safe

- fedimint-cli/src/lib.rs
> chore(cli): no need to log what we are already printing out

- .github/workflows/ci-backwards-compatibility.yml
- .github/workflows/hourly-run.yml
> fix(ci): disable uploading failed nix build dirs

- fedimint-server/src/net/api.rs
> chore(server): checking tx submission should be atomic

- modules/fedimint-mint-client/src/lib.rs
> chore(mint-client): assert note was deleted on spend

- modules/fedimint-ln-client/src/lib.rs
> fix: typed error for pay_bolt11_invoice

- fedimint-server/src/config/api.rs
- fedimint-server/src/lib.rs
Not writing to disk in the ConfigGenApi  makes it easier to reason about the behaviour of the ConfigGenApi struct as it is conceptually encapsulated. Now FedimintServers behaviour only depends on files that it has written to disk itself while ConfigGenApi has no side effects. Furthermore, a crashed config gen starts from a clean slate and does not have to deal with potential remnants.
> simplify: do not stage config

- modules/fedimint-mint-client/src/lib.rs
> fix: typed error for reissue external notes

- modules/fedimint-mint-client/src/lib.rs
Backport of #5236 to `releases/v0.3`.
> [Backport releases/v0.3] fix: typed error for reissue external notes

- gateway/ln-gateway/src/lib.rs
Adds function level comments to `lib.rs` in the gateway and removes two unused functions.
> chore: add comments to gateway

- Cargo.lock
- fedimint-logging/src/lib.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-mint-common/src/lib.rs
- modules/fedimint-mint-server/Cargo.toml
- modules/fedimint-mint-server/src/lib.rs
> chore: better logging & error to track lifetime of a note (client & server side)

- fedimint-core/src/module/mod.rs
Mostly about adding an ID, to help filter interleaved logging messages. But also I've noticed there was another span already there, just one that was not using `LOG_` constants.
> chore: better request handling logging

- fedimint-client/src/sm/executor.rs
- fedimint-core/src/runtime.rs
- fedimint-core/src/task.rs
- fedimint-core/src/task/jit.rs
- fedimint-logging/src/lib.rs
> chore: logging improvements

- Cargo.lock
- fedimint-server/Cargo.toml
- fedimint-server/src/atomic_broadcast/keychain.rs
- fedimint-server/src/atomic_broadcast/spawner.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/consensus/server.rs
- fedimint-server/src/db.rs
- fedimint-server/src/net/api.rs
- fedimint-server/src/net/peers.rs
This pr bundles a few small improvements in a larger effort to clean up and refactor Fedimint Server.
> Small improvements to Fedimint Server

- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/consensus/server.rs
- fedimint-server/src/net/api.rs
> chore(server): better logging on tx processing

- fedimint-testing/src/fixtures.rs
- flake.lock
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-server/src/metrics.rs
> chore: upate rust toolchain to 1.78

- fedimint-client/src/lib.rs
> chore(client): log finalized txes

- devimint/src/cli.rs
- devimint/src/external.rs
- devimint/src/main.rs
- devimint/src/vars.rs
- fedimint-testing/src/federation.rs
- fedimint-testing/src/fixtures.rs
- utils/portalloc/src/data.rs
- utils/portalloc/src/data/dto.rs
- utils/portalloc/src/lib.rs
>  fix(ci): running out of ports due to port range fragmentation 

- fedimint-server/src/config/api.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/lib.rs
- fedimintd/src/fedimintd.rs
Refactor: remove FedimintServer struct, turn run method in standalone function
> Refactor: remove unnecessary FedimintServer struct

- nix/modules/fedimintd.nix
> [Backport releases/v0.3.1] chore(nix-module): improvements

- fedimint-core/src/db/mod.rs
- fedimint-rocksdb/src/lib.rs
Backport of #5279 to `releases/v0.3`.
> [Backport releases/v0.3] fix: snapshot level isolation violations 

- .config/nextest.toml
- nix/flakebox.nix
> chore(ci): increase test run limits only for ccov runs

- fedimint-dbtool/src/dump.rs
- fedimint-server/src/atomic_broadcast/backup.rs
- fedimint-server/src/config/api.rs
- fedimint-server/src/consensus/api.rs
- fedimint-server/src/consensus/db.rs
- fedimint-server/src/consensus/engine.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/lib.rs
- fedimint-server/src/net/api.rs
- modules/fedimint-lnv2-server/src/lib.rs
- recoverytool/src/main.rs
Just moving some code around. Should be one of the last server cleanup / refactor prs.
> Cleanup Server II

- fedimint-core/src/encoding/mod.rs
- fedimint-derive/src/lib.rs
Fixes #5296. When removing the first variant of an enum we'd normally need to migrate all other variants to change their variant index. This is unnecessary work and we can just leave that index vacant by annotating the others with explicit indices.
> feat: variant index annotations for encodable enums

- fedimint-api-client/Cargo.toml
- fedimint-bip39/Cargo.toml
- fedimint-bitcoind/Cargo.toml
- fedimint-build/Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-core/Cargo.toml
- fedimint-dbtool/Cargo.toml
- fedimint-derive/Cargo.toml
- fedimint-load-test-tool/Cargo.toml
- fedimint-logging/Cargo.toml
- fedimint-metrics/Cargo.toml
- fedimint-rocksdb/Cargo.toml
- fedimint-server/Cargo.toml
- fedimint-testing/Cargo.toml
- fedimint-wasm-tests/Cargo.toml
- fedimintd/Cargo.toml
- fuzz/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/ln-gateway/Cargo.toml
> fixes package version fields

- modules/fedimint-ln-client/src/lib.rs
I'd really like to see the operation id of generated invoices when debugging client problems and added some other useful information too.
> chore: add logging to invoice generation

- .github/workflows/ci-backwards-compatibility.yml
- .github/workflows/ci-nix.yml
Wiki page that will act as a dashboard: https://github.com/fedimint/fedimint/wiki/CI-performance-tracking
Infra commit setting up the server side: https://github.com/fedimint/fedimint-infra/commit/47f61b3046b6d8ae07e28a597a65218c32702873
> feat: track some CI times in a perfitd

- fedimint-core/src/db/mod.rs
> chore: debug assert for overwrite existing values in db

- Cargo.lock
- Cargo.toml
- devimint/Cargo.toml
- devimint/src/tests.rs
- fedimint-metrics/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-lnv2-client/Cargo.toml
- modules/fedimint-lnv2-common/Cargo.toml
- modules/fedimint-lnv2-server/Cargo.toml
- modules/fedimint-lnv2-tests/Cargo.toml
>  chore(deps): bump the patch group with 6 updates

- .github/workflows/ci-backwards-compatibility.yml
- .github/workflows/ci-nix.yml
> chore: fix perfit binary reference

- .github/workflows/ci-backwards-compatibility.yml
- .github/workflows/ci-nix.yml
This should ignore failures to send and add a bit of logging, just in case we're debugging something around it.
> chore: update perfit

- fedimint-core/src/net/mod.rs
- fedimint-core/src/util/mod.rs
- fedimint-server/src/net/peers.rs
Backport of #5311 to `releases/v0.3`.
> [Backport releases/v0.3] chore: port in url handling improvements

- fedimint-api-client/src/api.rs
- fedimint-client/src/transaction/sm.rs
- fedimint-core/src/transaction.rs
- fedimint-server/src/consensus/api.rs
- modules/fedimint-dummy-tests/tests/tests.rs
We introduce a newtype to to highlight the similarities to OutputOutcome.
> refactor: introduce TransactionSubmissionOutcome newtype

- fedimint-client/src/sm/executor.rs
> chore: add more logging when state machines are being added

- Cargo.toml
- devimint/Cargo.toml
- fedimint-server/Cargo.toml
- gateway/integration_tests/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-dummy-tests/Cargo.toml
- modules/fedimint-empty-client/Cargo.toml
- modules/fedimint-empty-server/Cargo.toml
- modules/fedimint-ln-tests/Cargo.toml
- modules/fedimint-lnv2-tests/Cargo.toml
- modules/fedimint-mint-tests/Cargo.toml
- modules/fedimint-wallet-tests/Cargo.toml
Some trivia: in Helix, you can select bunch of deps, press `|`, `sort`, `Enter` and get all deps sorted.
> chore: Cargo.toml cleanup

- fedimint-derive/src/lib.rs
I was fuzzing something, and investigating certain failure (which turned out to be not an issue after all), but I needed a bit better decoding error, so I added it.
> chore: some more informative decoding errors

- Cargo.lock
- Cargo.toml
- fedimint-core/src/core.rs
- fuzz/Cargo.toml
- fuzz/src/bin/consensus_item.rs
- fuzz/src/lib.rs
One of the most interesting types to fuzz.
Re #287 , a quite old issue.
> chore: fuzz consensus item de/encoding

- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/sm/executor.rs
Allows debugging state machine runs:
```
$ fedimint-cli ln-invoice --amount 42
2024-05-24T15:45:31.581799Z  WARN fedimint_cli::client: Command deprecated. Use `fedimint-cli module ln invoice` instead.
{
"operation_id": "168081e9aecf41810939c2edfa3f96b0dd033b9c400ef82744d3172577bd403e",
"invoice": "lnbcrt420p1pn9pdsmdqqpp5z6qgr6dweaqczzfectkl50ukkrwsxwuugq80sf6y6vtj2aaagqlqsp5stlsv0w70qps7uuhvtsarrmkgzvvldgl5a39rfhfellqah0fpmrs9qrsgqcqpjnp4qdu7qew9u9zxjchtsryrhttgmmh4wh4qa8utzf4hs7k480sz0q457xqyz5vqrzjqv4j30k3sqvykdc78pu87jy0dv6g4y7r4wtywhhn3z9xy4nh5awssqqqqqqqqqqqqyqqqqqqqqqqqqqqrcr9yqvd0wec2kv8tagz90g39mp8cgvfzulte2uvsfwgyhuf2k9gd3c95zqqqwqqqqqgqqyqqqqlgqqqqqqgq2qpjk2976xqpsjehrcu8sl6g3a4nfz5ncw4ev3677wyg5cjkw7n46zqqqqqqqqqqqqqsqqqqqqqqqqqqqq0qpyuheyt2yecmy4jwurmdjnjneh2n2c5ff0q6g9f8xfd6w …
```
> feat: dump operation state machine log

- docs/rustdoc-index.md
> fix(docs): typo leading to a broken link

- Cargo.lock
- fuzz/Cargo.toml
> fix: cargo fuzz broken after update

- Cargo.lock
- fedimint-api-client/src/api.rs
- fedimint-api-client/src/lib.rs
- fedimint-api-client/src/query.rs
- fedimint-client/src/backup.rs
- fedimint-client/src/lib.rs
- fedimint-core/src/module/version.rs
- fedimint-server/src/consensus/engine.rs
- gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-ln-client/src/api.rs
- modules/fedimint-lnv2-client/Cargo.toml
- modules/fedimint-lnv2-client/src/api.rs
- modules/fedimint-mint-client/src/output.rs
> Consolidate query strategies

- README.md
Iirc the UI call isn't happening anymore (correct me if I'm wrong) and we have PR review calls now.
> chore: update weekly call list

- docs/meta_fields/README.md
Since there was confusion about it on Discord. @Kodylow @TonyGiorgio
> chore: add link to Fedi custom meta field docs

- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/sm/executor.rs
(cherry picked from commit e12d82c5236287ca67bb9c5fc7d3f5f3ec7c2405)
Fixes #5382
> Backport: dump operation state machine log

- fedimint-api-client/src/api.rs
- fedimint-core/src/core/backup.rs
- fedimint-server/src/consensus/engine.rs
> fix: remove unused imports

- fedimint-core/src/db/mod.rs
> chore: lower on_commit span level

- fedimint-core/src/invite_code.rs
Needed this so I can put the invite codes in a hashset and so you can sort a vec of them
> feat: Impl traits for InviteCode

- fedimint-server/src/consensus/engine.rs
If such an error or panic occurs we need to read the pending accepted items of the current session from disk to obtain the item at which the consensus diverged.
> chore: improve logging on consensus failure

- fedimint-core/src/api.rs
> backport: Impl traits for InviteCode

- fedimint-core/src/invite_code.rs
- modules/fedimint-mint-client/src/lib.rs
`Data` is sooo vague in software context, that it almost never is a good word to use to name something.
> refactor: rename `Data` to `Parts` for oob and invite code

- fedimint-client/src/lib.rs
It'll nearly always be e-cash that's causing the problem here, still good to have some more details.
> chore: log details when created transaction is too large

- modules/fedimint-wallet-client/src/lib.rs
> refactor: split WalletClientModule::get_deposit_address_inner

- fedimint-server/src/consensus/aleph_bft/keychain.rs
- fedimint-server/src/consensus/engine.rs
- fedimint-server/src/consensus/mod.rs
> Keychain Refactor

- Cargo.lock
- fedimint-server/Cargo.toml
- fedimint-server/src/config/mod.rs
- fedimintd/Cargo.toml
> chore(deps): bump rcgen from 0.12.1 to 0.13.1

- flake.lock
nix flake hasn't been updated in 30 days
> fix: nix flake update

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-ln-client/Cargo.toml
- modules/fedimint-lnv2-client/Cargo.toml
Also bump `reqwest` v0.11.26 to v0.11.27
> chore: add reqwest workspace dep

- modules/fedimint-ln-client/src/db.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
https://github.com/fedimint/fedimint/pull/4024 added some deprecation warnings. This PR just suppresses them since we don't need to see them during build.
> fix: fix LN deprecation warnings

- README.md
@dpc @elsirion @m1sterc001guy @maan2003 @oleonardolima @bradleystachurski  please fill out what you can in follow ups.
> chore: assign and document maintainers

- scripts/dev/build-docs.sh
> fix(ci): ignore unknown lints during cargo doc

- devimint/src/gatewayd.rs
- fedimint-api-client/src/api.rs
- fedimint-api-client/src/lib.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/meta.rs
- fedimint-core/src/util/mod.rs
- fedimint-server/src/net/peers.rs
- gateway/cli/src/main.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
> chore: fibonacci backoff when connecting to guardians

- README.md
> chore: update maintainer tracking

- Cargo.lock
- modules/fedimint-lnv2-client/src/cli.rs
- modules/fedimint-lnv2-tests/Cargo.toml
- modules/fedimint-lnv2-tests/src/bin/gateway_registration_sanity.rs
- scripts/tests/lnv2-module-test.sh
- scripts/tests/test-ci-all.sh
> chore: lnv2 gateway registration sanity test

- flake.lock
- flake.nix
> chore: update flakebox

- .typos.toml
- Cargo.toml
- flake.lock
- flake.nix
- modules/fedimint-mint-tests/tests/tests.rs
- nix/overlays/clightning.nix
- nix/pkgs/esplora-electrs.Cargo.lock
- nix/pkgs/esplora-electrs.nix
- scripts/tests/backend-test.sh
> chore: update nixpkgs to 24.05

- fedimint-core/src/encoding/mod.rs
- flake.lock
> chore: update rust toolchain

- fedimint-client/src/lib.rs
> fix: docs typo

- Cargo.lock
- devimint/src/gatewayd.rs
- modules/fedimint-lnv2-client/src/cli.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-tests/Cargo.toml
- modules/fedimint-lnv2-tests/src/bin/self_payment_with_one_gateway.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
> chore: test lnv2 self payment with one gateway

- gateway/ln-gateway/src/lib.rs
Addresses [this](https://github.com/fedimint/fedimint/pull/5487/commits/005440b10f642c03a34cd772521702ca7817c1b4#r1647946517) comment from another PR that touches this code
> chore: change Gateway.max_used_scid to next_scid

- devimint/src/cli.rs
- devimint/src/devfed.rs
- devimint/src/federation.rs
- devimint/src/gatewayd.rs
- devimint/src/lib.rs
- devimint/src/tests.rs
- devimint/src/vars.rs
- gateway/integration_tests/src/main.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-lnv2-tests/src/bin/gateway_registration_sanity.rs
- modules/fedimint-lnv2-tests/src/bin/self_payment_with_one_gateway.rs
- modules/fedimint-meta-tests/src/bin/meta-sanity-test.rs
- modules/fedimint-mint-tests/src/bin/mint-client-sanity.rs
- modules/fedimint-wallet-tests/src/bin/circular-deposit-test.rs
Fixes: https://github.com/fedimint/fedimint/issues/5001
Working Towards: https://github.com/fedimint/fedimint/issues/5168
Allows for spawning a new federation in devimint tests. Also adds some verifications to `config-test` to cover the removed tests from the lightning integration tests.
> feat: spawn new federation in devimint

- fedimint-testing/src/gateway.rs
- gateway/ln-gateway/src/bin/gatewayd.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/lnd.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/integration_tests.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
A bunch of small tweaks and cleanups throughout the gateway code. I recommend reviewing commit-by-commit.
> chore: gateway cleanup

- gateway/ln-gateway/src/bin/cln_extension.rs
I know we are considering removing CLN support but I don't like leaving things broken and this took about 5 minutes to debug and fix :)
> fix: create invoice CLN

- nix/modules/fedimintd.nix
> chore: improve NixOS module

- scripts/tests/lnv2-module-test.sh
> fix: actually run self payment test

- fedimint-bitcoind/src/lib.rs
caught this in mutiny, not sure why CI didn't catch this
> fix: Fix call of std::thread::sleep

- docs/wallet_module.md
- modules/fedimint-wallet-common/src/lib.rs
Closes https://github.com/fedimint/fedimint/issues/5498
> chore(wallet): use next block conf target to estimate feerate

- devimint/src/util.rs
- nix/flakebox.nix
- recoverytool/Cargo.toml
> chore: rename recoverytool binary to fedimint-recoverytool

- modules/fedimint-lnv2-tests/src/bin/self_payment.rs
- scripts/tests/lnv2-module-test.sh
> chore: test payment with two gateways

- fedimint-testing/src/ln.rs
Part of #1576
Change `FakeLightningTest.amount_sent` from `Arc<Mutex<u64>>` to `AtomicU64` to avoid the need to lock
This field isn't ever used, it's only there as a counter for debugging, so relaxed ordering is fine
> chore: change type of FakeLightningTest.amount_sent to avoid locking

- fedimint-core/src/amount.rs
- fedimint-core/src/invite_code.rs
- fedimint-core/src/lib.rs
- fedimint-core/src/peer_id.rs
Document some core structs, and split them into separate files
> chore: core cleanup

- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
> chore: test unilateral refund of outgoing contracts

- gateway/ln-gateway/src/gateway_module_v2/mod.rs
> fix: assert claim of outgoing contract

- fedimint-api-client/src/api/federation_peer_client.rs
Default connection attempts is 3, so currently it does:
100, 130, 5000, 5000, 5000 which is not the intention. Also jitter is always a good thing.
While at it I've noticed a minor improv. and let's increment maximum reconnection time. 5s seems still somewhat aggresive if the peer just seems down.
> fix: improve client reconnection backoff

- fedimint-api-client/src/lib.rs
The reconnection state is tracked inside `DynGlobalApi`. Recreating it means resetting it, which is undesireable.
> fix: client potentially not respecting reconnect backoff

- gateway/ln-gateway/src/bin/cln_extension.rs
As @elsirion mentioned here https://github.com/fedimint/fedimint/pull/5449#pullrequestreview-2125650786, CLN's `pay_private` implementation is a bit naive currently, it only tries one route and fails if that first route does not succeed.
This PR increases the number of route attempts to 10, and maintains a vector of `excluded_nodes` which is passed into each `getroute` request. This should hopefully increase the robustness of CLN's `pay_private`
> fix: multiple route attempts and exclude failed routes

- Cargo.lock
- fedimint-recoverytool/Cargo.toml
- fedimint-recoverytool/build.rs
- fedimint-recoverytool/src/main.rs
> feat(recoverytool): add `version-hash` support

- Cargo.lock
- fedimint-api-client/Cargo.toml
- fedimint-api-client/src/api/mod.rs
depends on:
fixes https://github.com/fedimint/fedimint/pull/5441#issuecomment-2161666413
> fix(jsonrpsee): use proper `tls` feature, with custom tls cfg

- Cargo.lock
- modules/fedimint-mint-client/Cargo.toml
- modules/fedimint-mint-client/src/cli.rs
- modules/fedimint-mint-client/src/lib.rs
> refactor: refactor mint modular cli

- fedimint-client/src/module/mod.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
hopefully we will get a fedimint typescript bindings out of this
> fedimint client rpc

- gateway/ln-gateway/src/lib.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-tests/src/bin/tests.rs
> fix: check that incoming payment is economical

- modules/fedimint-lnv2-tests/src/bin/tests.rs
> chore: improve lnv2 test coverage

- fedimint-testing/src/fixtures.rs
- modules/fedimint-lnv2-tests/src/bin/tests.rs
> chore: fix clippy warnings (v0.4 backport)

- devimint/src/cli.rs
The intention was for `devimint run-ui` to spawn stuff and block waiting for Ctrl+C. This got lost somewhere during refactorings of devimint and just now discovered.
I think the `clean_on_exit` is more versatile if it does not wait itself, and require logic that it wraps to block if that's the intention.
> fix(devimint): run_ui does not block

- devimint/src/cli.rs
Backport of #5620 to `releases/v0.4`.
> [Backport releases/v0.4] fix(devimint): run_ui does not block

- devimint/src/cli.rs
> fix(devimint): `devimint devfed` does not block

- devimint/src/cli.rs
fixes missing rpc auth in force env var for devimint run-ui
> fix: bitcoin:bitcoin

- Cargo.lock
- fedimint-core/src/endpoint_constants.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/consensus/server.rs
- fedimint-server/src/net/api.rs
Working towards https://github.com/fedimint/fedimint/issues/5601
> Backport shutdown endpoint logic

- fedimint-server/src/consensus/api.rs
Re: https://github.com/fedimint/fedimint/pull/5630#discussion_r1677223016
> fix: set version SHUTDOWN_ENDPOINT was introduced to 0.3

- fedimint-cli/src/lib.rs
- fedimint-core/src/api.rs
Working towards https://github.com/fedimint/fedimint/issues/5601
> Backport: feat: add shutdown command to admin CLI

- fedimint-cli/src/client.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-wasm-tests/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
OOBNotesV2 require an invite code.
> chore: always include invite code in oob ecash

- devimint/src/federation.rs
- devimint/src/federation/config.rs
Resolves one of the failures associated with https://github.com/fedimint/fedimint/issues/5602
Still debugging other upgrade issues.
> fix(devimint): check fedimintd version before attaching lnv2 module

- modules/fedimint-lnv2-tests/src/bin/tests.rs
> cleanup: remove redundant testing, add logs

- modules/fedimint-lnv2-client/src/api.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-client/src/send_sm.rs
- modules/fedimint-lnv2-common/src/lib.rs
- modules/fedimint-lnv2-server/src/db.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
> chore: prepare for alternative gateway endpoints

- fedimint-cli/src/client.rs
Backport of #5668 to `releases/v0.4`.
> [Backport releases/v0.4] feat: add session count to fedimint-cli

- fedimint-cli/src/client.rs
Backport of #5668 to `releases/v0.3`.
> [Backport releases/v0.3] feat: add session count to fedimint-cli

- modules/fedimint-wallet-client/src/backup.rs
- modules/fedimint-wallet-client/src/lib.rs
This would require another variant, but 0.4 is still unreleased, so can still backport.
> chore(wallet-client): add session count to backup

- docs/RELEASE_NOTES-v0.4.md
> chore: polish v0.4 upgrade instructions

- Cargo.toml
- fedimint-server/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-lnv2-client/Cargo.toml
- modules/fedimint-lnv2-common/Cargo.toml
- modules/fedimint-lnv2-server/Cargo.toml
> fix: some issues found during publishing v0.4.0-rc.1

- fedimint-api-client/src/api/mod.rs
- fedimint-server/src/consensus/api.rs
- fedimint-server/src/consensus/mod.rs
Backport of #5684 to `releases/v0.4`.
> [Backport releases/v0.4] feat: add scheduled_shutdown to FederationStatus

- fedimint-core/src/encoding/mod.rs
- fuzz/src/bin/vec_deque.rs
> chore(core): Encodable for `VecDeque`

- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-ln-client/src/lib.rs
> chore: share tcp connection for gateway api

- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-ln-client/src/lib.rs
Backport of #5693 to `releases/v0.4`.
> [Backport releases/v0.4] chore: share tcp connection for gateway api

- docs/RELEASE_NOTES-v0.4.md
Backport of #5685 to `releases/v0.4`.
> [Backport releases/v0.4] docs: update v0.4 release docs to warn about automatic restarts

- fedimint-core/src/api.rs
- fedimint-server/src/consensus/server.rs
- fedimint-server/src/net/api.rs
Closes https://github.com/fedimint/fedimint/issues/5687
> feat: add scheduled_shutdown to FederationStatus

- gateway/ln-gateway/src/lib.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
> fix: set base fee to ensure economical payments for the gateway

- devimint/src/tests.rs
Running upgrade tests locally can fail due to latency thresholds but succeed if we ignore the thresholds. Since upgrade tests should only consider the ability to successfully upgrade, we should skip asserting latency thresholds for upgrade tests.
> chore: ignore latency thresholds for upgrade tests

- fedimint-client/src/db.rs
- fedimint-core/src/db/mod.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-testing/src/db.rs
> fix(client): ignore user data in the new-db check

- fedimint-client/src/db.rs
> fix: don't panic when migrating without existing config

- Cargo.lock
- gateway/ln-gateway/Cargo.toml
Replaces #5623 and #5625
Tonic and prost must be bumped together. This PR just combines the two mentioned above.
> chore(deps): bump prost to 0.13 and tonic + tonic-build to 0.12

- fedimintd/src/fedimintd.rs
* Add/cleanup documentation
* Make `ServerOpts` private, since it is not usable in any other exported code
* Refactor `parse_map()`, changing the behavior in two ways:
1. Duplicate keys are not allowed
2. Keys and values have beginning/end whitespace trimmed
> chore: cleanup fedimintd.rs

- fedimint-core/src/core.rs
- fedimint-core/src/session_outcome.rs
I'm making a presentation, and link to some places in the Technical Reference, and want to make it look a bit better.
> chore: minor rustdoc improvements

- modules/fedimint-lnv2-client/src/api.rs
> chore: fix clippy warnings

- gateway/integration_tests/src/main.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
> chore: rename GatewayInfo.channels

- fedimint-cli/src/client.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-wasm-tests/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
> Revert "chore: always include invite code in oob ecash"

- fedimint-core/src/db/mod.rs
This is the beginning of the end, I am adding docs so AI can understand how to use database properly.
> chore: add database module level docs for LLMs

- modules/fedimint-lnv2-server/src/lib.rs
> fix: choose minimal block count or unix time

- Cargo.lock
- devimint/src/devfed.rs
- devimint/src/external.rs
- devimint/src/federation.rs
- devimint/src/version_constants.rs
- gateway/integration_tests/src/main.rs
- modules/fedimint-lnv2-tests/Cargo.toml
- modules/fedimint-lnv2-tests/src/bin/tests.rs
> chore: add LDK Gateway to LNV2 testing

- fedimint-client/src/module/recovery.rs
- fedimint-client/src/sm/executor.rs
- fedimint-client/src/sm/state.rs
- fedimint-client/src/transaction/sm.rs
- fedimint-core/src/core.rs
- fedimint-core/src/core/server.rs
- fedimint-core/src/macros.rs
- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-dummy-common/src/lib.rs
- modules/fedimint-empty-client/src/lib.rs
- modules/fedimint-empty-common/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-common/src/lib.rs
- modules/fedimint-meta-client/src/lib.rs
- modules/fedimint-meta-common/src/lib.rs
- modules/fedimint-mint-client/src/backup.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-common/src/lib.rs
- modules/fedimint-unknown-common/src/lib.rs
- modules/fedimint-wallet-client/src/backup.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-common/src/lib.rs
Mostly for debugging purposes.
Fix #1997
> refactor: add module kind info to all Dyn types

- .github/workflows/ci-nix.yml
>  fix(ci): cachix commands failing in builds flows 

- .github/workflows/ci-nix.yml
> chore(ci): run self-check only in PRs to master

- Cargo.toml
This brings the `fedimintd` CPU usage in devimint
a bit.
> chore: optimize more deps in dev build profile

- Cargo.toml
- devimint/Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-dbtool/Cargo.toml
- fedimint-load-test-tool/Cargo.toml
- fedimint-recoverytool/Cargo.toml
- fedimint-server/Cargo.toml
- fedimint-testing-core/Cargo.toml
- fedimint-testing/Cargo.toml
- fedimintd/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/ln-gateway/Cargo.toml
> chore: more workspace deps

- README.md
[Rendered](https://github.com/fedimint/fedimint/blob/4982943686e062846454dc9363e1893657310d53/README.md)
BTW. Tokei service seems to be down ATM, but that's unrelated.
https://github.com/XAMPPRocky/tokei/issues/1126
> chore: show Radicle node badge

- fedimint-client/src/sm/executor.rs
`ExecutorInner.{context, shutdown_executor, sm_update_rx}` all have specific values in each of three possible states of the `ExecutorInner`: unstarted, running, and stopped. These three states are somewhat loosely defined currently. This PR extracts the three struct fields into a state enum which contains those same values depending on the state, making it more clear and explicit what state the executor is in.
> chore: extract ExecutorInner state fields into separate enum

- fedimint-server/src/config/api.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/consensus/engine.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/lib.rs
- fedimint-server/src/net/api/mod.rs
- fedimint-server/src/net/peers.rs
- fedimint-server/src/net/peers_reliable.rs
- fedimint-testing/src/federation.rs
Backport of #5722 to `releases/v0.4`.
> [Backport releases/v0.4] refactor(server): remove bind addr's from local config

- crypto/tpe/src/lib.rs
> chore: polish lnv2 tpe

- gateway/ln-gateway/src/lib.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
> fix: increase maximum lightning routing fees to LDK default

- Cargo.lock
- fedimint-cli/src/lib.rs
- fedimint-client/src/db.rs
- fedimint-client/src/meta.rs
- modules/fedimint-meta-client/Cargo.toml
- modules/fedimint-meta-client/src/cli.rs
- modules/fedimint-meta-client/src/lib.rs
- modules/fedimint-meta-common/src/lib.rs
- modules/fedimint-meta-tests/src/bin/meta-sanity-test.rs
I made #5413 compile, still needs self-review and a test.
> feat: meta source for meta module

- fedimint-api-client/src/api/mod.rs
This loop is confusing since it actually only loops once, but after looking it over it all seems necessary. Let's document it for future readers.
> chore: cleanup confusing loop

- modules/fedimint-lnv2-tests/src/bin/tests.rs
Working towards https://github.com/fedimint/fedimint/issues/5490
Adds some test cases where a client in one federation can pay a client in a different federation.
This doesn't fundamentally add coverage to new code paths, since LNv2 treats this test case as the same, but I think its a cool test to have, and can serve as a nice check in the future to make sure this use case does not break.
> test: LNv2 add mint to mint test

- Cargo.lock
- fedimint-cli/src/lib.rs
- fedimint-client/src/db.rs
- fedimint-client/src/meta.rs
- modules/fedimint-meta-client/Cargo.toml
- modules/fedimint-meta-client/src/cli.rs
- modules/fedimint-meta-client/src/lib.rs
- modules/fedimint-meta-common/src/lib.rs
- modules/fedimint-meta-tests/src/bin/meta-sanity-test.rs
> backport: feat: meta source for meta module

- fedimint-client/src/lib.rs
- fedimint-client/src/module/recovery.rs
> feat: global client rpc commands

- modules/fedimint-mint-client/src/lib.rs
> fix: fix tx finalization for non-zero input fees

- modules/fedimint-mint-client/src/lib.rs
Backport of #5844 to `releases/v0.4`.
> [Backport releases/v0.4] fix: fix tx finalization for non-zero input fees

- gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs
- modules/fedimint-lnv2-common/src/lib.rs
- modules/fedimint-lnv2-server/src/db.rs
- modules/fedimint-lnv2-server/src/lib.rs
> Lnv2 extensible outcome

- modules/fedimint-lnv2-client/src/cli.rs
- modules/fedimint-lnv2-tests/src/bin/tests.rs
> cleanup: use subcommand

- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- modules/fedimint-lnv2-client/src/api.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-client/src/send_sm.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
> fix: omit ln fee for direct swaps

- modules/fedimint-lnv2-tests/tests/mock.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
> cleanup: remove unneded gateway from lnv2 module tests

- fedimint-core/src/core/server.rs
- fedimint-server/src/consensus/transaction.rs
> chore: remove redundant arguments

- devimint/src/external.rs
- scripts/_common.sh
Following up on some nit comments from https://github.com/fedimint/fedimint/pull/5871
> chore: cln extension upgrade follow ups

- fedimint-cli/src/lib.rs
- fedimint-client/src/api_announcements.rs
- fedimint-client/src/module/init/recovery.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-wallet-client/src/backup.rs
- modules/fedimint-wallet-client/src/backup/recovery_history_tracker.rs
- modules/fedimint-wallet-client/src/client_db.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-tests/src/bin/wallet-recovery-test.rs
- modules/fedimint-wallet-tests/tests/tests.rs
See comments in the code.
Fix #5584
> chore: wallet client recovery privacy improvements

- .github/workflows/ci-nix.yml
Fixes https://github.com/fedimint/fedimint/issues/5924
> Backport fix(ci): set release to prerelease if tag contains 'rc'

- modules/fedimint-meta-client/Cargo.toml
`master` equivalent of https://github.com/fedimint/fedimint/pull/5927
> fix: always require serde_json dep in meta module client

- .github/workflows/upgrade-tests.yml
Closes https://github.com/fedimint/fedimint/issues/5736
> chore(ci): add perfit to upgrade tests workflow

- Cargo.lock
- gateway/ln-gateway/Cargo.toml
- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/state_machine/mod.rs
> chore: remove secp256k1-zkp in gateway

- Cargo.lock
- gateway/cli/Cargo.toml
- gateway/cli/src/lightning_commands.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- modules/fedimint-lnv2-common/src/endpoint_constants.rs
Gateway can pay invoices as itself (i.e. no e-cash swap, just pay using its own funds)
> feat: gateway can pay invoices as itself

- modules/fedimint-wallet-client/src/backup.rs
- modules/fedimint-wallet-client/src/backup/recovery_history_tracker.rs
> chore: further small wallet recovery improvements

- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
> fix: deposit `Claimed` state waits for e-cash to be in wallet

- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-common/src/config.rs
- modules/fedimint-lnv2-server/src/lib.rs
In case we ever want to fine tune this.
> feat: fine grained fees specific to input and output variant

- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/gateway_module_v2/send_sm.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/lnd.rs
- gateway/ln-gateway/tests/tests.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-common/src/contracts.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
> feat: prepare ptlc support

- gateway/ln-gateway/src/lib.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
> cleanup: rename public_key to module_public_key

- devimint/src/tests.rs
>  chore: test one more client ecash recovery case 

- fedimint-client/src/backup.rs
> fix: don't allow making new backups while recovery is running (v0.4)

- modules/fedimint-lnv2-client/src/api.rs
- modules/fedimint-lnv2-client/src/cli.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-client/src/send_sm.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
> cleanup: refactor and rename lnv2 api traits for consistency

- fedimint-api-client/src/api/global_federation_api_with_cache.rs
Backport of #5949 to `releases/v0.4`.
> [Backport releases/v0.4] chore(client): increase size of the session fetching cache LRUs

- Cargo.lock
- fedimint-api-client/src/api/global_api.rs
- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- fedimint-client-wasm/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/federation_manager.rs
- gateway/ln-gateway/src/gateway_module_v2/send_sm.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/tests.rs
- modules/fedimint-dummy-tests/tests/tests.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
- modules/fedimint-meta-client/Cargo.toml
- modules/fedimint-meta-client/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
- modules/fedimint-wallet-tests/tests/tests.rs
> refactor: remove panic in `get_first_module`

- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-common/src/config.rs
- modules/fedimint-lnv2-server/src/lib.rs
> cleanup: lnv2 rename fees

- nix/flakebox.nix
Closes https://github.com/fedimint/fedimint/issues/5954
Busybox is very complete. curl and rsync may be also be util.
> chore: add more utils to docker images

- devimint/src/gatewayd.rs
- fedimint-testing/src/federation.rs
- gateway/cli/src/general_commands.rs
- gateway/integration_tests/src/main.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/ldk.rs
- gateway/ln-gateway/src/lightning/mod.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- modules/fedimint-ln-common/src/gateway_endpoint_constants.rs
- scripts/tests/gateway-restore-test.sh
- scripts/tests/test-ci-all.sh
Implements backup/restore for ecash in the gateway.
Also includes LDK onchain mnemonic and recovery.
> feat: Gateway ecash Backup/Restore and LDK onchain recovery

- fedimint-client/src/backup.rs
- fedimint-client/src/db.rs
- fedimint-core/src/db/mod.rs
> chore: lower logging levels and tweak messages

- gateway/ln-gateway/src/lib.rs
`Gateway::route_htlcs()` is the only place where `Gateway::handle_htlc_stream()` is called. Having both functions is a bit confusing, and `Gateway::handle_htlc_stream()` does very little. (A good chunk of its logic is to respect shutdown signals, but `Gateway::route_htlcs()` already calls it in a cancellable way anyway, so that's not even needed.) Let's inline it into `Gateway::route_htlcs()`.
> refactor: move handle_htlc_stream() logic into route_htlcs()

- devimint/src/devfed.rs
- devimint/src/external.rs
This fixes a clippy warning that's been hanging around for a while
> chore: create NamedGateway type

- modules/fedimint-ln-client/src/lib.rs
> fix(ln-client): verify operation type when subscribing to LN payment updates

- fedimint-api-client/src/api/global_federation_api_with_cache.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/api_announcements.rs
- fedimint-client/src/module/init/recovery.rs
- fedimint-core/src/encoding/mod.rs
- fuzz/src/bin/vec_deque.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-wallet-client/src/backup.rs
- modules/fedimint-wallet-client/src/backup/recovery_history_tracker.rs
- modules/fedimint-wallet-client/src/client_db.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-tests/src/bin/wallet-recovery-test.rs
- modules/fedimint-wallet-tests/tests/tests.rs
This backports #5697 to v0.4
Turns out these improvements would be great to have to in 0.4 and they were easy to backport (mostly just import merge conflicts).
> chore: wallet client recovery privacy improvements (v0.4 backport)

- devimint/src/vars.rs
- gateway/ln-gateway/src/config.rs
- gateway/ln-gateway/src/envs.rs
Related to #6014.
Its name now reflects that it doesn't affect already connected federations.
> fix(gateway): rename default fee env var

- .github/workflows/ci-nix.yml
- fedimint-client-wasm/src/db.rs
- nix/flakebox.nix
> chore(ci): compile fedimint-wasm for wasm

- modules/fedimint-ln-client/src/lib.rs
Backport of #6006 to `releases/v0.4`.
> [Backport releases/v0.4] fix(ln-client): verify operation type when subscribing to LN payment updates

- fedimint-rocksdb/src/lib.rs
> refactor: eliminate duplication in rocksdb impl

- fedimint-client/src/api_announcements.rs
> fix: misleading error message

- devimint/src/federation/config.rs
- fedimintd/src/bin/main.rs
- fedimintd/src/fedimintd.rs
- modules/fedimint-lnv2-common/src/config.rs
- modules/fedimint-lnv2-server/src/lib.rs
> chore: document lnv2 fee configuration

- Cargo.lock
- Cargo.toml
> chore(deps): bump cln-rpc from 0.1.9 to 0.2.0

- gateway/ln-gateway/proto/gateway_lnrpc.proto
- gateway/ln-gateway/src/bin/cln_extension.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/ldk.rs
- gateway/ln-gateway/src/lightning/lnd.rs
- gateway/ln-gateway/src/rpc/mod.rs
PR for this issue: #5980 
* add inbound lightning liquidity  to Get Balances Response
> feat(balance): add inbound lightning liquidity to GetBalancesResponse

- fedimint-core/src/db/mod.rs
- gateway/ln-gateway/src/client.rs
Very unlikely that this would get in a way of real module, but it occurred to me it would be a papercut.
> chore(db): improve `global_dbtx` when module uses nested `with_prefix`

- modules/fedimint-lnv2-client/src/api.rs
- modules/fedimint-lnv2-client/src/cli.rs
- modules/fedimint-lnv2-client/src/db.rs
- modules/fedimint-lnv2-client/src/lib.rs
> feat: cache gateways

- gateway/ln-gateway/src/lib.rs
Edge case of gateway's safe stop feature that was pointed out by @elsirion here: https://github.com/fedimint/fedimint/pull/5999/files#r1762742035
There's a race condition when stopping where if the gateway receives a payment request before `cancel_on_shutdown` has stopped the thread, the gateway would start processing the payment and potentially leave the gateway in an un-finished state. This PR just adds a `tokio::select!` to payment processing thread so that it knows to break when the gateway's state is `ShuttingDown`.
> fix: stop listening for payments when shutting down

- nix/flakebox.nix
> chore: remove unnecessary `sqlite` package from container

- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-tests/src/bin/tests.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
> Lnv2 put gateway url in receive meta

- fedimint-cli/src/lib.rs
- modules/fedimint-meta-client/src/lib.rs
we have a custom legacy source at fedi.
> chore: make meta source more generic

- fedimint-cli/src/lib.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-tests/src/bin/mint-client-restore.rs
- scripts/tests/mint-client-restore.sh
- scripts/tests/test-ci-all.sh
> chore(test): another mint module recovery test

- modules/fedimint-mint-client/src/backup/recovery.rs
> Remove redundant recovery code

- devimint/src/external.rs
- devimint/src/gatewayd.rs
Fixes #6077
The upgrade test was broken by #6008. This PR essentially reverts the behavior to what happened before that PR when running an old version of the gateway
> fix: devimint does not fetch channel funding txids for older gateways

- modules/fedimint-lnv2-client/src/lib.rs
> fix: set default limit to ldk default

- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/client_db.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
> chore(client): during recovery detect burned ecash due to nonce reuse

- modules/fedimint-lnv2-common/src/lib.rs
> fix: set lnv2 module consensus version to 1.0

- fedimint-cli/src/lib.rs
- fedimint-client/src/meta.rs
- modules/fedimint-meta-client/src/lib.rs
so we can get meta before joining the federation
> chore: make meta source work without a client

- fedimint-client/src/db.rs
- fedimint-client/src/lib.rs
- fedimint-core/src/db/mod.rs
- fedimint-core/src/module/mod.rs
- fedimint-server/src/consensus/db.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-testing-core/src/db.rs
- fedimintd/src/fedimintd.rs
- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-empty-client/src/lib.rs
- modules/fedimint-empty-server/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-meta-client/src/lib.rs
- modules/fedimint-meta-server/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-unknown-server/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
Fixes: https://github.com/fedimint/fedimint/issues/6108
Kind of a footgun so let's just remove it.
> chore: remove DATABASE_VERSION

- fedimint-server/src/net/peers.rs
> chore: improve p2p connectivity logging for debugging issues

- modules/fedimint-ln-client/src/lib.rs
Adds the tweaked invoice methods for ln.handle_rpc so we can add lightning address receiving to the fedimint web sdk
> feat: add tweaked invoice rpcs

- fedimint-cli/src/lib.rs
- fedimint-client/src/backup.rs
- fedimint-client/src/db.rs
- fedimint-client/src/db/event_log.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/mod.rs
- fedimint-client/src/sm/dbtx.rs
- fedimint-client/src/sm/executor.rs
- fedimint-client/src/transaction/sm.rs
- fedimint-logging/src/lib.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/event.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/output.rs
Motivation explained in the module doc comments.
Added few simple events as examples and to make sure it works.
Following events logic is there, but will need some more work.
```
> fedimint-cli dev show-event-log --limit 100
[                      
{ 
"id": 0,
"kind": "tx-created",
"module_id": null,     
"module_kind": null,
"payload": {          
"operation_id": "009e1a28b782fd350a422263ddce9467304bc7117ce3be9c4b868b55dd4319e0",
"txid": "549d0ac3610def6693525ae5fb7ec487dd1e9022e6c9c33b5177e3a218e830a7"   
},
"ts": 1726528542611
},
{
"id": 1,
"kind": "note-created",
"module_id": 1,
"module_kind": "mint",
"payload": {
"nonce": "0357cbf5868a0eabbf8bcbd01695f2578895662a5eebcc099d7dc9a39294f02489"
},
"ts": 1726528543859 …
```
> feat: client side event log

- fedimint-server/src/consensus/engine.rs
> fix: fix index bug in case of incomplete mid-session recovery

- gateway/ln-gateway/src/lib.rs
Will follow up with more renaming, but wanted to keep this relatively easy to review
> chore: rename HTLC to lightning payment in gateway lib

- fedimint-core/src/lib.rs
- fedimint-core/src/version.rs
> chore: official methods to get cargo and git hash versions

- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/mod.rs
Fixes: https://github.com/fedimint/fedimint/issues/6107
> fix: gateway registration exits early

- modules/fedimint-lnv2-client/src/lib.rs
> chore: prepare meta for bolt12 invoices

- devimint/src/cfg/lightningd.conf
- devimint/src/external.rs
- gateway/ln-gateway/src/bin/cln_extension.rs
- modules/fedimint-lnv2-tests/src/bin/tests.rs
- nix/overlays/clightning.nix
Linked issue doesn't seem to be a problem anymore.
> chore: upgrade core lightning to 24.08.1

- nix/flakebox.nix
> chore(ci): clippy to deny warnings

- modules/fedimint-lnv2-client/src/cli.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
> cleanup: simplify lnv2 client api

- README.md
Updated in UI already, considered beta since 0.4 per discussion
> chore: alpha -> beta in readme

- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/lib.rs
I addressed the TODO about renaming `incoming_amount`
> Renamed `incoming_amount` to `incoming_amount_msats`

- modules/fedimint-wallet-tests/tests/tests.rs
> fix(tests): retry client balance check to prevent flakiness

- devimint/src/gatewayd.rs
- gateway/ln-gateway/src/lightning/ldk.rs
> fix: GatewayLdkClient::info() doesn't rely on timestamps

- fedimint-core/src/db/mod.rs
- modules/fedimint-lnv2-common/src/config.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-unknown-server/src/lib.rs
Running CI to try and fix: https://github.com/fedimint/fedimint/issues/6209
> fix: Upgrade Tests

- devimint/src/tests.rs
- fedimint-recoverytool/README.md
- fedimint-recoverytool/src/main.rs
> chore: make read-only default in recoverytool

- gateway/ln-gateway/src/bin/cln_extension.rs
- gateway/ln-gateway/src/lightning/ldk.rs
- gateway/ln-gateway/src/lightning/lnd.rs
Fixes: https://github.com/fedimint/fedimint/issues/6123
> feat: get_balances filters non-active channels

- Cargo.lock
- devimint/src/federation/config.rs
- fedimint-core/src/bitcoin_migration.rs
- fedimint-core/src/encoding/btc.rs
- fedimint-recoverytool/src/main.rs
- fedimintd/src/fedimintd.rs
- gateway/ln-gateway/Cargo.toml
- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-common/Cargo.toml
- modules/fedimint-ln-common/src/config.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-common/Cargo.toml
- modules/fedimint-lnv2-common/src/config.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-common/Cargo.toml
- modules/fedimint-wallet-common/src/config.rs
- modules/fedimint-wallet-common/src/lib.rs
- modules/fedimint-wallet-server/Cargo.toml
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/Cargo.toml
- modules/fedimint-wallet-tests/tests/tests.rs
> chore: bump Network and Amount en/decoding to bitcoin v0.32

- devimint/src/external.rs
- devimint/src/tests.rs
- modules/fedimint-wallet-tests/src/bin/circular-deposit-test.rs
Currently we're calling `getrawtransaction` to check whether a particular transaction has been seen by bitcoind (for example, to wait for a channel open transaction to appear before mining blocks). Since we have `txindex` disabled in v0.4 and later, `getrawtransaction` will only return transactions in the mempool, not ones that have already been mined.
https://github.com/fedimint/fedimint/blob/5f56672f3c9934b9ebd8deaa6a3177f5108db7f5/devimint/src/external.rs#L52-L56
However, in devimint there are multiple parallel processes that each mine blocks on bitcoind, which can lead to a transaction being submitted in one process, confirmed in another, and then checked for existence in the first process. In this PR we add `get_transaction()` which checks both the mempool and the entire blockchain …
> fix: devimint checks if txs are visible anywhere

- fedimint-core/src/encoding/secp256k1.rs
- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs
- gateway/ln-gateway/src/gateway_module_v2/send_sm.rs
- modules/fedimint-ln-client/src/db.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-client/src/receive.rs
- modules/fedimint-ln-common/src/contracts/outgoing.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-client/src/receive_sm.rs
- modules/fedimint-lnv2-client/src/send_sm.rs
- modules/fedimint-mint-client/src/input.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/oob.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-mint-tests/tests/tests.rs
- modules/fedimint-wallet-client/src/deposit.rs
Part of #5200
The main change is in fedimint-core/src/encoding/secp256k1.rs. The rest of the PR is just handling the resulting changes in types.
> chore(deps): bump Keypair en/decoding to bitcoin v0.32

- gateway/ln-gateway/src/envs.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/lightning/mod.rs
Just adding some comments. Likely helpful for deployments for figuring out how to configure the gateway.
> chore: comment gateway environment variables

- fedimint-server/src/consensus/server.rs
> fix: fix index bug in case of mid-session recovery (backport 0.3)

- fedimint-server/src/consensus/server.rs
> chore(consensus): ask for signed session outcomes without a delay  (backport 0.3)

- fedimint-core/src/db/notifications.rs
I was debugging wrong thing. I got paranoid.
> chore: add extra db notification test

- Cargo.lock
- devimint/Cargo.toml
- devimint/src/external.rs
- devimint/src/tests.rs
- fedimint-core/src/bitcoin_migration.rs
- modules/fedimint-wallet-tests/src/bin/circular-deposit-test.rs
> chore(deps): bump devimint to bitcoin v0.32

- fedimint-client/src/lib.rs
> chore(docs): clarify `Client` handling

- gateway/ln-gateway/src/lightning/mod.rs
* Change all function documentation to third-person singular present tense, which is the rust convention
* Mark `routehints()` and `pay_private()` as LNv1-only
* Describe the API contract for `pay()` in much more detail
* Remove mention of "the gateway's lightning node" since that is implied because the purpose of `ILnRpcClient` is to act as the gateway's lightning node
> chore: improve documentation of ILnRpcClient

- Cargo.lock
- fedimint-bitcoind/Cargo.toml
- fedimint-bitcoind/src/bitcoincore.rs
- fedimint-bitcoind/src/electrum.rs
- fedimint-bitcoind/src/esplora.rs
- fedimint-bitcoind/src/lib.rs
- fedimint-core/src/bitcoin_migration.rs
- fedimint-testing/Cargo.toml
- fedimint-testing/src/btc/mock.rs
- modules/fedimint-wallet-client/src/backup.rs
- modules/fedimint-wallet-client/src/deposit.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-client/src/pegin_monitor.rs
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Part of #5200
Contains no non-trivial changes
> chore(deps): bump fedimint-bitcoind to bitcoin v0.32

- devimint/src/gatewayd.rs
Fixes: https://github.com/fedimint/fedimint/issues/6272
> fix: fix upgrade tests (dont deserialize `GatewayInfo`)

- modules/fedimint-lnv2-client/src/api.rs
- modules/fedimint-lnv2-client/src/cli.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-tests/src/bin/tests.rs
> chore: test gateway cache and selection

- Cargo.lock
- modules/fedimint-lnv2-client/Cargo.toml
- modules/fedimint-lnv2-client/src/cli.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-tests/src/bin/tests.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
> Lnv2 api cleanup II

- Cargo.lock
- Cargo.toml
- fedimint-server/Cargo.toml
- modules/fedimint-mint-client/Cargo.toml
- modules/fedimint-mint-client/src/backup.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/client_db.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/output.rs
> refactor(client): handle multiple outputs with a single state machine

- fedimint-cli/src/client.rs
- fedimint-core/src/net/api_announcement.rs
- fedimint-load-test-tool/src/main.rs
- gateway/ln-gateway/src/db.rs
- gateway/ln-gateway/src/federation_manager.rs
- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- gateway/ln-gateway/src/state_machine/pay.rs
- gateway/ln-gateway/tests/tests.rs
- modules/fedimint-ln-client/src/cli.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-common/src/contracts/mod.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-ln-tests/tests/tests.rs
> chore: partially bump bitcoin to v0.32

- Cargo.lock
- Cargo.toml
- fedimint-bitcoind/src/electrum.rs
- fedimint-core/src/bitcoin_migration.rs
> chore(deps): bump electrum-client to v0.21

- Cargo.lock
- Cargo.toml
- fedimint-core/Cargo.toml
- fedimint-core/src/bitcoin_migration.rs
- fedimint-core/src/encoding/mod.rs
- fedimint-core/src/lib.rs
- fedimint-testing/src/ln.rs
- gateway/ln-gateway/src/bin/cln_extension.rs
- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/gateway_module_v2/send_sm.rs
- gateway/ln-gateway/src/lightning/ldk.rs
- gateway/ln-gateway/src/lightning/lnd.rs
- gateway/ln-gateway/tests/tests.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-client/src/pay.rs
- modules/fedimint-ln-client/src/receive.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-common/src/gateway_api.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
> chore(deps): bump lightning and lightning-invoice

- fedimint-client/src/lib.rs
- fedimint-client/src/module/mod.rs
- fedimint-client/src/transaction/builder.rs
- gateway/ln-gateway/src/gateway_module_v2/mod.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-mint-client/src/backup.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/client_db.rs
- modules/fedimint-mint-client/src/input.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/oob.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-wallet-client/src/lib.rs
> refactor(client): newtype for the range of in/out idxs

- fedimint-core/src/bitcoin_migration.rs
- fedimint-core/src/encoding/btc.rs
- fedimint-core/src/encoding/mod.rs
> chore: remove bitcoin v0.29 en/decoding of PSBTs

- modules/fedimint-mint-client/src/output.rs
in MintOutputStatesCreatedMulti.
> refactor(client): parallelize getting output outcomes

- fedimint-client/src/db.rs
- fedimint-core/src/db/mod.rs
- fedimint-server/src/consensus/db.rs
- flake.nix
- gateway/ln-gateway/src/db.rs
- modules/fedimint-dummy-server/src/db.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-mint-client/src/api.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-common/src/endpoint_constants.rs
- modules/fedimint-mint-server/src/db.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
- nix/flakebox.nix
- nix/overlays/clightning.nix
> API endpoints to check e-cash status

- README.md
> chore: update readme with websdk

- fedimint-client/src/module/mod.rs
- modules/fedimint-mint-client/src/backup.rs
- modules/fedimint-mint-client/src/lib.rs
> refactor(client): use OutPoint when iterating OutPointRange

- Cargo.lock
- crypto/derive-secret/Cargo.toml
> chore: remove `bitcoin_hashes` 0.11

- fedimint-core/src/db/mod.rs
`find_by_range` has a small bug that prevents `PrefixDatabaseTransaction` from finding elements. Its just a typo in the range. Added a test to cover this scenario.
> fix: find_by_range Prefix DB Bug

- fedimint-server/src/net/peers.rs
> fix(net): flood of log messages on disconnected peer

- modules/fedimint-dummy-client/src/db.rs
The dummy migration is confusingly written. The `Unreachable` state parse a `ModuleInstanceId`, which is just a `u16`. This value is actually the length of the state though, so this decoding should happen outside of Unreachable's decoding.
> fix: dummy migration module instance id

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-cli/src/lib.rs
- fedimint-client/Cargo.toml
- fedimint-client/src/api.rs
- fedimint-client/src/backup.rs
- fedimint-client/src/db.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/module/mod.rs
- fedimint-eventlog/Cargo.toml
- fedimint-eventlog/src/lib.rs
- modules/fedimint-mint-client/Cargo.toml
- modules/fedimint-mint-client/src/event.rs
> refactor: split out fedimint-eventlog from fedimint-client

- fedimint-core/src/db/mod.rs
- modules/fedimint-lnv2-server/src/lib.rs
> fix: upgrade warn to a panic

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-cli/src/main.rs
- fedimintd/Cargo.toml
- fedimintd/src/bin/main.rs
- gateway/ln-gateway/Cargo.toml
- gateway/ln-gateway/src/bin/gatewayd.rs
"reverse backport" of #6354 
Fix #6334
> chore: switch to using jemalloc on all major binaries.

- .config/nextest.toml
- devimint/src/tests.rs
- nix/pkgs/esplora-electrs.Cargo.lock
- nix/pkgs/esplora-electrs.nix
- scripts/dev/run-test/fm-run-test
- scripts/tests/test-ci-all.sh
> chore: update our fork of esplora-electrs

- gateway/integration_tests/src/main.rs
> fix: flaky liquidity_test

- .config/semgrep.yaml
- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/backup.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/meta.rs
- fedimint-client/src/module/init.rs
- fedimint-client/src/module/init/recovery.rs
- fedimint-client/src/oplog.rs
- fedimint-client/src/sm/executor.rs
- fedimint-client/src/sm/notifier.rs
> chore(ci): enforce log targets of fedimint-cli and fedimint-client

- gateway/ln-gateway/src/lib.rs
> docs: add GatewayState::ShuttingDown to mermaid diagram

- .github/workflows/ci-nix.yml
Something fails there sometimes, and it's often unclear which exact step was it.
> chore(ci): print each step in the release pipeline

- flake.nix
Fix https://github.com/fedimint/fedimint/actions/runs/11922340790/job/33228414053
> fix(ci): some bundlers we use expect a missing `pname`

- nix/flakebox.nix
Fix https://github.com/fedimint/fedimint/actions/runs/11923997785/job/33233498506
> fix(ci): missing `devimint-faucet` output

- modules/fedimint-wallet-tests/tests/tests.rs
> fix(test): flaky on_chain_peg_in_and_peg_out_happy_case test

- devimint/src/gatewayd.rs
```
00:00:04 2024-11-19T22:50:56.566417Z  INFO fm::devimint: Devimint data dir path=/tmp/gateway_restore_test-WmPp/devimint-2727858-976
00:00:04 2024-11-19T22:50:56.713974Z  INFO devimint::tests: fedimint_cli_version="fedimint-cli 0.6.0-alpha"
00:00:04 2024-11-19T22:50:56.724145Z  INFO devimint::tests: fedimint_cli_version_hash="7147143b3e5c9425000000001e92942661eb6476"
00:00:04 2024-11-19T22:50:56.904345Z  INFO devimint::tests: gateway_cli_version="fedimint-gateway-cli 0.6.0-alpha"
00:00:05 2024-11-19T22:50:57.043152Z  INFO devimint::tests: gateway_cli_version_hash="7147143b3e5c9425000000001e92942661eb6476"
00:00:05 2024-11-19T22:50:57.204232Z  INFO devimint::tests: fedimintd_version_hash="7147143b3e5c9425000000001e92942661eb6476"
00:00:05 2024-11-19T22:50:57.226494Z  INFO …
```
> fix(ci): flake during fedimint initialization

- flake.lock
- flake.nix
```
nix bundle --bundler .# ".#devimint-faucet" -o "bins/devimint-x"
```
works again
> fix(ci): update flakebox to fix pname bundler issue again

- scripts/tests/test-ci-all.sh
I've been torturing our CI locally in a loop fixing all the issues I've spotted.
This should eventually work.
> chore(ci): CI can work faster now that some flakes are fixed

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-testing/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-wallet-client/Cargo.toml
> chore: bump to v0.5.0-rc.1

- devimint/src/devfed.rs
- devimint/src/federation/config.rs
- devimint/src/gatewayd.rs
- devimint/src/vars.rs
- fedimint-core/src/envs.rs
> chore(devimint): ability to force-disable lnv2 module

- devimint/src/devfed.rs
- devimint/src/federation/config.rs
- devimint/src/gatewayd.rs
- devimint/src/vars.rs
- fedimint-core/src/envs.rs
Backport of #6418 to `releases/v0.5`.
> [Backport releases/v0.5] chore(devimint): ability to force-disable lnv2 module

- Cargo.lock
- gateway/ln-gateway/Cargo.toml
- gateway/ln-gateway/src/lightning/ldk.rs
Backport of #6369 to `releases/v0.5`.
> [Backport releases/v0.5] fix: make ldk pay implementation idempotent

- fedimint-core/src/util/backoff_util.rs
- gateway/integration_tests/src/main.rs
> fix(ci): flake under load due to too short wait

- modules/fedimint-lnv2-tests/src/bin/tests.rs
Two benefits of testing HOLD invoices this way:
1. Allows us to verify that the gateway can successfully pay HOLD invoices (while also testing that HOLD invoices don't break LND).
2. Allows us to remove CLN node once LNv1 is not supported anymore.
> refactor: LNv2 use GW LDK to pay HOLD invoice

- Cargo.toml
> chore(dev): optimize dev build of jemalloc-sys

- fedimint-derive/src/lib.rs
> chore: improve error message of decoding error

- devimint/src/util.rs
`poll_with_timeout()` now uses fibonacci backoff rather than linear to reduce unnecessary spamming during dev fed startup
Also have `poll_simple()` call `poll()` since it is almost identical code
> chore: devimint polling uses fibonacci backoff

- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-mint-client/src/client_db.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-mint-tests/tests/tests.rs
so integrator can check they lost money and how much due to seed reuse.
> chore(recovery): save reused note indices

- fedimint-core/src/encoding/mod.rs
Contains no functional changes, just inlining functions that are only used once
> chore: inline collection en/decoding helpers

- modules/fedimint-wallet-server/src/lib.rs
>  chore(wallet-server): improve logging 

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-testing/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-wallet-client/Cargo.toml
> chore: release candidate v0.5.0-rc.2

- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-lnv2-tests/src/bin/tests.rs
> chore: make the code a bit cleaner

- fedimint-load-test-tool/src/common.rs
- fedimint-server/src/consensus/engine.rs
- fedimint-server/src/consensus/mod.rs
>  chore(core): better logging 

- devimint/src/federation.rs
Previously, devimint would coordinate a shutdown for `fedimintd` upgrade tests if the version we're upgrading to is `v0.4.*` or `v0.5.*`. This change considers if we're upgrading from `v0.3.3` or `v0.3.4-rc.1`, since those are the only two versions that require coordinating a shutdown.
I've been running upgrade tests locally with these changes and everything is passing for `v0.5.0` release candidates.
> chore: conditionally coordinate fedimintd restart in upgrade tests

- fedimint-cli/src/client.rs
- fedimint-client/src/db.rs
- fedimint-client/src/lib.rs
- fedimint-client/src/oplog.rs
- flake.nix
- modules/fedimint-wallet-tests/tests/tests.rs
> fix: use linear pagination algorithm for operation log

- .github/workflows/ci-backwards-compatibility.yml
- .github/workflows/ci-fuzz.yml
- .github/workflows/upgrade-tests.yml
- scripts/ci/run-in-fs-dir-cache.sh
It has automatic lock management, which makes unlocking 100% reliable and faster.
> chore(ci): use newly added `fs-dir-cache exec`

- devimint/src/federation.rs
Fixes: https://github.com/fedimint/fedimint/issues/6466
Fixes: https://github.com/fedimint/fedimint/issues/6367
(at least that's my suspicion)
In the past, we have seen LND fail payments when the payer and payee are not synced to the same block height. These errors manifest themselves in the LND logs as `expiry too soon, at accept height`.
If LND and LDK are not synced to the same block height, then the payment will sometimes fail. This can result in flaky tests depending on how fast the nodes sync the blocks. From the gateway's perspective, anytime we mine blocks we should wait until the gateway is caught up to bitcoind's block height before doing anything.
Somewhat difficult to verify so I'd propose we merge and monitor these tests to see if its fixed and re-open if its still a problem.
> fix: wait for block height after gateway pegin

- gateway/ln-gateway/src/lightning/lnd.rs
Fixes: https://github.com/fedimint/fedimint/issues/6443
We are hitting another syncing race condition where LND properly connects to the peer, but the node isn't fully synced so it can't open the channel. Then on subsequent tries to open the channel, it consistently fails because it can't connect to an already connected peer.
```
2024-12-02T20:56:17.415654Z ERROR open_channel{payload=OpenChannelPayload { pubkey: PublicKey(8cb3e84d5fe225c72ce41e3e0c0fedacd83aa4284b524fc74a8c923910fa6b7b3c151602120d61f5fc9d99403344c0e255fbb416b17760b53cbfc2b0cc800f8d), host: "127.0.0.1:18887", channel_size_sats: 10000000, push_amount_sats: 5000000 }}: ln_gateway::rpc::rpc_server: error=Lightning error: Failed to open channel: Failed to open channel Status { code: Unknown, message: "channels cannot be …
```
> fix: LND check if peer is already connected

- gateway/ln-gateway/src/lightning/lnd.rs
Backport of #6492 to `releases/v0.5`.
> [Backport releases/v0.5] fix: LND check if peer is already connected

- gateway/integration_tests/src/main.rs
Backport of #6397 to `releases/v0.5`.
> [Backport releases/v0.5] fix: flaky liquidity_test

- gateway/ln-gateway/src/lib.rs
* Prevent shadowing of `payment_request` by renaming to `payment_request_or` (since it is an `Option`)
* Check that `payment_request_or` is `Some` before locking `self.state`
* Call `handle_lightning_payment()` inside of the `if let GatewayState::Running ...`, removing the need to document why we're holding a lock on `self.state`
> refactor: cleanup Gateway::route_lightning_payments()

- fedimint-server/src/config/mod.rs
> fix(server): typo in log statement

- Cargo.lock
- Cargo.toml
- fedimint-core/Cargo.toml
- fedimint-core/src/amount.rs
- fedimint-core/src/core.rs
- fedimint-core/src/encoding/mod.rs
- fedimint-core/src/lib.rs
- fedimint-core/src/macros.rs
- fedimint-core/src/transaction.rs
- modules/fedimint-mint-common/src/lib.rs
Every time I'm debugging something and scrolling through logs, it annoys me, so I finally did something about it.
Before:
> ```2024-12-05T04:31:04.754355Z DEBUG spawn{task="peg-in monitor"}: fm::client::net::api: Finalized and submitting transaction txid=2bf04a0db06da03a0dd6631f392931f7fd7eb0e9445f6ce5479fb43bf6688cd8 transaction=Transaction { inputs: [DynInput { id: 2, kind: Some(ModuleKind("wallet")), inner: V1(WalletInputV1 { outpoint: OutPoint { txid: 7ca40498f24518a8d118a128345233763b4863c4b99a3e3d7508d1c50403e7a3, vout: 1 }, tweak_contract_key: PublicKey(8d873ac34c2ef91e50404db29106200b4f31db36cf35941f48fec44f6575aaaae85a1e95656bea2563ba49e7adba57c1d70dbd9eb5b2c760b6c31434e75eacc7), tx_out: TxOut { value: 1000000 SAT, script_pubkey: Script(OP_0 OP_PUSHBYTES_32 …
```
> chore: improve some fmt::Debug outputs

- modules/fedimint-lnv2-tests/Cargo.toml
- modules/fedimint-lnv2-tests/bin/tests.rs
- modules/fedimint-lnv2-tests/src/bin/tests.rs
- scripts/tests/lnv2-module-test.sh
> fix: check that full balance becomes available to the client

- fedimint-client/src/lib.rs
- fedimint-client/src/module/mod.rs
- gateway/ln-gateway/src/state_machine/mod.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
> refactor(client): await_primary_module_output not return Amount

- fedimint-api-client/src/api/global_api.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-api-client/src/lib.rs
- fedimint-api-client/src/query.rs
- fedimint-client/src/transaction/sm.rs
- fedimint-core/src/util/backoff_util.rs
- fedimint-server/src/consensus/engine.rs
- modules/fedimint-dummy-tests/tests/tests.rs
- modules/fedimint-mint-tests/tests/tests.rs
- modules/fedimint-wallet-client/src/api.rs
> chore: api client retries on level of individual peers

- fedimint-api-client/src/api/mod.rs
>  chore(api-client): add useful logging spans 

- fedimint-api-client/src/api/error.rs
- fedimint-api-client/src/api/global_api.rs
- fedimint-api-client/src/api/mod.rs
- modules/fedimint-wallet-client/src/api.rs
>  chore(api-client): renames and tweaks 

- fedimint-cli/src/lib.rs
- fedimint-client/src/lib.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-testing/src/federation.rs
- fedimint-testing/src/fixtures.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/lib.rs
Backport of #6524 to `releases/v0.5`.
> [Backport releases/v0.5] feat: allow specifying primary module kind

- fedimint-client/src/lib.rs
> chore: rename - `_gen` is informative

- fedimint-server/src/consensus/api.rs
> fix(server): small submit_transaction logging improvements

- fedimint-client/src/transaction/sm.rs
Re #6530
Most of the original code was superseded/incorporated by #6538
The last optimization left is not starting await until first successful `submit`. This cuts number of requests in parallel at the beginning by half, which might be meaningful if the client starts with multiple pending txes to submit after period of being offline in a low bandwidth env.
I was a bit worried about extra latency, but it looks like it's OK - [the consensus has latency as well](https://github.com/fedimint/fedimint/discussions/6521), so client has more than enough time to make a another request. 
old:
```
```
new:
```
```
> chore(client): don't await tx until it was submitted 

- justfile.fedimint.just
- scripts/bench-compilation.sh
A little command to quickly test incremental recompilation time after modifying just a given module.
> chore(dev): `just bench-compilation-quick-incr`

- Cargo.lock
- misc/git-hooks/pre-commit
- modules/fedimint-dummy-common/Cargo.toml
- modules/fedimint-empty-common/Cargo.toml
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-common/Cargo.toml
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-ln-tests/tests/tests.rs
- modules/fedimint-lnv2-common/Cargo.toml
- modules/fedimint-meta-common/Cargo.toml
- modules/fedimint-mint-common/Cargo.toml
- modules/fedimint-unknown-common/Cargo.toml
- modules/fedimint-wallet-common/Cargo.toml
Old:
```
> j bench-compilation-quick-incr fedimint-client
total    user     sys
Incr  check   debug:    3.60    4.59    2.9
```
New:
```
> j bench-compilation-quick-incr fedimint-client
total    user     sys
Incr  check   debug:    3.22    3.82    2.27
```
> chore: enforce light -common module deps

- modules/fedimint-wallet-server/src/lib.rs
> chore(wallet-server): fix noisy feerate logging

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-cli/src/main.rs
- fedimint-rocksdb/Cargo.toml
- fedimintd/Cargo.toml
- fedimintd/src/bin/main.rs
- flake.nix
- gateway/ln-gateway/Cargo.toml
- gateway/ln-gateway/src/bin/gatewayd.rs
This reverts commit 6cee01419778eab7c37f9cbf86330f60bcae04dd.
... which reverted enabling jemalloc which was caused by fedi-specific toolchain problem:
```
fedi-fedimint-pkgs-group-ci-deps>   /nix/store/wmq01pqz681xdgq2n0hl5w7bbdr738g1-clang-wrapper-16.0.6/bin/clang -std=gnu11 -Werror=unknown-warning-option -Wall -Wextra -Wshorten-64-to-32 -Wsign-compare -Wundef -Wno-format-zero-length -Wpointer-arith -Wno-missing-braces -Wno-missing-field-initializers -pipe -g3 -fvisibility=hidden -Wimplicit-fallthrough -O3 -funroll-loops -O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 --target=x86_64-unknown-linux-gnu -Wall -c -O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 --target=x86_64-unknown-linux-gnu -Wall -D_GNU_SOURCE …
```
> Reapply "chore: enable jemalloc on rocksdb itself (v0.5 backport)"

- misc/git-hooks/pre-commit
> chore(dev): make pre-commit hook silent again

- devimint/src/cfg/bitcoin.conf
> chore(ci): backport some fixes from `master` to 0.5

- devimint/src/gatewayd.rs
Backport of #6412 to `releases/v0.5`.
> [Backport releases/v0.5] fix(ci): flake during fedimint initialization

- docs/release-process.md
- justfile.fedimint.just
Closes https://github.com/fedimint/fedimint/issues/6598
> [Backport v0.5] chore: add cargo publish to just file

- fedimint-cli/Cargo.toml
- fedimint-client-wasm/Cargo.toml
- modules/fedimint-mint-client/Cargo.toml
- modules/fedimint-mint-client/src/lib.rs
Backport of #6587 to `releases/v0.5`.
> [Backport releases/v0.5] chore(wasm): disable cli feature

- fedimint-core/src/db/mod.rs
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c099f680214ed910d9defdf821c88d29
> chore: don't loose decoding error cause

- devimint/src/devfed.rs
- devimint/src/external.rs
- devimint/src/federation.rs
- mprocs.log
A bunch of devimint fixes and tweaks
I recommend reviewing commit-by-commit
> chore: devimint cleanup

- .cargo/audit.toml
> fix: cargo audit

- fedimint-api-client/src/api/error.rs
> chore: fix formatting of FederationError

- fedimint-server/src/net/peers_reliable.rs
> chore: improve logging [0.5]

- fedimint-server/src/consensus/engine.rs
This one is surprisingly spammy on start.
> chore(consensus): improve logging

- fedimint-server/src/net/peers.rs
> chore: improve logging

- modules/fedimint-wallet-client/src/cli.rs
> feat(client): fedimint-cli module wallet get-consensus-block-count

- fedimint-core/src/db/mod.rs
https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations
> chore: print causes, but not backtrace

- fedimint-cli/src/client.rs
- fedimint-cli/src/lib.rs
Fix #6622
Now this works:
```
❯ fedimint-cli dev api --module wallet block_count
{
"value": 153
}
❯ fedimint-cli dev api --module 2 block_count
{
"value": 153
}
```
> feat: `fedimint-cli dev api --module`

- modules/fedimint-wallet-server/src/lib.rs
"consensus count" doesn't seem like a real thing. We have only one consensus.
> chore(wallet-server): improve logging statement

- fedimint-core/src/session_outcome.rs
> chore: add assert in SessionOutcome::header

- modules/fedimint-wallet-server/src/lib.rs
Backport of #6629 to `releases/v0.5`.
> [Backport releases/v0.5] chore(wallet-server): improve logging statement

- scripts/dev/run-test/fm-run-test
> chore: include incremental time change in test output

- gateway/ln-gateway/src/client.rs
- gateway/ln-gateway/src/db.rs
Fixes: https://github.com/fedimint/fedimint/issues/6579
We have a nasty bug in the gateway's database. The crux of the issue is that when we added client databases to the same global database as the gateway's DB, we forgot to give them their own prefix and instead relied on the `FederationId` to provide uniqueness. This is fine....most of the time. As long as a `FederationId` doesn't start with `0x04`, then everything is ok. But if it does, then it actually clashes with `FederationIdKey` which is used to key the `FederationConfig` and the database cannot tell the difference. Trying to read the `FederationConfig` will result in a decoding error.
The fix is to migrate the isolated databases to be behind a prefix so that it doesn't clash with `FederationIdKey`. A database migration has been …
> fix: Gateway isolated DBs clash with `FederationConfig`

- gateway/cli/src/ecash_commands.rs
- gateway/ln-gateway/src/lib.rs
- gateway/ln-gateway/src/rpc/mod.rs
- gateway/ln-gateway/src/rpc/rpc_client.rs
- gateway/ln-gateway/src/rpc/rpc_server.rs
- scripts/dev/run-test/fm-run-test
- scripts/tests/test-ci-all.sh
On top of #6647 
Completes #6601
For consistency, I tried to do roughly what `gateway-cli eacash pegin` is doing.
>  feat(ln-gateway): `gateway-cli ecash pegin-recheck`

- Cargo.lock
- crypto/tbs/benches/tbs.rs
- crypto/tbs/src/lib.rs
- crypto/tpe/src/lib.rs
- fedimint-server/src/config/distributedgen.rs
- gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-common/src/contracts.rs
- modules/fedimint-lnv2-server/Cargo.toml
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-mint-client/src/output.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
> Cleanup cryptography around dealer dkg

- Cargo.lock
- fedimint-api-client/src/api/mod.rs
- fedimint-core/Cargo.toml
- fedimint-core/src/net/peers.rs
- fedimint-core/src/net/peers/fake.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/consensus/aleph_bft/network.rs
- fedimint-server/src/consensus/api.rs
- fedimint-server/src/consensus/engine.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/multiplexed.rs
- fedimint-server/src/net/peers.rs
> cleanup p2p networking layer

- modules/fedimint-ln-client/src/lib.rs
we need to know "have we paid this invoice"
> chore: expose get_prev_payment_result

- fedimint-server/src/consensus/engine.rs
now computes header only once outside of the all() call
> chore: improve request_signed_session_outcome

- devimint/src/tests.rs
- fedimint-core/src/core/server.rs
- fedimint-core/src/module/mod.rs
- fedimint-server/src/consensus/api.rs
- fedimint-server/src/consensus/engine.rs
- fedimint-server/src/consensus/transaction.rs
- modules/fedimint-mint-common/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-tests/src/bin/wallet-recovery-test-2.rs
- scripts/tests/test-ci-all.sh
- scripts/tests/wallet-recovery-test-2.sh
Impl non-consensus version of #6220
> feat(wallet-server): reject reused blind nonces during tx submission

- docs/deploying/docker-mutiny.md
Confidence inspiring to see lychee found this :slightly_smiling_face:
> fix(docs): update broken links

- README.md
Updated "Running your own Fedimint" section in README to improve clarity and readability.
> chore(docs): update 'Running your own Fedimint' section in readme

- fedimint-client/src/backup.rs
> fix: backup size padding being 2B off sometimes

- fedimint-core/src/util/backoff_util.rs
> fix: sane maximal networking backoff

- Cargo.lock
- modules/fedimint-mint-common/Cargo.toml
- modules/fedimint-mint-common/src/endpoint_constants.rs
- modules/fedimint-mint-common/src/lib.rs
- modules/fedimint-mint-server/src/db.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-mint-tests/tests/tests.rs
* Redundant serialization code for `Nonce` that needlessly pulled in `bincode`
* Old e-cash backup logic
> Remove unused code

- scripts/dev/devimint-env.sh
For people like me who keep forgetting they are already in devimint-env.
> chore(devimint-env): set PROMPT_ENV_INDICATOR

- scripts/dev/run-test/fm-run-test
- scripts/tests/upgrade-test.sh
> chore(ci): wrap all upgrade tests in fm-run-test

- fedimintd/src/fedimintd.rs
> fix: make code version string a valid SemVer version number

- fedimint-api-client/src/api/error.rs
- fedimint-api-client/src/api/global_api.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-api-client/src/lib.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/api.rs
- fedimint-client/src/lib.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/net/api/announcement.rs
- modules/fedimint-ln-client/src/api.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Follow up to this pr: https://github.com/fedimint/fedimint/pull/6725
> Api Client Refactor follow up

- fedimint-api-client/src/api/error.rs
- fedimint-api-client/src/api/global_api.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-api-client/src/lib.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/api.rs
- fedimint-client/src/lib.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/net/api/announcement.rs
- modules/fedimint-ln-client/src/api.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Backport of #6732 to `releases/v0.6`.
> [Backport releases/v0.6] Api Client Refactor follow up

- .github/workflows/ci-backwards-compatibility.yml
- .github/workflows/upgrade-tests.yml
Followup re: https://github.com/fedimint/fedimint/pull/6744#discussion_r1924413192
> refactor(ci): use unset instead of empty string in bash

- modules/fedimint-wallet-common/src/lib.rs
- modules/fedimint-wallet-server/src/envs.rs
- modules/fedimint-wallet-server/src/lib.rs
Backport of #6749 to `releases/v0.6`.
> [Backport releases/v0.6] chore: default feerate multiplier 4 -> 2 and ability to customize it

- fedimint-client/src/module/init/recovery.rs
- fedimint-load-test-tool/src/main.rs
- flake.lock
- gateway/fedimint-lightning/src/ldk.rs
- utils/portalloc/src/data.rs
Re: https://github.com/fedimint/fedimint/actions/runs/12956661631/job/36143443406?pr=6759
```
ERROR: the `nixpkgs` input is 31 days old (the max allowed is 30)
Error: Non-zero exit code of `1`.
```
> chore: update nix flake

- fedimint-server/src/consensus/engine.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
Backport of #6773 to `releases/v0.6`.
> [Backport releases/v0.6] chore: lower logging of consensus proposals

- modules/fedimint-wallet-server/src/lib.rs
Polling is almost always suboptimal.
> chore(wallet-server): make tx broadcasting faster and less noisy

- fedimint-client/src/db.rs
- fedimint-client/src/oplog.rs
> feat: add outcome_time to operation log entry

- README.md
Seems like it's no longer maintained.
> chore(README): remove Mutiny Wallet from client apps

- modules/fedimint-wallet-server/src/lib.rs
Backport of #6772 to `releases/v0.6`.
> [Backport releases/v0.6] chore(wallet-server): make tx broadcasting faster and less noisy

- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
> chore: checking for consensus version in test a bit spammy

- fedimint-core/src/module/mod.rs
Backport of #6775 to `releases/v0.6`.
> [Backport releases/v0.6] chore: lower logging level of "api request complete"

- fedimint-client/src/db.rs
- fedimint-client/src/oplog.rs
> backport: feat: add outcome_time to operation log entry

- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-meta-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
> chore: unify consensus item processing trace logging message

- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-meta-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
Backport of #6786 to `releases/v0.6`.
> [Backport releases/v0.6] chore: unify consensus item processing trace logging message

- fedimint-bitcoind/src/lib.rs
- fedimint-core/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
> refactor(bitcoind-monitor-tasks): improvements

- fedimint-api-client/src/api/error.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-server/src/consensus/engine.rs
- modules/fedimint-ln-client/src/receive.rs
Backport of #6787 to `releases/v0.6`.
> [Backport releases/v0.6] chore: cleanup peer error reporting

- fedimint-core/src/lib.rs
- fedimint-server-core/src/lib.rs
- fedimint-server/src/consensus/transaction.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-empty-server/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-meta-server/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-unknown-server/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Backport of #6799 to `releases/v0.6`.
> [Backport releases/v0.6] chore: add InPoint for TX inputs

- modules/fedimint-lnv2-server/src/lib.rs
> chore: increase unix time granularity

- fedimint-core/src/task.rs
- fedimint-server/src/consensus/aleph_bft/spawner.rs
Backport of #6792 to `releases/v0.6`.
> [Backport releases/v0.6] chore: make alephbft tasks log on lower level

- docs/lithning_module_v1.md
Add some [fancy diagrams](https://github.com/fedimint/fedimint/blob/49b3e7016eeecef21de82325fd4c4682bda5b539/docs/lithning_module_v1.md) to explain how our LN integration works.
> chore: add LNv1 protocol diagrams

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-testing/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/fedimint-lightning/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-wallet-client/Cargo.toml
> chore: bump version to v0.6.0-rc.2

- devimint/src/version_constants.rs
- gateway/ln-gateway/src/lib.rs
- modules/fedimint-lnv2-tests/bin/tests.rs
We are not currently testing backwards compatibility between v0.6.0-rc.X and master, but I noticed a few incompatibilities while testing https://github.com/fedimint/fedimint/pull/6781
> fix: lnv2 small backwards compatibility fixes

- fedimint-bitcoind/src/lib.rs
- fedimint-core/src/envs.rs
> chore: change default bitcoin polling rate add ability to customize

- fedimint-api-client/src/api/global_api.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-cli/src/lib.rs
- fedimint-core/src/backup.rs
- fedimint-core/src/endpoint_constants.rs
- fedimint-server/src/consensus/api.rs
> Backport of backup stats

- fedimint-bitcoind/src/lib.rs
- fedimint-core/src/envs.rs
> chore: change default bitcoin polling rate add ability to customize [0.6 backport]

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-testing/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/fedimint-lightning/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-wallet-client/Cargo.toml
~Let's wait to merge until we have the outstanding backports merged into `releases/v0.6`.~
Everything is backported, we're good to merge.
> chore: bump version to v0.6.0-rc.3

- .cargo/audit.toml
- flake.lock
> chore: fix cargo-audit

- Cargo.lock
- Cargo.toml
This might fix cargo audit failing.
> chore: update iroh

- fedimint-api-client/src/api/mod.rs
> chore: lower logging level

- fedimint-api-client/src/api/mod.rs
> chore: `trace!`-log every individual request [0.6 backport]

- fedimint-api-client/src/api/mod.rs
> chore: `trace!`-log every individual request

- devimint/src/vars.rs
- gateway/ln-gateway/src/config.rs
Fixes https://github.com/fedimint/fedimint/issues/6857
Backporting https://github.com/fedimint/fedimint/pull/6854 to v0.5.1
> [backport releases v0.5] chore: change lightning module mode default

- gateway/fedimint-lightning/src/lnd.rs
- gateway/integration_tests/src/main.rs
Backport of #6876 to `releases/v0.6`.
> [Backport releases/v0.6] fix: LND Gateway not forwarding payments correctly

- gateway/integration_tests/src/main.rs
- gateway/ln-gateway/src/lightning/lnd.rs
Backport of https://github.com/fedimint/fedimint/pull/6876 to releases/v0.5.
> [Backport releases/v0.5] fix: LND Gateway not forwarding payments correctly

- docs/lightning_module_v1.md
- docs/lightning_module_v2.md
Similar to https://github.com/fedimint/fedimint/pull/6812, but for LNv2.
> docs: add LNv2 sequence diagram

- Cargo.lock
- Cargo.toml
- fedimint-api-client/src/api/mod.rs
- fedimint-server/src/consensus/mod.rs
> chore: bump iroh dep to 0.33

- Cargo.lock
- devimint/src/federation.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-api-client/src/lib.rs
- fedimint-cli/src/lib.rs
- fedimint-client/src/client/builder.rs
- fedimint-core/src/util/mod.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-server/Cargo.toml
- fedimint-server/src/config/mod.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/lib.rs
- fedimint-server/src/net/api/announcement.rs
- fedimint-server/src/net/p2p_connector.rs
- fedimint-testing/src/federation.rs
- fedimint-testing/src/lib.rs
- fedimint-wasm-tests/src/lib.rs
- fedimintd/src/lib.rs
- gateway/fedimint-gateway-server/src/lib.rs
- modules/fedimint-wallet-tests/tests/tests.rs
This is the last puzzle piece to complete initial iroh support.
> feat: enable client to connect via iroh

- justfile.fedimint.just
Updating the justfile with the most recently supported versions
> chore: update justfile with new versions

- fedimint-core/src/util/mod.rs
- fedimint-server/src/net/p2p_connector.rs
> cleanup: localize url default port logic

- Cargo.lock
- devimint/src/cli.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-server/src/config/api.rs
- fedimint-server/src/consensus/mod.rs
- nix/flakebox.nix
- utils/portalloc/src/data/dto.rs
Bunch of fixes trying to get `env FM_FORCE_IROH=1 j test-ci-all` work.
> chore(devimint): iroh fixes

- Cargo.lock
- Cargo.toml
- devimint/Cargo.toml
- devimint/src/cli.rs
- devimint/src/envs.rs
- devimint/src/lib.rs
- gateway/integration_tests/src/main.rs
- modules/fedimint-lnv2-tests/bin/tests.rs
- modules/fedimint-meta-tests/src/bin/meta-sanity-test.rs
- modules/fedimint-mint-tests/src/bin/mint-module-tests.rs
- modules/fedimint-wallet-tests/src/bin/wallet-module-tests.rs
> refactor(devimint): builder pattern for `run_devfed_test`

- fedimint-server/src/config/api.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/net/p2p_connector.rs
- fedimint-testing/src/federation.rs
> cleanup: simplify p2p cert generation

- fedimint-client/src/db.rs
Followup to https://github.com/fedimint/fedimint/pull/6950#discussion_r1980217302
> fix: update log message for unordered log key

- fedimint-client/src/db.rs
- fedimint-eventlog/src/lib.rs
Closes https://github.com/fedimint/fedimint/issues/6958
> [Backport] fix(client): switched db prefixes

- devimint/src/federation.rs
- devimint/src/tests.rs
- fedimint-cli/src/lib.rs
> fix(client): hardcoding module rpc endpoint name

- scripts/dev/run-test/fm-run-test
> chore(ci): output logs of key services on test failure

- .lycheeignore
> fix(ci): ignore unreliable link

- fedimint-api-client/src/api/mod.rs
> fix(client): `wss` connector missing

- scripts/dev/run-test/fm-run-test
> fix(ci): dumping logs when test fails

- Cargo.lock
- fedimint-client-module/src/module/init.rs
- fedimint-client/src/client.rs
- fedimint-client/src/client/builder.rs
- fedimint-client/src/db.rs
- fedimint-client/src/module_init.rs
- fedimint-client/src/sm/executor.rs
- fedimint-core/src/db/mod.rs
- fedimint-dbtool/src/dump.rs
- fedimint-server-core/src/init.rs
- fedimint-server-tests/tests/migration.rs
- fedimint-server/src/consensus/db.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/db.rs
- fedimint-server/src/lib.rs
- fedimint-server/src/net/api/announcement.rs
- fedimint-testing-core/src/db.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-lnv2-client/Cargo.toml
- modules/fedimint-lnv2-client/src/db.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-server/src/lib.rs
- scripts/tests/test-ci-all.sh
> chore: db integrity check

- scripts/dev/run-test/fm-run-test
Couple of newlines here and there should help.
> chore(ci): on test fail, make it easier to find each section

- scripts/tests/test-ci-all-backcompat.sh
> fix(ci): backcompat tests logging too much

- .cargo/audit.toml
- devimint/src/external.rs
- scripts/dev/run-test/fm-run-test
- scripts/tests/test-ci-all-backcompat.sh
> chore: improve CI debugability

- README.md
> chore: add Vipr Wallet to list of wallets

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-testing/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/fedimint-lightning/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-wallet-client/Cargo.toml
> chore: bump version to v0.6.2-alpha

- .cargo/audit.toml
> fix: cargo-audit complains about `ring` issue

- devimint/src/cfg/lightningd.conf
- devimint/src/cfg/lnd.conf
- devimint/src/external.rs
- scripts/dev/run-test/fm-run-test
>  chore(ci): dump CLN logs on test failure 

- scripts/_common.sh
> fix: `set -euo pipefail` detection bug

- .cargo/audit.toml
- flake.lock
I guess new contributors started going through the reported issues and filling them as vulnerabilities.
> fix: cargo-audit complains again, and again

- devimint/src/external.rs
> chore(devimint): assert that txes show immediately in the mempool

- fedimint-core/src/task.rs
- fedimint-server/src/consensus/mod.rs
> chore(server): iroh rpc handling tasks less noisy

- fedimint-client-module/src/db.rs
- fedimint-client-module/src/module/init.rs
- fedimint-client/src/db.rs
- fedimint-client/src/module_init.rs
- fedimint-core/src/db/mod.rs
- fedimint-server-core/src/init.rs
- fedimint-server/src/consensus/db.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-testing-core/src/db.rs
- gateway/fedimint-gateway-server/src/db.rs
- gateway/fedimint-gateway-server/src/lib.rs
- modules/fedimint-dummy-client/src/lib.rs
- modules/fedimint-dummy-server/src/db.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-empty-client/src/lib.rs
- modules/fedimint-empty-server/src/lib.rs
- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-meta-client/src/lib.rs
- modules/fedimint-meta-server/src/lib.rs
- modules/fedimint-mint-client/src/lib.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-unknown-server/src/lib.rs
- modules/fedimint-wallet-server/src/db.rs
- modules/fedimint-wallet-server/src/lib.rs
... over client vs server context, so we can extend what is possible on each side separately.
> refactor: parametrize migration context

- fedimint-server/src/lib.rs
> chore: re-enable api announcements with iroh

- fedimint-server/src/consensus/api.rs
- fedimint-server/src/lib.rs
- fedimint-server/src/metrics.rs
> [Backport 0.6]  feat: expose additional backup metrics via prometheus 

- modules/fedimint-lnv2-client/src/lib.rs
This makes fedimint-cli commands slow to finish.
> fix(lnv2-client): gateway_map_update_task slow to cancel

- Cargo.lock
- Cargo.toml
- fedimint-api-client/Cargo.toml
- fedimint-api-client/src/api/mod.rs
- fedimint-core/Cargo.toml
- fedimint-server/Cargo.toml
- fedimintd/src/fedimintd.rs
- gateway/fedimint-gateway-client/src/general_commands.rs
- justfile.fedimint.just
- modules/fedimint-ln-server/Cargo.toml
- modules/fedimint-lnv2-server/Cargo.toml
- modules/fedimint-wallet-server/Cargo.toml
I added:
```
just check-packages-features
```
that will build every package with some cargo feature combinations we care about and see if it is working.
I don't think running it over and over on every PR, etc. is worth it, so I wrapped it into a new `just final-check-release` which we should call before publishing releases. 
I fixed issues it spotted and tightened how we handle some feature flags.
>  chore: just final-check-release 

- fedimint-server/src/config/dkg.rs
- fedimint-server/src/config/mod.rs
> chore: improve dkg logging

- fedimint-client-module/src/module/mod.rs
- modules/fedimint-gwv2-client/src/api.rs
- modules/fedimint-gwv2-client/src/lib.rs
- modules/fedimint-gwv2-client/src/receive_sm.rs
- modules/fedimint-gwv2-client/src/send_sm.rs
- modules/fedimint-lnv2-client/src/api.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-client/src/receive_sm.rs
- modules/fedimint-lnv2-client/src/send_sm.rs
- modules/fedimint-lnv2-common/src/gateway_api.rs
- modules/fedimint-lnv2-common/src/lib.rs
- modules/fedimint-lnv2-server/src/db.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-lnv2-tests/tests/mock.rs
- modules/fedimint-lnv2-tests/tests/tests.rs
- scripts/_common.sh
> feat: reference contracts by outpoint instead of contract id

- docs/api.md
- docs/rustdoc-index.md
- justfile.fedimint.just
[Rendered](https://github.com/dpc/fedimint/blob/dpc/jj-qmuyrkpsvmyp/docs/api.md)
AI-generated api docs are probably better than nothing.
> chore: `just ai-generate-api-docs`

- docker/deploy-fedimintd/docker-compose.yaml
- docker/iroh-fedimintd/docker-compose.yaml
> chore: expose iroh ports in dockerfiles

- gateway/integration_tests/src/main.rs
New Bolt12 test seems to be flaky: https://github.com/fedimint/fedimint/actions/runs/14086390262/job/39452597015?pr=7064
Let's not rely on balances, just lookup the transaction directly.
> test: lookup transaction instead of balance check

- fedimint-core/src/admin_client.rs
- fedimint-server/src/config/setup.rs
> chore: rename for consistency

- modules/fedimint-lnv2-tests/Cargo.toml
- scripts/tests/lnv2-module-test.sh
To unify with other modules.
Close #6907
> refactor: rename lnv2 module tests

- Cargo.lock
- fedimint-server-ui/Cargo.toml
- fedimint-server-ui/src/dashboard.rs
- fedimint-server-ui/src/lib.rs
- fedimint-server-ui/src/meta.rs
- modules/fedimint-meta-server/src/lib.rs
> chore: implement meta UI

- .github/workflows/ci-nix.yml
- .gitignore
This should accomplish also #7099 as a side-effect.
> chore(ci): Build our release packages on aarch64-darwin

- Cargo.lock
- fedimint-server-ui/Cargo.toml
- fedimint-server-ui/assets/style.css
- fedimint-server-ui/src/dashboard.rs
- fedimint-server-ui/src/error.rs
- fedimint-server-ui/src/lib.rs
- fedimint-server-ui/src/meta.rs
You can try with
```
env FM_FEDERATIONS_BASE_PORT=2000 just devimint-env
```
and then opening http://localhost:2002/ http://localhost:2006/ http://localhost:2010/ http://localhost:2014/
Suggestions for well known keys:
Grouping of pending submissions:
One thing I'd like to add is showing proposals as diffs against current consensus, but I want to wrap up what I have for today.
> chore(ui): meta editing 

- fedimint-client-wasm/src/lib.rs
Backport of #7046 to `releases/v0.6`.
> [Backport releases/v0.6] feat: Add parse_invite_code function in fedimint-client-wasm

- fedimint-server/src/consensus/api.rs
> fix: don't return own peer status

- fedimintd/src/envs.rs
- fedimintd/src/lib.rs
> feat(mint): allow overriding the default esplora server

- Cargo.lock
- fedimint-core/src/module/audit.rs
- fedimint-server-ui/Cargo.toml
- fedimint-server-ui/src/audit.rs
- fedimint-server-ui/src/dashboard.rs
- fedimint-server-ui/src/invite_code.rs
- fedimint-server-ui/src/lnv2.rs
- mprocs.log
* remove modal and QR code
* use simple table for audit and ensure deterministic ordering
* Improve lnv2 layout inside the tile
> cleanup: remove modal and QR code

- .github/workflows/ci-nix.yml
> fix(ci): aarch64-darwin building packages

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-testing/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/fedimint-lightning/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-wallet-client/Cargo.toml
> chore: bump version to v0.6.2-rc.0

- docs/release-process.md
Closes https://github.com/fedimint/fedimint/issues/6747
> docs: update release process to use `-beta` before `-rc`

- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-lnv2-client/src/send_sm.rs
> fix: make gateway and invoice optional for recovery

- fedimint-server-ui/src/wallet.rs
We simply display the information in one table.
> ui: simplify wallet view

- fedimint-server-ui/src/assets.rs
> chore(ui): cache static assets on the client side for 1h

- devimint/src/devfed.rs
> fix: `just devimint-env-pre-dkg` after recurringd landed

- fedimint-server-ui/src/invite_code.rs
- fedimint-server-ui/src/lnv2.rs
- fedimint-server-ui/src/wallet.rs
- modules/fedimint-wallet-server/src/lib.rs
Backport of #7140 to `releases/v0.7`.
> [Backport releases/v0.7] Wallet UI Improvements

- fedimintd/src/fedimintd.rs
- modules/fedimint-lnv2-tests/bin/tests.rs
Low enough to not matter for the user, but not zero so its always tested.
> fix: set default lnv2 fee to 0.01%

- lnurlp/Cargo.toml
Backport of #7155 to `releases/v0.7`.
> [Backport releases/v0.7] fix: add async feature to lnurlp

- devimint/src/federation.rs
- fedimint-server/src/config/mod.rs
- fedimintd/src/envs.rs
- fedimintd/src/fedimintd.rs
> cleanup: remove unused env variables

- CAHNGELOG.md
Let's try to add major changes as we implement them so there's no big chunk of work at the end when releasing.
> chore: add changelog file

- .github/workflows/ci-nix.yml
- nix/flakebox.nix
For anyone who wants to use `fedimint-recurringd` in a docker container
> chore: build and publish fedimint-recurringd container

- .github/workflows/ci-nix.yml
- nix/flakebox.nix
Backport of #7179 to `releases/v0.7`.
> [Backport releases/v0.7] chore: build and publish fedimint-recurringd container

- Cargo.lock
- Cargo.toml
- devimint/src/tests.rs
- fedimint-recurringd-tests/Cargo.toml
- fedimint-recurringd-tests/src/bin/fedimint-recurringd-tests.rs
- scripts/tests/recurringd-test.sh
- scripts/tests/test-ci-all.sh
Just moves a test
Partially addresses https://github.com/fedimint/fedimint/issues/7125
> chore: move recurringd test out of devimint

- .github/workflows/ci-nix.yml
> fix(ci): bundle binaries on Linux releases

- .github/workflows/ci-nix.yml
Backport of #7196 to `releases/v0.7`.
> [Backport releases/v0.7] fix(ci): bundle binaries on Linux releases

- nix/flakebox.nix
Closes https://github.com/fedimint/fedimint/issues/7190
@dpc and I synced and this is the correct approach.
> chore: remove completed todo re: zlib

- CAHNGELOG.md
> chore: add v0.7.0 changelog entry

- LICENSE
- fedimint-startos/LICENSE
> chore: bump license date

- Cargo.lock
> chore: update yanked dependency `bytemuck`

- fedimint-cli/Cargo.toml
- fedimint-cli/src/main.rs
- fedimint-rocksdb/Cargo.toml
- fedimintd/Cargo.toml
- fedimintd/src/bin/main.rs
- gateway/ln-gateway/Cargo.toml
- gateway/ln-gateway/src/bin/gatewayd.rs
https://github.com/tikv/jemallocator/issues/125
> fix(build): disable jemallocator on ios [0.6 backport]

- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-cli/src/main.rs
- fedimint-rocksdb/Cargo.toml
- fedimintd/Cargo.toml
- fedimintd/src/bin/main.rs
- gateway/fedimint-gateway-server/Cargo.toml
- gateway/fedimint-gateway-server/src/bin/gatewayd.rs
Backport of #7238 to `releases/v0.7`.
> [Backport releases/v0.7] fix(build): disable jemallocator on ios

- fedimintd/src/envs.rs
- fedimintd/src/fedimintd.rs
> Cleanup Environment Variables for server

- devimint/src/vars.rs
- fedimint-server-bitcoin-rpc/src/bitcoind.rs
- fedimint-testing/src/fixtures.rs
- fedimintd/src/envs.rs
- fedimintd/src/fedimintd.rs
> feat: improve bitcoin rpc cli interface with exclusive options

- fedimint-server/src/consensus/engine.rs
> chore(consensus): improve debugging of rejected citems

- fedimint-server/src/consensus/engine.rs
Backport of #7255 to `releases/v0.7`.
> [Backport releases/v0.7] chore(consensus): improve debugging of rejected citems

- fedimint-server/src/consensus/engine.rs
Closes https://github.com/fedimint/fedimint/issues/7258
> [Backport v0.6] chore(consensus): improve debugging of rejected citems

- devimint/src/vars.rs
- fedimintd/Cargo.toml
- fedimintd/src/envs.rs
- fedimintd/src/fedimintd.rs
> cleanup: cleanup telemetry flags for consistency

- README.md
> chore: simplify disclaimer

- fedimint-server-ui/src/assets.rs
- fedimint-server-ui/src/dashboard/mod.rs
- fedimint-server-ui/src/dashboard/modules/lnv2.rs
- fedimint-server-ui/src/dashboard/modules/meta.rs
- fedimint-server-ui/src/lib.rs
- fedimint-server-ui/src/setup.rs
> Route constants for UI

- .github/workflows/ci-nix.yml
Fixes https://github.com/fedimint/fedimint/issues/7277
> fix(ci): identify `beta` suffix as prerelease

- .github/workflows/ci-nix.yml
Closes https://github.com/fedimint/fedimint/issues/7297
> [Backport v0.7] fix(ci): identify `beta` suffix as prerelease

- fedimint-core/src/config.rs
- fedimint-core/src/macros.rs
- fedimint-server/src/config/mod.rs
- modules/fedimint-dummy-common/src/config.rs
- modules/fedimint-dummy-server/src/lib.rs
- modules/fedimint-empty-common/src/config.rs
- modules/fedimint-empty-server/src/lib.rs
- modules/fedimint-ln-common/src/config.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-lnv2-common/src/config.rs
- modules/fedimint-lnv2-server/src/lib.rs
- modules/fedimint-meta-common/src/config.rs
- modules/fedimint-meta-server/src/lib.rs
- modules/fedimint-mint-common/src/config.rs
- modules/fedimint-mint-server/src/lib.rs
- modules/fedimint-mint-server/src/test.rs
- modules/fedimint-unknown-common/src/config.rs
- modules/fedimint-unknown-server/src/lib.rs
- modules/fedimint-wallet-common/src/config.rs
- modules/fedimint-wallet-server/src/lib.rs
> cleanup: remove bitcoin rpc from local config

- .github/workflows/ci-nix.yml
Closes https://github.com/fedimint/fedimint/issues/7296
> [Backport v0.6] fix(ci): identify `beta` suffix as prerelease

- .github/workflows/ci-nix.yml
Closes https://github.com/fedimint/fedimint/issues/7295
> [Backport v0.5] fix(ci): identify `beta` suffix as prerelease

- fedimint-server/src/config/mod.rs
- fedimint-server/src/config/setup.rs
- fedimint-server/src/consensus/engine.rs
- fedimint-server/src/consensus/mod.rs
- fedimint-server/src/envs.rs
- fedimint-server/src/lib.rs
- fedimint-testing/src/federation.rs
- fedimintd/src/envs.rs
- fedimintd/src/fedimintd.rs
> Cleanup Server

- modules/fedimint-wallet-client/src/client_db.rs
- modules/fedimint-wallet-client/src/lib.rs
This should allow downstream clients list and filter all past/current pegins and filter them in whatever way they want.
Re #7279
> chore(wallet-client): `list_peg_in_tweak_idxes`

- Cargo.lock
> chore: upgrade miniscript

- Cargo.lock
> chore: update miniscript

- fedimint-cli/src/lib.rs
- fedimint-core/src/lib.rs
- fedimint-core/src/setup_code.rs
- fedimint-server/src/config/mod.rs
- fedimint-server/src/config/setup.rs
- fedimint-testing-core/src/config.rs
There will come a time when we'll question what's actually in the `PeerSetupCode` and it will be a stressful time such that nobody wants to implement this decoding functionality. Let's get it out of the way. :fork_and_knife: 
```bash
$ fedimint-cli dev decode setup-code fedimint40tamphe08v30ai2nrskjns5hhce3n06e1csio87i1c0jos5pgpa6i5ddbqs6q97fpb23ps6e1cs2oo5hhe43o06g9v30h162c0s5o8g1o00q1801g040ag7kdf8dl15kbtdtta40vq7abo323v3sf36ag1g0log8ijr32c020c2ios3g97cg1ka4o0o0b8e3rpa6n14jbpo6j14jbqe6nlc4386mi9ek3c0ibk1n9d0jo06h1c03o06g1ck5cs1k1ci3r06h1c23o06g1c03o8bg982jf06tg16gah0303c1pdc7bps6gce53rc6gce9rpsmihc0poa6pheg9m0j9o07gac84ppth020301ah1h47n7380eg188001g28aehchevc9u9lsv8nuef8rglf629h0glvuol4kdvnknapasnlk2fourionqq6jt5jfh6os8asfccqtiln268f202egj97k0t7qrrv8f1ok2gp4cg1kat8480606ag0h0olc5js8nidek …
```
> feat(fedimint-cli): add setup code decoding functionality

- fedimint-api-client/src/query.rs
Closes https://github.com/fedimint/fedimint/issues/7352
> [Backport v0.5] fix: fix possible double counting of previous response by the same peer

- modules/fedimint-wallet-client/src/client_db.rs
- modules/fedimint-wallet-client/src/lib.rs
Backport https://github.com/fedimint/fedimint/pull/7282
> [Backport v0.7] chore(wallet-client): `list_pegins`

- modules/fedimint-wallet-client/src/client_db.rs
- modules/fedimint-wallet-client/src/lib.rs
Backport https://github.com/fedimint/fedimint/pull/7282
> [Backport v0.6] chore(wallet-client): `list_pegins`

- .github/workflows/backport.yml
- .github/workflows/ci-nix.yml
- .github/workflows/flakebox-flakehub-publish.yml
- .github/workflows/hourly-run.yml
- .github/workflows/linkcheck.yml
- .github/workflows/validate-dependabot.yaml
> chore(ci): use our own runners for everything

- .github/workflows/ci-nix.yml
* Converts the container publishing workflow from copy-pasta to a matrix-based one (closes #7231)
* Adds container publishing for ARM64 (closes #3006)
* Merges both architectures into one tag
> Add arm64 container build to CI

- devimint/src/devfed.rs
Fixes: https://github.com/fedimint/fedimint/issues/7175
Mining blocks in parallel has always been a problem for us. We have been hitting a racy problem where `open_channel` fails because LND is not synced. We are already waiting for the gateway to be a certain block height and synced to a certain node, but the piece that was missing is that it is possible blocks are mined in parallel. So if blocks from `fed_epoch_generated` are mined after checking `synced_to_chain` in the gateway, it is possible to call `open_channel` when the gateway is not synced.
This PR fixes it by waiting for `fed_epoch_generated` before opening any channels.
> fix: wait for fed epoch before opening channels

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client/Cargo.toml
- fedimint-testing/Cargo.toml
- gateway/cli/Cargo.toml
- gateway/fedimint-lightning/Cargo.toml
- gateway/ln-gateway/Cargo.toml
- modules/fedimint-wallet-client/Cargo.toml
Working towards https://github.com/fedimint/fedimint/issues/7243
> chore: bump version to v0.6.3-beta.1

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client-module/Cargo.toml
- fedimint-testing/Cargo.toml
- gateway/fedimint-gateway-common/Cargo.toml
- gateway/fedimint-gateway-server/Cargo.toml
- gateway/fedimint-lightning/Cargo.toml
- modules/fedimint-gw-client/Cargo.toml
- modules/fedimint-wallet-client/Cargo.toml
Working towards https://github.com/fedimint/fedimint/issues/7369
> chore: bump version to v0.7.1-beta.0

- modules/fedimint-wallet-client/src/lib.rs
fix: #7292 
Exposed methods for peg_in and peg_out in wallet module to used for web-sdk to enable users to pegin and pegout their coins using their web wallets
> feat: Added rpc method for peg_in and peg_out

- .github/workflows/ci-nix.yml
- Cargo.lock
- devimint/Cargo.toml
- fedimint-core/Cargo.toml
- fedimint-server/Cargo.toml
- flake.lock
- flake.nix
- gateway/integration_tests/Cargo.toml
- modules/fedimint-ln-server/Cargo.toml
- modules/fedimint-mint-client/Cargo.toml
- modules/fedimint-wallet-server/Cargo.toml
> chore: re-enable cargo-udeps

- .github/workflows/pr-description-check.yml
> feat(ci): block description-less PRs

- docker/README.md
> chore: mention approximate system specs for running

- .github/workflows/ci-nix.yml
Backport https://github.com/fedimint/fedimint/pull/7395
> [Backport v0.5] fix(ci): cast `IS_PRERELEASE` to bool using `fromJSON`

- .github/workflows/ci-nix.yml
Backport https://github.com/fedimint/fedimint/pull/7395
> [Backport v0.6] fix(ci): cast `IS_PRERELEASE` to bool using `fromJSON`

- .github/workflows/ci-nix.yml
Backport https://github.com/fedimint/fedimint/pull/7395
> [Backport v0.7] fix(ci): cast `IS_PRERELEASE` to bool using `fromJSON`

- modules/fedimint-wallet-client/src/lib.rs
> fix(wallet-client): redundant notification

- flake.nix
We did some tests at Fedi, and in a lot of circumstances this only slows things down, sometimes it introduces issues, and seems generally not worth it.
> chore: disable sccache

- devimint/src/external.rs
- fedimint-testing/src/btc/real.rs
`Stdio::piped` can only handle outputs smaller than a pipe buffer size which is 64K on Linux, but only 16K on MacOS.
This is something to remember. We should not be mining that many blocks anyway, it's quite compute costly and slow.
> fix(devimint): split mining a lot of blocks into smaller batches

- devimint/src/tests.rs
Flaky under load.
AFAICT it's racy, so need retries.
> fix(tests): retry checking initial announcements

- Cargo.lock
- fedimint-server-core/Cargo.toml
- fedimint-server-core/src/bitcoin_rpc.rs
When debugging would be great to know if it started and what interval, just in case.
> chore: log some info about bitcoin rpc monitor

- fedimint-cli/Cargo.toml
- fedimint-cli/src/main.rs
- fedimint-rocksdb/Cargo.toml
- fedimintd/Cargo.toml
- fedimintd/src/bin/main.rs
- gateway/fedimint-gateway-server/Cargo.toml
- gateway/fedimint-gateway-server/src/bin/gatewayd.rs
android wants 16KB size and jemalloc doesn't support
ref https://android-developers.googleblog.com/2025/05/prepare-play-apps-for-devices-with-16kb-page-size.html
> chore: disable jemalloc on android

- fedimint-cli/Cargo.toml
- fedimint-cli/src/main.rs
- fedimint-rocksdb/Cargo.toml
- fedimintd/Cargo.toml
- fedimintd/src/bin/main.rs
- gateway/fedimint-gateway-server/Cargo.toml
- gateway/fedimint-gateway-server/src/bin/gatewayd.rs
android wants 16KB size and jemalloc doesn't support
fixes https://github.com/fedimint/fedimint/issues/7421
> backport: chore: disable jemalloc on android

- devimint/src/devfed.rs
> fix(devimint): improve logging on registering ldk

- devimint/src/federation/config.rs
- devimint/src/gatewayd.rs
- fedimint-core/src/lib.rs
- fedimintd/src/fedimintd.rs
- fedimintd/src/lib.rs
- gateway/fedimint-gateway-server/src/lib.rs
- gateway/fedimint-lightning/src/ldk.rs
- gateway/fedimint-lightning/src/ldk/tests.rs
- gateway/integration_tests/src/main.rs
Backport of https://github.com/fedimint/fedimint/pull/7439
> [backport v0.7] fix: LDK Gateway cannot connect to esplora instance on mutinynet

- modules/fedimint-wallet-client/src/lib.rs
> fix: unnecessary `Result` in `list_peg_in_tweak_idxes`

- fedimint-recurringd/README.md
There was lack of clarity around what the bearer token is even for, which made me remember that I forgot to document how to add federations to `recurringd`.
> chore: add recurringd instructions to add federations

- .config/semgrep.yaml
- modules/fedimint-ln-client/src/recurring/mod.rs
Backport of #7450 to `releases/v0.7`.
> [Backport releases/v0.7] chore(ln-client): improve recurring payment claim logging

- fedimint-server/src/config/setup.rs
> fix(setup): make `set_local_parameters` idempotent

- fedimint-server/src/config/setup.rs
Backport of #7445 to `releases/v0.7`.
> [Backport releases/v0.7] fix(setup): make `set_local_parameters` idempotent

- Cargo.lock
- Cargo.toml
- fedimint-recurringd-tests/Cargo.toml
- fedimint-recurringd-tests/src/bin/fedimint-recurringd-tests.rs
- fedimint-recurringd/Cargo.toml
- fedimint-recurringd/src/main.rs
I messed up and forgot to actually check auth for the one authenticated API endpoint in `recurringd` :/ thx for the retroactive review @douglaz. There's not a huge risk here, since a) ~nobody is running it yet and b) it's at most a DoS issue.
> fix(recurringd): actually check admin auth

- docker/deploy-fedimintd/deploy.sh
Also, need to open the p2p and api (for future Iroh) ports.
> chore(docker): actually enable firewall

- docker/deploy-fedimintd/deploy.sh
Backport of #7458 to `releases/v0.7`.
> [Backport releases/v0.7] chore(docker): actually enable firewall

- Cargo.lock
- Cargo.toml
- fedimint-cli/Cargo.toml
- fedimint-client-module/Cargo.toml
- fedimint-testing/Cargo.toml
- gateway/fedimint-gateway-common/Cargo.toml
- gateway/fedimint-gateway-server/Cargo.toml
- gateway/fedimint-lightning/Cargo.toml
- modules/fedimint-gw-client/Cargo.toml
- modules/fedimint-wallet-client/Cargo.toml
Working towards https://github.com/fedimint/fedimint/issues/7441
> chore: bump version to v0.7.2-rc.0

- Cargo.lock
- Cargo.toml
The original problem was fixed, no need to pin it anymore.
> chore: update `fs-lock`

- docker/README.md
Closes https://github.com/fedimint/fedimint/issues/7252
> docs: update docker README to reference release branch

- devimint/src/tests.rs
- fedimint-client-module/src/lib.rs
- fedimint-client-module/src/module/init/recovery.rs
- fedimint-client-module/src/module/mod.rs
- fedimint-core/src/core.rs
- fedimint-core/src/db/mem_impl.rs
- fedimint-core/src/db/mod.rs
- fedimint-core/src/encoding/btc.rs
- fedimint-core/src/fmt_utils.rs
- fedimint-core/src/module/version.rs
- fedimint-core/src/util/mod.rs
- fedimint-load-test-tool/src/main.rs
- fedimint-rocksdb/src/lib.rs
- fedimint-server/src/config/dkg.rs
- fedimint-server/src/consensus/api.rs
- fedimint-server/src/consensus/debug.rs
- fedimint-server/src/consensus/transaction.rs
- flake.lock
- gateway/fedimint-gateway-server/src/lib.rs
- modules/fedimint-ln-common/src/lib.rs
- modules/fedimint-ln-server/src/lib.rs
- modules/fedimint-lnv2-client/src/lib.rs
- modules/fedimint-meta-common/src/lib.rs
- modules/fedimint-mint-client/src/backup/recovery.rs
- modules/fedimint-wallet-common/src/txoproof.rs
- modules/fedimint-wallet-server/src/lib.rs
> chore: nix flake update

- fedimint-client/src/client.rs
- fedimint-client/src/db.rs
Added Pagination in list_operation method and added get_operation method to get specific transaction with the operation_id
> chore: enabled pagination in list_operations and added get_operation

- modules/fedimint-ln-client/src/lib.rs
- modules/fedimint-wallet-client/src/lib.rs
- Exposed subscribe_deposit in wallet and subscribe_internal_pay in ln module
> chore: exposed subscribe_deposit in wallet and subscribe_internal_pay in ln

- fedimint-cli/src/lib.rs
- fedimint-client-wasm/src/lib.rs
- fedimint-client/src/client/builder.rs
- fedimint-load-test-tool/src/common.rs
- fedimint-recurringd/src/lib.rs
- fedimint-testing/src/federation.rs
- fedimint-wasm-tests/src/lib.rs
- gateway/fedimint-gateway-server/src/client.rs
> chore: keep the double-derive secret as a standard

- devimint/src/version_constants.rs
- modules/fedimint-wallet-client/src/client_db.rs
- modules/fedimint-wallet-client/src/lib.rs
- modules/fedimint-wallet-client/src/pegin_monitor.rs
- modules/fedimint-wallet-tests/src/bin/wallet-module-tests.rs
- modules/fedimint-wallet-tests/tests/tests.rs
Backport of #7505 to `releases/v0.7`.
> [Backport releases/v0.7] fix(wallet-client): don't claim on-chain deposits smaller than the fee

- Cargo.lock
- Cargo.toml
- fedimint-api-client/Cargo.toml
- fedimint-api-client/src/api/iroh.rs
- fedimint-core/Cargo.toml
- nix/flakebox.nix
Wrapping up https://github.com/fedimint/fedimint/pull/7309 with actually two different Iroh versions.
> feat: dual stack api client 

- fedimint-client/src/meta.rs
we had this as ext trait in fedi for while
> chore: expose meta service all entries function

- Cargo.toml
fixes https://github.com/fedimint/fedimint/issues/7531
> chore: pin iroh version

- fedimint-api-client/src/api/iroh.rs
JoinSet is not compat with WASM, and in this particular case `FuturesUnordered` is just fine.
Fix #7532
> fix: use `FuturesUnordered` instead of `JoinSet`

- Cargo.lock
- Cargo.toml
- fedimint-api-client/src/api/iroh.rs
As described in:
https://www.iroh.computer/blog/iroh-0-90-the-canary-series
> chore: update iroh-next to newest 'canary'

- Cargo.lock
- Cargo.toml
- fedimint-api-client/Cargo.toml
- fedimint-api-client/src/api/iroh.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-core/src/envs.rs
- fedimint-core/src/iroh_prod.rs
- fedimint-core/src/lib.rs
- fedimint-server-bitcoin-rpc/src/bitcoind.rs
- fedimint-server-bitcoin-rpc/src/esplora.rs
- fedimint-server-bitcoin-rpc/src/lib.rs
- fedimint-server/Cargo.toml
- fedimint-server/src/net/p2p_connector.rs
- fedimintd/src/lib.rs
- flake.nix
- nix/modules/fedimintd.nix
I have attempted to deploy bitcoin backend with a fallback #7523  to our testing deployments, and I've noticed multiple issues along the way.
>  chore: fixes and debugging deploying latest master to our demo iroh instance

- fedimint-api-client/src/api/iroh.rs
- fedimint-core/src/iroh_prod.rs
- fedimint-server/src/net/p2p_connector.rs
Follow-up to https://github.com/fedimint/fedimint/pull/7540#event-18420680493 adding the US Fedimint Iroh infra to our defaults.
> chore: add US iroh infra to defaults

- fedimint-api-client/src/api/iroh.rs
- fedimint-core/src/iroh_prod.rs
- fedimint-server/src/net/p2p_connector.rs
Backport of #7567 to `releases/v0.8`.
> [Backport releases/v0.8] chore: add US iroh infra to defaults

- Cargo.lock
- Cargo.toml
Working towards https://github.com/fedimint/fedimint/issues/7560
> chore: bump version to v0.8.0-beta.2

- Cargo.lock
- Cargo.toml
Working towards https://github.com/fedimint/fedimint/issues/7560
> chore: bump version to v0.8.0-beta.3

- Cargo.lock
- Cargo.toml
Working towards https://github.com/fedimint/fedimint/issues/7560
> chore: bump version to v0.8.0-beta.4

- devimint/src/tests.rs
- scripts/tests/test-ci-all.sh
- scripts/tests/test-offline-client-initialization.sh
> chore: test to verify offline client initialization

- Cargo.lock
- devimint/Cargo.toml
- devimint/src/tests.rs
- devimint/src/version_constants.rs
- fedimint-client/src/client.rs
- fedimint-client/src/client/builder.rs
- fedimint-client/src/db.rs
- fedimint-core/src/encoding/mod.rs
- fedimint-server/src/config/mod.rs
- scripts/tests/test-ci-all.sh
- scripts/tests/test-client-config-change-detection.sh
> feat(client): fetch and switch to new client config

- fedimint-core/src/db/mod.rs
- fedimint-recurringd/src/lib.rs
Backport of #7653 to `releases/v0.8`.
> [Backport releases/v0.8] fix(recurringd): avoid "holes" in invoice indices getting sync stuck

- flake.lock
- flake.nix
Eg.
https://github.com/fedimint/fedimint/actions/runs/17103031471/job/48504522347
> fix: building bundled packages fails

- Cargo.lock
- fedimint-client-rpc/Cargo.toml
- fedimint-client-rpc/src/lib.rs
- fedimint-client/src/client.rs
- fedimint-client/src/client/builder.rs
Backup and recovery for fedimint-client-rpc
> feat: add backup and recovery for client-rpc

- Cargo.lock
- Cargo.toml
To the last version using the same sqlite version as current lnd.
> chore: update arti-client

- nix/modules/fedimintd.nix
We forgot to adapt the nix module when releasing 0.8, this fixes all the things I found to be broken.
> Fix `fedimintd` nix module

- fedimint-recurringd/src/db.rs
- fedimint-recurringd/src/lib.rs
We already prevented the bug from reoccurring in #7653, this commit adds a DB migration to get the DB entries of already affected users into a correct state again.
> fix(recurringd): fix LNURLs of users affected by #7650

- fedimint-recurringd/src/db.rs
- fedimint-recurringd/src/lib.rs
Backport of #7671 to `releases/v0.8`.
> [Backport releases/v0.8] fix(recurringd): fix LNURLs of users affected by #7650

- fedimint-api-client/src/api/global_api/with_cache.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-core/src/admin_client.rs
- fedimint-server-core/src/dashboard_ui.rs
- fedimint-server-core/src/net.rs
- fedimint-server-ui/src/auth.rs
- fedimint-server-ui/src/dashboard/mod.rs
- fedimint-server-ui/src/lib.rs
- fedimint-server/src/consensus/api.rs
Closes https://github.com/fedimint/fedimint/issues/7622
Verified backup/restore with `guardian-backup.tar` using 3/4 federation.
> feat: add guardian config backup download section

- fedimint-api-client/src/api/global_api/with_cache.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-core/src/admin_client.rs
- fedimint-server-core/src/dashboard_ui.rs
- fedimint-server-core/src/net.rs
- fedimint-server-ui/src/auth.rs
- fedimint-server-ui/src/dashboard/mod.rs
- fedimint-server-ui/src/lib.rs
- fedimint-server/src/consensus/api.rs
Backport of #7691 to `releases/v0.8`.
> [Backport releases/v0.8] feat: add guardian config backup download section

- modules/fedimint-wallet-client/src/lib.rs
Added subscribe_withdraw method in wallet module rpc
> feat: Added subscribe_withdraw in rpc

- fedimint-api-client/src/api/mod.rs
Without the API endpoint and payload it's hard to debug these.
> chore(api-client): add span for debugging `Unusual peer error`

- fedimint-bitcoind/src/lib.rs
fix: #5537 
Added pagination to get_script_history to fetch complete script transaction history instead of only the first page.
> feat: Added pagination to esplora get_script_history

- .gitignore
- fedimint-startos/Dockerfile
- fedimint-startos/Makefile
- fedimint-startos/check-web.sh
- fedimint-startos/docker_entrypoint.sh
- fedimint-startos/instructions.md
- fedimint-startos/manifest.yaml
- fedimint-startos/scripts/deps.ts
- fedimint-startos/scripts/embassy.ts
- fedimint-startos/scripts/procedures/getConfig.ts
- fedimint-startos/scripts/procedures/setConfig.ts
Backport of #7612 to `releases/v0.8`.
> [Backport releases/v0.8] feat: update startos package to connect to bitcoind on mainnet

- docs/deploying.md
Just an OCD-driven follow-up to #7708 :laughing:
> chore: added some formatting to setup steps list

- gateway/fedimint-lightning/src/ldk.rs
Fixes: https://github.com/fedimint/fedimint/issues/7694
LDK gateway has a silly bug where it will poll 10 times for the open channel, then give up. There's no reason to do this, we can instead wait for the `ChannelPending` event and return the `funding_txid` from that event.
> fix: LDK does not poll for open channels

- fedimint-wasm-tests/src/lib.rs
Just give this test a bit more funds on start.
Fix #7733
> fix: flaky wasm test

- fedimint-server-ui/src/setup.rs
We had report of minor confusion during setup, so went over it and improved some wording.
On top of it, I added auto-redirect after setup is complete, as it was another rough edge that seems simple to fix.
Test with `just devimint-env-pre-dkg`.
Bikesheding very much welcome.
> chore(ui): adjust wording, add auto-redirect after setup

- fedimint-load-test-tool/src/common.rs
Trying to fix [failing load tests](https://github.com/fedimint/fedimint/pull/7752#issuecomment-3315105372), my suspicion is that sometimes funds are still in flight and thus the wallet is temporarily underfunded. Retrying may help in that case.
> fix: try to fix load test flakiness

- fedimint-api-client/src/api/iroh.rs
- fedimint-core/src/iroh_prod.rs
- fedimint-server/src/net/p2p_connector.rs
While reading the code, I renamed some constants.
Happy to bikeshed.
> chore: iroh api endpoint minor improvements

- gateway/fedimint-gateway-server/src/config.rs
- gateway/fedimint-gateway-server/src/envs.rs
- gateway/fedimint-gateway-server/src/lib.rs
- modules/fedimint-lnv2-common/src/gateway_api.rs
Fixes #7790
(cherry picked from commit f3361aa43f6677532d9292ca0848880b6ac0c873)
> feat: customize default gateway fees

- Cargo.lock
- Cargo.toml
Working towards https://github.com/fedimint/fedimint/issues/7782
> chore: bump version to v0.8.2-rc.0

- fedimint-api-client/src/api/global_api/with_cache.rs
- fedimint-api-client/src/api/global_api/with_request_hook.rs
- fedimint-api-client/src/api/iroh.rs
- fedimint-api-client/src/api/mod.rs
- fedimint-api-client/src/api/net.rs
- fedimint-api-client/src/lib.rs
- fedimint-client-module/src/api.rs
- fedimint-client-rpc/src/lib.rs
- fedimint-client/src/client/builder.rs
- fedimint-load-test-tool/src/main.rs
One commit in https://github.com/fedimint/fedimint/pull/7785 was reported to lead to conectivity issues, and I think I'll take some and investigate it more properly.
In the meantime we can land the other changes. I had to redo [initialize iroh stable vs next in parallel](https://github.com/fedimint/fedimint/commit/85366c9c3d61b439759d67dd76615f07cedf2439) as it was very much conflicted with the commit that seems to have problems.
> chore: optimize join time when Iroh is used (pt 1)

- Cargo.lock
Still an old version, but maybe there could be some bugfixes we want.
> chore: update pkarr dependency

- fedimint-client/src/client/builder.rs
- fedimint-client/src/client/handle.rs
This extracts only a single change from #7806 , because the other one seems to be triggering bugs that are will take time to debug.
> chore(client): prefetch api address annonuncements during preview

- fedimint-client/src/client.rs
If we already had a response and we are not planning to retry, we can increment the "number of responses".
I don't think this had any negative user-visible consequences, as client is not blocked on this counter anyway, but seems technically incorrect.
Also, in case of a random connectivity problem, 15s retry time is not OK during joining, when we are waiting for it to wrap it up.
> fix: improve `refresh_peers_api_versions`

- fedimint-client/src/client/builder.rs
- fedimint-client/src/client/handle.rs
Backport of #7807 to `releases/v0.9`.
> [Backport releases/v0.9] chore(client): prefetch api address annonuncements during preview

- fedimint-client/src/client.rs
Backport of #7809 to `releases/v0.9`.
> [Backport releases/v0.9] fix: improve `refresh_peers_api_versions`
