fedimint/fedimint

gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, modules/fedimint-ln-common/src/gateway_endpoint_constants.rs
Fixes:
1. https://github.com/fedimint/fedimint/pull/4819 broke backwards compatibility since it changed the gateway's endpoint from `leave-fed` to `leave_fed`. We don't have tests to catch this. Adding in https://github.com/fedimint/fedimint/pull/5231
2. New endpoints for liquidity management didn't use constants.
=> fix: fix gateway endpoints

fedimint-core/src/module/mod.rs, fedimint-server/src/consensus/server.rs, fedimint-server/src/net/api.rs
=> chore: better tx submissin handling logging

scripts/dev/run-test/fm-run-test
Otherwise we get no output on timeouts.
=> fix(ci): timeout tests before parallel job times out

.config/nextest.toml, scripts/dev/run-test/fm-run-test, scripts/tests/test-ci-all.sh
Will rebase after #5176 lands
This is to prevent silent regressions.
I wish we could go lower. Most devimint-based tests are already below 40s, and unit-test like tests should be OK under 20s, IMO.
We'll get there.
=> chore: put tighther deadlines on test runtime

.github/workflows/ci-nix.yml
Now that we are using self-hosted runner that has everything locally there's less reason to use it, and it looks like MacOS + cachix got stuck on something because of it again.
=> chore: remove nix-fast-build

utils/portalloc/src/lib.rs
10m is more than we allow our tests to run altogether, and as soon as a port is used, it no longer really needs to be reserved anyway.
=> chore(port-alloc): lower port allocation time

fedimint-core/src/db/mod.rs, fedimint-rocksdb/src/lib.rs
Fix https://github.com/fedimint/fedimint/issues/5271
Fix https://github.com/fedimint/fedimint/issues/5195
=> fix: snapshot level isolation violations 

fedimint-logging/Cargo.toml, fedimint-logging/src/lib.rs, fedimintd/Cargo.toml, fedimintd/src/fedimintd.rs
New rustc flagged a non-existant `cfg = feature` and it seems we had it generally messed-up.
=> fix: opentelementry handling broken

.github/workflows/ci-nix.yml
It's hard to debug nix builds when the output is truncated to the last few lines.
=> fix(ci): missing `-L` in `nix build`s

devimint/src/cli.rs, devimint/src/devfed.rs, devimint/src/federation.rs, devimint/src/lib.rs
We can just kill everything in parallel.
Requires manually calling a dropping function because of `fn drop` taking `&mut self`, and not `self`, but on the happy path (which matters in the CI), it is not a big deal.
`j devimint-env`, press `ctrl+D` and see how much faster it is.
Or `env RUST_LOG=fm=debug ./scripts/tests/meta-module-test.sh` and see termination going very fast.
=> chore(devimint): significantly improve shutdown time

fedimint-server/src/consensus/engine.rs, fedimint-server/src/consensus/mod.rs, fedimint-server/src/consensus/transaction.rs, fedimint-server/src/lib.rs, fedimint-server/src/net/api.rs, fedimint-testing/src/federation.rs
=> Refactor server

fedimintd/src/fedimintd.rs
Because it prints it before logging is initialized.
=> fix(fedimintd): doesn't print version on start

fedimint-core/src/runtime.rs
It's just annoying, and they are conceptually top level things.
=> chore: task spawns should not inherit existing spans

fedimint-core/src/task/jit.rs
Leading to panics on shutdown sometimes.
=> fix(jit-values): they can actually get canceled

Cargo.lock, Cargo.toml, fedimint-testing/src/gateway.rs, gateway/integration_tests/Cargo.toml, gateway/integration_tests/src/main.rs, gateway/ln-gateway/tests/integration_tests.rs, scripts/tests/gateway-module-test.sh, scripts/tests/test-ci-all.sh
Builds on https://github.com/fedimint/fedimint/pull/5233
Part of https://github.com/fedimint/fedimint/issues/5168
Removes two tests from `integration_tests.rs` in the gateway and re-writes them as devimint tests. LND and CLN can be run in parallel. More functionality will be added to these tests over time (to amortize the cost of setting up a all of the daemons).
=> test: basic gateway devimint config test

fedimint-core/src/bitcoin_migration.rs, fedimint-core/src/config.rs, fedimint-core/src/core.rs, fedimint-core/src/core/server.rs, fedimint-core/src/db/mem_impl.rs, fedimint-core/src/db/mod.rs, fedimint-core/src/db/notifications.rs, fedimint-core/src/encoding/mod.rs, fedimint-core/src/encoding/secp256k1.rs, fedimint-core/src/encoding/threshold_crypto.rs, fedimint-core/src/fmt_utils.rs, fedimint-core/src/lib.rs, fedimint-core/src/module/mod.rs, fedimint-core/src/module/registry.rs, fedimint-core/src/module/version.rs, fedimint-core/src/net/peers/fake.rs, fedimint-core/src/runtime.rs, fedimint-core/src/session_outcome.rs, fedimint-core/src/task.rs, fedimint-core/src/tiered_multi.rs, fedimint-core/src/timing.rs, fedimint-core/src/transaction.rs, fedimint-core/src/util/mod.rs, fedimint-server/src/consensus/transaction.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, modules/fedimint-lnv2-client/src/lib.rs
I temporarily enabled clippy pedantic rules and fixed the issues it caught (except the ones that sacrifice code readability)
=> chore: cleanup fedimint-core code

devimint/src/cfg/bitcoin.conf, devimint/src/external.rs, fedimint-bitcoind/src/bitcoincore.rs, fedimint-bitcoind/src/electrum.rs, fedimint-bitcoind/src/esplora.rs, fedimint-bitcoind/src/lib.rs, fedimint-testing/src/btc/mock.rs, fedimint-testing/src/btc/mod.rs, fedimint-testing/src/btc/real.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
Fixes https://github.com/fedimint/fedimint/issues/5298
Peers using bitcoind without txindex will not recognize change outputs. This PR introduces `is_tx_in_block` to `IBitcoindRpc`, which uses [`getblock`](https://developer.bitcoin.org/reference/rpc/getblock.html) for bitcoind that doesn't require txindex.
For pruned nodes, calls to `getblock` will return an error if the block data has been pruned (see: https://github.com/bitcoin/bitcoin/blob/v0.11.0/doc/release-notes.md#block-file-pruning). The minimum allowed for pruned nodes is 550MB, which is ~2 days/288 blocks assuming average block size ~1.9MB. If a peer attempts to sync blocks that have been pruned while there are outstanding pending transactions, the underlying call to `getblock` will fail.
---
This change will prevent further …
=> fix: recognize change outputs for bitcoind backends without txindex

.github/workflows/ci-backwards-compatibility.yml, .github/workflows/ci-nix.yml
I temporarily deployed a NGINX config that accepts both the old and the new domain, so we can merge this independently @dpc.
=> chore: use fedimint.org perfit domain

devimint/src/tests.rs, fedimint-cli/src/client.rs, fedimint-client/src/module/mod.rs, fedimint-client/src/sm/executor.rs, fedimint-client/src/sm/notifier.rs, fedimint-core/src/core.rs, gateway/ln-gateway/src/state_machine/mod.rs, modules/fedimint-ln-client/src/cli.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-client/src/withdraw.rs
`operation_id` is soo common and soo long in client side logging that it's just annoying.
Shorten it to `abcdefgh..abcdefgh` version.
To prevent unintentional mistakes, remove `Display` from `OperationId` and require going through `fmt_short` or `fmt_full` to declare intention.
Fix all the call-sites.
Before:
After:
=> chore: print shortened version of OperationId when logging

devimint/src/cfg/bitcoin.conf, devimint/src/external.rs, devimint/src/version_constants.rs, fedimint-bitcoind/src/bitcoincore.rs, fedimint-bitcoind/src/electrum.rs, fedimint-bitcoind/src/esplora.rs, fedimint-bitcoind/src/lib.rs, fedimint-testing/src/btc/mock.rs, fedimint-testing/src/btc/mod.rs, fedimint-testing/src/btc/real.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
Fixes https://github.com/fedimint/fedimint/issues/5344
Note that I changed the version check from < 0.4.0-alpha to < v0.3.2 and we're currently on v0.3.1-rc.1 for this branch. This means we're still running the test suite with txindex enabled.
=> [Backport releases/v0.3] chore: disable txindex for bitcoind backends in tests

docs/gateway.md, fedimint-testing/src/ln.rs, gateway/cli/src/main.rs, gateway/ln-gateway/build.rs, gateway/ln-gateway/proto/gateway_lnrpc.proto, gateway/ln-gateway/src/bin/cln_extension.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/cln.rs, gateway/ln-gateway/src/lightning/lnd.rs, gateway/ln-gateway/src/lightning/mod.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, modules/fedimint-ln-common/src/gateway_endpoint_constants.rs
This will be an important command to have once we ship an LDK-powered gateway since the liquidity API will be the only way to manage channels
~~Only implementing for LND for now since LND and LDK support closing channels by funding TXID + output index, while CLN instead requires funding tx block height + transaction index + output index~~
Changed from closing by TXID + output index to closing all channels with a specific peer
=> feat: add close_channels_with_peer command to gateway liquidity API

fedimint-core/src/net/mod.rs, fedimint-core/src/util/mod.rs, fedimint-server/src/net/peers.rs
Explicitly specifying port in p2p url should not be neccessary (just a room for mistakes).
Also - `SafeUrl` should reject any URLs for which we don't know which port to use as early as possible, to limit room for mistakes.
=> chore: port in url handling improvements

scripts/ops/add_meta_module.sh
Federations deployed prior to 0.3.0 do not have the meta module in their config, meaning it doesn't get deactivated even though >=0.3.0 fedimintds support it. We currently don't support adding modules after the fact, but in case of the meta module we can kinda hack it in since it doesn't need any config, which is what the added script does.
=> feat: add expert-user script for activating the meta module

flake.nix, justfile.fedimint.just
Currently not enforcing or modifing anything, as would be best to find a convenient time to minimize amount of merge conflicts.
After we get it in, we can run it, land the sorting PR, and then I'll add a check in the lint step or maybe right in the git check hook.
=> chore: introduce `cargo-sort` into our lives

.github/workflows/ci-fuzz.yml, flake.nix, justfile.fedimint.just
Now that we self-hosted runners, that we don't pay for cycles used, it makes sense to run some fuzzing all the time, just to avoid accidental breakages and maybe even randomly discover something over time.
It will be running with the same `runLowPrio` we use for other CPU-heavy things, so it should not cause tests running in parallel to be affected too much.
Re #287
=> chore(ci): run a round of fuzzing for every fuzz target

modules/fedimint-mint-client/src/lib.rs
For decode we're handling both cases but for encode we're writing stand b64, should write as url safe
=> fix: base64 url safe for display

devimint/src/federation.rs, devimint/src/vars.rs, fedimint-server/src/config/api.rs, fedimint-server/src/consensus/api.rs, fedimint-server/src/consensus/mod.rs, fedimint-server/src/lib.rs, fedimint-server/src/net/api.rs, fedimint-server/src/net/api/http_auth.rs, fedimint-testing/src/federation.rs, fedimintd/src/envs.rs, fedimintd/src/fedimintd.rs
Re #5366
In the future we might want to let guardians manage Api secrets of a Federation via UI, storing the Api Secrets configuration in the database.
This will make env var naming confusing, just like it was in the case of a `FM_BITCOIN_RPC_URL`, etc. which we've split into `FM_FORCE_` and `FM_DEFAULT_` recently.
Do the same split for `FM_FORCE_API_SECRETS`, so the meaning and behavior of it does not need to change in the future.
While at it merge existing two arguments into one, to avoid 2 * 2 env vars/flags, and unify everything in a newtype.
```
env RUST_LOG=fm=debug j devimint-env
```
Verify in the logs of fedimintd that it says near the top:
```
2024-05-24T21:50:36.733769Z  INFO spawn{task="main"}: fm::net::auth: Api available for public access
```
Then run:
```
env …
```
=> chore: future-proof api secrets in private federations

devimint/src/external.rs, gateway/ln-gateway/src/bin/cln_extension.rs
I audited the code for [`open_channel()`](https://github.com/fedimint/fedimint/blob/5bd3555a5bf445def3f44f8b1a9049299e7f956b/devimint/src/external.rs#L552) to ensure that [`open_channel_between_gateways()`](https://github.com/fedimint/fedimint/blob/5bd3555a5bf445def3f44f8b1a9049299e7f956b/devimint/src/external.rs#L654) matches it 1-to-1. I then re-enabled `open_channel_between_gateways()` for devimint (which was disabled [here](https://github.com/fedimint/fedimint/pull/5149) due to being slow and flaky). I measured the startup time for `just mprocs` 10+ times on my local machine before and after the change and with the changes in this PR it never failed and the time difference was within margin of error.
=> chore: reenable devimint gateway liquidity channel opening

docs/dev-env.md
The existing link was broken here: https://github.com/NixOS/nixos-homepage/pull/1446
It used to redirect to `https://nix.dev/manual/nix/stable/command-ref/conf-file.html#conf-trusted-users` but now redirects to `https://nix.dev/manual/nix/stable/stable/command-ref/conf-file.html#conf-trusted-users` (`stable/stable` instead of just `stable`). This PR simply updates the link to where the old link used to redirect to.
=> fix: fix broken nix link

docker/0.3.0/fedimintd-mainnet-tls/.env, docker/0.3.0/fedimintd-mainnet-tls/docker-compose.yaml, docker/0.3.0/fedimintd-mainnet-tls/meta.json
Addressing my own comment https://github.com/fedimint/fedimint/pull/4872#pullrequestreview-1989401146. FYI @Kodylow @TonyGiorgio to avoid duplicate work.
=> feat: minimal mainnet fedimintd docker setup

fedimint-client/src/lib.rs, fedimint-core/src/config.rs, fedimint-core/src/endpoint_constants.rs, fedimint-derive/src/lib.rs, fedimint-server/src/config/mod.rs, fedimint-server/src/consensus/api.rs
I split this PR into three commits:
1. Remove old, redundant `consensus_json` config field we drag around in the server config. This is a breaking change because that also requires removing a public API endpoint returning the JSON-encoded server consensus config. 
2. Add new API endpoint that returns the JSON-encoded client config, which is mostly identical to the server consensus config, just has a slightly different structure.
3. Lastly I noticed that this was the only use of the `#[encodable_ignore]` annotation, which can now be removed, simplifying our derive macros a bit (it always felt like a hack anyway).
Since the only consumer I'm aware of is the Admin UI I'd propose to merge the two commits together. If there is strong opposition we could also just add the new API and remove the …
=> Remove json consensus config from server config only kept around for a UI

devimint/src/tests.rs, recoverytool/src/main.rs
Fixes https://github.com/fedimint/fedimint/issues/5388
- Updates devimint recoverytool test to process multiple withdrawals in single session, which reveals the underlying issue with the epochs method
- Updates the change tweak index for each withdrawal, instead of only once per session outcome
=> fix: recognize multiple peg-out tweaks in single session

fedimint-core/src/core/server.rs, fedimint-server/src/consensus/api.rs, fedimint-server/src/consensus/engine.rs, fedimint-server/src/consensus/transaction.rs
When working #5384 , which probably will get abandoned I needed/noticed some ways to avoid a clone and passed by reference stuff that didn't need to be moved.
The `&mut self` is not neccessary, but technically it does denote that the consensus code has an exclusive reference to `ConsensusEngine` which makese sense.
=> refactor(consensus): some pass-by-ref tweaks

Cargo.lock, Cargo.toml, fedimint-core/Cargo.toml, fuzz/Cargo.toml
Replaces #5403
Bump `serde` from v1.0.202 to v1.0.203
Bump `backtrace` from v0.3.71 to v0.3.72
Bump `proc-macro2` from v1.0.83 to v1.0.84
=> chore(deps): bump the patch group with 3 updates

fedimint-core/src/config.rs, fedimint-core/src/core.rs, fedimint-core/src/db/mod.rs, fedimint-core/src/encoding/bls12_381.rs, fedimint-core/src/lib.rs, fedimint-core/src/module/mod.rs, fedimint-core/src/task/jit.rs, fedimint-core/src/tiered.rs, fedimint-core/src/tiered_multi.rs, fedimint-core/src/util/mod.rs
Enforce most clippy nursery rules in fedimint-core. I disabled a few that seemed annoying. One rule that I'm on the fence about (that's currently enabled in this PR) is [missing_const_for_fn](https://rust-lang.github.io/rust-clippy/master/index.html#/missing_const_for_fn) since removing `const` from a function later would break API compatibility. Lmk if anyone has thoughts on that. If people like the restrictions in this PR, I'll do a sweep across the rest of the rust codebase and enable it everywhere.
=> chore: enforce clippy nursery rules in fedimint-core

modules/fedimint-mint-client/src/lib.rs
Sometimes I need to copy&paste notes between terminals, logs, etc. and it is just a QoL if it could not complain about some random newline or space in there.
=> feat: accept whitespaces in oob notes str

Cargo.lock, fedimint-server/Cargo.toml, fedimint-server/src/config/mod.rs, fedimint-server/src/consensus/aleph_bft/data_provider.rs, fedimint-server/src/consensus/aleph_bft/finalization_handler.rs, fedimint-server/src/consensus/engine.rs
This change requires a coordinated shutdown of all guardians at the end of a session such that all of them can restart with the 0.4.0 binary.
With the new defaults the maximum RAM consumption of a peers aleph bft instance is 230mb per peer in case of an attack while it is at most 180mb per peer under the assumption that all peers are correct. In a 3/4 federation we would have 920mb and 720mb respectively.
The new minimum session time will be less variable with a minimum of 3 minutes, and will not increase when a peer goes offline.
This is the last change to core consensus I have planned.
=> feat: reduce RAM usage by factor of three, simplify switching trigger logic

fedimint-server/src/consensus/debug.rs, fedimint-server/src/consensus/engine.rs
Follow-up to https://github.com/fedimint/fedimint/pull/5386/files#r1619463731
The goal here is to be able to do binary search using logs of peer nodes that have a mismatch and find the element(s) that are mismatched and at very least known which modules might have been involved, before attempting a full scale debugging with dbtool etc.
That's why the index and short-hash are printed first, and then it's some compact general info about txid, modules and/or total length.
If I'm reading it right, there is no guarantee that any peer with a majority-correct checksum/signature will notice invalid signature of another peer, but over 3 peers, the chance is high, and it's better than nothing.
Looks like this:
=> chore: dump citems dump on consensus mismatch

fedimint-api-client/src/api.rs, fedimint-api-client/src/query.rs, fedimint-client/src/lib.rs, fedimint-core/src/invite_code.rs, fedimint-core/src/lib.rs, fedimint-server/src/config/distributedgen.rs, fedimint-server/src/config/mod.rs, gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs, modules/fedimint-meta-server/src/lib.rs
It always bothered me that we have e.g. `peer_urls: BTreeMap<PeerId, String>` and we can write code like:
```
peer_urls.max_evil();
```
and while reading code like that I couldn't help but to think, "how do we go from a map to some consensus security calculations like that ...".
So at some point I added the `struct NumPeers` which is supposed to be an explicit newtype that carries the meaning of "how many peers we have", which seems like a decent place for methods like `max_evil` and `threshold`.
I recently attempted to remove the `NumPeersExt` where the methods like `max_evil` are implemented for collections, but it turned out that this was too much of a inconvenience. It is nice to be able to smoothly go from the data that carries number of peers implicitly (like a map of peer urls) to …
=> refactor: make conversion to num peers explicit

fedimint-core/src/lib.rs, fedimint-server/src/consensus/aleph_bft/keychain.rs, fedimint-server/src/consensus/engine.rs, modules/fedimint-ln-client/src/api.rs, modules/fedimint-ln-server/src/lib.rs, modules/fedimint-lnv2-client/src/api.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-mint-client/src/backup/recovery.rs, modules/fedimint-mint-client/src/output.rs, modules/fedimint-mint-server/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs
Follow-up to #5429
Actually it was smaller than I thought. But there might be further places where we e.g. want to take `NumPeers`.
=> refactor: finish `NumPeers` refactoring

Cargo.lock, fedimint-api-client/Cargo.toml, fedimint-api-client/src/api.rs, fedimint-core/Cargo.toml, fedimint-load-test-tool/Cargo.toml, fedimint-load-test-tool/src/main.rs, fedimint-server/Cargo.toml, fedimint-server/src/net/api.rs, fedimint-server/src/net/api/http_auth.rs, fedimintd/Cargo.toml
Replaces #5438, #5437, and #5436
=> chore: bump jsonrpsee and related dependencies from 0.22.5 to 0.23.0

deny.toml
This is causing our CI dependency audit to fail
For details, you can run `cargo-deny check licenses` locally. The following deps currently use the Unicode-3.0 license:
`icu_collections`
`icu_locid`
`icu_locid_transform`
`icu_locid_transform_data`
`icu_normalizer`
`icu_normalizer_data`
`icu_properties`
`icu_properties_data`
`icu_provider`
`icu_provider_macros`
`litemap`
`tinystr`
`writeable`
`yoke`
`yoke-derive`
`zerofrom`
`zerofrom-derive`
`zerovec`
`zerovec-derive`
=> fix: add unicode 3.0 license to list of allowed licenses

gateway/ln-gateway/proto/gateway_lnrpc.proto, gateway/ln-gateway/src/gateway_module_v2/complete_sm.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/lnd.rs, gateway/ln-gateway/src/state_machine/complete.rs, gateway/ln-gateway/src/state_machine/mod.rs
On the lightning gateway, each incoming HTLC from the underlying lightning node fires out an `InterceptHtlcRequest` to the stream returned by `ILnRpcClient::route_htlcs()`. The gateway responds by calling `ILnRpcClient::complete_htlc()` and passing in an `InterceptHtlcResponse` which includes two pieces of data:
1. How the HTLC should be handled (`InterceptHtlcResponse.action`)
2. Data used to identify the HTLC (`InterceptHtlcResponse.incoming_chan_id` and `InterceptHtlcResponse.htlc_id`)
The `incoming_chan_id` and `htlc_id` fields combined act as a unique identifier for a given HTLC, essentially mapping an `InterceptHtlcResponse` to the `InterceptHtlcRequest` it is responding to. We use these two fields instead of simply using the payment hash because, while we don't currently support …
=> chore: pipe payment hash from InterceptHtlcRequest to InterceptHtlcResponse

Cargo.lock, Cargo.toml, devimint/Cargo.toml, devimint/src/external.rs, fedimint-bitcoind/Cargo.toml
Necessary for ldk lightning gateway, since `ldk-node` panics if the esplora server it relies on is not able to respond to requests when the node starts up
=> fix: devimint jit esplora waits for esplora server to be ready

gateway/ln-gateway/proto/gateway_lnrpc.proto, gateway/ln-gateway/src/bin/cln_extension.rs, gateway/ln-gateway/src/lightning/cln.rs
Fixes: https://github.com/fedimint/fedimint/issues/278
Adds the ability for CLN to pay pruned invoices.
I kept the old implementation of paying the full BOLT11 invoice, since the new payment implementation is new and might not be as robust as the old implementation. Eventually once we are satisfied it is robust, we can remove the legacy payment implementation.
=> feat: CLN Pruned Invoices

Cargo.lock, fedimint-logging/Cargo.toml, fedimint-logging/src/lib.rs
Closes #5253 
Removed all the instance/reference of `tracing-chrome` from `fedimint-logging`
=> chore: remove instances of `tracing-chrome`

Cargo.lock, fedimint-core/Cargo.toml, fedimint-core/src/invite_code.rs, modules/fedimint-mint-client/Cargo.toml, modules/fedimint-mint-client/src/lib.rs
The encoding unifies our cash with Cashu. Furthermore the url safe base64 encoding makes it easy to copy and paste a token from and into chats, email etc. Using json makes it extendable and human readable given any standard url safe decoder.
Furthermore, this will save us just short of 500 lines when we remove the old encoding and also allow us to rid ourselves of TieredMulti.
=> feat: url safe json encoded invite codes and ecash

fedimint-cli/src/db_locked.rs, fedimint-core/src/db/mem_impl.rs, fedimint-core/src/db/mod.rs, fedimint-rocksdb/src/lib.rs, fedimint-server/src/consensus/engine.rs, fedimint-server/src/consensus/mod.rs, fedimint-server/src/envs.rs, fedimint-server/src/lib.rs, fedimint-testing/src/federation.rs
Fixes: https://github.com/fedimint/fedimint/issues/5450
I think this might be useful for federations that potentially corrupt their database. The checkpoint retention  is configurable, so this feature can be turned off if guardian operators don't want the backups.
=> feat: Checkpoint database when completing an AlephBFT session

gateway/integration_tests/src/main.rs, gateway/ln-gateway/tests/integration_tests.rs
Part of https://github.com/fedimint/fedimint/issues/5168
Makes `test_can_change_default_routing_fees` and `test_can_change_federation_routing_fees` apart of the devimint tests.
=> chore: convert fee configuration tests to devimint tests

Cargo.lock, fedimint-testing/Cargo.toml, fedimint-testing/src/ln.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, gateway/ln-gateway/src/gateway_module_v2/send_sm.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, misc/git-hooks/pre-commit, modules/fedimint-ln-common/src/gateway_endpoint_constants.rs, modules/fedimint-ln-common/src/lib.rs, modules/fedimint-lnv2-client/Cargo.toml, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-client/src/send_sm.rs
This pr allows a lnv2 client to specify a custom amount that should be payed instead of the invoices own amount. This allows to use lightning multi path payments to pay the same invoice from multiple mints and thereby simplifies liquidity management between mints and allows for a unified balance across mints. 
These so called multi mint payments where originally invented by the Cashu project.
=> feat: enable multi mint payments

modules/fedimint-ln-client/src/lib.rs
We do not have an error message for when we fail to scan/claim an incoming contract at a particular index. We currently just return an empty vector, which makes it difficult to debug. @benthecarman
=> chore: add error message for failed claimed contract

devimint/src/external.rs, gateway/cli/src/main.rs
Remove duplicate calls to `wait_for_chain_sync()` and stop polling the underlying command since the command itself already performs polling here:
https://github.com/fedimint/fedimint/blob/9e15104e126bb850e792d148aed14aa26d1dad6b/gateway/cli/src/main.rs#L338-L357
Also fix a race condition in `gateway-cli lightning wait-for-chain-sync` and raise the polling rate to get slightly faster & more consistent mprocs startup times
=> chore: simplify dev fed startup

fedimint-core/src/task.rs, fedimint-core/src/task/inner.rs
Part of #1576
`TaskGroupInner` contains a few locks, but its data and functionality are intermixed with `TaskGroup`.
In this PR we move `TaskGroupInner` into a separate file, isolating its functionality from `TaskGroup` and making its locking behavior easier to grok.
Then we replace `TaskGroupInner`'s `VecDeque` of task handles with an unbounded channel, which removes the need for any locking when adding a new task. We still need to lock when accessing the task handles, but this is already done in an `async` function so we can wrap the channel reader in an async mutex rather than a blocking one.
=> chore: cleanup TaskGroupInner

Cargo.toml
It is actually slightly faster. (verified with `j bench-compilation`):
Before:
```
Full  check   debug:   38.38  447.02   44.17
Incr  check   debug:    3.31    4.79    3.42
Full  build   debug:   69.23 1166.67   97.05
Incr  build   debug:   14.32   24.23   14.01
```
After:
```
Full  check   debug:   38.23  447.73   44.11
Incr  check   debug:    3.29    4.81    3.36
Full  build   debug:   67.84 1165.78   93.52
Incr  build   debug:   13.34   24.01   12.85
```
Inspired by https://www.reddit.com/r/rust/comments/1dkzzn5/dioxus_labs_highlevel_rust/
=> chore: build proc-macros and build deps in release mode

modules/fedimint-lnv2-client/src/api.rs, modules/fedimint-lnv2-client/src/cli.rs, modules/fedimint-lnv2-tests/src/bin/gateway_registration_sanity.rs
The cli can now fetch the gateways from all peers or optionally supply a peer id to only fetch from one peer. The latter option is used by the guardian to check its own gateway set.
=> fix: enable cli to fetch gateways without auth

fedimint-testing/src/ln.rs, gateway/ln-gateway/proto/gateway_lnrpc.proto, gateway/ln-gateway/src/bin/cln_extension.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/lnd.rs
A bit of a nit, but the rest of the fields in our proto definitions have unit suffixes where appropriate (`_msats` or `_sats`). Should be a simple change since I don't believe we've locked in backwards-compatibility for this field yet since it's used for LNv2.
=> chore: rename CreateInvoiceRequest.expiry to expiry_secs

gateway/ln-gateway/src/db.rs
These don't need to be exposed to the rest of the codebase since they only need to be used for migration purposes, but this module already exposes `get_gatewayd_database_migrations()`
=> chore: make GatewayConfiguration v0 structs private

fedimint-core/src/envs.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-common/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
Closes https://github.com/fedimint/fedimint/issues/5453
This approach prevents peers from processing RBF withdrawal outputs in `process_output`.
These changes are meant to be as minimal as possible to prevent RBF withdrawals, with the intent of removing all RBF withdrawal logic along with destructive client and server db migrations once this version reaches End of Life support. I'm not sure if we've reached consensus on how long we want to support versions (see: https://github.com/fedimint/fedimint/discussions/3950#discussioncomment-7862690), but the linked chart and several out-of-band discussions suggest the minimum supported version is two major versions in the past, i.e. if this lands in 0.4.0, we can safely remove the remaining RBF logic in 0.6.0. If this approach is accepted, I'll …
=> fix(wallet): prevent rbf withdrawals

fedimint-core/src/lib.rs, fedimint-testing/src/btc/mock.rs
In `rust-bitcoin` the `blockdata` module is a code organisation thing, it should never have been public. One day those guys would like to remove it, so as not to be a PITA for `fedimint` when they do lets remove all usage of `blockdata::` now.
Internal change only, no externally visible changes.
=> Remove usage of blockdata:: from bitcoin paths

nix/flakebox.nix
`fedimintd` and `devtools` containers don't currently have the recoverytool. This PR adds it to both images.
=> chore: add recoverytool to fedimintd and devtools

Cargo.lock, fedimint-cli/src/lib.rs, fedimint-dbtool/src/lib.rs, fedimint-testing/src/ln.rs, modules/fedimint-lnv2-client/src/api.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-client/src/receive_sm.rs, modules/fedimint-lnv2-client/src/send_sm.rs, modules/fedimint-lnv2-common/src/lib.rs, modules/fedimint-lnv2-tests/Cargo.toml, modules/fedimint-lnv2-tests/tests/mock.rs, modules/fedimint-lnv2-tests/tests/tests.rs
As part of https://github.com/fedimint/fedimint/issues/5168, I would like to remove the gateway's webserver from our tests. It should not be necessary since everything is running in the same process, and in the past it has been the source of flakiness.
LNv2 still has a dependency on the webserver, this PR mocks the clients interactions with the gateway so that there is no dependency anymore. Necessary for https://github.com/fedimint/fedimint/pull/5545
=> test: mock LNv2 interactions with gateway

fedimint-client/src/lib.rs, fedimint-client/src/oplog.rs, fedimint-client/src/sm/executor.rs, fedimint-client/src/sm/notifier.rs, fedimint-dbtool/src/dump.rs, fedimint-recoverytool/src/main.rs, fedimint-rocksdb/src/lib.rs, fedimint-server/src/consensus/aleph_bft/backup.rs, fedimint-server/src/consensus/db.rs, gateway/ln-gateway/src/db.rs, gateway/ln-gateway/src/lib.rs, modules/fedimint-ln-server/src/lib.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-mint-server/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs
This makes it easier to see at a glance whether a database interaction is writing or just reading
=> chore: use begin_transaction_nc where possible

modules/fedimint-wallet-server/src/lib.rs
Part of #1576
When `Wallet.block_count_local` was first added, `Wallet::get_block_count` made an API call to the bitcoin backend and then cached the value in `block_count_local` to ensure we didn't need to call `get_block_count` when fetching the local block count (see #3083). But since then, `get_block_count` was modified to read from a `watch::Receiver` rather than make an API call (see #4916), making `block_count_local` no longer necessary.
=> chore: remove `Wallet.block_count_local`

.github/workflows/ci-nix.yml
=> chore(ci): publish fedimint-recoverytool as a part of the release

Cargo.lock, devimint/Cargo.toml, devimint/src/federation.rs, fedimint-cli/Cargo.toml, fedimint-cli/src/client.rs, modules/fedimint-mint-client/src/client_db.rs, modules/fedimint-wallet-client/Cargo.toml, modules/fedimint-wallet-client/src/backup.rs, modules/fedimint-wallet-client/src/cli.rs, modules/fedimint-wallet-client/src/client_db.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-tests/src/bin/wallet-recovery-test.rs, modules/fedimint-wallet-tests/tests/tests.rs, scripts/tests/test-ci-all.sh, scripts/tests/wallet-recovery-test.sh
During recovery scan the pegin addresses to find a best place to start deriving new
addresses.
Since we are already checking them and potentially leaking them to the node.
Notably adds module-cli `fedimint-cli module wallet ...` support.
=> feature(wallet-client): client wallet module backup & recovery

fedimint-cli/src/client.rs, gateway/ln-gateway/src/lib.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
There are a few footguns that make peg-ins an expert only feature. This PR adds documentation highlighting these issues and strongly recommends clients to remove the functionality of generating peg-in addresses.
=> chore: add documentation warning peg-ins are an expert only feature

modules/fedimint-wallet-common/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
Peg-out transactions stuck in the mempool are incredibly risky. In addition to reducing the confirmation target used when estimating the feerate (see: https://github.com/fedimint/fedimint/issues/5498), we should multiply the estimated feerate.
The multiplier of 4 is hardcoded to be conservative. We've considered making this value configurable, either through the local config json or through environment variables, however making this multiplier easy to adjust downwards increases the risk of an operator optimizing peg-out fees then getting a peg-out stuck.
=> chore: add feerate multiplier

.github/workflows/ci-nix.yml, flake.lock
We had to downgrade `nix` on our CI runners.
=> fix(ci): fix to work with downgraded Nix version

Cargo.lock, fedimint-api-client/Cargo.toml, fedimint-api-client/src/api/mod.rs, fedimint-core/Cargo.toml, fedimint-load-test-tool/Cargo.toml, fedimint-server/Cargo.toml, fedimintd/Cargo.toml
I'll keep #5544 just for the tls feature usage and fix, using this one for bumping jsonrpsee.
=> chore(deps): bump jsonrpsee-* from 0.23.2 to 0.24.0

fedimint-server/src/consensus/api.rs, fedimint-server/src/net/api/mod.rs
Currently not easy to ensure that a given piece of logic in a api endpoint handler is actually running after auth was performered.
By introducing a token returned only by `check_uath` and requiring it as an argument, we can make mistakes of this type near impossible.
=> refactor: GuardianAuthToken

fedimint-cli/src/lib.rs, fedimint-core/src/config.rs
=> fix: `fedimint-cli invite-code` using deprecated API

fedimint-cli/src/lib.rs, fedimint-core/src/config.rs
Backport of #5607 to `releases/v0.4`.
=> [Backport releases/v0.4] fix: `fedimint-cli invite-code` using deprecated API

misc/mprocs.yaml
guardian logfiles are now called fedimint-default-X.log
=> fix: fix mprocs logfile paths

Cargo.lock, modules/fedimint-lnv2-tests/Cargo.toml, modules/fedimint-lnv2-tests/src/bin/tests.rs, scripts/tests/lnv2-module-test.sh
Moves the pegin gateway commands above the tests since they are agnostic to each test. This allows us to run each test individually based on a CLI parameter.
=> refactor: LNv2 pegin gateways before tests

devimint/src/vars.rs, docs/RELEASE_NOTES-v0.4.md, fedimintd/src/fedimintd.rs
This will require all end users to acknowledge that they are aware of upgrading in the lockstep requirement.
Fix #5603
=> chore: require acking v0.4 upgrade instructions via env var

devimint/src/vars.rs, docs/RELEASE_NOTES-v0.4.md, fedimintd/src/fedimintd.rs
Backport of #5605 to `releases/v0.4`.
=> [Backport releases/v0.4] chore: require acking v0.4 upgrade instructions via env var

modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-tests/tests/mock.rs, modules/fedimint-lnv2-tests/tests/tests.rs
Adds a check to LNv2 to verify the `Currency` of the invoice before paying, to ensure that it is the same as the federation's currency.
=> test: lnv2 rejects wrong network

devimint/src/gatewayd.rs, fedimint-api-client/src/api/federation_peer_client.rs, fedimint-api-client/src/lib.rs, fedimint-cli/src/lib.rs, fedimint-client/src/lib.rs, fedimint-client/src/meta.rs, fedimint-core/src/util/backoff_util.rs, fedimint-core/src/util/mod.rs, fedimint-server/src/net/peers.rs, gateway/cli/src/main.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs
Limit the `backon` types that are exported from `fedimint-core` and export a few standard backoff functions:
`background_backoff()`, `aggressive_backoff()`, `immediate_backoff()`, `custom_backoff()`
=> chore: consolidate usage of backoffs

devimint/src/cli.rs
Backport of #5637 to `releases/v0.4`.
=> [Backport releases/v0.4] fix(devimint): `devimint devfed` does not block

devimint/src/cli.rs
Backport of #5639 to `releases/v0.4`.
=> [Backport releases/v0.4] fix: bitcoin:bitcoin

fedimint-core/src/util/mod.rs
Otherwise it's easy to overlook that it was used to serialize to string accidentally, dropping auth and leading to hard to debug issues.
=> chore: print redacted user&pass on SafeUrl fmt::Display

gateway/ln-gateway/src/bin/cln_extension.rs, gateway/ln-gateway/src/lightning/lnd.rs, modules/fedimint-lnv2-tests/src/bin/tests.rs
LNv2 exposed 2 separate problems with our lightning implementations when cancelling a HTLC (in v2 context, it is a "payment", not an HTLC).
CLN: Previously, we never canceled HTLCs, we only forwarded them when something would go wrong, which would cause the `FailureNoRoute` response to happen. Previously, if we canceled an HTLC, we actually returned an HTLC processing failure, which crashes the extension. This PR fixes this by just forwarding payments when `Cancel` is received, which will have the affect that we want (i.e failing the payment, but the extension will not crash). When V1 is removed, we can remove the forwarding option altogether and simply rely on `Cancel` now.
LND: There was a small bug in `cancel_hold_invoice`, where it refuses to cancel a invoice that is not in the open …
=> fix: LNv2 Lightning Fixes for Cancel Payment/HTLC

fedimint-cli/src/client.rs, fedimint-load-test-tool/src/common.rs, fedimint-wasm-tests/src/lib.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-tests/tests/tests.rs
Backport of #5655 to `releases/v0.4`.
=> [Backport releases/v0.4] chore: always include invite code in oob ecash

fedimint-testing/src/ln.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, gateway/ln-gateway/src/gateway_module_v2/send_sm.rs, gateway/ln-gateway/src/lightning/cln.rs, gateway/ln-gateway/src/lightning/lnd.rs, gateway/ln-gateway/src/lightning/mod.rs, gateway/ln-gateway/src/state_machine/pay.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-tests/tests/mock.rs
lnv2 multi mint payment support blocks the ldk gateway pr as discussed there: https://github.com/fedimint/fedimint/pull/5554
=> Remove multi mint payments from lnv2 to enable ldk gateways

fedimint-cli/src/client.rs
We only expose the session count using the dev commands. This adds session count to `fedimint-cli` so federations can easily get the current session count, which is useful for deciding on an upcoming session count to shutdown after for coordinated upgrades.
This requires backporting to `releases/v0.3` and `releases/v0.4`.
For improved UX, we should also surface the current session count in the admin ui. See: discord [thread](https://discord.com/channels/990354215060795454/990354215878688860/1263173477121130649).
---
```
bash-5.2$ fedimint-cli session-count
{
"count": 1
}
```
=> feat: add session count to fedimint-cli

devimint/src/tests.rs
The upgrade tests are controlled by `parallel`. If we set the parallelism to 1 we still have parallel calls to `latency_tests`, which is causing flakiness in my local env. Running in sequence resolves the flakiness.
=> chore: run upgrade tests in sequence

Cargo.lock, Cargo.toml, fedimint-client/Cargo.toml, modules/fedimint-ln-client/Cargo.toml
~~Bump everywhere except for `fedimint-cli` since it currently uses `lnurl-rs` v0.4.1 which uses `reqwest` v0.11 and causes an error here if we bump it, due to mismatching versions:~~ https://github.com/fedimint/fedimint/blob/a3b9990ebcc5690f67b6a8e8895d8a9024bab77c/fedimint-cli/src/client.rs#L679
~~Once a new version of `lnurl-rs` is published that uses `reqwest` v0.12, we should be able to bump them both together for `fedimint-cli` without issue~~
Edit: a new version of `lnurl-rs` has been published and we're now bumping `reqwest` to v0.12.3 across the entire codebase along with bumping `lnurl-rs` from v0.4.1 to v0.5.0
=> chore(deps): bump reqwest to 0.12.5

modules/fedimint-wallet-client/src/backup.rs, modules/fedimint-wallet-client/src/lib.rs
Backport of #5672 to `releases/v0.4`.
=> [Backport releases/v0.4] chore(wallet-client): add session count to backup

docs/RELEASE_NOTES-v0.4.md
Backport of #5667 to `releases/v0.4`.
=> [Backport releases/v0.4] docs: update lock-step upgrade docs for 0.4

gateway/ln-gateway/Cargo.toml
This exact version in dev-dependencies causes issues when bumping the version. Removing since it's not necessary.
=> fix: rm exact version in dev-dependency

docs/RELEASE_NOTES-v0.4.md
Backport of #5679 to `releases/v0.4`.
=> [Backport releases/v0.4] chore: polish v0.4 upgrade instructions

fedimint-api-client/src/api/mod.rs, fedimint-server/src/consensus/api.rs, fedimint-server/src/consensus/mod.rs
Adds scheduled_shutdown to FederationStatus to surface in UI after someone schedules their shutdown
=> feat: add scheduled_shutdown to FederationStatus

fedimint-build/src/lib.rs
During 0.4 release process we've hit a case where we are unable to have auto-detection working, potentially forcing all downstream users to set env vars when building their projects.
Seems like having that git hash version always is not worth the troubles like this for the end users, so let's just default to 0s when all else failed.
=> chore: default to 0s when unable to detect git hash version during build

fedimint-build/src/lib.rs
Backport of #5692 to `releases/v0.4`.
=> [Backport releases/v0.4] chore: default to 0s when unable to detect git hash version during build

gateway/ln-gateway/src/client.rs, gateway/ln-gateway/src/db.rs, gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/lib.rs
Replaces #5633
If people like this design pattern, it's probably worth applying it for all of our databases, not just the gateway.
I wonder if this wouldn't be better implemented on `DatabaseTransaction`, so that the caller is free to commit the way it wants.
_Originally posted by @dpc in https://github.com/fedimint/fedimint/pull/5633#discussion_r1677212351_
=> chore: move gateway db code into dbtx ext trait

Cargo.lock, Cargo.toml, modules/fedimint-ln-client/Cargo.toml
New lnurl-rs pins transitivie dep to avoid breakage.
To make it work, we need to update reqwest as well.
=> chore: bump lnurl-rs

fedimint-client/src/db.rs, fedimint-core/src/db/mod.rs, fedimint-server/src/consensus/mod.rs, fedimint-testing/src/db.rs
Backport of #5716 to `releases/v0.4`.
=> [Backport releases/v0.4] fix(client): ignore user data in the new-db check

fedimint-dbtool/src/dump.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/db.rs, gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/lnd.rs, gateway/ln-gateway/src/state_machine/pay.rs
Follow-up to #5704
Move the rest of the gateway db code into the transaction extension trait. This makes usage of the db easier to understand at a glance, and allows us to make most of the gateway db keys private.
=> chore: extend gateway dbtx ext trait

fedimint-client/src/db.rs
Backport of #5705 to `releases/v0.4`.
=> [Backport releases/v0.4] fix: don't panic when migrating without existing config

gateway/cli/src/general_commands.rs, gateway/cli/src/lightning_commands.rs, gateway/cli/src/main.rs
With the addition of the lightning liquidity API, the current structure of the gateway CLI is becoming a bit unwieldy. In this PR, we're splitting the CLI commands into two groups: lightning commands (i.e. the liquidity API) and general commands. Each lives in its own file, along with its handling logic. The `General(GeneralCommands)` enum variant of `Commands` is annotated with `#[command(flatten)]` which prevents any behavior change (so, for example, `gateway-cli info` is not changed to `gateway-cli general info`).
=> chore: split gateway cli

Cargo.lock, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/envs.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/ldk.rs, gateway/ln-gateway/src/lightning/mod.rs
Add a third lightning node type to the gateway, a lightning node powered by [`ldk-node`](https://crates.io/crates/ldk-node) which runs in the same process as the gateway. The gateway can be run in ldk mode by setting the following environment variables:
`FM_LDK_ESPLORA_SERVER_URL`: Esplora server where blockchain data is accessed
`FM_LDK_NETWORK`: The bitcoin network being used (e.g. mainnet/testnet)
`FM_PORT_LDK`: The port that the lightning server is running on, where other lightning nodes can access it
The node's data is stored in a subdirectory of the gateway's data folder
This gateway mode should still be considered experimental!!! None of the behavior is tested or has locked-in backwards compatibility yet!
=> feat: add ldk gateway

fedimint-core/src/module/mod.rs, modules/fedimint-mint-common/src/config.rs, modules/fedimint-wallet-common/src/config.rs
=> refactor: get rid of last __reexports

.github/workflows/upgrade-tests.yml, devimint/src/federation.rs, devimint/src/tests.rs, devimint/src/util.rs
Closes https://github.com/fedimint/fedimint/issues/5604
- Adds new GH workflow that runs upgrade tests vs master once daily during off hours
- Adds coordinated shutdown logic to upgrade tests in devimint
Upgrade tests currently take a while to run, so this is triggered as a daily cron and not part of the PR jobs.
=> chore(ci): add upgrade tests vs master

fedimint-cli/src/client.rs, fedimint-load-test-tool/src/common.rs, fedimint-wasm-tests/src/lib.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-tests/tests/tests.rs
I talked to @joschisan, not every federation will want users to leak the invite code. `OOBNotesV2` will need to have an optional invite code too instead of the other way around.
=> Revert "[Backport releases/v0.4] chore: always include invite code in oob ecash"

gateway/ln-gateway/src/lightning/lnd.rs, gateway/ln-gateway/src/lightning/mod.rs
The `network` field of the `GetNodeInfoResponse` proto message states the following:
https://github.com/fedimint/fedimint/blob/0c7b40da7777311c95000fdac24fd77cfa730a21/gateway/ln-gateway/proto/gateway_lnrpc.proto#L67-L68
In this PR, we ensure that LND's implementation of `ILnRpcClient::info` adheres to the specified valid values constraint above.
=> chore: lnd gateway impl handles network naming mismatch

justfile.fedimint.just
It's just a quick check, no need to fire up all 96 CPUs of our CI workers.
=> chore(ci): limit fuzz-ci-quick to 2 threads

fedimint-server/src/config/api.rs, fedimint-server/src/config/mod.rs, fedimint-server/src/consensus/engine.rs, fedimint-server/src/consensus/mod.rs, fedimint-server/src/lib.rs, fedimint-server/src/net/api/mod.rs, fedimint-server/src/net/peers.rs, fedimint-server/src/net/peers_reliable.rs, fedimint-testing/src/federation.rs
They can be controlled by command line args / env vars directly, and having them redundantly in the config is just confusing.
=> refactor(server): remove bind addr's from local config

.github/workflows/upgrade-tests.yml
We cut v0.3.3 so we should use this version in the daily upgrade tests vs master.
=> chore(ci): bump v0.3.3-rc.2 -> v0.3.3 in upgrade tests

Cargo.toml, fedimint-bitcoind/Cargo.toml
Re #3049,  but we need to update to electrum-client 0.19 (bitcoin 0.31)
=> chore(client): electrum-client to use rustls

.github/workflows/ci-nix.yml
Tested in https://github.com/fedimint/fedimint/actions/runs/10116210016/job/27978568323 as a part of a 0.4 backport of #5753
=> fix(ci): cachix commands failing in builds flows

.gitattributes
Stolen from https://github.com/rust-bitcoin/rust-bitcoin/pull/3105
=> chore: Set `diff=rust` for `*.rs` in `.gitattributes`

fedimint-client/src/db.rs, fedimint-client/src/lib.rs, fedimint-client/src/secret.rs
Fix #3504
This prevent user/application from accidentally using a different secret, which could lead to ... who knows what. Not good things, that's for sure.
=> feat(client): save and verify root secret hash when creating the client

fedimint-server/src/consensus/aleph_bft/data_provider.rs, fedimint-server/src/consensus/engine.rs, fedimint-server/src/metrics.rs
This is resurrecting @joschisan 's #5432 with a fix I proposed for self-synchronization.
Fix #3759 - which I spotted during going through old issues and it reminded me about #5432.
This PR was&is a great idea, it has minimal implementation and I believe the fix I proposed is absolutely practical and will work just fine. There is really no point sitting on it: We could have been already gathering information from real deployments had it been a part of 0.4.
If you figure out a better way to do it, we can just replace it. It's not a consensus or any backward compat-encumbered code. Let's not let perfect be an enemy of good enough. Even if this metric would return wrong results 50% of the time, it still would be very useful.
=> feat: track ordering latency

justfile.fedimint.just, scripts/dev/build-docs.sh
If you go to https://docs.fedimint.org and type something in the search box, you'll see that the results are displayed under the index.html we added. It's annoying, so this PR fixes it.
=> fix(docs): Search does not hide the static content

devimint/src/gatewayd.rs, gateway/ln-gateway/proto/gateway_lnrpc.proto, gateway/ln-gateway/src/bin/cln_extension.rs, gateway/ln-gateway/src/lightning/cln.rs, gateway/ln-gateway/src/lightning/ldk.rs, gateway/ln-gateway/src/lightning/lnd.rs, gateway/ln-gateway/src/lightning/mod.rs
> Can we use bytes instead of string?
_Originally posted by @m1sterc001guy in https://github.com/fedimint/fedimint/pull/5218#discussion_r1600141463_
When adding `close_channels_with_peer` command to the gateway liquidity API, we decided to use bytes instead of a string for the pubkey. But this was after we already added a few other commands that used strings for the pubkey. Here we're going back and changing those to also use bytes for the pubkey.
=> chore: liquidity api uses bytes for pubkey

.github/workflows/upgrade-tests.yml
Using `v0.4.0` in the upgrade path vs master now that we've cut the release.
---
Verified CI passes for upgrade tests (doesn't run in PR workflow): https://github.com/fedimint/fedimint/actions/runs/10255509103/job/28372587992?pr=5802
=> chore(ci): use v0.3.3 -> v0.4.0 -> master in upgrade tests

scripts/_common.sh
This PR updates back-compat tests so `gateway-cli` and `gatewayd` are on the same version. We currently set `fedimint-cli` and `gateway-cli` to the same version.
@m1sterc001guy brought up some good points that there isn't much benefit in ensuring backwards-compatibility with `gateway-cli` since it's just a management tool for the gateway and doesn't hold funds or persist state like `fedimint-cli`. We should expect users to have the same version of `gatewayd` and `gateway-cli`. If there's a discrepancy, they can change the `gateway-cli` version to match, which doesn't require migrations.
=> chore(ci): use same version for gateway-cli and gatewayd

gateway/ln-gateway/src/client.rs, gateway/ln-gateway/src/lib.rs
Rather than having a lock for joining & leaving federations that carries only semantic meaning, we can grab the write lock for `Gateway.federation_manager`. Locking on the data we're modifying makes it more clear what's going on.
=> chore: remove Gateway.client_joining_lock

fedimint-client/src/lib.rs, fedimint-client/src/module/mod.rs, gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs, gateway/ln-gateway/src/gateway_module_v2/send_sm.rs, gateway/ln-gateway/src/state_machine/pay.rs, modules/fedimint-ln-client/src/incoming.rs, modules/fedimint-ln-client/src/pay.rs, modules/fedimint-ln-client/src/receive.rs, modules/fedimint-lnv2-client/src/receive_sm.rs, modules/fedimint-lnv2-client/src/send_sm.rs, modules/fedimint-mint-client/src/input.rs, modules/fedimint-mint-client/src/oob.rs, modules/fedimint-wallet-client/src/deposit.rs, modules/fedimint-wallet-client/src/pegin_monitor.rs
Partially Fixes: https://github.com/fedimint/fedimint/issues/5598
`claim_input` currently does not return a `Result`, but it can panic if there is not sufficient funds to claim the input. This is un-intuitive and a foot gun for module developers since it will crash if the client has no funds, which might be the default for newly initialized clients.
Instead, we should return a `Result` and force the module state machines to deal with this error. Currently, this PR just uses `expect` in each module state machine, so the behavior is the same, but in the future we could add looping to retrying claiming an input when funds are available.
=> chore: claim_input returns result

fedimint-bitcoind/src/esplora.rs
It seems to me that what happened is that during rust-bitcoin upgrade the internal representation of `BlockHash` was reversed and now naive `hex` crate encoding gives us wrong hash, that is interpreted as regtest network. Using `.to_string` on `BlockHash` does the right thing independent of underlying order of bytes.
This bug causes DKG to fail when esplora is used as a backend.
=> fix: esplora bitcoin backend returning reverse network hash / wrong network

fedimint-bitcoind/src/esplora.rs
Backport of #5813 to `releases/v0.4`.
=> [Backport releases/v0.4] fix: esplora bitcoin backend returning reverse network hash / wrong network

justfile.fedimint.just
Closes https://github.com/fedimint/fedimint/issues/5699
Replacing the cargo workspaces command since it fails to update `[dev-dependencies]`. I used this command to bump `v0.4.0 -> v0.4.1-rc.0` and `v0.4.1-rc.0 -> v0.4.1`
=> chore: add just command to bump versions using sed

Cargo.lock, gateway/cli/Cargo.toml, gateway/cli/src/general_commands.rs, gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, modules/fedimint-ln-common/src/gateway_endpoint_constants.rs
Adds functionality to directly send/receive ecash for a gateway operator. Part of the steps to make running a gateway more reasonable / manageable and exposing additional functionality for liquidity management through the new gateway UI.
=> feat: Adds Ecash Send and Receive commands and RPCs to Gateway

gateway/cli/src/general_commands.rs, gateway/ln-gateway/src/bin/cln_extension.rs
No functional change, just extracting duplicate code between two arms of a `match` statement
=> chore: consolidate cln create_invoice()

fedimint-testing/src/ln.rs, gateway/cli/src/general_commands.rs, gateway/ln-gateway/proto/gateway_lnrpc.proto, gateway/ln-gateway/src/bin/cln_extension.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/cln.rs, gateway/ln-gateway/src/lightning/ldk.rs, gateway/ln-gateway/src/lightning/lnd.rs, gateway/ln-gateway/src/lightning/mod.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, modules/fedimint-ln-common/src/gateway_endpoint_constants.rs
This command lists the following:
* Total amount of on-chain bitcoin
* Local lightning liquidity
* eCash across all federations
The primary purpose of this command is to provide a liquidity overview in the gateway UI
=> feat: add gateway rpc + cli command to get balances

gateway/integration_tests/src/main.rs, gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/mod.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/rpc/rpc_server.rs
Cleans up a bunch of stuff about `gateway-cli info` that has been bugging me for awhile.
- Removes `ClientConfig` from the `info` command. `ClientConfig` can still be retrieved using `gateway-cli config` command.
- Fixes `gateway-cli config` command
- Removes route hints and routing fees from `info`. Routing fees are already included in each individual federation. Route hints can be acquired by generating an invoice.
- Adds the gateway's API URL
- Adds the gateway's Lightning Mode for determining what type of node it is.
=> chore: gateway-cli info cleanup

Cargo.lock, fedimint-core/src/core/server.rs, fedimint-core/src/module/mod.rs, fedimint-server/Cargo.toml, fedimint-server/src/consensus/transaction.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-server/src/lib.rs, modules/fedimint-mint-tests/tests/tests.rs
The verification of ecash note signatures is at the moment the biggest performance bottleneck of the system as we can only verify about 500 per second per core. Performance testing on my M2 MacBook Air with 8 cores showed a 5x speed up when parallelising the verification across 10 to 50 signatures.
This pr allows us to lower the input fee of one sat per ecash not to a more reasonable 100 msats for DOS protection.
=> feat: parallelise signature checks

.github/workflows/upgrade-tests.yml, justfile.fedimint.just, scripts/tests/upgrade-test.sh
This should allow us to provide an upgrade path of versions when triggering a manual workflow (e.g. `"v0.3.3 v0.4.0 v0.4.1-rc.0"`). This seems like an improvement from needing to open a draft PR that includes the versions along with updating the workflow to trigger on PRs (see: https://github.com/fedimint/fedimint/pull/5821#issuecomment-2282259382).
I'll be able to verify once this is merged to `master`.
Resource to help review: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
=> chore(ci): add version params to manually triggered upgrade tests

Cargo.lock, devimint/Cargo.toml, devimint/src/devfed.rs, devimint/src/external.rs, devimint/src/lib.rs
On my local machine (Apple M1 Pro, 32GB RAM) the mprocs startup times before/after are:
Before (master branch):
Attempt 1: 93.3s
Attempt 2: 95.5s
Attempt 3: 94.0s
Attempt 4: 93.8s
Attempt 5: 93.5s
Average: 94.0s
After (PR branch):
Attempt 1: 65.2s
Attempt 2: 64.0s
Attempt 3: 63.7s
Attempt 4: 65.7s
Attempt 5: 64.3s
Average: 64.6s
So this is roughly 30% faster and helps to undo some of the damage caused by merging the LDK gateway
=> chore: parallelize mprocs lightning channel opening

fedimint-api-client/Cargo.toml, fedimint-api-client/src/api/mod.rs, fedimint-api-client/src/api/net.rs, fedimint-api-client/src/api/peer.rs, fedimint-cli/Cargo.toml, fedimint-cli/src/lib.rs, fedimint-client/Cargo.toml, fedimint-client/src/lib.rs, fedimint-testing/Cargo.toml, fedimint-testing/src/federation.rs, gateway/cli/Cargo.toml, gateway/cli/src/general_commands.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/db.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs
related to #4752 
The usage of `arti-client` for adding Tor support (#5443) recently landed on master, but `arti-client` relies on a bunch of other tor related crates, which can lead to an increase on the binary size.
In order to allow users to have the opt-in/opt-out of such feature and the leading binary increase, this PR adds a new feature where required for Tor support.
I'm wondering if we should have it by default, as its removal from default-features becomes a SemVer incompatible change.
Any other thoughts on it?
=> feat(tor): put `tor` support behind a feature, use as default

.github/workflows/upgrade-tests.yml
Timed out at 60 minutes. Since this isn't part of the CI flow, let's bump to 120.
https://discord.com/channels/990354215060795454/1092891381124579349/1273686857632186550
=> chore(ci): bump upgrade tests timeout to 120 minutes

devimint/src/envs.rs, devimint/src/external.rs, devimint/src/gatewayd.rs, devimint/src/tests.rs, devimint/src/util.rs, gateway/ln-gateway/src/bin/cln_extension.rs, scripts/tests/test-ci-all.sh, scripts/tests/upgrade-test.sh
Fixes: https://github.com/fedimint/fedimint/issues/5863
The culprit PR is https://github.com/fedimint/fedimint/pull/5663/files
This PR broke backwards compatibility between `gatewayd` and `gateway-cln-extension`. I do not think we need to maintain backwards compatibility between these binaries, but `devimint` does not enforce that all of these binaries run as the same version. This breaks the upgrade tests because the extension was expecting a different serialization of the public key when opening a channel than what v0.4.0 was providing.
This PR adds the necessary changes so that `gatewayd`, `gateway-cli`, and `gateway-cln-extension` all run as the same version.
=> fix: use same cln extension version as gatewayd

gateway/ln-gateway/proto/gateway_lnrpc.proto, gateway/ln-gateway/src/lightning/ldk.rs
Fixes #5879
The [`Network`](https://docs.rs/bitcoin/0.30.2/bitcoin/network/constants/enum.Network.html) enum in the rust `bitcoin` crate is represented as the strings "bitcoin", "testnet", "regtest", and "signet" (see [here](https://docs.rs/bitcoin/0.30.2/src/bitcoin/network/constants.rs.html#569-578)). In `gateway_lnrpc.proto` we incorrectly documented `GetNodeInfoResponse.network` by saying that the acceptable values instead were "main", "test", "signet", and "regtest". Here we fix this documentation issue and change the LDK gateway implementation to stay true to that documentation change. No changes are needed for LND (we already convert "mainnet" to "bitcoin" [here](https://github.com/fedimint/fedimint/blob/df2073e53c496035fe37c999cb0821970f86dfcb/gateway/ln-gateway/src/lightning/lnd.r …
=> fix: bitcoin network naming mismatch

.github/workflows/ci-nix.yml
Related to https://github.com/fedimint/fedimint/issues/5896
Keeping the issue open after merging so we can verify the `Pre-release` tag is correctly set the next time we push a `*-rc.*` tag.
Resources to help with review
- Custom inputs available in [action-gh-release](https://github.com/softprops/action-gh-release#-customizing)
- `contains()` expression [docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#contains)
=> fix(ci): set release to prerelease if tag contains 'rc'

scripts/tests/upgrade-test.sh
It's not obvious at a glance what versions are used in upgrade tests. This will help when looking through previous CI runs.
=> chore(ci): print versions in upgrade tests script

fedimint-bitcoind/src/electrum.rs, fedimint-bitcoind/src/esplora.rs, fedimint-bitcoind/src/lib.rs
Instead of assuming that any unknown gensis block hash is a regtest network, use the fact the regtest genesis block is hardcoded.
This should protect us from any bugs that lead to invalid block hashes, like in #5813.
=> chore: use a hardcoded regtest genesis block hash

fedimint-bitcoind/src/lib.rs, fedimint-testing-core/src/envs.rs, fedimint-testing/src/fixtures.rs, scripts/tests/backend-test.sh
Noticed while testing https://github.com/fedimint/fedimint/pull/5900
Introduces new env vars to override only the wallet server's Bitcoin RPC for esplora and electrs backend tests. We can't use `FM_FORCE_*` env vars to override because that will also override the wallet client, which fails since electrum can't support `get_txout_proof`.
=> fix(tests): use esplora and electrs backends

gateway/ln-gateway/src/rpc/rpc_server.rs
Needs to be authenticated so that anyone can't just steal from the gateway
=> fix: make spend ecash authenticated

scripts/tests/backend-test.sh
The hourly run is surfacing flakiness in the electrum tests. I noticed similar timeouts when enabling esplora tests in https://github.com/fedimint/fedimint/pull/5902 and needed to run in sequence, so applying the same fix here.
=> fix(tests): run electrum tests in sequence

fedimint-cli/src/client.rs, fedimint-client/src/module/mod.rs, gateway/ln-gateway/src/lib.rs, modules/fedimint-wallet-client/src/client_db.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
The functionality to list and observe deposits was accidentally removed in #5473.
It's a bit tricky because technically a single generated address can now cause multiple operations. My plan is to create a first operation on address generation, this will correspond to the first deposit seen on-chain. 
Any successive deposit could result in another operation log entry. Since this will be hard to do 100% consistently (we don't model the "transaction seen but unconfirmed" state anymore) and the previous behavior was to ignore this anyway I'm not including this here.
=> Restore operation log entries for deposits

scripts/tests/test-ci-all.sh
Associated with https://github.com/fedimint/fedimint/issues/5917
```
fedimint-test-all-wasm32-unknown-unknown-ci> 00:01:20      TIMEOUT [  60.059s] fedimint-wallet-tests::fedimint_wallet_tests on_chain_peg_in_and_peg_out_happy_case
```
I'd prefer to not increase the timeout just for this test using electrs. Disabling while investigating alternatives.
=> chore(ci): disable `bckn_electrs` while investigating test timeouts

modules/fedimint-meta-client/Cargo.toml
`cargo workspaces publish --from-git` fails otherwise:
```
Compiling fedimint-meta-client v0.4.2-rc.1 (/home/user/projects/elsirion/minimint/target-nix/package/fedimint-meta-client-0.4.2-rc.1)
error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
--> src/lib.rs:230:29
|
230 |                     values: serde_json::from_slice(meta.value.as_slice())?,
|                             ^^^^^^^^^^ use of undeclared crate or module `serde_json`
For more information about this error, try `rustc --explain E0433`.
error: could not compile `fedimint-meta-client` (lib) due to 1 previous error
error: failed to verify package tarball
error: unable to publish package fedimint-meta-client
```
=> fix: always require serde_json dep in meta module client

devimint/src/devfed.rs, devimint/src/envs.rs
From this comment: https://github.com/fedimint/fedimint/pull/5852/files#r1723775088
> these are not used anywhere meaningful and they trigger a polling loop by contacting each gateway. Just not necessary.
=> chore: remove unused devfed env vars

modules/fedimint-lnv2-tests/src/bin/tests.rs
LNv2 inter federation test is flaky: https://github.com/fedimint/fedimint/issues/5944
Seems to be an issue with CLN crashing during the test for some reason. I have found it difficult to debug as I cannot reproduce locally and the CI runs have not had enough logs to debug properly.
To unblock CI, this PR deactivates the test from CI.
=> chore: deativate LNv2 inter-federation test

modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
=> Backport: fix: deposit `Claimed` state waits for e-cash to be in wallet

.github/workflows/upgrade-tests.yml, scripts/_common.sh, scripts/tests/upgrade-test.sh
Upgrade tests run all of the test kinds (`fedimint-cli`, `fedimintd`, and `gateway`) using the same upgrade paths. Now that `fedimintd` introduced coordinated upgrades, it's useful to trigger different upgrade paths for different test kinds. E.g. we know that `fedimintd` will fail upgrading from 0.2.1 -> 0.4.0, however it would be useful to test that upgrade path for `fedimint-cli` and `gateway`.
The changes to the GH workflow allows specifying the test kinds when manually triggering a run. If none are provided, all test kinds are run.
=> chore(ci): parameterize which upgrade tests to run

fedimint-client/src/backup.rs
That's a potential foot-gun for integrators imo.
=> fix: don't allow making new backups while recovery is running

devimint/src/tests.rs, modules/fedimint-mint-client/src/backup/recovery.rs, modules/fedimint-mint-client/src/lib.rs
Draft. Let's land #5937 first.
Changes here are technically more correct, though in practice it
doesn't matter. I was debugging some other issue and had my doubts
about it, but after investigation it looks like overshooting here
only leads to mint client code skipping some nonce index, which
is harmless.
In https://github.com/fedimint/fedimint/pull/5937 I add a test that gives me more confidence everything is OK.
=> chore(mint-client): clarify the meaning and handling of one variable 

fedimint-api-client/src/api/global_api.rs
I did some test recoveries on the real Federations and I observed, that due to small cache size wallet & mint recovery fetching diverged and was fetching sessions twice. Not the end of the world, but the whole point of this cache was to avoid doube-downloading, so a waste.
Increasing the size of the LRU, gives enough buffer for everything to reliably stay in sync.
=> chore(client): increase size of the session fetching cache LRUs

devimint/src/gatewayd.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-common/src/config.rs, modules/fedimint-lnv2-server/src/lib.rs
- Reverts https://github.com/fedimint/fedimint/pull/5941
- Adds logic for using `get-funding-address` vs `get-ln-onchain-address`
Debugging the same issue as https://github.com/fedimint/fedimint/pull/5952
=> fix: upgrade test fixes

fedimint-recoverytool/src/main.rs
We were generating one descriptor per session, as if in each session we had one change output generated. We should only generate change descriptors when peg-outs happened.
=> fix(recoverytool): don't generate unused change descriptors

fedimint-bitcoind/src/bitcoincore.rs, fedimint-bitcoind/src/electrum.rs, fedimint-bitcoind/src/esplora.rs, fedimint-bitcoind/src/lib.rs, fedimint-core/src/util/mod.rs, fedimint-testing/src/btc/mock.rs, modules/fedimint-wallet-client/src/api.rs, modules/fedimint-wallet-client/src/cli.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-common/src/endpoint_constants.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/Cargo.toml, modules/fedimint-wallet-tests/tests/tests.rs, scripts/tests/backend-test.sh
Followup addressing:
> Can we assert in a test that the correct blockchain API is used to avoid regressions? Do you think that would be useful?
https://github.com/fedimint/fedimint/pull/5902#pullrequestreview-2254638875
---
Adds two endpoints to wallet server:
- authed endpoint that returns bitcoin rpc kind and url
- auth required since bitcoin url should not be leaked to public
- useful for surfacing to guardians in UI
- url is stripped of `user:pass` prior to sending over the wire
- no-auth endpoint that returns the bitcoin kind for a peer
- useful for surfacing to clients (e.g. `fedimint-observer`)
```bash
bash-5.2$ fedimint-cli module wallet --help
Usage: wallet <COMMAND>
Commands:
await-deposit           Await a deposit on a given deposit address
get-bitcoin-rpc-kind    Returns the …
```
=> Surface Bitcoin RPC used by fedimintd

modules/fedimint-wallet-server/src/lib.rs
Followup to https://github.com/fedimint/fedimint/pull/5905
Two new endpoints were introduced to the wallet server without bumping the minor API version.
=> chore(wallet): bump api minor version

Cargo.lock, fedimint-cli/Cargo.toml, fedimint-client/Cargo.toml, fedimint-testing/Cargo.toml, fedimintd/Cargo.toml, gateway/cli/Cargo.toml, gateway/ln-gateway/Cargo.toml, modules/fedimint-ln-common/Cargo.toml, modules/fedimint-wallet-client/Cargo.toml
On master, running `just check` produces the following errors:
```
warning: /Users/tommyvolk/Documents/GitHub/fedimint/fedimintd/Cargo.toml: `default-features` is ignored for axum, since `default-features` was not specified for `workspace.dependencies.axum`, this could become a hard error in the future
warning: /Users/tommyvolk/Documents/GitHub/fedimint/fedimint-testing/Cargo.toml: `default-features` is ignored for ln-gateway, since `default-features` was not specified for `workspace.dependencies.ln-gateway`, this could become a hard error in the future
warning: /Users/tommyvolk/Documents/GitHub/fedimint/fedimint-cli/Cargo.toml: `default-features` is ignored for fedimint-api-client, since `default-features` was not specified for `workspace.dependencies.fedimint-api-client`, this could …
```
=> fix: remove ignored 'default-features = false'

gateway/integration_tests/src/main.rs, gateway/ln-gateway/src/client.rs, gateway/ln-gateway/src/db.rs, gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/state_machine/mod.rs, gateway/ln-gateway/src/state_machine/pay.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-ln-common/src/lib.rs, modules/fedimint-ln-tests/tests/tests.rs
The concept of a `mint_channel_id` is going away with LNv1, but as https://github.com/fedimint/fedimint/pull/5852 showed it is still useful to have a unique identifier for a federation that is not the federation id, since that is rather long (32 bytes), whereas this identifier is a `u64` and can be variable length encoded.
This PR just renames `mint_channel_id` to `federation_index` to reflect its new use. It will still be used as the short channel id for LNv1 until LNv1 is removed.
=> refactor: rename mint_channel_id to federation_index

fedimint-core/src/envs.rs, fedimint-server/src/net/framed.rs, fedimint-wasm-tests/src/lib.rs, flake.lock
One of the flakes being updated bumps the rust version, which introduces some new clippy rules, hence a few rust diffs here
=> chore: update nix flake

modules/fedimint-lnv2-client/src/api.rs, modules/fedimint-lnv2-client/src/cli.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-client/src/send_sm.rs, modules/fedimint-lnv2-common/src/lib.rs, modules/fedimint-lnv2-server/src/db.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-lnv2-tests/src/bin/tests.rs, modules/fedimint-lnv2-tests/tests/mock.rs, modules/fedimint-lnv2-tests/tests/tests.rs
Currently LNV2 api requires you to specify the gateway api by url, makes it optional. Only really used in testing. In practice you would set this to none and module will choose the gateway for you.
Philosophy of LNv2: guardians set list of vetted gateways and module handles selection logic. All gatways are equal but some are more equal than others.
=> feat: make gateway api optional

gateway/cli/src/general_commands.rs, gateway/ln-gateway/src/bin/gatewayd.rs, gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/gateway_module_v2/complete_sm.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs, gateway/ln-gateway/src/gateway_module_v2/send_sm.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, gateway/ln-gateway/src/state_machine/complete.rs, gateway/ln-gateway/src/state_machine/mod.rs, gateway/ln-gateway/src/state_machine/pay.rs, modules/fedimint-ln-client/src/incoming.rs, modules/fedimint-ln-common/src/gateway_endpoint_constants.rs
Keeping with the theme of gateway recovery, this PR adds a `stop` RPC that shuts down the gateway. Previously, to kill the gateway the gateway operator could just kill the process or use Ctrl-C. The issue with this though, is that if the gateway operator kills the gateway at an unfortunate time (after the incoming contract has been created, but before the gateway has revealed the preimage), AND the operator either deletes their database or restores their mnemonic into another gateway, then the gateway will lose money because it will never reveal the preimage for the incoming payment.
This "safe stop" mechanism will prevent new incoming payments, then wait for incoming payments to complete, then shutdown.
=> feat: gateway safe stop

fedimint-client-wasm/src/lib.rs
makes stream cancellable
sends end event for stream
based on requests from frontend. 
see commits
=> wasm client: rpc stream updates

fedimint-core/src/db/mod.rs
It's already the case, yet in the interface documentation we don't commit to it. I'm quite sure there are already parts of the code that depend on it anyway.
In a system like ours any form of non-determism is unwelcomed. I rather have the db impls have to do the sorting, than all users need to sort. Especially that for all kv stores, sorting should come naturally.
=> fix: find_by_prefix should guarantee order

devimint/src/external.rs, devimint/src/gatewayd.rs, fedimint-testing/src/ln.rs, gateway/cli/src/lightning_commands.rs, gateway/ln-gateway/proto/gateway_lnrpc.proto, gateway/ln-gateway/src/bin/cln_extension.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/cln.rs, gateway/ln-gateway/src/lightning/ldk.rs, gateway/ln-gateway/src/lightning/lnd.rs, gateway/ln-gateway/src/lightning/mod.rs, gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs
Change `ILnRpcClient::open_channel()` to return the channel funding TXID, and set devfed to wait for those TXIDs to be present in the bitcoind mempool before mining blocks. Previously we were just blindly waiting, requiring that we waited significantly longer than needed in order to prevent flakiness.
`just mprocs` startup speed tests on my M1 Pro machine:
Before:
66.0s, 74.0s, 64.2s, 64.3s, 66.2s, 66.7s, 63.8s, 64.0s, 64.0s, 66.4s
Average: 65.96s
After:
55.8s, 54.5s, 56.0s, 54.3s, 56.4s, 54.8s, 54.5s, 56.5s, 63.8s, 54.1s
Average: 56.07s
Average speed improvement of ~15%
=> chore: devfed waits for channel funding txs before mining blocks

devimint/src/external.rs, fedimint-testing/src/ln.rs, gateway/cli/src/lightning_commands.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/cln.rs, gateway/ln-gateway/src/lightning/ldk.rs, gateway/ln-gateway/src/lightning/lnd.rs, gateway/ln-gateway/src/lightning/mod.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, modules/fedimint-ln-common/src/gateway_endpoint_constants.rs
Allow gateway to trigger an on-chain wallet sync on the underlying lightning node. Only implemented for LDK since LND and CLN automatically sync.
This is needed for LDK since `ldk-node::Node` gets its on-chain data from esplora rather than bitcoind and therefore needs to avoid getting rate-limited by esplora by not pinging it too frequently.
This change speeds up `just mprocs` and should allow us to remove the following overrides which were put in place to prevent mprocs startup speed from almost tripling (and which I believe are the cause of #5965):
https://github.com/fedimint/fedimint/blob/06717c0a480f619feadb9b411dd57267fbb03e98/gateway/ln-gateway/src/lightning/ldk.rs#L76-L77
However, attempting to remove those overrides in this PR led to a doubling of mprocs startup time (~100s). I'm …
=> chore: add chain sync command to ILnRpcClient

devimint/src/cli.rs
Rather than each pegin (to the global client, and to each of the 3 gateways) mining blocks, we wait for them all to finish and then mine blocks a single time. I made this change to see if it would uncover any flakiness (since, startup time aside, blocks should only need to be mined a single time), but it also appears to improve devimint startup time. My best guess as to why is that the gateways having fewer blocks to sync speeds up time-to-channel-readiness.
`just mprocs` startup speed tests on my M1 Pro machine:
Before:
51.3s, 48.6s, 49.5s, 55.3s, 52.5s, 45.4s, 56.3s, 52.2s, 50.1s, 52.6s
Average: 51.38s
After:
50.5s, 49.5s, 50.7s, 51.6s, 46.1s, 40.4s, 44.1s, 48.0s, 52.1s, 46.6s
Average: 47.96s
Average speed improvement of ~7%
=> chore: devfed pegin setup only mines blocks once

gateway/ln-gateway/src/rpc/mod.rs
I addressed the TODO about renaming `balance_msat`
=> Removed the TODO about `balance_msat` field

modules/fedimint-wallet-server/src/lib.rs
We pass consensus block counts to `sync_up_to_consensus_height`, which is confusing. This is a simple rename so it's obvious we're using block counts. There are no logical changes.
More context in this PR discussion https://github.com/fedimint/fedimint/pull/6012
=> refactor: rename sync_up_to_block_height and args to count

misc/mprocs.yaml
LDK logs are emitted to a different directory than `ldk_gw`. It is useful for debugging to also have this pane in mprocs
=> chore: add ldk logs to mprocs

devimint/src/cfg/lnd.conf
Fixes: https://github.com/fedimint/fedimint/issues/6009
In our devimint environment, LND will by default use 10 sat/vbyte on commitment transactions. This causing payments from LND -> LDK to fail, because the HTLC commitments will create dust transactions that are larger than the amount LDK is configured to risk to dust. 
On regtest, 10 sat/vbyte is high and unnecessary. We want to set this value high enough that the channel opens are confirmed, but not so high that it causes payments to fail due to dust. In my testing, 5 sat/vbyte seems to work.
=> fix: lower LND's max-commit-fee-rate-anchors in devimint

modules/fedimint-lnv2-tests/src/bin/tests.rs, scripts/tests/lnv2-inter-federation.sh, scripts/tests/test-ci-all.sh
Fixes: https://github.com/fedimint/fedimint/issues/5944
Re-enables the LNv2 inter federation tests, but this time in parallel to the rest of the LNv2 tests. Should prevent any issues with the test timing out.
=> chore: reenable LNv2 inter federation tests in parallel

gateway/ln-gateway/src/rpc/rpc_server.rs
`SYNC_TO_CHAIN` should be authenticated, there is no reason to have it be a public endpoint.
=> fix: make sync_to_chain authenticated

gateway/ln-gateway/src/lightning/ldk.rs
`Description` is an optional parameter, but generating an LDK invoice will fail without one since it only accepts direct descriptions (it does not support description hashes). This is really un-intuitive from the CLI, it actually makes the gateway return a 500 error.
=> fix: use empty description for default

fedimint-server/src/consensus/engine.rs
I think this just leads to a huge slowdown of #6030 and in a normal operation the cost of this API call is neglible.
=> chore(consensus): ask for signed session outcomes without a delay

gateway/ln-gateway/src/lightning/ldk.rs
`ldk-node` already sets the gossip source to p2p [by default](https://docs.rs/ldk-node/0.3.0/ldk_node/struct.Builder.html#defaults), so this isn't needed
=> chore: stop explicitly setting ldk gossip to p2p

fedimint-cli/src/client.rs, fedimint-client/src/db.rs, fedimint-client/src/lib.rs, fedimint-client/src/module/init.rs, fedimint-client/src/module/mod.rs, fedimint-client/src/sm/dbtx.rs, fedimint-core/src/db/mem_impl.rs, fedimint-core/src/db/mod.rs, fedimint-dbtool/src/dump.rs, fedimint-load-test-tool/src/common.rs, fedimint-recoverytool/src/main.rs, fedimint-rocksdb/src/lib.rs, fedimint-server/src/config/api.rs, fedimint-server/src/consensus/api.rs, fedimint-server/src/consensus/engine.rs, fedimint-server/src/consensus/mod.rs, fedimint-server/src/consensus/transaction.rs, fedimint-testing-core/src/db.rs, gateway/ln-gateway/src/client.rs, modules/fedimint-ln-server/src/lib.rs, modules/fedimint-mint-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
This allows going back from prefixed dbtx, to global unprefixed dbtx, but only if one posseses the "access token" created during creation of the prefixed db.
In the future, this could help eliminate bunch of abstractions we introduced to juggle global vs module dbtx, though it might require long term effort and refactoring.
Currently  the goal is to unblock #5995
=> chore(core): `DatabaseTransaction::global_dbtx`

crypto/tpe/src/lib.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, gateway/ln-gateway/src/lib.rs, modules/fedimint-lnv2-client/Cargo.toml, modules/fedimint-lnv2-client/src/api.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-common/src/config.rs, modules/fedimint-lnv2-server/src/db.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-lnv2-tests/tests/mock.rs, modules/fedimint-lnv2-tests/tests/tests.rs
A bunch of API cleanup, methods not used yet become private for now. Most importantly I added the invoice to the receive operation meta and provided a method to calculate the fees paid to the gateway from the meta.
=> cleanup: cleanup lnv2 module client api

devimint/src/external.rs
I've seen CI fail a few times due to this poll timing out, causing flakiness. Let's bump it.
For an example of this failure, see [this CI run](https://github.com/fedimint/fedimint/actions/runs/10926024375/job/30328929384) from #6035
=> chore: bump devimint channel open timeout

nix/modules/fedimintd.nix
This change is made to address deprecation warnings in the fedimint service logs. The environment variables `FM_BITCOIN_RPC_URL` and `FM_BITCOIN_RPC_KIND` are now considered obsolete, and having only these variables causes the following warnings:
```
2024-09-19T17:44:17.136580Z  WARN fm::core: FM_BITCOIN_RPC_KIND is obsolete, use FM_DEFAULT_BITCOIND_RPC_KIND instead
2024-09-19T17:44:17.136588Z  WARN fm::core: FM_BITCOIN_RPC_URL is obsolete, use FM_DEFAULT_BITCOIND_RPC_URL instead
```
To avoid these warnings, the corresponding environment variables with the `DEFAULT` prefix (`FM_DEFAULT_BITCOIND_RPC_URL` and `FM_DEFAULT_BITCOIND_RPC_KIND`) are added in the NixOS module, while keeping the deprecated ones for backward compatibility.
Ref: …
=> chore: add default BTC RPC env vars in NixOS module

fedimint-client/src/api_announcements.rs
It's highly likely this query will sometimes fail.
We are seeing flakes caused by it in the CI. Eg.:
https://github.com/fedimint/fedimint/actions/runs/10964718284/job/30448946223?pr=6054
=> chore(client): retry getting api announcements from a single peer

fedimint-server/src/consensus/aleph_bft/backup.rs, fedimint-server/src/consensus/engine.rs
Partially reverting beb5892f0fb7ac485fe47b9b5091ecd9bda2dda8 .
This query performance is not as good as we would hope.
Re #6050
=> fix(consensus): cache unit count in `BackupWriter`

fedimint-testing/src/btc/mock.rs, fedimint-testing/src/btc/mod.rs, fedimint-testing/src/btc/real.rs, modules/fedimint-wallet-client/src/api.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-common/src/endpoint_constants.rs, modules/fedimint-wallet-common/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
This introduces a `WalletSummary`, which is a snapshot of the wallet's coins that are spendable and in-flight.
Consuming this new endpoint is interesting in a vacuum, however it becomes significantly more useful when consumed with a tool like `fedimint-observer`, since it allows us to have a view of the wallet's coins as reported from peer databases. We can compare the `WalletSummary` to the UTXO set constructed from scraping the session outcomes to detect inconsistencies. Historically this would have come in handy while investigating wallet bugs.
One approach we've discussed to solve https://github.com/fedimint/fedimint/issues/3802 is to compare the mint's reported coins against the UTXO set from a different bitcoin backend to detect spends constructed outside of the wallet.
Since we …
=> feat(wallet): add wallet summary

fedimint-testing/src/ln.rs
Just some tidying up
Most notably, OpenAI o1 noticed that `FakeLightningTest.receiver` isn't really used anywhere. I went ahead and inlined it in `route_htlcs()` and documented its purpose.
=> chore: cleanup FakeLightningTest

gateway/ln-gateway/src/client.rs, gateway/ln-gateway/src/error.rs, gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/mod.rs, gateway/ln-gateway/src/rpc/rpc_server.rs
See https://github.com/fedimint/fedimint/pull/5923#issuecomment-2327284866 for additional context.
This PR refactors how we handle errors in the gateway. Previously, we just had a `GatewayError` type where we dumped all of our error types. Most of these would be redacted before returning to the client, which kind of defeats the purpose of using typed errors.
This PR adds two error types: `PublicGatewayError` and `AdminGatewayError`. `AdminGatewayError` error messages and full details are always returned to the client. The intention is that this error type is used for authenticated endpoints only. Unauthenticated endpoints, such as what is used in LNv1 and LNv2, should use `PublicGatewayError`, which has the specific details of the error redacted for privacy reasons.
Both error types …
=> refactor: gateway error refactor

fedimint-client/src/module/init/recovery.rs, fedimint-client/src/module/mod.rs, fedimint-core/src/db/mod.rs, gateway/ln-gateway/src/state_machine/mod.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-mint-client/src/backup.rs, modules/fedimint-mint-client/src/backup/recovery.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-wallet-client/src/backup.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-client/src/pegin_monitor.rs
It has been rendered redudndant, by the built-in DBTx global_tx.
=> refactor: get rid of ClientDbTxContext

gateway/ln-gateway/src/lib.rs
gets rid of clippy warning, drops at end of scope so don't borrow
=> fix: clippy warning lightning_context

.github/workflows/ci-nix.yml, flake.nix, nix/flakebox.nix, nix/overlays/trustedcoin.nix, nix/pkgs/trustedcoin.nix
* Uses trustedcoin as its BTC backend
* Ships with the gateway plugin
Makes setting up gateways easier since there's no need to wait for chain sync. Caveats: 
* Depends on 3rd party APIs that might become malicious or go offline.
* Only expose the CLN gateway plugin port (`3301`) to the gateway container and **never publicly**, it's unauthenticated and gives node access.
Fixes #6088.
Try it this way:
```
$ nix build .#container.cln-light-gateway
$ docker load < result 
006b2621cc78: Loading layer [==================================================>]  325.8MB/325.8MB
…
62a910d016c0: Loading layer [==================================================>]  440.3kB/440.3kB
Loaded image: cln-light-gateway:0ryra1zr5hl111xvg4hca9n1ii65w40b
$ docker run -it --rm -p 9735:9735 -p 3301:3301 -e …
```
=> feat: add lightweight CLN container

gateway/ln-gateway/build.rs
Fixes a warning that must have been introduced with a recent version bump.
=> fix: fix gateway protoc warning

modules/fedimint-mint-client/src/backup/recovery.rs, modules/fedimint-mint-client/src/client_db.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-tests/tests/tests.rs
=> chore(client): during recovery detect burned ecash due to nonce reuse (backport to v0.4)

gateway/integration_tests/src/main.rs, gateway/ln-gateway/src/client.rs
We have a bug in the DB implementation of the gateway. Previously, we used the `federation_index` as the prefix for the database. However, this has an issue because the `federation_index` changes when the user leaves and then rejoins the federation.
This PR changes it so that when building the client, we use the federation id instead (which should not change). It turns out that [RocksDB does delta encoding, so common prefixes will not be stored redundantly](https://docs.rockset.com/documentation/docs/storage-architecture#data-compaction-in-rocksdb). So storage size shouldn't be a concern.
=> fix: use federation id for database prefix

fedimintd/src/lib.rs
=> fix: default esplora address for signet network shouldn't be mutinynet

Cargo.lock, Cargo.toml, crypto/derive-secret/Cargo.toml, crypto/derive-secret/src/lib.rs, fedimint-core/Cargo.toml, fedimint-core/src/backup.rs, fedimint-core/src/core/backup.rs, fedimint-core/src/encoding/secp256k1.rs, fedimint-core/src/module/mod.rs, fedimint-core/src/transaction.rs, modules/fedimint-mint-client/Cargo.toml, modules/fedimint-mint-client/src/backup/recovery.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-client/src/output.rs, modules/fedimint-mint-common/Cargo.toml, modules/fedimint-mint-common/src/common.rs, modules/fedimint-mint-common/src/lib.rs, modules/fedimint-mint-server/Cargo.toml, modules/fedimint-mint-server/src/db.rs, modules/fedimint-mint-server/src/lib.rs
We're not using any functionality from `secp256k1-zkp` that isn't simply re-exported from `secp256k1`.
=> chore(deps): remove secp256k1-zkp

Cargo.lock, fedimint-core/Cargo.toml
We've bumped this dependency several times since adding this warning. I think we should just remove the warning.
@maan2003
=> chore: remove backon upgrade warning

Cargo.lock, fedimint-bip39/src/lib.rs, fedimint-cli/Cargo.toml, fedimint-cli/src/client.rs, fedimint-cli/src/lib.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/client.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/ldk.rs, gateway/ln-gateway/src/lightning/mod.rs
Both crates that rely on the `bip39` crate also rely on `fedimint-bip39`. Let's just re-export what we need from `bip39` from `fedimint-bip39`.
=> chore: re-export bip39 types from fedimint-bip39

Cargo.toml, fedimint-api-client/src/api/peer.rs
While working on #6151 I've noticed that the duration of initial calls is suspiciously long.
Turns out we are always adding a delay on connecting, even the first time.
=> fix(client): always adding retry delay, even on first connection

Cargo.lock, Cargo.toml, deny.toml, fedimint-api-client/Cargo.toml, fedimint-cli/Cargo.toml, fedimint-core/Cargo.toml, fedimint-load-test-tool/Cargo.toml, fedimint-server/Cargo.toml, gateway/cli/Cargo.toml
Replaces #6161 by adding the zlib license. See https://github.com/fedimint/fedimint/pull/6161#issuecomment-2408700262
=> chore(deps): bump the patch group with 12 updates

.github/workflows/ci-nix.yml, devimint/src/bin/devimint-faucet.rs, devimint/src/tests.rs, devimint/src/util.rs
Rename `faucet` to `devimint-faucet`, as it is part of the `devimint` build itself so people installing it in dev shells will get it as well.
This should also pin all tagged releases of devimint (like all existing packages), as required in #6167.
=> chore: release devimint package

devimint/src/devfed.rs
The `gw_ldk` defined above already performs a fedimintd version check, and returns `None` if it's older than 0.4.0, so performing a version check and the `if let Some(gw_ldk) = gw_ldk` check is redundant.
=> chore: remove duplicate version check for ldk gw

modules/fedimint-wallet-client/src/pegin_monitor.rs
Currently, if the user creates a deposit address, and then decides to make a peg-in after a week, they might wait 3.5 day for the client to notice.
Ultimately end-user apps needs to expose ability to check for deposits on demand (click a button or something), but irrespective of that, checking a 7 day old address arond once a day seems reasonable.
=> chore(client): check peg-in addresses with no deposits more often

devimint/src/cfg/lightningd.conf, gateway/ln-gateway/src/bin/cln_extension.rs, nix/overlays/clightning.nix
Bumping core lightning beyond v23.05.2 causes it to fail in devimint on MacOS due to this known issue:
Fixes #6193
=> fix: revert cln version bump

devimint/src/gatewayd.rs, gateway/ln-gateway/src/lightning/ldk.rs
This reverts commit 1cfa530153837397cfc9cee003d2fa03cb6d0898.
I have a suspicion this is what is causing CI flakiness.
=> Revert "fix: GatewayLdkClient::info() doesn't rely on timestamps"

fedimint-client/src/lib.rs, fedimint-client/src/module/mod.rs, fedimint-client/src/sm/state.rs, fedimint-client/src/transaction/builder.rs, gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs, gateway/ln-gateway/src/gateway_module_v2/send_sm.rs, gateway/ln-gateway/src/state_machine/pay.rs, gateway/ln-gateway/tests/tests.rs, modules/fedimint-dummy-client/src/lib.rs, modules/fedimint-dummy-tests/tests/tests.rs, modules/fedimint-ln-client/src/incoming.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-ln-client/src/pay.rs, modules/fedimint-ln-client/src/receive.rs, modules/fedimint-lnv2-client/src/receive_sm.rs, modules/fedimint-lnv2-client/src/send_sm.rs, modules/fedimint-lnv2-tests/tests/tests.rs, modules/fedimint-mint-client/src/input.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-client/src/oob.rs, modules/fedimint-mint-tests/tests/tests.rs, modules/fedimint-wallet-client/src/deposit.rs, modules/fedimint-wallet-client/src/pegin_monitor.rs
This will allow more efficient use of state machines in the client and enable e.g. #6176
=> refactor(client): decouple inputs and their state machines

Cargo.lock, fedimint-api-client/src/api/global_api.rs, fedimint-api-client/src/api/mod.rs, fedimint-client/Cargo.toml, fedimint-client/src/api.rs, fedimint-client/src/db/event_log.rs, fedimint-client/src/lib.rs
The volume of api calls is relatively low, so it seems perfectly reasonable to add corresponding events to the client side event log.
For privacy and to keep the event log lean, the request and response bodies itself are not logged.
This should allow:
* end user applications to detect and show in the UI networking errors, or problems with federation peers, including average response times, and other diagnostics
* improve ability to debug issues
* write tests that need to verify api calls
=> chore(client): add api call events

devimint/src/federation.rs, devimint/src/tests.rs, gateway/integration_tests/src/main.rs, modules/fedimint-lnv2-tests/src/bin/tests.rs
We often want to pegin to all gateways at the same time. Currently this leads to blocks being mined for each pegin. This isn't necessary, we can do all pegin transactions then mine the block and wait for the balance in parallel.
=> chore: devimint batch gateway pegins

docs/release-process.md
We've established a convention of prepending `v` to our version tags. Reflecting that in the release docs is more clear.
=> docs: prepend 'v' for tags

fedimint-load-test-tool/src/common.rs, fedimint-wasm-tests/src/lib.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-tests/tests/tests.rs
The default behavior of `spend_ecash` is a foot-gun: if no notes of the correct denominatons are available it will return the next bigger note without regard for the amount over-spent. This was ok for expert integrators, but is a massive foot-gun for people less familiar with the code base.
This PR makes `spend_ecash` fail if the exact amount cannot be provided and introduces a new `spend_ecash_expert` function that can be used by people relying on the old behavior.
This is mostly relevant to the Web SDK, but also the CLI. cc @maan2003 @alexlwn123
=> fix: make `spend_ecash` not overspend by default

devimint/src/federation/config.rs, fedimint-core/src/fee_consensus.rs, fedimint-core/src/lib.rs, fedimintd/src/fedimintd.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-common/src/config.rs
Move the FeeConsensus into fedimint-core such that it may be reused across all v2 modules.
=> refactor: move the FeeConsensus into fedimint-core

Cargo.lock, Cargo.toml, devimint/Cargo.toml, devimint/src/external.rs, devimint/src/tests.rs, fedimint-core/Cargo.toml, fedimint-core/src/bitcoin_migration.rs, fedimint-core/src/encoding/btc.rs, fedimint-core/src/encoding/mod.rs, fedimint-core/src/txoproof.rs, fedimint-recoverytool/src/main.rs, modules/fedimint-wallet-client/Cargo.toml, modules/fedimint-wallet-client/src/backup.rs, modules/fedimint-wallet-client/src/backup/recovery_history_tracker.rs, modules/fedimint-wallet-client/src/client_db.rs, modules/fedimint-wallet-client/src/deposit.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-client/src/pegin_monitor.rs, modules/fedimint-wallet-common/src/lib.rs, modules/fedimint-wallet-common/src/txoproof.rs, modules/fedimint-wallet-server/src/db.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/src/bin/circular-deposit-test.rs, modules/fedimint-wallet-tests/tests/tests.rs
Part of #5200
The primary changes are in `fedimint-core/src/encoding/btc.rs`. The rest of the diffs in this PR are downstream changes.
=> chore(deps): bump bridge-encoded bitcoin structs to v0.32

fedimint-client/src/lib.rs, fedimint-client/src/module/mod.rs, fedimint-client/src/transaction/builder.rs, fedimint-load-test-tool/src/common.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, gateway/ln-gateway/src/state_machine/mod.rs, gateway/ln-gateway/src/state_machine/pay.rs, gateway/ln-gateway/tests/tests.rs, modules/fedimint-dummy-client/src/lib.rs, modules/fedimint-dummy-tests/tests/tests.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-wallet-client/src/lib.rs
This is like https://github.com/fedimint/fedimint/pull/6207, but for outputs.
=> refactor(client): decouple outputs and their state machines

gateway/ln-gateway/src/lib.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-tests/tests/mock.rs
We remove the parameters from PaymentFeeExceedsLimit, ExpirationDeltaExceedsLimit and PaymentFeeExceedsLimit as they are not actionable, with the current implementation that is just considered invalid by the client and three no mechanism to accept them anyway.
=> chore: improve documentation of fees

fedimint-client/src/lib.rs, fedimint-client/src/sm/executor.rs, fedimint-wasm-tests/src/lib.rs
```
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:33 thread 'sends_ecash_out_of_band' panicked at fedimint-client/src/sm/executor.rs:814:14:
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:33 Only locked during startup, no collisions should be possible: TryLockError(())
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:33 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
https://github.com/fedimint/fedimint/actions/runs/11634629737/job/32402260832?pr=6264
There seem to be no reason to have an async lock there, all the locking is wrapping only non-blocking/non-async operations anyway.
=> fix(client): panic on executor lock

fedimint-server/src/config/api.rs, fedimint-server/src/lib.rs
If the file was created/modified manually, the text editor will likely add an extra newline.
=> fix: remove leading and trailing newlines from password

fedimint-server/src/config/api.rs, fedimint-server/src/lib.rs
Backport of #6253 to `releases/v0.4`.
=> [Backport releases/v0.4] fix: remove leading and trailing newlines from password

devimint/src/federation/config.rs
Fixes https://github.com/fedimint/fedimint/issues/6281
When we introduced relative fees in the mint module, we changed the field names of `FeeConsensus`. This caused upgrade tests to fail calling `fedimint-cli admin dkg` using a v0.5.0 client against older `fedimintd` versions since the payload is json encoded. This PR preserves the old `FeeConsensus` to allow devimint to run dkg for older versions of `fedimintd`.
Successful upgrade tests in [CI](https://github.com/fedimint/fedimint/actions/runs/11698976088/job/32580164401?pr=6290).
=> fix(devimint): add LegacyFeeConsensus to support upgrade tests

fedimint-client/src/sm/executor.rs, fedimint-core/src/db/mod.rs, modules/fedimint-dummy-client/src/db.rs, modules/fedimint-mint-client/src/client_db.rs, modules/fedimint-mint-client/src/input.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-client/src/oob.rs, modules/fedimint-mint-tests/tests/tests.rs
Fix #5069
Alternative to #5833
Instead of trying to reclaim every spendable note from oob spend, reclaim them all in one tx.
This requires first a refactoring commit that breaks the 1:1 input to sm relationship. Now multiple inputs can generate a single state machine that will reclaim them all.
One behavior change is that the new tx will fail or succeed together. But if the destination user claimed one note, is it still a reasonable thing to do to reclaim other ones? I don't think so.
=>  chore: claim oob refunds with a single state machine 

fedimint-server/src/net/connect.rs
=> fix: use default port for p2p connections if none was specified

fedimint-server/src/net/connect.rs
Backport of #6292 to `releases/v0.4`.
=> [Backport releases/v0.4] fix: use default port for p2p connections if none was specified

devimint/src/external.rs, modules/fedimint-ln-client/src/lib.rs
Fixes: https://github.com/fedimint/fedimint/issues/6241
Adds LNv1's timelock constant to the invoice's `min_cltv_delta`. 
@joschisan should we do this for LNv2 as well? We would be able to decrease the total locktime that the user's ecash would be stuck if a gateway should disappear, which I think would be a UX improvement.
=> fix: LNv1 add min_cltv_delta to timelock constant

Cargo.lock, Cargo.toml, devimint/src/external.rs, fedimint-core/src/bitcoin_migration.rs, gateway/ln-gateway/src/bin/cln_extension.rs
Part of #5200
Bumping `cln-rpc` to a fedimint release so that we can remove `bitcoin` v0.30
=> chore(deps): bump cln-rpc to internal version that uses bitcoin v0.32

fedimint-cli/src/client.rs, fedimint-load-test-tool/src/common.rs, modules/fedimint-mint-client/src/lib.rs
=> chore(mint-client): deprecate redundant `get_notes_tier_counts` function

devimint/src/util.rs, fedimint-logging/src/lib.rs, gateway/ln-gateway/src/lightning/ldk.rs
On my machine this takes startup time from 26s to 16s, which is a huge win. Enough to justify this hackery.
This translate in the CI to change from:
to:
=>  chore(ci): speed up devimint startup 

gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs
It is useful to have when managing multiple federations in a gateway.
=> chore: include federation name in `FederationInfo`

Cargo.lock
Part of #6293
De-dupes the `miniz_oxide` dependency
=> chore(deps): bump flate2 to v1.0.34

Cargo.lock, modules/fedimint-meta-client/src/cli.rs, modules/fedimint-meta-common/Cargo.toml, modules/fedimint-meta-common/src/lib.rs
@dpc did I miss any places where I should use the lenient decoding?
=> fix: allow lenient parsing of meta values if their encoding is broken

fedimint-core/src/encoding/btc.rs, fedimint-core/src/encoding/mod.rs, gateway/ln-gateway/src/lib.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-common/src/config.rs, modules/fedimint-lnv2-server/src/lib.rs
Encode magic bytes directly instead of as u32 which was a historical accident.
Will also be done with walletv2. We can then retire the old encoding eventually with lnv1 and walletv1.
=> cleanup: sane network encoding for lnv2

fedimint-core/src/util/backoff_util.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
We observed issues with a public federation that had peers with a bitcoin backend that was unable to stay at tip, with some that went two months without contributing a block count vote. Instead of allowing the peers to keep progressing and contributing other consensus items, this change introduces a graceful shutdown if we haven't observed a block that other peers have seen `finality_delay` confirmations.
I'm opening as a draft since I'm still chewing on the implications of these changes. Please flag any concerns with this approach cc: @elsirion @dpc @joschisan
=> chore(wallet): shutdown fedimintd if bitcoin backend is stale

docs/release-process.md
The steps for creating a new `release/v*` branch benefits from elaborating the steps.
=> docs: clarify release process for new release branches

Cargo.lock, Cargo.toml, fedimint-cli/Cargo.toml, fedimint-client/Cargo.toml, fedimint-testing/Cargo.toml, gateway/cli/Cargo.toml, gateway/ln-gateway/Cargo.toml, modules/fedimint-wallet-client/Cargo.toml
As discussed on the deep dive call today, we can bump the version on master once we create the `releases/v*` branch. The release process docs are now updated to capture when we should do this step, see: https://github.com/fedimint/fedimint/pull/6356
=> chore: bump master to 0.6.0-alpha

docs/release-process.md
Once we create a new `releases/v*` branch off of `master`, we can then bump the `*-alpha` version on `master`. This PR updates the release process docs to add a step to bump the version.
=> docs: update release process to bump master *-alpha version

fedimint-server/src/net/peers.rs
Backport of #6339 to `releases/v0.4`.
=> [Backport releases/v0.4] fix(net): flood of log messages on disconnected peer

fedimint-core/src/encoding/btc.rs, fedimint-recoverytool/src/main.rs, gateway/ln-gateway/src/db.rs, gateway/ln-gateway/src/lib.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-ln-common/src/config.rs, modules/fedimint-ln-server/src/lib.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-common/src/config.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-common/src/config.rs, modules/fedimint-wallet-common/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
Follow-up to #6336
Makes the default encoding for `bitcoin::Network` byte-encoded instead of int-encoded to prevent accidental use of the old encoding
To ensure safe conversion, this PR is split into two commits. One commit removes `bitcoin::Network` en/decoding and replaces it with a `NetworkLegacyEncodingWrapper`, and a second commit removes `NetworkSaneEncodingWrapper` and replaces it with `bitcoin::Network` en/decoding.
=> chore: swap NetworkSaneEncodingWrapper for Legacy

modules/fedimint-mint-client/src/client_db.rs, modules/fedimint-mint-client/src/input.rs, modules/fedimint-mint-client/src/oob.rs, modules/fedimint-mint-client/src/output.rs
Fixes https://github.com/fedimint/fedimint/issues/6338
This only fixes one failure of upgrade tests. Since `master` and `releases/v0.5` are still broken after including this fix, I haven't kicked off a run in CI, only local tests. To verify locally against these changes, first checkout the commit that introduced this failure and run upgrade tests for `fedimint-cli`
```
git checkout 8d156fd39049203fc134c2debe99e1182c3a6d60
TEST_KINDS=fedimint-cli just test-upgrades v0.4.0 current &> results.log
```
Expected failure message
```
Error: command: fedimint-cli --data-dir=/tmp/nix-shell.lh5Zqz/devimint-2050963-520/clients/reissue-client-0 deposit-address
Caused by:
exit status: 1
stdout:
{
"error": "Decoding named block MintOOBStateMachineV1 {} state"
}
```
After applying the changes in this PR, …
=> fix: mint client state machine migration

modules/fedimint-mint-client/src/client_db.rs, modules/fedimint-mint-client/src/input.rs, modules/fedimint-mint-client/src/oob.rs, modules/fedimint-mint-client/src/output.rs
Backport of #6359 to `releases/v0.5`.
=> [Backport releases/v0.5] fix: mint client state machine migration

fedimint-core/src/db/mod.rs, fedimint-core/src/encoding/btc.rs, fedimint-core/src/encoding/mod.rs, fedimint-core/src/invite_code.rs, fedimint-core/src/net/api_announcement.rs, fedimint-core/src/txoproof.rs, fedimint-dbtool/src/dump.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, modules/fedimint-dummy-tests/tests/tests.rs, modules/fedimint-ln-client/src/db.rs, modules/fedimint-ln-tests/tests/tests.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs
[`fedimint-core::Encodable::consensus_encode()`](https://github.com/fedimint/fedimint/blob/02bf690a8bb198d678b98e31112260185ea1b211/fedimint-core/src/encoding/mod.rs#L85-L89) returns a `Result<usize, std::io::Error>` because [`std::io::Write::write()`](https://doc.rust-lang.org/nightly/std/io/trait.Write.html#tymethod.write) returns the same type. However, since the implementation of `std::io::Write::write()` for `Vec<u8>` [never returns an error](https://doc.rust-lang.org/src/std/io/impls.rs.html#409-413), we have a helper function [`fedimint-core::Encodable::consensus_encode_to_vec()`](https://github.com/fedimint/fedimint/blob/02bf690a8bb198d678b98e31112260185ea1b211/fedimint-core/src/encoding/mod.rs#L91-L97) which safely unwraps the value. In this PR, we replace calls to …
=> chore: replace consensus_encode() with consensus_encode_to_vec()

modules/fedimint-mint-client/src/lib.rs
Backport of #6377 to `releases/v0.5`.
=> [Backport releases/v0.5] fix: outputs might be empoty due to fees

devimint/src/external.rs
The new comment specifies v0.4.0-alpha because the only usage of `open_channel()` is here:
https://github.com/fedimint/fedimint/blob/8ccfee352f967956a8951c1c59bdcbad2150929e/devimint/src/devfed.rs#L270-L277
=> chore: correct TODOs to remove old devimint block processing

gateway/ln-gateway/src/lightning/ldk.rs
Fixes #5965
I've tested mprocs startup speed several times locally and this change doesn't affect it at all now that we're syncing the ldk gateway wallet in the background (#6315)
=> chore: remove EsploraSyncConfig from ldk gateway

Cargo.lock, Cargo.toml, fedimint-cli/Cargo.toml, fedimint-cli/src/main.rs, fedimintd/Cargo.toml, fedimintd/src/bin/main.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/bin/gatewayd.rs
Backport of #6357 to `releases/v0.5`.
=> [Backport releases/v0.5] chore: switch to using jemalloc on all major binaries.

fedimint-core/src/module/version.rs, fedimint-server/src/consensus/api.rs, fedimint-server/src/consensus/engine.rs, fedimint-server/src/consensus/transaction.rs, modules/fedimint-mint-tests/tests/tests.rs
The 0.5.0 mint  client supports non-zero absolute and relative fees for inputs and outputs if it is allowed to slightly overfund transactions. Since only new federations can set non-zero fees anyways it is sufficient to only enable this in new deployments.
=> Allow overpayment of fees

fedimint-core/src/util/backoff_util.rs, modules/fedimint-wallet-server/src/lib.rs
Followup to address feedback https://github.com/fedimint/fedimint/pull/5981#discussion_r1832538656
> nit: I'd prefer a Fibonacci backoff with 10s max to reduce expected latency.
=> chore: use fibonacci backoff for waiting for finality delay confs

fedimint-core/src/encoding/btc.rs, fedimint-core/src/encoding/mod.rs
Move implementations of `Encodable` and `Decodable` for types in the `lightning` crate to be alongside types from the `bitcoin` crate. This allows us to also move `SimpleBitcoinRead` and `BufBitcoinReader` and make them private. Also move scattered tests for bitcoin impls to be alongside their prod code.
=> chore: move lightning en/decodable impls to btc.rs

Cargo.lock, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/lightning/ldk.rs
Makes `GatewayLdkClient::pay()` idempotent even when called simultaneously by multiple threads.
To achieve single-threaded idempotency, we do two things:
* Use the invoice's payment hash as the payment ID
* Skip initiating a payment with the underlying `ldk-node::Node` instance if it has already saved a payment with the given payment ID, indicating that it has already initiated a payment attempt for a given invoice
To achieve multi-threaded idempotency, we use a [`lockable::LockPool`](https://docs.rs/lockable/0.1.1/lockable/struct.LockPool.html) to lock by payment hash for the entire duration of a call to `GatewayLdkClient::pay()`. This should have almost no performance impact, since as soon as the first call completes and returns, subsequent calls simply need to grab the lock, lookup the …
=> fix: make ldk pay implementation idempotent

devimint/src/tests.rs
Locally I'm running test suite in a loop with `cpulimit`, trying to trigger and debug any flakiness, and this is one of the few things I'm still able to hit.
=> fix: flaky latency test due to low arbitrary limits

fedimint-cli/src/client.rs, fedimint-core/src/amount.rs, fedimint-load-test-tool/src/main.rs, gateway/ln-gateway/src/gateway_module_v2/send_sm.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/state_machine/pay.rs, gateway/ln-gateway/tests/tests.rs, modules/fedimint-dummy-client/src/lib.rs, modules/fedimint-dummy-server/src/lib.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-tests/tests/tests.rs
Remove implementation of `std::ops::Sub` for `Amount`, requiring the usage of `Amount::saturating_sub()` or `Amount::checked_sub()` instead
=> chore: require saturating or checked subtraction for Amount

devimint/src/external.rs, devimint/src/vars.rs
`:0` is not a safe way to allocate any ports.
=> fix(ci): flaky esplora port allocation

Cargo.lock, fedimint-eventlog/src/lib.rs, gateway/cli/Cargo.toml, gateway/cli/src/general_commands.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/events.rs, gateway/ln-gateway/src/gateway_module_v2/complete_sm.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs, gateway/ln-gateway/src/gateway_module_v2/send_sm.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, gateway/ln-gateway/tests/tests.rs
Re-uses @dpc's client log for a "gateway transaction log".
Adds five LNv2 events `OutgoingPaymentStarted`, `OutgoingPaymentSucceeded`, `IncomingPaymentStarted`, `IncomingPaymentSucceeded`, and `CompleteLightningPaymentSucceeded`. Can tackle failure events in a follow up.
Also adds a `/payment_log` endpoint that allows querying for these events. The API contains very basic predicate filtering based on `FederationId` and `EventKind`, but I suspect the proper way to use this API will be to periodically query the data from an ETL task, insert it into a SQL database, and then execute more interesting queries there (e.g group by weekly, swaps vs LN, etc).
The added LNv2 events contain information required to compute fees, latency, and other payment information. Looking for feedback if there's …
=> feat: Gateway Transaction Log

flake.nix
Backport of #6407 to `releases/v0.5`.
=> [Backport releases/v0.5] fix(ci): some bundlers we use expect a missing `pname`

nix/flakebox.nix
Backport of #6409 to `releases/v0.5`.
=> [Backport releases/v0.5] fix(ci): missing `devimint-faucet` output

fedimint-load-test-tool/src/common.rs, fedimint-load-test-tool/src/main.rs
If no invite code is given to the load test tool, then it tries to get one from the command-line in a best-effort basis. It was broken because we don't have tests for it (and not sure if we need, it's not a critical feature).
=> fix: correctly get invite-code on load-test-tool

flake.nix
The dev shell for this architecture seems broken anyway, which prevents flake evaluation. No harm in deactivating the shell till someone actually wants to develop fedimint with cross-compilation on ARM Linux.
Fixes #6428
=> fix: deactivate cross compile dev shell for aarch64-linux

gateway/ln-gateway/src/events.rs, gateway/ln-gateway/src/gateway_module_v2/complete_sm.rs, gateway/ln-gateway/src/gateway_module_v2/events.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs, gateway/ln-gateway/src/gateway_module_v2/send_sm.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/tests/tests.rs
Moves existing gateway events into LNv2 module, they won't be re-usable for LNv1.
Adds failure events for outgoing and incoming payments.
=> feat: add LNv2 failure events

fedimint-client/src/db.rs, fedimint-core/src/core.rs, fedimint-dbtool/src/dump.rs
very helpful for debugging, hex is annoying
hit bunch of decoder issues when logging active and inactive state machines, for some other time
=> dbtool: add dump for operation log and client config

fedimint-bitcoind/src/bitcoincore.rs, fedimint-bitcoind/src/electrum.rs, fedimint-bitcoind/src/esplora.rs, fedimint-bitcoind/src/lib.rs, fedimint-server/src/config/api.rs, fedimint-testing/src/btc/mock.rs, fedimint-testing/src/fixtures.rs, modules/fedimint-ln-server/src/lib.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-wallet-client/src/backup.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs
I recommend reviewing commit-by-commit
The biggest change here is the removal of the `RetryClient`. Its purpose is to wrap the [`IBitcoindRpc`](https://github.com/fedimint/fedimint/blob/330c0a3168b68b32c4458cce296ca4553b00439c/fedimint-bitcoind/src/lib.rs#L107-L187) trait to ensure automatic retrying of RPCs if the underlying chain info source is unreachable. However, since it retries indefinitely until success or daemon shutdown, an unreachable chain info source can lead to undesired behavior. For example, [this](https://github.com/fedimint/fedimint/blob/330c0a3168b68b32c4458cce296ca4553b00439c/fedimint-server/src/config/api.rs#L935-L942) endpoint will hang if the esplora node is offline since it calls [this](https://github.com/fedimint/fedimint/blob/330c0a3168b68b32c4458cce296ca4553b0043 …
=> chore: fedimint-bitcoind cleanup

modules/fedimint-mint-client/src/backup/recovery.rs, modules/fedimint-mint-client/src/client_db.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-client/src/output.rs, modules/fedimint-mint-tests/tests/tests.rs
Backport of #6458 to `releases/v0.5`.
=> [Backport releases/v0.5] chore(recovery): save reused note indices

gateway/ln-gateway/src/bin/gatewayd.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/rpc_server.rs
There are several methods on the `Gateway` struct that currently require a `TaskGroup` argument. In practice the same task group is always used when calling all of these methods, so let's have the `Gateway` hold it as a struct field to make the purpose/ownership more clear.
=> refactor: gateway owns its task group

fedimint-core/src/encoding/collections.rs, fedimint-core/src/encoding/mod.rs
Also beef up our testing of these impls
=> refactor: move collection en/decodable impls to separate file

fedimint-bitcoind/src/bitcoincore.rs, fedimint-bitcoind/src/esplora.rs, fedimint-bitcoind/src/lib.rs, fedimint-server/src/config/api.rs, fedimint-testing/src/btc/mock.rs
Change the return type of `check_bitcoin_status` from an enum containing info on whether the bitcoin backend is synced to a struct containing the latest block height, block time, and optional sync percentage estimate. This allows for consistent behavior for different bitcoin backends.
We're able to change the return type of this endpoint since it is only used by the guardian UI, and we require that the UI and guardian are upgraded in lockstep. In the UI, we will need to compare the block height and block time to the consensus block height and local system time in order to determine whether the guardian's bitcoin backend is stalled.
=> feature: repurpose bitcoin status endpoint

fedimint-core/src/encoding/btc.rs, fedimint-core/src/encoding/mod.rs
`CountWrite` is only used in the btc module, let's move it there and make it private
=> chore: move CountWrite into btc encoding module

Cargo.lock, Cargo.toml, fedimint-cli/Cargo.toml, fedimint-cli/src/main.rs, fedimint-rocksdb/Cargo.toml, fedimintd/Cargo.toml, fedimintd/src/bin/main.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/bin/gatewayd.rs
It needs to be done via Cargo feature flag.
Switch to recommended version of tikv-jemallocator:
https://crates.io/crates/jemallocator:
> The project is also published as jemallocator for historical reasons. The two crates are the same except names. For new projects, it's recommended to use tikv-xxx versions instead.
=> chore: enable jemalloc on rocksdb itself

Cargo.lock, gateway/ln-gateway/src/events.rs, modules/fedimint-mint-client/src/event.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-wallet-client/Cargo.toml, modules/fedimint-wallet-client/src/deposit.rs, modules/fedimint-wallet-client/src/events.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-client/src/pegin_monitor.rs, modules/fedimint-wallet-client/src/withdraw.rs
Adds events to the event log for when ecash notes are spent OOB and when an onchain deposit or withdraw happens. Will be useful for the gateway's payment log to see when non-lightning transactions happen.
=> feat: add OOB Spend/Receive and Wallet Deposit/Withdraw events

Cargo.lock, Cargo.toml, fedimint-cli/Cargo.toml, fedimint-cli/src/main.rs, fedimint-rocksdb/Cargo.toml, fedimintd/Cargo.toml, fedimintd/src/bin/main.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/bin/gatewayd.rs
Backport #6488 
It needs to be done via Cargo feature flag.
Switch to recommended version of tikv-jemallocator:
https://crates.io/crates/jemallocator:
> The project is also published as jemallocator for historical reasons. The two crates are the same except names. For new projects, it's recommended to use tikv-xxx versions instead.
=> chore: enable jemalloc on rocksdb itself (v0.5 backport)

Cargo.lock, Cargo.toml, fedimint-cli/Cargo.toml, fedimint-cli/src/main.rs, fedimint-rocksdb/Cargo.toml, fedimintd/Cargo.toml, fedimintd/src/bin/main.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/bin/gatewayd.rs
Backport #6488 
It needs to be done via Cargo feature flag.
Switch to recommended version of tikv-jemallocator:
https://crates.io/crates/jemallocator:
> The project is also published as jemallocator for historical reasons. The two crates are the same except names. For new projects, it's recommended to use tikv-xxx versions instead.
=> chore: enable jemalloc on rocksdb itself (backport v0.4)

fedimint-client/src/oplog.rs
Likely related to flakiness reported in #6502, although I don't know how this *ever* worked the way it was :exploding_head:
=> feat: fix missing loop break label

fedimint-server/src/config/mod.rs
Backport of #6501 to `releases/v0.5`.
=> [Backport releases/v0.5] fix(server): typo in log statement

flake.nix
`just mprocs` isn't booting for me without it.
=> fix: add mprocs after nixpkgs 24.11

.cargo/audit.toml
=> fix: ignore RUSTSEC-2024-0402 which we don't care about

Cargo.lock, Cargo.toml, devimint/src/gatewayd.rs, devimint/src/vars.rs, fedimint-testing/Cargo.toml, fedimint-testing/src/fixtures.rs, gateway/cli/src/general_commands.rs, gateway/integration_tests/src/main.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/config.rs, gateway/ln-gateway/src/db.rs, gateway/ln-gateway/src/envs.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, gateway/ln-gateway/tests/tests.rs
Fixes #6427
Previously, the gateway stored its password in its DB and required that a password be provided via an environment variable or CLI argument on first-time startup, after which any provided password was ignored. In this PR, we remove the password from the gateway DB and require that a bcrypt password hash be provided on _every_ startup (either through an environment variable or a CLI argument).
This allows several downstream changes, including:
* Removing `GatewayState::Configuring` since all it was waiting on was for a password to be set, whereas now an unset bcrypt password hash will cause the gateway to panic and exit.
* Merging `GatewayState::Initializing` into `GatewayState::Disconnected` since without the `Configuring` state, the two behave identically.
* Remove the …
=> feat: gateway auth redesign

gateway/ln-gateway/src/state_machine/complete.rs, gateway/ln-gateway/src/state_machine/events.rs, gateway/ln-gateway/src/state_machine/mod.rs, gateway/ln-gateway/src/state_machine/pay.rs
Similar to https://github.com/fedimint/fedimint/pull/6351, this PR adds payment events for LNv1. It allows us to compute profit, fees, and latency for LNv1.
The LNv2 events are a bit better structured, but this still gives us the necessary data. Since we will be supporting LNv1 for a bit I figured it would be good to add this as well (might even be fun to compare with LNv2).
=> feat: LNv1 Payment Events

fedimint-testing/src/ln.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/lightning/ldk.rs, gateway/ln-gateway/src/lightning/lnd.rs, gateway/ln-gateway/src/lightning/mod.rs
All other methods in the liquidity API return a response type (`CreateInvoiceResponse`, `GetLnOnchainAddressResponse`, etc...), let's use that pattern here too
=> chore: ILnRpcClient::list_active_channels() returns response

fedimint-cli/src/lib.rs, fedimint-client/src/lib.rs, fedimint-load-test-tool/src/common.rs, fedimint-testing/src/federation.rs, fedimint-testing/src/fixtures.rs, fedimint-wasm-tests/src/lib.rs, gateway/ln-gateway/src/client.rs, gateway/ln-gateway/src/lib.rs
The primary module instance id cannot be known upfront, it may differ from federation to federation.
=> feat: allow specifying primary module kind

.github/workflows/daily.yml
Due to:
https://github.com/fedimint/fedimint/actions/runs/12270380989/job/34235492495
We might as well use the same Nix-based `cargo-audit` as we do in normal runs.
=> chore(ci): avoid hitting secondary rate limits

Cargo.lock, Cargo.toml, fedimint-core/src/envs.rs, fedimint-core/src/util/mod.rs, modules/fedimint-wallet-common/src/lib.rs, modules/fedimint-wallet-server/Cargo.toml, modules/fedimint-wallet-server/src/feerate_source.rs, modules/fedimint-wallet-server/src/lib.rs
Introduces a `FM_WALLET_FEERATE_SOURCES` env var which allows specifing a list of urls along with `jq` filter syntax to extract the sats/vB feerate.
A default value is (will be - the exact contents are to be determined) provided per-network.
All sources are queried, along with the bitcoind, and a median is used to get the actual feerate to vote on during consensus.
Can be tested with:
```
env RUST_LOG=fm=info,fm::module::wallet=debug FM_WALLET_FEERATE_SOURCES="https://mempool.space/api/v1/fees/recommended#.halfHourFee;https://blockstream.info/api/fee-estimates#.\"1\"" j devimint-env
```
=> feat(wallet-server): ability to source fee rates from external sources

.github/workflows/ci-backwards-compatibility.yml, devimint/src/devfed.rs, devimint/src/federation.rs, devimint/src/gatewayd.rs, devimint/src/tests.rs, devimint/src/vars.rs, devimint/src/version_constants.rs, gateway/integration_tests/src/main.rs, modules/fedimint-lnv2-tests/bin/tests.rs, modules/fedimint-meta-tests/src/bin/meta-sanity-test.rs, modules/fedimint-wallet-tests/src/bin/wallet-recovery-test.rs, scripts/tests/test-ci-all.sh
Closes https://github.com/fedimint/fedimint/issues/6460
Closes https://github.com/fedimint/fedimint/issues/6465
Ports backwards-compatibility fixes to `master` found in https://github.com/fedimint/fedimint/pull/6432 while testing `v0.5.0` release candidates.
These changes update backwards-compatibility tests to run vs `v0.5.0-rc.2` on each PR push (we'll update to `v0.5.0` after cutting the release) and vs `v0.3.4-rc.1`, `v0.4.4`, and `v0.5.0-rc.2` in the merge queue (takes ~20 minutes to complete). Increasing our coverage of versions will help prevent introducing multiple breaking tests, which delays the release process.
These changes no longer test vs `v0.2.1`, since it's reached End of Life as of `v0.6`. A later PR will remove code paths related to testing `v0.2.1`.
This CI …
=> fix: backwards-incompatibilities vs v0.3.4-rc.1 v0.4.4 and v0.5.0

.github/workflows/ci-nix.yml
=> fix: warn about pre-releases to avoid accidental mainnet usage

.github/workflows/ci-backwards-compatibility.yml, gateway/integration_tests/src/main.rs
Closes https://github.com/fedimint/fedimint/issues/6545
=> chore(ci): use separate perfit metric for back-compat merge queue

.github/workflows/ci-nix.yml
Closes https://github.com/fedimint/fedimint/issues/6562
=> [Backport v0.5] fix: warn about pre-releases to avoid accidental mainnet usage

justfile.fedimint.just
Given the numbe of targets it takes around 6 minutes currently, which is somewhat significant, and our CI is getting busy.
=> chore(ci): cut the time "quick fuzzing" takes

fedimint-client/src/lib.rs, fedimint-client/src/module/mod.rs, fedimint-client/src/transaction/builder.rs, fedimint-load-test-tool/src/common.rs, gateway/ln-gateway/src/gateway_module_v2/mod.rs, gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs, gateway/ln-gateway/src/gateway_module_v2/send_sm.rs, gateway/ln-gateway/src/state_machine/mod.rs, gateway/ln-gateway/src/state_machine/pay.rs, gateway/ln-gateway/tests/tests.rs, modules/fedimint-dummy-client/src/lib.rs, modules/fedimint-dummy-tests/tests/tests.rs, modules/fedimint-ln-client/src/incoming.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-ln-client/src/pay.rs, modules/fedimint-ln-client/src/receive.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-client/src/receive_sm.rs, modules/fedimint-lnv2-client/src/send_sm.rs, modules/fedimint-lnv2-tests/tests/tests.rs, modules/fedimint-mint-client/src/backup/recovery.rs, modules/fedimint-mint-client/src/client_db.rs, modules/fedimint-mint-client/src/input.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-client/src/oob.rs, modules/fedimint-mint-tests/tests/tests.rs, modules/fedimint-wallet-client/src/deposit.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-client/src/pegin_monitor.rs
Notable changes:
* `await_primary_module_output` and similar do not return `Amount` as we no longer track per-output amount, and it didn't seem very used anywhere anyway, and it returned wrong value now as reported by @shaurya947 
* `OutPointRange` and `IdxRange` is a half-open range now, to allow expressing "txid without any change outputs"
If we're fine with this direction, I will attempt to backport, if it fails, we can backport just the `await_primary_module_output` side, I guess. I had to try the whole thing to ensure everything architecturally still works and makes sense.
=> refactor(client): finalize_and_submit to return OutPointRange

devimint/src/external.rs, fedimint-cli/src/client.rs, fedimint-core/src/encoding/btc.rs, gateway/ln-gateway/src/lib.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-common/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
Fixes #5203
Doesn't remove all usage of `assume_checked()`, since some uses are acceptable, such as in tests
=> fix: remove usage of assume_checked()

modules/fedimint-dummy-client/src/db.rs, modules/fedimint-dummy-client/src/lib.rs, modules/fedimint-dummy-tests/tests/tests.rs, modules/fedimint-ln-client/src/db.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-ln-tests/tests/tests.rs, modules/fedimint-lnv2-client/src/db.rs, modules/fedimint-mint-client/src/client_db.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-mint-tests/tests/tests.rs, modules/fedimint-wallet-client/src/client_db.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
reserves some prefixes for external integrator use in all client module databases
=> chore: reserve prefixes for external use

devimint/src/gatewayd.rs, devimint/src/tests.rs, devimint/src/vars.rs, devimint/src/version_constants.rs, fedimint-testing/src/fixtures.rs, gateway/cli/src/config_commands.rs, gateway/cli/src/general_commands.rs, gateway/cli/src/main.rs, gateway/integration_tests/src/main.rs, gateway/ln-gateway/src/client.rs, gateway/ln-gateway/src/config.rs, gateway/ln-gateway/src/db.rs, gateway/ln-gateway/src/envs.rs, gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, gateway/ln-gateway/src/state_machine/mod.rs, gateway/ln-gateway/src/state_machine/pay.rs, gateway/ln-gateway/tests/tests.rs, modules/fedimint-ln-common/src/config.rs, modules/fedimint-lnv2-common/src/gateway_api.rs, modules/fedimint-lnv2-tests/bin/tests.rs, modules/fedimint-lnv2-tests/tests/mock.rs
I think it is important that we allow customization of the various fees in the gateway for LNv2. Not all federations will be run for profit (private federations, smaller communities, etc) and I think gateways should have the option to change their fees to also be cheaper. LNv2 lightning fees are currently very expensive (1.5%), which is often higher than Lightning.
This PR also adds customization for the "transaction fees" which are applied to every transaction (send or receive).
=> feat: allow customization of LNv2 Lightning and Transaction Fees

devimint/src/gatewayd.rs, gateway/cli/src/config_commands.rs, gateway/integration_tests/src/main.rs, gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs
`FederationConfig` and `FederationInfo` have overlapping fields and its confusing when each one is used. This PR refactors it so that `FederationConfig` is a field inside of `FederationInfo`. `FederationInfo` is what is displayed to the gateway operator during the `info` command. `FederationConfig` is what is stored in the database.
`FederationConfig` can be printed using `gateway-cli cfg display`.
=> refactor: cleanup FederationInfo

Cargo.toml, fedimint-client-wasm/Cargo.toml, flake.nix, nix/flakebox.nix
To get:
```
> nix build .#wasmBundle
> ls -l result/share/fedimint-client-wasm/
total 5688
-r--r--r-- 3 root root   44832 Dec 31  1969 fedimint_client_wasm_bg.js
-r--r--r-- 3 root root 5770912 Dec 31  1969 fedimint_client_wasm_bg.wasm
-r--r--r-- 3 root root    3660 Dec 31  1969 fedimint_client_wasm_bg.wasm.d.ts
-r--r--r-- 3 root root    2323 Dec 31  1969 fedimint_client_wasm.d.ts
-r--r--r-- 3 root root     187 Dec 31  1969 fedimint_client_wasm.js
-r--r--r-- 3 root root     601 Dec 31  1969 package.json
```
Baseline I started with:
```
-rw-r--r-- 1 dpc dpc 9044484 Dec 18 22:52 fedimint-client-wasm/pkg/fedimint_client_wasm_bg.wasm
```
Not far from the [current fedimint-web-sdk bundle](https://github.com/fedimint/fedimint-web-sdk/blob/main/packages/wasm-bundler/fedimint_client_wasm_bg.wasm). …
=> chore: size-optimized wasm bundle

fedimint-cli/Cargo.toml, fedimint-client-wasm/Cargo.toml, modules/fedimint-mint-client/Cargo.toml, modules/fedimint-mint-client/src/lib.rs
This costs around 90KB in a fully-optimized build.
I'm not sure if there was any reason to enable it, so pushing in a separate to #6586 PR .
BTW. For reference: If you want to debug wasm bundle sizes:
```
diff --git a/fedimint-client-wasm/Cargo.toml b/fedimint-client-wasm/Cargo.toml
index 40ffc19a3b..c28783beae 100644
--- a/fedimint-client-wasm/Cargo.toml
+++ b/fedimint-client-wasm/Cargo.toml
@@ -10,7 +10,8 @@ repository = "https://github.com/fedimint/fedimint"
[package.metadata.wasm-pack.profile.release]
-wasm-opt = ['-Os']
+wasm-opt = false
```
```
nix shell nixpkgs#twiggy
nix build -L .#wasmBundle && ls -l result/share/fedimint-client-wasm/
twiggy top result/share/fedimint-client-wasm/fedimint_client_wasm_bg.wasm | less
```
=> chore(wasm): disable cli feature

Cargo.toml, fedimint-client-wasm/Cargo.toml, flake.nix, nix/flakebox.nix
Backport of #6586 to `releases/v0.5`.
=> [Backport releases/v0.5] chore: size-optimized wasm bundle

docs/release-process.md, justfile.fedimint.just
=> chore: add cargo publish to just file

.github/workflows/ci-backwards-compatibility.yml, docs/release-process.md, justfile.fedimint.just
We should update the version used in backwards-compatibility tests in CI vs master as part of the release process.
=> chore: update back-compat version from v0.5.0-rc.2 to v0.5.0

Cargo.toml
It is used to compile some regex by `tracing` and meaningfully important in dev/ci builds.
=> chore(dev): always optimize regex dependency

fedimint-core/Cargo.toml
```
-r--r--r--  2 root root 4329542 Dec 31  1969 fedimint_client_wasm_bg.wasm
```
:rocket:
=> chore: on wasm32 enable lowmemory feature of secp256k1

fedimint-core/Cargo.toml
Backport of #6594 to `releases/v0.5`.
=> [Backport releases/v0.5] chore: on wasm32 enable lowmemory feature of secp256k1

Cargo.lock, Cargo.toml, fedimint-cli/Cargo.toml, fedimint-client/Cargo.toml, fedimint-testing/Cargo.toml, gateway/cli/Cargo.toml, gateway/ln-gateway/Cargo.toml, modules/fedimint-wallet-client/Cargo.toml
> If you deploy something (e.g. to infra) using patches on top of releases/v0.5 then the fact that it shows 0.5.0-rc.x is a bit confusing.
Because technically I'm running v0.5.0 + patches
-- @dpc 
https://discord.com/channels/990354215060795454/990354215878688860/1319792791085125663
It is confusing to see you're running `0.5.0-rc.*`, when you're not actually running the release candidate. To stick with the convention defined on `master`, I propose we bump the minor version with `-alpha` suffix on the `releases/v0.*` branches. So for `releases/v0.5`, instead of using `0.5.0-rc5`, we'll use `0.5.1-alpha`, then bump the alpha to the release candidate when we're ready.
=> chore: bump version to v0.5.1-alpha

Cargo.lock, gateway/cli/Cargo.toml, gateway/cli/src/general_commands.rs
Since we switched to using bcrypt password hashes in #6482, we should make it easier for to-be gateway operators to create password hashes to use in their deployments. Here we're adding a command to the gateway CLI to create a password hash.
=> feat: gateway CLI can generate bcrypt password hashes

Cargo.toml, fedimint-cli/Cargo.toml, fedimint-client/Cargo.toml, fedimintd/Cargo.toml, gateway/cli/Cargo.toml
I discovered that it's possible to inherit almost all fields in each `package` from the root `Cargo.toml`
This is just to show it by using in few packages.
=> chore: inherit more from workspace Cargo.toml

fedimint-server/src/consensus/engine.rs
Backport of #6607 to `releases/v0.5`.
=> [Backport releases/v0.5] chore(consensus): improve logging

scripts/_common.sh
Fix #6633
No other places seem to use `TMP`
=> chore: use `TMPDIR`, not `TMP`

fedimint-client/src/transaction/builder.rs, fedimint-client/src/transaction/builder/tests.rs
Trying to forbid "empty bundle" (no inputs/outputs) turned out to generate too much `Option`-noise downstream, so let's just embrace it.
=> refactor(client): clarify handling of empty bundles

docs/release-process.md
- Adds new convention to bump `releases/v0.*` to use `-alpha` suffix after final release
- First proposed in https://github.com/fedimint/fedimint/pull/6613
- Reorgs final release steps for clarity
=> docs: update release process docs for final releases

fedimint-cli/src/client.rs, modules/fedimint-wallet-client/src/cli.rs, modules/fedimint-wallet-client/src/client_db.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-tests/src/bin/wallet-recovery-test.rs, modules/fedimint-wallet-tests/tests/tests.rs
Partially implements #6601 , plus moves a bit forward towards moving more stuff into module specific cli commands.
Notably I breaks backward compat of `fedimint-cli module wallet await-deposit` command, as I think it should default to `bitcoin::Address` argument, which the user probably cares more about than `OperationId`. Though both are still supported.
=> chore(client-wallet): new `fedimint-cli module wallet` cli commands

scripts/dev/run-test/fm-run-test, scripts/tests/test-ci-all.sh
Makes it easier to clean up my `/tmp` sometimes.
While at it, truncate the test name.
=> chore: prefix test tmpdir with fm-

devimint/build.rs, devimint/share/aliases/fm-cli, devimint/share/aliases/gateway-ldk, devimint/share/aliases/gateway-lnd, devimint/src/cli.rs, devimint/src/envs.rs, flake.lock, flake.nix, nix/flakebox.nix, scripts/_common.sh, scripts/dev/aliases.sh, scripts/dev/devimint-env.sh, scripts/dev/mprocs/run.sh, scripts/dev/user-shell.sh
Superseeds #6655
Make aliases standalone binaries, so they work in any setup, tooling, shell.
Ship `aliases` as a part of "static data" of devimint package. The location of the "static data" defaults to `/usr/devimint`, but can be overridden during build time and runtime. On Nix packaging will take care of setting the default either through a shell script (our flake case), or by setting it during build time (probably easiest approach in NixOS).
=> chore(devimint): ship aliases with `devimint` package

devimint/Cargo.toml, fedimint-api-client/Cargo.toml, fedimint-cli/Cargo.toml, fedimint-client/Cargo.toml, fedimint-testing/Cargo.toml, fedimint-testing/src/federation.rs, gateway/cli/Cargo.toml, gateway/ln-gateway/Cargo.toml
Tor pulls in a sqlite dependency, which requires downstream projects that depend on these crates to depend on sqlite in order to build, even if they're not using tor. Tor is already a feature, I think it makes sense to be optional.
=> chore: turn off tor by default

gateway/ln-gateway/src/lib.rs
Adds a check that prevents v0.5.1 gateways from joining affected federations of https://github.com/fedimint/fedimint/issues/6579
Upgrade scenarios:
- v0.4 -> v0.5.1. Gateways upgrading from v0.4 will continue to work normally, even if they have already joined an affected federation (because v0.4 handled databases differently and this is supported in future versions as well). 
- v0.5 -> v0.5.1. If a gateway is on v0.5 and has already joined an affected federation, the gateway will not be able to boot (because `load_clients` will expose the bug and crash the gateway). v0.5.1 does not fix that. v0.5.1 will prevent gateways from joining new federations that are affected. Unaffected v0.5 gateways can safely upgrade to v0.5.1 and will not hit the bug moving forward. 
- v0.6 will fix the bug. …
=> fix: prevent v0.5 gateways from joining clashing federations

Cargo.lock, fedimint-api-client/Cargo.toml, fedimint-api-client/src/api/error.rs, modules/fedimint-wallet-client/src/api.rs, modules/fedimint-wallet-client/src/pegin_monitor.rs, modules/fedimint-wallet-common/src/endpoint_constants.rs, modules/fedimint-wallet-server/src/lib.rs
The following edge case exists:
- Client sends funds to peg-in address
- Prior to claiming the peg-in, federation reaches consensus for 2.2
- Client attempts to claim peg-in, constructing V1 input since federation consensus is 2.2
- Federation rejects since UTXO is unknown, due to not persisting UTXO until 2.2 consensus is reached
This PR handles this by adding a new endpoint to check if the federation knows of the UTXO prior to submitting a V1 input. If the federation doesn't know of the UTXO, the client will fallback to V0 inputs.
Please note:
- The client no longer checks the consensus version since the federation will only know of the UTXO if the consensus version >= 2.2, thus the check is redundant
- This PR does not modify `modules/fedimint-wallet-client/src/deposit.rs` since the …
=> fix(wallet): verify utxo is known by server for v1 inputs

.github/workflows/linkcheck.yml, .lycheeignore, README.md, docs/architecture.md, docs/rustdoc-index.md
The output of existing link checker is super verbose and annoys me every time there's an issue, while it is no longer maintained:
https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/193
=> chore(ci): switch linkchecking to lychee

README.md, docs/deploying.md, docs/deploying/docker-mutiny.md
Currently from the README we link straight into very long and detailed and hands-on guide.
I think we need a single page that does some prep-talk, overviews and then points the reader at more detailed and specific guides, in which the existing guide will be just one of the items.
=> chore(docs): generalize "setting up Fedimint" docs

CONTRIBUTING.md, docs/deploying/docker-mutiny.md, docs/recoverable_e-cash.md, docs/rustdoc-index.md
These are no longer needed now that we moved from markdown link check to lychee.
=> chore: remove stale markdown-link-check elements

.github/workflows/upgrade-tests.yml, devimint/src/tests.rs, justfile.fedimint.just, scripts/tests/upgrade-test.sh
Closes https://github.com/fedimint/fedimint/issues/6282
This PR enables running upgrade tests against PRs and reduces the total time to run upgrade tests in CI vs the last three major versions from ~90 minutes to ~12 minutes ([CI run](https://github.com/fedimint/fedimint/actions/runs/12780718825/job/35640806526?pr=6619)).
These gains are accomplished by:
- Reducing the number of iterations run per upgrade test from 20 to 1, which still tests the same coverage of database entries
- Skipping running another round of `fedimintd` tests with the federation degraded, which is unnecessary since we have degraded federation test coverage throughout the test suite
- Parallelizing the upgrade tests to handle multiple upgrade paths in the same run
Since the total time is ~12 minutes, I don't see an …
=> Run upgrade tests against PRs and reduce total test time

Cargo.lock, fedimint-api-client/Cargo.toml, fedimint-api-client/src/api/global_api.rs, fedimint-api-client/src/api/mod.rs, fedimint-client/src/lib.rs, fedimint-client/src/module/init.rs, fedimint-client/src/module/init/recovery.rs, fedimint-client/src/module/mod.rs, fedimint-core/Cargo.toml, fedimint-core/src/encoding/as_base64.rs, fedimint-core/src/encoding/as_hex.rs, fedimint-core/src/encoding/mod.rs, fedimint-core/src/endpoint_constants.rs, fedimint-core/src/macros.rs, fedimint-core/src/module/mod.rs, fedimint-core/src/session_outcome.rs, fedimint-core/src/util/mod.rs, fedimint-server/src/config/mod.rs, fedimint-server/src/consensus/api.rs
goal: reduce data usage for recovery
- changed from hex to base64: 33% saving
- client can only download from single peer and verify using signature: num peers times saving
for 4 guardian federation: overall 6x less data download
Happy new year!
=> Recovery data usage improvements

fedimint-core/src/module/mod.rs, fedimint-server/src/consensus/api.rs, gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs, modules/fedimint-lnv2-common/src/endpoint_constants.rs, modules/fedimint-lnv2-common/src/lib.rs, modules/fedimint-lnv2-server/src/db.rs, modules/fedimint-lnv2-server/src/lib.rs
=> cleanup: do not use output outcome to return decryption shares

fedimint-cli/src/lib.rs
So in 744df9be092cf1e88f4f84744d1d0ee254741c1d @elsirion changed the default logging level, I didn't notice, and it confused me a lot.
I also don't want fedimint-cli to print too much noise, but I think that should be done by downgrading noisy stuff to debug or trace, as this is not only about fedimint-cli, but also any other software using fedimint client.
I happened to recently discuss the logging level in our (soon to be) dependencies as well: https://github.com/n0-computer/iroh/issues/3071#issuecomment-2561477758
To me the `info` are the most important informative messages that the user probably wants, and anything else should go into debug or even trace.
In #6711 I already downgraded some offenders, and make the expiration notice logging level increasingly higher logging level, based …
=> chore: fedimint-cli to default to info log level

fedimintd/src/fedimintd.rs
It's been long enough that anyone serious should be on 0.4 already anyway, and the check itself was rather clunky.
=> chore: remove the "check release notes ack"

devimint/Cargo.toml
Followup to ensure we continue publishing `devimint`. https://github.com/fedimint/fedimint/issues/6288
=> chore: publish devimint to crates.io

modules/fedimint-meta-tests/src/bin/meta-sanity-test.rs
Closes https://github.com/fedimint/fedimint/issues/6668
Error
```
01:12 00.000007 Caused by:
01:12 00.000006     Incorrect value: {}, expected: {"1":{"foo":"bar"}}
```
Not a proper fix, but stops the bleeding. I don't think it's worth the effort now to figure out support for v0.3.4-rc.1 compatibility. We introduced a fix for a race condition that first arrived in v0.4.0, so the surface area is likely contained to our minimum supported version that we'll soon drop when we release v0.6.0.
Original race condition fix https://github.com/fedimint/fedimint/commit/53e4fcc5b129b43d17994c916272d4f727470573
=> chore: skip running met-sanity-test for versions <= v0.3.4-rc.1

.github/workflows/upgrade-tests.yml
Now that we run upgrade tests against PRs and in the merge queue, we shouldn't run the test with `runLowPrio`. A potential cause for the flakiness observed in https://github.com/fedimint/fedimint/issues/6718.
=> chore(ci): rm runLowPrio from upgrade tests

.github/workflows/ci-nix.yml
They are not all that important, and with our relatively small cache just waste space over time.
=> chore(ci): do not pin pre-releases in cachix

fedimint-client/src/lib.rs, fedimint-client/src/module/init.rs, fedimint-client/src/module/mod.rs, gateway/ln-gateway/tests/tests.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-wallet-client/src/lib.rs
As a follow-up we'll break the `fedimint-client` into `fedimint-client-module` and `fedimint-client`, so that client modules depend only on the `fedimint-client-module`.
=> refactor(client): introduce interface betwen client and client modules

fedimint-core/src/db/mod.rs, fedimint-dbtool/src/dump.rs, fedimint-server-tests/tests/migration.rs, fedimint-server/src/consensus/db.rs, fedimint-server/src/consensus/mod.rs, fedimint-server/src/db.rs, fedimint-server/src/lib.rs
Our upgrade check in 0.4 was very crude and inconvenient, because we couldn't tell at which version the federation was set up. It's prudent to avoid such a problem in the future, even if we don't expect upgrades like these.
We can write a version of fedimint code that the federation was created with, and last one it was running with. Might come handy and doesn't cost much.
Thinking about where to put the "last version" update, it occured to me that it should be done atomically along with database migrations.
=> chore(server): maintain a code version info in the db

fedimint-core/src/config.rs, fedimint-core/src/module/mod.rs, fedimint-core/src/net/peers.rs, fedimint-core/src/net/peers/fake.rs, fedimint-server/src/config/distributedgen.rs, fedimint-server/src/config/mod.rs, fedimint-server/src/consensus/engine.rs, fedimint-server/src/net/p2p.rs, fedimint-server/src/net/p2p_connection.rs, fedimint-server/src/net/p2p_connector.rs
Rename p2p connection traits, remove unnecessary wrappers. Bring back dkg completion confirmation messages that were removed in https://github.com/fedimint/fedimint/pull/6695.
=> P2P follow up

Cargo.lock, fedimint-server-core/Cargo.toml, fedimint-server-core/src/init.rs, fedimint-server/src/consensus/mod.rs, modules/fedimint-wallet-common/src/endpoint_constants.rs, modules/fedimint-wallet-server/Cargo.toml, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/Cargo.toml, modules/fedimint-wallet-tests/tests/tests.rs
Automatically activates wallet module consensus upgrades if **every guardian** supports a newer consensus version than is currently active. If not, we still rely on manual upgrade votes, which can activate new consensus versions with a threshold of guardians, kicking out the remaining ones.
=> Activate wallet consensus rules

devimint/src/cli.rs, devimint/src/devfed.rs, devimint/src/lib.rs
```
2025-01-18T04:44:44.085057Z  INFO fm::devimint: Started lnd gateway elapsed_ms=698
thread 'tokio-runtime-worker' panicked at devimint/src/devfed.rs:297:34:
GW LDK should be present
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> chore: fix devimint panic in upgrade-tests

Cargo.lock, Cargo.toml, fedimint-cli/Cargo.toml, fedimint-client/Cargo.toml, fedimint-testing/Cargo.toml, gateway/cli/Cargo.toml, gateway/fedimint-lightning/Cargo.toml, gateway/ln-gateway/Cargo.toml, modules/fedimint-wallet-client/Cargo.toml
We cut the `releases/v0.6`, so time to bump master to `0.7.0-alpha`.
=> chore: bump master to 0.7.0-alpha

fedimint-core/src/envs.rs
OMG...
To help transition, I added backward compatiblity for the wrong versions too.
=> fix: typo in the names of env variables

fedimint-core/src/envs.rs
Backport of #6741 to `releases/v0.6`.
=> [Backport releases/v0.6] fix: typo in the names of env variables

devimint/Cargo.toml
Backports https://github.com/fedimint/fedimint/pull/6706
Using this instead of https://github.com/fedimint/fedimint/pull/6721, since we didn't have the `[package]` section of the root `Cargo.toml` until after v0.5. See https://github.com/fedimint/fedimint/pull/6721#issuecomment-2599167074
=> Backport v0.5: chore: publish devimint to crates.io

.github/workflows/upgrade-tests.yml
`v0.6.0-rc.0` is the first time we've been able to test multiple upgrade paths in one job. The default parallelism caused flakiness, so we reduce here. 5 may seem conservative, but we're much more interested in a single successful run than a fast run since this doesn't block PRs. We also need to increase the timeout since some upgrade paths can take a long time to complete (e.g. `v0.3.4-rc.1 -> v0.4.4 -> v0.5.0 -> v0.6.0-rc.0`.
=> chore(ci): define overrides for manual upgrade tests

modules/fedimint-wallet-common/src/lib.rs, modules/fedimint-wallet-server/src/envs.rs, modules/fedimint-wallet-server/src/lib.rs
Now that we have an ability to get fee rates from sources better than bitcoind estimation, our fee rates should be much more accurate.
Besides, I am yet to hear about a single instance of peg-outs getting stuck in the mempool, while I heard about and experience myself a decent amount of instances, when a person got robbed blind by a peg-out fee.
While at it, make it override-able from an env var.
=> chore: default feerate multiplier 4 -> 2 and ability to customize it

Cargo.lock, Cargo.toml, fedimint-cli/Cargo.toml, fedimint-client/Cargo.toml, fedimint-testing/Cargo.toml, gateway/cli/Cargo.toml, gateway/fedimint-lightning/Cargo.toml, gateway/ln-gateway/Cargo.toml, modules/fedimint-wallet-client/Cargo.toml
The diff compared to the previous version bump is 126 lines instead of 125 lines since we backported `fedimint-workspace` with the typed `PeerError`s (see: https://github.com/fedimint/fedimint/pull/6748/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R32).
=> chore: bump version to v0.6.0-rc.1

fedimint-bip39/src/lib.rs, fedimint-client/src/backup.rs, fedimint-client/src/oplog.rs, fedimint-client/src/secret.rs, fedimint-client/src/sm/executor.rs, fedimint-client/src/sm/state.rs, fedimint-core/src/core.rs, fedimint-core/src/encoding/bls12_381.rs, fedimint-core/src/encoding/btc.rs, fedimint-core/src/encoding/collections.rs, fedimint-core/src/encoding/iroh.rs, fedimint-core/src/encoding/mod.rs, fedimint-core/src/encoding/secp256k1.rs, fedimint-core/src/encoding/threshold_crypto.rs, fedimint-core/src/encoding/tls.rs, fedimint-core/src/lib.rs, fedimint-core/src/macros.rs, fedimint-core/src/tiered.rs, fedimint-core/src/tiered_multi.rs, fedimint-core/src/txoproof.rs, fedimint-derive/src/lib.rs, fedimint-server/src/consensus/debug.rs, modules/fedimint-ln-common/src/contracts/incoming.rs, modules/fedimint-ln-common/src/contracts/mod.rs, modules/fedimint-ln-common/src/lib.rs, modules/fedimint-wallet-common/src/keys.rs
It is redundant. 99% of the time, we throw it away anyway. The caller can always just wrap the writer in one that counts written bytes if they need it.
Since it is redundant I also notices some places where the number of returned bytes was wrong, and some in which it was hiding calling `write` instead of `write_all`, so also caused extra bugs.
=> refactor: do not return written bytes from consensus_encode

docker/current/.env, docker/current/deploy.sh, docker/current/docker-compose.yaml
I haven't verified against our Hetzner VMs, but I setup a personal VM and verified
- New deployment using existing logic
- Wipe using these changes and verified correct restart with new `fedimintd` tag and `bitcoin` named volume is untouched
Once we merge these changes, I'll deploy against our Hetzner VMs.
=> chore(ci): rm fedimintd_data and use fedimintd image tag var

fedimint-server/src/consensus/engine.rs, modules/fedimint-ln-server/src/lib.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs
Due to how AlephBFT works we generate consensus proposals over and over, and over and it's not very useful to know about that.
=> chore: lower logging of consensus proposals

devimint/src/gatewayd.rs, fedimint-bitcoind/src/lib.rs, fedimint-cli/src/lib.rs, fedimint-client/src/lib.rs, fedimint-core/src/util/mod.rs, fedimint-eventlog/src/lib.rs, gateway/cli/src/general_commands.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/events.rs, gateway/ln-gateway/src/gateway_module_v2/events.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs, gateway/ln-gateway/src/state_machine/events.rs, gateway/ln-gateway/tests/tests.rs, modules/fedimint-lnv2-tests/bin/tests.rs
Adds a 24 hour payment summary command to the gateway. Useful to get an "at a glance" summary of what happened over the last day.
=> feat: Gateway 24 hour payment summary

fedimint-core/src/module/mod.rs
For every request we print two log lines (received + complete/error) and this one is less useful by default.
=> chore: lower logging level of "api request complete"

fedimint-core/src/lib.rs, fedimint-server-core/src/lib.rs, fedimint-server/src/consensus/transaction.rs, modules/fedimint-dummy-server/src/lib.rs, modules/fedimint-empty-server/src/lib.rs, modules/fedimint-ln-server/src/lib.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-meta-server/src/lib.rs, modules/fedimint-mint-server/src/lib.rs, modules/fedimint-unknown-server/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
Similar to `OutPoint`, allows us to have access to the txid within process_input
=> chore: add InPoint for TX inputs

fedimint-api-client/src/api/global_api/with_cache.rs, fedimint-api-client/src/api/mod.rs, fedimint-cli/src/lib.rs, fedimint-core/src/backup.rs, fedimint-core/src/endpoint_constants.rs, fedimint-server/src/consensus/api.rs
=> Allow guardians to see statistics about client backups saved to their fedimintd

fedimint-core/src/task.rs, fedimint-server/src/consensus/aleph_bft/spawner.rs
On `debug` logging level, on every session switch we'll log finishing ~10 alephbft tasks, and starting of ~10 alephbft task for the next session. It's not very useful, and the default:
```
2025-01-31T00:37:04.100637Z  INFO spawn{task="main"}:run{id=0}: fm::consensus: Completed consensus session session_index=8
2025-01-31T00:37:04.100724Z  INFO spawn{task="main"}:run{id=0}: fm::consensus: Starting consensus session session_index=9
```
are all that we really need anyway. Especially in tests/devimint where we switch session every 10s or so.
Most other spawns kick in only once on start, so they are more useful.
=> chore: make alephbft tasks log on lower level

Cargo.lock, gateway/fedimint-lightning/Cargo.toml
LDK Node had a issue that caused devimint to not work properly in downstream projects. v0.4.3 fixed that, I would like that to be included in v0.6
=> [backport releases/v0.6] chore: bump LDK Node

Cargo.lock, Cargo.toml, fedimint-eventlog/Cargo.toml, fedimint-eventlog/src/lib.rs, gateway/fedimint-lightning/src/lib.rs, gateway/ln-gateway/Cargo.toml, gateway/ln-gateway/src/client.rs, gateway/ln-gateway/src/error.rs, gateway/ln-gateway/src/events.rs, gateway/ln-gateway/src/federation_manager.rs, gateway/ln-gateway/src/gateway_module_v2/events.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/tests/tests.rs, modules/fedimint-gw-client/Cargo.toml, modules/fedimint-gw-client/src/complete.rs, modules/fedimint-gw-client/src/events.rs, modules/fedimint-gw-client/src/lib.rs, modules/fedimint-gw-client/src/pay.rs
Moves the LNv1 module into its own crate called `fedimint-gateway-v1`. LNv2 will be done in a follow up.
The core idea is that that gateway's database and the lightning node are resources that the gateway manages, not the modules. There will be a separate trait per LN module `LightningV1Manager` and `LightningV2Manager` that will define how the module interacts with the gateway.
Some of the recently added event code also needed to be refactored so that the LNv1 and LNv2 modules can share it.
=> refactor: move LNv1 module into its own crate

Cargo.lock, gateway/fedimint-lightning/Cargo.toml, gateway/fedimint-lightning/src/lib.rs, gateway/fedimint-lightning/src/lnd.rs, gateway/ln-gateway/src/lib.rs
I don't like that the LND lightning implementation is dependent on the gateway's database.
It currently dependent on the database because, before spawning a subscription task to monitor the status of an invoice, we check if the invoice was created using LNv2.
This isn't strictly necessary though. We can just spawn the subscription task for all HOLD invoices, and if the invoice is a "real" invoice, the gateway won't be able to complete it anyway because there is no contract in the federation. So this PR removes this lookup. There might be a few more tasks spawned but I think this makes the code much cleaner.
There is already test coverage for this. The LNv2 tests pay a real HOLD invoice to verify nothing is broken.
=> refactor: remove LND's access to the gateway's database

fedimint-cli/src/lib.rs
I have `fedimint-cli` installed as `fmcli` locally for quick access and want to setup completions.
=> fix: use actual binary name for completions

Cargo.lock, fedimint-bitcoind/Cargo.toml, fedimint-bitcoind/src/lib.rs, fedimint-bitcoind/src/shared.rs, fedimint-logging/src/lib.rs, fedimint-server-core/Cargo.toml, fedimint-server-core/src/init.rs, fedimint-server/src/consensus/mod.rs, modules/fedimint-ln-server/src/lib.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-wallet-common/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/Cargo.toml, modules/fedimint-wallet-tests/tests/tests.rs
We're receiving reports of rate limitting issues
when using public block explorers.
Especially in 0.5 we've added sourcing of fee-rates from external web sources, which might add up
to existing block count sourcing.
One way to cut on the amount of requests we make is to not do duplicate work. Current all: wallet, ln and lnv2 modules just spawn their own monitoring tasks.
This change introduces a "anymap" share data structure where two modules can coordinate and re-use a type, as long as they both know about it and thus their
code and the type itself were implemented to facilitate such a sharing.
The first type to be used like this comes from `fedimint-bitcoind` and just hosts monitoring tasks, so all interested modules can share them.
=> refactor: share bitcoind monitoring between modules

fedimint-core/src/timing.rs, fedimint-server/src/consensus/engine.rs
We don't really use these as much anymore, at least usually.
W.r.t. db checkpoints we've verified in real settings that they are very cheap, so no need to log it anymore as much.
=> chore: lower logging level of some timings

nix/flakebox.nix
I don't know why this worked before, but I think we need to handle it manually here, especially if we want to retain some debug symbols and not strip the binary completely.
Fix #6821
=> chore: remove references to rust toolchain from binaries

nix/flakebox.nix
Backport of #6824 to `releases/v0.6`.
=> [Backport releases/v0.6] chore: remove references to rust toolchain from binaries

.github/workflows/ci-nix.yml
=> chore(ci): protect against accid. too large Nix closure sizes

.github/workflows/ci-nix.yml
MacOS is slow, and sometimes need some time to rebuild some new packages, etc.
=> chore(ci): increase timeout on MacOS build

.github/workflows/ci-backwards-compatibility.yml, .github/workflows/ci-fuzz.yml, .github/workflows/ci-nix.yml, .github/workflows/docs.yml, .github/workflows/flakebox-flakehub-publish.yml, .github/workflows/hourly-run.yml, .github/workflows/upgrade-tests.yml
They have some MacOS fixes for problems that are otherwise causing random CI failures, like e.g.:
https://github.com/fedimint/fedimint/actions/runs/13172264947/job/36764693478
=> chore(ci): switch to determinatesystems installer

.github/workflows/ci-nix.yml
It's slow, it's heavy and we don't really care.
We have a lot of fancy e2e tests, etc. so some number going up or down a little doesn't mean anything to us anymore.
=> chore(ci): drop the ccov build

devimint/src/vars.rs, gateway/ln-gateway/src/config.rs
The default for the Lightning Module Mode is confusing because it defaults to `All` which is necessary in devimint but discouraged in production. This PR changes it to LNv1 to be backwards compatible with previous code.
=> chore: change lightning module mode default

devimint/src/federation.rs, devimint/src/util.rs, scripts/tests/test-ci-all.sh, scripts/tests/upgrade-test.sh
We don't make any backwards-compatible guarantees for using different versions of `fedimint-cli` and `fedimintd` when running dkg. To enable refactors in https://github.com/fedimint/fedimint/pull/6827 we should first set the `fedimint-cli` version to match the `fedimintd` version in devimint before running DKG, then revert the cli version once that's complete.
=> chore: use fedimint-cli version that matches fedimintd for dkg

fedimint-core/src/module/mod.rs, modules/fedimint-meta-server/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs
Recently there was a bug in the wallet module where the server was committing a database transaction where it shouldn't be. https://github.com/fedimint/fedimint/pull/6869
Api endpoints do not own the database transaction, it is passed in through the `ApiContext`. This PR enforces that the db transaction passed in is non-committable, which enforces that the api endpoints themselves do not commit the database transaction. 
The db transaction is later committed as part of the api endpoint macro and any changes applied in the endpoint will be committed then.
=> fix: enforce api endpoints using non committable db transactions

devimint/src/version_constants.rs, gateway/ln-gateway/src/lib.rs, modules/fedimint-lnv2-tests/bin/tests.rs
Removes part of the test that is not present in v0.6
=> [Backport releases/v0.6] fix: lnv2 small backwards compatibility fixes

devimint/src/gatewayd.rs, devimint/src/tests.rs, fedimint-testing/src/ln.rs, gateway/cli/src/lightning_commands.rs, gateway/fedimint-lightning/src/ldk.rs, gateway/fedimint-lightning/src/lib.rs, gateway/fedimint-lightning/src/lnd.rs, gateway/ln-gateway/src/lib.rs, gateway/ln-gateway/src/rpc/mod.rs, gateway/ln-gateway/src/rpc/rpc_client.rs, gateway/ln-gateway/src/rpc/rpc_server.rs
Allows the gateway operator to query the status of an invoice if it knows the payment hash. Can be used for LNv2 invoices or invoices the gateway creates.
Currently this is only tested in the LNv1 tests with the LND gateway. This will be used to swap CLN for LDK, so that the LNv1 tests will still know when an invoice has been paid.
=> feat: Add `get_invoice` endpoint to gateway

Cargo.toml
Motivated by:
https://github.com/fedimint/fedimint/pull/6850#issuecomment-2669697615
Leads to significantly lower disk use and better compilation times.
We also might want to consolidate our test binaries (will do in the future).
=> chore: use line-table only debug symbols in dev

.github/workflows/ci-backwards-compatibility.yml, .github/workflows/upgrade-tests.yml, devimint/src/cli.rs, devimint/src/devfed.rs, devimint/src/federation/config.rs, devimint/src/gatewayd.rs, devimint/src/lib.rs, devimint/src/tests.rs, devimint/src/util.rs, devimint/src/vars.rs, fedimint-core/src/envs.rs, gateway/integration_tests/src/main.rs, modules/fedimint-lnv2-tests/bin/tests.rs, scripts/_common.sh, scripts/tests/gateway-module-test.sh, scripts/tests/gateway-reboot-test.sh, scripts/tests/lightning-reconnect-test.sh, scripts/tests/lnv2-module-test.sh, scripts/tests/test-ci-all.sh, scripts/tests/upgrade-test.sh
Fixes: https://github.com/fedimint/fedimint/issues/6795
1) Removes `FM_DEVIMINT_DISABLE_MODULE_LNV2` and replaces it with `supports_lnv2()` function, which just checks if `FM_ENABLE_MODULE_LNV2` is set. It is the responsibility of the bash scripts to set this variable.
2) For backwards compatibility tests, if the current set of versions supports LNv2, then each test is run 2x, once with LNv2 off and once with it on.
3) For upgrade tests, if the "first version" specified in the version set (ex: "v0.3.4-rc.1 v0.4.4" -> v0.3.4-rc.1 is the first version), then the upgrade test is executed with LNv2 off. If the first version in the version set does support LNv2 then the upgrade tests are executed 2x with LNv2 on/off.
4) For tests that are all on the current version, LNv2 is always on.
As it …
=> chore: Backwards Compatibility/Upgrade tests with LNv2

fedimint-api-client/src/api/mod.rs, fedimint-testing/src/federation.rs, fedimint-testing/src/fixtures.rs, gateway/fedimint-gateway-server/tests/tests.rs, modules/fedimint-dummy-tests/tests/tests.rs, modules/fedimint-ln-tests/tests/tests.rs, modules/fedimint-lnv2-tests/tests/tests.rs, modules/fedimint-mint-tests/tests/tests.rs, modules/fedimint-wallet-client/src/api.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
This builds on and replaces https://github.com/fedimint/fedimint/pull/6852.
Previously, `await_consensus_upgrade` only confirmed that `btc_tx_has_no_size_limit` returned `Ok` without checking the result. This led to consensus upgrades not activating, but tests passed since we continue to use the old consensus logic.
Our tests setup degraded federations, which prevents automatic activation of consensus version voting. We should keep running existing tests in a degraded state, so `await_consensus_upgrade` will trigger manual voting for degraded federations. There's a new test that verifies a 4/4 federation will trigger automatic voting.
There's another sneaky bug in the activate consensus version voting endpoint. We call `dbtx.commit_tx_result`, which causes the endpoint to return an error …
=> Fixes and tests for consensus version voting activation

fedimint-api-client/src/api/mod.rs, fedimint-testing/src/federation.rs, fedimint-testing/src/fixtures.rs, gateway/ln-gateway/tests/tests.rs, modules/fedimint-dummy-tests/tests/tests.rs, modules/fedimint-ln-tests/tests/tests.rs, modules/fedimint-lnv2-tests/tests/tests.rs, modules/fedimint-mint-tests/tests/tests.rs, modules/fedimint-wallet-client/src/api.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
Closes https://github.com/fedimint/fedimint/issues/6892
Cherry-picks all the commits from https://github.com/fedimint/fedimint/pull/6869 except [`6e6b1d9` (#6869)](https://github.com/fedimint/fedimint/pull/6869/commits/6e6b1d996cb70f5f0d651f67e558989d54bb9b16). That commit conflicts but isn't needed since the retry interval is already fast enough on `releases/v0.6`.
=> [Backport] Fixes and tests for consensus version voting activation

scripts/tests/upgrade-test.sh
@dpc spotted the formatting looked a bit off and it looks like we swapped `{$` for `${` in some bash variable expansions. Not a biggie since this only impacts the format of the upgrade test names.
before
```
```
after
```
```
=> fix: correct bash variable interpolation for lnv2 in upgrade tests

scripts/dev/mprocs/run.sh
https://github.com/fedimint/fedimint/pull/6781 forgot to enable LNv2 when running mprocs.
=> fix: enable LNv2 in mprocs

Cargo.lock
=> chore: update fs-lock to fix some Rust 2024 issues on nightly

docker/deploy-fedimintd/.env, docker/deploy-fedimintd/docker-compose.yaml
- Changes are tested and deployed
- Setup federation (surfaced some bugs with our docker env)
- Verified peers are on wallet module consensus version 2.2
- Originally 2.0, then after next loop of task we automatically activated
```
./fedimint-cli --data-dir=/home/stachurski/code/fedimint/docker-client dev api --peer-id 0 --module wallet module_consensus_version
{
"value": {
"major": 2,
"minor": 2
}
}
```
=> Docker test env fixes and fedimintd image version bump

.github/workflows/ci-nix.yml, devimint/src/cli.rs, nix/flakebox.nix
No need to build/package it separately.
=> fix(ci): `devimint-faucet` is now `devimint faucet`

fedimint-server/Cargo.toml
This commit fixes a build failure in `fedimint-server` (without the `"net"` feature) encountered during the `v0.6.0` release. It was added to `releases/v0.6.0` before the version bump and tag. This diff isn’t needed on `master` since `tokio-stream` was removed from `fedimint-server` (https://github.com/fedimint/fedimint/commit/86005130a6b42e27e3319c94418ea0ca7eee3b7c).
=> fix: build fedimint-server with "net" feature

.github/workflows/ci-backwards-compatibility.yml, .github/workflows/upgrade-tests.yml, devimint/src/external.rs, devimint/src/federation.rs, devimint/src/federation/config.rs, devimint/src/gatewayd.rs, devimint/src/tests.rs, devimint/src/version_constants.rs, gateway/integration_tests/src/main.rs, modules/fedimint-meta-tests/src/bin/meta-sanity-test.rs, modules/fedimint-mint-tests/src/bin/mint-module-tests.rs, modules/fedimint-wallet-tests/src/bin/wallet-module-tests.rs, scripts/_common.sh
Removes `v0.2` and `v0.3` codepaths from devimint and other integration tests.
Adds `v0.6.0` to backwards compatibility and upgrade tests. Changes `LNV2_STABLE_VERSION` to be `v0.6.0`.
=> chore: remove v0.2 and v0.3 codepaths

docker/deploy-fedimintd/.env, docker/deploy-fedimintd/docker-compose.yaml
Builds on top of https://github.com/fedimint/fedimint/pull/6913 (resolves merge conflict)
Bumps `fedimintd` image tag to `v0.6.0`. Deployed, setup with guardian ui, and joined with a new client.
Deploying also re-verified #6913
=> chore: bump docker fedimint tag to v0.6.0 

docs/release-process.md
We discovered an issue publishing to crates.io when we cut the final tag (see: https://github.com/fedimint/fedimint/pull/6918). Instead, let's publish release candidates so we discover earlier.
=> chore: update release process to publish to crates for rcs

devimint/src/cli.rs, devimint/src/devfed.rs, devimint/src/gatewayd.rs, devimint/src/tests.rs, gateway/integration_tests/src/main.rs, modules/fedimint-lnv2-tests/bin/tests.rs
Builds on https://github.com/fedimint/fedimint/pull/6781
Allows devimint to always spawn an LDK GW, regardless of the version (backwards compat, upgrade, etc). If the LDK GW version is "before" LNv2, then it just spawns the most recent GW version. When LNv2 is not active, operations that require LNv2 (i.e pegging in) are skipped and the LDK GW can be used as a normal lightning node.
Next step after this is removing CLN.
=> refactor: Divorce LDK GW from LNv2

Cargo.lock, devimint/Cargo.toml, devimint/src/cli.rs, devimint/src/devfed.rs, devimint/src/federation.rs, devimint/src/vars.rs, devimint/src/vars/iroh.rs, devimint/src/vars/net_overrides.rs, fedimint-server/src/config/api.rs, fedimint-server/src/config/mod.rs, fedimint-server/src/consensus/mod.rs, fedimint-server/src/envs.rs, fedimint-server/src/lib.rs, fedimint-server/src/net/p2p_connector.rs, fedimintd/src/fedimintd.rs, gateway/integration_tests/src/main.rs
Start with refactoring some clumsy handling of fedimintd ports in devimint. Now allocation happens upfront in the `Global`s. There seem to be no good reason to do it later (when starting fedimintd). Some other cleanups/changes were needed.
Thanks to having it upfront we can add iroh overrides. For every fedimintd iroh endpoints will be seeded with secret keys, and overrides for making connections to iroh endpoints are globally set.
State:
Normal tcp-based connectivity should be not affected.
It's now possible to enable Iroh in devimint e.g. with:
```
env FM_FORCE_IROH=true RUST_LOG=fm::net::iroh=trace,fm=debug,warn just devimint-env
```
DKG completes, but announcement handling seems to be panicking both in the server and client:
```
Unrecoverable decoding DatabaseValue as …
```
=> refactor(devimint): iroh support

devimint/src/devfed.rs, devimint/src/external.rs, devimint/src/federation.rs, devimint/src/gatewayd.rs, devimint/src/tests.rs, gateway/fedimint-gateway-common/src/envs.rs, gateway/fedimint-gateway-common/src/lib.rs, gateway/fedimint-gateway-server/src/lib.rs, gateway/fedimint-lightning/src/ldk.rs, gateway/integration_tests/src/main.rs, misc/mprocs.yaml, modules/fedimint-lnv2-tests/bin/tests.rs
In devimint, we currently make an assumption that there is only 1 LDK Gateway. When we add a second one, we will need the paths that are used for the data directory to be unique and the logs directory to be unique. This PR makes some devimint cleanups to allow us to customize the name.
Additionally, the LDK Gateway has a bug where it does not set the node's alias on mainnet. This prevents other nodes from opening channels to it. https://docs.rs/ldk-node/0.4.3/ldk_node/config/struct.Config.html#structfield.node_alias. This is a bug, we want other nodes to be able to open channels to it.
=> feat: Allow customization of `Gatewayd` name in devimint

fedimint-api-client/src/api/mod.rs, fedimint-server/src/config/mod.rs
Works here (`env FM_DEVIMINT_CMD_INHERIT_STDERR=1 FM_FORCE_IROH=true RUST_LOG=fm::net::iroh=trace,fm=debug,off j devimint-env` works)
=> chore: remove suffix from iroh urls

Cargo.lock, fedimint-core/src/base32.rs, fedimint-core/src/invite_code.rs, fedimint-core/src/lib.rs, fedimint-server/Cargo.toml, fedimint-server/src/config/api.rs, fedimint-server/src/config/mod.rs, modules/fedimint-mint-client/src/lib.rs
Right now we use different encodings (bech32, base64 and base58) for the invite code, ecash and connection strings. In order to reduce dependencies I propose to move to our own base32 lower hex encoding as the once and for all standard for oob byte encodings to strike a balance between compactness, implementation complexity and aesthetics.
=> replace bs58 base 58 encoding with our own base 32

devimint/src/external.rs, devimint/src/gatewayd.rs
Fixes: https://github.com/fedimint/fedimint/issues/6908
Having some trouble debugging the flaky channel opens in devimint. Figured it would be a good time to dump the gateway's logs when channel openings fail or when `info` times out.
=> test: dump gatewayd logs

fedimint-client/src/db.rs, fedimint-eventlog/src/lib.rs
Fix https://github.com/fedimint/fedimint/issues/6948
How I tested it:
* Checkout 0.6.0 or just existing `master`, which has the prefixes switched.
* Start `just devimint-env`
* Run `fm-cli backup` or whatever, just to generate some more events.
* Verify events exist in `fedimint-dbtool --database-dir $FM_CLIENT_DIR/client.db list --prefix "39"` and `fedimint-dbtool --database-dir $FM_CLIENT_DIR/client.db list --prefix "3a"`. Pending events will be empty, as they get processed almost immediately :shrug: .
* Keep `devimint-env` working, checkout this branch.
* `cargo build` to build fixed client
* Run `env RUST_LOG=fm=debug,fm::client::db=trace fm-cli backup`. This will trigger db migration. All keys get migrated, since they were all in the wrong place. Everything still works.
Our upgrade …
=> fix(client): event log prefixes switched

gateway/fedimint-lightning/src/ldk.rs
My suspicion for the flakiness in CI is that a recent change to how we set LDK's alias is causing channel openings to be flaky. Previous we had always set an LDK alias in regtest, so let's just do that for all networks now.
This also fixes a panic if the alias is longer than 32 bytes.
=> fix: set LDK alias correctly

fedimint-client/src/db.rs
Backport of #6957 to `releases/v0.6`.
=> [Backport releases/v0.6] fix: update log message for unordered log key

scripts/dev/run-test/fm-run-test
`timeout -k <dur>` is *duration after the initial signal*, and not after the command started.
=> chore(ci): fix timeouts on tests

fedimint-api-client/src/api/error.rs
Now:
```
{
"error": "Federation rpc error { method => list_gateways, 1 => Connection failed: Failed to connect to peer, 2 => Connection failed: Failed to connect to peer }"
}
```
=> fix: Federation rpc error formatting

.github/workflows/ci-backwards-compatibility.yml, .github/workflows/upgrade-tests.yml, justfile.fedimint.just
We cut `v0.5.1`, so time to bump our version in tests.
=> chore: bump version to v0.5.1 in tests

Cargo.lock, modules/fedimint-meta-tests/Cargo.toml, modules/fedimint-meta-tests/src/bin/meta-module-tests.rs, scripts/tests/meta-module-test.sh
To make it work and look like `wallet-module-tests` and `mint-module-tests`.
=> chore: rename meta module tests

scripts/_common.sh
Fixes https://github.com/fedimint/fedimint/issues/6986
=> fix: exit if nix build fails in `nix_build_binary_for_version`

scripts/_common.sh
=> chore(ci): warn about `set -euo pipefail` not enabled

devimint/src/cfg/lnd.conf, scripts/dev/run-test/fm-run-test
While at it, lower LND logging level, the debug
one is really chatty with stuff we probably
don't care about.
=> chore(ci): dump LN node logs on test fail

devimint/src/devfed.rs, devimint/src/external.rs, devimint/src/gatewayd.rs, gateway/fedimint-gateway-server/src/lib.rs
CLN and LND need to be synced when opening channels. When channels are opened in parallel, two threads are mining blocks which causes the lightning nodes to not be synced for a small period of time. The `open_channel` requests then can fail, which fails the devimint setup.
Solution is to remove the parallelism in channel opens and wait for the lightning node to be synced before opening channels.
=> chore: Simplify devimint channel opens

devimint/src/envs.rs, devimint/src/tests.rs, devimint/src/util.rs, fedimint-load-test-tool/src/common.rs, fedimint-load-test-tool/src/main.rs
One step closer to removing CLN.
Coverage remains the same, just using LDK as the Lightning node for LNv1 instead of CLN.
=> refactor: use LDK in load tool test instead of CLN

devimint/src/cli.rs, devimint/src/envs.rs, devimint/src/external.rs, devimint/src/faucet.rs, devimint/src/tests.rs
Prepping for Core Lightning to be removed from the codebase. The external daemons and devimint faucet still depend on it. This PR removes that dependency.
=> refactor: remove core lightning from external daemons and faucet

fedimint-bitcoind/src/lib.rs
```
> curl -s "https://mempool.space/api/v1/fees/recommended"
{"fastestFee":11,"halfHourFee":10,"hourFee":8,"economyFee":2,"minimumFee":1}
```
=> fix: default FM_WALLET_FEERATE_SOURCES for mempool.space

fedimint-client/src/db.rs, fedimint-core/src/db/mod.rs, gateway/fedimint-gateway-server/src/db.rs, modules/fedimint-dummy-server/src/lib.rs, modules/fedimint-mint-server/src/lib.rs, modules/fedimint-unknown-server/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs
Functions have a lot of limitations, that I'm hitting in a larger refactoring I'm trying to get done.
=> refactor(core): make migration fn a closure

fedimint-bitcoind/src/lib.rs
Backport of #7012 to `releases/v0.6`.
=> [Backport releases/v0.6] fix: default FM_WALLET_FEERATE_SOURCES for mempool.space

fedimint-server-core/src/init.rs, modules/fedimint-dummy-server/src/lib.rs, modules/fedimint-empty-server/src/lib.rs, modules/fedimint-ln-server/src/lib.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-meta-server/src/lib.rs, modules/fedimint-mint-server/src/lib.rs, modules/fedimint-unknown-server/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs
There's currently no way to get server module type for a given server module init type.
[`ClientModuleInit::Module`](https://docs.fedimint.org/fedimint_client_module/module/init/trait.ClientModuleInit.html#associatedtype.Module) already exists, so add one just like that.
=> refactor(server): add `ServerModuleInit::Module`

.github/workflows/ci-nix.yml
=> chore(ci): document why we run tests with wasm32-unknown toolchain

fedimint-wasm-tests/src/lib.rs
Given that our note selection can pull in extra notes, etc. Its possible to hit flakes here like:
https://github.com/fedimint/fedimint/actions/runs/13850780953/job/38757569355?pr=7030
https://github.com/fedimint/fedimint/actions/runs/13845186320/job/38754100255?pr=7028
=> fix(wasm-tests): not whole balance necessarily available

gateway/fedimint-gateway-server/src/envs.rs, gateway/fedimint-gateway-server/src/lib.rs
It has been discouraged in the past to run with both LNv1 and LNv2 in the gateway, because the invoices cannot be paid using the same gateway. We haven't ever explicitly prevented doing this though.
We should. This PR adds a check on mainnet that prevents users from running with `LightningModuleMode::All`. Can be overridden if absolutely necessary.
=> chore: check if running with LNv1 and LNv2 on mainnet

Cargo.lock, Cargo.toml, fedimint-dbtool/Cargo.toml, fedimint-dbtool/src/dump.rs, gateway/fedimint-gateway-server-db/Cargo.toml, gateway/fedimint-gateway-server-db/src/lib.rs, gateway/fedimint-gateway-server-db/src/migration_tests.rs, gateway/fedimint-gateway-server/Cargo.toml, gateway/fedimint-gateway-server/src/client.rs, gateway/fedimint-gateway-server/src/federation_manager.rs, gateway/fedimint-gateway-server/src/lib.rs
On top of #7030 
`fedimint-testing` is slow to compile and depends on a lot of things.
`devimint` is slow to compile and depends on a lot of things.
`devimint` waiting for `fedimint-testing` to finish just to use
one struct and one function is absolutely terrible.
=>  refactor: dbtool to depend only on fedimint-gateway-server-db 

fedimint-server-ui/Cargo.toml
Without an explicit lib or bin section cargo deny can't parse the manifest and fails in CI.
See https://github.com/fedimint/fedimint/pull/7033#issuecomment-2732586431
=> fix: add lib secrion to server-ui Cargo.toml

Cargo.lock, Cargo.toml
https://github.com/cargo-bins/cargo-binstall/issues/2090
```
2025-03-18T18:34:57.983443Z DEBUG fm::db: Acquiring database lock lock=/tmp/devimint-299688-990/clients/default-0/client.db.lock
2025-03-18T18:34:57.983460Z DEBUG fm::db: Acquired database lock lock=/tmp/devimint-299688-990/clients/default-0/client.db.lock
2025-03-18T18:34:57.983482Z DEBUG fm::db: Acquiring database lock lock=/tmp/devimint-299688-990/clients/default-0/client.db.lock
2025-03-18T18:34:57.983493Z DEBUG fm::db: Acquired database lock lock=/tmp/devimint-299688-990/clients/default-0/client.db.lock
```
Seems like locking just stopped working.
=> fix: downgrade and pin fs-lock

Cargo.lock, Cargo.toml, devimint/Cargo.toml, devimint/src/gatewayd.rs, fedimint-testing/src/ln.rs, gateway/fedimint-gateway-client/Cargo.toml, gateway/fedimint-gateway-client/src/general_commands.rs, gateway/fedimint-gateway-client/src/lib.rs, gateway/fedimint-gateway-client/src/lightning_commands.rs, gateway/fedimint-gateway-common/src/lib.rs, gateway/fedimint-gateway-server/src/lib.rs, gateway/fedimint-gateway-server/src/rpc_server.rs, gateway/fedimint-lightning/src/ldk.rs, gateway/fedimint-lightning/src/lib.rs, gateway/fedimint-lightning/src/lnd.rs, gateway/integration_tests/src/main.rs, modules/fedimint-ln-common/src/contracts/mod.rs
Fixes: https://github.com/fedimint/fedimint/issues/6389
We need to have an API to list the transactions the gateway has executed (outbound and inbound).
API takes a `DateTime` to limit the returned results.
=> feat: gateway list lightning transactions

devimint/src/util.rs, fedimintd/src/fedimintd.rs, scripts/dev/mprocs/run.sh, scripts/tests/gateway-module-test.sh, scripts/tests/gateway-reboot-test.sh, scripts/tests/lightning-reconnect-test.sh, scripts/tests/lnv2-module-test.sh
Fixes: https://github.com/fedimint/fedimint/issues/7011
We have discussed enabling LNv2 by default on federations to incentivize wallet developers to implement it. This PR just changes the default of `FM_ENABLE_LNV2_MODULE` to true.
Testing infrastructure stays the same as it was before.
=> feat: enable LNv2 by default

fedimint-client/src/oplog.rs
Just because someone requested huge limit, doesn't mean there are that many matching entries, and we want to allocate whole system memory in anticipation.
=> fix(client): crash possibility

fedimint-client/src/oplog.rs
Backport of #7058 to `releases/v0.6`.
=> [Backport releases/v0.6] fix(client): crash possibility

Cargo.lock, fedimint-cli/src/lib.rs, fedimint-dbtool/src/dump.rs, fedimint-dbtool/src/lib.rs, fedimint-load-test-tool/src/common.rs, fedimint-recoverytool/src/main.rs, fedimint-rocksdb/Cargo.toml, fedimint-rocksdb/src/db_locked.rs, fedimint-rocksdb/src/lib.rs, fedimint-testing-core/src/db.rs, fedimint-testing/src/federation.rs, fedimintd/src/fedimintd.rs, gateway/fedimint-gateway-server/src/client.rs, gateway/fedimint-gateway-server/src/lib.rs
This should be common functionality, so there is no doubt
that dbtool and other things respect locking.
While at it, fix the async/blocking IO handling.
=> refactor(rocksdb): lock rocksdb by default

docker/deploy-fedimintd/deploy.sh
We should stop the `fedimint-docker-compose` service before calling `docker-compose down`, since the service has a restart policy.
=> fix: stop docker compose service before removing fedimintd volume

devimint/src/cli.rs, devimint/src/devfed.rs, devimint/src/envs.rs, devimint/src/federation.rs, devimint/src/lib.rs, gateway/integration_tests/src/main.rs, justfile.fedimint.just
You can try with:
```
> just devimint-env-pre-dkg                                                                                                                   [0/9]
fedimint-0 UI: http://localhost:2002
fedimint-1 UI: http://localhost:2006
fedimint-2 UI: http://localhost:2010
fedimint-3 UI: http://localhost:2014
env FM_FEDERATIONS_BASE_PORT=2000 FM_PRE_DKG=true ./scripts/dev/devimint-env.sh
Lowering IO priority with chrt -i 0 ionice -c 3
Compiling fedimint-client-module v0.7.0-alpha (/home/dpc/lab/fedimint/fedimint/fedimint-client-module)
...
```
On top of #7056 
This is to replace what @joschisan is removing in #7041 , in a (hopefully) more elegant way.
=> chore(devimint): ability to stop before dkg

docker/README.md, docker/iroh-fedimintd/docker-compose.yaml
Closes https://github.com/fedimint/fedimint/issues/7005
Introduces a new `docker-compose` that supports Iroh. Unifying with the existing `docker-compose` isn't worth the effort yet while we're still in the early stages of testing Iroh in the wild.
=> feat: add docker-compose that supports iroh federations

devimint/src/vars.rs, docker/deploy-fedimintd/docker-compose.yaml, docker/iroh-fedimintd/docker-compose.yaml, fedimint-server/src/config/mod.rs, fedimint-server/src/config/setup.rs, fedimint-server/src/consensus/mod.rs, fedimint-server/src/lib.rs, fedimint-server/src/net/api/mod.rs, fedimint-server/src/net/p2p_connector.rs, fedimint-testing/src/federation.rs, fedimintd/src/envs.rs, fedimintd/src/fedimintd.rs
Fundamentally Iroh typically needs to be bound to 0.0.0.0, while our http apis to 127.0.0.1. We need two different settings for binding it, as we run both APIs at the same time (at least sometimes).
We can set the defaults to typical production settings:
* p2p (iroh/tls): 0.0.0.0
* iroh api: 0.0.0.0
* ws api: 127.0.0.1
Add some documentation with mention of typical settings, so `--help` is more informative.
Fix our docker examples, as at least Iroh one was setting iroh to bind to 127.0.0.1, which probably only worked because of fallback TCP connections to public relays.
=> fix: improve our network setting policy

Cargo.toml
We're using "fat" LTO with a single codegen unit
for maximum LTO and runtime performance results, but this costs *a lot* at compilation time.
Using a couple more compilation units should significantly improve linking time on release builds.
=> chore: build release build with more cores

.clippy.toml, fedimint-bitcoind/src/shared.rs, fedimint-client-module/src/module/init.rs, fedimint-client-module/src/transaction/sm.rs, fedimint-client/src/client.rs, fedimint-core/src/task/inner.rs, fedimint-eventlog/src/lib.rs, fedimint-server/src/consensus/engine.rs, fedimint-server/src/net/p2p.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-client/src/pegin_monitor.rs, modules/fedimint-wallet-server/src/lib.rs
Require `#[allow(...)]` if it's semantics are actually needed
See motivation in: https://github.com/tokio-rs/tokio/issues/7228
In the places where we were just trowing the error away, we can just update to `send_replace` anyway, it's better to keep the latest value in there anyway, even if no one is going to subscribe and check it again.
=> chore: have clippy warn about `watch::Sender::send`

Cargo.lock, fedimint-client-wasm/Cargo.toml, fedimint-client-wasm/src/lib.rs
Closes [#96](https://github.com/fedimint/fedimint-web-sdk/issues/96)
- Added parse_bolt11_invoice function to parse Lightning invoices.  
- Extracts and returns the following details in JSON format:  
- amount: Invoice amount in satoshis.  
- expiry: Expiry time in seconds.  
- memo: Description or description hash.  
- Includes error handling for invalid invoice formats.
=> feat: Add parse_bolt11_invoice function

Cargo.lock, Cargo.toml, fedimint-api-client/Cargo.toml, fedimint-api-client/src/api/mod.rs, fedimint-server/Cargo.toml, fedimint-server/src/consensus/mod.rs, fedimint-server/src/net/p2p_connector.rs
This is to help debugging connectivity issues.
If the logs print:
```
2025-03-25T18:56:44.507980Z  INFO fm::net::iroh: Iroh p2p server endpoint bind_addr=127.0.0.1:14550 node_id=e7fe3258fd193b8b118683c5262482072ef74162c040befdb57b98c3e296e727 node_id_pkarr=h99drs87dr7asrcgoxn1cjrnyhzxqomnabym79pixqcc8awshhuo
```
You can query n0 DNS resolution like this:
```
> dig _iroh.h99drs87dr7asrcgoxn1cjrnyhzxqomnabym79pixqcc8awshhuo.dns.iroh.link. TXT
; <<>> DiG 9.18.33 <<>> _iroh.h99drs87dr7asrcgoxn1cjrnyhzxqomnabym79pixqcc8awshhuo.dns.iroh.link. TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48040
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION: …
```
=> chore: improve iroh endpoint logging

docker/iroh-fedimintd/docker-compose.yaml
https://discord.com/channels/990354215060795454/1354146374677041163/1354146911002693884
=> chore: use static hash for iroh docker image version

modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-lnv2-tests/tests/tests.rs
Preimage is a proof of payment, some Lightning wallets might want to display it or save it for future reference (Harbor Wallet does this)
=> fix: expose LNV2 preimage when payment is successful

devimint/src/devfed.rs, devimint/src/external.rs, devimint/src/gatewayd.rs, devimint/src/tests.rs, devimint/src/vars.rs, gateway/fedimint-gateway-server/src/lib.rs, gateway/fedimint-lightning/src/ldk.rs
In https://github.com/fedimint/fedimint/pull/6561, we refactored LDK in devimint to use bitcoind instead of esplora because it is much faster. We technically still support esplora, but it isn't tested.
To my surprise, getting a devimint test to work with esplora was difficult (turns out the esplora client cannot handle trailing slashes). This PR enables `Gatewayd` in devimint to start with either bitcoind or esplora, with bitcoind being the default.
I modified the gateway reboot test to verify that LDK can connect to esplora after it reboots.
=> test: verify LDK can connect to esplora

fedimint-server-ui/src/meta.rs
If you select key to delete and press enter it will now work and delete the key. No changes visually.
=> chore(ui): delete meta key on enter keypress

fedimintd/src/envs.rs, fedimintd/src/lib.rs
Backport of #7121 to `releases/v0.6`.
=> [Backport releases/v0.6] feat(mint): allow overriding the default esplora server

fedimint-client-wasm/src/lib.rs, modules/fedimint-mint-client/src/lib.rs
Currently Web SDK have no functions to get note counts by the denomination so that users can see how their eCash is distributed across different denominations.
Have added `get_note_counts_by_denomination` function in fedimint-client-wasm that should be beneficiary in future for web SDK usage and wallet implemention.
=> feat: Added get_note_counts_by_denomination in fedimint-client-wasm

fedimint-server-ui/src/invite_code.rs, fedimint-server-ui/src/lnv2.rs, fedimint-server-ui/src/wallet.rs, modules/fedimint-wallet-server/src/lib.rs
- Reorganize balance display with logical grouping:
- Spendable Amount
- Change Amounts (unsigned/unconfirmed)
- Total Available Balance
- Outgoing Amounts (unsigned/unconfirmed)
- Add collapsible documentation section explaining each balance type
- Add mempool.space links for transaction acceleration and exploration
=> Wallet UI Improvements

fedimint-api-client/src/api/error.rs
Saw a warning due to an unspecified server error when fetching signed session outcomes and I'd like to know what they are about.
=> chore: print more error information for `PeerError`

fedimint-api-client/src/api/error.rs
Backport of #7151 to `releases/v0.6`.
=> [Backport releases/v0.6] chore: print more error information for `PeerError`

lnurlp/Cargo.toml
We'll fail to publish to crates.io since we can't build `lnurlp` without the `async` feature.
```
cargo build -p lnurlp
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Compiling lnurlp v0.7.0-beta.0 (/home/stachurski/code/fedimint/lnurlp)
error[E0433]: failed to resolve: could not find `AsyncClient` in `lnurl`
--> lnurlp/src/main.rs:54:31
|
54 |     let async_client = lnurl::AsyncClient::from_client(reqwest::Client::new());
|                               ^^^^^^^^^^^ could not find `AsyncClient` in `lnurl`
```
=> fix: add async feature to lnurlp

fedimint-api-client/src/api/error.rs
Backport of #7151 to `releases/v0.7`.
=> [Backport releases/v0.7] chore: print more error information for `PeerError`

docker/README.md
For new users it's unclear how to access the web UI after starting the docker compose stack. This hopefully clarifies how to access the UI.
Additional context: https://discord.com/channels/990354215060795454/990354215878688860/1357792906836050163
=> docs: clarify accessing the web UI using iroh docker

fedimint-recurringd/Cargo.toml, fedimint-recurringd/README.md, fedimint-recurringd/src/db.rs, fedimint-recurringd/src/lib.rs, fedimint-recurringd/src/main.rs
We fail to publish to crates.io without the `description` metadata field.
```
Updating crates.io index
warning: manifest has no description, documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
Packaging fedimint-recurringd v0.7.0-beta.1 (/home/stachurski/code/fedimint/fedimint-recurringd)
Updating crates.io index
Packaged 8 files, 186.4KiB (45.7KiB compressed)
Verifying fedimint-recurringd v0.7.0-beta.1 (/home/stachurski/code/fedimint/fedimint-recurringd)
Compiling fedimint-recurringd v0.7.0-beta.1 (/home/stachurski/code/fedimint/target-nix/package/fedimint-recurringd-0.
7.0-beta.1)
Finished `dev` profile [optimized + debuginfo] target(s) in 5.13s
Uploading fedimint-recurringd v0.7.0-beta.1 …
```
=> fix: add missing metadata to fedimint-recurringd Cargo.toml

fedimint-recurringd/Cargo.toml, fedimint-recurringd/README.md, fedimint-recurringd/src/db.rs, fedimint-recurringd/src/lib.rs, fedimint-recurringd/src/main.rs
Backport of #7162 to `releases/v0.7`.
=> [Backport releases/v0.7] fix: add missing metadata to fedimint-recurringd Cargo.toml

.typos.toml, flake.nix, nix/bin/cargo-with-memlimit.sh, nix/flakebox.nix
Alternative to #7135 that just caps number of jobs to based by the total memory of the system.
=> chore(nix): avoid running out of memory

docker/iroh-fedimintd/docker-compose.yaml
Verified:
- Setup a new federation with `v0.7.0-beta.1`
- Mixture of docker and start9
- Round trip deposit/withdrawal on mutinynet.
We should bump the version again when we cut `v0.7.0`, however it's useful to bump the tag early since we have users interested in kicking the tires.
=> chore: bump docker iroh version to v0.7.0-beta.1

devimint/src/gatewayd.rs, devimint/src/tests.rs
When running our full suite of upgrade tests, we ran into an issue where LND could not pay the LDK gateway. Upon investigation, it appears that LDK didn't think the channel between itself and LND was active (while LND did), which caused the payment to fail.
Repro:
`env TEST_KINDS=gateway ./scripts/tests/upgrade-test.sh "v0.4.0 v0.4.1 v0.4.2 v0.4.3 v0.4.4 v0.5.0 v0.5.1 v0.6.0 v0.6.1 v0.7.0-beta.0"`
The upgrade tests have changed since we removed CLN. Previously with CLN, when upgrading a gateway there would be no impact on the gateway's channels. But now, since the LN node is embedded, upgrading the gateway causes the channel between LND and LDK to flip flop between active and inactive. This happens each restart, which in the above repro, is a lot of times (this bug does not repro with a …
=> fix: dont restart ldk during gateway upgrade tests

docker/README.md
When a user sets up a new federation with Iroh on Mutinynet, it's useful to provide additional context of how they can continue experimenting. This PR adds steps to deposit funds using mutinynet's faucet.
Additional context: https://discord.com/channels/990354215060795454/990354215878688860/1357792906836050163
=> docs: add steps to deposit on mutinynet for iroh docker

nix/flakebox.nix
`cargo build -p fedimint-gateway-client` fails with `mold: fatal: library not found: z`. This may not be the correct approach but is necessary to unblock the `v0.7.0` release.
Followup issue for ensuring the correct approach when @dpc is back: https://github.com/fedimint/fedimint/issues/7190
=> fix: add zlib to resolve linker errors

nix/flakebox.nix
Backport of #7189 to `releases/v0.7`.
=> [Backport releases/v0.7] fix: add zlib to resolve linker errors

fedimint-core/src/macros.rs
Backport of #7204 to `releases/v0.7`.
=> [Backport releases/v0.7] fix(core): disambiguate macro impl

fedimint-core/src/macros.rs
Backport of #7204 to `releases/v0.6`.
=> [Backport releases/v0.6] fix(core): disambiguate macro impl

docker/deploy-fedimintd/.env, docker/deploy-fedimintd/docker-compose.yaml
Our standard docker env (no iroh) fails to load the UI with a 404 error when we navigate to `https://fedimintd-docker-<peer_id>.dev.fedimint.org`. Inspecting the traefik logs we see
```
root@ubuntu-4gb-fsn1-1:~/fedimint-docker# docker compose logs traefik
traefik  | time="2025-04-10T14:04:53Z" level=info msg="Configuration loaded from flags."
traefik  | time="2025-04-10T14:04:53Z" level=error msg="Could not define the service name for the router: too many services" providerName=docker routerName=fedimintd-ui
traefik  | time="2025-04-10T14:04:53Z" level=error msg="Could not define the service name for the router: too many services" providerName=docker routerName=fedimintd
```
We can resolve this by explicitly linking each router to its corresponding service.
With these changes, I'm able to …
=> fix: explicitly link traefik routers to services

.github/workflows/ci-nix.yml
During the `v0.7.0` release, the macOS build timed out after 90 minutes:
https://github.com/fedimint/fedimint/actions/runs/14391263459/job/40363731901
I suggest we don't attempt to rerun the build solely to publish macOS artifacts unless specifically requested by a user.
=> chore: bump macos release packages timeout

docker/iroh-fedimintd/docker-compose.yaml
=> fix(docker): set default esplora server for mutinynet

fedimintd/src/envs.rs, fedimintd/src/lib.rs
=> cleanup: change to mempool.space for esplora default and mutinynet for only supported signet

devimint/src/external.rs, devimint/src/federation.rs, devimint/src/federation/config.rs, devimint/src/gatewayd.rs, devimint/src/tests.rs, devimint/src/version_constants.rs, gateway/integration_tests/src/main.rs, modules/fedimint-meta-tests/src/bin/meta-module-tests.rs, modules/fedimint-mint-tests/src/bin/mint-module-tests.rs
We no longer test `v0.4` for back-compat or upgrade tests vs master, so we can remove deprecated test logic.
=> chore: cleanup codepaths for version v0.4

fedimint-cli/Cargo.toml, fedimint-client-module/Cargo.toml, fedimint-testing/Cargo.toml, gateway/fedimint-gateway-common/Cargo.toml, gateway/fedimint-gateway-server/Cargo.toml, gateway/fedimint-lightning/Cargo.toml, modules/fedimint-gw-client/Cargo.toml
Working towards https://github.com/fedimint/fedimint/issues/7177.
This diff is straightforward except for [`3a03418` (#7237)](https://github.com/fedimint/fedimint/pull/7237/commits/3a034182d580fc69b6e4bd315744d987982eb9ad), which inspired me to make the initial PR smaller so this is carefully considered. Part of the discussions regarding https://github.com/fedimint/fedimint/pull/7183 included explicitly dropping support for the `bitcoincore-rpc` feature in `fedimint-wallet-client`.
Please voice any concerns if we should keep the `bitcoincore-rpc` in `fedimint-wallet-client` (cc: @m1sterc001guy @elsirion @joschisan).
Once we merge this, I'll have a followup PR that centralizes the remaining dependencies into the root `Cargo.toml`.
=> refactor: reference workspace for package dependencies

modules/fedimint-mint-client/src/lib.rs
Backport of #7229 to `releases/v0.6`.
=> [Backport releases/v0.6] fix(mint-client): recognize balance change on receiving e-cash

modules/fedimint-mint-client/src/lib.rs
Backport of #7229 to `releases/v0.7`.
=> [Backport releases/v0.7] fix(mint-client): recognize balance change on receiving e-cash

Cargo.lock, Cargo.toml, fedimint-cli/Cargo.toml, fedimint-client/Cargo.toml, fedimint-testing/Cargo.toml, gateway/cli/Cargo.toml, gateway/fedimint-lightning/Cargo.toml, gateway/ln-gateway/Cargo.toml, modules/fedimint-wallet-client/Cargo.toml
This deviates from the established pattern of `rc.0` for patch releases since we want to experiment with publishing docker images, so we don't want to make any commitments to backwards compatibility.
=> chore: bump version to v0.6.3-beta.0

.github/workflows/ci-backwards-compatibility.yml, .github/workflows/ci-fuzz.yml, .github/workflows/ci-nix.yml, .github/workflows/daily.yml, .github/workflows/docs.yml, .github/workflows/hourly-run.yml, .github/workflows/upgrade-tests.yml
I'm provisioning an arm64 CI runner in preparation for #3006 but had to deactivate it so it wouldn't receive normal build jobs. This PR specifies x64 (aka x86, amd64) as the runner architecture for all existing workflows running on self-hosted runners.
=> chore(ci): specify architecture for self-hosted runners

devimint/src/federation.rs, fedimint-server/src/config/mod.rs, fedimint-server/src/consensus/mod.rs, fedimint-server/src/lib.rs, fedimint-testing/src/federation.rs, fedimintd/src/fedimintd.rs
To clean this up and consolidate ws api bind and iroh api bind arguments into one argument we need to stop starting the iroh and websocket api in parallel. Hence, when we run on iroh we cannot use the admin setup status command anymore to wait for the dkg to complete and the api to come online as it does not support iroh. Therefore we need to poll the existence  of the invite code for the dkg to complete and join-federation for the api to come online.
=> cleanup: consolidate api binds into one argument

modules/fedimint-mint-client/src/lib.rs
The decoding of this variant has been implemented
for so long, that backward compat. should not be
an issue anymore.
=> desc: encode oob notes in URL safe variant.

modules/fedimint-ln-common/src/lib.rs, modules/fedimint-lnv2-common/src/lib.rs, modules/fedimint-meta-common/src/lib.rs
When working on #7285 I've noticed they are all over the place and look weird.
=> chore: unify fmt::Display for consensus items

.github/workflows/ci-nix.yml
Closes https://github.com/fedimint/fedimint/issues/4488
=> chore(ci): reduce cross timeout back to 20 minutes

Cargo.lock, fedimint-client-wasm/Cargo.toml, fedimint-client-wasm/src/lib.rs, modules/fedimint-wallet-client/src/lib.rs
- Implemented handle_rpc in WalletClientModule to support get_wallet_summary which provides a WalletSummary with all UTXO states.
- Updated wasm-client to route the wallet module RPC calls to WalletClientModule.
=> feat: Added get_wallet_summary to get utxo set in federation

.github/workflows/ci-nix.yml
We're unable to merge the latest `nix flake update` since the dev shell for macos is timing out.
https://github.com/fedimint/fedimint/pull/7313
https://github.com/fedimint/fedimint/actions/runs/14652815200
=> chore(ci): bump macos dev shell timeout

scripts/dev/run-test/fm-run-test
Backward compat tests often fail because there is a lot of them, and each devimint
test has a 1/256 change to trigger the old bug that we've never fixed in old
releases.
It just occurred to me that we can relatively easily detect it and re-run the test
which typically should help.
=> chore(ci): rerun the test if old known gatewayd bug was triggered

fedimint-server/src/consensus/engine.rs, fedimintd/src/lib.rs
In #7330 you can see that when this happens, which often has nothing to do with consensus or aleph,
a long ugly stacktrace is printed, distracting
the user from the fact that probably something else caused the error.
=> fix: improve errors when alephbft tasks are gone

fedimintd/src/lib.rs
Nobody has time to wait 5 minutes for a mutinynet deposit. Related to #7184, which turned out to be a bigger architectural lift than expected.
=> chore: make deposits on test networks faster

fedimint-core/src/task.rs, fedimint-server/src/consensus/engine.rs, fedimintd/src/lib.rs
This reverts changes (only some) of #7304 w.r.t root task handling.
AFAIU, not running it as cancellable task leads to triggering a race between shutdown of alephbft and consensus task, which can lead to spurious errors.
However, I don't understand e2e why would it make the CI more flaky. I can only tell that it would lead to reporting (in logs) errors that it shouldn't.
While at it, it occurred to me that even the old code could (theoretically at least) also report this error, so added a patch for that.
Not sure if this will fix everything, but it should help debugging, and I think it's a correct thing to do. Consensus task is not special, and needs to be cancellable as well if want a unified shutdown procedure that reports all panics.
=>  fix: run main server task a cancellable task 

fedimint-server-core/src/dashboard_ui.rs, fedimint-server-ui/src/dashboard/consensus_explorer.rs, fedimint-server-ui/src/dashboard/general.rs, fedimint-server-ui/src/dashboard/mod.rs, fedimint-server-ui/src/lib.rs, fedimint-server/src/consensus/api.rs, justfile.fedimint.just
Add a simple consensus explorer to the Admin UI.
It's not linked anywhere yet, need to go to `/explorer` manually ATM.
It's really just exposing existing consensus method, and then the LLM generated some UI.
=> chore(ui): consensus explorer

fedimint-api-client/src/query.rs
This fixes a race condition where a response that is fetched twice from the same peer is also counted twice with respect the threshold, hence leading the client to believe a threshold has been established even though we have had the response returned by t - 1 peers. 
In a 3/4 federation you actually get the unique situation where t - 1 <= 2 / n which at least theoretically can break chronologic order of events as observed by the client such as a decreasing block count.
This may have lead to the previously observed unknown block hash / unknown utxo error.
=> fix: fix possible double counting of previous response by the same peer

fedimint-api-client/src/query.rs
Backport of #7329 to `releases/v0.6`.
=> [Backport releases/v0.6] fix: fix possible double counting of previous response by the same peer

fedimint-api-client/src/query.rs
Backport of #7329 to `releases/v0.7`.
=> [Backport releases/v0.7] fix: fix possible double counting of previous response by the same peer

scripts/dev/run-test/fm-run-test
LLM told me `a; exit_code=$?` will work even with `set -e`, but it doesn't. Need to turn off `e` opt for that one command.
Fix #7332
=> fix(ci): re-running test if old known gatewayd bug was triggered

fedimint-api-client/src/query.rs
This is a follow up to https://github.com/fedimint/fedimint/pull/7329.
This test verifies that the query strategy does not count the same response on a retry by a peer twice with respect to the threshold, which was the original issue fixed by the aforementioned pr.
=> fix: add unit test

fedimint-client-module/src/sm/util.rs, modules/fedimint-gw-client/src/lib.rs, modules/fedimint-gwv2-client/src/lib.rs, modules/fedimint-ln-client/src/lib.rs, modules/fedimint-lnv2-client/src/lib.rs, modules/fedimint-mint-client/src/lib.rs, modules/fedimint-wallet-client/src/lib.rs
If the caller side does not have it imported, the macro fails on `.map` method not existing, which is confusing. Neither RA nor rustc seem to see through the macro to suggest it.
=> chore: sm_enum_variant_translation to auto-import MapStateTransitions

fedimint-client/src/db.rs
To be able to split fedimint-client and fedimint-client-module the logical type and db key/value types were split, so there are now two `MetaFieldKey` and `MetaFieldValue`, which is confusing downstream.
The one used for db access can only be used in fedimint-client itself, so should be `pub(crate)`
=> chore(client): make the client db meta key/value private

.github/workflows/ci-nix.yml
Closes https://github.com/fedimint/fedimint/issues/7346
A few days ago (Monday), all merges to `master` were blocked due to macos runners so we removed all macos related jobs. The macos runners appear to be working again so we can reintroduce the macos related jobs. We run the risk of accumulating a bill for GH macos runners, however @elsirion and I synced out-of-band and he'll continue monitoring the usage in the admin dashboard.
In addition to the revert, this PR:
- Reduces the macos dev shell timeout back to 60 minutes (see: https://github.com/fedimint/fedimint/pull/7320 and https://github.com/fedimint/fedimint/pull/7313#issuecomment-2831175000)
- Removes macos cross-compile jobs, since we don't have a clear reason to cross-compile using macos to wasm and multiple android architectures
=> Reintroduce macos builds in CI

.github/workflows/ci-nix.yml
We recently reintroduced the macos jobs in CI (see: https://github.com/fedimint/fedimint/pull/7360) and noticed jobs failing the merge queue due to the dev shell timeout (https://github.com/fedimint/fedimint/pull/7368#issuecomment-2845922764).
=> chore(ci): bump macos dev shell timeout from 60 to 90 mins

fedimint-client/src/client/builder.rs, fedimint-client/src/db.rs
Fix #7367
Tested manually in `devimint-env`, by doing a restore on an old version, then switching to new version:
```
2025-05-01T18:06:07.960066Z  INFO fm::db: Migrating module... kind="fedimint-client" current_db_version=DatabaseVersion(3) target_db_version=DatabaseVersion(4)
2025-05-01T18:06:07.960132Z DEBUG fm::client::db: Migrating old ClientModuleRecovery key module_id=0
2025-05-01T18:06:07.960281Z DEBUG fm::client::db: Migrating old ClientModuleRecovery key module_id=1
2025-05-01T18:06:07.960384Z DEBUG fm::client::db: Migrating old ClientModuleRecovery key module_id=2
2025-05-01T18:06:07.960461Z DEBUG fm::client::db: Migrating old ClientModuleRecovery key module_id=3
2025-05-01T18:06:07.960537Z DEBUG fm::client::db: Migrating old ClientModuleRecovery key module_id=4 …
```
=> fix(client): prefix reuse

gateway/fedimint-lightning/src/lnd.rs
We hit an underflow bug in the gateway https://github.com/fedimint/fedimint/actions/runs/14711340067/job/41284259447#step:6:4437
It looks as though unsettled and pending might overflow and end up being greater than total inbound/outbound. For our case, it doesn't matter, this is just displaying the balances for the operator. Using `saturating_sub` here so that it rounds to 0 is fine.
=> fix: use saturating sub when calculating LND liquidity

.github/workflows/linkcheck.yml
* Use GH token when running on master, so that we don't get rate-limited
* Accept 429 status code (rate limited) such that on PRs where the secret isn't available we have green CI
Fixes #7375
=> fix(ci): don't fail on GitHub rate limitng requests

.github/workflows/linkcheck.yml, flake.nix
Master link check CI is still failing, I tried:
* Updating `lychee` and pinning it to a more predictable version
* Passing the GH token as an argument instead of a env var
* Not caching the 429 error codes but allow them even on master
The last approach made it kinda work: we cache all successful fetches, so each run covers some more github URLs before hitting the rate limit.
=> fix(ci): don't pass gh token to lychee, just cache

.taplo.toml
If you're using taplo (LSP for Toml files), this will make it automatically sort the keys, which is what we want.
=> chore: add `.taplo.toml`

.github/workflows/ci-nix.yml
Fixes https://github.com/fedimint/fedimint/issues/7394
`env: IS_PRERELEASE` evaluates to a string, which is truthy for any non-empty string including `"false"`. This caused the body of a normal release to include the `PRERELEASE_MEASSGE`. We can cast the `"false"` string to a bool using `fromJSON`.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#fromjson
=> fix(ci): cast `IS_PRERELEASE` to bool using `fromJSON`

.github/workflows/ci-nix.yml
Debugging related to https://github.com/fedimint/fedimint/issues/7371
Referencing this [blog post](https://tech.aufomm.com/how-to-build-multi-arch-docker-image-on-nixos/?utm_source=chatgpt.com#Tag-multi-arch), it looks like we need to add `docker manifest annotate` to unify multi arch images under a single tag.
This is untested since it's tricky to push containers from a PR branch. I think it will be easiest to iterate by merging to `master` and checking that the multi arch images are correctly annotated in Docker Hub.
=> chore(ci): add annotations for multi arch images in docker manifest

.github/workflows/ci-backwards-compatibility.yml, .github/workflows/upgrade-tests.yml, justfile.fedimint.just
We released `v0.5.2`, `v0.6.3`, and `v0.7.1` patch releases so we can now bump the versions we test against in CI.
Related issues:
https://github.com/fedimint/fedimint/issues/7372
https://github.com/fedimint/fedimint/issues/7243
https://github.com/fedimint/fedimint/issues/7369
=> chore(ci): bump versions for back-compat/upgrade tests

fedimint-core/src/util/backoff_util.rs
Under (simulated) heavy load, tests are failing due to too short retries.
=> chore(tests): increase timeout on retries

devimint/src/vars.rs
This flag is one of the things triggering debug-only behavior inside Fedimint.
Seems like it might not be set currently for `fedimintd` which in certain situation might lead to prod-like settings in tests.
=> chore: Set `FM_IN_DEVIMINT` for `fedimintd` as well

fedimint-client-wasm/src/lib.rs
ref https://github.com/fedimint/fedimint-web-sdk/issues/110
This PR adds a new `preview_federation` method to the `Client` struct in `fedimint-client`, enabling users to fetch and preview a federation’s configuration before joining it.
=> feat: Added previewFederation

fedimint-api-client/src/api/mod.rs, fedimint-server/src/consensus/engine.rs
Backport of #7419 to `releases/v0.7`.
=> [Backport releases/v0.7] chore: don't panic in `ClientConnection::connection`

fedimint-core/src/core/backup.rs
Ain't nobody wants to see all these bytes of `payload` in their logs ...
=> chore(core): better `fmt::Debug` for `BackupRequest`

docker/iroh-fedimintd/docker-compose.yaml, fedimint-startos/docker_entrypoint.sh, nix/flakebox.nix
It also can't handle `1` now. Must be `true`. :/
=> fix: FM_FORCE_IROH was renamed to FM_ENABLE_IROH

Cargo.lock, Cargo.toml, fedimint-server/Cargo.toml, fedimint-server/src/config/mod.rs, fedimint-server/src/consensus/mod.rs, fedimint-server/src/lib.rs, fedimint-server/src/net/p2p_connector.rs, fedimint-testing/src/federation.rs, fedimintd/src/lib.rs
Allows using custom relay settings in `fedimintd` via command line arguments.
Taken and fixed second commit from #7309 , skipped removing connectivity overrides, as we're going to need them for the tests to work offline.
=> chore: iroh dns and relay env variables

gateway/fedimint-gateway-server/src/lib.rs
Fixes: https://github.com/fedimint/fedimint/issues/6519
In LNv1, gateway will un-announce itself from all federations when it is disconnected from its Lightning node so that clients don't accidentally use it while the LN node is offline.
=> fix: LNv1 unannounce when LN node is disconnected

modules/fedimint-lnv2-client/src/lib.rs
I want to be able to show users the fees they will be charged up front in LNv2. This is currently very difficult. Making `select_gateway` public will make this much easier.
=> chore: LNv2 make select_gateway public

modules/fedimint-lnv2-client/src/lib.rs
Backport of #7454 to `releases/v0.7`.
=> [Backport releases/v0.7] chore: LNv2 make select_gateway public

modules/fedimint-wallet-client/src/lib.rs
Backport of #7449 to `releases/v0.7`.
=> [Backport releases/v0.7] fix: unnecessary `Result` in `list_peg_in_tweak_idxes`

modules/fedimint-wallet-client/src/lib.rs
Backport of #7449 to `releases/v0.6`.
=> [Backport releases/v0.6] fix: unnecessary `Result` in `list_peg_in_tweak_idxes`

docs/meta_fields/recurringd_api.md
Recurring payment support in Fedimint requires yet another service: `recurringd`. Since instances only support specific federations for now, having a discovery mechanism is useful. Meta fields seem a good place for it.
Thx @maan2003 for the suggestion :)
=> feat: define recurringd_api meta field

fedimint-rocksdb/src/db_locked.rs, fedimint-rocksdb/src/lib.rs
In an expression:
```
xyz().bar(baz());
```
it is not clear that `baz` has to run after `xyz`, which I suspect might be the reason for locking failures, like:
https://github.com/fedimint/fedimint/actions/runs/15007989771/job/42386156342
Best not to depend on it, but use a lambda.
=> fix: order of locking not immediately clear

scripts/dev/run-test/fm-run-test
The LDK node log name changed when we merged https://github.com/fedimint/fedimint/pull/7389
```
cat: '/build/fm-gw_liquidity-FDUV/devimint-*/gatewayd-ldk-0/ldk_node/logs/ldk_node_latest.log': No such file or directory
```
This PR fixes LDK node's log name when it prints to CI. It will help us debug https://github.com/fedimint/fedimint/issues/7476
=> chore: change ldk-node-0 log name

devimint/src/tests.rs, fedimint-api-client/src/lib.rs, fedimint-cli/src/lib.rs, fedimint-client-wasm/src/lib.rs, fedimint-client/src/api_announcements.rs, fedimint-client/src/client.rs, fedimint-client/src/client/builder.rs, fedimint-client/src/lib.rs, fedimint-load-test-tool/src/common.rs, fedimint-recurringd/src/lib.rs, fedimint-testing/src/federation.rs, fedimint-wasm-tests/src/lib.rs, gateway/fedimint-gateway-server/src/client.rs
Fix #6976
**Edit**: Argh, the whole thing does not work, because we already exposed federation_id hashing into secret to the outside of join, and for that client needs federation_id, and for that they need to download the config.
**Edit**: OK, fixed that, but... Argh, as we need to do more stuff on join, we can't have it repeated over and over everywhere, so we need to fold it into client.  But that doesn't work with preview ...
**Edit**: Well, I had to refactor even more things. :shrug: . But I kind of like this explicit preview step now.
=> fix(client): fetch api announcements on join

docker/deploy-fedimintd/.env
We released `v0.7.2` so we can bump the referenced tag for docker deployments (see: https://github.com/fedimint/fedimint/issues/7441)
=> [releases/v0.7] chore: bump docker tag to v0.7.2

flake.nix, nix/pkgs/wild.nix
I've tried #6850 with a newest version of wild, and it is 20% faster on incremental builds, which is a nice improvement, so why not?
```
> echo $CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS
-C link-arg=-fuse-ld=mold -C link-arg=-Wl,--compress-debug-sections=zlib
> env BENCH_COMP_SKIP_PROFILE=release just bench-compilation
...
total    user     sys
Full  check   debug:   52.78  854.30  125.46
Incr  check   debug:    4.21    8.25    7.88
Full  build   debug:   91.71 1712.73  180.90
Incr  build   debug:   10.27   28.92   23.64
> echo $CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS
-C link-arg=--ld-path=wild
> just bench-compilation-quick-incr
total    user     sys
Incr  check   debug:    5.78   12.22   21.79
> env BENCH_COMP_SKIP_PROFILE=release just bench-compilation
total    user …
```
=> chore: try wild linker (only in dev shell)

fedimint-client-wasm/Cargo.toml, nix/flakebox.nix
ref: https://github.com/fedimint/fedimint/pull/6586
cc: @maan2003 
* sets even more aggressive flag to optimize for size (`z` saves about 7% in bundle size compared to `s`)
* Adds additional wasm-pack target for web sdk (web)
```sh
❯ ls -la result/share/fedimint-client-wasm
total 8080
dr-xr-xr-x 8 alex nixbld     256 Dec 31  1969 .
dr-xr-xr-x 4 alex nixbld     128 Dec 31  1969 ..
-r--r--r-- 1 alex nixbld    2153 Dec 31  1969 fedimint_client_wasm.d.ts
-r--r--r-- 1 alex nixbld     212 Dec 31  1969 fedimint_client_wasm.js
-r--r--r-- 1 alex nixbld   49803 Dec 31  1969 fedimint_client_wasm_bg.js
-r--r--r-- 1 alex nixbld 8197192 Dec 31  1969 fedimint_client_wasm_bg.wasm
-r--r--r-- 1 alex nixbld    4106 Dec 31  1969 fedimint_client_wasm_bg.wasm.d.ts
-r--r--r-- 1 alex nixbld     601 Dec 31  1969 …
```
=> chore: further optimize wasm & add additional target

devimint/src/version_constants.rs, modules/fedimint-wallet-client/src/client_db.rs, modules/fedimint-wallet-client/src/lib.rs, modules/fedimint-wallet-client/src/pegin_monitor.rs, modules/fedimint-wallet-tests/src/bin/wallet-module-tests.rs, modules/fedimint-wallet-tests/tests/tests.rs
Claiming on-chain deposits worth less than the fee that needs to be paid to the federation for them doesn't make economic sense and can lead to panics if the wallet doesn't have enough funds and losing money otherwise. Let's not do that.
Great find @cvaz21 and @maan2003!
=> fix(wallet-client): don't claim on-chain deposits smaller than the fee

flake.nix
Commands like `cargo nextest run` fail with:
```
error: creating test list failed
Caused by:
for `fedimint-dummy-tests::fedimint_dummy_tests`, command `/home/dpc/lab/fedimint/fedimint/target-nix/debug/deps/fedimint_dummy_tests-e1ac9f7caff
f2a1b --list --format terse` exited with code 127
--- stdout:
--- stderr:
/home/dpc/lab/fedimint/fedimint/target-nix/debug/deps/fedimint_dummy_tests-e1ac9f7cafff2a1b: error while loading shared libraries: libstdc++.so.6:
cannot open shared object file: No such file or directory
---
```
and there can be lots of reasons for it, possibly related to Nix wrapping described in: https://github.com/davidlattimore/wild?tab=readme-ov-file#nix
which compounds with flakebox complexity, etc. which I don't have time to tackle now.
=> chore: revert wild in the dev shell

devimint/src/version_constants.rs, modules/fedimint-wallet-tests/src/bin/wallet-module-tests.rs
Re: https://github.com/fedimint/fedimint/pull/7514#discussion_r2142536094
=> fix: use v0.7.2 as threshold for testing dust in circular deposit test

Cargo.lock, Cargo.toml
Title says it all. No code changes needed. But since v0.6.1 uses `bitcoin` v0.32.6`, we need to bump that from v0.32.5 as well.
=> chore(deps): bump ldk-node to v0.6.1

Cargo.toml
This should prevent dependabot etc. from trying to upgrade them and make it explicit that they must not change.
=> chore: pin stable iroh dependencies

scripts/tests/test-ci-all.sh
This test became very flaky and it's been like that for a while.
Re #7546
=> chore: disable flaky gw_liquidity_test

.github/workflows/ci-nix.yml
Do it in MQ only. It's just waaay too slow.
=> chore: don't build aarch64-linux container in the PRs

.github/workflows/ci-nix.yml
The containers job isn't completing within 60 minutes vs master for `aarch64-linux`. We're able to complete in a short period of time with the CI profile (see: https://github.com/fedimint/fedimint/pull/7556), but it takes much longer vs master. As a temporary workaround, let's try bumping from 60 to 120 minutes.
Using https://github.com/fedimint/fedimint/issues/7561 to followup with a better long-term fix.
https://github.com/fedimint/fedimint/actions/runs/16064288213/job/45345062320
=> chore: bump containers timeout from 60 to 120m

.github/workflows/ci-nix.yml
After cutting the `v0.8.0-beta.0` tag the release job fails due to the `gatewayd` closure size.
```
gatewayd's Nix closure size seems too big: 212189616
```
https://github.com/fedimint/fedimint/actions/runs/16078077766/job/45377647469#step:6:143
This approach kicks the can by bumping the closure size limit (we set the can kicking precedence in https://github.com/fedimint/fedimint/pull/7196). Another approach is to modify debug symbols, but I don't think it's worth degrading debug symbols if we only need to slightly increase the closure limit. Please let me know if you see any better approaches.
=> chore(ci): bump nix closure size limit

Cargo.lock, Cargo.toml
Working towards https://github.com/fedimint/fedimint/issues/7560
We branched off master with `releases/v0.8` so we can bump master to `v0.9.0-alpha`.
=> chore: bump master to 0.9.0-alpha

.github/workflows/ci-nix.yml
Closes https://github.com/fedimint/fedimint/issues/7570
=> [Backport v0.8] chore(ci): bump nix closure size limit

fedimint-core/src/iroh_prod.rs
Backport of #7578 to `releases/v0.8`.
=> [Backport releases/v0.8] fix: use correct iroh pkarr URL

fedimint-recurringd/src/main.rs, misc/mprocs.yaml
Adds recurringd to the mprocs logs and a log statement printing the API endpoint for recurringd
=> fix: recurringd in mprocs and log printing api endpoint

fedimint-server-ui/src/dashboard/invite.rs
Adds a link to the dashboard to Fedimint Observer for mint operators to announce their federation on Nostr.
=> feat: announce on nostr link

Cargo.lock, fedimint-core/Cargo.toml, fedimint-core/src/config.rs, fedimint-server/src/config/mod.rs
While the function is being exported, that looks more like an accident from a time when the function was in use in fedimint itself.
I was looking at https://github.com/fedimint/fedimint/pull/7584#event-18597347482 to determine if there was any consensus usage of `bincode` and noticed 1 of 2 occurrences isn't relevant anymore.
=> chore: remove dead code `serde_binary_human_readable`

Cargo.lock, modules/fedimint-ln-client/Cargo.toml, modules/fedimint-ln-client/src/recurring/mod.rs
Adds a new event for an invoice having been created for an LNURL the client created. It only signals the invoice was created, not necessarily paid.
Fixes #7474
=> feat: add recurring invoice created event

fedimint-api-client/src/api/iroh.rs, fedimint-core/src/iroh_prod.rs, fedimint-server/src/net/p2p_connector.rs
@bradleystachurski [noticed major performance degradation](https://github.com/fedimint/fedimint/issues/7580#issuecomment-3070140276) when using our self-hosted discovery infrastructure (even after fixing initial mis-configuration). There might be a bug in iroh or further problems in our infra, either way we'd rather not block the release given [iroh isn't rug-pulling us anytime soon](https://www.iroh.computer/blog/iroh-0-90-the-canary-series).
This should be fixed asap after the release though.
=> chore: remove self-hosted iroh DNS infrastructure

devimint/src/vars.rs, fedimint-server-bitcoin-rpc/src/bitcoind.rs, fedimint-server-bitcoin-rpc/src/lib.rs, fedimint-testing/src/fixtures.rs, fedimintd/src/envs.rs, fedimintd/src/lib.rs
Alternative to https://github.com/fedimint/fedimint/pull/7601
Moves the bitcoind username and password from the URL into separate environment variables, so that they are not URL encoded, which leads to connection issues.
=> fix: use separate environment variables for bitcoind username and password

gateway/integration_tests/src/main.rs, modules/fedimint-lnv2-common/src/gateway_api.rs
Backport of #7240 to `releases/v0.8`.
=> [Backport releases/v0.8] feat: lower default gateway LNv2 fees

fedimint-server-ui/src/dashboard/bitcoin.rs
The guardian UI shows the sync percentage is 1.0% when it's 100%. This change correctly displays the sync percentage. The bitcoin rpc returns the node's estimated chain sync percentage as a float between 0.0 and 1.0, so IMO the appropriate fix is to change at the UI instead of modifying the rpc.
https://github.com/fedimint/fedimint/blob/deace979529d33f1ee9872f6c8d09330e652c2bb/fedimint-server-core/src/bitcoin_rpc.rs#L168-L170
**Guardian dashboard for fully synced node**
=> fix: correct how the ui displays sync percentage

fedimint-server-ui/src/dashboard/bitcoin.rs
Backport of #7614 to `releases/v0.8`.
=> [Backport releases/v0.8] fix: correct how the ui displays sync percentage

.taplo.toml
When working on release branches and compiling locally we'll have build artifacts related to that release in `target-nix`. If you switch to a different version (e.g. `master`), the git pre-commit hook will fail since older versions might not have the correct formatting.
```
❯ git commit
INFO taplo:format_files:load_config: found configuration file path="/home/stachurski/code/fedimint/.taplo.toml"
INFO taplo:format_files:collect_files: found files total=143 excluded=0 cwd="/home/stachurski/code/fedimint"
ERROR taplo:format_files: the file is not properly formatted path="/home/stachurski/code/fedimint/target-nix/package/devimint-0.8.0/Cargo.toml"
```
This PR updates `.taplo.toml` to ignore the formatting in any `Cargo.toml` files in `target*`.
=> fix: exclude `target*` dirs from taplo

docs/meta_fields/README.md, docs/meta_fields/lnaddress_api.md
Similar to https://github.com/fedimint/fedimint/pull/7539, but adding a meta field for a Lightning Address server API.
=> docs: add lnaddress_api to meta fields

fedimint-client-module/src/api.rs
This is a potentially high-volume event and was
not supposed to be persisted at all.
=> fix: ApiCallDone should not be persisted

fedimint-client-module/src/api.rs
Backport of #7641 to `releases/v0.8`.
=> [Backport releases/v0.8] fix: ApiCallDone should not be persisted

fedimint-client/src/client.rs, modules/fedimint-wallet-client/src/api.rs, modules/fedimint-wallet-client/src/lib.rs
Implemented `block_count` and `session_count` in client rpc for showing it in wallet guardians details
=> feat: Added block count and session count in client rpc

flake.lock, flake.nix
Mostly to get rid of annoying nix/crane warning about `stdenv`, see https://github.com/rustshop/flakebox/commit/18572519afc40cd1e5cab03f9dabe9c53dbc5034
=> chore: update flakebox

gateway/integration_tests/src/main.rs, scripts/tests/test-ci-all.sh
Builds on: https://github.com/fedimint/fedimint/pull/7672
Fixes: https://github.com/fedimint/fedimint/issues/7546
This PR removes the traditionally flaky checks where were verify amounts and mine a bunch of blocks in the gateway liquidity test. Instead, we just verify that `send_onchain` creates a bitcoin transaction (and bitcoind sees it). We also verify that `close_all_channels` changes the status of the channels to not-active.
Seems to be more consistent for me, I will monitor CI closer when this merges.
=> fix: fix and re-enable gateway liquidity test

devimint/src/federation.rs, devimint/src/gatewayd.rs, devimint/src/tests.rs, devimint/src/version_constants.rs, gateway/integration_tests/src/main.rs, modules/fedimint-wallet-tests/src/bin/wallet-module-tests.rs
Followup to https://github.com/fedimint/fedimint/issues/7560
After releasing `v0.8.0`, we dropped support for `v0.5` and older. We already updated the versions we test in CI with https://github.com/fedimint/fedimint/pull/7634, so we can now cleanup the codepaths for testing deprecated versions.
=> chore: rm deprecated version codepaths

Cargo.lock, Cargo.toml
Re #7628
Switch ldk-node crate to our temporary fork [fedimint-ldk-node](https://crates.io/crates/fedimint-ldk-node) v0.6.1, which is just [ldk-node v0.6.1 with rusqlite update](https://github.com/fedimint/ldk-node/commits/dpc/jj-rskqnlzvywls/) that can't be landed into mainstream ATM.
This unblocks us to upgrade arti-client to newest version via rusqlite unification.
We'll have to port fedimint-ldk-node changes until ldk-node updates rusqlite, but the changes are tiny, so it's not painful, and updated to ldk-node are not all that common.
=> update arti and ldk-node (to our temporary fork)

docker/README.md
We've spoken out-of-band about our support boundary for docker compose. We should make that explicit.
=> docs(docker): add scope of support warning for docker compose usage

docker/docker-compose.yaml
Re: https://github.com/fedimint/fedimint/issues/7665
=> chore: bump docker compose fedimintd version to v0.8.1

fedimint-startos/Dockerfile, fedimint-startos/manifest.yaml
Re: https://github.com/fedimint/fedimint/issues/7665
Bumping the Start9 package to `v0.8.1`. This was tested as part of the release process and the `fedimintd.s9pk` generated from these changes is included in the release artifacts.
=> chore: bump start9 to v0.8.1

fedimint-startos/Dockerfile, fedimint-startos/manifest.yaml
Backport of #7711 to `releases/v0.8`.
=> [Backport releases/v0.8] chore: bump start9 to v0.8.1

fedimint-server-core/src/dashboard_ui.rs, fedimint-server-ui/src/dashboard/consensus_explorer.rs, fedimint-server-ui/src/dashboard/mod.rs, fedimint-server/src/consensus/api.rs
It's useful to know at a glance what version you're running from the guardian dashboard. This adds the version tag to the dashboard below the header.
=> feat: add fedimintd version tag to guardian dashboard

fedimintd/src/lib.rs, modules/fedimint-lnv2-tests/bin/tests.rs
As some operators might take issue with taking a relative fee and we do not allow for its configuration yet we set it to zero for now.
=> chore: set lnv2 relative in prod to zero until we make it configurable

Cargo.toml
These changes cut memory usage like 8 times, and built time by at least 2.
=> chore: use thin (instead of fat) LTO in release build

devimint/src/tests.rs, fedimint-core/src/envs.rs, fedimintd/src/lib.rs, modules/fedimint-lnv2-tests/bin/tests.rs
The base fee is necessary to prevent excessive use of ecash only transactions to exhaust the guardians disk space. 100msat per ecash output / input roughly equals 1 msat per byte hence 1 million sats per gigabyte of disk space. Since ecash transactions are quite large and need to be downloaded by every user in recovery a gigabyte of additional transaction data is a considerable cost to the system.
This is a follow up to: https://github.com/fedimint/fedimint/pull/7725. The previous pr enabled the fee only in devimint testing via an environment variable called FM_ENABLE_MINT_BASE_FEES_ENV. We invert this, enable the base fee of 100msat by default and allow for disabling it through FM_DISABLE_MINT_BASE_FEES_ENV. This is used in the load test tool test which is the only test that has not been …
=> fix: enable mint base fees by default

fedimint-startos/manifest.yaml
The Start9 team noticed the wrapper repo link is incorrect. This updates the link and bumps the package version. I've verified the `fedimintd.s9pk` generated with these changes works and you can successfully upgrade from the previous package version.
Once this merges, I'm going to update the `v0.8.1` release assets with `fedimintd.s9pk` generated with these changes.
=> chore: update wrapper-repo docs for start9

fedimint-startos/manifest.yaml
Backport of #7754 to `releases/v0.8`.
=> [Backport releases/v0.8] chore: update wrapper-repo docs for start9

devimint/src/federation/config.rs, devimint/src/tests.rs, fedimint-api-client/src/api/global_api/with_cache.rs, fedimint-api-client/src/api/mod.rs, fedimint-cli/src/lib.rs, fedimint-core/src/admin_client.rs, fedimint-core/src/envs.rs, fedimint-core/src/setup_code.rs, fedimint-server-core/src/init.rs, fedimint-server-core/src/setup_ui.rs, fedimint-server-ui/src/setup.rs, fedimint-server/src/config/mod.rs, fedimint-server/src/config/setup.rs, fedimint-testing-core/src/config.rs, fedimintd/src/lib.rs, modules/fedimint-dummy-server/src/lib.rs, modules/fedimint-empty-server/src/lib.rs, modules/fedimint-ln-server/src/lib.rs, modules/fedimint-lnv2-common/src/config.rs, modules/fedimint-lnv2-server/src/lib.rs, modules/fedimint-lnv2-tests/bin/tests.rs, modules/fedimint-meta-server/src/lib.rs, modules/fedimint-mint-common/src/config.rs, modules/fedimint-mint-server/src/lib.rs, modules/fedimint-mint-server/src/test.rs, modules/fedimint-mint-tests/tests/tests.rs, modules/fedimint-unknown-server/src/lib.rs, modules/fedimint-wallet-server/src/lib.rs, modules/fedimint-wallet-tests/tests/tests.rs
As requested in the Monday call we make the mint ecash note base fee of 100msat configurable by the leading guardian. For consistency we also toggle the 1sat per contract lnv2 base fee as well to achieve true zero fee operation.
Right now we default to enabling the base fee so it needs to be manually disabled by the setup leader by setting a checkmark in the UI. Under the checkmark we render and explainer with the implications of disabling the base fee.
=> feat: make absolute base fees configurable by the leading guardian

Cargo.toml
Backport of #7743 to `releases/v0.8`.
=> [Backport releases/v0.8] chore: use thin (instead of fat) LTO in release build

fedimint-server-ui/src/setup.rs
Checking a box to "disable" something is confusing. Checked box should mean "enabled". I generally think that it would have been best to avoid `disabled_` (as a negation) everywhere, but in this PR I only change it where it matters - in the UI, as a part of #7771 .
=> fix(ui): "disable" checkbox is confusing

.github/workflows/ci-nix.yml
`v0.8.2-beta.0` failed with
```
gatewayd's Nix closure size: 262335208
gatewayd's Nix closure size seems too big: 262335208
Error: Process completed with exit code 1.
```
https://github.com/fedimint/fedimint/actions/runs/18011155168/job/51243898889#step:6:1068
That's quite the jump. The culprit is https://github.com/fedimint/fedimint/commit/aeae5a1871 along with before/after stats
```
Binary                       Fat(MB)   Thin(MB)        +MB        +MB        %
narSize    narSize    narSize    closure increase
------------------------- ---------- ---------- ---------- ---------- --------
fedimintd                        161        202        +41        +41      25%
fedimint-cli                     159        200        +41        +41      25%
fedimint-dbtool                  107 …
```
=> chore(ci): bump nix closure size limit to 280MB

fedimint-client/src/client.rs, fedimint-client/src/client/builder.rs
Block indefinitely client initialization if the initial api version can't be discovered.
Seems like it's preferable than just initializing client with disabled modules.
=> chore: keep retrying if the client can't negotiate initial api version

devimint/src/gatewayd.rs, devimint/src/vars.rs, gateway/fedimint-gateway-server/src/envs.rs
`FM_GATEWAY_LIGHTNING_MODULE_MODE` no longer does anything. There were a few spots in devimint that were not cleaned up originally.
All occurrences can be removed once `v0.9` is no longer supported.
=> refactor: cleanup unused lightning module mode env var

fedimint-api-client/src/api/iroh.rs
On top of #7785 
These are actually costly, as they might require new relay connections, which can lead to rate limiting.
We are already doing reconnections and connection reuse on the api level, but these are not reused between preview and join, which seems to be causing rate limiting on relays for users, as public relays might be quite stingy with limits.
After #7785 we do preserve the connector itself between preview and join, etc. so reusing connections at the connector level will reuse them preview and join.
Things to consider:
* These do not use any backoff - it is already done at the api layer, where it seems to belong better.
* jsonrpsee_core::Client can be shared between threads with `Arc<Client> and also has ability to check if the Client is connected, so could apply the same …
=>  chore(client): Iroh connection reuse 

Cargo.toml, fedimint-core/src/rustls.rs
Backport of #7813 to `releases/v0.9`.
=> [Backport releases/v0.9] fix: enable aws_lc_rs crypto provider for tokio-rustls

fedimint-api-client/src/api/mod.rs
If there are any requestors that wanted to make a connection and we were not able to, it's better to tell them right away, instead of waiting the whole backoff time. Some of them might actually not immediately retry.
=> fix(client): disconnect before going to sleep

Cargo.lock
Backport of #7815 to `releases/v0.9`.
=> [Backport releases/v0.9] chore: update pkarr dependency

fedimint-api-client/src/api/mod.rs
Backport of #7808 to `releases/v0.9`.
=> [Backport releases/v0.9] fix(client): disconnect before going to sleep
